import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'ar',
  googleSearch: [
    {
      id: 'g-ar-01',
      name: 'منصة AI API',
      objective: 'دفع التسجيلات في الباقة المجانية لـ AI API',
      budget: '€500/شهرياً',
      adGroups: [
        {
          id: 'g-ar-01-brand',
          name: 'العلامة التجارية',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'منصة ai empire'],
          ads: [
            { id: 'g-ar-01-brand-1', headline: 'AI Empire — منصة AI API الموحدة', description: 'استخدم Groq وGemini من خلال API واحد. باقة مجانية متاحة، لا حاجة لبطاقة ائتمان. تكامل في 5 دقائق.', cta: 'جرّب مجاناً' },
            { id: 'g-ar-01-brand-2', headline: 'AI Empire — بوابة API الخاص بك', description: 'API واحد، نماذج AI متعددة. Groq + Gemini. رصيد مجاني عند التسجيل. مكتبات JavaScript وPython مضمنة.', cta: 'احصل على مفتاح API' },
            { id: 'g-ar-01-brand-3', headline: 'AI Empire — ابنِ بالـ AI اليوم', description: 'API جاهز للإنتاج. Groq للسرعة، Gemini للقدرة. باقة مجانية، تسعير حسب الاستخدام.', cta: 'ابدأ الآن' },
          ],
        },
        {
          id: 'g-ar-01-competitor',
          name: 'المنافسون',
          keywords: ['بديل openai', 'بديل groq api', 'ai api أرخص', 'غلاف gemini api', 'مقارنة ai api'],
          ads: [
            { id: 'g-ar-01-comp-1', headline: 'AI API ميسور التكلفة — وفّر مقارنة بـ OpenAI', description: 'ذات الجودة العالية بتكلفة أقل. Groq + Gemini موحدان. باقة مجانية مع 100 رصيد. انتقل في دقائق.', cta: 'قارن الأسعار' },
            { id: 'g-ar-01-comp-2', headline: 'بديل OpenAI — AI Empire', description: 'تبحث عن API AI فعال من حيث التكلفة؟ يجمع AI Empire Groq وGemini في نقطة نهاية واحدة. ابدأ مجاناً.', cta: 'اطّلع على الخطط' },
            { id: 'g-ar-01-comp-3', headline: 'AI API — أقل بـ 70% من OpenAI', description: 'احصل على نتائج بجودة GPT مع Groq وGemini. API موحد. باقة مجانية. بدون ارتباط بالمزود.', cta: 'ابدأ مجاناً' },
          ],
        },
        {
          id: 'g-ar-01-generic',
          name: 'عام',
          keywords: ['ai api', 'api الذكاء الاصطناعي', 'groq api', 'gemini api', 'ai للمطورين', 'ai api مجاني'],
          ads: [
            { id: 'g-ar-01-gen-1', headline: 'AI API للمطورين — باقة مجانية', description: 'Groq + Gemini من خلال API واحد. رصيد مجاني عند التسجيل. التوثيقات والأمثلة ومكتبات البرمجة مضمنة.', cta: 'اطّلع على التوثيقات' },
            { id: 'g-ar-01-gen-2', headline: 'أدمج AI في تطبيقك — إعداد في 5 دقائق', description: 'API واحد لـ Groq وGemini. باقة مجانية متاحة. فوترة Stripe. توثيقات كاملة.', cta: 'ابدأ الآن' },
            { id: 'g-ar-01-gen-3', headline: 'API AI — Groq وGemini معاً', description: 'نقطة نهاية واحدة لعدة نماذج AI. ابدأ مجاناً، ادفع حسب الاستخدام. جاهز للإنتاج.', cta: 'استكشف API' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-02',
      name: 'قوالب Next.js SaaS',
      objective: 'دفع مبيعات القوالب',
      budget: '€400/شهرياً',
      adGroups: [
        {
          id: 'g-ar-02-brand',
          name: 'العلامة التجارية',
          keywords: ['قوالب ai empire', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-ar-02-brand-1', headline: 'AI Empire — قوالب SaaS لـ Next.js 14', description: 'قوالب جاهزة للإنتاج مع تكامل AI. NeuraStore وNeuraBlog وNeuraPortfolio. من €19.', cta: 'شاهد القوالب' },
            { id: 'g-ar-02-brand-2', headline: 'NeuraStore وNeuraBlog من AI Empire', description: 'قوالب Next.js 14 احترافية مع Stripe والمصادقة والـ AI. انشر في دقائق.', cta: 'عرض القوالب' },
            { id: 'g-ar-02-brand-3', headline: 'قوالب AI Empire — أطلق SaaS الخاص بك', description: '6 قوالب مميزة. Next.js 14 وTailwind وStripe وAPI AI. من €19 إلى حزمة €299.', cta: 'تصفح القوالب' },
          ],
        },
        {
          id: 'g-ar-02-competitor',
          name: 'المنافسون',
          keywords: ['قالب saas', 'قالب next.js', 'قالب react saas', 'طقم بدء saas', 'قالب nextjs للتجارة الإلكترونية'],
          ads: [
            { id: 'g-ar-02-comp-1', headline: 'قالب Next.js SaaS — AI مدمج', description: 'على عكس القوالب النموذجية، تتضمن قوالب AI Empire API AI وStripe والمصادقة. جاهز للنشر.', cta: 'قارن القوالب' },
            { id: 'g-ar-02-comp-2', headline: 'أفضل من قالب SaaS النموذجي', description: 'قوالب AI Empire: تصميم احترافي، تكامل AI، فوترة Stripe. ليست مجرد كود مبدئي.', cta: 'شاهد الفرق' },
            { id: 'g-ar-02-comp-3', headline: 'قالب Next.js 14 — جاهز للتكامل الكامل', description: 'قوالب تتضمن كل شيء: واجهة المستخدم والـ API والمصادقة والمدفوعات والـ AI. انشر الآن.', cta: 'شاهد القوالب' },
          ],
        },
        {
          id: 'g-ar-02-generic',
          name: 'عام',
          keywords: ['قالب saas', 'قالب nextjs 14', 'قالب react', 'صفحة هبوط saas', 'قالب لـ saas', 'بناء saas بسرعة'],
          ads: [
            { id: 'g-ar-02-gen-1', headline: 'قوالب SaaS — أطلق في أيام لا في أشهر', description: 'قوالب Next.js 14 مع المصادقة والـ AI والـ Stripe. من €19.', cta: 'ابدأ الآن' },
            { id: 'g-ar-02-gen-2', headline: 'ابنِ SaaS بـ Next.js 14', description: 'قوالب جاهزة للإنتاج. فوترة Stripe والمصادقة وAPI AI ولوحة الإدارة.', cta: 'استكشف القوالب' },
            { id: 'g-ar-02-gen-3', headline: 'قوالب Next.js 14 للتجارة الإلكترونية والمدونة', description: 'قوالب احترافية بتصميم عصري. متجاوبة ووضع مظلم ومحسّنة لمحركات البحث. من €19.', cta: 'تسوّق القوالب' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-03',
      name: 'تكامل AI',
      objective: 'استقطاب المطورين بحاجة لتكامل AI',
      budget: '€350/شهرياً',
      adGroups: [
        {
          id: 'g-ar-03-brand',
          name: 'العلامة التجارية',
          keywords: ['تكامل ai empire', 'توثيقات ai empire', 'sdk ai empire', 'توثيقات api ai empire'],
          ads: [
            { id: 'g-ar-03-brand-1', headline: 'AI Empire — أضف AI لأي تطبيق', description: 'API بسيط لإضافة إمكانيات AI لتطبيقك. Groq + Gemini. مكتبات لـ JS وPython.', cta: 'اطّلع على التوثيقات' },
            { id: 'g-ar-03-brand-2', headline: 'SDK AI Empire — تكامل AI في 5 دقائق', description: 'ثبّت وعّمّل وانشر. يجعل SDK الخاص بنا تكامل AI مباشراً. باقة مجانية متاحة.', cta: 'عرض SDK' },
            { id: 'g-ar-03-brand-3', headline: 'توثيقات API AI Empire — ابدأ البناء', description: 'توثيقات شاملة وأمثلة تعليمية ودروس. أضف AI لتطبيق Next.js الخاص بك اليوم.', cta: 'اطّلع على التوثيقات' },
          ],
        },
        {
          id: 'g-ar-03-competitor',
          name: 'المنافسون',
          keywords: ['خدمة تكامل AI', 'دمج AI في التطبيق', 'sdk AI', 'sdk groq', 'sdk gemini', 'غلاف ai api'],
          ads: [
            { id: 'g-ar-03-comp-1', headline: 'تكامل AI أسهل من البناء المخصص', description: 'قف عن إدارة عدة مكتبات AI. AI Empire: API واحد، عدة نماذج. باقة مجانية.', cta: 'ابسَط الأمر' },
            { id: 'g-ar-03-comp-2', headline: 'تكامل AI — بدون إعداد معقد', description: 'مفتاح API واحد، نقطة نهاية واحدة. Groq وGemini جاهزان. رصيد مجاني للاختبار. التوثيقات مضمنة.', cta: 'جرّب مجاناً' },
            { id: 'g-ar-03-comp-3', headline: 'استبدل غلاف AI API الخاص بك', description: 'يوفر AI Empire API موحداً جاهزاً للإنتاج. الفوترة ومراقبة المعدل والمراقبة مضمنة.', cta: 'شاهد كيف' },
          ],
        },
        {
          id: 'g-ar-03-generic',
          name: 'عام',
          keywords: ['إضافة ai للتطبيق', 'تكامل AI', 'ai api لتطبيق الويب', 'تكامل groq', 'تكامل gemini', 'ai api rest'],
          ads: [
            { id: 'g-ar-03-gen-1', headline: 'أضف AI لتطبيق الويب — REST API بسيط', description: 'REST API لـ Groq وGemini. باقة مجانية. استجابة JSON. يعمل بأي لغة.', cta: 'ابدأ مجاناً' },
            { id: 'g-ar-03-gen-2', headline: 'تكامل AI API — سهل للمطورين', description: 'API موثّق جيداً مع مكتبات لـ JavaScript وPython. باقة مجانية. ادفع حسب الاستخدام.', cta: 'اطّلع على التوثيقات' },
            { id: 'g-ar-03-gen-3', headline: 'API Groq وGemini — نقطة نهاية واحدة', description: 'API واحد لعدة نماذج AI. رصيد مجاني. فوترة Stripe. جاهز للإنتاج.', cta: 'ابدأ الآن' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-04',
      name: 'طقم بدء SaaS',
      objective: 'تحويل مؤسسي SaaS والمطورين المستقلين',
      budget: '€400/شهرياً',
      adGroups: [
        {
          id: 'g-ar-04-brand',
          name: 'العلامة التجارية',
          keywords: ['بدء ai empire', 'طقم ai empire saas', 'حزمة ai empire', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-ar-04-brand-1', headline: 'AI Empire — طقم بدء SaaS كامل', description: 'Next.js 14 وStripe والمصادقة وAPI AI ولوحة الإدارة. كل ما تحتاجه لإطلاق SaaS. من €19.', cta: 'احصل على طقم البداية' },
            { id: 'g-ar-04-brand-2', headline: 'أطلق SaaS الخاص بك مع AI Empire', description: '6 قوالب احترافية. فوترة Stripe والمصادقة وAPI AI. انشر خلال 24 ساعة.', cta: 'شاهد القوالب' },
            { id: 'g-ar-04-brand-3', headline: 'حزمة AI Empire — جميع القوالب', description: '6 قوالب + دعم أولوية + تحديثات مجانية. طقم بدء SaaS كامل بـ €299.', cta: 'احصل على الحزمة' },
          ],
        },
        {
          id: 'g-ar-04-competitor',
          name: 'المنافسون',
          keywords: ['طقم بدء saas', 'قالب saas nextjs', 'طقم أدوات المطور المستقل', 'قالب saas متكامل', 'إطلاق saas بسرعة'],
          ads: [
            { id: 'g-ar-04-comp-1', headline: 'طقم بدء SaaS — أكثر من قالب نموذجي', description: 'يتضمن AI Empire API AI ولوحة الإدارة وقوالب حقيقية. ليست مجرد كود مبدئي.', cta: 'قارن الميزات' },
            { id: 'g-ar-04-comp-2', headline: 'أطلق SaaS خلال 24 ساعة', description: 'لماذا تقضي شهراً في البناء من الصفر؟ قوالب AI Empire: انشر اليوم، طوّر غداً.', cta: 'شاهد القوالب' },
            { id: 'g-ar-04-comp-3', headline: 'طقم أدوات SaaS للمطور المستقل', description: 'كل ما تحتاجه: قوالب وAPI AI وStripe ومصادقة. من €19. باقة مجانية للـ API.', cta: 'ابدأ البناء' },
          ],
        },
        {
          id: 'g-ar-04-generic',
          name: 'عام',
          keywords: ['قالب saas', 'كيفية بناء saas', 'قالب تطبيق saas', 'next.js saas', 'قالب saas stripe', 'mvp saas'],
          ads: [
            { id: 'g-ar-04-gen-1', headline: 'ابنِ MVP لـ SaaS في أيام', description: 'قوالب Next.js 14 مع Stripe والمصادقة والـ AI. من €19. انشر على Vercel.', cta: 'ابدأ الآن' },
            { id: 'g-ar-04-gen-2', headline: 'قالب SaaS — Stripe والمصادقة مضمنان', description: 'قوالب Next.js 14 جاهزة للإنتاج. المدفوعات والمصادقة وAPI AI مدمجة.', cta: 'استكشف القوالب' },
            { id: 'g-ar-04-gen-3', headline: 'قالب SaaS متكامل — Next.js 14', description: 'stack عصري: Next.js 14 وTailwind وStripe وAI. من €19.', cta: 'شاهد القوالب' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-05',
      name: 'بديل OpenAI',
      objective: 'استقطاب حركة مقارنة OpenAI',
      budget: '€300/شهرياً',
      adGroups: [
        {
          id: 'g-ar-05-brand',
          name: 'العلامة التجارية',
          keywords: ['ai empire vs openai', 'بديل ai empire', 'أسعار ai empire', 'أرخص من openai'],
          ads: [
            { id: 'g-ar-05-brand-1', headline: 'AI Empire vs OpenAI — الجودة نفسها، التكلفة أقل', description: 'Groq وGemini عبر AI Empire. API موحد مع باقة مجانية. وفّر ما يصل إلى 70% مقارنة بـ OpenAI.', cta: 'قارن الأسعار' },
            { id: 'g-ar-05-brand-2', headline: 'لماذا تنتقل من OpenAI إلى AI Empire', description: 'تكلفة أقل، نماذج متعددة، API موحد، باقة مجانية. انتقل في دقائق بدون تغيير الكود.', cta: 'شاهد الأسعار' },
            { id: 'g-ar-05-brand-3', headline: 'AI Empire — API AI فعال من حيث التكلفة', description: 'Groq + Gemini. أقل بـ 70% من OpenAI بنفس الجودة. رصيد مجاني عند التسجيل.', cta: 'ابدأ مجاناً' },
          ],
        },
        {
          id: 'g-ar-05-competitor',
          name: 'المنافسون',
          keywords: ['بديل openai api', 'أرخص من openai api', 'بديل تسعير openai', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-ar-05-comp-1', headline: 'بديل OpenAI أرخص — جرّب مجاناً', description: 'AI Empire: API موحد لـ Groq وGemini. باقة مجانية، تسعير حسب الاستخدام. أقل بـ 70% من OpenAI.', cta: 'جرّب مجاناً' },
            { id: 'g-ar-05-comp-2', headline: 'API Groq وGemini — قيمة أفضل', description: 'لماذا تدفع أكثر؟ Groq للسرعة، Gemini للقدرة. API واحد، تكلفة أقل. باقة مجانية.', cta: 'اطّلع على الخطط' },
            { id: 'g-ar-05-comp-3', headline: 'انتقل من OpenAI — وفّر 70%', description: 'يوفر AI Empire Groq وGemini من خلال API واحد. الجودة نفسها، تكلفة بسيطة.', cta: 'قارن الآن' },
          ],
        },
        {
          id: 'g-ar-05-generic',
          name: 'عام',
          keywords: ['تسعير ai api', 'تكلفة ai api', 'تسعير groq', 'تسعير gemini api', 'مقارنة ai api', 'أرخص ai api'],
          ads: [
            { id: 'g-ar-05-gen-1', headline: 'AI API — من المجاني إلى الدفع حسب الاستخدام', description: 'ابدأ مجاناً، توسع بشكل فعال. Groq + Gemini. بدون رسوم شهرية. ادفع فقط مقابل ما تستخدمه.', cta: 'شاهد الأسعار' },
            { id: 'g-ar-05-gen-2', headline: 'AI API ميسور التكلفة — Groq وGemini', description: '100 رصيد في الباقة المجانية. ادفع حسب الاستخدام بعدها. بدون حد أدنى، بدون ارتباط.', cta: 'ابدأ الآن' },
            { id: 'g-ar-05-gen-3', headline: 'تسعير AI API — شفاف وعادل', description: 'بدون رسوم خفية. API واحد لـ Groq وGemini. باقة مجانية. فوترة Stripe.', cta: 'شاهد الأسعار' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-06',
      name: 'بديل قوالب Vercel',
      objective: 'استقطاب حركة مقارنة القوالب',
      budget: '€250/شهرياً',
      adGroups: [
        {
          id: 'g-ar-06-brand',
          name: 'العلامة التجارية',
          keywords: ['ai empire vercel', 'نشر ai empire', 'ai empire next.js', 'استضافة ai empire'],
          ads: [
            { id: 'g-ar-06-brand-1', headline: 'قوالب AI Empire — انشر على Vercel', description: 'قوالب Next.js 14 محسّنة لـ Vercel. API AI وStripe والمصادقة. انشر في دقائق.', cta: 'انشر الآن' },
            { id: 'g-ar-06-brand-2', headline: 'قوالب SaaS جاهزة لـ Vercel', description: 'قوالب AI Empire: مصممة لـ Vercel. نشر بنقرة واحدة. تكامل AI وفوترة ومصادقة.', cta: 'شاهد القوالب' },
            { id: 'g-ar-06-brand-3', headline: 'قوالب Next.js 14 لـ Vercel', description: 'قوالب احترافية. انشر على Vercel في دقائق. API AI وفوーター Stripe مدمجان.', cta: 'احصل على القوالب' },
          ],
        },
        {
          id: 'g-ar-06-competitor',
          name: 'المنافسون',
          keywords: ['بديل قالب vercel', 'قالب next.js', 'أفضل من قالب vercel', 'قالب saas vercel', 'نشر قالب saas'],
          ads: [
            { id: 'g-ar-06-comp-1', headline: 'تجاوز القوالب الأساسية — AI Empire', description: 'على عكس قوالب Vercel الأساسية، يتضمن AI Empire API AI وStripe ولوحة الإدارة.', cta: 'شاهد الميزات' },
            { id: 'g-ar-06-comp-2', headline: 'قالب Next.js مع AI وStripe', description: 'AI Empire: ليس مجرد قالب، بل طقم بدء SaaS كامل. API AI وفوترة ومصادقة.', cta: 'قارن' },
            { id: 'g-ar-06-comp-3', headline: 'قوالب SaaS للإنتاج — Next.js 14', description: 'تجاوز قوالب العرض. AI Empire: مصادقة حقيقية ومدفوعات حقيقية وتكامل AI حقيقي.', cta: 'شاهد القوالب' },
          ],
        },
        {
          id: 'g-ar-06-generic',
          name: 'عام',
          keywords: ['قالب نشر next.js', 'قالب نشر saas', 'vercel saas', 'نشر nextjs 14', 'قالب نشر saas', 'نشر قالب vercel'],
          ads: [
            { id: 'g-ar-06-gen-1', headline: 'انشر SaaS على Vercel اليوم', description: 'قوالب Next.js 14. نشر بنقرة واحدة. AI وStripe ومصادقة. من €19.', cta: 'ابدأ النشر' },
            { id: 'g-ar-06-gen-2', headline: 'قالب SaaS — جاهز للنشر', description: 'قوالب Next.js 14 احترافية. انشر على Vercel في دقائق. stack كامل.', cta: 'ابدأ الآن' },
            { id: 'g-ar-06-gen-3', headline: 'Next.js 14 SaaS — انشر في دقائق', description: 'قوالب تتضمن كل شيء: مصادقة ومدفوعات وAI وإدارة. انشر فوراً على Vercel.', cta: 'استكشف القوالب' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-07',
      name: 'قالب التجارة الإلكترونية — NeuraStore',
      objective: 'دفع مبيعات قالب NeuraStore',
      budget: '€300/شهرياً',
      adGroups: [
        {
          id: 'g-ar-07-brand',
          name: 'العلامة التجارية',
          keywords: ['neurastore', 'تجارة إلكترونية ai empire', 'قالب neurastore', 'neurastore next.js'],
          ads: [
            { id: 'g-ar-07-brand-1', headline: 'NeuraStore — قالب تجارة إلكترونية بالـ AI', description: 'قالب تجارة إلكترونية Next.js 14 مع Stripe وسلة التسوق ولوحة الإدارة. توصيات منتجات بالـ AI.', cta: 'شاهد NeuraStore' },
            { id: 'g-ar-07-brand-2', headline: 'NeuraStore — أطلق متجرك الإلكتروني', description: 'قالب تجارة إلكترونية احترافي. مدفوعات Stripe وإدارة المخزون وتصميم متجاوب.', cta: 'شاهد العرض التوضيحي' },
            { id: 'g-ar-07-brand-3', headline: 'NeuraStore من AI Empire — €29', description: 'قالب تجارة إلكترونية كامل. Next.js 14 وStripe وTailwind. انشر في دقائق.', cta: 'اشترِ NeuraStore' },
          ],
        },
        {
          id: 'g-ar-07-competitor',
          name: 'المنافسون',
          keywords: ['قالب تجارة إلكترونية next.js', 'قالب متجر إلكتروني', 'بديل shopify قالب', 'قالب تجارة إلكترونية react', 'قالب متجر nextjs'],
          ads: [
            { id: 'g-ar-07-comp-1', headline: 'قالب التجارة الإلكترونية — امتلك متجرك', description: 'على عكس Shopify، NeuraStore ملكك. استضافة ذاتية وقابل للتخصيص ومدعوم بالـ AI. €29.', cta: 'احصل على NeuraStore' },
            { id: 'g-ar-07-comp-2', headline: 'تجارة إلكترونية Next.js — تحكم كامل', description: 'NeuraStore: امتلك الكود والبيانات والمتجر. تكامل Stripe ولوحة إدارة.', cta: 'شاهد القالب' },
            { id: 'g-ar-07-comp-3', headline: 'ابنِ متجرك الإلكتروني الخاص', description: 'قالب NeuraStore: Next.js 14 وStripe وتصميم متجاوب ولوحة إدارة. €29.', cta: 'ابدأ البناء' },
          ],
        },
        {
          id: 'g-ar-07-generic',
          name: 'عام',
          keywords: ['قالب موقع تجارة إلكترونية', 'قالب متجر إلكتروني', 'nextjs تجارة إلكترونية', 'بناء متجر إلكتروني', 'قالب saas تجارة إلكترونية', 'قالب متجر رقمي'],
          ads: [
            { id: 'g-ar-07-gen-1', headline: 'قالب موقع تجارة إلكترونية — Next.js 14', description: 'قالب متجر إلكتروني احترافي. Stripe وسلة تسوق وإدارة. متجاوب ووضع مظلم. €29.', cta: 'تسوّق القالب' },
            { id: 'g-ar-07-gen-2', headline: 'ابنِ متجر إلكتروني بـ Next.js', description: 'NeuraStore: حل تجارة إلكترونية كامل. المدفوعات والمخزون والتوصيات بالـ AI.', cta: 'ابدأ الآن' },
            { id: 'g-ar-07-gen-3', headline: 'قالب متجر إلكتروني — جاهز للإطلاق', description: 'قالب تجارة إلكترونية Next.js 14. فوترة Stripe وتصميم متجاوب ومحسّن لمحركات البحث. €29.', cta: 'انشر الآن' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-08',
      name: 'قالب المدونة — NeuraBlog',
      objective: 'دفع مبيعات قالب NeuraBlog',
      budget: '€250/شهرياً',
      adGroups: [
        {
          id: 'g-ar-08-brand',
          name: 'العلامة التجارية',
          keywords: ['neurablog', 'مدونة ai empire', 'قالب neurablog', 'neurablog next.js'],
          ads: [
            { id: 'g-ar-08-brand-1', headline: 'NeuraBlog — قالب مدونة محسّن لمحركات البحث', description: 'قالب مدونة Next.js 14 مع MDX ووضع مظلم وخلاصة RSS. تكامل النشرة الإخبارية مدمج.', cta: 'شاهد NeuraBlog' },
            { id: 'g-ar-08-brand-2', headline: 'NeuraBlog — مدونة احترافية في دقائق', description: 'قالب مدونة مميز. دعم MDX وتحسين محركات البحث ونظام التعليقات. €19.', cta: 'شاهد العرض التوضيحي' },
            { id: 'g-ar-08-brand-3', headline: 'NeuraBlog من AI Empire — €19', description: 'قالب مدونة كامل. Next.js 14 وMDX ووضع مظلم وRSS. انشر على Vercel.', cta: 'اشترِ NeuraBlog' },
          ],
        },
        {
          id: 'g-ar-08-competitor',
          name: 'المنافسون',
          keywords: ['قالب مدونة next.js', 'بديل wordpress', 'بديل ghost', 'قالب مدونة mdx', 'قالب مدونة react'],
          ads: [
            { id: 'g-ar-08-comp-1', headline: 'قالب مدونة — أسرع من WordPress', description: 'NeuraBlog: سرعة الموقع الثابت، ميزات ديناميكية. MDX والبحث والنشرة الإخبارية. €19.', cta: 'جرّب NeuraBlog' },
            { id: 'g-ar-08-comp-2', headline: 'قالب مدونة MDX — Next.js 14', description: 'على عكس Ghost، يمنحك NeuraBlog تحكماً كاملاً. استضافة ذاتية وسريع وقابل للتخصيص.', cta: 'شاهد القالب' },
            { id: 'g-ar-08-comp-3', headline: 'مدونتك، كودك — NeuraBlog', description: 'امتلك منصتك. NeuraBlog: Next.js 14 وMDX ووضع مظلم وRSS. €19.', cta: 'احصل على NeuraBlog' },
          ],
        },
        {
          id: 'g-ar-08-generic',
          name: 'عام',
          keywords: ['قالب مدونة', 'قالب مدونة شخصية', 'مدونة nextjs', 'قالب مدونة تقنية', 'بدء مدونة', 'قالب موقع مدونة'],
          ads: [
            { id: 'g-ar-08-gen-1', headline: 'قالب مدونة — ابدأ مدونتك اليوم', description: 'قالب مدونة احترافي. محسّن لمحركات البحث ووضع مظلم والنشرة الإخبارية. انشر في دقائق. €19.', cta: 'ابدأ التدوين' },
            { id: 'g-ar-08-gen-2', headline: 'مدونة Next.js 14 — سريعة وجميلة', description: 'NeuraBlog: قالب مدونة عصري. MDX ووضع مظلم وRSS ونظام التعليقات. €19.', cta: 'شاهد القالب' },
            { id: 'g-ar-08-gen-3', headline: 'ابدأ مدونة احترافية — €19', description: 'قالب NeuraBlog. محسّن لمحركات البحث ومتجاوب ووضع مظلم. انشر على Vercel.', cta: 'ابدأ الآن' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-09',
      name: 'قالب المعرض — NeuraPortfolio',
      objective: 'دفع مبيعات قالب NeuraPortfolio',
      budget: '€200/شهرياً',
      adGroups: [
        {
          id: 'g-ar-09-brand',
          name: 'العلامة التجارية',
          keywords: ['neuraportfolio', 'معرض ai empire', 'قالب neuraportfolio', 'قالب معرض مطور'],
          ads: [
            { id: 'g-ar-09-brand-1', headline: 'NeuraPortfolio — قالب معرض المطورين', description: 'معرض احترافي مع رسوم متحركة ووضع مظلم ونموذج اتصال. Next.js 14. €29.', cta: 'شاهد NeuraPortfolio' },
            { id: 'g-ar-09-brand-2', headline: 'NeuraPortfolio — تألّق على الإنترنت', description: 'قالب معرض جميل. رسوم متحركة Framer Motion ومتجاوب ووضع مظلم. €29.', cta: 'شاهد العرض التوضيحي' },
            { id: 'g-ar-09-brand-3', headline: 'NeuraPortfolio من AI Empire — €29', description: 'قالب معرض كامل. Next.js 14 ورسوم متحركة ووضع مظلم ونموذج اتصال.', cta: 'اشترِ NeuraPortfolio' },
          ],
        },
        {
          id: 'g-ar-09-competitor',
          name: 'المنافسون',
          keywords: ['قالب معرض مطور', 'قالب موقع معرض', 'أفضل قالب معرض', 'قالب معرض إبداعي', 'معرض مستقل'],
          ads: [
            { id: 'g-ar-09-comp-1', headline: 'قالب معرض — اترك انطباعاً', description: 'NeuraPortfolio: رسوم متحركة جميلة وتصميم متجاوب ووضع مظلم. أفضل من القوالب العامة.', cta: 'شاهد القالب' },
            { id: 'g-ar-09-comp-2', headline: 'معرضك يستحق التميز', description: 'NeuraPortfolio: رسوم متحركة Framer Motion وتصميم عصري وتخصيص كامل. €29.', cta: 'شاهد NeuraPortfolio' },
            { id: 'g-ar-09-comp-3', headline: 'معرض مطور — Next.js 14', description: 'ابنِ معرضك مع NeuraPortfolio. سريع وجميل ويُنشر في دقائق.', cta: 'ابدأ الآن' },
          ],
        },
        {
          id: 'g-ar-09-generic',
          name: 'عام',
          keywords: ['موقع معرض', 'بناء معرض', 'معرض إلكتروني', 'قالب موقع شخصي', 'قالب معرض مستقل', 'عرض معرض'],
          ads: [
            { id: 'g-ar-09-gen-1', headline: 'ابنِ معرضك الإلكتروني — €29', description: 'NeuraPortfolio: قالب احترافي مع رسوم متحركة. انشر في دقائق.', cta: 'ابدأ البناء' },
            { id: 'g-ar-09-gen-2', headline: 'قالب موقع شخصي — Next.js 14', description: 'قالب معرض جميل. وضع مظلم ورسوم متحركة ومتجاوب. من €29.', cta: 'شاهد القوالب' },
            { id: 'g-ar-09-gen-3', headline: 'قالب معرض — انشر اليوم', description: 'معرض احترافي بتصميم عصري. Framer Motion ووضع مظلم. €29.', cta: 'احصل على المعرض' },
          ],
        },
      ],
    },
    {
      id: 'g-ar-10',
      name: 'منشئ SaaS بالـ AI',
      objective: 'استقطاب نية بناء SaaS بالـ AI',
      budget: '€350/شهرياً',
      adGroups: [
        {
          id: 'g-ar-10-brand',
          name: 'العلامة التجارية',
          keywords: ['منشئ saas ai empire', 'بناء saas ai empire', 'إطلاق ai empire', 'منصة ai empire'],
          ads: [
            { id: 'g-ar-10-brand-1', headline: 'AI Empire — ابنِ SaaS بالـ AI الخاص بك', description: 'قوالب + API AI + Stripe + مصادقة. كل ما تحتاجه لبناء وإطلاق SaaS بالـ AI.', cta: 'ابدأ البناء' },
            { id: 'g-ar-10-brand-2', headline: 'AI Empire — منصة SaaS بالـ AI الخاصة بك', description: 'من الفكرة إلى الإطلاق. قوالب وAPI AI ومدفوعات ومصادقة. انشر خلال 24 ساعة.', cta: 'أطلق الآن' },
            { id: 'g-ar-10-brand-3', headline: 'AI Empire — أطلق SaaS أسرع', description: 'قوالب احترافية مع تكامل AI. Stripe ومصادقة ولوحة إدارة. من €19.', cta: 'ابدأ الآن' },
          ],
        },
        {
          id: 'g-ar-10-competitor',
          name: 'المنافسون',
          keywords: ['بناء ai saas', 'منشئ saas', 'قالب ai saas', 'منصة saas ai', 'بناء saas بـ ai', 'منشئ منتج ai'],
          ads: [
            { id: 'g-ar-10-comp-1', headline: 'ابنِ SaaS بالـ AI — ليس من الصفر', description: 'AI Empire: قوالب احترافية مع API AI مدمج. وفّر شهوراً من التطوير.', cta: 'شاهد القوالب' },
            { id: 'g-ar-10-comp-2', headline: 'منشئ SaaS بالـ AI — أطلق في أيام', description: 'قوالب وAPI AI وStripe ومصادقة. AI Empire: كل ما تحتاجه للإطلاق.', cta: 'قارن الميزات' },
            { id: 'g-ar-10-comp-3', headline: 'أطلق SaaS بالـ AI هذا الأسبوع', description: 'لماذا تبني من الصفر؟ قوالب AI Empire: انشر خلال 24 ساعة. تكامل AI مضمن.', cta: 'ابدأ مجاناً' },
          ],
        },
        {
          id: 'g-ar-10-generic',
          name: 'عام',
          keywords: ['قالب saas', 'بناء saas', 'تطبيق saas', 'منصة saas', 'قالب منتج ai', 'أفكار saas', 'إطلاق saas'],
          ads: [
            { id: 'g-ar-10-gen-1', headline: 'ابنِ SaaS — قوالب وAI ومدفوعات', description: 'قوالب Next.js 14 مع API AI وStripe ومصادقة. من €19. انشر اليوم.', cta: 'ابدأ الآن' },
            { id: 'g-ar-10-gen-2', headline: 'منشئ SaaS — كل شيء مضمن', description: 'قوالب وتكامل AI ومدفوعات ولوحة إدارة. طقم SaaS كامل. من €19.', cta: 'استكشف القوالب' },
            { id: 'g-ar-10-gen-3', headline: 'أطلق فكرة SaaS — Next.js 14', description: 'قوالب احترافية بstack عصري. AI وStripe ومصادقة. انشر في دقائق.', cta: 'ابدأ البناء' },
          ],
        },
      ],
    },
  ],
  facebook: [
    {
      id: 'fb-ar-01',
      name: 'زيادة الوعي بالعلامة التجارية AI Empire',
      type: 'awareness',
      objective: 'زيادة الوعي بالعلامة التجارية بين المطورين ومؤسسي الشركات الناشئة',
      audience: 'مطورون وقادة تقنيون ومؤسسو شركات ناشئة، تتراوح أعمارهم بين 22-45 سنة، مهتمون بالـ AI وSaaS وNext.js وتطوير الويب',
      placements: ['_news Feed على Facebook', 'News Feed على Instagram', 'Audience Network'],
      adCopy: 'تبني SaaS؟ يمنحك AI Empire قوالب Next.js 14 مع API AI مدمج (Groq + Gemini) وفوترة Stripe ومصادقة — من €19. انضم لأكثر من 5,000 مطور أطلق أسرع.',
      cta: 'اعرف المزيد',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-ar-02',
      name: 'قيمة API الموحد',
      type: 'awareness',
      objective: 'تثقيف المطورين حول API AI الموحد',
      audience: 'مطورو برمجيات ومحللو تعلم آلي ومحبّو الذكاء الاصطناعي، تتراوح أعمارهم بين 22-40 سنة',
      placements: ['News Feed على Facebook', 'Stories على Instagram', 'Reels'],
      adCopy: 'API واحد لـ Groq وGemini. يوفر AI Empire نقطة نهاية موحدة لعدة نماذج AI — ابدأ مجاناً وادفع حسب نموك. توقف عن إدارة عدة مكتبات AI.',
      cta: 'جرّب مجاناً',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    {
      id: 'fb-ar-03',
      name: 'عرض NeuraStore',
      type: 'consideration',
      objective: 'دفع حركة المرور لصفحة قالب NeuraStore',
      audience: 'مطورو التجارة الإلكترونية وبناء المتاجر الإلكترونية ومستخدمو Shopify يبحثون عن بدائل',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Marketplace'],
      adCopy: 'NeuraStore: قالب تجارة إلكترونية كامل بـ Next.js 14. مدفوعات Stripe وإدارة السلة ولوحة الإدارة وتوصيات المنتجات بالـ AI. €29 — امتلك متجرك وملكك كودك.',
      cta: 'شاهد القالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-ar-04',
      name: 'عرض حزمة القوالب',
      type: 'consideration',
      objective: 'إثارة الاهتمام بالحزمة الكاملة للقوالب',
      audience: 'مؤسسو SaaS والمطورون المستقلون والمطورون المتكاملون',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Facebook Marketplace'],
      adCopy: 'احصل على جميع قوالب AI Empire الست بـ €299. NeuraStore وNeuraBlog وNeuraPortfolio و3 قوالب أخرى. دعم أولوية وتحديثات مجانية وكل شيء شامل. وفّر أكثر من €400 مقارنة بالشراء الفردي.',
      cta: 'شاهد الحزمة',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-ar-05',
      name: 'دليل تكامل AI',
      type: 'consideration',
      objective: 'جذب المطورين بمحتوى تعليمي',
      audience: 'مطورو الويب ومطورو React ومطورو Node.js',
      placements: ['News Feed على Facebook', 'Reels على Instagram', 'Stories'],
      adCopy: 'أضف AI لتطبيق Next.js في 5 دقائق. يجعل SDK الخاص بنا التكامل مباشراً — مفتاح API واحد ونقطة نهاية واحدة. 100 رصيد في الباقة المجانية. التوثيقات والأمثلة مضمنة.',
      cta: 'اطّلع على التوثيقات',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    {
      id: 'fb-ar-06',
      name: 'تسجيل مجاني في API',
      type: 'conversion',
      objective: 'دفع التسجيلات في الباقة المجانية',
      audience: 'زوار الموقع وقرّاء التوثيقات وقرّاء المدونة والجماهير المماثلة',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Audience Network'],
      adCopy: 'API AI المجاني في انتظارك. سجّل في AI Empire واحصل على 100 رصيد لـ Groq وGemini. لا حاجة لبطاقة ائتمان. ابدأ بالبناء بالـ AI اليوم.',
      cta: 'سجّل مجاناً',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-ar-07',
      name: 'تحويل شراء القوالب',
      type: 'conversion',
      objective: 'تحويل زوار صفحة القوالب إلى مشترين',
      audience: 'زوار صفحة القوالب والمتسوقون المتردّدون والمستخدمون ذوو النية العالية',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Messenger'],
      adCopy: 'لا تزال تفكر؟ NeuraBlog (€19) وNeuraStore (€29) جاهزان للنشر. Stripe والمصادقة وتكامل AI شامل. ضمان استرداد 100%.',
      cta: 'اشترِ الآن',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-ar-08',
      name: 'خصم محدود على الحزمة',
      type: 'conversion',
      objective: 'دفع شراء الحزمة بالإلحاح',
      audience: 'مشتركو البريد الإلكتروني والمتسوقون المتردّدون والمستخدمون ذوو المشاركة العالية',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Stories على Instagram'],
      adCopy: 'عرض محدود: احصل على حزمة قوالب AI Empire الكاملة بـ €299 (وفّر أكثر من €400). تتضمن 6 قوالب ودعم أولوية وتحديثات مجانية. العرض ينتهي قريباً.',
      cta: 'احصل على الحزمة',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    {
      id: 'fb-ar-09',
      name: 'الزوار العائدون — القوالب',
      type: 'retargeting',
      objective: 'إعادة جذب الزوار الذين شاهدوا القوالب لكنهم لم يشتروا',
      audience: 'زوار صفحة القوالب (7-30 يوماً) لم يكملوا الشراء',
      placements: ['News Feed على Facebook', 'News Feed على Instagram', 'Audience Network'],
      adCopy: 'كنت تتصفح قوالب AI Empire. NeuraBlog يبدأ من €19 وNeuraStore من €29. stack كامل وجاهز للنشر ومتكامل مع AI. عُد وأطلق SaaS الخاص بك.',
      cta: 'شاهد القوالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-ar-10',
      name: 'الزوار العائدون — API',
      type: 'retargeting',
      objective: 'إعادة جذب الزوار الذين استكشفوا توثيقات API لكنهم لم يسجلوا',
      audience: 'زوار صفحة التوثيقات (7-30 يوماً) لم ينشئوا حساباً',
      placements: ['News Feed على Facebook', 'Stories على Instagram', 'Reels'],
      adCopy: 'استكشفت توثيقاتنا. مستعد للبناء؟ يمنحك AI Empire رصيداً مجانيًا لـ Groq وGemini. سجّل في 30 ثانية، لا حاجة لبطاقة ائتمان.',
      cta: 'ابدأ مجاناً',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    {
      id: 'li-ar-01',
      name: 'إعلان إطلاق SaaS',
      type: 'sponsored_content',
      objective: 'جذب التسجيلات من صانعي القرار التقنيين',
      audience: 'قادة تقنيون ومسؤولو هندسة في الشركات الناشئة والمتوسطة',
      headline: 'أطلق SaaS 10 أسرع مع AI Empire',
      body: 'يوفر AI Empire قوالب Next.js 14 مع API AI مدمج (Groq + Gemini) وفوترة Stripe ومصادقة. حوّل الفكرة إلى SaaS منشور في 24 ساعة، وليس في أشهر.\n\nما هو شامل:\n- 6 قوالب جاهزة للإنتاج (€19 - €299)\n- API AI موحد مع باقة مجانية\n- Stripe + مصادقة مُعدّان\n- لوحة إدارة\n\nانضم لأكثر من 5,000 مطور يبنون مع AI Empire.',
      cta: 'ابدأ البناء',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-ar-02',
      name: 'API AI للمؤسسات',
      type: 'sponsored_content',
      objective: 'الوصول لقادة الهندسة الذين يقيّمون حلول API AI',
      audience: 'مديرو الهندسة ونواب رئيس الهندسة والمهندsono المعماريون في الشركات المتوسطة والكبيرة',
      headline: 'API AI موحد — Groq وGemini لفريقك',
      body: 'توقف عن إدارة علاقات مزودي AI المتعددة. يوفر AI Empire API واحداً لـ Groq وGemini — مع فوترة ومراقبة معدل ومراقبة مدمجة.\n\nلماذا تختار فرق الهندسة AI Empire:\n- نقطة نهاية واحدة لعدة نماذج AI\n- مكتبات JavaScript وPython\n- باقة مجانية للنماذج الأولية\n- توسع حسب الاستخدام\n\nقلّل تعقيد تكامل AI.',
      cta: 'استكشف API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-ar-03',
      name: 'نجاح المطور المستقل',
      type: 'sponsored_content',
      objective: 'استقطاب المطورين المستقلين والمؤسسين الأفراد',
      audience: 'مطورون مستقلون ومؤسسو أفراد وشركات ناشئة ذاتية التمويل',
      headline: 'أطلق SaaS هذا العطلةWeekend',
      body: 'مصمم للمؤسسين الأفراد الذين يريدون التحرك بسرعة.\n\nAI Empire يمنحك:\n- قوالب Next.js 14 احترافية\n- API AI جاهزة للاستخدام\n- فوترة Stripe في 5 دقائق\n- لا حاجة للكود عند الإطلاق\n\nقوالب من €19. انشر بنقرة واحدة على Vercel.\n\nتوقف عن التفكير الزائد. ابدأ النشر.',
      cta: 'شاهد القوالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-ar-04',
      name: 'مقارنة التكاليف',
      type: 'sponsored_content',
      objective: 'استقطاب الفرق المعنيّة بالتكلفة الذين يقارنون مزودي AI',
      audience: 'قادة تقنيون ومسؤولو مالية ومشترون في الشركات الناشئة والمتوسطة',
      headline: 'API AI — أقل بـ 70% من المنافسين',
      body: 'يجمع AI Empire Groq وGemini في API واحد. ادفع فقط مقابل ما تستخدمه.\n\nالمقارنة:\n- OpenAI: €0.03 لكل 1,000 رمز (GPT-4)\n- AI Empire: ~€0.009 لكل 1,000 رمز (Groq Llama)\n\nباقة مجانية شاملة. بدون ارتباط بالمزود. انتقل في دقائق.\n\nأكثر من 5,000 مطور يوفّرون بالفعل.',
      cta: 'شاهد الأسعار',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    {
      id: 'li-ar-05',
      name: 'تواصل مباشر مع CTOs',
      type: 'message_ads',
      objective: 'تواصل شخصي مع CTOs في الشركات المستهدفة',
      audience: 'CTOs في شركات التقنية وSaaS والتجارة الإلكترونية بحجم 10-200 موظف',
      headline: 'سؤال سريع حول مكدّس الـ AI الخاص بك',
      body: 'مرحباً {{first_name}}،\n\nلاحظت أن {{company}} تبني بالـ AI. سؤال سريع: هل تدير واجهات API AI متعددة من المزودين؟\n\nيوفر AI Empire API موحداً لـ Groq وGemini — نقطة نهاية واحدة وفاتورة واحدة ولوحة تحكم واحدة. باقة مجانية شاملة.\n\nهل يُمكن أن نتحدث لمدة 10 دقائق؟ يسعدني أن أشرح لك.',
      cta: 'حدد محادثة',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-ar-06',
      name: 'تواصل مباشر مع المطورين',
      type: 'message_ads',
      objective: 'جذب المطورين الأفراد بعروض شخصية',
      audience: 'مطورون متكاملون ومطورون React/Next.js في شركات التقنية',
      headline: 'تبني بـ Next.js؟',
      body: 'مرحباً {{first_name}}،\n\nلاحظت أنك تعمل بـ Next.js. بنينا AI Empire خصيصاً لنظام Next.js — قوالب مع API AI وStripe ومصادقة جاهزة.\n\nإذا كنت تعمل على مشروع جانبي أو تساعد فريقك على الإطلاق أسرع، فقد تكون الباقة المجانية مفيدة.\n\nيسعدني مشاركة رمز خصم إذا كنت مهتماً.',
      cta: 'احصل على رمز الخصم',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-ar-07',
      name: 'تواصل شراكة',
      type: 'message_ads',
      objective: 'استكشاف فرص الشراكة مع الوكالات والاستشاريين',
      audience: ' أصحاب وكالات ومؤسسو استشاريين وقادة التحول الرقمي',
      headline: 'فرصة شراكة لـ {{company}}',
      body: 'مرحباً {{first_name}}،\n\nيساعد AI Empire الفرق على إطلاق منتجات مدعومة بالـ AI أسرع. نبني برنامج شراكة للوكالات والاستشاريين الذين يوصون بقوالبنا وواجهات API لعملائهم.\n\nالمزايا:\n- مشاركة الإيرادات من الإحالات\n- دعم أولوية لعملائك\n- فرص تسويق مشتركة\n\nهل يستحق الاستكشاف؟',
      cta: 'تعرّف على الشراكات',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    {
      id: 'li-ar-08',
      name: 'ديناميكي — استهداف المسمى الوظيفي',
      type: 'dynamic',
      objective: 'استهداف المطورين حسب المسمى الوظيفي بإعلانات شخصية',
      audience: 'مستخدمون بـ CTO أو نائب رئيس الهندسة أو قائد تقني أو مطور أول',
      headline: 'AI Empire لـ {{job_title}} — أطلق أسرع',
      body: 'يمنحك AI Empire مساراً أسرع للإنتاج لـ {{company_name}}. قوالب Next.js 14 مع API AI وStripe ومصادقة. باقة مجانية للنماذج الأولية، توسع حسب الاستخدام.',
      cta: 'استكشف AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-ar-09',
      name: 'ديناميكي — حجم الشركة',
      type: 'dynamic',
      objective: 'تخصيص الرسالة حسب حجم الشركة',
      audience: 'شركات بحجم 1-50 موظف (ناشئة) و51-500 موظف (نمو)',
      headline: '{{company_name}} — قوالب AI SaaS',
      body: 'للفرق النامية: يوفر AI Empire قوالب Next.js 14 جاهزة للإنتاج مع تكامل AI. انشر في أيام، وليس في أشهر. من €19.',
      cta: 'شاهد القوالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-ar-10',
      name: 'ديناميكي — استهداف الصناعة',
      type: 'dynamic',
      objective: 'استهداف صناعات محددة برسائل مخصصة',
      audience: 'التجارة الإلكترونية وSaaS والوكالات الرقمية',
      headline: 'حلول {{industry}} مدعومة بالـ AI',
      body: 'قوالب AI Empire مصممة لـ {{industry}}. Next.js 14 وStripe وAPI AI ولوحة إدارة. من €19 إلى حزمة €299.',
      cta: 'شاهد القوالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-ar-01',
      tweet: 'بنينا AI Empire حتى لا تضطر أنت للبناء.\n\nقوالب Next.js 14 + APIs Groq وGemini + Stripe + مصادقة — كل شيء في منصة واحدة.\n\nابدأ مجاناً. انشر في دقائق.',
      cta: 'جرّب مجاناً',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'مطورون ومؤسسو شركات ناشئة',
    },
    {
      id: 'tw-ar-02',
      tweet: 'بصراحة: بناء SaaS لا ينبغي أن يستغرق 6 أشهر.\n\nقوالب AI Empire: Next.js 14 احترافي مع AI مدمج وStripe مُعد.\n\nمن الفكرة إلى النشر في 24 ساعة.',
      cta: 'شاهد القوالب',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'مطورون مستقلون ومؤسسو أفراد',
    },
    {
      id: 'tw-ar-03',
      tweet: 'API واحد. عدة نماذج AI. باقة مجانية.\n\nAI Empire: Groq للسرعة، Gemini للقدرة. نقطة نهاية موحدة.\n\nتوقف عن إدارة 5 مكتبات AI مختلفة.',
      cta: 'احصل على مفتاح API',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'مطورو AI وقادة تقنيون',
    },
    {
      id: 'tw-ar-04',
      tweet: 'NeuraStore: قالب تجارة إلكترونية كامل لـ Next.js 14.\n\nمدفوعات Stripe ✓ سلة تسوق ✓ لوحة إدارة ✓ توصيات AI ✓\n\n€29. انشر على Vercel في دقائق.',
      cta: 'شاهد NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'مطورو التجارة الإلكترونية',
    },
    {
      id: 'tw-ar-05',
      tweet: 'قارنّا أسعار OpenAI وAI Empire:\n\nنتائج بنفس الجودة بتكلفة أقل بـ 70%.\n\nGroq وGemini من خلال API واحد. باقة مجانية شاملة. بدون ارتباط بالمزود.',
      cta: 'قارن الأسعار',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'مطورون مهتمّون بالتكلفة',
    },
    {
      id: 'tw-ar-06',
      tweet: 'نشرنا SaaS في 4 ساعات باستخدام قوالب AI Empire.\n\nNext.js 14 + Stripe + مصادقة + API AI. كل شيء مُعد. فقط أضف كودك.',
      cta: 'أطلق أسرع',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'مطورون ومؤسسو شركات ناشئة',
    },
    {
      id: 'tw-ar-07',
      tweet: 'حزمة AI Empire: 6 قوالب بـ €299.\n\nNeuraStore وNeuraBlog وNeuraPortfolio و3 قوالب أخرى. دعم أولوية. تحديثات مجانية.\n\nوفّر أكثر من €400 مقارنة بالشراء الفردي.',
      cta: 'احصل على الحزمة',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'مؤسسو SaaS ومطورون',
    },
    {
      id: 'tw-ar-08',
      tweet: 'ملّيت من WordPress؟\n\nNeuraBlog: قالب مدونة Next.js 14. MDX ووضع مظلم وRSS ومحسّن لمحركات البحث. €19.\n\nسريع. عصري. ملكك.',
      cta: 'شاهد NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'مدونون ومبدعو المحتوى',
    },
    {
      id: 'tw-ar-09',
      tweet: 'الباقة المجانية في AI Empire: 100 رصيد لـ Groq وGemini.\n\nلا حاجة لبطاقة ائتمان. لا التزام. فقط ابنِ.\n\nإعداد في 5 دقائق. مكتبات JS وPython.',
      cta: 'ابدأ مجاناً',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'طلاب ومطورون هواة',
    },
    {
      id: 'tw-ar-10',
      tweet: 'معرضك يستحق أكثر من قالب HTML أساسي.\n\nNeuraPortfolio: Next.js 14 مع رسوم متحركة Framer Motion ووضع مظلم ومتجاوب. €29.\n\nاترك انطباعاً.',
      cta: 'شاهد قالب المعرض',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'مطورون ومصممون ومستقلون',
    },
  ],
  instagram: [
    {
      id: 'ig-ar-01',
      name: 'نظرة عامة على المنصة Reel',
      type: 'reel',
      script: 'المشهد 1: تسجيل شاشة للوحة التحكم — نص "تعرّف على AI Empire". المشهد 2: محرر أكواد مع استدعاء API — "API واحد، عدة نماذج". المشهد 3: صفحة دفع Stripe — "مدفوعات في 5 دقائق". المشهد 4: نشر مباشر — "تم النشر خلال 24 ساعة". المشهد 5: شعار + رابط — "ابدأ مجاناً اليوم".',
      visualDirection: 'تسجيلات شاشة سريعة بانتقالات سلسة. واجهة وضع مظلم. ألوان التدرج البنفسجي للعلامة التجارية. موسيقى إلكترونية نابضة بالحياة.',
      textOverlay: 'AI Empire — ابنِ SaaS أسرع',
      cta: 'رابط السيرة — ابدأ مجاناً',
      duration: '15-30 ثانية',
    },
    {
      id: 'ig-ar-02',
      name: 'عرض NeuraStore Story',
      type: 'story',
      script: 'استعراض مُنسّق لقالب NeuraStore. أظهر شبكة المنتجات وتدفق سلة التسوق ودفع Stripe والعرض المتجاوب على الهاتف. اختم بسعر (€29) ودعوة للعمل.',
      visualDirection: 'خلفيات بيضاء/داكنة نظيفة. عروض منتجات على iPhone وMacBook. حركات انزلاق سلسة. لمسات بنفسجية للعلامة التجارية.',
      textOverlay: 'NeuraStore — €29 — قالب تجارة إلكترونية',
      cta: 'اسحب للأعلى للعرض',
      duration: '15 ثانية',
    },
    {
      id: 'ig-ar-03',
      name: 'عرض توضيحي لـ API AI Reel',
      type: 'reel',
      script: 'المشهد 1: مطور يكتب كوداً — "أضف AI لتطبيقك". المشهد 2: استجابة API في الطرفية — "Groq وGemini في استدعاء واحد". المشهد 3: تطبيق يعمل بميزات AI — "تكامل في 5 دقائق". المشهد 4: صفحة الأسعار — "ابدأ مجاناً".',
      visualDirection: 'لقطات تسجيل من فوق الكتف ممزوجة بتسجيلات الشاشة. سمة داكنة. طرفية خضراء على خلفية سوداء. قصات سريعة تتوافق مع الموسيقى.',
      textOverlay: 'API AI — باقة مجانية متاحة',
      cta: 'احصل على مفتاح API — رابط السيرة',
      duration: '20-30 ثانية',
    },
    {
      id: 'ig-ar-04',
      name: 'حزمة القوالب Story',
      type: 'story',
      script: 'قصة من 3 إطارات. الإطار 1: شبكة 6 قوالب — "6 قوالب. €299." الإطار 2: أبرز القوالب — "NeuraStore وNeuraBlog وNeuraPortfolio..." الإطار 3: تسليط الضوء على التوفير — "وفّر أكثر من €400" مع زر دعوة للعمل.',
      visualDirection: 'تخطيط شبكة المنتجات. كل قالب معروض كنموذج جهاز. خلفية تدرج بنفسجي. خطوط عريضة.',
      textOverlay: 'الحزمة الكاملة — €299 — وفّر أكثر من €400',
      cta: 'احصل على الحزمة',
      duration: '15 ثانية لكل إطار',
    },
    {
      id: 'ig-ar-05',
      name: 'شهادة مطور Reel',
      type: 'reel',
      script: 'المشهد 1: مطور يصور نفسه — "أطلقت SaaS في يومين باستخدام AI Empire". المشهد 2: تسجيل شاشة للتطبيق المنشور. المشهد 3: مقتطفات أكواد تكامل. المشهد 4: غطاء دعوة للعمل.',
      visualDirection: 'أسلوب UGC أصيل. إضاءة طبيعية. إحساس بالكاميرا المحمولة. ترجمة لسهولة الوصول.',
      textOverlay: '"أطلق في يومين" — @developer',
      cta: 'ابدأ البناء — رابط السيرة',
      duration: '30 ثانية',
    },
    {
      id: 'ig-ar-06',
      name: 'مميزات NeuraBlog Story',
      type: 'story',
      script: 'جولة في NeuraBlog: محرر MDX وتبديل الوضع المظلم والعرض المتجاوب على الهاتف ومعاينة خلاصة RSS وقسم التعليقات. اختم بالسعر (€19) ودعوة للعمل.',
      visualDirection: 'تسجيل شاشة بتأثير تكبير على الميزات الرئيسية. شاشة منقسمة تُظهر الوضع الفاتح/الداكن. جمالية نظيفة وبسيطة.',
      textOverlay: 'NeuraBlog — €19 — قالب مدونة SEO',
      cta: 'اسحب للأعلى — شاهد القالب',
      duration: '15 ثانية',
    },
    {
      id: 'ig-ar-07',
      name: 'تحدي سرعة SaaS Reel',
      type: 'reel',
      script: 'تسجيل بطيء لبناء SaaS من الصفر. مؤقت يظهر من 0:00 إلى 4:00:00. أظهر اختيار القالب وإعداد API وتكوين Stripe والنشر. اختم برابط مباشر.',
      visualDirection: 'شاشة منقسمة: مؤقت على اليسار وتسجيل شاشة على اليمين. تأثير تسريع. موسيقى خلفية حيوية. علامات ميل عند الساعة 1 و2 و3.',
      textOverlay: 'بنينا SaaS في 4 ساعات',
      cta: 'جرّب AI Empire — رابط السيرة',
      duration: '30-60 ثانية',
    },
    {
      id: 'ig-ar-08',
      name: 'إعلان الباقة المجانية Story',
      type: 'story',
      script: 'كشف خطوط عريضة: "مجاني" ← "AI API" ← "100 رصيد" ← "Groq وGemini" ← "لا حاجة لبطاقة ائتمان" ← دعوة للعمل. كل عنصر نصي يظهر بتأثير ارتداد أو انزلاق.',
      visualDirection: 'خلفيات بنفسجية/داكنة مصغرة. نص أبيض عريض كبير. تصميم بسيط. كل إطار ينتقل بحركة حماسية.',
      textOverlay: 'AI API مجاني — 100 رصيد — لا حاجة لبطاقة',
      cta: 'سجّل مجاناً',
      duration: '10 ثانية إجمالاً',
    },
    {
      id: 'ig-ar-09',
      name: 'عرض NeuraPortfolio Reel',
      type: 'reel',
      script: 'استعراض رسوم متحركة NeuraPortfolio: تأثير مظلي لقسم البطل وتأثير تمرير على بطاقات المشاريع وانتقال سلس بين الصفحات والوضع المظلم. كل ذلك على نموذج MacBook.',
      visualDirection: 'نموذج جهاز بحركة بطيء أنيقة. حركات كاميرا خفيفة. إضاءة ناعمة. موسيقى خلفية بسيطة. التركيز على جودة الرسوم المتحركة.',
      textOverlay: 'NeuraPortfolio — €29 — معرض مطورين',
      cta: 'رابط السيرة — شاهد العرض التوضيحي',
      duration: '20-30 ثانية',
    },
    {
      id: 'ig-ar-10',
      name: 'قصة المقارنة Story',
      type: 'story',
      script: 'الإطار 1: "البناء من الصفر: 3-6 أشهر" مع أيقونة تقويم. الإطار 2: "باستخدام AI Empire: 1-2 يوم" مع أيقونة صاروخ. الإطار 3: "النتيجة نفسها. 95% وقت أقل." الإطار 4: دعوة للعمل مع الأسعار.',
      visualDirection: 'تخطيط مقارنة جانبي بجانب. أسلوب قبل/بعد. اللون الأحمر لخيار "البطيء" والأخضر لـ AI Empire. خطوط تأثير قوية.',
      textOverlay: '3 أشهر مقابل يومين — اختر السرعة',
      cta: 'ابدأ الآن — رابط السيرة',
      duration: '15 ثانية لكل إطار',
    },
  ],
};
