import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'de',
  googleSearch: [
    // === Kampagne 1: KI-API-Plattform ===
    {
      id: 'g-de-01',
      name: 'KI-API-Plattform',
      objective: 'Anmeldungen für die kostenlose KI-API-Stufe generieren',
      budget: '500 €/Monat',
      adGroups: [
        {
          id: 'g-de-01-brand',
          name: 'Marke',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'ai empire plattform'],
          ads: [
            { id: 'g-de-01-brand-1', headline: 'AI Empire — Einheitliche KI-API-Plattform', description: 'Greifen Sie über eine einzige API auf Groq und Gemini zu. Kostenfreie Stufe verfügbar, ohne Kreditkarte. Integration in 5 Minuten.', cta: 'Kostenlos testen' },
            { id: 'g-de-01-brand-2', headline: 'AI Empire — Ihr KI-API-Gateway', description: 'Eine API, mehrere KI-Modelle. Groq + Gemini. Kostenfreie Credits bei der Anmeldung. JavaScript- und Python-SDKs inklusive.', cta: 'API-Schlüssel erhalten' },
            { id: 'g-de-01-brand-3', headline: 'AI Empire — Entwickeln Sie heute mit KI', description: 'Produktionsreife KI-APIs. Groq für Geschwindigkeit, Gemini für Leistungsfähigkeit. Kostenfreie Stufe, nutzungsbasierte Abrechnung.', cta: 'Jetzt entwickeln' },
          ],
        },
        {
          id: 'g-de-01-competitor',
          name: 'Wettbewerber',
          keywords: ['openai alternative', 'groq api alternative', 'günstigere ki api', 'gemini api wrapper', 'ki api vergleich'],
          ads: [
            { id: 'g-de-01-comp-1', headline: 'Günstige KI-API — Sparen Sie gegenüber OpenAI', description: 'Gleiche KI-Qualität zu niedrigeren Kosten. Groq + Gemini vereinheitlicht. Kostenfreie Stufe mit 100 Credits. Wechsel in Minuten.', cta: 'Preise vergleichen' },
            { id: 'g-de-01-comp-2', headline: 'OpenAI-Alternative — AI Empire', description: 'Auf der Suche nach einer kostengünstigen KI-API? AI Empire kombiniert Groq und Gemini in einem Endpoint. Kostenlos zum Starten.', cta: 'Pläne ansehen' },
            { id: 'g-de-01-comp-3', headline: 'KI-API — 70% weniger als OpenAI', description: 'Erzielen Sie GPT-Qualität mit Groq und Gemini. Vereinheitlichte API. Kostenfreie Stufe. Keine Anbieterbindung.', cta: 'Kostenlos starten' },
          ],
        },
        {
          id: 'g-de-01-generic',
          name: 'Generisch',
          keywords: ['ki api', 'künstliche intelligenz api', 'groq api', 'gemini api', 'ki für entwickler', 'kostenlose ki api'],
          ads: [
            { id: 'g-de-01-gen-1', headline: 'KI-API für Entwickler — Kostenfreie Stufe', description: 'Groq + Gemini über eine API. Kostenfreie Credits bei der Anmeldung. Dokumentation, Beispiele und SDKs inklusive.', cta: 'Dokumentation lesen' },
            { id: 'g-de-01-gen-2', headline: 'KI in Ihre App integrieren — 5 Min Einrichtung', description: 'Eine API für Groq und Gemini. Kostenfreie Stufe verfügbar. Stripe-Abrechnung. Vollständige Dokumentation.', cta: 'Loslegen' },
            { id: 'g-de-01-gen-3', headline: 'KI-APIs — Groq & Gemini kombiniert', description: 'Einheitlicher Endpoint für mehrere KI-Modelle. Kostenlos zum Starten, nutzungsbasiert beim Wachstum. Produktionsreif.', cta: 'API erkunden' },
          ],
        },
      ],
    },
    // === Kampagne 2: Next.js SaaS-Templates ===
    {
      id: 'g-de-02',
      name: 'Next.js SaaS-Templates',
      objective: 'Template-Verkäufe steigern',
      budget: '400 €/Monat',
      adGroups: [
        {
          id: 'g-de-02-brand',
          name: 'Marke',
          keywords: ['ai empire templates', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-de-02-brand-1', headline: 'AI Empire — SaaS-Templates für Next.js 14', description: 'Produktionsreife Templates mit KI-Integration. NeuraStore, NeuraBlog, NeuraPortfolio. Ab 19 €.', cta: 'Templates ansehen' },
            { id: 'g-de-02-brand-2', headline: 'NeuraStore & NeuraBlog von AI Empire', description: 'Professionelle Next.js 14-Templates mit Stripe, Authentifizierung und eingebauter KI. In Minuten bereitstellen.', cta: 'Templates ansehen' },
            { id: 'g-de-02-brand-3', headline: 'AI Empire Templates — Starten Sie Ihr SaaS', description: '6 Premium-Templates. Next.js 14, Tailwind, Stripe, KI-APIs inklusive. Ab 19 € bis Bundle für 299 €.', cta: 'Templates durchstöbern' },
          ],
        },
        {
          id: 'g-de-02-competitor',
          name: 'Wettbewerber',
          keywords: ['saas boilerplate', 'next.js template', 'react saas template', 'saas starter kit', 'nextjs ecommerce template'],
          ads: [
            { id: 'g-de-02-comp-1', headline: 'Next.js SaaS-Template — KI eingebaut', description: 'Anders als generische Boilerplates enthalten AI Empire-Templates KI-APIs, Stripe und Authentifizierung. Einsatzbereit.', cta: 'Templates vergleichen' },
            { id: 'g-de-02-comp-2', headline: 'Besser als ein SaaS-Boilerplate', description: 'AI Empire-Templates: professionelles Design, KI-Integration, Stripe-Abrechnung. Nicht nur Startcode.', cta: 'Unterschied sehen' },
            { id: 'g-de-02-comp-3', headline: 'Next.js 14-Template — Full-Stack bereit', description: 'Templates mit allem: UI, API, Authentifizierung, Zahlungen, KI. Heute bereitstellen.', cta: 'Templates ansehen' },
          ],
        },
        {
          id: 'g-de-02-generic',
          name: 'Generisch',
          keywords: ['saas template', 'nextjs 14 template', 'react template', 'saas landing page', 'template für saas', 'saas schnell bauen'],
          ads: [
            { id: 'g-de-02-gen-1', headline: 'SaaS-Templates — In Tagen starten, nicht in Monaten', description: 'Next.js 14-Templates mit Authentifizierung, Stripe, KI und Admin-Dashboard. Ab 19 €.', cta: 'Loslegen' },
            { id: 'g-de-02-gen-2', headline: 'Erstellen Sie ein SaaS mit Next.js 14', description: 'Produktionsreife Templates. Stripe-Abrechnung, Authentifizierung, KI-APIs, Admin-Panel inklusive.', cta: 'Templates erkunden' },
            { id: 'g-de-02-gen-3', headline: 'Next.js 14 E-Commerce & Blog-Templates', description: 'Professionelle Templates mit modernem Design. Responsive, Dark Mode, SEO-optimiert. Ab 19 €.', cta: 'Templates kaufen' },
          ],
        },
      ],
    },
    // === Kampagne 3: KI-Integration ===
    {
      id: 'g-de-03',
      name: 'KI-Integration',
      objective: 'Entwickler anziehen, die KI-Integration benötigen',
      budget: '350 €/Monat',
      adGroups: [
        {
          id: 'g-de-03-brand',
          name: 'Marke',
          keywords: ['ai empire integration', 'ai empire docs', 'ai empire sdk', 'ai empire api docs'],
          ads: [
            { id: 'g-de-03-brand-1', headline: 'AI Empire — Fügen Sie KI zu jeder App hinzu', description: 'Einfache API zum Hinzufügen von KI-Funktionen zu Ihrer App. Groq + Gemini. SDKs für JS und Python.', cta: 'Dokumentation lesen' },
            { id: 'g-de-03-brand-2', headline: 'AI Empire SDK — KI in 5 Minuten', description: 'Installieren, konfigurieren, bereitstellen. Unser SDK macht KI-Integration einfach. Kostenfreie Stufe verfügbar.', cta: 'SDK ansehen' },
            { id: 'g-de-03-brand-3', headline: 'AI Empire API-Docs — Beginnen Sie zu entwickeln', description: 'Umfassende Dokumentation, Code-Beispiele und Tutorials. Fügen Sie heute KI zu Ihrer Next.js-App hinzu.', cta: 'Dokumentation lesen' },
          ],
        },
        {
          id: 'g-de-03-competitor',
          name: 'Wettbewerber',
          keywords: ['ki integration service', 'ki in app einbetten', 'ki sdk', 'groq sdk', 'gemini sdk', 'ki api wrapper'],
          ads: [
            { id: 'g-de-03-comp-1', headline: 'Einfachere KI-Integration als individuelle Entwicklung', description: 'Hören Sie auf, mehrere KI-SDKs zu pflegen. AI Empire: eine API, mehrere Modelle. Kostenfreie Stufe.', cta: 'Jetzt vereinfachen' },
            { id: 'g-de-03-comp-2', headline: 'KI-Integration — Kein kompliziertes Setup', description: 'Ein API-Schlüssel, ein Endpoint. Groq und Gemini bereit. Kostenfreie Credits zum Testen. Dokumentation inklusive.', cta: 'Kostenlos testen' },
            { id: 'g-de-03-comp-3', headline: 'Ersetzen Sie Ihren KI-API-Wrapper', description: 'AI Empire bietet eine produktionsreife vereinheitlichte API. Abrechnung, Ratenbegrenzung und Monitoring inklusive.', cta: 'Mehr erfahren' },
          ],
        },
        {
          id: 'g-de-03-generic',
          name: 'Generisch',
          keywords: ['ki zu app hinzufügen', 'ki integrieren', 'ki api für web app', 'groq integration', 'gemini integration', 'ki api rest'],
          ads: [
            { id: 'g-de-03-gen-1', headline: 'KI zu Ihrer Web-App hinzufügen — Einfache REST-API', description: 'REST-API für Groq und Gemini. Kostenfreie Stufe. JSON-Antworten. Funktioniert mit jeder Sprache.', cta: 'Kostenlos starten' },
            { id: 'g-de-03-gen-2', headline: 'KI-API-Integration — Entwicklerfreundlich', description: 'Gut dokumentierte API mit SDKs für JavaScript und Python. Kostenfreie Stufe. Nutzungsbasierte Abrechnung.', cta: 'Dokumentation ansehen' },
            { id: 'g-de-03-gen-3', headline: 'Groq + Gemini API — Ein Endpoint', description: 'Einzelne API für mehrere KI-Modelle. Kostenfreie Credits. Stripe-Abrechnung. Produktionsreif.', cta: 'Loslegen' },
          ],
        },
      ],
    },
    // === Kampagne 4: SaaS-Starter-Kit ===
    {
      id: 'g-de-04',
      name: 'SaaS-Starter-Kit',
      objective: 'SaaS-Gründer und Indie-Hacker konvertieren',
      budget: '400 €/Monat',
      adGroups: [
        {
          id: 'g-de-04-brand',
          name: 'Marke',
          keywords: ['ai empire starter', 'ai empire saas kit', 'ai empire bundle', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-de-04-brand-1', headline: 'AI Empire — Vollständiges SaaS-Starter-Kit', description: 'Next.js 14, Stripe, Auth, KI-APIs, Admin-Dashboard. Alles zum Starten Ihres SaaS. Ab 19 €.', cta: 'Starter-Kit erhalten' },
            { id: 'g-de-04-brand-2', headline: 'Starten Sie Ihr SaaS mit AI Empire', description: '6 professionelle Templates. Stripe-Abrechnung, Authentifizierung, KI-APIs. In 24 Stunden bereitstellen.', cta: 'Templates ansehen' },
            { id: 'g-de-04-brand-3', headline: 'AI Empire Bundle — Alle Templates', description: '6 Templates + Prioritäts-Support + kostenlose Updates. Vollständiges SaaS-Starter-Kit für 299 €.', cta: 'Bundle erhalten' },
          ],
        },
        {
          id: 'g-de-04-competitor',
          name: 'Wettbewerber',
          keywords: ['saas starter kit', 'saas boilerplate nextjs', 'indie hacker toolkit', 'saas template full stack', 'saas schnell starten'],
          ads: [
            { id: 'g-de-04-comp-1', headline: 'SaaS-Starter-Kit — Mehr als ein Boilerplate', description: 'AI Empire enthält KI-APIs, Admin-Dashboard und echte Templates. Nicht nur Startcode.', cta: 'Funktionen vergleichen' },
            { id: 'g-de-04-comp-2', headline: 'Starten Sie Ihr SaaS in 24 Stunden', description: 'Warum Monate mit dem Bauen von Grund auf verbringen? AI Empire-Templates: heute bereitstellen, morgen iterieren.', cta: 'Templates ansehen' },
            { id: 'g-de-04-comp-3', headline: 'Indie-Hacker SaaS-Toolkit', description: 'Alles was Sie brauchen: Templates, KI-APIs, Stripe, Auth. Ab 19 €. Kostenfreie Stufe für die API.', cta: 'Jetzt entwickeln' },
          ],
        },
        {
          id: 'g-de-04-generic',
          name: 'Generisch',
          keywords: ['saas template', 'wie saas bauen', 'saas app template', 'next.js saas', 'stripe saas template', 'saas mvp'],
          ads: [
            { id: 'g-de-04-gen-1', headline: 'Erstellen Sie ein SaaS-MVP in Tagen', description: 'Next.js 14-Templates mit Stripe, Auth und KI. Ab 19 €. Auf Vercel bereitstellen.', cta: 'Loslegen' },
            { id: 'g-de-04-gen-2', headline: 'SaaS-Template — Stripe + Auth inklusive', description: 'Produktionsreife Next.js 14-Templates. Zahlungen, Authentifizierung, KI-APIs eingebaut.', cta: 'Templates erkunden' },
            { id: 'g-de-04-gen-3', headline: 'Full-Stack SaaS-Template — Next.js 14', description: 'Moderner Stack: Next.js 14, Tailwind, Stripe, KI. Templates ab 19 €.', cta: 'Templates ansehen' },
          ],
        },
      ],
    },
    // === Kampagne 5: Alternative zu OpenAI ===
    {
      id: 'g-de-05',
      name: 'Alternative zu OpenAI',
      objective: 'OpenAI-Vergleichsverkehr erfassen',
      budget: '300 €/Monat',
      adGroups: [
        {
          id: 'g-de-05-brand',
          name: 'Marke',
          keywords: ['ai empire vs openai', 'ai empire alternative', 'ai empire preise', 'günstiger als openai'],
          ads: [
            { id: 'g-de-05-brand-1', headline: 'AI Empire vs OpenAI — Gleiche Qualität, niedrigere Kosten', description: 'Groq und Gemini über AI Empire. Vereinheitlichte API mit kostenfreier Stufe. Bis zu 70% sparen gegenüber OpenAI.', cta: 'Preise vergleichen' },
            { id: 'g-de-05-brand-2', headline: 'Warum zu AI Empire von OpenAI wechseln', description: 'Niedrigere Kosten, mehrere Modelle, vereinheitlichte API, kostenfreie Stufe. In Minuten wechseln, ohne Code-Änderungen.', cta: 'Preise ansehen' },
            { id: 'g-de-05-brand-3', headline: 'AI Empire — Kostengünstige KI-API', description: 'Groq + Gemini. 70% günstiger als OpenAI bei vergleichbarer Qualität. Kostenfreie Credits bei der Anmeldung.', cta: 'Kostenlos starten' },
          ],
        },
        {
          id: 'g-de-05-competitor',
          name: 'Wettbewerber',
          keywords: ['openai alternative api', 'günstiger als openai api', 'openai preis alternative', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-de-05-comp-1', headline: 'Günstigere OpenAI-Alternative — Kostenlos testen', description: 'AI Empire: vereinheitlichte Groq + Gemini API. Kostenfreie Stufe, nutzungsbasiert. 70% weniger als OpenAI.', cta: 'Kostenlos testen' },
            { id: 'g-de-05-comp-2', headline: 'Groq & Gemini API — Besseres Preis-Leistungs-Verhältnis', description: 'Warum mehr zahlen? Groq für Geschwindigkeit, Gemini für Leistungsfähigkeit. Eine API, niedrigere Kosten. Kostenfreie Stufe.', cta: 'Pläne ansehen' },
            { id: 'g-de-05-comp-3', headline: 'Von OpenAI wechseln — 70% sparen', description: 'AI Empire bietet Groq + Gemini über eine vereinheitlichte API. Gleiche Qualität, ein Bruchteil der Kosten.', cta: 'Jetzt vergleichen' },
          ],
        },
        {
          id: 'g-de-05-generic',
          name: 'Generisch',
          keywords: ['ki api preise', 'ki api kosten', 'groq preise', 'gemini api preise', 'ki api vergleich', 'günstigste ki api'],
          ads: [
            { id: 'g-de-05-gen-1', headline: 'KI-API — Von kostenlos bis nutzungsbasiert', description: 'Kostenlos starten, bezahlbar skalieren. Groq + Gemini. Keine monatlichen Gebühren. Nur zahlen, was Sie nutzen.', cta: 'Preise ansehen' },
            { id: 'g-de-05-gen-2', headline: 'Bezahlbare KI-API — Groq + Gemini', description: 'Kostenfreie Stufe mit 100 Credits. Danach nutzungsbasiert. Keine Mindestbestellungen, keine Bindung.', cta: 'Loslegen' },
            { id: 'g-de-05-gen-3', headline: 'KI-API-Preise — Transparent und fair', description: 'Keine versteckten Gebühren. Groq + Gemini über eine API. Kostenfreie Stufe. Stripe-Abrechnung.', cta: 'Preise ansehen' },
          ],
        },
      ],
    },
    // === Kampagne 6: Alternative zu Vercel-Templates ===
    {
      id: 'g-de-06',
      name: 'Alternative zu Vercel-Templates',
      objective: 'Template-Vergleichsverkehr erfassen',
      budget: '250 €/Monat',
      adGroups: [
        {
          id: 'g-de-06-brand',
          name: 'Marke',
          keywords: ['ai empire vercel', 'ai empire bereitstellung', 'ai empire next.js', 'ai empire hosting'],
          ads: [
            { id: 'g-de-06-brand-1', headline: 'AI Empire Templates — Auf Vercel bereitstellen', description: 'Next.js 14-Templates für Vercel optimiert. KI-APIs, Stripe, Authentifizierung inklusive. In Minuten bereitstellen.', cta: 'Jetzt bereitstellen' },
            { id: 'g-de-06-brand-2', headline: 'Vercel-kompatible SaaS-Templates', description: 'AI Empire-Templates: für Vercel gebaut. One-Click-Bereitstellung. KI-Integration, Abrechnung, Authentifizierung.', cta: 'Templates ansehen' },
            { id: 'g-de-06-brand-3', headline: 'Next.js 14-Templates für Vercel', description: 'Professionelle Templates. In Minuten auf Vercel bereitstellen. KI-APIs und Stripe-Abrechnung eingebaut.', cta: 'Templates erhalten' },
          ],
        },
        {
          id: 'g-de-06-competitor',
          name: 'Wettbewerber',
          keywords: ['vercel template alternative', 'next.js template', 'besser als vercel template', 'saas template vercel', 'template saas bereitstellung'],
          ads: [
            { id: 'g-de-06-comp-1', headline: 'Mehr als grundlegende Templates — AI Empire', description: 'Anders als grundlegende Vercel-Templates enthält AI Empire KI-APIs, Stripe und Admin-Dashboard.', cta: 'Funktionen ansehen' },
            { id: 'g-de-06-comp-2', headline: 'Next.js-Template mit KI & Stripe', description: 'AI Empire: nicht nur ein Template, ein vollständiges SaaS-Starter-Kit. KI-APIs, Abrechnung, Authentifizierung inklusive.', cta: 'Vergleichen' },
            { id: 'g-de-06-comp-3', headline: 'Produktionsreife SaaS-Templates — Next.js 14', description: 'Jenseits von Demo-Templates. AI Empire: echte Authentifizierung, echte Zahlungen, echte KI-Integration.', cta: 'Templates ansehen' },
          ],
        },
        {
          id: 'g-de-06-generic',
          name: 'Generisch',
          keywords: ['next.js bereitstellung template', 'saas template bereitstellung', 'vercel saas', 'nextjs 14 bereitstellung', 'saas bereitstellung template', 'template vercel bereitstellung'],
          ads: [
            { id: 'g-de-06-gen-1', headline: 'Stellen Sie Ihr SaaS heute auf Vercel bereit', description: 'Next.js 14-Templates. One-Click-Bereitstellung. KI, Stripe, Auth inklusive. Ab 19 €.', cta: 'Jetzt bereitstellen' },
            { id: 'g-de-06-gen-2', headline: 'SaaS-Template — Bereit zur Bereitstellung', description: 'Professionelle Next.js 14-Templates. In Minuten auf Vercel bereitstellen. Full Stack inklusive.', cta: 'Loslegen' },
            { id: 'g-de-06-gen-3', headline: 'Next.js 14 SaaS — In Minuten bereitstellen', description: 'Templates mit allem: Auth, Zahlungen, KI, Admin. Sofort auf Vercel bereitstellen.', cta: 'Templates erkunden' },
          ],
        },
      ],
    },
    // === Kampagne 7: E-Commerce-Template ===
    {
      id: 'g-de-07',
      name: 'E-Commerce-Template — NeuraStore',
      objective: 'NeuraStore-Template-Verkäufe steigern',
      budget: '300 €/Monat',
      adGroups: [
        {
          id: 'g-de-07-brand',
          name: 'Marke',
          keywords: ['neurastore', 'ai empire ecommerce', 'neurastore template', 'neurastore next.js'],
          ads: [
            { id: 'g-de-07-brand-1', headline: 'NeuraStore — KI-gestütztes E-Commerce-Template', description: 'Next.js 14 E-Commerce-Template mit Stripe, Warenkorb, Admin-Dashboard. KI-Produktempfehlungen.', cta: 'NeuraStore ansehen' },
            { id: 'g-de-07-brand-2', headline: 'NeuraStore — Starten Sie Ihren Online-Shop', description: 'Professionelles E-Commerce-Template. Stripe-Zahlungen, Lagerverwaltung, responsives Design.', cta: 'Demo ansehen' },
            { id: 'g-de-07-brand-3', headline: 'NeuraStore von AI Empire — 29 €', description: 'Vollständiges E-Commerce-Template. Next.js 14, Stripe, Tailwind. In Minuten bereitstellen.', cta: 'NeuraStore kaufen' },
          ],
        },
        {
          id: 'g-de-07-competitor',
          name: 'Wettbewerber',
          keywords: ['ecommerce template next.js', 'online shop template', 'shopify alternative template', 'react ecommerce template', 'nextjs shop template'],
          ads: [
            { id: 'g-de-07-comp-1', headline: 'E-Commerce-Template — Besitzen Sie Ihren Shop', description: 'Anders als Shopify gehört NeuraStore Ihnen. Selbstgehostet, anpassbar, KI-gestützt. 29 €.', cta: 'NeuraStore erhalten' },
            { id: 'g-de-07-comp-2', headline: 'Next.js E-Commerce — Vollständige Kontrolle', description: 'NeuraStore: Besitzen Sie Ihren Code, Ihre Daten, Ihren Shop. Stripe-Integration, Admin-Dashboard.', cta: 'Template ansehen' },
            { id: 'g-de-07-comp-3', headline: 'Erstellen Sie Ihren eigenen Online-Shop', description: 'NeuraStore-Template: Next.js 14, Stripe, responsives Design, Admin-Panel. 29 €.', cta: 'Jetzt entwickeln' },
          ],
        },
        {
          id: 'g-de-07-generic',
          name: 'Generisch',
          keywords: ['ecommerce website template', 'online shop template', 'nextjs ecommerce', 'online shop erstellen', 'saas ecommerce template', 'digitaler shop template'],
          ads: [
            { id: 'g-de-07-gen-1', headline: 'E-Commerce-Website-Template — Next.js 14', description: 'Professionelles Online-Shop-Template. Stripe, Warenkorb, Admin. Responsive, Dark Mode. 29 €.', cta: 'Template kaufen' },
            { id: 'g-de-07-gen-2', headline: 'Erstellen Sie einen Online-Shop mit Next.js', description: 'NeuraStore: vollständige E-Commerce-Lösung. Zahlungen, Lagerverwaltung, KI-Empfehlungen.', cta: 'Loslegen' },
            { id: 'g-de-07-gen-3', headline: 'Online-Shop-Template — Bereit zum Starten', description: 'Next.js 14 E-Commerce-Template. Stripe-Abrechnung, responsives Design, SEO-optimiert. 29 €.', cta: 'Jetzt bereitstellen' },
          ],
        },
      ],
    },
    // === Kampagne 8: Blog-Template ===
    {
      id: 'g-de-08',
      name: 'Blog-Template — NeuraBlog',
      objective: 'NeuraBlog-Template-Verkäufe steigern',
      budget: '250 €/Monat',
      adGroups: [
        {
          id: 'g-de-08-brand',
          name: 'Marke',
          keywords: ['neurablog', 'ai empire blog', 'neurablog template', 'neurablog next.js'],
          ads: [
            { id: 'g-de-08-brand-1', headline: 'NeuraBlog — SEO-optimiertes Blog-Template', description: 'Next.js 14 Blog-Template mit MDX, Dark Mode, RSS-Feed. Newsletter-Integration eingebaut.', cta: 'NeuraBlog ansehen' },
            { id: 'g-de-08-brand-2', headline: 'NeuraBlog — Professioneller Blog in Minuten', description: 'Premium-Blog-Template. MDX-Unterstützung, SEO-Optimierung, Kommentarsystem. 19 €.', cta: 'Demo ansehen' },
            { id: 'g-de-08-brand-3', headline: 'NeuraBlog von AI Empire — 19 €', description: 'Vollständiges Blog-Template. Next.js 14, MDX, Dark Mode, RSS. Auf Vercel bereitstellen.', cta: 'NeuraBlog kaufen' },
          ],
        },
        {
          id: 'g-de-08-competitor',
          name: 'Wettbewerber',
          keywords: ['blog template next.js', 'wordpress alternative', 'ghost alternative', 'mdx blog template', 'react blog template'],
          ads: [
            { id: 'g-de-08-comp-1', headline: 'Blog-Template — Schneller als WordPress', description: 'NeuraBlog: statische Website-Geschwindigkeit, dynamische Funktionen. MDX, SEO, Newsletter. 19 €.', cta: 'NeuraBlog testen' },
            { id: 'g-de-08-comp-2', headline: 'MDX-Blog-Template — Next.js 14', description: 'Anders als Ghost gibt Ihnen NeuraBlog volle Kontrolle. Selbstgehostet, schnell, anpassbar.', cta: 'Template ansehen' },
            { id: 'g-de-08-comp-3', headline: 'Ihr Blog, Ihr Code — NeuraBlog', description: 'Besitzen Sie Ihre Content-Plattform. NeuraBlog: Next.js 14, MDX, Dark Mode, RSS. 19 €.', cta: 'NeuraBlog erhalten' },
          ],
        },
        {
          id: 'g-de-08-generic',
          name: 'Generisch',
          keywords: ['blog template', 'persönliches blog template', 'nextjs blog', 'tech blog template', 'blog starten', 'blog website template'],
          ads: [
            { id: 'g-de-08-gen-1', headline: 'Blog-Template — Starten Sie Ihren Blog heute', description: 'Professionelles Blog-Template. SEO-optimiert, Dark Mode, Newsletter. In Minuten bereitstellen. 19 €.', cta: 'Jetzt bloggen' },
            { id: 'g-de-08-gen-2', headline: 'Next.js 14 Blog — Schnell & Schön', description: 'NeuraBlog: modernes Blog-Template. MDX, Dark Mode, RSS, Kommentarsystem. 19 €.', cta: 'Template ansehen' },
            { id: 'g-de-08-gen-3', headline: 'Erstellen Sie einen professionellen Blog — 19 €', description: 'NeuraBlog-Template. SEO-optimiert, responsiv, Dark Mode. Auf Vercel bereitstellen.', cta: 'Loslegen' },
          ],
        },
      ],
    },
    // === Kampagne 9: Portfolio-Template ===
    {
      id: 'g-de-09',
      name: 'Portfolio-Template — NeuraPortfolio',
      objective: 'NeuraPortfolio-Template-Verkäufe steigern',
      budget: '200 €/Monat',
      adGroups: [
        {
          id: 'g-de-09-brand',
          name: 'Marke',
          keywords: ['neuraportfolio', 'ai empire portfolio', 'neuraportfolio template', 'entwickler portfolio template'],
          ads: [
            { id: 'g-de-09-brand-1', headline: 'NeuraPortfolio — Entwickler-Portfolio-Template', description: 'Professionelles Portfolio mit Animationen, Dark Mode, Kontaktformular. Next.js 14. 29 €.', cta: 'NeuraPortfolio ansehen' },
            { id: 'g-de-09-brand-2', headline: 'NeuraPortfolio — Heben Sie sich Online hervor', description: 'Atemberaubendes Portfolio-Template. Framer-Motion-Animationen, responsiv, Dark Mode. 29 €.', cta: 'Demo ansehen' },
            { id: 'g-de-09-brand-3', headline: 'NeuraPortfolio von AI Empire — 29 €', description: 'Vollständiges Portfolio-Template. Next.js 14, Animationen, Dark Mode, Kontaktformular.', cta: 'NeuraPortfolio kaufen' },
          ],
        },
        {
          id: 'g-de-09-competitor',
          name: 'Wettbewerber',
          keywords: ['entwickler portfolio template', 'portfolio website template', 'bestes portfolio template', 'kreatives portfolio template', 'freelancer portfolio'],
          ads: [
            { id: 'g-de-09-comp-1', headline: 'Portfolio-Template — Einen Eindruck hinterlassen', description: 'NeuraPortfolio: wunderschöne Animationen, responsives Design, Dark Mode. Besser als generische Themes.', cta: 'Template ansehen' },
            { id: 'g-de-09-comp-2', headline: 'Ihr Portfolio sollte sich abheben', description: 'NeuraPortfolio: Framer-Motion-Animationen, modernes Design, vollständige Anpassbarkeit. 29 €.', cta: 'NeuraPortfolio ansehen' },
            { id: 'g-de-09-comp-3', headline: 'Entwickler-Portfolio — Next.js 14', description: 'Erstellen Sie Ihr Portfolio mit NeuraPortfolio. Schnell, schön, in Minuten bereitstellbar.', cta: 'Loslegen' },
          ],
        },
        {
          id: 'g-de-09-generic',
          name: 'Generisch',
          keywords: ['portfolio website', 'portfolio erstellen', 'online portfolio', 'persönliche website template', 'freelancer portfolio template', 'portfolio showcase'],
          ads: [
            { id: 'g-de-09-gen-1', headline: 'Erstellen Sie Ihr Online-Portfolio — 29 €', description: 'NeuraPortfolio: professionelles Template mit Animationen. In Minuten bereitstellen.', cta: 'Jetzt entwickeln' },
            { id: 'g-de-09-gen-2', headline: 'Persönliches Website-Template — Next.js 14', description: 'Wunderschönes Portfolio-Template. Dark Mode, Animationen, responsiv. Ab 29 €.', cta: 'Templates ansehen' },
            { id: 'g-de-09-gen-3', headline: 'Portfolio-Template — Heute bereitstellen', description: 'Professionelles Portfolio mit modernem Design. Framer Motion, Dark Mode. 29 €.', cta: 'Portfolio erhalten' },
          ],
        },
      ],
    },
    // === Kampagne 10: KI-SaaS-Builder ===
    {
      id: 'g-de-10',
      name: 'KI-SaaS-Builder',
      objective: 'KI-SaaS-Building-Absicht erfassen',
      budget: '350 €/Monat',
      adGroups: [
        {
          id: 'g-de-10-brand',
          name: 'Marke',
          keywords: ['ai empire saas builder', 'ai empire saas bauen', 'ai empire starten', 'ai empire plattform'],
          ads: [
            { id: 'g-de-10-brand-1', headline: 'AI Empire — Bauen Sie Ihr KI-SaaS', description: 'Templates + KI-APIs + Stripe + Auth. Alles zum Bauen und Starten eines KI-gestützten SaaS.', cta: 'Jetzt entwickeln' },
            { id: 'g-de-10-brand-2', headline: 'AI Empire — Ihre KI-SaaS-Plattform', description: 'Von der Idee zum Launch. Templates, KI-APIs, Zahlungen, Authentifizierung. In 24 Stunden bereitstellen.', cta: 'Jetzt starten' },
            { id: 'g-de-10-brand-3', headline: 'AI Empire — Bringen Sie Ihr SaaS schneller raus', description: 'Professionelle Templates mit KI-Integration. Stripe, Authentifizierung, Admin-Dashboard. Ab 19 €.', cta: 'Loslegen' },
          ],
        },
        {
          id: 'g-de-10-competitor',
          name: 'Wettbewerber',
          keywords: ['ki saas bauen', 'saas builder', 'ki saas template', 'saas ki plattform', 'saas mit ki bauen', 'ki produkt builder'],
          ads: [
            { id: 'g-de-10-comp-1', headline: 'Ein KI-SaaS bauen — Nicht von Grund auf', description: 'AI Empire: professionelle Templates mit eingebauten KI-APIs. Monate der Entwicklung einsparen.', cta: 'Templates ansehen' },
            { id: 'g-de-10-comp-2', headline: 'KI-SaaS-Builder — In Tagen ausliefern', description: 'Templates, KI-APIs, Stripe, Auth. AI Empire: alles was Sie zum Starten brauchen.', cta: 'Funktionen vergleichen' },
            { id: 'g-de-10-comp-3', headline: 'Ihr KI-SaaS — Diese Woche starten', description: 'Warum von Grund auf bauen? AI Empire-Templates: in 24 Stunden bereitstellen. KI-Integration inklusive.', cta: 'Kostenlos starten' },
          ],
        },
        {
          id: 'g-de-10-generic',
          name: 'Generisch',
          keywords: ['saas template', 'saas bauen', 'saas app', 'saas plattform', 'ki produkt template', 'saas ideen', 'saas starten'],
          ads: [
            { id: 'g-de-10-gen-1', headline: 'Ein SaaS bauen — Templates, KI, Zahlungen', description: 'Next.js 14-Templates mit KI-APIs, Stripe, Auth. Ab 19 €. Heute bereitstellen.', cta: 'Loslegen' },
            { id: 'g-de-10-gen-2', headline: 'SaaS-Builder — Alles inklusive', description: 'Templates, KI-Integration, Zahlungen, Admin-Dashboard. Vollständiges SaaS-Toolkit. Ab 19 €.', cta: 'Templates erkunden' },
            { id: 'g-de-10-gen-3', headline: 'Bringen Sie Ihre SaaS-Idee raus — Next.js 14', description: 'Professionelle Templates mit modernem Stack. KI, Stripe, Auth. In Minuten bereitstellen.', cta: 'Jetzt entwickeln' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Bewusstsein (2)
    {
      id: 'fb-de-01',
      name: 'AI Empire Markenbekanntheit',
      type: 'awareness',
      objective: 'Markenbekanntheit bei Entwicklern und Startup-Gründern steigern',
      audience: 'Entwickler, CTOs, Startup-Gründer, 22-45 Jahre, interessiert an KI, SaaS, Next.js, Webentwicklung',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Bauen Sie ein SaaS? AI Empire bietet Ihnen Next.js 14-Templates, eingebaute KI-APIs (Groq + Gemini), Stripe-Abrechnung und Authentifizierung — alles ab 19 €. Schließen Sie sich über 5.000 Entwicklern an, die schneller gestartet sind.',
      cta: 'Mehr erfahren',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-de-02',
      name: 'KI-API-Wertversprechen',
      type: 'awareness',
      objective: 'Entwickler über die einheitliche KI-API aufklären',
      audience: 'Software-Entwickler, ML-Ingenieure, KI-Enthusiasten, 22-40 Jahre',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'Eine einzige API für Groq und Gemini. AI Empire bietet einen einheitlichen Endpoint für mehrere KI-Modelle — kostenlos zum Starten, nutzungsbasiert beim Wachsen. Hören Sie auf, mehrere KI-SDKs zu verwalten.',
      cta: 'Kostenlos testen',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Überlegung (3)
    {
      id: 'fb-de-03',
      name: 'NeuraStore-Produktpräsentation',
      type: 'consideration',
      objective: 'Traffic zur NeuraStore-Template-Seite leiten',
      audience: 'E-Commerce-Entwickler, Online-Shop-Betreiber, Shopify-Nutzer auf Alternativen-Suche',
      placements: ['Facebook Feed', 'Instagram Feed', 'Marketplace'],
      adCopy: 'NeuraStore: ein vollständiges E-Commerce-Template gebaut mit Next.js 14. Stripe-Zahlungen, Warenkorb-Verwaltung, Admin-Dashboard und KI-Produktempfehlungen. 29 € — Besitzen Sie Ihren Shop, besitzen Sie Ihren Code.',
      cta: 'Template ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-de-04',
      name: 'Template-Bundle-Angebot',
      type: 'consideration',
      objective: 'Interesse am vollständigen Template-Bundle wecken',
      audience: 'SaaS-Gründer, Indie-Hacker, Full-Stack-Entwickler',
      placements: ['Facebook Feed', 'Instagram Feed', 'Facebook Marketplace'],
      adCopy: 'Erhalten Sie alle 6 AI Empire-Templates für 299 €. NeuraStore, NeuraBlog, NeuraPortfolio und 3 weitere. Prioritäts-Support, kostenlose Updates, alles inklusive. Sparen Sie über 400 € gegenüber dem Einzelkauf.',
      cta: 'Bundle ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-de-05',
      name: 'KI-Integration-Tutorial',
      type: 'consideration',
      objective: 'Entwickler mit Bildungsinhalten einbinden',
      audience: 'Web-Entwickler, React-Entwickler, Node.js-Entwickler',
      placements: ['Facebook Feed', 'Instagram Reels', 'Stories'],
      adCopy: 'Fügen Sie KI zu Ihrer Next.js-App in 5 Minuten hinzu. Das SDK von AI Empire macht die Integration einfach — ein API-Schlüssel, ein Endpoint. Kostenfreie Stufe mit 100 Credits. Dokumentation und Beispiele inklusive.',
      cta: 'Dokumentation lesen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Konversion (3)
    {
      id: 'fb-de-06',
      name: 'Kostenlose API-Anmeldung',
      type: 'conversion',
      objective: 'Kostenlose Stufen-Anmeldungen generieren',
      audience: 'Website-Besucher, Dokumentationsleser, Blog-Leser, Ähnliche Zielgruppen',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Ihre kostenlose KI-API wartet auf Sie. Melden Sie sich bei AI Empire an und erhalten Sie 100 Credits für Groq und Gemini. Keine Kreditkarte erforderlich. Beginnen Sie heute mit der KI-Entwicklung.',
      cta: 'Kostenlos anmelden',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-de-07',
      name: 'Template-Kauf-Konversion',
      type: 'conversion',
      objective: 'Template-Seiten-Besucher zu Käufern konvertieren',
      audience: 'Template-Seiten-Besucher, Warenkorb-abbrecher, Nutzer mit hoher Kaufabsicht',
      placements: ['Facebook Feed', 'Instagram Feed', 'Messenger'],
      adCopy: 'Noch unsicher? NeuraBlog (19 €) und NeuraStore (29 €) sind einsatzbereit. Stripe, Authentifizierung, KI-Integration inklusive. Geld-zurück-Garantie.',
      cta: 'Jetzt kaufen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-de-08',
      name: 'Zeitlich begrenztes Bundle-Angebot',
      type: 'conversion',
      objective: 'Bundle-Käufe mit Dringlichkeit fördern',
      audience: 'Newsletter-Abonnenten, Warenkorb-abbrecher, hochengagierte Nutzer',
      placements: ['Facebook Feed', 'Instagram Feed', 'Instagram Stories'],
      adCopy: 'Begrenztes Angebot: Erhalten Sie das vollständige AI Empire-Template-Bundle für 299 € (sparen Sie über 400 €). Enthält alle 6 Templates, Prioritäts-Support und kostenlose Updates. Angebot endet bald.',
      cta: 'Bundle erhalten',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Retargeting (2)
    {
      id: 'fb-de-09',
      name: 'Rückkehr-Besucher — Templates',
      type: 'retargeting',
      objective: 'Besucher neu aktivieren, die sich Templates angesehen haben ohne zu kaufen',
      audience: 'Template-Seiten-Besucher (7-30 Tage), kein Kauf abgeschlossen',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Sie haben sich AI Empire-Templates angesehen. NeuraBlog beginnt bei 19 €, NeuraStore bei 29 €. Full-Stack, einsatzbereit, mit KI integriert. Kommen Sie zurück und starten Sie Ihr SaaS.',
      cta: 'Templates ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-de-10',
      name: 'Rückkehr-Besucher — API',
      type: 'retargeting',
      objective: 'Besucher neu aktivieren, die die API-Dokumentation erkundet haben ohne sich anzumelden',
      audience: 'Dokumentationsseiten-Besucher (7-30 Tage), kein Konto erstellt',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'Sie haben unsere API-Dokumentation erkundet. Bereit zum Entwickeln? AI Empire bietet Ihnen kostenlose Credits für Groq und Gemini. In 30 Sekunden anmelden, ohne Kreditkarte.',
      cta: 'Kostenlos starten',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Gesponserte Inhalte (4)
    {
      id: 'li-de-01',
      name: 'SaaS-Start-Ankündigung',
      type: 'sponsored_content',
      objective: 'Anmeldungen von technischen Entscheidern generieren',
      audience: 'CTOs, Tech Leads, Engineering Manager in Startups und KMU',
      headline: 'Starten Sie Ihr SaaS 10x schneller mit AI Empire',
      body: 'AI Empire bietet Next.js 14-Templates mit eingebauten KI-APIs (Groq + Gemini), Stripe-Abrechnung und Authentifizierung. Von der Idee zum bereitgestellten SaaS in 24 Stunden, nicht in Monaten.\n\nWas enthalten ist:\n- 6 produktionsreife Templates (19 € - 299 €)\n- Einheitliche KI-API mit kostenfreier Stufe\n- Stripe + Auth konfiguriert\n- Admin-Dashboard\n\nSchließen Sie sich über 5.000 Entwicklern an, die mit AI Empire bauen.',
      cta: 'Jetzt entwickeln',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-de-02',
      name: 'KI-API für Unternehmen',
      type: 'sponsored_content',
      objective: 'Technische Führungskräfte erreichen, die KI-API-Lösungen evaluieren',
      audience: 'Engineering Manager, VP Engineering, Architekten in mittelständischen und großen Unternehmen',
      headline: 'Einheitliche KI-API — Groq + Gemini für Ihr Team',
      body: 'Hören Sie auf, mehrere KI-Anbieter-Beziehungen zu pflegen. AI Empire bietet eine API für Groq und Gemini — mit eingebauter Abrechnung, Ratenbegrenzung und Monitoring.\n\nWarum technische Teams AI Empire wählen:\n- Ein Endpoint für mehrere KI-Modelle\n- JavaScript- und Python-SDKs\n- Kostenfreie Stufe für Prototyping\n- Nutzungsbasierte Skalierung\n\nReduzieren Sie Ihre KI-Integrationskomplexität.',
      cta: 'API erkunden',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-de-03',
      name: 'Indie-Hacker-Erfolg',
      type: 'sponsored_content',
      objective: 'Indie-Hacker und Solo-Gründer anziehen',
      audience: 'Indie-Hacker, Solo-Gründer, Bootstrapped-Startup-Gründer',
      headline: 'Bringen Sie Ihr SaaS dieses Wochenende raus',
      body: 'Gebaut für Solo-Gründer, die schnell vorankommen wollen.\n\nAI Empire bietet Ihnen:\n- Professionelle Next.js 14-Templates\n- KI-APIs einsatzbereit\n- Stripe in 5 Minuten konfiguriert\n- Keine Programmierung für den Launch nötig\n\nTemplates ab 19 €. Mit einem Klick auf Vercel bereitstellen.\n\nHören Sie auf, zu viel nachzudenken. Fangen Sie an, auszuliefern.',
      cta: 'Templates ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-de-04',
      name: 'Kostenvergleich',
      type: 'sponsored_content',
      objective: 'Kostenbewusste Teams ansprechen, die KI-Anbieter vergleichen',
      audience: 'CTOs, Finanzverantwortliche, Einkäufer in Startups und KMU',
      headline: 'KI-APIs — 70% weniger als Wettbewerber',
      body: 'AI Empire kombiniert Groq und Gemini in einer API. Zahlen Sie nur, was Sie nutzen.\n\nVergleich:\n- OpenAI: 0,03 €/1K Tokens (GPT-4)\n- AI Empire: ~0,009 €/1K Tokens (Groq Llama)\n\nKostenfreie Stufe inklusive. Keine Anbieterbindung. In Minuten wechseln.\n\nÜber 5.000 Entwickler sparen bereits.',
      cta: 'Preise ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Nachrichten-Werbung (3)
    {
      id: 'li-de-05',
      name: 'Direktansprache — CTOs',
      type: 'message_ads',
      objective: 'Personalisierte Ansprache von CTOs in Zielunternehmen',
      audience: 'CTOs in Unternehmen mit 10-200 Mitarbeitern in Tech, SaaS und E-Commerce',
      headline: 'Schnelle Frage zu Ihrem KI-Stack',
      body: 'Hallo {{first_name}},\n\nIch habe gesehen, dass {{company}} mit KI arbeitet. Kurze Frage: Verwalten Sie mehrere KI-Anbieter-APIs?\n\nAI Empire bietet eine einheitliche API für Groq und Gemini — ein Endpoint, eine Rechnung, ein Dashboard. Kostenfreie Stufe inklusive.\n\nWäre ein 10-minütiges Gespräch sinnvoll? Ich zeige Ihnen gerne, wie es funktioniert.',
      cta: 'Chat vereinbaren',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-de-06',
      name: 'Direktansprache — Entwickler',
      type: 'message_ads',
      objective: 'Einzelne Entwickler mit personalisierten Angeboten einbinden',
      audience: 'Full-Stack-Entwickler, React/Next.js-Entwickler in Tech-Unternehmen',
      headline: 'Entwickeln Sie mit Next.js?',
      body: 'Hallo {{first_name}},\n\nIch habe gesehen, dass Sie mit Next.js arbeiten. Wir haben AI Empire speziell für das Next.js-Ökosystem gebaut — Templates mit KI-APIs, Stripe und Authentifizierung, die sofort einsatzbereit sind.\n\nWenn Sie an einem Seitenprojekt arbeiten oder Ihrem Team helfen, schneller auszuliefern, könnte unsere kostenfreie Stufe nützlich sein.\n\nIch gebe Ihnen gerne einen Rabattcode, wenn Sie interessiert sind.',
      cta: 'Rabattcode erhalten',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-de-07',
      name: 'Partnerschaftsansprache',
      type: 'message_ads',
      objective: 'Partnerschaftsmöglichkeiten mit Agenturen und Beratungen erkunden',
      audience: 'Agenturbesitzer, Beratungsgründer, Digitale Transformationsführer',
      headline: 'Partnerschaftsmöglichkeit für {{company}}',
      body: 'Hallo {{first_name}},\n\nAI Empire hilft Teams, KI-gestützte Produkte schneller auszuliefern. Wir bauen ein Partnernetzwerk für Agenturen und Beratungen, die unsere Templates und APIs an Kunden empfehlen.\n\nVorteile:\n- Umsatzbeteiligung an Empfehlungen\n- Prioritäts-Support für Ihre Kunden\n- Co-Marketing-Möglichkeiten\n\nLohnt sich die Erkundung?',
      cta: 'Partnerschaften entdecken',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dynamisch (3)
    {
      id: 'li-de-08',
      name: 'Dynamisch — Job-Titel-Targeting',
      type: 'dynamic',
      objective: 'Entwickler nach Job-Titel mit personalisierten Anzeigen ansprechen',
      audience: 'Nutzer mit Job-Titeln: CTO, VP Engineering, Tech Lead, Senior Developer',
      headline: 'AI Empire für {{job_title}}s — Schneller ausliefern',
      body: 'AI Empire bietet {{company_name}} einen schnelleren Weg zur Produktion. Next.js 14-Templates mit KI-APIs, Stripe und Authentifizierung. Kostenfreie Stufe zum Prototyping, nutzungsbasiert zum Skalieren.',
      cta: 'AI Empire erkunden',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-de-09',
      name: 'Dynamisch — Unternehmensgröße',
      type: 'dynamic',
      objective: 'Nachricht nach Unternehmensgröße anpassen',
      audience: 'Unternehmen mit 1-50 Mitarbeitern (Startup) und 51-500 Mitarbeitern (Wachstum)',
      headline: '{{company_name}} — KI-SaaS-Templates',
      body: 'Für wachsende Teams: AI Empire bietet produktionsreife Next.js 14-Templates mit KI-Integration. In Tagen bereitstellen, nicht in Monaten. Ab 19 €.',
      cta: 'Templates ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-de-10',
      name: 'Dynamisch — Branchen-Targeting',
      type: 'dynamic',
      objective: 'Bestimmte Branchen mit maßgeschneiderten Nachrichten ansprechen',
      audience: 'E-Commerce, SaaS und Digitale Agenturen',
      headline: 'KI-Lösungen für {{industry}}',
      body: 'AI Empire-Templates sind für {{industry}} gebaut. Next.js 14, Stripe, KI-APIs und Admin-Dashboards. Ab 19 € bis Bundle für 299 €.',
      cta: 'Templates ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-de-01',
      tweet: 'Wir haben AI Empire gebaut, damit Sie nicht alles selbst bauen müssen.\n\nNext.js 14-Templates + Groq & Gemini APIs + Stripe + Auth — alles auf einer Plattform.\n\nKostenlos zum Starten. In Minuten bereitstellen.',
      cta: 'Kostenlos testen',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Entwickler, Startup-Gründer',
    },
    {
      id: 'tw-de-02',
      tweet: 'Heiße Meinung: Ein SaaS sollte nicht 6 Monate zum Bauen dauern.\n\nAI Empire-Templates: professionelles Next.js 14, eingebaute KI-APIs, Stripe konfiguriert.\n\nVon der Idee zur Bereitstellung in 24 Stunden.',
      cta: 'Templates ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Indie-Hacker, Solo-Gründer',
    },
    {
      id: 'tw-de-03',
      tweet: 'Eine API. Mehrere KI-Modelle. Kostenfreie Stufe.\n\nAI Empire: Groq für Geschwindigkeit, Gemini für Leistungsfähigkeit. Einheitlicher Endpoint.\n\nHören Sie auf, 5 verschiedene KI-SDKs zu verwalten.',
      cta: 'API-Schlüssel erhalten',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'KI-Entwickler, Tech Leads',
    },
    {
      id: 'tw-de-04',
      tweet: 'NeuraStore: vollständiges E-Commerce-Template für Next.js 14.\n\nStripe-Zahlungen ✓ Warenkorb ✓ Admin-Dashboard ✓ KI-Empfehlungen ✓\n\n29 €. Auf Vercel in Minuten bereitstellen.',
      cta: 'NeuraStore ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'E-Commerce-Entwickler',
    },
    {
      id: 'tw-de-05',
      tweet: 'Vergleich OpenAI vs AI Empire Preise:\n\nGleiche Qualitätsergebnisse, 70% niedrigere Kosten.\n\nGroq + Gemini über eine vereinheitlichte API. Kostenfreie Stufe inklusive. Keine Anbieterbindung.',
      cta: 'Preise vergleichen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Kostenbewusste Entwickler',
    },
    {
      id: 'tw-de-06',
      tweet: 'Habe gerade einen SaaS in 4 Stunden mit AI Empire-Templates bereitgestellt.\n\nNext.js 14 + Stripe + Auth + KI-APIs. Alles konfiguriert. Fügen Sie einfach Ihren Code hinzu.',
      cta: 'Schneller ausliefern',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Entwickler, Startup-Gründer',
    },
    {
      id: 'tw-de-07',
      tweet: 'Das AI Empire Bundle: 6 Templates, 299 €.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + 3 weitere. Prioritäts-Support. Kostenlose Updates.\n\nSparen Sie über 400 € gegenüber dem Einzelkauf.',
      cta: 'Bundle erhalten',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'SaaS-Gründer, Entwickler',
    },
    {
      id: 'tw-de-08',
      tweet: 'Satt von WordPress?\n\nNeuraBlog: Next.js 14 Blog-Template. MDX, Dark Mode, RSS, SEO-optimiert. 19 €.\n\nSchnell. Modern. Ihres.',
      cta: 'NeuraBlog ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Blogger, Content-Ersteller',
    },
    {
      id: 'tw-de-09',
      tweet: 'AI Empire kostenfreie Stufe: 100 Credits für Groq + Gemini.\n\nKeine Kreditkarte. Keine Verpflichtung. Einfach bauen.\n\n5-Minuten-Einrichtung. SDKs für JS und Python.',
      cta: 'Kostenlos starten',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Studenten, Hobby-Entwickler',
    },
    {
      id: 'tw-de-10',
      tweet: 'Ihr Portfolio verdient mehr als ein grundlegendes HTML-Template.\n\nNeuraPortfolio: Next.js 14, Framer-Motion-Animationen, Dark Mode, responsiv. 29 €.\n\nMachen Sie einen Eindruck.',
      cta: 'Portfolio-Template ansehen',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Entwickler, Designer, Freelancer',
    },
  ],
  instagram: [
    {
      id: 'ig-de-01',
      name: 'Plattformübersicht — Reel',
      type: 'reel',
      script: 'Szene 1: Bildschirmaufnahme des Dashboards — Textüberlagerung "Lernen Sie AI Empire kennen". Szene 2: Code-Editor zeigt API-Aufruf — "Eine API, Mehrere Modelle". Szene 3: Stripe-Checkout — "Zahlungen in 5 Minuten". Szene 4: Live-Bereitstellung — "In 24 Stunden bereitgestellt". Szene 5: Logo + URL — "Starten Sie heute kostenlos".',
      visualDirection: 'Schnelle Bildschirmaufnahmen mit fließenden Übergängen. Dark-Mode-UI. Lila Gradient-Markenfarben. Upbeat-Elektronikmusik im Hintergrund.',
      textOverlay: 'AI Empire — Bauen Sie Ihr SaaS schneller',
      cta: 'Link in Bio — Kostenlos starten',
      duration: '15-30 Sekunden',
    },
    {
      id: 'ig-de-02',
      name: 'NeuraStore-Präsentation — Story',
      type: 'story',
      script: 'Durchswipe durch das NeuraStore-Template. Produktgitter, Warenkorb-Ablauf, Stripe-Checkout, mobile responsive-Ansicht zeigen. Enden mit Preisschild (29 €) und Handlungsaufforderung.',
      visualDirection: 'Saubere weiße/dunkle Hintergründe. Produkt-Mockups auf iPhone und MacBook. Fließende Swipe-Animationen. Lila Markenakzente.',
      textOverlay: 'NeuraStore — 29 € — E-Commerce-Template',
      cta: 'Hochswischen zum Ansehen',
      duration: '15 Sekunden',
    },
    {
      id: 'ig-de-03',
      name: 'KI-API-Demo — Reel',
      type: 'reel',
      script: 'Szene 1: Entwickler tippt Code — "Fügen Sie KI zu Ihrer App hinzu". Szene 2: Terminal zeigt API-Antwort — "Groq + Gemini in einem Aufruf". Szene 3: App läuft mit KI-Funktionen — "5-Minuten-Integration". Szene 4: Preisbildschirm — "Kostenlos zum Starten".',
      visualDirection: 'Over-the-Shoulder-Coding-Shots gemischt mit Bildschirmaufnahmen. Dunkles Thema. Terminal grün auf schwarz. Schnelle Schnitte synchronisiert mit Musik.',
      textOverlay: 'KI-API — Kostenfreie Stufe verfügbar',
      cta: 'API-Schlüssel erhalten — Link in Bio',
      duration: '20-30 Sekunden',
    },
    {
      id: 'ig-de-04',
      name: 'Template-Bundle — Story',
      type: 'story',
      script: 'Dreiteilige Story. Teil 1: Alle 6 Templates im Gitter — "6 Templates. 299 €." Teil 2: Individuelle Template-Highlights — "NeuraStore, NeuraBlog, NeuraPortfolio..." Teil 3: Ersparnis-Hinweis — "Sparen Sie über 400 €" mit Handlungsaufforderungs-Button.',
      visualDirection: 'Produktgitter-Layout. Jedes Template als Gerätemockup dargestellt. Lila Gradient-Hintergrund. Fette Typografie.',
      textOverlay: 'Vollständiges Bundle — 299 € — Sparen Sie über 400 €',
      cta: 'Bundle erhalten',
      duration: '15 Sekunden pro Teil',
    },
    {
      id: 'ig-de-05',
      name: 'Entwickler-Testimonial — Reel',
      type: 'reel',
      script: 'Szene 1: Entwickler Selfie/Video — "Ich habe mein SaaS in 2 Tagen mit AI Empire gestartet". Szene 2: Bildschirmaufnahme der bereitgestellten App. Szene 3: Code-Snippets zeigen Integration. Szene 4: Handlungsaufforderungs-Überlagerung.',
      visualDirection: 'Authentischer UGC-Stil. Natürliches Licht. Handgehaltene Kamera. Untertitel für Barrierefreiheit.',
      textOverlay: '"In 2 Tagen gestartet" — @entwickler',
      cta: 'Jetzt entwickeln — Link in Bio',
      duration: '30 Sekunden',
    },
    {
      id: 'ig-de-06',
      name: 'NeuraBlog-Funktionen — Story',
      type: 'story',
      script: 'Durchgang durch NeuraBlog: MDX-Editor, Dark-Mode-Umschaltung, responsive mobile Ansicht, RSS-Feed-Vorschau, Kommentarbereich. Enden mit Preis (19 €) und Handlungsaufforderung.',
      visualDirection: 'Bildschirmaufnahme mit Zoom-Effekten auf Hauptfunktionen. Bildschirm geteilt zeigt Hell/Dunkel-Modus. Sauberes, minimalistisches Design.',
      textOverlay: 'NeuraBlog — 19 € — SEO-Blog-Template',
      cta: 'Hochswischen — Template ansehen',
      duration: '15 Sekunden',
    },
    {
      id: 'ig-de-07',
      name: 'SaaS-Geschwindigkeits-Challenge — Reel',
      type: 'reel',
      script: 'Zeitraffer beim Bauen eines SaaS von Grund auf. Timer-Überlagerung von 0:00 bis 4:00:00. Template-Auswahl, API-Einrichtung, Stripe-Konfiguration, Bereitstellung zeigen. Enden mit Live-URL.',
      visualDirection: 'Geteilter Bildschirm: Timer links, Bildschirmaufnahme rechts. Zeitraffer-Effekt. Energetische Hintergrundmusik. Meilenstein-Markierungen bei 1h, 2h, 3h.',
      textOverlay: 'SaaS in 4 Stunden gebaut',
      cta: 'AI Empire testen — Link in Bio',
      duration: '30-60 Sekunden',
    },
    {
      id: 'ig-de-08',
      name: 'Kostenfreie Stufe-Ankündigung — Story',
      type: 'story',
      script: 'Fette Typografie-Enthüllung: "KOSTENLOS" → "KI-API" → "100 Credits" → "Groq + Gemini" → "Ohne Kreditkarte" → Handlungsaufforderung. Jedes Textelement erscheint mit Bounce- oder Slide-Effekt.',
      visualDirection: 'Einheitliche lila/dunkle Hintergründe. Großes fettes weißes Text. Minimalistisches Design. Jeder Teil geht mit knackiger Animation in den nächsten über.',
      textOverlay: 'KOSTENLOSE KI-API — 100 Credits — Ohne Karte',
      cta: 'Kostenlos anmelden',
      duration: '10 Sekunden insgesamt',
    },
    {
      id: 'ig-de-09',
      name: 'NeuraPortfolio-Präsentation — Reel',
      type: 'reel',
      script: 'Vorstellung der NeuraPortfolio-Animationen: Hero-Bereich-Parallaxe, Projekt-Karten-Hover-Effekte, fließende Seitenübergänge, Dark Mode. Alles auf einem MacBook-Mockup.',
      visualDirection: 'Elegant, langsamer Geräte-Mockup. Sanfte Kamerabewegungen. Weiches Licht. Minimale Hintergrundmusik. Fokus auf Animationsqualität.',
      textOverlay: 'NeuraPortfolio — 29 € — Entwickler-Portfolio',
      cta: 'Link in Bio — Demo ansehen',
      duration: '20-30 Sekunden',
    },
    {
      id: 'ig-de-10',
      name: 'Vergleich Vorher/Nachher — Story',
      type: 'story',
      script: 'Teil 1: "Von Grund auf bauen: 3-6 Monate" mit Kalender-Symbol. Teil 2: "AI Empire nutzen: 1-2 Tage" mit Raketen-Symbol. Teil 3: "Gleiche Ergebnisse. 95% weniger Zeit." Teil 4: Handlungsaufforderung mit Preisangaben.',
      visualDirection: 'Nebeneinander-Vergleich-Layout. Vorher-Nachher-Stil. Rot für "langsame" Option, Grün für AI Empire. Fettwirkende Typografie.',
      textOverlay: '3 Monate vs 2 Tage — Wählen Sie Schnelligkeit',
      cta: 'Jetzt starten — Link in Bio',
      duration: '15 Sekunden pro Teil',
    },
  ],
};
