import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'en',
  googleSearch: [
    // === Campaign 1: AI API Platform ===
    {
      id: 'g-en-01',
      name: 'AI API Platform',
      objective: 'Drive sign-ups for AI API free tier',
      budget: '€500/mo',
      adGroups: [
        {
          id: 'g-en-01-brand',
          name: 'Brand',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'ai empire platform'],
          ads: [
            { id: 'g-en-01-brand-1', headline: 'AI Empire — Unified AI API Platform', description: 'Access Groq & Gemini through one API. Free tier available, no credit card required. 5-minute integration.', cta: 'Try Free' },
            { id: 'g-en-01-brand-2', headline: 'AI Empire — Your AI API Gateway', description: 'One API, multiple AI models. Groq + Gemini. Free credits on signup. JavaScript and Python SDKs included.', cta: 'Get API Key' },
            { id: 'g-en-01-brand-3', headline: 'AI Empire — Build with AI Today', description: 'Production-ready AI APIs. Groq for speed, Gemini for capability. Free tier, pay-as-you-go pricing.', cta: 'Start Building' },
          ],
        },
        {
          id: 'g-en-01-competitor',
          name: 'Competitor',
          keywords: ['openai alternative', 'groq api alternative', 'cheaper ai api', 'gemini api wrapper', 'ai api comparison'],
          ads: [
            { id: 'g-en-01-comp-1', headline: 'Affordable AI API — Save vs OpenAI', description: 'Same quality AI at lower cost. Groq + Gemini unified. Free tier with 100 credits. Switch in minutes.', cta: 'Compare Pricing' },
            { id: 'g-en-01-comp-2', headline: 'OpenAI Alternative — AI Empire', description: 'Looking for a cost-effective AI API? AI Empire combines Groq and Gemini in one endpoint. Free to start.', cta: 'See Plans' },
            { id: 'g-en-01-comp-3', headline: 'AI API — 70% Less Than OpenAI', description: 'Get GPT-quality results with Groq and Gemini. Unified API. Free tier. No vendor lock-in.', cta: 'Start Free' },
          ],
        },
        {
          id: 'g-en-01-generic',
          name: 'Generic',
          keywords: ['ai api', 'artificial intelligence api', 'groq api', 'gemini api', 'ai for developers', 'free ai api'],
          ads: [
            { id: 'g-en-01-gen-1', headline: 'AI API for Developers — Free Tier', description: 'Groq + Gemini through one API. Free credits on signup. Docs, examples, and SDKs included.', cta: 'Read Docs' },
            { id: 'g-en-01-gen-2', headline: 'Integrate AI in Your App — 5 Min Setup', description: 'One API for Groq and Gemini. Free tier available. Stripe billing. Full documentation.', cta: 'Get Started' },
            { id: 'g-en-01-gen-3', headline: 'AI APIs — Groq & Gemini Combined', description: 'Unified endpoint for multiple AI models. Free to start, pay as you grow. Production-ready.', cta: 'Explore API' },
          ],
        },
      ],
    },
    // === Campaign 2: Next.js SaaS Templates ===
    {
      id: 'g-en-02',
      name: 'Next.js SaaS Templates',
      objective: 'Drive template sales',
      budget: '€400/mo',
      adGroups: [
        {
          id: 'g-en-02-brand',
          name: 'Brand',
          keywords: ['ai empire templates', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-en-02-brand-1', headline: 'AI Empire — SaaS Templates for Next.js 14', description: 'Production-ready templates with AI integration. NeuraStore, NeuraBlog, NeuraPortfolio. From €19.', cta: 'See Templates' },
            { id: 'g-en-02-brand-2', headline: 'NeuraStore & NeuraBlog by AI Empire', description: 'Professional Next.js 14 templates with Stripe, auth, and AI built in. Deploy in minutes.', cta: 'View Templates' },
            { id: 'g-en-02-brand-3', headline: 'AI Empire Templates — Launch Your SaaS', description: '6 premium templates. Next.js 14, Tailwind, Stripe, AI APIs included. From €19 to €299 bundle.', cta: 'Browse Templates' },
          ],
        },
        {
          id: 'g-en-02-competitor',
          name: 'Competitor',
          keywords: ['saas boilerplate', 'next.js template', 'react saas template', 'saas starter kit', 'nextjs ecommerce template'],
          ads: [
            { id: 'g-en-02-comp-1', headline: 'Next.js SaaS Template — AI Built In', description: 'Unlike generic boilerplates, AI Empire templates include AI APIs, Stripe, and auth. Ready to deploy.', cta: 'Compare Templates' },
            { id: 'g-en-02-comp-2', headline: 'Better Than a SaaS Boilerplate', description: 'AI Empire templates: professional design, AI integration, Stripe billing. Not just starter code.', cta: 'See the Difference' },
            { id: 'g-en-02-comp-3', headline: 'Next.js 14 Template — Full Stack Ready', description: 'Templates with everything included: UI, API, auth, payments, AI. Deploy today.', cta: 'View Templates' },
          ],
        },
        {
          id: 'g-en-02-generic',
          name: 'Generic',
          keywords: ['saas template', 'nextjs 14 template', 'react template', 'saas landing page', 'template for saas', 'build saas fast'],
          ads: [
            { id: 'g-en-02-gen-1', headline: 'SaaS Templates — Launch in Days, Not Months', description: 'Next.js 14 templates with auth, Stripe, AI, and admin dashboard. From €19.', cta: 'Get Started' },
            { id: 'g-en-02-gen-2', headline: 'Build a SaaS with Next.js 14', description: 'Production-ready templates. Stripe billing, authentication, AI APIs, admin panel included.', cta: 'Explore Templates' },
            { id: 'g-en-02-gen-3', headline: 'Next.js 14 E-Commerce & Blog Templates', description: 'Professional templates with modern design. Responsive, dark mode, SEO optimized. From €19.', cta: 'Shop Templates' },
          ],
        },
      ],
    },
    // === Campaign 3: AI Integration ===
    {
      id: 'g-en-03',
      name: 'AI Integration',
      objective: 'Attract developers needing AI integration',
      budget: '€350/mo',
      adGroups: [
        {
          id: 'g-en-03-brand',
          name: 'Brand',
          keywords: ['ai empire integration', 'ai empire docs', 'ai empire sdk', 'ai empire api docs'],
          ads: [
            { id: 'g-en-03-brand-1', headline: 'AI Empire — Add AI to Any App', description: 'Simple API to add AI capabilities to your app. Groq + Gemini. SDKs for JS and Python.', cta: 'Read Docs' },
            { id: 'g-en-03-brand-2', headline: 'AI Empire SDK — AI in 5 Minutes', description: 'Install, configure, deploy. Our SDK makes AI integration straightforward. Free tier available.', cta: 'View SDK' },
            { id: 'g-en-03-brand-3', headline: 'AI Empire API Docs — Start Building', description: 'Comprehensive docs, code examples, and tutorials. Add AI to your Next.js app today.', cta: 'Read Docs' },
          ],
        },
        {
          id: 'g-en-03-competitor',
          name: 'Competitor',
          keywords: ['ai integration service', 'embed ai in app', 'ai sdk', 'groq sdk', 'gemini sdk', 'ai api wrapper'],
          ads: [
            { id: 'g-en-03-comp-1', headline: 'Easier AI Integration Than Building Custom', description: 'Stop maintaining multiple AI SDKs. AI Empire: one API, multiple models. Free tier.', cta: 'Simplify Now' },
            { id: 'g-en-03-comp-2', headline: 'AI Integration — No Complex Setup', description: 'One API key, one endpoint. Groq and Gemini ready. Free credits to test. Docs included.', cta: 'Try It Free' },
            { id: 'g-en-03-comp-3', headline: 'Replace Your AI API Wrapper', description: 'AI Empire provides a production-ready unified API. Billing, rate limiting, and monitoring included.', cta: 'See How' },
          ],
        },
        {
          id: 'g-en-03-generic',
          name: 'Generic',
          keywords: ['add ai to app', 'integrate ai', 'ai api for web app', 'groq integration', 'gemini integration', 'ai api rest'],
          ads: [
            { id: 'g-en-03-gen-1', headline: 'Add AI to Your Web App — Simple REST API', description: 'REST API for Groq and Gemini. Free tier. JSON responses. Works with any language.', cta: 'Start Free' },
            { id: 'g-en-03-gen-2', headline: 'AI API Integration — Developer Friendly', description: 'Well-documented API with SDKs for JavaScript and Python. Free tier. Pay per use.', cta: 'View Docs' },
            { id: 'g-en-03-gen-3', headline: 'Groq + Gemini API — One Endpoint', description: 'Single API for multiple AI models. Free credits. Stripe billing. Production-ready.', cta: 'Get Started' },
          ],
        },
      ],
    },
    // === Campaign 4: SaaS Starter Kit ===
    {
      id: 'g-en-04',
      name: 'SaaS Starter Kit',
      objective: 'Convert SaaS founders and indie hackers',
      budget: '€400/mo',
      adGroups: [
        {
          id: 'g-en-04-brand',
          name: 'Brand',
          keywords: ['ai empire starter', 'ai empire saas kit', 'ai empire bundle', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-en-04-brand-1', headline: 'AI Empire — Complete SaaS Starter Kit', description: 'Next.js 14, Stripe, Auth, AI APIs, admin dashboard. Everything to launch your SaaS. From €19.', cta: 'Get Starter Kit' },
            { id: 'g-en-04-brand-2', headline: 'Launch Your SaaS with AI Empire', description: '6 professional templates. Stripe billing, authentication, AI APIs. Deploy in 24 hours.', cta: 'See Templates' },
            { id: 'g-en-04-brand-3', headline: 'AI Empire Bundle — All Templates', description: '6 templates + priority support + free updates. Complete SaaS starter kit for €299.', cta: 'Get Bundle' },
          ],
        },
        {
          id: 'g-en-04-competitor',
          name: 'Competitor',
          keywords: ['saas starter kit', 'saas boilerplate nextjs', 'indie hacker toolkit', 'saas template full stack', 'launch saas fast'],
          ads: [
            { id: 'g-en-04-comp-1', headline: 'SaaS Starter Kit — More Than Boilerplate', description: 'AI Empire includes AI APIs, admin dashboard, and real templates. Not just starter code.', cta: 'Compare Features' },
            { id: 'g-en-04-comp-2', headline: 'Launch Your SaaS in 24 Hours', description: 'Why spend months building from scratch? AI Empire templates: deploy today, iterate tomorrow.', cta: 'See Templates' },
            { id: 'g-en-04-comp-3', headline: 'Indie Hacker SaaS Toolkit', description: 'Everything you need: templates, AI APIs, Stripe, auth. From €19. Free tier for API.', cta: 'Start Building' },
          ],
        },
        {
          id: 'g-en-04-generic',
          name: 'Generic',
          keywords: ['saas template', 'how to build saas', 'saas app template', 'next.js saas', 'stripe saas template', 'saas mvp'],
          ads: [
            { id: 'g-en-04-gen-1', headline: 'Build a SaaS MVP in Days', description: 'Next.js 14 templates with Stripe, auth, and AI. From €19. Deploy to Vercel.', cta: 'Get Started' },
            { id: 'g-en-04-gen-2', headline: 'SaaS Template — Stripe + Auth Included', description: 'Production-ready Next.js 14 templates. Payments, authentication, AI APIs built in.', cta: 'Explore Templates' },
            { id: 'g-en-04-gen-3', headline: 'Full Stack SaaS Template — Next.js 14', description: 'Modern stack: Next.js 14, Tailwind, Stripe, AI. Templates from €19.', cta: 'View Templates' },
          ],
        },
      ],
    },
    // === Campaign 5: Alternative to OpenAI ===
    {
      id: 'g-en-05',
      name: 'Alternative to OpenAI',
      objective: 'Capture OpenAI comparison traffic',
      budget: '€300/mo',
      adGroups: [
        {
          id: 'g-en-05-brand',
          name: 'Brand',
          keywords: ['ai empire vs openai', 'ai empire alternative', 'ai empire pricing', 'cheaper than openai'],
          ads: [
            { id: 'g-en-05-brand-1', headline: 'AI Empire vs OpenAI — Same Quality, Lower Cost', description: 'Groq and Gemini through AI Empire. Unified API with free tier. Save up to 70% vs OpenAI.', cta: 'Compare Pricing' },
            { id: 'g-en-05-brand-2', headline: 'Why Switch to AI Empire from OpenAI', description: 'Lower cost, multiple models, unified API, free tier. Switch in minutes, no code changes.', cta: 'See Pricing' },
            { id: 'g-en-05-brand-3', headline: 'AI Empire — Cost-Effective AI API', description: 'Groq + Gemini. 70% cheaper than OpenAI for similar quality. Free credits on signup.', cta: 'Start Free' },
          ],
        },
        {
          id: 'g-en-05-competitor',
          name: 'Competitor',
          keywords: ['openai alternative api', 'cheaper than openai api', 'openai pricing alternative', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-en-05-comp-1', headline: 'Cheaper OpenAI Alternative — Try Free', description: 'AI Empire: unified Groq + Gemini API. Free tier, pay-as-you-go. 70% less than OpenAI.', cta: 'Try Free' },
            { id: 'g-en-05-comp-2', headline: 'Groq & Gemini API — Better Value', description: 'Why pay more? Groq for speed, Gemini for capability. One API, lower cost. Free tier.', cta: 'See Plans' },
            { id: 'g-en-05-comp-3', headline: 'Switch from OpenAI — Save 70%', description: 'AI Empire provides Groq + Gemini through one API. Same quality, fraction of the cost.', cta: 'Compare Now' },
          ],
        },
        {
          id: 'g-en-05-generic',
          name: 'Generic',
          keywords: ['ai api pricing', 'ai api cost', 'groq pricing', 'gemini api pricing', 'ai api comparison', 'cheapest ai api'],
          ads: [
            { id: 'g-en-05-gen-1', headline: 'AI API — From Free to Pay-As-You-Go', description: 'Start free, scale affordably. Groq + Gemini. No monthly fees. Pay only for what you use.', cta: 'See Pricing' },
            { id: 'g-en-05-gen-2', headline: 'Affordable AI API — Groq + Gemini', description: 'Free tier with 100 credits. Pay-as-you-go after. No minimums, no lock-in.', cta: 'Get Started' },
            { id: 'g-en-05-gen-3', headline: 'AI API Pricing — Transparent & Fair', description: 'No hidden fees. Groq + Gemini through one API. Free tier. Stripe billing.', cta: 'View Pricing' },
          ],
        },
      ],
    },
    // === Campaign 6: Alternative to Vercel Templates ===
    {
      id: 'g-en-06',
      name: 'Alternative to Vercel Templates',
      objective: 'Capture template comparison traffic',
      budget: '€250/mo',
      adGroups: [
        {
          id: 'g-en-06-brand',
          name: 'Brand',
          keywords: ['ai empire vercel', 'ai empire deploy', 'ai empire next.js', 'ai empire hosting'],
          ads: [
            { id: 'g-en-06-brand-1', headline: 'AI Empire Templates — Deploy to Vercel', description: 'Next.js 14 templates optimized for Vercel. AI APIs, Stripe, auth included. Deploy in minutes.', cta: 'Deploy Now' },
            { id: 'g-en-06-brand-2', headline: 'Vercel-Ready SaaS Templates', description: 'AI Empire templates: built for Vercel. One-click deploy. AI integration, billing, auth.', cta: 'View Templates' },
            { id: 'g-en-06-brand-3', headline: 'Next.js 14 Templates for Vercel', description: 'Professional templates. Deploy to Vercel in minutes. AI APIs and Stripe billing built in.', cta: 'Get Templates' },
          ],
        },
        {
          id: 'g-en-06-competitor',
          name: 'Competitor',
          keywords: ['vercel template alternative', 'next.js template', 'better than vercel template', 'saas template vercel', 'template saas deploy'],
          ads: [
            { id: 'g-en-06-comp-1', headline: 'Templates Beyond Basic — AI Empire', description: 'Unlike basic Vercel templates, AI Empire includes AI APIs, Stripe, admin dashboard.', cta: 'See Features' },
            { id: 'g-en-06-comp-2', headline: 'Next.js Template with AI & Stripe', description: 'AI Empire: not just a template, a complete SaaS starter. AI APIs, billing, auth included.', cta: 'Compare' },
            { id: 'g-en-06-comp-3', headline: 'Production SaaS Templates — Next.js 14', description: 'Go beyond demo templates. AI Empire: real auth, real payments, real AI integration.', cta: 'View Templates' },
          ],
        },
        {
          id: 'g-en-06-generic',
          name: 'Generic',
          keywords: ['next.js deploy template', 'saas template deploy', 'vercel saas', 'nextjs 14 deploy', 'saas deploy template', 'template vercel deploy'],
          ads: [
            { id: 'g-en-06-gen-1', headline: 'Deploy Your SaaS to Vercel Today', description: 'Next.js 14 templates. One-click deploy. AI, Stripe, auth included. From €19.', cta: 'Start Deploying' },
            { id: 'g-en-06-gen-2', headline: 'SaaS Template — Ready to Deploy', description: 'Professional Next.js 14 templates. Deploy to Vercel in minutes. Full stack included.', cta: 'Get Started' },
            { id: 'g-en-06-gen-3', headline: 'Next.js 14 SaaS — Deploy in Minutes', description: 'Templates with everything: auth, payments, AI, admin. Deploy to Vercel instantly.', cta: 'Explore Templates' },
          ],
        },
      ],
    },
    // === Campaign 7: E-commerce Template ===
    {
      id: 'g-en-07',
      name: 'E-commerce Template — NeuraStore',
      objective: 'Drive NeuraStore template sales',
      budget: '€300/mo',
      adGroups: [
        {
          id: 'g-en-07-brand',
          name: 'Brand',
          keywords: ['neurastore', 'ai empire ecommerce', 'neurastore template', 'neurastore next.js'],
          ads: [
            { id: 'g-en-07-brand-1', headline: 'NeuraStore — AI-Powered E-Commerce Template', description: 'Next.js 14 e-commerce template with Stripe, cart, admin dashboard. AI product recommendations.', cta: 'View NeuraStore' },
            { id: 'g-en-07-brand-2', headline: 'NeuraStore — Launch Your Online Store', description: 'Professional e-commerce template. Stripe payments, inventory management, responsive design.', cta: 'See Demo' },
            { id: 'g-en-07-brand-3', headline: 'NeuraStore by AI Empire — €29', description: 'Complete e-commerce template. Next.js 14, Stripe, Tailwind. Deploy in minutes.', cta: 'Buy NeuraStore' },
          ],
        },
        {
          id: 'g-en-07-competitor',
          name: 'Competitor',
          keywords: ['ecommerce template next.js', 'online store template', 'shopify alternative template', 'react ecommerce template', 'nextjs store template'],
          ads: [
            { id: 'g-en-07-comp-1', headline: 'E-Commerce Template — Own Your Store', description: 'Unlike Shopify, NeuraStore is yours. Self-hosted, customizable, AI-powered. €29.', cta: 'Get NeuraStore' },
            { id: 'g-en-07-comp-2', headline: 'Next.js E-Commerce — Full Control', description: 'NeuraStore: own your code, your data, your store. Stripe integration, admin dashboard.', cta: 'View Template' },
            { id: 'g-en-07-comp-3', headline: 'Build Your Own Online Store', description: 'NeuraStore template: Next.js 14, Stripe, responsive design, admin panel. €29.', cta: 'Start Building' },
          ],
        },
        {
          id: 'g-en-07-generic',
          name: 'Generic',
          keywords: ['ecommerce website template', 'online shop template', 'nextjs ecommerce', 'build online store', 'saas ecommerce template', 'digital store template'],
          ads: [
            { id: 'g-en-07-gen-1', headline: 'E-Commerce Website Template — Next.js 14', description: 'Professional online store template. Stripe, cart, admin. Responsive, dark mode. €29.', cta: 'Shop Template' },
            { id: 'g-en-07-gen-2', headline: 'Build an Online Store with Next.js', description: 'NeuraStore: complete e-commerce solution. Payments, inventory, AI recommendations.', cta: 'Get Started' },
            { id: 'g-en-07-gen-3', headline: 'Online Store Template — Ready to Launch', description: 'Next.js 14 e-commerce template. Stripe billing, responsive design, SEO optimized. €29.', cta: 'Deploy Now' },
          ],
        },
      ],
    },
    // === Campaign 8: Blog Template ===
    {
      id: 'g-en-08',
      name: 'Blog Template — NeuraBlog',
      objective: 'Drive NeuraBlog template sales',
      budget: '€250/mo',
      adGroups: [
        {
          id: 'g-en-08-brand',
          name: 'Brand',
          keywords: ['neurablog', 'ai empire blog', 'neurablog template', 'neurablog next.js'],
          ads: [
            { id: 'g-en-08-brand-1', headline: 'NeuraBlog — SEO-Optimized Blog Template', description: 'Next.js 14 blog template with MDX, dark mode, RSS feed. Newsletter integration built in.', cta: 'View NeuraBlog' },
            { id: 'g-en-08-brand-2', headline: 'NeuraBlog — Professional Blog in Minutes', description: 'Premium blog template. MDX support, SEO optimization, commenting system. €19.', cta: 'See Demo' },
            { id: 'g-en-08-brand-3', headline: 'NeuraBlog by AI Empire — €19', description: 'Complete blog template. Next.js 14, MDX, dark mode, RSS. Deploy to Vercel.', cta: 'Buy NeuraBlog' },
          ],
        },
        {
          id: 'g-en-08-competitor',
          name: 'Competitor',
          keywords: ['blog template next.js', 'wordpress alternative', 'ghost alternative', 'mdx blog template', 'react blog template'],
          ads: [
            { id: 'g-en-08-comp-1', headline: 'Blog Template — Faster Than WordPress', description: 'NeuraBlog: static site speed, dynamic features. MDX, SEO, newsletter. €19.', cta: 'Try NeuraBlog' },
            { id: 'g-en-08-comp-2', headline: 'MDX Blog Template — Next.js 14', description: 'Unlike Ghost, NeuraBlog gives you full control. Self-hosted, fast, customizable.', cta: 'View Template' },
            { id: 'g-en-08-comp-3', headline: 'Your Blog, Your Code — NeuraBlog', description: 'Own your content platform. NeuraBlog: Next.js 14, MDX, dark mode, RSS. €19.', cta: 'Get NeuraBlog' },
          ],
        },
        {
          id: 'g-en-08-generic',
          name: 'Generic',
          keywords: ['blog template', 'personal blog template', 'nextjs blog', 'tech blog template', 'start a blog', 'blog website template'],
          ads: [
            { id: 'g-en-08-gen-1', headline: 'Blog Template — Launch Your Blog Today', description: 'Professional blog template. SEO optimized, dark mode, newsletter. Deploy in minutes. €19.', cta: 'Start Blogging' },
            { id: 'g-en-08-gen-2', headline: 'Next.js 14 Blog — Fast & Beautiful', description: 'NeuraBlog: modern blog template. MDX, dark mode, RSS, commenting system. €19.', cta: 'View Template' },
            { id: 'g-en-08-gen-3', headline: 'Start a Professional Blog — €19', description: 'NeuraBlog template. SEO optimized, responsive, dark mode. Deploy to Vercel.', cta: 'Get Started' },
          ],
        },
      ],
    },
    // === Campaign 9: Portfolio Template ===
    {
      id: 'g-en-09',
      name: 'Portfolio Template — NeuraPortfolio',
      objective: 'Drive NeuraPortfolio template sales',
      budget: '€200/mo',
      adGroups: [
        {
          id: 'g-en-09-brand',
          name: 'Brand',
          keywords: ['neuraportfolio', 'ai empire portfolio', 'neuraportfolio template', 'developer portfolio template'],
          ads: [
            { id: 'g-en-09-brand-1', headline: 'NeuraPortfolio — Developer Portfolio Template', description: 'Professional portfolio with animations, dark mode, contact form. Next.js 14. €29.', cta: 'View NeuraPortfolio' },
            { id: 'g-en-09-brand-2', headline: 'NeuraPortfolio — Stand Out Online', description: 'Stunning portfolio template. Framer Motion animations, responsive, dark mode. €29.', cta: 'See Demo' },
            { id: 'g-en-09-brand-3', headline: 'NeuraPortfolio by AI Empire — €29', description: 'Complete portfolio template. Next.js 14, animations, dark mode, contact form.', cta: 'Buy NeuraPortfolio' },
          ],
        },
        {
          id: 'g-en-09-competitor',
          name: 'Competitor',
          keywords: ['developer portfolio template', 'portfolio website template', 'best portfolio template', 'creative portfolio template', 'freelancer portfolio'],
          ads: [
            { id: 'g-en-09-comp-1', headline: 'Portfolio Template — Make an Impression', description: 'NeuraPortfolio: beautiful animations, responsive design, dark mode. Better than generic themes.', cta: 'View Template' },
            { id: 'g-en-09-comp-2', headline: 'Your Portfolio Should Stand Out', description: 'NeuraPortfolio: Framer Motion animations, modern design, full customization. €29.', cta: 'See NeuraPortfolio' },
            { id: 'g-en-09-comp-3', headline: 'Developer Portfolio — Next.js 14', description: 'Build your portfolio with NeuraPortfolio. Fast, beautiful, deployable in minutes.', cta: 'Get Started' },
          ],
        },
        {
          id: 'g-en-09-generic',
          name: 'Generic',
          keywords: ['portfolio website', 'build portfolio', 'online portfolio', 'personal website template', 'freelance portfolio template', 'showcase portfolio'],
          ads: [
            { id: 'g-en-09-gen-1', headline: 'Build Your Online Portfolio — €29', description: 'NeuraPortfolio: professional template with animations. Deploy in minutes.', cta: 'Start Building' },
            { id: 'g-en-09-gen-2', headline: 'Personal Website Template — Next.js 14', description: 'Beautiful portfolio template. Dark mode, animations, responsive. From €29.', cta: 'View Templates' },
            { id: 'g-en-09-gen-3', headline: 'Portfolio Template — Deploy Today', description: 'Professional portfolio with modern design. Framer Motion, dark mode. €29.', cta: 'Get Portfolio' },
          ],
        },
      ],
    },
    // === Campaign 10: AI SaaS Builder ===
    {
      id: 'g-en-10',
      name: 'AI SaaS Builder',
      objective: 'Capture AI SaaS builder intent',
      budget: '€350/mo',
      adGroups: [
        {
          id: 'g-en-10-brand',
          name: 'Brand',
          keywords: ['ai empire saas builder', 'ai empire build saas', 'ai empire launch', 'ai empire platform'],
          ads: [
            { id: 'g-en-10-brand-1', headline: 'AI Empire — Build Your AI SaaS', description: 'Templates + AI APIs + Stripe + Auth. Everything to build and launch an AI-powered SaaS.', cta: 'Start Building' },
            { id: 'g-en-10-brand-2', headline: 'AI Empire — Your AI SaaS Platform', description: 'From idea to launch. Templates, AI APIs, payments, auth. Deploy in 24 hours.', cta: 'Launch Now' },
            { id: 'g-en-10-brand-3', headline: 'AI Empire — Ship Your SaaS Faster', description: 'Professional templates with AI integration. Stripe, auth, admin dashboard. From €19.', cta: 'Get Started' },
          ],
        },
        {
          id: 'g-en-10-competitor',
          name: 'Competitor',
          keywords: ['build ai saas', 'saas builder', 'ai saas template', 'saas ai platform', 'build saas with ai', 'ai product builder'],
          ads: [
            { id: 'g-en-10-comp-1', headline: 'Build an AI SaaS — Not from Scratch', description: 'AI Empire: professional templates with AI APIs built in. Save months of development.', cta: 'See Templates' },
            { id: 'g-en-10-comp-2', headline: 'AI SaaS Builder — Ship in Days', description: 'Templates, AI APIs, Stripe, auth. AI Empire: everything you need to launch.', cta: 'Compare Features' },
            { id: 'g-en-10-comp-3', headline: 'Your AI SaaS — Launch This Week', description: 'Why build from scratch? AI Empire templates: deploy in 24 hours. AI integration included.', cta: 'Start Free' },
          ],
        },
        {
          id: 'g-en-10-generic',
          name: 'Generic',
          keywords: ['saas template', 'build saas', 'saas app', 'saas platform', 'ai product template', 'saas ideas', 'launch saas'],
          ads: [
            { id: 'g-en-10-gen-1', headline: 'Build a SaaS — Templates, AI, Payments', description: 'Next.js 14 templates with AI APIs, Stripe, auth. From €19. Deploy today.', cta: 'Get Started' },
            { id: 'g-en-10-gen-2', headline: 'SaaS Builder — Everything Included', description: 'Templates, AI integration, payments, admin dashboard. Complete SaaS toolkit. From €19.', cta: 'Explore Templates' },
            { id: 'g-en-10-gen-3', headline: 'Ship Your SaaS Idea — Next.js 14', description: 'Professional templates with modern stack. AI, Stripe, auth. Deploy in minutes.', cta: 'Start Building' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Awareness (2)
    {
      id: 'fb-en-01',
      name: 'AI Empire Brand Awareness',
      type: 'awareness',
      objective: 'Increase brand awareness among developers and startup founders',
      audience: 'Developers, CTOs, startup founders, ages 22-45, interested in AI, SaaS, Next.js, web development',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Building a SaaS? AI Empire gives you Next.js 14 templates, built-in AI APIs (Groq + Gemini), Stripe billing, and authentication — all starting from €19. Join 5,000+ developers who launched faster.',
      cta: 'Learn More',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-en-02',
      name: 'AI API Value Proposition',
      type: 'awareness',
      objective: 'Educate developers about the unified AI API',
      audience: 'Software developers, ML engineers, AI enthusiasts, ages 22-40',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'One API for Groq and Gemini. AI Empire provides a unified endpoint for multiple AI models — free to start, pay as you grow. Stop managing multiple AI SDKs.',
      cta: 'Try Free',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Consideration (3)
    {
      id: 'fb-en-03',
      name: 'NeuraStore Product Showcase',
      type: 'consideration',
      objective: 'Drive traffic to NeuraStore template page',
      audience: 'E-commerce developers, online store builders, Shopify users looking for alternatives',
      placements: ['Facebook Feed', 'Instagram Feed', 'Marketplace'],
      adCopy: 'NeuraStore: a complete e-commerce template built with Next.js 14. Stripe payments, cart management, admin dashboard, and AI product recommendations. €29 — own your store, own your code.',
      cta: 'View Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-en-04',
      name: 'Template Bundle Offer',
      type: 'consideration',
      objective: 'Drive interest in the full template bundle',
      audience: 'SaaS founders, indie hackers, full-stack developers',
      placements: ['Facebook Feed', 'Instagram Feed', 'Facebook Marketplace'],
      adCopy: 'Get all 6 AI Empire templates for €299. NeuraStore, NeuraBlog, NeuraPortfolio, and 3 more. Priority support, free updates, everything included. Save €400+ vs buying individually.',
      cta: 'See Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-en-05',
      name: 'AI Integration Tutorial',
      type: 'consideration',
      objective: 'Engage developers with educational content',
      audience: 'Web developers, React developers, Node.js developers',
      placements: ['Facebook Feed', 'Instagram Reels', 'Stories'],
      adCopy: 'Add AI to your Next.js app in 5 minutes. AI Empire\'s SDK makes integration simple — one API key, one endpoint. Free tier with 100 credits. Docs and examples included.',
      cta: 'Read Docs',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Conversion (3)
    {
      id: 'fb-en-06',
      name: 'Free API Sign-Up',
      type: 'conversion',
      objective: 'Drive free tier sign-ups',
      audience: 'Website visitors, documentation readers, blog readers, lookalike audiences',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Your free AI API is waiting. Sign up for AI Empire and get 100 credits for Groq and Gemini. No credit card required. Start building with AI today.',
      cta: 'Sign Up Free',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-en-07',
      name: 'Template Purchase Conversion',
      type: 'conversion',
      objective: 'Convert template page visitors into buyers',
      audience: 'Template page visitors, cart abandoners, high-intent users',
      placements: ['Facebook Feed', 'Instagram Feed', 'Messenger'],
      adCopy: 'Still thinking about it? NeuraBlog (€19) and NeuraStore (€29) are ready to deploy. Stripe, auth, AI integration included. 100% money-back guarantee.',
      cta: 'Buy Now',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-en-08',
      name: 'Limited Time Bundle Discount',
      type: 'conversion',
      objective: 'Drive bundle purchases with urgency',
      audience: 'Email subscribers, cart abandoners, high-engagement users',
      placements: ['Facebook Feed', 'Instagram Feed', 'Instagram Stories'],
      adCopy: 'Limited offer: Get the full AI Empire template bundle for €299 (save €400+). Includes all 6 templates, priority support, and free updates. Offer ends soon.',
      cta: 'Get Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Retargeting (2)
    {
      id: 'fb-en-09',
      name: 'Return Visitor — Templates',
      type: 'retargeting',
      objective: 'Re-engage visitors who viewed templates but did not purchase',
      audience: 'Template page visitors (7-30 days), did not complete purchase',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'You were looking at AI Empire templates. NeuraBlog starts at €19, NeuraStore at €29. Full stack, deploy-ready, AI integrated. Come back and launch your SaaS.',
      cta: 'View Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-en-10',
      name: 'Return Visitor — API',
      type: 'retargeting',
      objective: 'Re-engage visitors who explored the API docs but did not sign up',
      audience: 'Docs page visitors (7-30 days), did not create account',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'You explored our API docs. Ready to build? AI Empire gives you free credits for Groq and Gemini. Sign up in 30 seconds, no credit card needed.',
      cta: 'Start Free',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Sponsored Content (4)
    {
      id: 'li-en-01',
      name: 'SaaS Launch Announcement',
      type: 'sponsored_content',
      objective: 'Generate sign-ups from tech decision-makers',
      audience: 'CTOs, tech leads, engineering managers at startups and SMBs',
      headline: 'Launch Your SaaS 10x Faster with AI Empire',
      body: 'AI Empire provides Next.js 14 templates with built-in AI APIs (Groq + Gemini), Stripe billing, and authentication. Go from idea to deployed SaaS in 24 hours, not months.\n\nWhat\'s included:\n- 6 production-ready templates (€19-€299)\n- Unified AI API with free tier\n- Stripe + Auth configured\n- Admin dashboard\n\nJoin 5,000+ developers building with AI Empire.',
      cta: 'Start Building',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-en-02',
      name: 'AI API for Enterprise',
      type: 'sponsored_content',
      objective: 'Reach engineering leaders evaluating AI API solutions',
      audience: 'Engineering managers, VP Engineering, architects at mid-market and enterprise companies',
      headline: 'Unified AI API — Groq + Gemini for Your Team',
      body: 'Stop managing multiple AI vendor relationships. AI Empire provides one API for Groq and Gemini — with built-in billing, rate limiting, and monitoring.\n\nWhy engineering teams choose AI Empire:\n- One endpoint for multiple AI models\n- JavaScript and Python SDKs\n- Free tier for prototyping\n- Pay-as-you-go scaling\n\nReduce your AI integration complexity.',
      cta: 'Explore API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-en-03',
      name: 'Indie Hacker Success',
      type: 'sponsored_content',
      objective: 'Attract indie hackers and solo founders',
      audience: 'Indie hackers, solo founders, bootstrapped startup founders',
      headline: 'Ship Your SaaS This Weekend',
      body: 'Built for solo founders who want to move fast.\n\nAI Empire gives you:\n- Professional Next.js 14 templates\n- AI APIs ready to use\n- Stripe billing in 5 minutes\n- No code required for launch\n\nTemplates from €19. Deploy to Vercel in one click.\n\nStop overthinking. Start shipping.',
      cta: 'See Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-en-04',
      name: 'Cost Comparison',
      type: 'sponsored_content',
      objective: 'Appeal to cost-conscious teams comparing AI providers',
      audience: 'CTOs, finance leaders, procurement at startups and SMBs',
      headline: 'AI APIs — 70% Less Than Competitors',
      body: 'AI Empire combines Groq and Gemini in one API. Pay only for what you use.\n\nComparison:\n- OpenAI: €0.03/1K tokens (GPT-4)\n- AI Empire: ~€0.009/1K tokens (Groq Llama)\n\nFree tier included. No vendor lock-in. Switch in minutes.\n\n5,000+ developers already saving.',
      cta: 'See Pricing',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Message Ads (3)
    {
      id: 'li-en-05',
      name: 'Direct Outreach — CTOs',
      type: 'message_ads',
      objective: 'Personalized outreach to CTOs at target companies',
      audience: 'CTOs at companies with 10-200 employees in tech, SaaS, and e-commerce',
      headline: 'Quick question about your AI stack',
      body: 'Hi {{first_name}},\n\nNoticed {{company}} is building with AI. Quick question: are you managing multiple AI vendor APIs?\n\nAI Empire provides a unified API for Groq and Gemini — one endpoint, one bill, one dashboard. Free tier included.\n\nWould it make sense to chat for 10 minutes? Happy to walk you through it.',
      cta: 'Schedule a Chat',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-en-06',
      name: 'Direct Outreach — Developers',
      type: 'message_ads',
      objective: 'Engage individual developers with personalized offers',
      audience: 'Full-stack developers, React/Next.js developers at tech companies',
      headline: 'Building with Next.js?',
      body: 'Hi {{first_name}},\n\nSaw you\'re working with Next.js. We built AI Empire specifically for the Next.js ecosystem — templates with AI APIs, Stripe, and auth ready to go.\n\nIf you\'re working on a side project or helping your team ship faster, our free tier might be useful.\n\nHappy to share a discount code if you\'re interested.',
      cta: 'Get Discount Code',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-en-07',
      name: 'Partnership Outreach',
      type: 'message_ads',
      objective: 'Explore partnership opportunities with agencies and consultancies',
      audience: 'Agency owners, consultancy founders, digital transformation leaders',
      headline: 'Partnership opportunity for {{company}}',
      body: 'Hi {{first_name}},\n\nAI Empire helps teams ship AI-powered products faster. We\'re building a partner program for agencies and consultancies that recommend our templates and APIs to clients.\n\nBenefits:\n- Revenue share on referrals\n- Priority support for your clients\n- Co-marketing opportunities\n\nWorth exploring?',
      cta: 'Learn About Partnerships',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dynamic (3)
    {
      id: 'li-en-08',
      name: 'Dynamic — Job Title Targeting',
      type: 'dynamic',
      objective: 'Target developers by job title with personalized ads',
      audience: 'Users with job titles: CTO, VP Engineering, Tech Lead, Senior Developer',
      headline: 'AI Empire for {{job_title}}s — Ship Faster',
      body: 'AI Empire gives {{company_name}} a faster path to production. Next.js 14 templates with AI APIs, Stripe, and auth. Free tier to prototype, pay-as-you-go to scale.',
      cta: 'Explore AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-en-09',
      name: 'Dynamic — Company Size',
      type: 'dynamic',
      objective: 'Customize messaging by company size',
      audience: 'Companies with 1-50 employees (startup) and 51-500 employees (growth)',
      headline: '{{company_name}} — AI SaaS Templates',
      body: 'For growing teams: AI Empire provides production-ready Next.js 14 templates with AI integration. Deploy in days, not months. From €19.',
      cta: 'See Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-en-10',
      name: 'Dynamic — Industry Targeting',
      type: 'dynamic',
      objective: 'Target specific industries with tailored messaging',
      audience: 'E-commerce, SaaS, and digital agencies',
      headline: 'AI-Powered {{industry}} Solutions',
      body: 'AI Empire templates are built for {{industry}}. Next.js 14, Stripe, AI APIs, and admin dashboards. From €19 to €299 bundle.',
      cta: 'View Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-en-01',
      tweet: 'We built AI Empire so you don\'t have to.\n\nNext.js 14 templates + Groq & Gemini APIs + Stripe + Auth — all in one platform.\n\nFree to start. Deploy in minutes.',
      cta: 'Try Free',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Developers, startup founders',
    },
    {
      id: 'tw-en-02',
      tweet: 'Hot take: Building a SaaS shouldn\'t take 6 months.\n\nAI Empire templates: professional Next.js 14, AI APIs built in, Stripe configured.\n\nFrom idea to deployment in 24 hours.',
      cta: 'See Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Indie hackers, solo founders',
    },
    {
      id: 'tw-en-03',
      tweet: 'One API. Multiple AI models. Free tier.\n\nAI Empire: Groq for speed, Gemini for capability. Unified endpoint.\n\nStop managing 5 different AI SDKs.',
      cta: 'Get API Key',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'AI developers, tech leads',
    },
    {
      id: 'tw-en-04',
      tweet: 'NeuraStore: complete e-commerce template for Next.js 14.\n\nStripe payments ✓ Cart ✓ Admin dashboard ✓ AI recommendations ✓\n\n€29. Deploy to Vercel in minutes.',
      cta: 'View NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'E-commerce developers',
    },
    {
      id: 'tw-en-05',
      tweet: 'Compared OpenAI vs AI Empire pricing:\n\nSame quality results, 70% lower cost.\n\nGroq + Gemini through one API. Free tier included. No vendor lock-in.',
      cta: 'Compare Pricing',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Cost-conscious developers',
    },
    {
      id: 'tw-en-06',
      tweet: 'Just deployed a SaaS in 4 hours using AI Empire templates.\n\nNext.js 14 + Stripe + Auth + AI APIs. All configured. Just add your code.',
      cta: 'Ship Faster',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Developers, startup founders',
    },
    {
      id: 'tw-en-07',
      tweet: 'The AI Empire bundle: 6 templates, €299.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + 3 more. Priority support. Free updates.\n\nSave €400+ vs buying individually.',
      cta: 'Get Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'SaaS founders, developers',
    },
    {
      id: 'tw-en-08',
      tweet: 'Tired of WordPress?\n\nNeuraBlog: Next.js 14 blog template. MDX, dark mode, RSS, SEO optimized. €19.\n\nFast. Modern. Yours.',
      cta: 'View NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Bloggers, content creators',
    },
    {
      id: 'tw-en-09',
      tweet: 'AI Empire free tier: 100 credits for Groq + Gemini.\n\nNo credit card. No commitment. Just build.\n\n5-minute setup. SDKs for JS and Python.',
      cta: 'Start Free',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Students, hobby developers',
    },
    {
      id: 'tw-en-10',
      tweet: 'Your portfolio deserves better than a basic HTML template.\n\nNeuraPortfolio: Next.js 14, Framer Motion animations, dark mode, responsive. €29.\n\nMake an impression.',
      cta: 'View Portfolio Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Developers, designers, freelancers',
    },
  ],
  instagram: [
    {
      id: 'ig-en-01',
      name: 'Platform Overview Reel',
      type: 'reel',
      script: 'Scene 1: Screen recording of dashboard — "Meet AI Empire" text overlay. Scene 2: Code editor showing API call — "One API, Multiple Models". Scene 3: Stripe checkout — "Payments in 5 Minutes". Scene 4: Live deployment — "Deployed in 24 Hours". Scene 5: Logo + URL — "Start Free Today".',
      visualDirection: 'Fast-paced screen recordings with smooth transitions. Dark mode UI. Purple gradient brand colors. Upbeat electronic background music.',
      textOverlay: 'AI Empire — Build Your SaaS Faster',
      cta: 'Link in Bio — Start Free',
      duration: '15-30 seconds',
    },
    {
      id: 'ig-en-02',
      name: 'NeuraStore Showcase Story',
      type: 'story',
      script: 'Swipe-through of NeuraStore template. Show product grid, cart flow, Stripe checkout, mobile responsive view. End with price tag (€29) and CTA.',
      visualDirection: 'Clean white/dark backgrounds. Product mockups on iPhone and MacBook. Smooth swipe animations. Brand purple accents.',
      textOverlay: 'NeuraStore — €29 — E-Commerce Template',
      cta: 'Swipe Up to View',
      duration: '15 seconds',
    },
    {
      id: 'ig-en-03',
      name: 'AI API Demo Reel',
      type: 'reel',
      script: 'Scene 1: Developer typing code — "Adding AI to your app". Scene 2: Terminal showing API response — "Groq + Gemini in one call". Scene 3: App running with AI features — "5-minute integration". Scene 4: Pricing screen — "Free to start".',
      visualDirection: 'Over-the-shoulder coding shots mixed with screen recordings. Dark theme. Terminal green on black. Quick cuts synced to music.',
      textOverlay: 'AI API — Free Tier Available',
      cta: 'Get Your API Key — Link in Bio',
      duration: '20-30 seconds',
    },
    {
      id: 'ig-en-04',
      name: 'Template Bundle Story',
      type: 'story',
      script: 'Three-frame story. Frame 1: All 6 templates displayed in grid — "6 Templates. €299." Frame 2: Individual template highlights — "NeuraStore, NeuraBlog, NeuraPortfolio..." Frame 3: Savings callout — "Save €400+" with CTA button.',
      visualDirection: 'Product grid layout. Each template shown as a device mockup. Purple gradient background. Bold typography.',
      textOverlay: 'Full Bundle — €299 — Save €400+',
      cta: 'Get the Bundle',
      duration: '15 seconds per frame',
    },
    {
      id: 'ig-en-05',
      name: 'Developer Testimonial Reel',
      type: 'reel',
      script: 'Scene 1: Developer selfie/video — "I launched my SaaS in 2 days with AI Empire". Scene 2: Screen recording of their deployed app. Scene 3: Code snippets showing integration. Scene 4: CTA overlay.',
      visualDirection: 'Authentic UGC-style footage. Natural lighting. Handheld camera feel. Subtitles for accessibility.',
      textOverlay: '"Launched in 2 Days" — @developer',
      cta: 'Start Building — Link in Bio',
      duration: '30 seconds',
    },
    {
      id: 'ig-en-06',
      name: 'NeuraBlog Feature Story',
      type: 'story',
      script: 'Walkthrough of NeuraBlog: MDX editor, dark mode toggle, responsive mobile view, RSS feed preview, comment section. End with pricing (€19) and CTA.',
      visualDirection: 'Screen recording with zoom effects on key features. Split-screen showing light/dark mode. Clean, minimal aesthetic.',
      textOverlay: 'NeuraBlog — €19 — SEO Blog Template',
      cta: 'Swipe Up — View Template',
      duration: '15 seconds',
    },
    {
      id: 'ig-en-07',
      name: 'SaaS Speed Challenge Reel',
      type: 'reel',
      script: 'Time-lapse of building a SaaS from scratch. Timer overlay counting from 0:00 to 4:00:00. Show template selection, API setup, Stripe config, deployment. End with live URL.',
      visualDirection: 'Split screen: timer on left, screen recording on right. Fast-forward effect. Energetic background music. Milestone markers at 1h, 2h, 3h.',
      textOverlay: 'Built a SaaS in 4 Hours',
      cta: 'Try AI Empire — Link in Bio',
      duration: '30-60 seconds',
    },
    {
      id: 'ig-en-08',
      name: 'Free Tier Announcement Story',
      type: 'story',
      script: 'Bold typography reveal: "FREE" → "AI API" → "100 Credits" → "Groq + Gemini" → "No Credit Card" → CTA. Each text element animates in with a bounce or slide effect.',
      visualDirection: 'Solid purple/dark backgrounds. Large bold white text. Minimal design. Each frame transitions with a punchy animation.',
      textOverlay: 'FREE AI API — 100 Credits — No Card',
      cta: 'Sign Up Free',
      duration: '10 seconds total',
    },
    {
      id: 'ig-en-09',
      name: 'NeuraPortfolio Showcase Reel',
      type: 'reel',
      script: 'Showcase of NeuraPortfolio animations: hero section parallax, project card hover effects, smooth page transitions, dark mode. All on a MacBook mockup.',
      visualDirection: 'Elegant, slow-motion device mockup. Subtle camera movements. Soft lighting. Minimal background music. Focus on animation quality.',
      textOverlay: 'NeuraPortfolio — €29 — Developer Portfolio',
      cta: 'Link in Bio — View Demo',
      duration: '20-30 seconds',
    },
    {
      id: 'ig-en-10',
      name: 'Comparison Carousel Story',
      type: 'story',
      script: 'Frame 1: "Building from scratch: 3-6 months" with calendar icon. Frame 2: "Using AI Empire: 1-2 days" with rocket icon. Frame 3: "Same result. 95% less time." Frame 4: CTA with pricing.',
      visualDirection: 'Side-by-side comparison layout. Before/after style. Red for "slow" option, green for AI Empire. Bold impact typography.',
      textOverlay: '3 Months vs 2 Days — Choose Fast',
      cta: 'Start Now — Link in Bio',
      duration: '15 seconds per frame',
    },
  ],
};
