import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'es',
  googleSearch: [
    // === Campaña 1: Plataforma API de IA ===
    {
      id: 'g-es-01',
      name: 'Plataforma API de IA',
      objective: 'Generar registros en la capa gratuita de la API de IA',
      budget: '500 €/mes',
      adGroups: [
        {
          id: 'g-es-01-brand',
          name: 'Marca',
          keywords: ['ai empire', 'ai-empire', 'api ai empire', 'plataforma ai empire'],
          ads: [
            { id: 'g-es-01-brand-1', headline: 'AI Empire — Plataforma API de IA Unificada', description: 'Accede a Groq y Gemini a través de una sola API. Capa gratuita disponible, sin tarjeta de crédito. Integración en 5 minutos.', cta: 'Probar gratis' },
            { id: 'g-es-01-brand-2', headline: 'AI Empire — Tu Puerta de Enlace API de IA', description: 'Una API, múltiples modelos de IA. Groq + Gemini. Créditos gratuitos al registrarte. SDKs para JavaScript y Python incluidos.', cta: 'Obtener clave API' },
            { id: 'g-es-01-brand-3', headline: 'AI Empire — Desarrolla con IA Hoy', description: 'APIs de IA listas para producción. Groq para velocidad, Gemini para capacidad. Capa gratuita, pago por uso.', cta: 'Empezar a desarrollar' },
          ],
        },
        {
          id: 'g-es-01-competitor',
          name: 'Competidor',
          keywords: ['alternativa openai', 'alternativa api groq', 'api ia más barata', 'wrapper api gemini', 'comparativa api ia'],
          ads: [
            { id: 'g-es-01-comp-1', headline: 'API de IA asequible — Ahorra vs OpenAI', description: 'Misma calidad de IA a menor costo. Groq + Gemini unificados. Capa gratuita con 100 créditos. Cambia en minutos.', cta: 'Comparar precios' },
            { id: 'g-es-01-comp-2', headline: 'Alternativa a OpenAI — AI Empire', description: '¿Buscas una API de IA económica? AI Empire combina Groq y Gemini en un solo endpoint. Gratis para empezar.', cta: 'Ver planes' },
            { id: 'g-es-01-comp-3', headline: 'API de IA — 70% menos que OpenAI', description: 'Obtén resultados de calidad GPT con Groq y Gemini. API unificada. Capa gratuita. Sin bloqueo de proveedor.', cta: 'Empezar gratis' },
          ],
        },
        {
          id: 'g-es-01-generic',
          name: 'Genérico',
          keywords: ['api ia', 'api inteligencia artificial', 'api groq', 'api gemini', 'ia para desarrolladores', 'api ia gratuita'],
          ads: [
            { id: 'g-es-01-gen-1', headline: 'API de IA para Desarrolladores — Capa Gratuita', description: 'Groq + Gemini a través de una sola API. Créditos gratuitos al registrarte. Documentación, ejemplos y SDKs incluidos.', cta: 'Leer docs' },
            { id: 'g-es-01-gen-2', headline: 'Integra IA en tu App — Configuración en 5 Min', description: 'Una API para Groq y Gemini. Capa gratuita disponible. Facturación con Stripe. Documentación completa.', cta: 'Empezar' },
            { id: 'g-es-01-gen-3', headline: 'APIs de IA — Groq y Gemini Combinados', description: 'Endpoint unificado para múltiples modelos de IA. Gratis para empezar, paga a medida que creces. Listo para producción.', cta: 'Explorar API' },
          ],
        },
      ],
    },
    // === Campaña 2: Templates SaaS Next.js ===
    {
      id: 'g-es-02',
      name: 'Templates SaaS Next.js',
      objective: 'Generar ventas de templates',
      budget: '400 €/mes',
      adGroups: [
        {
          id: 'g-es-02-brand',
          name: 'Marca',
          keywords: ['templates ai empire', 'saas ai empire', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-es-02-brand-1', headline: 'AI Empire — Templates SaaS para Next.js 14', description: 'Templates listos para producción con integración de IA. NeuraStore, NeuraBlog, NeuraPortfolio. Desde 19 €.', cta: 'Ver templates' },
            { id: 'g-es-02-brand-2', headline: 'NeuraStore y NeuraBlog de AI Empire', description: 'Templates Next.js 14 profesionales con Stripe, autenticación e IA integrados. Despliega en minutos.', cta: 'Ver templates' },
            { id: 'g-es-02-brand-3', headline: 'Templates AI Empire — Lanza tu SaaS', description: '6 templates premium. Next.js 14, Tailwind, Stripe, APIs de IA incluidos. Desde 19 € hasta bundle de 299 €.', cta: 'Explorar templates' },
          ],
        },
        {
          id: 'g-es-02-competitor',
          name: 'Competidor',
          keywords: ['boilerplate saas', 'template next.js', 'template saas react', 'kit de inicio saas', 'template ecommerce nextjs'],
          ads: [
            { id: 'g-es-02-comp-1', headline: 'Template SaaS Next.js — IA Integrada', description: 'A diferencia de los boilerplates genéricos, los templates de AI Empire incluyen APIs de IA, Stripe y autenticación. Listos para desplegar.', cta: 'Comparar templates' },
            { id: 'g-es-02-comp-2', headline: 'Mejor que un Boilerplate SaaS', description: 'Templates AI Empire: diseño profesional, integración de IA, facturación con Stripe. No solo código inicial.', cta: 'Ver la diferencia' },
            { id: 'g-es-02-comp-3', headline: 'Template Next.js 14 — Full Stack Listo', description: 'Templates con todo incluido: interfaz, API, autenticación, pagos, IA. Despliega hoy.', cta: 'Ver templates' },
          ],
        },
        {
          id: 'g-es-02-generic',
          name: 'Genérico',
          keywords: ['template saas', 'template nextjs 14', 'template react', 'landing page saas', 'template para saas', 'crear saas rápido'],
          ads: [
            { id: 'g-es-02-gen-1', headline: 'Templates SaaS — Lanza en Días, No en Meses', description: 'Templates Next.js 14 con autenticación, Stripe, IA y panel de administración. Desde 19 €.', cta: 'Empezar' },
            { id: 'g-es-02-gen-2', headline: 'Crea un SaaS con Next.js 14', description: 'Templates listos para producción. Facturación con Stripe, autenticación, APIs de IA, panel de administración incluidos.', cta: 'Explorar templates' },
            { id: 'g-es-02-gen-3', headline: 'Templates Next.js 14 E-commerce y Blog', description: 'Templates profesionales con diseño moderno. Responsive, modo oscuro, optimizados para SEO. Desde 19 €.', cta: 'Comprar templates' },
          ],
        },
      ],
    },
    // === Campaña 3: Integración de IA ===
    {
      id: 'g-es-03',
      name: 'Integración de IA',
      objective: 'Atraer desarrolladores que necesitan integración de IA',
      budget: '350 €/mes',
      adGroups: [
        {
          id: 'g-es-03-brand',
          name: 'Marca',
          keywords: ['integración ai empire', 'documentación ai empire', 'sdk ai empire', 'docs api ai empire'],
          ads: [
            { id: 'g-es-03-brand-1', headline: 'AI Empire — Añade IA a Cualquier Aplicación', description: 'API sencilla para agregar capacidades de IA a tu app. Groq + Gemini. SDKs para JS y Python.', cta: 'Leer docs' },
            { id: 'g-es-03-brand-2', headline: 'SDK AI Empire — IA en 5 Minutos', description: 'Instala, configura, despliega. Nuestro SDK hace la integración de IA sencilla. Capa gratuita disponible.', cta: 'Ver SDK' },
            { id: 'g-es-03-brand-3', headline: 'Docs API AI Empire — Empieza a Desarrollar', description: 'Documentación completa, ejemplos de código y tutoriales. Añade IA a tu app Next.js hoy.', cta: 'Leer docs' },
          ],
        },
        {
          id: 'g-es-03-competitor',
          name: 'Competidor',
          keywords: ['servicio integración ia', 'integrar ia en app', 'sdk ia', 'sdk groq', 'sdk gemini', 'wrapper api ia'],
          ads: [
            { id: 'g-es-03-comp-1', headline: 'Integración de IA Más Fácil que Construir a Medida', description: 'Deja de mantener múltiples SDKs de IA. AI Empire: una API, múltiples modelos. Capa gratuita.', cta: 'Simplificar ahora' },
            { id: 'g-es-03-comp-2', headline: 'Integración de IA — Sin Configuración Compleja', description: 'Una clave API, un endpoint. Groq y Gemini listos. Créditos gratuitos para probar. Documentación incluida.', cta: 'Probar gratis' },
            { id: 'g-es-03-comp-3', headline: 'Reemplaza tu Wrapper API de IA', description: 'AI Empire proporciona una API unificada lista para producción. Facturación, limitación de velocidad y monitoreo incluidos.', cta: 'Ver cómo' },
          ],
        },
        {
          id: 'g-es-03-generic',
          name: 'Genérico',
          keywords: ['añadir ia a app', 'integrar ia', 'api ia para app web', 'integración groq', 'integración gemini', 'api ia rest'],
          ads: [
            { id: 'g-es-03-gen-1', headline: 'Añade IA a tu App Web — API REST Sencilla', description: 'API REST para Groq y Gemini. Capa gratuita. Respuestas JSON. Compatible con cualquier lenguaje.', cta: 'Empezar gratis' },
            { id: 'g-es-03-gen-2', headline: 'Integración API de IA — Amigable para Desarrolladores', description: 'API bien documentada con SDKs para JavaScript y Python. Capa gratuita. Pago por uso.', cta: 'Ver documentación' },
            { id: 'g-es-03-gen-3', headline: 'API Groq + Gemini — Un Solo Endpoint', description: 'API única para múltiples modelos de IA. Créditos gratuitos. Facturación con Stripe. Listo para producción.', cta: 'Empezar' },
          ],
        },
      ],
    },
    // === Campaña 4: Kit de Inicio SaaS ===
    {
      id: 'g-es-04',
      name: 'Kit de Inicio SaaS',
      objective: 'Convertir fundadores de SaaS e independientes',
      budget: '400 €/mes',
      adGroups: [
        {
          id: 'g-es-04-brand',
          name: 'Marca',
          keywords: ['kit inicio ai empire', 'kit saas ai empire', 'bundle ai empire', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-es-04-brand-1', headline: 'AI Empire — Kit de Inicio SaaS Completo', description: 'Next.js 14, Stripe, Auth, APIs de IA, panel de administración. Todo para lanzar tu SaaS. Desde 19 €.', cta: 'Obtener kit' },
            { id: 'g-es-04-brand-2', headline: 'Lanza tu SaaS con AI Empire', description: '6 templates profesionales. Facturación con Stripe, autenticación, APIs de IA. Despliega en 24 horas.', cta: 'Ver templates' },
            { id: 'g-es-04-brand-3', headline: 'Bundle AI Empire — Todos los Templates', description: '6 templates + soporte prioritario + actualizaciones gratuitas. Kit de inicio SaaS completo por 299 €.', cta: 'Obtener bundle' },
          ],
        },
        {
          id: 'g-es-04-competitor',
          name: 'Competidor',
          keywords: ['kit inicio saas', 'boilerplate saas nextjs', 'herramienta independiente', 'template saas full stack', 'lanzar saas rápido'],
          ads: [
            { id: 'g-es-04-comp-1', headline: 'Kit de Inicio SaaS — Más que un Boilerplate', description: 'AI Empire incluye APIs de IA, panel de administración y templates reales. No solo código inicial.', cta: 'Comparar funciones' },
            { id: 'g-es-04-comp-2', headline: 'Lanza tu SaaS en 24 Horas', description: '¿Por qué pasar meses construyendo desde cero? Templates AI Empire: despliega hoy, mejora mañana.', cta: 'Ver templates' },
            { id: 'g-es-04-comp-3', headline: 'Kit de Herramientas SaaS para Independientes', description: 'Todo lo que necesitas: templates, APIs de IA, Stripe, autenticación. Desde 19 €. Capa gratuita para la API.', cta: 'Empezar a desarrollar' },
          ],
        },
        {
          id: 'g-es-04-generic',
          name: 'Genérico',
          keywords: ['template saas', 'cómo crear saas', 'template app saas', 'next.js saas', 'template saas stripe', 'mvp saas'],
          ads: [
            { id: 'g-es-04-gen-1', headline: 'Crea un MVP SaaS en Días', description: 'Templates Next.js 14 con Stripe, autenticación e IA. Desde 19 €. Despliega en Vercel.', cta: 'Empezar' },
            { id: 'g-es-04-gen-2', headline: 'Template SaaS — Stripe + Auth Incluidos', description: 'Templates Next.js 14 listos para producción. Pagos, autenticación, APIs de IA integradas.', cta: 'Explorar templates' },
            { id: 'g-es-04-gen-3', headline: 'Template SaaS Full Stack — Next.js 14', description: 'Stack moderno: Next.js 14, Tailwind, Stripe, IA. Templates desde 19 €.', cta: 'Ver templates' },
          ],
        },
      ],
    },
    // === Campaña 5: Alternativa a OpenAI ===
    {
      id: 'g-es-05',
      name: 'Alternativa a OpenAI',
      objective: 'Capturar tráfico de comparación con OpenAI',
      budget: '300 €/mes',
      adGroups: [
        {
          id: 'g-es-05-brand',
          name: 'Marca',
          keywords: ['ai empire vs openai', 'alternativa ai empire', 'precios ai empire', 'más barato que openai'],
          ads: [
            { id: 'g-es-05-brand-1', headline: 'AI Empire vs OpenAI — Misma Calidad, Menor Costo', description: 'Groq y Gemini a través de AI Empire. API unificada con capa gratuita. Ahorra hasta un 70% vs OpenAI.', cta: 'Comparar precios' },
            { id: 'g-es-05-brand-2', headline: 'Por qué Cambiar a AI Empire de OpenAI', description: 'Menor costo, múltiples modelos, API unificada, capa gratuita. Cambia en minutos, sin cambios de código.', cta: 'Ver precios' },
            { id: 'g-es-05-brand-3', headline: 'AI Empire — API de IA Económica', description: 'Groq + Gemini. 70% más barato que OpenAI con calidad similar. Créditos gratuitos al registrarte.', cta: 'Empezar gratis' },
          ],
        },
        {
          id: 'g-es-05-competitor',
          name: 'Competidor',
          keywords: ['alternativa api openai', 'más barato que api openai', 'alternativa precios openai', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-es-05-comp-1', headline: 'Alternativa OpenAI Más Barata — Prueba Gratis', description: 'AI Empire: API unificada Groq + Gemini. Capa gratuita, pago por uso. 70% menos que OpenAI.', cta: 'Probar gratis' },
            { id: 'g-es-05-comp-2', headline: 'API Groq y Gemini — Mejor Relación Calidad-Precio', description: '¿Por qué pagar más? Groq para velocidad, Gemini para capacidad. Una API, menor costo. Capa gratuita.', cta: 'Ver planes' },
            { id: 'g-es-05-comp-3', headline: 'Cambia de OpenAI — Ahorra 70%', description: 'AI Empire ofrece Groq + Gemini a través de una API unificada. Misma calidad, una fracción del costo.', cta: 'Comparar ahora' },
          ],
        },
        {
          id: 'g-es-05-generic',
          name: 'Genérico',
          keywords: ['precios api ia', 'costo api ia', 'precios groq', 'precios api gemini', 'comparativa api ia', 'api ia más barata'],
          ads: [
            { id: 'g-es-05-gen-1', headline: 'API de IA — Desde Gratis hasta Pago por Uso', description: 'Empieza gratis, escala a bajo costo. Groq + Gemini. Sin cuotas mensuales. Paga solo por lo que uses.', cta: 'Ver precios' },
            { id: 'g-es-05-gen-2', headline: 'API de IA Asequible — Groq + Gemini', description: 'Capa gratuita con 100 créditos. Pago por uso después. Sin mínimos, sin compromisos.', cta: 'Empezar' },
            { id: 'g-es-05-gen-3', headline: 'Precios API de IA — Transparentes y Justos', description: 'Sin costos ocultos. Groq + Gemini a través de una API unificada. Capa gratuita. Facturación con Stripe.', cta: 'Ver precios' },
          ],
        },
      ],
    },
    // === Campaña 6: Alternativa a Templates Vercel ===
    {
      id: 'g-es-06',
      name: 'Alternativa a Templates Vercel',
      objective: 'Capturar tráfico de comparación de templates',
      budget: '250 €/mes',
      adGroups: [
        {
          id: 'g-es-06-brand',
          name: 'Marca',
          keywords: ['ai empire vercel', 'despliegue ai empire', 'ai empire next.js', 'hosting ai empire'],
          ads: [
            { id: 'g-es-06-brand-1', headline: 'Templates AI Empire — Despliega en Vercel', description: 'Templates Next.js 14 optimizados para Vercel. APIs de IA, Stripe, autenticación incluidos. Despliega en minutos.', cta: 'Desplegar ahora' },
            { id: 'g-es-06-brand-2', headline: 'Templates SaaS Compatibles con Vercel', description: 'Templates AI Empire: diseñados para Vercel. Despliegue con un clic. Integración de IA, facturación, autenticación.', cta: 'Ver templates' },
            { id: 'g-es-06-brand-3', headline: 'Templates Next.js 14 para Vercel', description: 'Templates profesionales. Despliega en Vercel en minutos. APIs de IA y facturación con Stripe integradas.', cta: 'Obtener templates' },
          ],
        },
        {
          id: 'g-es-06-competitor',
          name: 'Competidor',
          keywords: ['alternativa template vercel', 'template next.js', 'mejor que template vercel', 'template saas vercel', 'template saas despliegue'],
          ads: [
            { id: 'g-es-06-comp-1', headline: 'Más Allá de Templates Básicos — AI Empire', description: 'A diferencia de los templates básicos de Vercel, AI Empire incluye APIs de IA, Stripe y panel de administración.', cta: 'Ver funciones' },
            { id: 'g-es-06-comp-2', headline: 'Template Next.js con IA y Stripe', description: 'AI Empire: no solo un template, un kit de inicio SaaS completo. APIs de IA, facturación, autenticación incluidos.', cta: 'Comparar' },
            { id: 'g-es-06-comp-3', headline: 'Templates SaaS en Producción — Next.js 14', description: 'Más allá de templates de demostración. AI Empire: autenticación real, pagos reales, integración de IA real.', cta: 'Ver templates' },
          ],
        },
        {
          id: 'g-es-06-generic',
          name: 'Genérico',
          keywords: ['template despliegue next.js', 'template despliegue saas', 'vercel saas', 'despliegue nextjs 14', 'template despliegue saas', 'template despliegue vercel'],
          ads: [
            { id: 'g-es-06-gen-1', headline: 'Despliega tu SaaS en Vercel Hoy', description: 'Templates Next.js 14. Despliegue con un clic. IA, Stripe, autenticación incluidos. Desde 19 €.', cta: 'Empezar a desplegar' },
            { id: 'g-es-06-gen-2', headline: 'Template SaaS — Listo para Desplegar', description: 'Templates Next.js 14 profesionales. Despliega en Vercel en minutos. Full stack incluido.', cta: 'Empezar' },
            { id: 'g-es-06-gen-3', headline: 'Next.js 14 SaaS — Despliega en Minutos', description: 'Templates con todo: autenticación, pagos, IA, administración. Despliegue instantáneo en Vercel.', cta: 'Explorar templates' },
          ],
        },
      ],
    },
    // === Campaña 7: Template E-commerce ===
    {
      id: 'g-es-07',
      name: 'Template E-commerce — NeuraStore',
      objective: 'Generar ventas del template NeuraStore',
      budget: '300 €/mes',
      adGroups: [
        {
          id: 'g-es-07-brand',
          name: 'Marca',
          keywords: ['neurastore', 'ecommerce ai empire', 'template neurastore', 'neurastore next.js'],
          ads: [
            { id: 'g-es-07-brand-1', headline: 'NeuraStore — Template E-commerce con IA', description: 'Template e-commerce Next.js 14 con Stripe, carrito, panel de administración. Recomendaciones de productos con IA.', cta: 'Ver NeuraStore' },
            { id: 'g-es-07-brand-2', headline: 'NeuraStore — Lanza tu Tienda Online', description: 'Template e-commerce profesional. Pagos con Stripe, gestión de inventario, diseño responsive.', cta: 'Ver demo' },
            { id: 'g-es-07-brand-3', headline: 'NeuraStore de AI Empire — 29 €', description: 'Template e-commerce completo. Next.js 14, Stripe, Tailwind. Despliega en minutos.', cta: 'Comprar NeuraStore' },
          ],
        },
        {
          id: 'g-es-07-competitor',
          name: 'Competidor',
          keywords: ['template ecommerce next.js', 'template tienda online', 'alternativa shopify template', 'template react ecommerce', 'template tienda nextjs'],
          ads: [
            { id: 'g-es-07-comp-1', headline: 'Template E-commerce — Posee tu Tienda', description: 'A diferencia de Shopify, NeuraStore es tuyo. Autoalojado, personalizable, con IA. 29 €.', cta: 'Obtener NeuraStore' },
            { id: 'g-es-07-comp-2', headline: 'E-commerce Next.js — Control Total', description: 'NeuraStore: posee tu código, tus datos, tu tienda. Integración con Stripe, panel de administración.', cta: 'Ver template' },
            { id: 'g-es-07-comp-3', headline: 'Crea tu Propia Tienda Online', description: 'Template NeuraStore: Next.js 14, Stripe, diseño responsive, panel de administración. 29 €.', cta: 'Empezar a desarrollar' },
          ],
        },
        {
          id: 'g-es-07-generic',
          name: 'Genérico',
          keywords: ['template sitio ecommerce', 'template tienda online', 'ecommerce nextjs', 'crear tienda online', 'template saas ecommerce', 'template tienda digital'],
          ads: [
            { id: 'g-es-07-gen-1', headline: 'Template Sitio E-commerce — Next.js 14', description: 'Template tienda online profesional. Stripe, carrito, administración. Responsive, modo oscuro. 29 €.', cta: 'Comprar template' },
            { id: 'g-es-07-gen-2', headline: 'Crea una Tienda Online con Next.js', description: 'NeuraStore: solución e-commerce completa. Pagos, gestión de inventario, recomendaciones de IA.', cta: 'Empezar' },
            { id: 'g-es-07-gen-3', headline: 'Template Tienda Online — Listo para Lanzar', description: 'Template e-commerce Next.js 14. Facturación con Stripe, diseño responsive, optimizado para SEO. 29 €.', cta: 'Desplegar ahora' },
          ],
        },
      ],
    },
    // === Campaña 8: Template Blog ===
    {
      id: 'g-es-08',
      name: 'Template Blog — NeuraBlog',
      objective: 'Generar ventas del template NeuraBlog',
      budget: '250 €/mes',
      adGroups: [
        {
          id: 'g-es-08-brand',
          name: 'Marca',
          keywords: ['neurablog', 'blog ai empire', 'template neurablog', 'neurablog next.js'],
          ads: [
            { id: 'g-es-08-brand-1', headline: 'NeuraBlog — Template Blog Optimizado para SEO', description: 'Template blog Next.js 14 con MDX, modo oscuro, feed RSS. Integración con newsletter incorporada.', cta: 'Ver NeuraBlog' },
            { id: 'g-es-08-brand-2', headline: 'NeuraBlog — Blog Profesional en Minutos', description: 'Template blog premium. Soporte MDX, optimización SEO, sistema de comentarios. 19 €.', cta: 'Ver demo' },
            { id: 'g-es-08-brand-3', headline: 'NeuraBlog de AI Empire — 19 €', description: 'Template blog completo. Next.js 14, MDX, modo oscuro, RSS. Despliega en Vercel.', cta: 'Comprar NeuraBlog' },
          ],
        },
        {
          id: 'g-es-08-competitor',
          name: 'Competidor',
          keywords: ['template blog next.js', 'alternativa wordpress', 'alternativa ghost', 'template blog mdx', 'template blog react'],
          ads: [
            { id: 'g-es-08-comp-1', headline: 'Template Blog — Más Rápido que WordPress', description: 'NeuraBlog: velocidad de sitio estático, funciones dinámicas. MDX, SEO, newsletter. 19 €.', cta: 'Probar NeuraBlog' },
            { id: 'g-es-08-comp-2', headline: 'Template Blog MDX — Next.js 14', description: 'A diferencia de Ghost, NeuraBlog te da control total. Autoalojado, rápido, personalizable.', cta: 'Ver template' },
            { id: 'g-es-08-comp-3', headline: 'Tu Blog, Tu Código — NeuraBlog', description: 'Posee tu plataforma de contenido. NeuraBlog: Next.js 14, MDX, modo oscuro, RSS. 19 €.', cta: 'Obtener NeuraBlog' },
          ],
        },
        {
          id: 'g-es-08-generic',
          name: 'Genérico',
          keywords: ['template blog', 'template blog personal', 'blog nextjs', 'template blog tech', 'crear un blog', 'template sitio blog'],
          ads: [
            { id: 'g-es-08-gen-1', headline: 'Template Blog — Lanza tu Blog Hoy', description: 'Template blog profesional. Optimizado para SEO, modo oscuro, newsletter. Despliega en minutos. 19 €.', cta: 'Empezar a bloguear' },
            { id: 'g-es-08-gen-2', headline: 'Blog Next.js 14 — Rápido y Hermoso', description: 'NeuraBlog: template blog moderno. MDX, modo oscuro, RSS, sistema de comentarios. 19 €.', cta: 'Ver template' },
            { id: 'g-es-08-gen-3', headline: 'Crea un Blog Profesional — 19 €', description: 'Template NeuraBlog. Optimizado para SEO, responsive, modo oscuro. Despliega en Vercel.', cta: 'Empezar' },
          ],
        },
      ],
    },
    // === Campaña 9: Template Portfolio ===
    {
      id: 'g-es-09',
      name: 'Template Portfolio — NeuraPortfolio',
      objective: 'Generar ventas del template NeuraPortfolio',
      budget: '200 €/mes',
      adGroups: [
        {
          id: 'g-es-09-brand',
          name: 'Marca',
          keywords: ['neuraportfolio', 'portfolio ai empire', 'template neuraportfolio', 'template portfolio desarrollador'],
          ads: [
            { id: 'g-es-09-brand-1', headline: 'NeuraPortfolio — Template Portfolio para Desarrolladores', description: 'Portfolio profesional con animaciones, modo oscuro, formulario de contacto. Next.js 14. 29 €.', cta: 'Ver NeuraPortfolio' },
            { id: 'g-es-09-brand-2', headline: 'NeuraPortfolio — Destaca en Línea', description: 'Template portfolio impresionante. Animaciones con Framer Motion, responsive, modo oscuro. 29 €.', cta: 'Ver demo' },
            { id: 'g-es-09-brand-3', headline: 'NeuraPortfolio de AI Empire — 29 €', description: 'Template portfolio completo. Next.js 14, animaciones, modo oscuro, formulario de contacto.', cta: 'Comprar NeuraPortfolio' },
          ],
        },
        {
          id: 'g-es-09-competitor',
          name: 'Competidor',
          keywords: ['template portfolio desarrollador', 'template sitio portfolio', 'mejor template portfolio', 'template portfolio creativo', 'portfolio freelance'],
          ads: [
            { id: 'g-es-09-comp-1', headline: 'Template Portfolio — Causa Buena Impresión', description: 'NeuraPortfolio: animaciones hermosas, diseño responsive, modo oscuro. Mejor que los temas genéricos.', cta: 'Ver template' },
            { id: 'g-es-09-comp-2', headline: 'Tu Portfolio Debe Destacar', description: 'NeuraPortfolio: animaciones Framer Motion, diseño moderno, personalización completa. 29 €.', cta: 'Ver NeuraPortfolio' },
            { id: 'g-es-09-comp-3', headline: 'Portfolio Desarrollador — Next.js 14', description: 'Crea tu portfolio con NeuraPortfolio. Rápido, hermoso, desplegable en minutos.', cta: 'Empezar' },
          ],
        },
        {
          id: 'g-es-09-generic',
          name: 'Genérico',
          keywords: ['sitio portfolio', 'crear portfolio', 'portfolio en línea', 'template sitio personal', 'template portfolio freelance', 'portfolio showcase'],
          ads: [
            { id: 'g-es-09-gen-1', headline: 'Crea tu Portfolio en Línea — 29 €', description: 'NeuraPortfolio: template profesional con animaciones. Despliega en minutos.', cta: 'Empezar a desarrollar' },
            { id: 'g-es-09-gen-2', headline: 'Template Sitio Personal — Next.js 14', description: 'Template portfolio hermoso. Modo oscuro, animaciones, responsive. Desde 29 €.', cta: 'Ver templates' },
            { id: 'g-es-09-gen-3', headline: 'Template Portfolio — Despliega Hoy', description: 'Portfolio profesional con diseño moderno. Framer Motion, modo oscuro. 29 €.', cta: 'Obtener portfolio' },
          ],
        },
      ],
    },
    // === Campaña 10: Constructor SaaS con IA ===
    {
      id: 'g-es-10',
      name: 'Constructor SaaS con IA',
      objective: 'Capturar intención de construcción de SaaS con IA',
      budget: '350 €/mes',
      adGroups: [
        {
          id: 'g-es-10-brand',
          name: 'Marca',
          keywords: ['constructor saas ai empire', 'crear saas ai empire', 'lanzar ai empire', 'plataforma ai empire'],
          ads: [
            { id: 'g-es-10-brand-1', headline: 'AI Empire — Crea tu SaaS con IA', description: 'Templates + APIs de IA + Stripe + Auth. Todo para construir y lanzar un SaaS impulsado por IA.', cta: 'Empezar a desarrollar' },
            { id: 'g-es-10-brand-2', headline: 'AI Empire — Tu Plataforma SaaS con IA', description: 'De la idea al lanzamiento. Templates, APIs de IA, pagos, autenticación. Despliega en 24 horas.', cta: 'Lanzar ahora' },
            { id: 'g-es-10-brand-3', headline: 'AI Empire — Entrega tu SaaS Más Rápido', description: 'Templates profesionales con integración de IA. Stripe, autenticación, panel de administración. Desde 19 €.', cta: 'Empezar' },
          ],
        },
        {
          id: 'g-es-10-competitor',
          name: 'Competidor',
          keywords: ['crear saas ia', 'constructor saas', 'template saas ia', 'plataforma saas ia', 'crear saas con ia', 'constructor producto ia'],
          ads: [
            { id: 'g-es-10-comp-1', headline: 'Crea un SaaS con IA — Sin Construir Todo', description: 'AI Empire: templates profesionales con APIs de IA integradas. Ahorra meses de desarrollo.', cta: 'Ver templates' },
            { id: 'g-es-10-comp-2', headline: 'Constructor SaaS con IA — Entrega en Días', description: 'Templates, APIs de IA, Stripe, autenticación. AI Empire: todo lo que necesitas para lanzar.', cta: 'Comparar funciones' },
            { id: 'g-es-10-comp-3', headline: 'Tu SaaS con IA — Lanza Esta Semana', description: '¿Por qué construir todo? Templates AI Empire: despliegue en 24 horas. Integración de IA incluida.', cta: 'Empezar gratis' },
          ],
        },
        {
          id: 'g-es-10-generic',
          name: 'Genérico',
          keywords: ['template saas', 'crear saas', 'app saas', 'plataforma saas', 'template producto ia', 'ideas saas', 'lanzar saas'],
          ads: [
            { id: 'g-es-10-gen-1', headline: 'Crea un SaaS — Templates, IA, Pagos', description: 'Templates Next.js 14 con APIs de IA, Stripe, autenticación. Desde 19 €. Despliega hoy.', cta: 'Empezar' },
            { id: 'g-es-10-gen-2', headline: 'Constructor SaaS — Todo Incluido', description: 'Templates, integración de IA, pagos, panel de administración. Kit SaaS completo. Desde 19 €.', cta: 'Explorar templates' },
            { id: 'g-es-10-gen-3', headline: 'Entrega tu Idea de SaaS — Next.js 14', description: 'Templates profesionales con stack moderno. IA, Stripe, autenticación. Despliega en minutos.', cta: 'Empezar a desarrollar' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Concienciación (2)
    {
      id: 'fb-es-01',
      name: 'Concienciación de Marca AI Empire',
      type: 'awareness',
      objective: 'Aumentar el conocimiento de marca entre desarrolladores y fundadores de startups',
      audience: 'Desarrolladores, CTO, fundadores de startups, de 22 a 45 años, interesados en IA, SaaS, Next.js, desarrollo web',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: '¿Estás construyendo un SaaS? AI Empire te ofrece templates Next.js 14, APIs de IA integradas (Groq + Gemini), facturación con Stripe y autenticación — todo desde 19 €. Únete a más de 5.000 desarrolladores que lanzaron más rápido.',
      cta: 'Saber más',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-es-02',
      name: 'Propuesta de Valor API de IA',
      type: 'awareness',
      objective: 'Educar a los desarrolladores sobre la API de IA unificada',
      audience: 'Desarrolladores de software, ingenieros ML, entusiastas de la IA, de 22 a 40 años',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'Una sola API para Groq y Gemini. AI Empire proporciona un endpoint unificado para múltiples modelos de IA — gratis para empezar, paga a medida que creces. Deja de gestionar múltiples SDKs de IA.',
      cta: 'Probar gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Consideración (3)
    {
      id: 'fb-es-03',
      name: 'Presentación del Producto NeuraStore',
      type: 'consideration',
      objective: 'Generar tráfico hacia la página del template NeuraStore',
      audience: 'Desarrolladores e-commerce, creadores de tiendas online, usuarios de Shopify buscando alternativas',
      placements: ['Facebook Feed', 'Instagram Feed', 'Marketplace'],
      adCopy: 'NeuraStore: un template e-commerce completo construido con Next.js 14. Pagos con Stripe, gestión de carrito, panel de administración y recomendaciones de productos con IA. 29 € — posee tu tienda, posee tu código.',
      cta: 'Ver template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-es-04',
      name: 'Oferta Bundle de Templates',
      type: 'consideration',
      objective: 'Generar interés en el bundle completo de templates',
      audience: 'Fundadores de SaaS, independientes, desarrolladores full stack',
      placements: ['Facebook Feed', 'Instagram Feed', 'Facebook Marketplace'],
      adCopy: 'Obtén los 6 templates de AI Empire por 299 €. NeuraStore, NeuraBlog, NeuraPortfolio y 3 más. Soporte prioritario, actualizaciones gratuitas, todo incluido. Ahorra más de 400 € vs comprar por separado.',
      cta: 'Ver bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-es-05',
      name: 'Tutorial de Integración de IA',
      type: 'consideration',
      objective: 'Enganchar a los desarrolladores con contenido educativo',
      audience: 'Desarrolladores web, desarrolladores React, desarrolladores Node.js',
      placements: ['Facebook Feed', 'Instagram Reels', 'Stories'],
      adCopy: 'Añade IA a tu app Next.js en 5 minutos. El SDK de AI Empire hace la integración sencilla — una clave API, un endpoint. Capa gratuita con 100 créditos. Documentación y ejemplos incluidos.',
      cta: 'Leer docs',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Conversión (3)
    {
      id: 'fb-es-06',
      name: 'Registro Gratuito API',
      type: 'conversion',
      objective: 'Generar registros en la capa gratuita',
      audience: 'Visitantes del sitio, lectores de documentación, lectores del blog, audiencias similares',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Tu API de IA gratuita te espera. Regístrate en AI Empire y obtén 100 créditos para Groq y Gemini. Sin tarjeta de crédito. Empieza a desarrollar con IA hoy.',
      cta: 'Registrarse gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-es-07',
      name: 'Conversión de Compra de Template',
      type: 'conversion',
      objective: 'Convertir visitantes de la página de template en compradores',
      audience: 'Visitantes de la página de template, carritos abandonados, usuarios con alta intención',
      placements: ['Facebook Feed', 'Instagram Feed', 'Messenger'],
      adCopy: '¿Sigues pensándolo? NeuraBlog (19 €) y NeuraStore (29 €) están listos para desplegar. Stripe, autenticación, integración de IA incluidos. Garantía de devolución.',
      cta: 'Comprar ahora',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-es-08',
      name: 'Oferta Limitada Bundle con Descuento',
      type: 'conversion',
      objective: 'Generar compras de bundle con urgencia',
      audience: 'Suscriptores de newsletter, carritos abandonados, usuarios muy comprometidos',
      placements: ['Facebook Feed', 'Instagram Feed', 'Instagram Stories'],
      adCopy: 'Oferta limitada: obtén el bundle completo de templates AI Empire por 299 € (ahorra más de 400 €). Incluye los 6 templates, soporte prioritario y actualizaciones gratuitas. La oferta termina pronto.',
      cta: 'Obtener bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Retargeting (2)
    {
      id: 'fb-es-09',
      name: 'Visitante de Regreso — Templates',
      type: 'retargeting',
      objective: 'Reenganchar a visitantes que vieron templates sin comprar',
      audience: 'Visitantes de la página de template (7-30 días), sin compra completada',
      placements: ['Facebook Feed', 'Instagram Feed', 'Audience Network'],
      adCopy: 'Estuviste viendo los templates de AI Empire. NeuraBlog empieza en 19 €, NeuraStore en 29 €. Full stack, listos para desplegar, con IA integrada. Regresa y lanza tu SaaS.',
      cta: 'Ver templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-es-10',
      name: 'Visitante de Regreso — API',
      type: 'retargeting',
      objective: 'Reenganchar a visitantes que exploraron la documentación de la API sin registrarse',
      audience: 'Visitantes de la página de docs (7-30 días), sin cuenta creada',
      placements: ['Facebook Feed', 'Instagram Stories', 'Reels'],
      adCopy: 'Exploraste nuestra documentación de API. ¿Listo para desarrollar? AI Empire te ofrece créditos gratuitos para Groq y Gemini. Regístrate en 30 segundos, sin tarjeta de crédito.',
      cta: 'Empezar gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Contenido patrocinado (4)
    {
      id: 'li-es-01',
      name: 'Anuncio de Lanzamiento SaaS',
      type: 'sponsored_content',
      objective: 'Generar registros entre tomadores de decisiones tecnológicos',
      audience: 'CTO, tech leads, gerentes de ingeniería en startups y pymes',
      headline: 'Lanza tu SaaS 10x más rápido con AI Empire',
      body: 'AI Empire proporciona templates Next.js 14 con APIs de IA integradas (Groq + Gemini), facturación con Stripe y autenticación. Pasa de la idea a un SaaS desplegado en 24 horas, no en meses.\n\nQué incluye:\n- 6 templates listos para producción (19 € - 299 €)\n- API de IA unificada con capa gratuita\n- Stripe + Auth configurados\n- Panel de administración\n\nÚnete a más de 5.000 desarrolladores construyendo con AI Empire.',
      cta: 'Empezar a desarrollar',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-es-02',
      name: 'API de IA para Empresas',
      type: 'sponsored_content',
      objective: 'Alcanzar líderes técnicos evaluando soluciones de API de IA',
      audience: 'Gerentes de ingeniería, VP de Ingeniería, arquitectos en empresas medianas y grandes',
      headline: 'API de IA Unificada — Groq + Gemini para tu Equipo',
      body: 'Deja de gestionar múltiples relaciones con proveedores de IA. AI Empire proporciona una API para Groq y Gemini — con facturación integrada, limitación de velocidad y monitoreo.\n\nPor qué los equipos técnicos eligen AI Empire:\n- Un endpoint para múltiples modelos de IA\n- SDKs para JavaScript y Python\n- Capa gratuita para prototipado\n- Pago por uso para escalar\n\nReduce la complejidad de tu integración de IA.',
      cta: 'Explorar API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-es-03',
      name: 'Éxito de Independientes',
      type: 'sponsored_content',
      objective: 'Atraer a independientes y fundadores solitarios',
      audience: 'Independientes, fundadores solitarios, fundadores de startups bootstrapped',
      headline: 'Entrega tu SaaS este fin de semana',
      body: 'Diseñado para fundadores solitarios que quieren avanzar rápido.\n\nAI Empire te ofrece:\n- Templates Next.js 14 profesionales\n- APIs de IA listas para usar\n- Stripe configurado en 5 minutos\n- Sin necesidad de programar para lanzar\n\nTemplates desde 19 €. Despliega en Vercel con un clic.\n\nDeja de pensarlo demasiado. Empieza a entregar.',
      cta: 'Ver templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-es-04',
      name: 'Comparación de Costos',
      type: 'sponsored_content',
      objective: 'Atraer a equipos preocupados por el costo que comparan proveedores de IA',
      audience: 'CTO, líderes financieros, compradores en startups y pymes',
      headline: 'APIs de IA — 70% menos que la Competencia',
      body: 'AI Empire combina Groq y Gemini en una sola API. Paga solo por lo que uses.\n\nComparación:\n- OpenAI: 0,03 €/1K tokens (GPT-4)\n- AI Empire: ~0,009 €/1K tokens (Groq Llama)\n\nCapa gratuita incluida. Sin bloqueo de proveedor. Cambia en minutos.\n\nMás de 5.000 desarrolladores ya están ahorrando.',
      cta: 'Ver precios',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Mensajes patrocinados (3)
    {
      id: 'li-es-05',
      name: 'Contacto Directo — CTO',
      type: 'message_ads',
      objective: 'Contacto personalizado con CTO de empresas objetivo',
      audience: 'CTO en empresas de 10 a 200 empleados en tecnología, SaaS y e-commerce',
      headline: 'Pregunta rápida sobre tu stack de IA',
      body: 'Hola {{first_name}},\n\nHe visto que {{company}} está desarrollando con IA. Pregunta rápida: ¿estás gestionando múltiples APIs de proveedores de IA?\n\nAI Empire proporciona una API unificada para Groq y Gemini — un endpoint, una factura, un panel de control. Capa gratuita incluida.\n\n¿Tendría sentido conversar 10 minutos? Con gusto te muestro cómo funciona.',
      cta: 'Programar una charla',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-es-06',
      name: 'Contacto Directo — Desarrolladores',
      type: 'message_ads',
      objective: 'Enganchar a desarrolladores individuales con ofertas personalizadas',
      audience: 'Desarrolladores full stack, desarrolladores React/Next.js en empresas tecnológicas',
      headline: '¿Desarrollas con Next.js?',
      body: 'Hola {{first_name}},\n\nHe visto que trabajas con Next.js. Creamos AI Empire específicamente para el ecosystème de Next.js — templates con APIs de IA, Stripe y autenticación listos para usar.\n\nSi estás trabajando en un proyecto personal o ayudando a tu equipo a entregar más rápido, nuestra capa gratuita podría ser útil.\n\nCon gusto te comparto un código de descuento si te interesa.',
      cta: 'Obtener código de descuento',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-es-07',
      name: 'Contacto de Asociación',
      type: 'message_ads',
      objective: 'Explorar oportunidades de asociación con agencias y consultoras',
      audience: 'Propietarios de agencias, fundadores de consultoras, líderes de transformación digital',
      headline: 'Oportunidad de asociación para {{company}}',
      body: 'Hola {{first_name}},\n\nAI Empire ayuda a los equipos a entregar productos impulsados por IA más rápido. Estamos construyendo un programa de asociación para agencias y consultoras que recomiendan nuestros templates y APIs a sus clientes.\n\nBeneficios:\n- Participación en ingresos por referidos\n- Soporte prioritario para tus clientes\n- Oportunidades de co-marketing\n\n¿Vale la pena explorarlo?',
      cta: 'Descubrir asociaciones',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dinámico (3)
    {
      id: 'li-es-08',
      name: 'Dinámico — Segmentación por Título',
      type: 'dynamic',
      objective: 'Segmentar desarrolladores por título con anuncios personalizados',
      audience: 'Usuarios con títulos: CTO, VP de Ingeniería, Tech Lead, Desarrollador Senior',
      headline: 'AI Empire para {{job_title}}s — Entrega Más Rápido',
      body: 'AI Empire proporciona a {{company_name}} un camino más rápido hacia la producción. Templates Next.js 14 con APIs de IA, Stripe y autenticación. Capa gratuita para prototipar, pago por uso para escalar.',
      cta: 'Explorar AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-es-09',
      name: 'Dinámico — Tamaño de Empresa',
      type: 'dynamic',
      objective: 'Adaptar el mensaje según el tamaño de la empresa',
      audience: 'Empresas de 1 a 50 empleados (startup) y 51 a 500 empleados (crecimiento)',
      headline: '{{company_name}} — Templates SaaS con IA',
      body: 'Para equipos en crecimiento: AI Empire proporciona templates Next.js 14 listos para producción con integración de IA. Despliega en días, no en meses. Desde 19 €.',
      cta: 'Ver templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-es-10',
      name: 'Dinámico — Segmentación por Industria',
      type: 'dynamic',
      objective: 'Segmentar industrias específicas con mensajes adaptados',
      audience: 'E-commerce, SaaS y agencias digitales',
      headline: 'Soluciones de IA para {{industry}}',
      body: 'Los templates de AI Empire están diseñados para {{industry}}. Next.js 14, Stripe, APIs de IA y paneles de administración. Desde 19 € hasta bundle de 299 €.',
      cta: 'Ver templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-es-01',
      tweet: 'Creamos AI Empire para que no tengas que construir todo.\n\nTemplates Next.js 14 + APIs Groq y Gemini + Stripe + Auth — todo en una plataforma.\n\nGratis para empezar. Despliega en minutos.',
      cta: 'Probar gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Desarrolladores, fundadores de startups',
    },
    {
      id: 'tw-es-02',
      tweet: 'Opinión polémica: Construir un SaaS no debería tomar 6 meses.\n\nTemplates AI Empire: Next.js 14 profesional, APIs de IA integradas, Stripe configurado.\n\nDe la idea al despliegue en 24 horas.',
      cta: 'Ver templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Independientes, fundadores solitarios',
    },
    {
      id: 'tw-es-03',
      tweet: 'Una API. Múltiples modelos de IA. Capa gratuita.\n\nAI Empire: Groq para velocidad, Gemini para capacidad. Endpoint unificado.\n\nDeja de gestionar 5 SDKs de IA diferentes.',
      cta: 'Obtener clave API',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'Desarrolladores de IA, tech leads',
    },
    {
      id: 'tw-es-04',
      tweet: 'NeuraStore: template e-commerce completo para Next.js 14.\n\nPagos con Stripe ✓ Carrito ✓ Panel de administración ✓ Recomendaciones de IA ✓\n\n29 €. Despliega en Vercel en minutos.',
      cta: 'Ver NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'Desarrolladores e-commerce',
    },
    {
      id: 'tw-es-05',
      tweet: 'Comparativa de precios OpenAI vs AI Empire:\n\nMismos resultados de calidad, 70% menos de costo.\n\nGroq + Gemini a través de una API unificada. Capa gratuita incluida. Sin bloqueo de proveedor.',
      cta: 'Comparar precios',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Desarrolladores preocupados por el costo',
    },
    {
      id: 'tw-es-06',
      tweet: 'Acabo de desplegar un SaaS en 4 horas usando templates de AI Empire.\n\nNext.js 14 + Stripe + Auth + APIs de IA. Todo configurado. Solo agrega tu código.',
      cta: 'Entregar más rápido',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Desarrolladores, fundadores de startups',
    },
    {
      id: 'tw-es-07',
      tweet: 'El bundle AI Empire: 6 templates, 299 €.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + 3 más. Soporte prioritario. Actualizaciones gratuitas.\n\nAhorra más de 400 € vs comprar por separado.',
      cta: 'Obtener bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'Fundadores de SaaS, desarrolladores',
    },
    {
      id: 'tw-es-08',
      tweet: '¿Cansado de WordPress?\n\nNeuraBlog: template blog Next.js 14. MDX, modo oscuro, RSS, optimizado para SEO. 19 €.\n\nRápido. Moderno. Tuyo.',
      cta: 'Ver NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Blogueros, creadores de contenido',
    },
    {
      id: 'tw-es-09',
      tweet: 'Capa gratuita de AI Empire: 100 créditos para Groq + Gemini.\n\nSin tarjeta de crédito. Sin compromisos. Solo crea.\n\nConfiguración en 5 minutos. SDKs para JS y Python.',
      cta: 'Empezar gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Estudiantes, desarrolladores aficionados',
    },
    {
      id: 'tw-es-10',
      tweet: 'Tu portfolio merece más que un template HTML básico.\n\nNeuraPortfolio: Next.js 14, animaciones Framer Motion, modo oscuro, responsive. 29 €.\n\nCausa buena impresión.',
      cta: 'Ver template portfolio',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Desarrolladores, diseñadores, freelancers',
    },
  ],
  instagram: [
    {
      id: 'ig-es-01',
      name: 'Presentación de la Plataforma — Reel',
      type: 'reel',
      script: 'Escena 1: Grabación de pantalla del panel — texto superpuesto "Conoce AI Empire". Escena 2: Editor de código mostrando llamada API — "Una API, Múltiples Modelos". Escena 3: Pago con Stripe — "Pagos en 5 Minutos". Escena 4: Despliegue en vivo — "Desplegado en 24 Horas". Escena 5: Logo + URL — "Empieza Gratis Hoy".',
      visualDirection: 'Grabaciones de pantalla rápidas con transiciones fluidas. Interfaz en modo oscuro. Colores de marca degradado púrpura. Música electrónica enérgica de fondo.',
      textOverlay: 'AI Empire — Construye tu SaaS Más Rápido',
      cta: 'Enlace en bio — Empezar Gratis',
      duration: '15-30 segundos',
    },
    {
      id: 'ig-es-02',
      name: 'Presentación NeuraStore — Story',
      type: 'story',
      script: 'Recorrido deslizando por el template NeuraStore. Mostrar cuadrícula de productos, flujo del carrito, pago con Stripe, vista responsive móvil. Terminar con etiqueta de precio (29 €) y llamada a la acción.',
      visualDirection: 'Fondos blancos/oscuros limpios. Maquetas de productos en iPhone y MacBook. Animaciones de deslizamiento fluidas. Acentos púrpura de marca.',
      textOverlay: 'NeuraStore — 29 € — Template E-commerce',
      cta: 'Deslizar para Ver',
      duration: '15 segundos',
    },
    {
      id: 'ig-es-03',
      name: 'Demo API de IA — Reel',
      type: 'reel',
      script: 'Escena 1: Desarrollador escribiendo código — "Añade IA a tu app". Escena 2: Terminal mostrando respuesta API — "Groq + Gemini en una llamada". Escena 3: App funcionando con funciones de IA — "Integración en 5 minutos". Escena 4: Pantalla de precios — "Gratis para empezar".',
      visualDirection: 'Planos sobre el hombro del desarrollador mezclados con grabaciones de pantalla. Tema oscuro. Terminal verde sobre negro. Edición rápida sincronizada con la música.',
      textOverlay: 'API de IA — Capa Gratuita Disponible',
      cta: 'Obtén tu Clave API — Enlace en bio',
      duration: '20-30 segundos',
    },
    {
      id: 'ig-es-04',
      name: 'Bundle de Templates — Story',
      type: 'story',
      script: 'Story en tres partes. Parte 1: Los 6 templates en cuadrícula — "6 Templates. 299 €." Parte 2: Destacados individuales — "NeuraStore, NeuraBlog, NeuraPortfolio..." Parte 3: Llamada de ahorro — "Ahorra más de 400 €" con botón de llamada a la acción.',
      visualDirection: 'Diseño de cuadrícula de productos. Cada template como maqueta de dispositivo. Fondo degradado púrpura. Tipografía audaz.',
      textOverlay: 'Bundle Completo — 299 € — Ahorra Más de 400 €',
      cta: 'Obtener Bundle',
      duration: '15 segundos por parte',
    },
    {
      id: 'ig-es-05',
      name: 'Testimonio de Desarrollador — Reel',
      type: 'reel',
      script: 'Escena 1: Video del desarrollador — "Lancé mi SaaS en 2 días con AI Empire". Escena 2: Grabación de pantalla de su app desplegada. Escena 3: Fragmentos de código mostrando la integración. Escena 4: Superposición de llamada a la acción.',
      visualDirection: 'Estilo UGC auténtico. Iluminación natural. Cámara en mano. Subtítulos para accesibilidad.',
      textOverlay: '"Lanzado en 2 Días" — @desarrollador',
      cta: 'Empezar a Desarrollar — Enlace en bio',
      duration: '30 segundos',
    },
    {
      id: 'ig-es-06',
      name: 'Funciones NeuraBlog — Story',
      type: 'story',
      script: 'Recorrido por NeuraBlog: editor MDX, cambio de modo oscuro, vista responsive móvil, vista previa del feed RSS, sección de comentarios. Terminar con precio (19 €) y llamada a la acción.',
      visualDirection: 'Grabación de pantalla con efectos de zoom en funciones clave. Pantalla dividida mostrando modo claro/oscuro. Estética limpia y minimalista.',
      textOverlay: 'NeuraBlog — 19 € — Template Blog SEO',
      cta: 'Deslizar — Ver Template',
      duration: '15 segundos',
    },
    {
      id: 'ig-es-07',
      name: 'Desafío de Velocidad SaaS — Reel',
      type: 'reel',
      script: 'Timelapse de construcción de un SaaS desde cero. Superposición de cronómetro de 0:00 a 4:00:00. Mostrar selección de template, configuración de API, configuración de Stripe, despliegue. Terminar con URL en vivo.',
      visualDirection: 'Pantalla dividida: cronómetro a la izquierda, grabación de pantalla a la derecha. Efecto acelerado. Música de fondo enérgica. Marcadores de hito a 1h, 2h, 3h.',
      textOverlay: 'SaaS Construido en 4 Horas',
      cta: 'Prueba AI Empire — Enlace en bio',
      duration: '30-60 segundos',
    },
    {
      id: 'ig-es-08',
      name: 'Anuncio Capa Gratuita — Story',
      type: 'story',
      script: 'Revelación con tipografía audaz: "GRATIS" → "API DE IA" → "100 Créditos" → "Groq + Gemini" → "Sin Tarjeta de Crédito" → Llamada a la acción. Cada elemento de texto aparece con efecto rebote o deslizamiento.',
      visualDirection: 'Fondos púrpuras/oscuros sólidos. Texto blanco grande y audaz. Diseño minimalista. Cada parte transiciona con animación contundente.',
      textOverlay: 'API IA GRATUITA — 100 Créditos — Sin Tarjeta',
      cta: 'Registrarse Gratis',
      duration: '10 segundos en total',
    },
    {
      id: 'ig-es-09',
      name: 'Presentación NeuraPortfolio — Reel',
      type: 'reel',
      script: 'Demostración de las animaciones de NeuraPortfolio: parallax de la sección hero, efectos hover en tarjetas de proyectos, transiciones de páginas fluidas, modo oscuro. Todo en una maqueta de MacBook.',
      visualDirection: 'Elegante, maqueta de dispositivo en slow motion. Movimientos sutiles de cámara. Iluminación suave. Música de fondo minimalista. Enfoque en calidad de animaciones.',
      textOverlay: 'NeuraPortfolio — 29 € — Portfolio Desarrollador',
      cta: 'Enlace en bio — Ver Demo',
      duration: '20-30 segundos',
    },
    {
      id: 'ig-es-10',
      name: 'Comparativa Antes/Después — Story',
      type: 'story',
      script: 'Parte 1: "Construir desde cero: 3 a 6 meses" con ícono de calendario. Parte 2: "Usar AI Empire: 1 a 2 días" con ícono de cohete. Parte 3: "Mismo resultado. 95% menos de tiempo." Parte 4: Llamada a la acción con precios.',
      visualDirection: 'Diseño de comparación lado a lado. Estilo antes/después. Rojo para la opción "lenta", verde para AI Empire. Tipografía contundente.',
      textOverlay: '3 Meses vs 2 Días — Elige la Rapidez',
      cta: 'Empezar Ahora — Enlace en bio',
      duration: '15 segundos por parte',
    },
  ],
};
