import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'fr',
  googleSearch: [
    // === Campagne 1 : Plateforme API IA ===
    {
      id: 'g-fr-01',
      name: 'Plateforme API IA',
      objective: 'Générer des inscriptions à la offre gratuite de l\'API IA',
      budget: '500 €/mois',
      adGroups: [
        {
          id: 'g-fr-01-brand',
          name: 'Marque',
          keywords: ['ai empire', 'ai-empire', 'api ai empire', 'plateforme ai empire'],
          ads: [
            { id: 'g-fr-01-brand-1', headline: 'AI Empire — Plateforme API IA Unifiée', description: 'Accédez à Groq et Gemini via une seule API. Offre gratuite disponible, sans carte bancaire. Intégration en 5 minutes.', cta: 'Essayer gratuitement' },
            { id: 'g-fr-01-brand-2', headline: 'AI Empire — Votre Passerelle API IA', description: 'Une API, plusieurs modèles IA. Groq + Gemini. Crédits gratuits à l\'inscription. SDK JavaScript et Python inclus.', cta: 'Obtenir la clé API' },
            { id: 'g-fr-01-brand-3', headline: 'AI Empire — Développez avec l\'IA dès aujourd\'hui', description: 'APIs IA prêtes pour la production. Groq pour la rapidité, Gemini pour les capacités. Offre gratuite, paiement à l\'usage.', cta: 'Commencer à développer' },
          ],
        },
        {
          id: 'g-fr-01-competitor',
          name: 'Concurrent',
          keywords: ['alternative openai', 'alternative api groq', 'api ia moins chère', 'wrapper api gemini', 'comparatif api ia'],
          ads: [
            { id: 'g-fr-01-comp-1', headline: 'API IA abordable — Économisez vs OpenAI', description: 'Même qualité d\'IA à moindre coût. Groq + Gemini unifiés. Offre gratuite avec 100 crédits. Changez en quelques minutes.', cta: 'Comparer les tarifs' },
            { id: 'g-fr-01-comp-2', headline: 'Alternative à OpenAI — AI Empire', description: 'À la recherche d\'une API IA économique ? AI Empire combine Groq et Gemini en un seul endpoint. Gratuit pour commencer.', cta: 'Voir les offres' },
            { id: 'g-fr-01-comp-3', headline: 'API IA — 70% moins cher qu\'OpenAI', description: 'Obtenez des résultats de qualité GPT avec Groq et Gemini. API unifiée. Offre gratuite. Sans engagement fournisseur.', cta: 'Commencer gratuitement' },
          ],
        },
        {
          id: 'g-fr-01-generic',
          name: 'Générique',
          keywords: ['api ia', 'api intelligence artificielle', 'api groq', 'api gemini', 'ia pour développeurs', 'api ia gratuite'],
          ads: [
            { id: 'g-fr-01-gen-1', headline: 'API IA pour développeurs — Offre gratuite', description: 'Groq + Gemini via une seule API. Crédits gratuits à l\'inscription. Documentation, exemples et SDK inclus.', cta: 'Lire la doc' },
            { id: 'g-fr-01-gen-2', headline: 'Intégrez l\'IA dans votre application — Mise en place en 5 min', description: 'Une API pour Groq et Gemini. Offre gratuite disponible. Facturation Stripe. Documentation complète.', cta: 'Commencer' },
            { id: 'g-fr-01-gen-3', headline: 'APIs IA — Groq et Gemini combinés', description: 'Endpoint unifié pour plusieurs modèles IA. Gratuit pour démarrer, payez au fur et à mesure. Prêt pour la production.', cta: 'Explorer l\'API' },
          ],
        },
      ],
    },
    // === Campagne 2 : Templates SaaS Next.js ===
    {
      id: 'g-fr-02',
      name: 'Templates SaaS Next.js',
      objective: 'Générer des ventes de templates',
      budget: '400 €/mois',
      adGroups: [
        {
          id: 'g-fr-02-brand',
          name: 'Marque',
          keywords: ['templates ai empire', 'saas ai empire', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-fr-02-brand-1', headline: 'AI Empire — Templates SaaS pour Next.js 14', description: 'Templates prêts pour la production avec intégration IA. NeuraStore, NeuraBlog, NeuraPortfolio. À partir de 19 €.', cta: 'Voir les templates' },
            { id: 'g-fr-02-brand-2', headline: 'NeuraStore et NeuraBlog par AI Empire', description: 'Templates Next.js 14 professionnels avec Stripe, authentification et IA intégrés. Déploiement en quelques minutes.', cta: 'Consulter les templates' },
            { id: 'g-fr-02-brand-3', headline: 'Templates AI Empire — Lancez votre SaaS', description: '6 templates premium. Next.js 14, Tailwind, Stripe, APIs IA inclus. De 19 € au bundle à 299 €.', cta: 'Parcourir les templates' },
          ],
        },
        {
          id: 'g-fr-02-competitor',
          name: 'Concurrent',
          keywords: ['boilerplate saas', 'template next.js', 'template saas react', 'kit de démarrage saas', 'template ecommerce nextjs'],
          ads: [
            { id: 'g-fr-02-comp-1', headline: 'Template SaaS Next.js — IA intégrée', description: 'Contrairement aux boilerplates génériques, les templates AI Empire incluent APIs IA, Stripe et authentification. Prêts à déployer.', cta: 'Comparer les templates' },
            { id: 'g-fr-02-comp-2', headline: 'Mieux qu\'un boilerplate SaaS', description: 'Templates AI Empire : design professionnel, intégration IA, facturation Stripe. Pas juste du code de démarrage.', cta: 'Voir la différence' },
            { id: 'g-fr-02-comp-3', headline: 'Template Next.js 14 — Prêt pour le full stack', description: 'Templates avec tout inclus : interface, API, authentification, paiements, IA. Déployez aujourd\'hui.', cta: 'Voir les templates' },
          ],
        },
        {
          id: 'g-fr-02-generic',
          name: 'Générique',
          keywords: ['template saas', 'template nextjs 14', 'template react', 'landing page saas', 'template pour saas', 'créer un saas vite'],
          ads: [
            { id: 'g-fr-02-gen-1', headline: 'Templates SaaS — Lancez en jours, pas en mois', description: 'Templates Next.js 14 avec authentification, Stripe, IA et tableau de bord admin. À partir de 19 €.', cta: 'Commencer' },
            { id: 'g-fr-02-gen-2', headline: 'Créez un SaaS avec Next.js 14', description: 'Templates prêts pour la production. Facturation Stripe, authentification, APIs IA, panneau d\'administration inclus.', cta: 'Explorer les templates' },
            { id: 'g-fr-02-gen-3', headline: 'Templates Next.js 14 E-commerce et Blog', description: 'Templates professionnels au design moderne. Responsive, mode sombre, optimisés SEO. À partir de 19 €.', cta: 'Acheter des templates' },
          ],
        },
      ],
    },
    // === Campagne 3 : Intégration IA ===
    {
      id: 'g-fr-03',
      name: 'Intégration IA',
      objective: 'Attirer les développeurs ayant besoin d\'intégration IA',
      budget: '350 €/mois',
      adGroups: [
        {
          id: 'g-fr-03-brand',
          name: 'Marque',
          keywords: ['intégration ai empire', 'documentation ai empire', 'sdk ai empire', 'docs api ai empire'],
          ads: [
            { id: 'g-fr-03-brand-1', headline: 'AI Empire — Ajoutez l\'IA à n\'importe quelle application', description: 'API simple pour ajouter des capacités IA à votre application. Groq + Gemini. SDKs pour JS et Python.', cta: 'Lire la doc' },
            { id: 'g-fr-03-brand-2', headline: 'SDK AI Empire — L\'IA en 5 minutes', description: 'Installez, configurez, déployez. Notre SDK rend l\'intégration IA simple. Offre gratuite disponible.', cta: 'Voir le SDK' },
            { id: 'g-fr-03-brand-3', headline: 'Documentation API AI Empire — Commencez à développer', description: 'Documentation complète, exemples de code et tutoriels. Ajoutez l\'IA à votre application Next.js dès aujourd\'hui.', cta: 'Lire la doc' },
          ],
        },
        {
          id: 'g-fr-03-competitor',
          name: 'Concurrent',
          keywords: ['service intégration ia', 'intégrer ia dans application', 'sdk ia', 'sdk groq', 'sdk gemini', 'wrapper api ia'],
          ads: [
            { id: 'g-fr-03-comp-1', headline: 'Intégration IA plus simple que le développement sur mesure', description: 'Arrêtez de maintenir plusieurs SDKs IA. AI Empire : une API, plusieurs modèles. Offre gratuite.', cta: 'Simplifier maintenant' },
            { id: 'g-fr-03-comp-2', headline: 'Intégration IA — Pas de configuration complexe', description: 'Une clé API, un endpoint. Groq et Gemini prêts. Crédits gratuits pour tester. Documentation incluse.', cta: 'Essayer gratuitement' },
            { id: 'g-fr-03-comp-3', headline: 'Remplacez votre wrapper API IA', description: 'AI Empire fournit une API unifiée prête pour la production. Facturation, limitation de débit et monitoring inclus.', cta: 'Découvrir comment' },
          ],
        },
        {
          id: 'g-fr-03-generic',
          name: 'Générique',
          keywords: ['ajouter ia à application', 'intégrer ia', 'api ia pour application web', 'intégration groq', 'intégration gemini', 'api ia rest'],
          ads: [
            { id: 'g-fr-03-gen-1', headline: 'Ajoutez l\'IA à votre application web — API REST simple', description: 'API REST pour Groq et Gemini. Offre gratuite. Réponses JSON. Compatible avec tous les langages.', cta: 'Commencer gratuitement' },
            { id: 'g-fr-03-gen-2', headline: 'Intégration API IA — Pour les développeurs', description: 'API bien documentée avec SDKs pour JavaScript et Python. Offre gratuite. Paiement à l\'usage.', cta: 'Voir la documentation' },
            { id: 'g-fr-03-gen-3', headline: 'API Groq + Gemini — Un seul endpoint', description: 'API unique pour plusieurs modèles IA. Crédits gratuits. Facturation Stripe. Prêt pour la production.', cta: 'Commencer' },
          ],
        },
      ],
    },
    // === Campagne 4 : Kit de démarrage SaaS ===
    {
      id: 'g-fr-04',
      name: 'Kit de démarrage SaaS',
      objective: 'Convertir les fondateurs de SaaS et les indépendants',
      budget: '400 €/mois',
      adGroups: [
        {
          id: 'g-fr-04-brand',
          name: 'Marque',
          keywords: ['kit démarrage ai empire', 'kit saas ai empire', 'bundle ai empire', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-fr-04-brand-1', headline: 'AI Empire — Kit de démarrage SaaS complet', description: 'Next.js 14, Stripe, Auth, APIs IA, tableau de bord admin. Tout pour lancer votre SaaS. À partir de 19 €.', cta: 'Obtenir le kit' },
            { id: 'g-fr-04-brand-2', headline: 'Lancez votre SaaS avec AI Empire', description: '6 templates professionnels. Facturation Stripe, authentification, APIs IA. Déploiement en 24 heures.', cta: 'Voir les templates' },
            { id: 'g-fr-04-brand-3', headline: 'Bundle AI Empire — Tous les templates', description: '6 templates + support prioritaire + mises à jour gratuites. Kit de démarrage SaaS complet pour 299 €.', cta: 'Obtenir le bundle' },
          ],
        },
        {
          id: 'g-fr-04-competitor',
          name: 'Concurrent',
          keywords: ['kit démarrage saas', 'boilerplate saas nextjs', 'toolkit indépendant', 'template saas full stack', 'lancer saas vite'],
          ads: [
            { id: 'g-fr-04-comp-1', headline: 'Kit de démarrage SaaS — Plus qu\'un boilerplate', description: 'AI Empire inclut APIs IA, tableau de bord admin et de vrais templates. Pas juste du code de démarrage.', cta: 'Comparer les fonctionnalités' },
            { id: 'g-fr-04-comp-2', headline: 'Lancez votre SaaS en 24 heures', description: 'Pourquoi passer des mois à tout construire ? Templates AI Empire : déployez aujourd\'hui, améliorez demain.', cta: 'Voir les templates' },
            { id: 'g-fr-04-comp-3', headline: 'Toolkit SaaS pour indépendants', description: 'Tout ce dont vous avez besoin : templates, APIs IA, Stripe, authentification. À partir de 19 €. Offre gratuite pour l\'API.', cta: 'Commencer à développer' },
          ],
        },
        {
          id: 'g-fr-04-generic',
          name: 'Générique',
          keywords: ['template saas', 'comment créer un saas', 'template application saas', 'next.js saas', 'template saas stripe', 'mvp saas'],
          ads: [
            { id: 'g-fr-04-gen-1', headline: 'Créez un MVP SaaS en quelques jours', description: 'Templates Next.js 14 avec Stripe, authentification et IA. À partir de 19 €. Déploiement sur Vercel.', cta: 'Commencer' },
            { id: 'g-fr-04-gen-2', headline: 'Template SaaS — Stripe + Auth inclus', description: 'Templates Next.js 14 prêts pour la production. Paiements, authentification, APIs IA intégrés.', cta: 'Explorer les templates' },
            { id: 'g-fr-04-gen-3', headline: 'Template SaaS full stack — Next.js 14', description: 'Stack moderne : Next.js 14, Tailwind, Stripe, IA. Templates à partir de 19 €.', cta: 'Voir les templates' },
          ],
        },
      ],
    },
    // === Campagne 5 : Alternative à OpenAI ===
    {
      id: 'g-fr-05',
      name: 'Alternative à OpenAI',
      objective: 'Capter le trafic de comparaison avec OpenAI',
      budget: '300 €/mois',
      adGroups: [
        {
          id: 'g-fr-05-brand',
          name: 'Marque',
          keywords: ['ai empire vs openai', 'alternative ai empire', 'tarifs ai empire', 'moins cher que openai'],
          ads: [
            { id: 'g-fr-05-brand-1', headline: 'AI Empire vs OpenAI — Même qualité, moindre coût', description: 'Groq et Gemini via AI Empire. API unifiée avec offre gratuite. Économisez jusqu\'à 70% vs OpenAI.', cta: 'Comparer les tarifs' },
            { id: 'g-fr-05-brand-2', headline: 'Pourquoi passer à AI Empire d\'OpenAI', description: 'Coût réduit, modèles multiples, API unifiée, offre gratuite. Changez en quelques minutes, sans modifier le code.', cta: 'Voir les tarifs' },
            { id: 'g-fr-05-brand-3', headline: 'AI Empire — API IA économique', description: 'Groq + Gemini. 70% moins cher qu\'OpenAI pour une qualité similaire. Crédits gratuits à l\'inscription.', cta: 'Commencer gratuitement' },
          ],
        },
        {
          id: 'g-fr-05-competitor',
          name: 'Concurrent',
          keywords: ['alternative api openai', 'moins cher que api openai', 'alternative tarifs openai', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-fr-05-comp-1', headline: 'Alternative OpenAI moins chère — Essayez gratuitement', description: 'AI Empire : API unifiée Groq + Gemini. Offre gratuite, paiement à l\'usage. 70% moins cher qu\'OpenAI.', cta: 'Essayer gratuitement' },
            { id: 'g-fr-05-comp-2', headline: 'API Groq et Gemini — Meilleur rapport qualité-prix', description: 'Pourquoi payer plus ? Groq pour la rapidité, Gemini pour les capacités. Une API, moindre coût. Offre gratuite.', cta: 'Voir les offres' },
            { id: 'g-fr-05-comp-3', headline: 'Passez d\'OpenAI — Économisez 70%', description: 'AI Empire propose Groq + Gemini via une API unifiée. Même qualité, une fraction du coût.', cta: 'Comparer maintenant' },
          ],
        },
        {
          id: 'g-fr-05-generic',
          name: 'Générique',
          keywords: ['tarifs api ia', 'coût api ia', 'tarifs groq', 'tarifs api gemini', 'comparatif api ia', 'api ia la moins chère'],
          ads: [
            { id: 'g-fr-05-gen-1', headline: 'API IA — Du gratuit au paiement à l\'usage', description: 'Commencez gratuitement, évoluez à moindre coût. Groq + Gemini. Pas de frais mensuels. Payez uniquement ce que vous utilisez.', cta: 'Voir les tarifs' },
            { id: 'g-fr-05-gen-2', headline: 'API IA abordable — Groq + Gemini', description: 'Offre gratuite avec 100 crédits. Paiement à l\'usage ensuite. Pas de minimums, pas d\'engagement.', cta: 'Commencer' },
            { id: 'g-fr-05-gen-3', headline: 'Tarifs API IA — Transparents et équitables', description: 'Pas de frais cachés. Groq + Gemini via une API unifiée. Offre gratuite. Facturation Stripe.', cta: 'Voir les tarifs' },
          ],
        },
      ],
    },
    // === Campagne 6 : Alternative aux templates Vercel ===
    {
      id: 'g-fr-06',
      name: 'Alternative aux templates Vercel',
      objective: 'Capter le trafic de comparaison de templates',
      budget: '250 €/mois',
      adGroups: [
        {
          id: 'g-fr-06-brand',
          name: 'Marque',
          keywords: ['ai empire vercel', 'déploiement ai empire', 'ai empire next.js', 'hébergement ai empire'],
          ads: [
            { id: 'g-fr-06-brand-1', headline: 'Templates AI Empire — Déployez sur Vercel', description: 'Templates Next.js 14 optimisés pour Vercel. APIs IA, Stripe, authentification inclus. Déploiement en quelques minutes.', cta: 'Déployer maintenant' },
            { id: 'g-fr-06-brand-2', headline: 'Templates SaaS compatibles Vercel', description: 'Templates AI Empire : conçus pour Vercel. Déploiement en un clic. Intégration IA, facturation, authentification.', cta: 'Voir les templates' },
            { id: 'g-fr-06-brand-3', headline: 'Templates Next.js 14 pour Vercel', description: 'Templates professionnels. Déploiement sur Vercel en quelques minutes. APIs IA et facturation Stripe intégrés.', cta: 'Obtenir les templates' },
          ],
        },
        {
          id: 'g-fr-06-competitor',
          name: 'Concurrent',
          keywords: ['alternative template vercel', 'template next.js', 'meilleur que template vercel', 'template saas vercel', 'template saas déploiement'],
          ads: [
            { id: 'g-fr-06-comp-1', headline: 'Au-delà des templates basiques — AI Empire', description: 'Contrairement aux templates Vercel simples, AI Empire inclut APIs IA, Stripe et tableau de bord admin.', cta: 'Voir les fonctionnalités' },
            { id: 'g-fr-06-comp-2', headline: 'Template Next.js avec IA et Stripe', description: 'AI Empire : pas juste un template, un véritable kit de démarrage SaaS. APIs IA, facturation, authentification inclus.', cta: 'Comparer' },
            { id: 'g-fr-06-comp-3', headline: 'Templates SaaS production — Next.js 14', description: 'Au-delà des templates de démo. AI Empire : vraie authentification, vrais paiements, vraie intégration IA.', cta: 'Voir les templates' },
          ],
        },
        {
          id: 'g-fr-06-generic',
          name: 'Générique',
          keywords: ['template déploiement next.js', 'template déploiement saas', 'vercel saas', 'déploiement nextjs 14', 'template déploiement saas', 'template déploiement vercel'],
          ads: [
            { id: 'g-fr-06-gen-1', headline: 'Déployez votre SaaS sur Vercel dès aujourd\'hui', description: 'Templates Next.js 14. Déploiement en un clic. IA, Stripe, authentification inclus. À partir de 19 €.', cta: 'Commencer le déploiement' },
            { id: 'g-fr-06-gen-2', headline: 'Template SaaS — Prêt à déployer', description: 'Templates Next.js 14 professionnels. Déploiement sur Vercel en quelques minutes. Full stack inclus.', cta: 'Commencer' },
            { id: 'g-fr-06-gen-3', headline: 'Next.js 14 SaaS — Déploiement en quelques minutes', description: 'Templates avec tout : authentification, paiements, IA, admin. Déploiement instantané sur Vercel.', cta: 'Explorer les templates' },
          ],
        },
      ],
    },
    // === Campagne 7 : Template E-commerce ===
    {
      id: 'g-fr-07',
      name: 'Template E-commerce — NeuraStore',
      objective: 'Générer des ventes du template NeuraStore',
      budget: '300 €/mois',
      adGroups: [
        {
          id: 'g-fr-07-brand',
          name: 'Marque',
          keywords: ['neurastore', 'ecommerce ai empire', 'template neurastore', 'neurastore next.js'],
          ads: [
            { id: 'g-fr-07-brand-1', headline: 'NeuraStore — Template e-commerce propulsé par l\'IA', description: 'Template e-commerce Next.js 14 avec Stripe, panier, tableau de bord admin. Recommandations produits par IA.', cta: 'Voir NeuraStore' },
            { id: 'g-fr-07-brand-2', headline: 'NeuraStore — Lancez votre boutique en ligne', description: 'Template e-commerce professionnel. Paiements Stripe, gestion des stocks, design responsive.', cta: 'Voir la démo' },
            { id: 'g-fr-07-brand-3', headline: 'NeuraStore par AI Empire — 29 €', description: 'Template e-commerce complet. Next.js 14, Stripe, Tailwind. Déploiement en quelques minutes.', cta: 'Acheter NeuraStore' },
          ],
        },
        {
          id: 'g-fr-07-competitor',
          name: 'Concurrent',
          keywords: ['template ecommerce next.js', 'template boutique en ligne', 'alternative shopify template', 'template react ecommerce', 'template magasin nextjs'],
          ads: [
            { id: 'g-fr-07-comp-1', headline: 'Template e-commerce — Possédez votre boutique', description: 'Contrairement à Shopify, NeuraStore vous appartient. Auto-hébergé, personnalisable, propulsé par l\'IA. 29 €.', cta: 'Obtenir NeuraStore' },
            { id: 'g-fr-07-comp-2', headline: 'E-commerce Next.js — Contrôle total', description: 'NeuraStore : possédez votre code, vos données, votre boutique. Intégration Stripe, tableau de bord admin.', cta: 'Voir le template' },
            { id: 'g-fr-07-comp-3', headline: 'Créez votre propre boutique en ligne', description: 'Template NeuraStore : Next.js 14, Stripe, design responsive, panneau d\'administration. 29 €.', cta: 'Commencer à développer' },
          ],
        },
        {
          id: 'g-fr-07-generic',
          name: 'Générique',
          keywords: ['template site ecommerce', 'template boutique en ligne', 'ecommerce nextjs', 'créer boutique en ligne', 'template saas ecommerce', 'template boutique numérique'],
          ads: [
            { id: 'g-fr-07-gen-1', headline: 'Template site e-commerce — Next.js 14', description: 'Template boutique en ligne professionnel. Stripe, panier, admin. Responsive, mode sombre. 29 €.', cta: 'Acheter le template' },
            { id: 'g-fr-07-gen-2', headline: 'Créez une boutique en ligne avec Next.js', description: 'NeuraStore : solution e-commerce complète. Paiements, gestion des stocks, recommandations IA.', cta: 'Commencer' },
            { id: 'g-fr-07-gen-3', headline: 'Template boutique en ligne — Prêt à lancer', description: 'Template e-commerce Next.js 14. Facturation Stripe, design responsive, optimisé SEO. 29 €.', cta: 'Déployer maintenant' },
          ],
        },
      ],
    },
    // === Campagne 8 : Template Blog ===
    {
      id: 'g-fr-08',
      name: 'Template Blog — NeuraBlog',
      objective: 'Générer des ventes du template NeuraBlog',
      budget: '250 €/mois',
      adGroups: [
        {
          id: 'g-fr-08-brand',
          name: 'Marque',
          keywords: ['neurablog', 'blog ai empire', 'template neurablog', 'neurablog next.js'],
          ads: [
            { id: 'g-fr-08-brand-1', headline: 'NeuraBlog — Template blog optimisé SEO', description: 'Template blog Next.js 14 avec MDX, mode sombre, flux RSS. Intégration newsletter intégrée.', cta: 'Voir NeuraBlog' },
            { id: 'g-fr-08-brand-2', headline: 'NeuraBlog — Blog professionnel en quelques minutes', description: 'Template blog premium. Support MDX, optimisation SEO, système de commentaires. 19 €.', cta: 'Voir la démo' },
            { id: 'g-fr-08-brand-3', headline: 'NeuraBlog par AI Empire — 19 €', description: 'Template blog complet. Next.js 14, MDX, mode sombre, RSS. Déploiement sur Vercel.', cta: 'Acheter NeuraBlog' },
          ],
        },
        {
          id: 'g-fr-08-competitor',
          name: 'Concurrent',
          keywords: ['template blog next.js', 'alternative wordpress', 'alternative ghost', 'template blog mdx', 'template blog react'],
          ads: [
            { id: 'g-fr-08-comp-1', headline: 'Template blog — Plus rapide que WordPress', description: 'NeuraBlog : vitesse de site statique, fonctionnalités dynamiques. MDX, SEO, newsletter. 19 €.', cta: 'Essayer NeuraBlog' },
            { id: 'g-fr-08-comp-2', headline: 'Template blog MDX — Next.js 14', description: 'Contrairement à Ghost, NeuraBlog vous donne le contrôle total. Auto-hébergé, rapide, personnalisable.', cta: 'Voir le template' },
            { id: 'g-fr-08-comp-3', headline: 'Votre blog, votre code — NeuraBlog', description: 'Possédez votre plateforme de contenu. NeuraBlog : Next.js 14, MDX, mode sombre, RSS. 19 €.', cta: 'Obtenir NeuraBlog' },
          ],
        },
        {
          id: 'g-fr-08-generic',
          name: 'Générique',
          keywords: ['template blog', 'template blog personnel', 'blog nextjs', 'template blog tech', 'créer un blog', 'template site blog'],
          ads: [
            { id: 'g-fr-08-gen-1', headline: 'Template blog — Lancez votre blog dès aujourd\'hui', description: 'Template blog professionnel. Optimisé SEO, mode sombre, newsletter. Déploiement en quelques minutes. 19 €.', cta: 'Commencer à bloguer' },
            { id: 'g-fr-08-gen-2', headline: 'Blog Next.js 14 — Rapide et magnifique', description: 'NeuraBlog : template blog moderne. MDX, mode sombre, RSS, système de commentaires. 19 €.', cta: 'Voir le template' },
            { id: 'g-fr-08-gen-3', headline: 'Créez un blog professionnel — 19 €', description: 'Template NeuraBlog. Optimisé SEO, responsive, mode sombre. Déploiement sur Vercel.', cta: 'Commencer' },
          ],
        },
      ],
    },
    // === Campagne 9 : Template Portfolio ===
    {
      id: 'g-fr-09',
      name: 'Template Portfolio — NeuraPortfolio',
      objective: 'Générer des ventes du template NeuraPortfolio',
      budget: '200 €/mois',
      adGroups: [
        {
          id: 'g-fr-09-brand',
          name: 'Marque',
          keywords: ['neuraportfolio', 'portfolio ai empire', 'template neuraportfolio', 'template portfolio développeur'],
          ads: [
            { id: 'g-fr-09-brand-1', headline: 'NeuraPortfolio — Template portfolio développeur', description: 'Portfolio professionnel avec animations, mode sombre, formulaire de contact. Next.js 14. 29 €.', cta: 'Voir NeuraPortfolio' },
            { id: 'g-fr-09-brand-2', headline: 'NeuraPortfolio — Démarquez-vous en ligne', description: 'Template portfolio éblouissant. Animations Framer Motion, responsive, mode sombre. 29 €.', cta: 'Voir la démo' },
            { id: 'g-fr-09-brand-3', headline: 'NeuraPortfolio par AI Empire — 29 €', description: 'Template portfolio complet. Next.js 14, animations, mode sombre, formulaire de contact.', cta: 'Acheter NeuraPortfolio' },
          ],
        },
        {
          id: 'g-fr-09-competitor',
          name: 'Concurrent',
          keywords: ['template portfolio développeur', 'template site portfolio', 'meilleur template portfolio', 'template portfolio créatif', 'portfolio freelance'],
          ads: [
            { id: 'g-fr-09-comp-1', headline: 'Template portfolio — Faites bonne impression', description: 'NeuraPortfolio : animations magnifiques, design responsive, mode sombre. Mieux que les thèmes génériques.', cta: 'Voir le template' },
            { id: 'g-fr-09-comp-2', headline: 'Votre portfolio doit se démarquer', description: 'NeuraPortfolio : animations Framer Motion, design moderne, personnalisation complète. 29 €.', cta: 'Voir NeuraPortfolio' },
            { id: 'g-fr-09-comp-3', headline: 'Portfolio développeur — Next.js 14', description: 'Créez votre portfolio avec NeuraPortfolio. Rapide, magnifique, déployable en quelques minutes.', cta: 'Commencer' },
          ],
        },
        {
          id: 'g-fr-09-generic',
          name: 'Générique',
          keywords: ['site portfolio', 'créer portfolio', 'portfolio en ligne', 'template site personnel', 'template portfolio freelance', 'portfolio showcase'],
          ads: [
            { id: 'g-fr-09-gen-1', headline: 'Créez votre portfolio en ligne — 29 €', description: 'NeuraPortfolio : template professionnel avec animations. Déploiement en quelques minutes.', cta: 'Commencer à développer' },
            { id: 'g-fr-09-gen-2', headline: 'Template site personnel — Next.js 14', description: 'Template portfolio magnifique. Mode sombre, animations, responsive. À partir de 29 €.', cta: 'Voir les templates' },
            { id: 'g-fr-09-gen-3', headline: 'Template portfolio — Déployez dès aujourd\'hui', description: 'Portfolio professionnel au design moderne. Framer Motion, mode sombre. 29 €.', cta: 'Obtenir le portfolio' },
          ],
        },
      ],
    },
    // === Campagne 10 : Constructeur SaaS IA ===
    {
      id: 'g-fr-10',
      name: 'Constructeur SaaS IA',
      objective: 'Capter l\'intention de construction de SaaS IA',
      budget: '350 €/mois',
      adGroups: [
        {
          id: 'g-fr-10-brand',
          name: 'Marque',
          keywords: ['constructeur saas ai empire', 'créer saas ai empire', 'lancer ai empire', 'plateforme ai empire'],
          ads: [
            { id: 'g-fr-10-brand-1', headline: 'AI Empire — Créez votre SaaS IA', description: 'Templates + APIs IA + Stripe + Auth. Tout pour construire et lancer un SaaS propulsé par l\'IA.', cta: 'Commencer à développer' },
            { id: 'g-fr-10-brand-2', headline: 'AI Empire — Votre plateforme SaaS IA', description: 'De l\'idée au lancement. Templates, APIs IA, paiements, authentification. Déploiement en 24 heures.', cta: 'Lancer maintenant' },
            { id: 'g-fr-10-brand-3', headline: 'AI Empire — Livrez votre SaaS plus vite', description: 'Templates professionnels avec intégration IA. Stripe, authentification, tableau de bord admin. À partir de 19 €.', cta: 'Commencer' },
          ],
        },
        {
          id: 'g-fr-10-competitor',
          name: 'Concurrent',
          keywords: ['créer saas ia', 'constructeur saas', 'template saas ia', 'plateforme saas ia', 'créer saas avec ia', 'constructeur produit ia'],
          ads: [
            { id: 'g-fr-10-comp-1', headline: 'Créez un SaaS IA — Sans tout construire', description: 'AI Empire : templates professionnels avec APIs IA intégrées. Économisez des mois de développement.', cta: 'Voir les templates' },
            { id: 'g-fr-10-comp-2', headline: 'Constructeur SaaS IA — Livrez en quelques jours', description: 'Templates, APIs IA, Stripe, authentification. AI Empire : tout ce dont vous avez besoin pour lancer.', cta: 'Comparer les fonctionnalités' },
            { id: 'g-fr-10-comp-3', headline: 'Votre SaaS IA — Lancez cette semaine', description: 'Pourquoi tout construire ? Templates AI Empire : déploiement en 24 heures. Intégration IA incluse.', cta: 'Commencer gratuitement' },
          ],
        },
        {
          id: 'g-fr-10-generic',
          name: 'Générique',
          keywords: ['template saas', 'créer saas', 'application saas', 'plateforme saas', 'template produit ia', 'idées saas', 'lancer saas'],
          ads: [
            { id: 'g-fr-10-gen-1', headline: 'Créez un SaaS — Templates, IA, paiements', description: 'Templates Next.js 14 avec APIs IA, Stripe, authentification. À partir de 19 €. Déploiement aujourd\'hui.', cta: 'Commencer' },
            { id: 'g-fr-10-gen-2', headline: 'Constructeur SaaS — Tout inclus', description: 'Templates, intégration IA, paiements, tableau de bord admin. Kit SaaS complet. À partir de 19 €.', cta: 'Explorer les templates' },
            { id: 'g-fr-10-gen-3', headline: 'Lancez votre idée de SaaS — Next.js 14', description: 'Templates professionnels avec stack moderne. IA, Stripe, authentification. Déploiement en quelques minutes.', cta: 'Commencer à développer' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Sensibilisation (2)
    {
      id: 'fb-fr-01',
      name: 'Sensibilisation à la marque AI Empire',
      type: 'awareness',
      objective: 'Augmenter la notoriété de la marque auprès des développeurs et fondateurs de startups',
      audience: 'Développeurs, CTO, fondateurs de startups, 22-45 ans, intéressés par l\'IA, le SaaS, Next.js, le développement web',
      placements: ['Fil Facebook', 'Fil Instagram', 'Audience Network'],
      adCopy: 'Vous construisez un SaaS ? AI Empire vous offre des templates Next.js 14, des APIs IA intégrées (Groq + Gemini), une facturation Stripe et une authentification — le tout à partir de 19 €. Rejoignez plus de 5 000 développeurs qui ont lancé plus vite.',
      cta: 'En savoir plus',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-fr-02',
      name: 'Proposition de valeur API IA',
      type: 'awareness',
      objective: 'Éduquer les développeurs sur l\'API IA unifiée',
      audience: 'Développeurs logiciels, ingénieurs ML, passionnés d\'IA, 22-40 ans',
      placements: ['Fil Facebook', 'Stories Instagram', 'Reels'],
      adCopy: 'Une seule API pour Groq et Gemini. AI Empire fournit un endpoint unifié pour plusieurs modèles IA — gratuit pour démarrer, payez au fur et à mesure. Arrêtez de gérer plusieurs SDKs IA.',
      cta: 'Essayer gratuitement',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Considération (3)
    {
      id: 'fb-fr-03',
      name: 'Présentation du produit NeuraStore',
      type: 'consideration',
      objective: 'Générer du trafic vers la page du template NeuraStore',
      audience: 'Développeurs e-commerce, créateurs de boutiques en ligne, utilisateurs Shopify à la recherche d\'alternatives',
      placements: ['Fil Facebook', 'Fil Instagram', 'Marketplace'],
      adCopy: 'NeuraStore : template e-commerce complet construit avec Next.js 14. Paiements Stripe, gestion du panier, tableau de bord admin et recommandations produits par IA. 29 € — possédez votre boutique, possédez votre code.',
      cta: 'Voir le template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-fr-04',
      name: 'Offre bundle de templates',
      type: 'consideration',
      objective: 'Stimuler l\'intérêt pour le bundle complet de templates',
      audience: 'Fondateurs de SaaS, indépendants, développeurs full stack',
      placements: ['Fil Facebook', 'Fil Instagram', 'Marketplace Facebook'],
      adCopy: 'Obtenez les 6 templates AI Empire pour 299 €. NeuraStore, NeuraBlog, NeuraPortfolio et 3 autres. Support prioritaire, mises à jour gratuites, tout inclus. Économisez plus de 400 € par rapport à l\'achat individuel.',
      cta: 'Voir le bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-fr-05',
      name: 'Tutoriel d\'intégration IA',
      type: 'consideration',
      objective: 'Engager les développeurs avec du contenu éducatif',
      audience: 'Développeurs web, développeurs React, développeurs Node.js',
      placements: ['Fil Facebook', 'Reels Instagram', 'Stories'],
      adCopy: 'Ajoutez l\'IA à votre application Next.js en 5 minutes. Le SDK d\'AI Empire rend l\'intégration simple — une clé API, un endpoint. Offre gratuite avec 100 crédits. Documentation et exemples inclus.',
      cta: 'Lire la doc',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Conversion (3)
    {
      id: 'fb-fr-06',
      name: 'Inscription gratuite à l\'API',
      type: 'conversion',
      objective: 'Générer des inscriptions à l\'offre gratuite',
      audience: 'Visiteurs du site, lecteurs de la documentation, lecteurs du blog, audiences similaires',
      placements: ['Fil Facebook', 'Fil Instagram', 'Audience Network'],
      adCopy: 'Votre API IA gratuite vous attend. Inscrivez-vous sur AI Empire et obtenez 100 crédits pour Groq et Gemini. Sans carte bancaire. Commencez à développer avec l\'IA dès aujourd\'hui.',
      cta: 'S\'inscrire gratuitement',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-fr-07',
      name: 'Conversion achat de template',
      type: 'conversion',
      objective: 'Convertir les visiteurs de la page template en acheteurs',
      audience: 'Visiteurs de la page template, paniers abandonnés, utilisateurs à forte intention',
      placements: ['Fil Facebook', 'Fil Instagram', 'Messenger'],
      adCopy: 'Vous hésitez encore ? NeuraBlog (19 €) et NeuraStore (29 €) sont prêts à déployer. Stripe, authentification, intégration IA inclus. Garantie satisfait ou remboursé.',
      cta: 'Acheter maintenant',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-fr-08',
      name: 'Offre limitée bundle avec réduction',
      type: 'conversion',
      objective: 'Générer des achats de bundle avec un sentiment d\'urgence',
      audience: 'Abonnés newsletter, paniers abandonnés, utilisateurs très engagés',
      placements: ['Fil Facebook', 'Fil Instagram', 'Stories Instagram'],
      adCopy: 'Offre limitée : obtenez le bundle complet de templates AI Empire pour 299 € (économisez plus de 400 €). Inclut les 6 templates, le support prioritaire et les mises à jour gratuites. L\'offre se termine bientôt.',
      cta: 'Obtenir le bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Reciblage (2)
    {
      id: 'fb-fr-09',
      name: 'Visiteur de retour — Templates',
      type: 'retargeting',
      objective: 'Réengager les visiteurs qui ont consulté les templates sans acheter',
      audience: 'Visiteurs de la page template (7-30 jours), pas d\'achat effectué',
      placements: ['Fil Facebook', 'Fil Instagram', 'Audience Network'],
      adCopy: 'Vous consultiez les templates AI Empire. NeuraBlog commence à 19 €, NeuraStore à 29 €. Full stack, prêts à déployer, IA intégrée. Revenez et lancez votre SaaS.',
      cta: 'Voir les templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-fr-10',
      name: 'Visiteur de retour — API',
      type: 'retargeting',
      objective: 'Réengager les visiteurs qui ont exploré la doc API sans s\'inscrire',
      audience: 'Visiteurs de la page doc (7-30 jours), pas de compte créé',
      placements: ['Fil Facebook', 'Stories Instagram', 'Reels'],
      adCopy: 'Vous avez exploré notre documentation API. Prêt à développer ? AI Empire vous offre des crédits gratuits pour Groq et Gemini. Inscription en 30 secondes, sans carte bancaire.',
      cta: 'Commencer gratuitement',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Contenu sponsorisé (4)
    {
      id: 'li-fr-01',
      name: 'Annonce de lancement SaaS',
      type: 'sponsored_content',
      objective: 'Générer des inscriptions auprès des décideurs tech',
      audience: 'CTO, tech leads, managers d\'ingénierie dans les startups et PME',
      headline: 'Lancez votre SaaS 10x plus vite avec AI Empire',
      body: 'AI Empire fournit des templates Next.js 14 avec APIs IA intégrées (Groq + Gemini), facturation Stripe et authentification. Passez de l\'idée à un SaaS déployé en 24 heures, pas en mois.\n\nCe qui est inclus :\n- 6 templates prêts pour la production (19 € - 299 €)\n- API IA unifiée avec offre gratuite\n- Stripe + Auth configurés\n- Tableau de bord administrateur\n\nRejoignez plus de 5 000 développeurs qui construisent avec AI Empire.',
      cta: 'Commencer à développer',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-fr-02',
      name: 'API IA pour les entreprises',
      type: 'sponsored_content',
      objective: 'Atteindre les leaders techniques qui évaluent des solutions API IA',
      audience: 'Managers d\'ingénierie, VP Engineering, architectes dans les entreprises moyennes et grandes',
      headline: 'API IA unifiée — Groq + Gemini pour votre équipe',
      body: 'Arrêtez de gérer plusieurs relations fournisseurs IA. AI Empire fournit une API pour Groq et Gemini — avec facturation intégrée, limitation de débit et monitoring.\n\nPourquoi les équipes techniques choisissent AI Empire :\n- Un endpoint pour plusieurs modèles IA\n- SDKs JavaScript et Python\n- Offre gratuite pour le prototypage\n- Paiement à l\'usage pour l\'évolution\n\nRéduisez la complexité de votre intégration IA.',
      cta: 'Explorer l\'API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-fr-03',
      name: 'Succès des indépendants',
      type: 'sponsored_content',
      objective: 'Attirer les indépendants et fondateurs solo',
      audience: 'Indépendants, fondateurs solo, fondateurs de startups bootstrappées',
      headline: 'Livrez votre SaaS ce week-end',
      body: 'Conçu pour les fondateurs solo qui veulent avancer vite.\n\nAI Empire vous offre :\n- Des templates Next.js 14 professionnels\n- Des APIs IA prêtes à l\'emploi\n- Stripe configuré en 5 minutes\n- Aucune programmation requise pour le lancement\n\nTemplates à partir de 19 €. Déploiement sur Vercel en un clic.\n\nArrêtez de trop réfléchir. Commencez à livrer.',
      cta: 'Voir les templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-fr-04',
      name: 'Comparaison de coûts',
      type: 'sponsored_content',
      objective: 'Séduire les équipes soucieuses des coûts comparant les fournisseurs IA',
      audience: 'CTO, responsables financiers, acheteurs dans les startups et PME',
      headline: 'APIs IA — 70% moins que les concurrents',
      body: 'AI Empire combine Groq et Gemini dans une seule API. Payez uniquement ce que vous utilisez.\n\nComparaison :\n- OpenAI : 0,03 €/1K tokens (GPT-4)\n- AI Empire : ~0,009 €/1K tokens (Groq Llama)\n\nOffre gratuite incluse. Sans engagement fournisseur. Changez en quelques minutes.\n\nPlus de 5 000 développeurs économisent déjà.',
      cta: 'Voir les tarifs',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Messages sponsorisés (3)
    {
      id: 'li-fr-05',
      name: 'Contact direct — CTO',
      type: 'message_ads',
      objective: 'Contact personnalisé auprès des CTO d\'entreprises cibles',
      audience: 'CTO d\'entreprises de 10 à 200 salariés dans la tech, le SaaS et l\'e-commerce',
      headline: 'Question rapide sur votre stack IA',
      body: 'Bonjour {{first_name}},\n\nJ\'ai remarqué que {{company}} développe avec l\'IA. Question rapide : vous gérez plusieurs API de fournisseurs IA ?\n\nAI Empire fournit une API unifiée pour Groq et Gemini — un endpoint, une facture, un tableau de bord. Offre gratuite incluse.\n\nEst-ce qu\'on pourrait échanger 10 minutes ? Je serais ravi de vous montrer comment ça fonctionne.',
      cta: 'Planifier un échange',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-fr-06',
      name: 'Contact direct — Développeurs',
      type: 'message_ads',
      objective: 'Engager les développeurs individuels avec des offres personnalisées',
      audience: 'Développeurs full stack, développeurs React/Next.js dans les entreprises tech',
      headline: 'Vous développez avec Next.js ?',
      body: 'Bonjour {{first_name}},\n\nJ\'ai vu que vous travailliez avec Next.js. Nous avons créé AI Empire spécifiquement pour l\'écosystème Next.js — des templates avec APIs IA, Stripe et authentification prêts à l\'emploi.\n\nSi vous travaillez sur un projet personnel ou si vous aidez votre équipe à livrer plus vite, notre offre gratuite pourrait vous être utile.\n\nJe serais ravi de vous partager un code de réduction si ça vous intéresse.',
      cta: 'Obtenir un code promo',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-fr-07',
      name: 'Contact partenariat',
      type: 'message_ads',
      objective: 'Explorer les opportunités de partenariat avec les agences et cabinets de conseil',
      audience: 'Propriétaires d\'agences, fondateurs de cabinets, leaders de la transformation digitale',
      headline: 'Opportunité de partenariat pour {{company}}',
      body: 'Bonjour {{first_name}},\n\nAI Empire aide les équipes à livrer des produits propulsés par l\'IA plus vite. Nous construisons un programme partenaire pour les agences et cabinets qui recommandent nos templates et APIs à leurs clients.\n\nAvantages :\n- Part de revenus sur les recommandations\n- Support prioritaire pour vos clients\n- Opportunités de co-marketing\n\nÇa vaut le coup d\'explorer ?',
      cta: 'Découvrir les partenariats',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dynamique (3)
    {
      id: 'li-fr-08',
      name: 'Dynamique — Ciblage par titre',
      type: 'dynamic',
      objective: 'Cibler les développeurs par titre avec des publicités personnalisées',
      audience: 'Utilisateurs avec les titres : CTO, VP Engineering, Tech Lead, Développeur Senior',
      headline: 'AI Empire pour les {{job_title}} — Livrez plus vite',
      body: 'AI Empire offre à {{company_name}} un chemin plus rapide vers la production. Templates Next.js 14 avec APIs IA, Stripe et authentification. Offre gratuite pour prototyper, paiement à l\'usage pour évoluer.',
      cta: 'Explorer AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-fr-09',
      name: 'Dynamique — Taille d\'entreprise',
      type: 'dynamic',
      objective: 'Adapter le message selon la taille de l\'entreprise',
      audience: 'Entreprises de 1 à 50 salariés (startup) et 51 à 500 salariés (croissance)',
      headline: '{{company_name}} — Templates SaaS IA',
      body: 'Pour les équipes en croissance : AI Empire fournit des templates Next.js 14 prêts pour la production avec intégration IA. Déploiement en jours, pas en mois. À partir de 19 €.',
      cta: 'Voir les templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-fr-10',
      name: 'Dynamique — Ciblage par secteur',
      type: 'dynamic',
      objective: 'Cibler des secteurs spécifiques avec un message adapté',
      audience: 'E-commerce, SaaS et agences digitales',
      headline: 'Solutions IA pour {{industry}}',
      body: 'Les templates AI Empire sont conçus pour le secteur {{industry}}. Next.js 14, Stripe, APIs IA et tableaux de bord admin. De 19 € au bundle à 299 €.',
      cta: 'Voir les templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-fr-01',
      tweet: 'Nous avons créé AI Empire pour que vous n\'ayez pas à tout construire.\n\nTemplates Next.js 14 + APIs Groq et Gemini + Stripe + Auth — tout sur une plateforme.\n\nGratuit pour commencer. Déploiement en quelques minutes.',
      cta: 'Essayer gratuitement',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Développeurs, fondateurs de startups',
    },
    {
      id: 'tw-fr-02',
      tweet: 'Débat : Construire un SaaS ne devrait pas prendre 6 mois.\n\nTemplates AI Empire : Next.js 14 professionnel, APIs IA intégrées, Stripe configuré.\n\nDe l\'idée au déploiement en 24 heures.',
      cta: 'Voir les templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Indépendants, fondateurs solo',
    },
    {
      id: 'tw-fr-03',
      tweet: 'Une API. Plusieurs modèles IA. Offre gratuite.\n\nAI Empire : Groq pour la rapidité, Gemini pour les capacités. Endpoint unifié.\n\nArrêtez de gérer 5 SDKs IA différents.',
      cta: 'Obtenir la clé API',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'Développeurs IA, tech leads',
    },
    {
      id: 'tw-fr-04',
      tweet: 'NeuraStore : template e-commerce complet pour Next.js 14.\n\nPaiements Stripe ✓ Panier ✓ Tableau de bord admin ✓ Recommandations IA ✓\n\n29 €. Déploiement sur Vercel en quelques minutes.',
      cta: 'Voir NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'Développeurs e-commerce',
    },
    {
      id: 'tw-fr-05',
      tweet: 'Comparaison des tarifs OpenAI vs AI Empire :\n\nRésultats de même qualité, 70% de coût en moins.\n\nGroq + Gemini via une API unifiée. Offre gratuite incluse. Sans engagement fournisseur.',
      cta: 'Comparer les tarifs',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Développeurs soucieux des coûts',
    },
    {
      id: 'tw-fr-06',
      tweet: 'Vient de déployer un SaaS en 4 heures avec les templates AI Empire.\n\nNext.js 14 + Stripe + Auth + APIs IA. Tout configuré. Il suffit d\'ajouter votre code.',
      cta: 'Livrer plus vite',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Développeurs, fondateurs de startups',
    },
    {
      id: 'tw-fr-07',
      tweet: 'Le bundle AI Empire : 6 templates, 299 €.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + 3 autres. Support prioritaire. Mises à jour gratuites.\n\nÉconomisez plus de 400 € par rapport à l\'achat individuel.',
      cta: 'Obtenir le bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'Fondateurs de SaaS, développeurs',
    },
    {
      id: 'tw-fr-08',
      tweet: 'Vous en avez assez de WordPress ?\n\nNeuraBlog : template blog Next.js 14. MDX, mode sombre, RSS, optimisé SEO. 19 €.\n\nRapide. Moderne. À vous.',
      cta: 'Voir NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Blogueurs, créateurs de contenu',
    },
    {
      id: 'tw-fr-09',
      tweet: 'Offre gratuite AI Empire : 100 crédits pour Groq + Gemini.\n\nSans carte bancaire. Sans engagement. Juste du code.\n\nMise en place en 5 minutes. SDKs pour JS et Python.',
      cta: 'Commencer gratuitement',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Étudiants, développeurs amateurs',
    },
    {
      id: 'tw-fr-10',
      tweet: 'Votre portfolio mérite mieux qu\'un template HTML basique.\n\nNeuraPortfolio : Next.js 14, animations Framer Motion, mode sombre, responsive. 29 €.\n\nFaites bonne impression.',
      cta: 'Voir le template portfolio',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Développeurs, designers, freelances',
    },
  ],
  instagram: [
    {
      id: 'ig-fr-01',
      name: 'Présentation de la plateforme — Reel',
      type: 'reel',
      script: 'Scène 1 : Enregistrement d\'écran du tableau de bord — texte superposé "Découvrez AI Empire". Scène 2 : Éditeur de code montrant un appel API — "Une API, plusieurs modèles". Scène 3 : Paiement Stripe — "Paiements en 5 minutes". Scène 4 : Déploiement en direct — "Déployé en 24 heures". Scène 5 : Logo + URL — "Commencez gratuitement aujourd\'hui".',
      visualDirection: 'Enregistrements d\'écran rythmés avec des transitions fluides. Interface en mode sombre. Couleurs de marque dégradé violet. Musique électronique entraînante en fond.',
      textOverlay: 'AI Empire — Créez votre SaaS plus vite',
      cta: 'Lien en bio — Commencer gratuitement',
      duration: '15-30 secondes',
    },
    {
      id: 'ig-fr-02',
      name: 'Présentation NeuraStore — Story',
      type: 'story',
      script: 'Parcours en balayage du template NeuraStore. Montrer la grille de produits, le flux du panier, le paiement Stripe, la vue responsive mobile. Terminer avec l\'étiquette de prix (29 €) et l\'appel à l\'action.',
      visualDirection: 'Fonds blancs/sombres épurés. Maquettes de produits sur iPhone et MacBook. Animations de balayage fluides. Accents violets de marque.',
      textOverlay: 'NeuraStore — 29 € — Template E-commerce',
      cta: 'Glisser pour voir',
      duration: '15 secondes',
    },
    {
      id: 'ig-fr-03',
      name: 'Démo API IA — Reel',
      type: 'reel',
      script: 'Scène 1 : Développeur en train de coder — "Ajoutez l\'IA à votre application". Scène 2 : Terminal montrant la réponse API — "Groq + Gemini en un seul appel". Scène 3 : Application fonctionnant avec des fonctionnalités IA — "Intégration en 5 minutes". Scène 4 : Écran des tarifs — "Gratuit pour commencer".',
      visualDirection: 'Plans de coding en surplomb mélangés à des enregistrements d\'écran. Thème sombre. Terminal vert sur noir. Montage rapide synchronisé sur la musique.',
      textOverlay: 'API IA — Offre gratuite disponible',
      cta: 'Obtenez votre clé API — Lien en bio',
      duration: '20-30 secondes',
    },
    {
      id: 'ig-fr-04',
      name: 'Bundle de templates — Story',
      type: 'story',
      script: 'Story en trois parties. Partie 1 : Les 6 templates affichés en grille — "6 templates. 299 €." Partie 2 : Mise en avant de chaque template — "NeuraStore, NeuraBlog, NeuraPortfolio..." Partie 3 : Appel des économies — "Économisez plus de 400 €" avec bouton d\'appel à l\'action.',
      visualDirection: 'Mise en page en grille de produits. Chaque template présenté sous forme de maquette d\'appareil. Fond dégradé violet. Typographie audacieuse.',
      textOverlay: 'Bundle complet — 299 € — Économisez plus de 400 €',
      cta: 'Obtenir le bundle',
      duration: '15 secondes par partie',
    },
    {
      id: 'ig-fr-05',
      name: 'Témoignage développeur — Reel',
      type: 'reel',
      script: 'Scène 1 : Self vidéo du développeur — "J\'ai lancé mon SaaS en 2 jours avec AI Empire". Scène 2 : Enregistrement d\'écran de l\'application déployée. Scène 3 : Extraits de code montrant l\'intégration. Scène 4 : Superposition de l\'appel à l\'action.',
      visualDirection: 'Style authentique UGC. Éclairage naturel. Caméra à la main. Sous-titres pour l\'accessibilité.',
      textOverlay: '"Lancé en 2 jours" — @développeur',
      cta: 'Commencer à développer — Lien en bio',
      duration: '30 secondes',
    },
    {
      id: 'ig-fr-06',
      name: 'Fonctionnalités NeuraBlog — Story',
      type: 'story',
      script: 'Parcours de NeuraBlog : éditeur MDX, basculement du mode sombre, vue mobile responsive, aperçu du flux RSS, section commentaires. Terminer avec le tarif (19 €) et l\'appel à l\'action.',
      visualDirection: 'Enregistrement d\'écran avec effets de zoom sur les fonctionnalités clés. Écran divisé montrant le mode clair/sombre. Esthétique épurée et minimale.',
      textOverlay: 'NeuraBlog — 19 € — Template blog SEO',
      cta: 'Glisser — Voir le template',
      duration: '15 secondes',
    },
    {
      id: 'ig-fr-07',
      name: 'Défi vitesse SaaS — Reel',
      type: 'reel',
      script: 'Timelapse de la création d\'un SaaS de zéro. Superposition du chronomètre de 0:00 à 4:00:00. Montrer la sélection du template, la configuration de l\'API, la config Stripe, le déploiement. Terminer avec l\'URL en direct.',
      visualDirection: 'Écran divisé : chronomètre à gauche, enregistrement d\'écran à droite. Effet accéléré. Musique de fond énergétique. Marqueurs d\'étapes à 1h, 2h, 3h.',
      textOverlay: 'SaaS créé en 4 heures',
      cta: 'Essayez AI Empire — Lien en bio',
      duration: '30-60 secondes',
    },
    {
      id: 'ig-fr-08',
      name: 'Annonce offre gratuite — Story',
      type: 'story',
      script: 'Révélation en typographie audacieuse : "GRATUIT" → "API IA" → "100 Crédits" → "Groq + Gemini" → "Sans carte bancaire" → Appel à l\'action. Chaque élément de texte apparaît avec un effet rebond ou glissement.',
      visualDirection: 'Fonds violets/sombres unis. Texte blanc gras et grand. Design minimaliste. Chaque partie transitionne avec une animation percutante.',
      textOverlay: 'API IA GRATUITE — 100 Crédits — Sans carte',
      cta: 'S\'inscrire gratuitement',
      duration: '10 secondes au total',
    },
    {
      id: 'ig-fr-09',
      name: 'Présentation NeuraPortfolio — Reel',
      type: 'reel',
      script: 'Mise en avant des animations de NeuraPortfolio : parallaxe de la section héro, effets de survol des cartes de projets, transitions de pages fluides, mode sombre. Le tout sur une maquette de MacBook.',
      visualDirection: 'Élégant, maquette d\'appareil en slow motion. Mouvements de caméra subtils. Éclairage doux. Musique de fond minimale. Focus sur la qualité des animations.',
      textOverlay: 'NeuraPortfolio — 29 € — Portfolio développeur',
      cta: 'Lien en bio — Voir la démo',
      duration: '20-30 secondes',
    },
    {
      id: 'ig-fr-10',
      name: 'Comparaison avant/après — Story',
      type: 'story',
      script: 'Partie 1 : "Tout construire soi-même : 3 à 6 mois" avec icône calendrier. Partie 2 : "Utiliser AI Empire : 1 à 2 jours" avec icône fusée. Partie 3 : "Même résultat. 95% de temps en moins." Partie 4 : Appel à l\'action avec tarifs.',
      visualDirection: 'Mise en page de comparaison côte à côte. Style avant/après. Rouge pour l\'option "lente", vert pour AI Empire. Typographie percutante.',
      textOverlay: '3 mois vs 2 jours — Choisissez la rapidité',
      cta: 'Commencer maintenant — Lien en bio',
      duration: '15 secondes par partie',
    },
  ],
};
