import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'it',
  googleSearch: [
    // === Campagna 1: Piattaforma API AI ===
    {
      id: 'g-it-01',
      name: 'Piattaforma API AI',
      objective: 'Generare iscrizioni al tier gratuito dell\'API AI',
      budget: '€500/mese',
      adGroups: [
        {
          id: 'g-it-01-brand',
          name: 'Brand',
          keywords: ['ai empire', 'ai-empire', 'api ai empire', 'piattaforma ai empire'],
          ads: [
            { id: 'g-it-01-brand-1', headline: 'AI Empire — Piattaforma API AI Unificata', description: 'Accedi a Groq e Gemini attraverso un\'unica API. Tier gratuito disponibile, senza carta di credito. Integrazione in 5 minuti.', cta: 'Prova Gratis' },
            { id: 'g-it-01-brand-2', headline: 'AI Empire — La Sua Gateway AI', description: 'Un\'API, più modelli AI. Groq + Gemini. Crediti gratuiti all\'iscrizione. SDK per JavaScript e Python inclusi.', cta: 'Ottieni Chiave API' },
            { id: 'g-it-01-brand-3', headline: 'AI Empire — Sviluppi con AI Oggi', description: 'API AI pronte per la produzione. Groq per la velocità, Gemini per la capacità. Tier gratuito, tariffe a consumo.', cta: 'Inizia a Costruire' },
          ],
        },
        {
          id: 'g-it-01-competitor',
          name: 'Competitor',
          keywords: ['alternativa a openai', 'alternativa groq api', 'api ai più economica', 'wrapper api gemini', 'confronto api ai'],
          ads: [
            { id: 'g-it-01-comp-1', headline: 'API AI Accessoriosa — Risparmio vs OpenAI', description: 'Stessa qualità AI a costo inferiore. Groq + Gemini unificati. Tier gratuito con 100 crediti. Passaggio in pochi minuti.', cta: 'Confronta Prezzi' },
            { id: 'g-it-01-comp-2', headline: 'Alternativa a OpenAI — AI Empire', description: 'Cerca un\'API AI economica? AI Empire combina Groq e Gemini in un unico endpoint. Gratis per iniziare.', cta: 'Vedi Piani' },
            { id: 'g-it-01-comp-3', headline: 'API AI — 70% Meno di OpenAI', description: 'Risultati qualità GPT con Groq e Gemini. API unificata. Tier gratuito. Nessun vincolo con il fornitore.', cta: 'Inizia Gratis' },
          ],
        },
        {
          id: 'g-it-01-generic',
          name: 'Generico',
          keywords: ['api ai', 'api intelligenza artificiale', 'api groq', 'api gemini', 'ai per sviluppatori', 'api ai gratuita'],
          ads: [
            { id: 'g-it-01-gen-1', headline: 'API AI per Sviluppatori — Tier Gratuito', description: 'Groq + Gemini attraverso un\'unica API. Crediti gratuiti all\'iscrizione. Documentazione, esempi e SDK inclusi.', cta: 'Leggi la Doc' },
            { id: 'g-it-01-gen-2', headline: 'Integra AI nella Tua App — Setup in 5 Min', description: 'Un\'API per Groq e Gemini. Tier gratuito disponibile. Fatturazione Stripe. Documentazione completa.', cta: 'Inizia' },
            { id: 'g-it-01-gen-3', headline: 'API AI — Groq e Gemini Combinate', description: 'Endpoint unificato per più modelli AI. Gratis per iniziare, paga a consumo. Pronto per la produzione.', cta: 'Esplora l\'API' },
          ],
        },
      ],
    },
    // === Campagna 2: Template SaaS Next.js ===
    {
      id: 'g-it-02',
      name: 'Template SaaS Next.js',
      objective: 'Generare vendite di template',
      budget: '€400/mese',
      adGroups: [
        {
          id: 'g-it-02-brand',
          name: 'Brand',
          keywords: ['template ai empire', 'saas ai empire', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-it-02-brand-1', headline: 'AI Empire — Template SaaS per Next.js 14', description: 'Template pronti per la produzione con integrazione AI. NeuraStore, NeuraBlog, NeuraPortfolio. Da €19.', cta: 'Vedi Template' },
            { id: 'g-it-02-brand-2', headline: 'NeuraStore e NeuraBlog di AI Empire', description: 'Template professionali per Next.js 14 con Stripe, autenticazione e AI integrati. Deploy in pochi minuti.', cta: 'Vedi Template' },
            { id: 'g-it-02-brand-3', headline: 'Template AI Empire — Lancia il Tuo SaaS', description: '6 template premium. Next.js 14, Tailwind, Stripe, API AI incluse. Da €19 a €299 nel bundle.', cta: 'Sfoglia Template' },
          ],
        },
        {
          id: 'g-it-02-competitor',
          name: 'Competitor',
          keywords: ['boilerplate saas', 'template next.js', 'template saas react', 'kit di avvio saas', 'template ecommerce nextjs'],
          ads: [
            { id: 'g-it-02-comp-1', headline: 'Template SaaS Next.js — AI Integrata', description: 'A differenza dei boilerplate generici, i template AI Empire includono API AI, Stripe e autenticazione. Pronti per il deploy.', cta: 'Confronta Template' },
            { id: 'g-it-02-comp-2', headline: 'Più di un Boilerplate SaaS', description: 'Template AI Empire: design professionale, integrazione AI, fatturazione Stripe. Non solo codice iniziale.', cta: 'Vedi la Differenza' },
            { id: 'g-it-02-comp-3', headline: 'Template Next.js 14 — Full Stack Pronto', description: 'Template con tutto incluso: UI, API, autenticazione, pagamenti, AI. Deploy oggi.', cta: 'Vedi Template' },
          ],
        },
        {
          id: 'g-it-02-generic',
          name: 'Generico',
          keywords: ['template saas', 'template nextjs 14', 'template react', 'landing page saas', 'template per saas', 'costruisci saas velocemente'],
          ads: [
            { id: 'g-it-02-gen-1', headline: 'Template SaaS — Lancia in Giorni, Non Mesi', description: 'Template Next.js 14 con autenticazione, Stripe, AI e pannello amministrativo. Da €19.', cta: 'Inizia' },
            { id: 'g-it-02-gen-2', headline: 'Costruisci un SaaS con Next.js 14', description: 'Template pronti per la produzione. Fatturazione Stripe, autenticazione, API AI, pannello admin inclusi.', cta: 'Esplora Template' },
            { id: 'g-it-02-gen-3', headline: 'Template E-Commerce e Blog Next.js 14', description: 'Template professionali con design moderno. Responsive, dark mode, ottimizzati per SEO. Da €19.', cta: 'Acquista Template' },
          ],
        },
      ],
    },
    // === Campagna 3: Integrazione AI ===
    {
      id: 'g-it-03',
      name: 'Integrazione AI',
      objective: 'Attrarre sviluppatori che necessitano di integrazione AI',
      budget: '€350/mese',
      adGroups: [
        {
          id: 'g-it-03-brand',
          name: 'Brand',
          keywords: ['integrazione ai empire', 'documentazione ai empire', 'sdk ai empire', 'documentazione api ai empire'],
          ads: [
            { id: 'g-it-03-brand-1', headline: 'AI Empire — Aggiungi AI a Qualsiasi App', description: 'API semplice per aggiungere funzionalità AI alla tua app. Groq + Gemini. SDK per JS e Python.', cta: 'Leggi la Doc' },
            { id: 'g-it-03-brand-2', headline: 'SDK AI Empire — AI in 5 Minuti', description: 'Installa, configura, deploy. Il nostro SDK rende l\'integrazione AI semplice. Tier gratuito disponibile.', cta: 'Vedi SDK' },
            { id: 'g-it-03-brand-3', headline: 'Documentazione API AI Empire — Inizia', description: 'Documentazione completa, esempi di codice e tutorial. Aggiungi AI alla tua app Next.js oggi.', cta: 'Leggi la Doc' },
          ],
        },
        {
          id: 'g-it-03-competitor',
          name: 'Competitor',
          keywords: ['servizio integrazione ai', 'integrare ai nell\'app', 'sdk ai', 'sdk groq', 'sdk gemini', 'wrapper api ai'],
          ads: [
            { id: 'g-it-03-comp-1', headline: 'Integrazione AI Più Semplice dello Sviluppo Custom', description: 'Smetti di mantenere più SDK AI. AI Empire: un\'API, più modelli. Tier gratuito.', cta: 'Semplifica Ora' },
            { id: 'g-it-03-comp-2', headline: 'Integrazione AI — Senza Configurazione Complessa', description: 'Una chiave API, un endpoint. Groq e Gemini pronti. Crediti gratuiti per i test. Documentazione inclusa.', cta: 'Prova Gratis' },
            { id: 'g-it-03-comp-3', headline: 'Sostituisci il Tuo Wrapper API AI', description: 'AI Empire fornisce un\'API unificata pronta per la produzione. Fatturazione, rate limiting e monitoraggio inclusi.', cta: 'Scopri Come' },
          ],
        },
        {
          id: 'g-it-03-generic',
          name: 'Generico',
          keywords: ['aggiungi ai all\'app', 'integra ai', 'api ai per web app', 'integrazione groq', 'integrazione gemini', 'api ai rest'],
          ads: [
            { id: 'g-it-03-gen-1', headline: 'Aggiungi AI alla Tua Web App — API REST Semplice', description: 'API REST per Groq e Gemini. Tier gratuito. Risposte JSON. Funziona con qualsiasi linguaggio.', cta: 'Inizia Gratis' },
            { id: 'g-it-03-gen-2', headline: 'Integrazione API AI — Facile per gli Sviluppatori', description: 'API ben documentata con SDK per JavaScript e Python. Tier gratuito. Paga a consumo.', cta: 'Vedi la Doc' },
            { id: 'g-it-03-gen-3', headline: 'API Groq + Gemini — Un Endpoint', description: 'API singola per più modelli AI. Crediti gratuiti. Fatturazione Stripe. Pronto per la produzione.', cta: 'Inizia' },
          ],
        },
      ],
    },
    // === Campagna 4: Kit di Avvio SaaS ===
    {
      id: 'g-it-04',
      name: 'Kit di Avvio SaaS',
      objective: 'Convertire fondatori di SaaS e hacker indie',
      budget: '€400/mese',
      adGroups: [
        {
          id: 'g-it-04-brand',
          name: 'Brand',
          keywords: ['avvio ai empire', 'kit saas ai empire', 'bundle ai empire', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-it-04-brand-1', headline: 'AI Empire — Kit Completo di Avvio SaaS', description: 'Next.js 14, Stripe, Autenticazione, API AI, pannello amministrativo. Tutto per lanciare il tuo SaaS. Da €19.', cta: 'Ottieni Kit' },
            { id: 'g-it-04-brand-2', headline: 'Lancia il Tuo SaaS con AI Empire', description: '6 template professionali. Fatturazione Stripe, autenticazione, API AI. Deploy in 24 ore.', cta: 'Vedi Template' },
            { id: 'g-it-04-brand-3', headline: 'Bundle AI Empire — Tutti i Template', description: '6 template + supporto prioritario + aggiornamenti gratuiti. Kit completo per SaaS a €299.', cta: 'Ottieni Bundle' },
          ],
        },
        {
          id: 'g-it-04-competitor',
          name: 'Competitor',
          keywords: ['kit avvio saas', 'boilerplate saas nextjs', 'toolkit hacker indie', 'template saas full stack', 'lancia saas velocemente'],
          ads: [
            { id: 'g-it-04-comp-1', headline: 'Kit Avvio SaaS — Più di un Boilerplate', description: 'AI Empire include API AI, pannello amministrativo e template reali. Non solo codice iniziale.', cta: 'Confronta Funzionalità' },
            { id: 'g-it-04-comp-2', headline: 'Lancia il Tuo SaaS in 24 Ore', description: 'Perché impiegare mesi a costruire da zero? Template AI Empire: deploy oggi,迭代 domani.', cta: 'Vedi Template' },
            { id: 'g-it-04-comp-3', headline: 'Toolkit SaaS per Hacker Indie', description: 'Tutto ciò di cui hai bisogno: template, API AI, Stripe, autenticazione. Da €19. Tier gratuito per l\'API.', cta: 'Inizia a Costruire' },
          ],
        },
        {
          id: 'g-it-04-generic',
          name: 'Generico',
          keywords: ['template saas', 'come costruire saas', 'template app saas', 'next.js saas', 'template saas stripe', 'saas mvp'],
          ads: [
            { id: 'g-it-04-gen-1', headline: 'Costruisci un MVP SaaS in Giorni', description: 'Template Next.js 14 con Stripe, autenticazione e AI. Da €19. Deploy su Vercel.', cta: 'Inizia' },
            { id: 'g-it-04-gen-2', headline: 'Template SaaS — Stripe e Autenticazione Inclusi', description: 'Template Next.js 14 pronti per la produzione. Pagamenti, autenticazione, API AI integrati.', cta: 'Esplora Template' },
            { id: 'g-it-04-gen-3', headline: 'Template SaaS Full Stack — Next.js 14', description: 'Stack moderno: Next.js 14, Tailwind, Stripe, AI. Template da €19.', cta: 'Vedi Template' },
          ],
        },
      ],
    },
    // === Campagna 5: Alternativa a OpenAI ===
    {
      id: 'g-it-05',
      name: 'Alternativa a OpenAI',
      objective: 'Catturare traffico di confronto con OpenAI',
      budget: '€300/mese',
      adGroups: [
        {
          id: 'g-it-05-brand',
          name: 'Brand',
          keywords: ['ai empire vs openai', 'alternativa ai empire', 'prezzi ai empire', 'più economico di openai'],
          ads: [
            { id: 'g-it-05-brand-1', headline: 'AI Empire vs OpenAI — Stessa Qualità, Costo Inferiore', description: 'Groq e Gemini tramite AI Empire. API unificata con tier gratuito. Risparmia fino al 70% rispetto a OpenAI.', cta: 'Confronta Prezzi' },
            { id: 'g-it-05-brand-2', headline: 'Perché Passare a AI Empire da OpenAI', description: 'Costo inferiore, più modelli, API unificata, tier gratuito. Passaggio in pochi minuti, senza modifiche al codice.', cta: 'Vedi Prezzi' },
            { id: 'g-it-05-brand-3', headline: 'AI Empire — API AI a Costo Accessorio', description: 'Groq + Gemini. 70% più economica di OpenAI per qualità simile. Crediti gratuiti all\'iscrizione.', cta: 'Inizia Gratis' },
          ],
        },
        {
          id: 'g-it-05-competitor',
          name: 'Competitor',
          keywords: ['alternativa api openai', 'api più economica di openai', 'alternativa prezzi openai', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-it-05-comp-1', headline: 'Alternativa Economica a OpenAI — Prova Gratis', description: 'AI Empire: API unificata Groq + Gemini. Tier gratuito, a consumo. 70% meno di OpenAI.', cta: 'Prova Gratis' },
            { id: 'g-it-05-comp-2', headline: 'API Groq e Gemini — Miglior Rapporto Qualità-Prezzo', description: 'Perché pagare di più? Groq per la velocità, Gemini per la capacità. Un\'API, costo inferiore. Tier gratuito.', cta: 'Vedi Piani' },
            { id: 'g-it-05-comp-3', headline: 'Passa da OpenAI — Risparmia il 70%', description: 'AI Empire fornisce Groq e Gemini attraverso un\'unica API. Stessa qualità, frazione del costo.', cta: 'Confronta Ora' },
          ],
        },
        {
          id: 'g-it-05-generic',
          name: 'Generico',
          keywords: ['prezzi api ai', 'costo api ai', 'prezzi groq', 'prezzi api gemini', 'confronto api ai', 'api ai più economica'],
          ads: [
            { id: 'g-it-05-gen-1', headline: 'API AI — Da Gratis a Consumo', description: 'Inizia gratis, scala a costo accessorio. Groq + Gemini. Nessun canone mensile. Paga solo per ciò che usi.', cta: 'Vedi Prezzi' },
            { id: 'g-it-05-gen-2', headline: 'API AI Accessoriosa — Groq + Gemini', description: 'Tier gratuito con 100 crediti. Poi a consumo. Nessun minimo, nessun vincolo.', cta: 'Inizia' },
            { id: 'g-it-05-gen-3', headline: 'Prezzi API AI — Trasparenti ed Equì', description: 'Nessun costo nascosto. Groq e Gemini attraverso un\'unica API. Tier gratuito. Fatturazione Stripe.', cta: 'Vedi Prezzi' },
          ],
        },
      ],
    },
    // === Campagna 6: Alternativa ai Template Vercel ===
    {
      id: 'g-it-06',
      name: 'Alternativa ai Template Vercel',
      objective: 'Catturare traffico di confronto template',
      budget: '€250/mese',
      adGroups: [
        {
          id: 'g-it-06-brand',
          name: 'Brand',
          keywords: ['ai empire vercel', 'deploy ai empire', 'ai empire next.js', 'hosting ai empire'],
          ads: [
            { id: 'g-it-06-brand-1', headline: 'Template AI Empire — Deploy su Vercel', description: 'Template Next.js 14 ottimizzati per Vercel. API AI, Stripe, autenticazione inclusi. Deploy in pochi minuti.', cta: 'Deploy Ora' },
            { id: 'g-it-06-brand-2', headline: 'Template SaaS Pronti per Vercel', description: 'Template AI Empire: costruiti per Vercel. Deploy con un clic. Integrazione AI, fatturazione, autenticazione.', cta: 'Vedi Template' },
            { id: 'g-it-06-brand-3', headline: 'Template Next.js 14 per Vercel', description: 'Template professionali. Deploy su Vercel in pochi minuti. API AI e fatturazione Stripe integrati.', cta: 'Ottieni Template' },
          ],
        },
        {
          id: 'g-it-06-competitor',
          name: 'Competitor',
          keywords: ['alternativa template vercel', 'template next.js', 'meglio dei template vercel', 'template saas vercel', 'template saas deploy'],
          ads: [
            { id: 'g-it-06-comp-1', headline: 'Template Oltre il Base — AI Empire', description: 'A differenza dei template base Vercel, AI Empire include API AI, Stripe, pannello amministrativo.', cta: 'Vedi Funzionalità' },
            { id: 'g-it-06-comp-2', headline: 'Template Next.js con AI e Stripe', description: 'AI Empire: non solo un template, un kit di avvio SaaS completo. API AI, fatturazione, autenticazione inclusi.', cta: 'Confronta' },
            { id: 'g-it-06-comp-3', headline: 'Template SaaS per Produzione — Next.js 14', description: 'Oltre i template demo. AI Empire: autenticazione reale, pagamenti reali, integrazione AI reale.', cta: 'Vedi Template' },
          ],
        },
        {
          id: 'g-it-06-generic',
          name: 'Generico',
          keywords: ['template deploy next.js', 'template deploy saas', 'vercel saas', 'deploy nextjs 14', 'template deploy saas', 'template deploy vercel'],
          ads: [
            { id: 'g-it-06-gen-1', headline: 'Deploy il Tuo SaaS su Vercel Oggi', description: 'Template Next.js 14. Deploy con un clic. AI, Stripe, autenticazione inclusi. Da €19.', cta: 'Inizia il Deploy' },
            { id: 'g-it-06-gen-2', headline: 'Template SaaS — Pronti per il Deploy', description: 'Template professionali Next.js 14. Deploy su Vercel in pochi minuti. Full stack incluso.', cta: 'Inizia' },
            { id: 'g-it-06-gen-3', headline: 'Next.js 14 SaaS — Deploy in Minuti', description: 'Template con tutto: autenticazione, pagamenti, AI, admin. Deploy su Vercel istantaneamente.', cta: 'Esplora Template' },
          ],
        },
      ],
    },
    // === Campagna 7: Template E-Commerce ===
    {
      id: 'g-it-07',
      name: 'Template E-Commerce — NeuraStore',
      objective: 'Generare vendite del template NeuraStore',
      budget: '€300/mese',
      adGroups: [
        {
          id: 'g-it-07-brand',
          name: 'Brand',
          keywords: ['neurastore', 'ecommerce ai empire', 'template neurastore', 'neurastore next.js'],
          ads: [
            { id: 'g-it-07-brand-1', headline: 'NeuraStore — Template E-Commerce con AI', description: 'Template e-commerce Next.js 14 con Stripe, carrello, pannello amministrativo. Raccomandazioni prodotto AI.', cta: 'Vedi NeuraStore' },
            { id: 'g-it-07-brand-2', headline: 'NeuraStore — Lancia il Tuo Negozio Online', description: 'Template e-commerce professionale. Pagamenti Stripe, gestione inventario, design responsive.', cta: 'Vedi Demo' },
            { id: 'g-it-07-brand-3', headline: 'NeuraStore di AI Empire — €29', description: 'Template e-commerce completo. Next.js 14, Stripe, Tailwind. Deploy in pochi minuti.', cta: 'Acquista NeuraStore' },
          ],
        },
        {
          id: 'g-it-07-competitor',
          name: 'Competitor',
          keywords: ['template ecommerce next.js', 'template negozio online', 'alternativa shopify template', 'template react ecommerce', 'template store nextjs'],
          ads: [
            { id: 'g-it-07-comp-1', headline: 'Template E-Commerce — Possiedi il Tuo Negozio', description: 'A differenza di Shopify, NeuraStore è tuo. Self-hosted, personalizzabile, con AI. €29.', cta: 'Ottieni NeuraStore' },
            { id: 'g-it-07-comp-2', headline: 'E-Commerce Next.js — Controllo Totale', description: 'NeuraStore: possiedi il tuo codice, i tuoi dati, il tuo negozio. Integrazione Stripe, pannello amministrativo.', cta: 'Vedi Template' },
            { id: 'g-it-07-comp-3', headline: 'Costruisci il Tuo Negozio Online', description: 'Template NeuraStore: Next.js 14, Stripe, design responsive, pannello admin. €29.', cta: 'Inizia a Costruire' },
          ],
        },
        {
          id: 'g-it-07-generic',
          name: 'Generico',
          keywords: ['template sito ecommerce', 'template negozio online', 'nextjs ecommerce', 'costruisci negozio online', 'template saas ecommerce', 'template store digitale'],
          ads: [
            { id: 'g-it-07-gen-1', headline: 'Template Sito E-Commerce — Next.js 14', description: 'Template negozio online professionale. Stripe, carrello, admin. Responsive, dark mode. €29.', cta: 'Acquista Template' },
            { id: 'g-it-07-gen-2', headline: 'Costruisci un Negozio Online con Next.js', description: 'NeuraStore: soluzione e-commerce completa. Pagamenti, inventario, raccomandazioni AI.', cta: 'Inizia' },
            { id: 'g-it-07-gen-3', headline: 'Template Negozio Online — Pronto al Lancio', description: 'Template e-commerce Next.js 14. Fatturazione Stripe, design responsive, ottimizzato SEO. €29.', cta: 'Deploy Ora' },
          ],
        },
      ],
    },
    // === Campagna 8: Template Blog ===
    {
      id: 'g-it-08',
      name: 'Template Blog — NeuraBlog',
      objective: 'Generare vendite del template NeuraBlog',
      budget: '€250/mese',
      adGroups: [
        {
          id: 'g-it-08-brand',
          name: 'Brand',
          keywords: ['neurablog', 'blog ai empire', 'template neurablog', 'neurablog next.js'],
          ads: [
            { id: 'g-it-08-brand-1', headline: 'NeuraBlog — Template Blog Ottimizzato SEO', description: 'Template blog Next.js 14 con MDX, dark mode, feed RSS. Integrazione newsletter integrata.', cta: 'Vedi NeuraBlog' },
            { id: 'g-it-08-brand-2', headline: 'NeuraBlog — Blog Professionale in Minuti', description: 'Template blog premium. Supporto MDX, ottimizzazione SEO, sistema di commenti. €19.', cta: 'Vedi Demo' },
            { id: 'g-it-08-brand-3', headline: 'NeuraBlog di AI Empire — €19', description: 'Template blog completo. Next.js 14, MDX, dark mode, RSS. Deploy su Vercel.', cta: 'Acquista NeuraBlog' },
          ],
        },
        {
          id: 'g-it-08-competitor',
          name: 'Competitor',
          keywords: ['template blog next.js', 'alternativa wordpress', 'alternativa ghost', 'template blog mdx', 'template blog react'],
          ads: [
            { id: 'g-it-08-comp-1', headline: 'Template Blog — Più Veloce di WordPress', description: 'NeuraBlog: velocità di un sito statico, funzionalità dinamiche. MDX, SEO, newsletter. €19.', cta: 'Prova NeuraBlog' },
            { id: 'g-it-08-comp-2', headline: 'Template Blog MDX — Next.js 14', description: 'A differenza di Ghost, NeuraBlog ti dà il controllo totale. Self-hosted, veloce, personalizzabile.', cta: 'Vedi Template' },
            { id: 'g-it-08-comp-3', headline: 'Il Tuo Blog, Il Tuo Codice — NeuraBlog', description: 'Possiedi la tua piattaforma di contenuti. NeuraBlog: Next.js 14, MDX, dark mode, RSS. €19.', cta: 'Ottieni NeuraBlog' },
          ],
        },
        {
          id: 'g-it-08-generic',
          name: 'Generico',
          keywords: ['template blog', 'template blog personale', 'nextjs blog', 'template blog tech', 'avvia un blog', 'template sito blog'],
          ads: [
            { id: 'g-it-08-gen-1', headline: 'Template Blog — Lancia il Tuo Blog Oggi', description: 'Template blog professionale. Ottimizzato SEO, dark mode, newsletter. Deploy in pochi minuti. €19.', cta: 'Inizia a Bloggare' },
            { id: 'g-it-08-gen-2', headline: 'Blog Next.js 14 — Veloce e Bellissimo', description: 'NeuraBlog: template blog moderno. MDX, dark mode, RSS, sistema di commenti. €19.', cta: 'Vedi Template' },
            { id: 'g-it-08-gen-3', headline: 'Avvia un Blog Professionale — €19', description: 'Template NeuraBlog. Ottimizzato SEO, responsive, dark mode. Deploy su Vercel.', cta: 'Inizia' },
          ],
        },
      ],
    },
    // === Campagna 9: Template Portfolio ===
    {
      id: 'g-it-09',
      name: 'Template Portfolio — NeuraPortfolio',
      objective: 'Generare vendite del template NeuraPortfolio',
      budget: '€200/mese',
      adGroups: [
        {
          id: 'g-it-09-brand',
          name: 'Brand',
          keywords: ['neuraportfolio', 'portfolio ai empire', 'template neuraportfolio', 'template portfolio sviluppatore'],
          ads: [
            { id: 'g-it-09-brand-1', headline: 'NeuraPortfolio — Template Portfolio Sviluppatore', description: 'Portfolio professionale con animazioni, dark mode, modulo di contatto. Next.js 14. €29.', cta: 'Vedi NeuraPortfolio' },
            { id: 'g-it-09-brand-2', headline: 'NeuraPortfolio — Emergi Online', description: 'Template portfolio straordinario. Animazioni Framer Motion, responsive, dark mode. €29.', cta: 'Vedi Demo' },
            { id: 'g-it-09-brand-3', headline: 'NeuraPortfolio di AI Empire — €29', description: 'Template portfolio completo. Next.js 14, animazioni, dark mode, modulo di contatto.', cta: 'Acquista NeuraPortfolio' },
          ],
        },
        {
          id: 'g-it-09-competitor',
          name: 'Competitor',
          keywords: ['template portfolio sviluppatore', 'template sito portfolio', 'miglior template portfolio', 'template portfolio creativo', 'portfolio freelancer'],
          ads: [
            { id: 'g-it-09-comp-1', headline: 'Template Portfolio — Fai una Bella Figura', description: 'NeuraPortfolio: animazioni bellissime, design responsive, dark mode. Meglio dei temi generici.', cta: 'Vedi Template' },
            { id: 'g-it-09-comp-2', headline: 'Il Tuo Portfolio Dovrebbe Emergere', description: 'NeuraPortfolio: animazioni Framer Motion, design moderno, personalizzazione completa. €29.', cta: 'Vedi NeuraPortfolio' },
            { id: 'g-it-09-comp-3', headline: 'Portfolio Sviluppatore — Next.js 14', description: 'Costruisci il tuo portfolio con NeuraPortfolio. Veloce, bellissimo, deployabile in pochi minuti.', cta: 'Inizia' },
          ],
        },
        {
          id: 'g-it-09-generic',
          name: 'Generico',
          keywords: ['sito portfolio', 'costruisci portfolio', 'portfolio online', 'template sito personale', 'template portfolio freelancer', 'portfolio showcase'],
          ads: [
            { id: 'g-it-09-gen-1', headline: 'Costruisci il Tuo Portfolio Online — €29', description: 'NeuraPortfolio: template professionale con animazioni. Deploy in pochi minuti.', cta: 'Inizia a Costruire' },
            { id: 'g-it-09-gen-2', headline: 'Template Sito Personale — Next.js 14', description: 'Template portfolio bellissimo. Dark mode, animazioni, responsive. Da €29.', cta: 'Vedi Template' },
            { id: 'g-it-09-gen-3', headline: 'Template Portfolio — Deploy Oggi', description: 'Portfolio professionale con design moderno. Framer Motion, dark mode. €29.', cta: 'Ottieni Portfolio' },
          ],
        },
      ],
    },
    // === Campagna 10: Costruttore SaaS AI ===
    {
      id: 'g-it-10',
      name: 'Costruttore SaaS AI',
      objective: 'Catturare intento di costruzione SaaS con AI',
      budget: '€350/mese',
      adGroups: [
        {
          id: 'g-it-10-brand',
          name: 'Brand',
          keywords: ['costruttore saas ai empire', 'costruisci saas con ai empire', 'lancia ai empire', 'piattaforma ai empire'],
          ads: [
            { id: 'g-it-10-brand-1', headline: 'AI Empire — Costruisci il Tuo SaaS AI', description: 'Template + API AI + Stripe + Autenticazione. Tutto per costruire e lanciare un SaaS potenziato dall\'AI.', cta: 'Inizia a Costruire' },
            { id: 'g-it-10-brand-2', headline: 'AI Empire — La Tua Piattaforma SaaS AI', description: 'Dall\'idea al lancio. Template, API AI, pagamenti, autenticazione. Deploy in 24 ore.', cta: 'Lancia Ora' },
            { id: 'g-it-10-brand-3', headline: 'AI Empire — Lancia il Tuo SaaS Più Velocemente', description: 'Template professionali con integrazione AI. Stripe, autenticazione, pannello amministrativo. Da €19.', cta: 'Inizia' },
          ],
        },
        {
          id: 'g-it-10-competitor',
          name: 'Competitor',
          keywords: ['costruisci saas ai', 'costruttore saas', 'template saas ai', 'piattaforma saas ai', 'costruisci saas con ai', 'costruttore prodotto ai'],
          ads: [
            { id: 'g-it-10-comp-1', headline: 'Costruisci un SaaS AI — Non da Zero', description: 'AI Empire: template professionali con API AI integrate. Risparmia mesi di sviluppo.', cta: 'Vedi Template' },
            { id: 'g-it-10-comp-2', headline: 'Costruttore SaaS AI — Lancia in Giorni', description: 'Template, API AI, Stripe, autenticazione. AI Empire: tutto ciò che serve per lanciare.', cta: 'Confronta Funzionalità' },
            { id: 'g-it-10-comp-3', headline: 'Il Tuo SaaS AI — Lancia Questa Settimana', description: 'Perché costruire da zero? Template AI Empire: deploy in 24 ore. Integrazione AI inclusa.', cta: 'Inizia Gratis' },
          ],
        },
        {
          id: 'g-it-10-generic',
          name: 'Generico',
          keywords: ['template saas', 'costruisci saas', 'app saas', 'piattaforma saas', 'template prodotto ai', 'idee saas', 'lancia saas'],
          ads: [
            { id: 'g-it-10-gen-1', headline: 'Costruisci un SaaS — Template, AI, Pagamenti', description: 'Template Next.js 14 con API AI, Stripe, autenticazione. Da €19. Deploy oggi.', cta: 'Inizia' },
            { id: 'g-it-10-gen-2', headline: 'Costruttore SaaS — Tutto Incluso', description: 'Template, integrazione AI, pagamenti, pannello amministrativo. Kit SaaS completo. Da €19.', cta: 'Esplora Template' },
            { id: 'g-it-10-gen-3', headline: 'Lancia la Tua Idea SaaS — Next.js 14', description: 'Template professionali con stack moderno. AI, Stripe, autenticazione. Deploy in minuti.', cta: 'Inizia a Costruire' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Consapevolezza (2)
    {
      id: 'fb-it-01',
      name: 'Consapevolezza Brand AI Empire',
      type: 'awareness',
      objective: 'Aumentare la consapevolezza del brand tra sviluppatori e fondatori di startup',
      audience: 'Sviluppatori, CTO, fondatori di startup, età 22-45, interessati a AI, SaaS, Next.js, sviluppo web',
      placements: ['Feed Facebook', 'Feed Instagram', 'Audience Network'],
      adCopy: 'Stai costruendo un SaaS? AI Empire ti offre template Next.js 14 con API AI integrate (Groq + Gemini), fatturazione Stripe e autenticazione — tutto a partire da €19. Unisciti a oltre 5.000 sviluppatori che hanno lanciato più velocemente.',
      cta: 'Scopri di Più',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-it-02',
      name: 'Proposta di Valore API AI',
      type: 'awareness',
      objective: 'Educare gli sviluppatori sull\'API AI unificata',
      audience: 'Sviluppatori software, ingegneri ML, appassionati di AI, età 22-40',
      placements: ['Feed Facebook', 'Stories Instagram', 'Reels'],
      adCopy: 'Un\'API per Groq e Gemini. AI Empire fornisce un endpoint unificato per più modelli AI — gratis per iniziare, paga a consumo. Smetti di gestire più SDK AI.',
      cta: 'Prova Gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Considerazione (3)
    {
      id: 'fb-it-03',
      name: 'Presentazione Prodotto NeuraStore',
      type: 'consideration',
      objective: 'Generare traffico alla pagina del template NeuraStore',
      audience: 'Sviluppatori e-commerce, costruttori di negozi online, utenti Shopify in cerca di alternative',
      placements: ['Feed Facebook', 'Feed Instagram', 'Marketplace'],
      adCopy: 'NeuraStore: template e-commerce completo costruito con Next.js 14. Pagamenti Stripe, gestione carrello, pannello amministrativo e raccomandazioni prodotto AI. €29 — possiedi il tuo negozio, possiedi il tuo codice.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-it-04',
      name: 'Offerta Bundle Template',
      type: 'consideration',
      objective: 'Generare interesse per il bundle completo di template',
      audience: 'Fondatori di SaaS, hacker indie, sviluppatori full stack',
      placements: ['Feed Facebook', 'Feed Instagram', 'Marketplace Facebook'],
      adCopy: 'Ottieni tutti e 6 i template AI Empire per €299. NeuraStore, NeuraBlog, NeuraPortfolio e altri 3. Supporto prioritario, aggiornamenti gratuiti, tutto incluso. Risparmia oltre €400 rispetto all\'acquisto singolo.',
      cta: 'Vedi Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-it-05',
      name: 'Tutorial Integrazione AI',
      type: 'consideration',
      objective: 'Coinvolgere gli sviluppatori con contenuti educativi',
      audience: 'Sviluppatori web, sviluppatori React, sviluppatori Node.js',
      placements: ['Feed Facebook', 'Reels Instagram', 'Stories'],
      adCopy: 'Aggiungi AI alla tua app Next.js in 5 minuti. L\'SDK di AI Empire rende l\'integrazione semplice — una chiave API, un endpoint. Tier gratuito con 100 crediti. Documentazione ed esempi inclusi.',
      cta: 'Leggi la Doc',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Conversione (3)
    {
      id: 'fb-it-06',
      name: 'Iscrizione API Gratuita',
      type: 'conversion',
      objective: 'Generare iscrizioni al tier gratuito',
      audience: 'Visitatori del sito, lettori di documentazione, lettori di blog, pubblici simili',
      placements: ['Feed Facebook', 'Feed Instagram', 'Audience Network'],
      adCopy: 'La tua API AI gratuita ti aspetta. Iscriviti a AI Empire e ottieni 100 crediti per Groq e Gemini. Nessuna carta di credito richiesta. Inizia a costruire con AI oggi.',
      cta: 'Iscriviti Gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-it-07',
      name: 'Conversione Acquisto Template',
      type: 'conversion',
      objective: 'Convertire i visitatori delle pagine template in acquirenti',
      audience: 'Visitatori pagine template, abbandoni carrello, utenti ad alto intento',
      placements: ['Feed Facebook', 'Feed Instagram', 'Messenger'],
      adCopy: 'Stai ancora pensandoci? NeuraBlog (€19) e NeuraStore (€29) sono pronti per il deploy. Stripe, autenticazione, integrazione AI inclusi. Garanzia di rimborso al 100%.',
      cta: 'Acquista Ora',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-it-08',
      name: 'Sconto Bundle a Tempo Limitato',
      type: 'conversion',
      objective: 'Generare acquisti di bundle con urgenza',
      audience: 'Iscritti alla newsletter, abbandoni carrello, utenti ad alto coinvolgimento',
      placements: ['Feed Facebook', 'Feed Instagram', 'Stories Instagram'],
      adCopy: 'Offerta limitata: ottieni il bundle completo di template AI Empire per €299 (risparmia oltre €400). Include tutti e 6 i template, supporto prioritario e aggiornamenti gratuiti. L\'offerta termina a breve.',
      cta: 'Ottieni Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Retargeting (2)
    {
      id: 'fb-it-09',
      name: 'Visitatore di Ritorno — Template',
      type: 'retargeting',
      objective: 'Riengaggiare i visitatori che hanno visualizzato i template senza acquistare',
      audience: 'Visitatori pagine template (7-30 giorni), non hanno completato l\'acquisto',
      placements: ['Feed Facebook', 'Feed Instagram', 'Audience Network'],
      adCopy: 'Stavi guardando i template AI Empire. NeuraBlog inizia a €19, NeuraStore a €29. Full stack, pronti per il deploy, con AI integrata. Torna e lancia il tuo SaaS.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-it-10',
      name: 'Visitatore di Ritorno — API',
      type: 'retargeting',
      objective: 'Riengaggiare i visitatori che hanno esplorato la documentazione API senza iscriversi',
      audience: 'Visitatori pagine documentazione (7-30 giorni), non hanno creato un account',
      placements: ['Feed Facebook', 'Stories Instagram', 'Reels'],
      adCopy: 'Hai esplorato la nostra documentazione API. Pronto a costruire? AI Empire ti offre crediti gratuiti per Groq e Gemini. Iscriviti in 30 secondi, senza carta di credito.',
      cta: 'Inizia Gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Contenuto Sponsorizzato (4)
    {
      id: 'li-it-01',
      name: 'Annuncio Lancio SaaS',
      type: 'sponsored_content',
      objective: 'Generare iscrizioni da decision-maker tecnologici',
      audience: 'CTO, tech lead, manager di ingegneria in startup e PMI',
      headline: 'Lancia il Tuo SaaS 10x Più Velocemente con AI Empire',
      body: 'AI Empire fornisce template Next.js 14 con API AI integrate (Groq + Gemini), fatturazione Stripe e autenticazione. Passa dall\'idea a un SaaS deployato in 24 ore, non in mesi.\n\nCosa è incluso:\n- 6 template pronti per la produzione (€19-€299)\n- API AI unificata con tier gratuito\n- Stripe + Autenticazione configurati\n- Pannello amministrativo\n\nUnisciti a oltre 5.000 sviluppatori che costruiscono con AI Empire.',
      cta: 'Inizia a Costruire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-it-02',
      name: 'API AI per l\'Enterprise',
      type: 'sponsored_content',
      objective: 'Raggiungere leader dell\'ingegneria che valutano soluzioni API AI',
      audience: 'Manager di ingegneria, VP Engineering, architetti in aziende mid-market e enterprise',
      headline: 'API AI Unificata — Groq + Gemini per il Tuo Team',
      body: 'Smetti di gestire molteplici relazioni con fornitori AI. AI Empire fornisce un\'API per Groq e Gemini — con fatturazione, rate limiting e monitoraggio integrati.\n\nPerché i team di ingegneria scelgono AI Empire:\n- Un endpoint per più modelli AI\n- SDK per JavaScript e Python\n- Tier gratuito per il prototipaggio\n- Scalabilità a consumo\n\nRiduci la complessità della tua integrazione AI.',
      cta: 'Esplora l\'API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-it-03',
      name: 'Successo dell\'Hacker Indie',
      type: 'sponsored_content',
      objective: 'Attrarre hacker indie e fondatori solitari',
      audience: 'Hacker indie, fondatori solitari, fondatori di startup bootstrappate',
      headline: 'Lancia il Tuo SaaS Questo Fine Settimana',
      body: 'Costruito per i fondatori solitari che vogliono muoversi velocemente.\n\nAI Empire ti offre:\n- Template Next.js 14 professionali\n- API AI pronte all\'uso\n- Fatturazione Stripe in 5 minuti\n- Nessuna codifica necessaria per il lancio\n\nTemplate da €19. Deploy su Vercel con un clic.\n\nSmetti di soprappensare. Inizia a lanciare.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-it-04',
      name: 'Confronto Costi',
      type: 'sponsored_content',
      objective: 'Attrarre team attenti ai costi che confrontano fornitori AI',
      audience: 'CTO, leader finanziari, acquisti in startup e PMI',
      headline: 'API AI — 70% Meno dei Concorrenti',
      body: 'AI Empire combina Groq e Gemini in un\'API. Paga solo per ciò che usi.\n\nConfronto:\n- OpenAI: €0.03/1K token (GPT-4)\n- AI Empire: ~€0.009/1K token (Groq Llama)\n\nTier gratuito incluso. Nessun vincolo con il fornitore. Passaggio in pochi minuti.\n\nOltre 5.000 sviluppatori stanno già risparmiando.',
      cta: 'Vedi Prezzi',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Messaggi Sponsorizzati (3)
    {
      id: 'li-it-05',
      name: 'Contatto Diretto — CTO',
      type: 'message_ads',
      objective: 'Contatto personalizzato con CTO di aziende target',
      audience: 'CTO di aziende con 10-200 dipendenti nel tech, SaaS ed e-commerce',
      headline: 'Una domanda sul tuo stack AI',
      body: 'Ciao {{first_name}},\n\nHo notato che {{company}} sta lavorando con l\'AI. Una domanda rapida: stai gestendo API AI di più fornitori?\n\nAI Empire fornisce un\'API unificata per Groq e Gemini — un endpoint, una fattura, una dashboard. Tier gratuito incluso.\n\nAvrebbe senso chiacchierare per 10 minuti? Sono a disposizione per mostrarti come funziona.',
      cta: 'Prenota una Chiacchierata',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-it-06',
      name: 'Contatto Diretto — Sviluppatori',
      type: 'message_ads',
      objective: 'Coinvolgere sviluppatori individuali con offerte personalizzate',
      audience: 'Sviluppatori full stack, sviluppatori React/Next.js in aziende tech',
      headline: 'Stai sviluppando con Next.js?',
      body: 'Ciao {{first_name}},\n\nHo visto che lavori con Next.js. Abbiamo costruito AI Empire specificamente per l\'ecosistema Next.js — template con API AI, Stripe e autenticazione pronti all\'uso.\n\nSe stai lavorando a un progetto personale o aiuti il tuo team a lanciare più velocemente, il nostro tier gratuito potrebbe esserti utile.\n\nSono felice di condividere un codice sconto se sei interessato.',
      cta: 'Ottieni Codice Sconto',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-it-07',
      name: 'Contatto Partnership',
      type: 'message_ads',
      objective: 'Esplorare opportunità di partnership con agenzie e consulenze',
      audience: 'Proprietari di agenzie, fondatori di consulenze, leader di trasformazione digitale',
      headline: 'Opportunità di partnership per {{company}}',
      body: 'Ciao {{first_name}},\n\nAI Empire aiuta i team a lanciare prodotti potenziati dall\'AI più velocemente. Stiamo costruendo un programma partner per agenzie e consulenze che raccomandano i nostri template e API ai clienti.\n\nVantaggi:\n- Revenue share sui referral\n- Supporto prioritario per i tuoi clienti\n- Opportunità di co-marketing\n\nVale la pena esplorare?',
      cta: 'Scopri le Partnership',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dinamico (3)
    {
      id: 'li-it-08',
      name: 'Dinamico — Targeting per Titolo Lavorativo',
      type: 'dynamic',
      objective: 'Targeting degli sviluppatori per titolo lavorativo con annunci personalizzati',
      audience: 'Utenti con titoli: CTO, VP Engineering, Tech Lead, Senior Developer',
      headline: 'AI Empire per {{job_title}} — Lancia Più Velocemente',
      body: 'AI Empire offre a {{company_name}} un percorso più rapido verso la produzione. Template Next.js 14 con API AI, Stripe e autenticazione. Tier gratuito per prototipare, scalabilità a consumo.',
      cta: 'Esplora AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-it-09',
      name: 'Dinamico — Dimensione Azienda',
      type: 'dynamic',
      objective: 'Personalizzare il messaggio in base alla dimensione aziendale',
      audience: 'Aziende con 1-50 dipendenti (startup) e 51-500 dipendenti (growth)',
      headline: '{{company_name}} — Template SaaS AI',
      body: 'Per team in crescita: AI Empire fornisce template Next.js 14 pronti per la produzione con integrazione AI. Deploy in giorni, non in mesi. Da €19.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-it-10',
      name: 'Dinamico — Targeting per Settore',
      type: 'dynamic',
      objective: 'Targeting di settori specifici con messaggi personalizzati',
      audience: 'E-commerce, SaaS e agenzie digitali',
      headline: 'Soluzioni AI per {{industry}}',
      body: 'I template AI Empire sono costruiti per {{industry}}. Next.js 14, Stripe, API AI e pannelli amministrativi. Da €19 a €299 nel bundle.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-it-01',
      tweet: 'Abbiamo costruito AI Empire per non doverlo fare tu.\n\nTemplate Next.js 14 + API Groq e Gemini + Stripe + Autenticazione — tutto in una piattaforma.\n\nGratis per iniziare. Deploy in pochi minuti.',
      cta: 'Prova Gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Sviluppatori, fondatori di startup',
    },
    {
      id: 'tw-it-02',
      tweet: 'Provocazione: costruire un SaaS non dovrebbe prendere 6 mesi.\n\nTemplate AI Empire: Next.js 14 professionali, API AI integrate, Stripe configurato.\n\nDall\'idea al deploy in 24 ore.',
      cta: 'Vedi Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Hacker indie, fondatori solitari',
    },
    {
      id: 'tw-it-03',
      tweet: 'Un\'API. Più modelli AI. Tier gratuito.\n\nAI Empire: Groq per la velocità, Gemini per la capacità. Endpoint unificato.\n\nSmetti di gestire 5 SDK AI diversi.',
      cta: 'Ottieni Chiave API',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'Sviluppatori AI, tech lead',
    },
    {
      id: 'tw-it-04',
      tweet: 'NeuraStore: template e-commerce completo per Next.js 14.\n\nPagamenti Stripe ✓ Carrello ✓ Pannello admin ✓ Raccomandazioni AI ✓\n\n€29. Deploy su Vercel in pochi minuti.',
      cta: 'Vedi NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'Sviluppatori e-commerce',
    },
    {
      id: 'tw-it-05',
      tweet: 'Abbiamo confrontato i prezzi di OpenAI e AI Empire:\n\nStessa qualità di risultati, costo inferiore del 70%.\n\nGroq + Gemini attraverso un\'API. Tier gratuito incluso. Nessun vincolo.',
      cta: 'Confronta Prezzi',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Sviluppatori attenti ai costi',
    },
    {
      id: 'tw-it-06',
      tweet: 'Ho appena deployato un SaaS in 4 ore con i template AI Empire.\n\nNext.js 14 + Stripe + Autenticazione + API AI. Tutto configurato. Basta aggiungere il tuo codice.',
      cta: 'Lancia Più Velocemente',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Sviluppatori, fondatori di startup',
    },
    {
      id: 'tw-it-07',
      tweet: 'Il bundle AI Empire: 6 template, €299.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + altri 3. Supporto prioritario. Aggiornamenti gratuiti.\n\nRisparmia oltre €400 rispetto all\'acquisto singolo.',
      cta: 'Ottieni Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'Fondatori di SaaS, sviluppatori',
    },
    {
      id: 'tw-it-08',
      tweet: 'Stanco di WordPress?\n\nNeuraBlog: template blog Next.js 14. MDX, dark mode, RSS, ottimizzato SEO. €19.\n\nVeloce. Moderno. Tuo.',
      cta: 'Vedi NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Blogger, creatori di contenuti',
    },
    {
      id: 'tw-it-09',
      tweet: 'Tier gratuito AI Empire: 100 crediti per Groq + Gemini.\n\nNessuna carta di credito. Nessun impegno. Costruisci.\n\nSetup in 5 minuti. SDK per JS e Python.',
      cta: 'Inizia Gratis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Studenti, sviluppatori hobbisti',
    },
    {
      id: 'tw-it-10',
      tweet: 'Il tuo portfolio merita qualcosa di meglio di un template HTML base.\n\nNeuraPortfolio: Next.js 14, animazioni Framer Motion, dark mode, responsive. €29.\n\nFai una bella impressione.',
      cta: 'Vedi Template Portfolio',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Sviluppatori, designer, freelancer',
    },
  ],
  instagram: [
    {
      id: 'ig-it-01',
      name: 'Panoramica Piattaforma Reel',
      type: 'reel',
      script: 'Scena 1: Registrazione schermo della dashboard — testo "Ecco AI Empire". Scena 2: Editor di codice con chiamata API — "Un\'API, più Modelli". Scena 3: Checkout Stripe — "Pagamenti in 5 Minuti". Scena 4: Deploy live — "Deployato in 24 Ore". Scena 5: Logo + URL — "Inizia Gratis Oggi".',
      visualDirection: 'Registrazioni schermo veloci con transizioni fluide. UI dark mode. Colori brand viola gradiente. Musica elettronica allegra.',
      textOverlay: 'AI Empire — Costruisci il Tuo SaaS Più Velocemente',
      cta: 'Link in Bio — Inizia Gratis',
      duration: '15-30 secondi',
    },
    {
      id: 'ig-it-02',
      name: 'Presentazione NeuraStore Story',
      type: 'story',
      script: 'Scorrimento del template NeuraStore. Mostra griglia prodotti, flusso carrello, checkout Stripe, vista responsive mobile. Conclusione con prezzo (€29) e CTA.',
      visualDirection: 'Sfondi bianchi/scuri puliti. Mockup prodotti su iPhone e MacBook. Animazioni di scorrimento fluide. Accenti viola del brand.',
      textOverlay: 'NeuraStore — €29 — Template E-Commerce',
      cta: 'Scorri per Visualizzare',
      duration: '15 secondi',
    },
    {
      id: 'ig-it-03',
      name: 'Demo API AI Reel',
      type: 'reel',
      script: 'Scena 1: Sviluppatore che scrive codice — "Aggiungi AI alla tua app". Scena 2: Terminale con risposta API — "Groq + Gemini in una chiamata". Scena 3: App funzionante con funzionalità AI — "Integrazione in 5 minuti". Scena 4: Schermata prezzi — "Gratis per iniziare".',
      visualDirection: 'Inquadrature di spalla con registrazione schermo. Tema scuro. Verde terminale su nero. Tagli rapidi sincronizzati con la musica.',
      textOverlay: 'API AI — Tier Gratuito Disponibile',
      cta: 'Ottieni la Tua Chiave API — Link in Bio',
      duration: '20-30 secondi',
    },
    {
      id: 'ig-it-04',
      name: 'Bundle Template Story',
      type: 'story',
      script: 'Story in tre fotogrammi. Fotogramma 1: Tutti e 6 i template in griglia — "6 Template. €299." Fotogramma 2: Evidenziazione singoli template — "NeuraStore, NeuraBlog, NeuraPortfolio..." Fotogramma 3: Chiamata al risparmio — "Risparmia Oltre €400" con pulsante CTA.',
      visualDirection: 'Layout griglia prodotti. Ogni template mostrato come mockup device. Sfondo gradiente viola. Tipografia audace.',
      textOverlay: 'Bundle Completo — €299 — Risparmia Oltre €400',
      cta: 'Ottieni il Bundle',
      duration: '15 secondi per fotogramma',
    },
    {
      id: 'ig-it-05',
      name: 'Testimonianza Sviluppatore Reel',
      type: 'reel',
      script: 'Scena 1: Selfie/video sviluppatore — "Ho lanciato il mio SaaS in 2 giorni con AI Empire". Scena 2: Registrazione schermo dell\'app deployata. Scena 3: Snippet di codice con integrazione. Scena 4: Overlay CTA.',
      visualDirection: 'Filmato autentico stile UGC. Luce naturale. Sensazione di camera handheld. Sottotitoli per accessibilità.',
      textOverlay: '"Lanciato in 2 Giorni" — @sviluppatore',
      cta: 'Inizia a Costruire — Link in Bio',
      duration: '30 secondi',
    },
    {
      id: 'ig-it-06',
      name: 'Funzionalità NeuraBlog Story',
      type: 'story',
      script: 'Panoramica di NeuraBlog: editor MDX, toggle dark mode, vista mobile responsive, anteprima feed RSS, sezione commenti. Conclusione con prezzo (€19) e CTA.',
      visualDirection: 'Registrazione schermo con effetti zoom sulle funzionalità chiave. Schermo diviso che mostra luce/scuro. Estetica pulita e minimale.',
      textOverlay: 'NeuraBlog — €19 — Template Blog SEO',
      cta: 'Scorri per Visualizzare — Template',
      duration: '15 secondi',
    },
    {
      id: 'ig-it-07',
      name: 'Sfida Velocità SaaS Reel',
      type: 'reel',
      script: 'Time-lapse della costruzione di un SaaS da zero. Overlay del timer da 0:00 a 4:00:00. Mostra selezione template, setup API, configurazione Stripe, deploy. Conclusione con URL live.',
      visualDirection: 'Schermo diviso: timer a sinistra, registrazione schermo a destra. Effetto avanti veloce. Musica di sottofondo energica. Marcatori traguardo a 1h, 2h, 3h.',
      textOverlay: 'SaaS Costruito in 4 Ore',
      cta: 'Prova AI Empire — Link in Bio',
      duration: '30-60 secondi',
    },
    {
      id: 'ig-it-08',
      name: 'Annuncio Tier Gratuito Story',
      type: 'story',
      script: 'Rivelazione tipografia audace: "GRATIS" → "API AI" → "100 Crediti" → "Groq + Gemini" → "Nessuna Carta di Credito" → CTA. Ogni elemento testuale appare con animazione rimbalzo o scorrimento.',
      visualDirection: 'Sfondi viola/scuri solidi. Testo bianco grande e audace. Design minimale. Ogni fotogramma transita con animazione incisiva.',
      textOverlay: 'API AI GRATIS — 100 Crediti — Nessuna Carta',
      cta: 'Iscriviti Gratis',
      duration: '10 secondi totali',
    },
    {
      id: 'ig-it-09',
      name: 'Presentazione NeuraPortfolio Reel',
      type: 'reel',
      script: 'Mostra le animazioni di NeuraPortfolio: parallax della sezione hero, effetti hover sulle card progetto, transizioni pagine fluide, dark mode. Tutto su un mockup MacBook.',
      visualDirection: 'Elegante, mockup device al rallentamento. Movimenti camera sottili. Illuminazione soffusa. Musica di sottofondo minimale. Focus sulla qualità delle animazioni.',
      textOverlay: 'NeuraPortfolio — €29 — Portfolio Sviluppatore',
      cta: 'Link in Bio — Vedi Demo',
      duration: '20-30 secondi',
    },
    {
      id: 'ig-it-10',
      name: 'Carosello Confronto Story',
      type: 'story',
      script: 'Fotogramma 1: "Costruire da zero: 3-6 mesi" con icona calendario. Fotogramma 2: "Usando AI Empire: 1-2 giorni" con icona razzo. Fotogramma 3: "Stesso risultato. 95% meno di tempo." Fotogramma 4: CTA con prezzi.',
      visualDirection: 'Layout confronto fianco a fianco. Prima/dopo. Rosso per l\'opzione "lenta", verde per AI Empire. Tipografia d\'impatto audace.',
      textOverlay: '3 Mesi vs 2 Giorni — Scegli la Velocità',
      cta: 'Inizia Ora — Link in Bio',
      duration: '15 secondi per fotogramma',
    },
  ],
};
