import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'ja',
  googleSearch: [
    // === キャンペーン 1: AI API プラットフォーム ===
    {
      id: 'g-ja-01',
      name: 'AI API プラットフォーム',
      objective: 'AI API 無料 tier の登録を促進する',
      budget: '月€500',
      adGroups: [
        {
          id: 'g-ja-01-brand',
          name: 'ブランド',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'ai empire プラットフォーム'],
          ads: [
            { id: 'g-ja-01-brand-1', headline: 'AI Empire — 統合 AI API プラットフォーム', description: '1つの API で Groq と Gemini にアクセスできます。無料 tier 利用可能、クレジットカード不要。5分で統合完了。', cta: '無料で試す' },
            { id: 'g-ja-02-brand-2', headline: 'AI Empire — あなたの AI API ゲートウェイ', description: '1つの API で複数の AI モデルにアクセス。Groq + Gemini。登録時に無料クレジット付与。JavaScript と Python の SDK 含む。', cta: 'API キーを取得' },
            { id: 'g-ja-03-brand-3', headline: 'AI Empire — 今日から AI で開発', description: '本番環境対応の AI API。Groq は速度、Gemini は能力を提供。無料 tier、従量課金制。', cta: '開発を始める' },
          ],
        },
        {
          id: 'g-ja-01-competitor',
          name: '競合比較',
          keywords: ['openai 代替', 'groq api 代替', '安い ai api', 'gemini api ラッパー', 'ai api 比較'],
          ads: [
            { id: 'g-ja-01-comp-1', headline: '手頃な AI API — OpenAI より節約', description: '同等の品質の AI を低コストで。Groq + Gemini を統合。100 クレジットの無料 tier。数分で切り替え可能。', cta: '料金を比較' },
            { id: 'g-ja-01-comp-2', headline: 'OpenAI の代替 — AI Empire', description: 'コスト効率の良い AI API をお探しですか？AI Empire は Groq と Gemini を1つのエンドポイントに統合。無料で始められます。', cta: 'プランを見る' },
            { id: 'g-ja-01-comp-3', headline: 'AI API — OpenAI より 70% 安い', description: 'Groq と Gemini で GPT 並みの品質を実現。統合 API。無料 tier。ベンダーロックインなし。', cta: '無料で始める' },
          ],
        },
        {
          id: 'g-ja-01-generic',
          name: '汎用',
          keywords: ['ai api', '人工知能 api', 'groq api', 'gemini api', '開発者向け ai', '無料 ai api'],
          ads: [
            { id: 'g-ja-01-gen-1', headline: '開発者向け AI API — 無料 tier', description: '1つの API で Groq と Gemini にアクセス。登録時に無料クレジット。ドキュメント、サンプル、SDK 含む。', cta: 'ドキュメントを読む' },
            { id: 'g-ja-01-gen-2', headline: 'アプリに AI を統合 — 5分でセットアップ', description: 'Groq と Gemini 用の1つの API。無料 tier 利用可能。Stripe 請求。充実したドキュメント。', cta: '始める' },
            { id: 'g-ja-01-gen-3', headline: 'AI API — Groq と Gemini を統合', description: '複数の AI モデルへの統合エンドポイント。無料で始め、使い分けて従量課金。本番環境対応。', cta: 'API を探索' },
          ],
        },
      ],
    },
    // === キャンペーン 2: Next.js SaaS テンプレート ===
    {
      id: 'g-ja-02',
      name: 'Next.js SaaS テンプレート',
      objective: 'テンプレートの販売を促進する',
      budget: '月€400',
      adGroups: [
        {
          id: 'g-ja-02-brand',
          name: 'ブランド',
          keywords: ['ai empire テンプレート', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-ja-02-brand-1', headline: 'AI Empire — Next.js 14 向け SaaS テンプレート', description: 'AI 統合済みの本番環境対応テンプレート。NeuraStore、NeuraBlog、NeuraPortfolio。€19 から。', cta: 'テンプレートを見る' },
            { id: 'g-ja-02-brand-2', headline: 'AI Empire の NeuraStore と NeuraBlog', description: 'Stripe、認証、AI を統合した Next.js 14 向けプロフェッショナルテンプレート。数分でデプロイ。', cta: 'テンプレートを見る' },
            { id: 'g-ja-02-brand-3', headline: 'AI Empire テンプレート — SaaS をローンチ', description: '6つのプレミアムテンプレート。Next.js 14、Tailwind、Stripe、AI API 含む。€19 から €299 バンドル。', cta: 'テンプレートを閲覧' },
          ],
        },
        {
          id: 'g-ja-02-competitor',
          name: '競合比較',
          keywords: ['saas ボイラープレート', 'next.js テンプレート', 'react saas テンプレート', 'saas スターターキット', 'nextjs ecommerce テンプレート'],
          ads: [
            { id: 'g-ja-02-comp-1', headline: 'Next.js SaaS テンプレート — AI 統合済み', description: '汎用的なボイラープレートとは異なり、AI Empire テンプレートには AI API、Stripe、認証が含まれます。デプロイ可能。', cta: 'テンプレートを比較' },
            { id: 'g-ja-02-comp-2', headline: 'SaaS ボイラープレートよりも優れたもの', description: 'AI Empire テンプレート：プロフェッショナルデザイン、AI 統合、Stripe 請求。単なるスターターコードではありません。', cta: '違いを見る' },
            { id: 'g-ja-02-comp-3', headline: 'Next.js 14 テンプレート — フルスタック対応', description: 'UI、API、認証、決済、AI を含むテンプレート。今日からデプロイ。', cta: 'テンプレートを見る' },
          ],
        },
        {
          id: 'g-ja-02-generic',
          name: '汎用',
          keywords: ['saas テンプレート', 'nextjs 14 テンプレート', 'react テンプレート', 'saas ランディングページ', 'saas 向けテンプレート', 'saas を素早く構築'],
          ads: [
            { id: 'g-ja-02-gen-1', headline: 'SaaS テンプレート — 数ヶ月ではなく数日でローンチ', description: '認証、Stripe、AI、管理画面を含む Next.js 14 テンプレート。€19 から。', cta: '始める' },
            { id: 'g-ja-02-gen-2', headline: 'Next.js 14 で SaaS を構築', description: '本番環境対応テンプレート。Stripe 請求、認証、AI API、管理パネル含む。', cta: 'テンプレートを探索' },
            { id: 'g-ja-02-gen-3', headline: 'Next.js 14 EC・ブログテンプレート', description: 'モダンデザインのプロフェッショナルテンプレート。レスポンシブ、ダークモード、SEO 最適化。€19 から。', cta: 'テンプレートを購入' },
          ],
        },
      ],
    },
    // === キャンペーン 3: AI 統合 ===
    {
      id: 'g-ja-03',
      name: 'AI 統合',
      objective: 'AI 統合を必要とする開発者を獲得する',
      budget: '月€350',
      adGroups: [
        {
          id: 'g-ja-03-brand',
          name: 'ブランド',
          keywords: ['ai empire 統合', 'ai empire ドキュメント', 'ai empire sdk', 'ai empire api ドキュメント'],
          ads: [
            { id: 'g-ja-03-brand-1', headline: 'AI Empire — あらゆるアプリに AI を追加', description: 'アプリに AI 機能を追加するシンプルな API。Groq + Gemini。JS と Python の SDK。', cta: 'ドキュメントを読む' },
            { id: 'g-ja-03-brand-2', headline: 'AI Empire SDK — 5分で AI を統合', description: 'インストール、設定、デプロイ。当社の SDK で AI 統合が簡単になります。無料 tier 利用可能。', cta: 'SDK を見る' },
            { id: 'g-ja-03-brand-3', headline: 'AI Empire API ドキュメント — 開発を始める', description: '充実したドキュメント、コードサンプル、チュートリアル。今日から Next.js アプリに AI を追加。', cta: 'ドキュメントを読む' },
          ],
        },
        {
          id: 'g-ja-03-competitor',
          name: '競合比較',
          keywords: ['ai 統合サービス', 'アプリに ai を組み込む', 'ai sdk', 'groq sdk', 'gemini sdk', 'ai api ラッパー'],
          ads: [
            { id: 'g-ja-03-comp-1', headline: 'カスタム開発よりも簡単な AI 統合', description: '複数の AI SDK の保守をやめましょう。AI Empire：1つの API で複数モデル。無料 tier。', cta: '今すぐシンプルに' },
            { id: 'g-ja-03-comp-2', headline: 'AI 統合 — 複雑な設定なし', description: '1つの API キー、1つのエンドポイント。Groq と Gemini 準備完了。テスト用の無料クレジット。ドキュメント付き。', cta: '無料で試す' },
            { id: 'g-ja-03-comp-3', headline: 'AI API ラッパーを置き換え', description: 'AI Empire は本番環境対応の統合 API を提供。請求、レート制限、監視が含まれます。', cta: '方法を見る' },
          ],
        },
        {
          id: 'g-ja-03-generic',
          name: '汎用',
          keywords: ['アプリに ai を追加', 'ai を統合', 'web アプリ向け ai api', 'groq 統合', 'gemini 統合', 'ai api rest'],
          ads: [
            { id: 'g-ja-03-gen-1', headline: 'Web アプリに AI を追加 — シンプルな REST API', description: 'Groq と Gemini 用の REST API。無料 tier。JSON レスポンス。あらゆる言語で動作。', cta: '無料で始める' },
            { id: 'g-ja-03-gen-2', headline: 'AI API 統合 — 開発者フレンドリー', description: 'JavaScript と Python の SDK を含む充実したドキュメント。無料 tier。従量課金。', cta: 'ドキュメントを見る' },
            { id: 'g-ja-03-gen-3', headline: 'Groq + Gemini API — 1つのエンドポイント', description: '複数の AI モデルへの単一 API。無料クレジット。Stripe 請求。本番環境対応。', cta: '始める' },
          ],
        },
      ],
    },
    // === キャンペーン 4: SaaS スターターキット ===
    {
      id: 'g-ja-04',
      name: 'SaaS スターターキット',
      objective: 'SaaS 創業者とインディーハッカーを獲得する',
      budget: '月€400',
      adGroups: [
        {
          id: 'g-ja-04-brand',
          name: 'ブランド',
          keywords: ['ai empire スターター', 'ai empire saas キット', 'ai empire バンドル', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-ja-04-brand-1', headline: 'AI Empire — 完全な SaaS スターターキット', description: 'Next.js 14、Stripe、認証、AI API、管理ダッシュボード。SaaS ローンチに必要なすべて。€19 から。', cta: 'キットを取得' },
            { id: 'g-ja-04-brand-2', headline: 'AI Empire で SaaS をローンチ', description: '6つのプロフェッショナルテンプレート。Stripe 請求、認証、AI API。24時間以内にデプロイ。', cta: 'テンプレートを見る' },
            { id: 'g-ja-04-brand-3', headline: 'AI Empire バンドル — 全テンプレート', description: '6テンプレート + 優先サポート + 無料更新。€299 で完全な SaaS スターターキット。', cta: 'バンドルを取得' },
          ],
        },
        {
          id: 'g-ja-04-competitor',
          name: '競合比較',
          keywords: ['saas スターターキット', 'saas ボイラープレート nextjs', 'インディーハッカー ツールキット', 'saas テンプレート フルスタック', 'saas を素早くローンチ'],
          ads: [
            { id: 'g-ja-04-comp-1', headline: 'SaaS スターターキット — ボイラープレート以上', description: 'AI Empire は AI API、管理ダッシュボード、本物のテンプレートを含みます。スターターコードだけではありません。', cta: '機能を比較' },
            { id: 'g-ja-04-comp-2', headline: '24時間で SaaS をローンチ', description: 'ゼロから構築するのに何ヶ月も費やす必要はありません。AI Empire テンプレート：今日デプロイ、明日改善。', cta: 'テンプレートを見る' },
            { id: 'g-ja-04-comp-3', headline: 'インディーハッカー向け SaaS ツールキット', description: 'テンプレート、AI API、Stripe、認証 — 必要なすべて。€19 から。API は無料 tier。', cta: '開発を始める' },
          ],
        },
        {
          id: 'g-ja-04-generic',
          name: '汎用',
          keywords: ['saas テンプレート', 'saas の作り方', 'saas アプリテンプレート', 'next.js saas', 'stripe saas テンプレート', 'saas mvp'],
          ads: [
            { id: 'g-ja-04-gen-1', headline: '数日で SaaS MVP を構築', description: 'Stripe、認証、AI を含む Next.js 14 テンプレート。€19 から。Vercel にデプロイ。', cta: '始める' },
            { id: 'g-ja-04-gen-2', headline: 'SaaS テンプレート — Stripe + 認証付き', description: '本番環境対応の Next.js 14 テンプレート。決済、認証、AI API 内蔵。', cta: 'テンプレートを探索' },
            { id: 'g-ja-04-gen-3', headline: 'フルスタック SaaS テンプレート — Next.js 14', description: 'モダンスタック：Next.js 14、Tailwind、Stripe、AI。€19 から。', cta: 'テンプレートを見る' },
          ],
        },
      ],
    },
    // === キャンペーン 5: OpenAI の代替 ===
    {
      id: 'g-ja-05',
      name: 'OpenAI の代替',
      objective: 'OpenAI 比較トラフィックを獲得する',
      budget: '月€300',
      adGroups: [
        {
          id: 'g-ja-05-brand',
          name: 'ブランド',
          keywords: ['ai empire vs openai', 'ai empire 代替', 'ai empire 料金', 'openai より安い'],
          ads: [
            { id: 'g-ja-05-brand-1', headline: 'AI Empire vs OpenAI — 同等の品質、低コスト', description: 'AI Empire 経由で Groq と Gemini にアクセス。無料 tier 付きの統合 API。OpenAI より最大 70% 節約。', cta: '料金を比較' },
            { id: 'g-ja-05-brand-2', headline: 'OpenAI から AI Empire に切り替える理由', description: '低コスト、複数モデル、統合 API、無料 tier。数分で切り替え可能、コード変更不要。', cta: '料金を見る' },
            { id: 'g-ja-05-brand-3', headline: 'AI Empire — コスパの良い AI API', description: 'Groq + Gemini。同等品質で OpenAI より 70% 低成本。登録時に無料クレジット。', cta: '無料で始める' },
          ],
        },
        {
          id: 'g-ja-05-competitor',
          name: '競合比較',
          keywords: ['openai 代替 api', 'openai より安い api', 'openai 料金 代替', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-ja-05-comp-1', headline: 'OpenAI の手頃な代替 — 無料で試す', description: 'AI Empire：Groq + Gemini の統合 API。無料 tier、従量課金。OpenAI より 70% 低成本。', cta: '無料で試す' },
            { id: 'g-ja-05-comp-2', headline: 'Groq + Gemini API — 最高のコストパフォーマンス', description: 'なぜもっと払う必要がある？Groq は速度、Gemini は能力。1つの API で低コスト。無料 tier。', cta: 'プランを見る' },
            { id: 'g-ja-05-comp-3', headline: 'OpenAI から切り替え — 70% 節約', description: 'AI Empire は1つの API で Groq と Gemini を提供。同等の品質、コストの一部。', cta: '今すぐ比較' },
          ],
        },
        {
          id: 'g-ja-05-generic',
          name: '汎用',
          keywords: ['ai api 料金', 'ai api コスト', 'groq 料金', 'gemini api 料金', 'ai api 比較', '最も安い ai api'],
          ads: [
            { id: 'g-ja-05-gen-1', headline: 'AI API — 無料から従量課金まで', description: '無料で始め、手頃にスケール。Groq + Gemini。月額費用なし。使った分だけ支払い。', cta: '料金を見る' },
            { id: 'g-ja-05-gen-2', headline: '手頃な AI API — Groq + Gemini', description: '100 クレジットの無料 tier。その後は従量課金。最低利用なし、ロックインなし。', cta: '始める' },
            { id: 'g-ja-05-gen-3', headline: 'AI API 料金 — 透明で公正', description: '隠れた費用なし。1つの API で Groq と Gemini。無料 tier。Stripe 請求。', cta: '料金を見る' },
          ],
        },
      ],
    },
    // === キャンペーン 6: Vercel テンプレートの代替 ===
    {
      id: 'g-ja-06',
      name: 'Vercel テンプレートの代替',
      objective: 'テンプレート比較トラフィックを獲得する',
      budget: '月€250',
      adGroups: [
        {
          id: 'g-ja-06-brand',
          name: 'ブランド',
          keywords: ['ai empire vercel', 'ai empire デプロイ', 'ai empire next.js', 'ai empire ホスティング'],
          ads: [
            { id: 'g-ja-06-brand-1', headline: 'AI Empire テンプレート — Vercel にデプロイ', description: 'Vercel 向けに最適化された Next.js 14 テンプレート。AI API、Stripe、認証付き。数分でデプロイ。', cta: '今すぐデプロイ' },
            { id: 'g-ja-06-brand-2', headline: 'Vercel 対応 SaaS テンプレート', description: 'AI Empire テンプレート：Vercel 向けに構築。ワンクリックデプロイ。AI 統合、請求、認証。', cta: 'テンプレートを見る' },
            { id: 'g-ja-06-brand-3', headline: 'Vercel 向け Next.js 14 テンプレート', description: 'プロフェッショナルテンプレート。数分で Vercel にデプロイ。AI API と Stripe 請求内蔵。', cta: 'テンプレートを取得' },
          ],
        },
        {
          id: 'g-ja-06-competitor',
          name: '競合比較',
          keywords: ['vercel テンプレート 代替', 'next.js テンプレート', 'vercel テンプレート より良い', 'saas テンプレート vercel', 'テンプレート saas デプロイ'],
          ads: [
            { id: 'g-ja-06-comp-1', headline: '基本を超えるテンプレート — AI Empire', description: '基本的な Vercel テンプレートとは異なり、AI Empire には AI API、Stripe、管理ダッシュボードが含まれます。', cta: '機能を見る' },
            { id: 'g-ja-06-comp-2', headline: 'AI と Stripe 付き Next.js テンプレート', description: 'AI Empire：テンプレートだけでなく、完全な SaaS スターターキット。AI API、請求、認証付き。', cta: '比較する' },
            { id: 'g-ja-06-comp-3', headline: '本番 SaaS テンプレート — Next.js 14', description: 'デモテンプレートを超えましょう。AI Empire：本物の認証、本物の決済、本物の AI 統合。', cta: 'テンプレートを見る' },
          ],
        },
        {
          id: 'g-ja-06-generic',
          name: '汎用',
          keywords: ['next.js デプロイ テンプレート', 'saas テンプレート デプロイ', 'vercel saas', 'nextjs 14 デプロイ', 'saas デプロイ テンプレート', 'テンプレート vercel デプロイ'],
          ads: [
            { id: 'g-ja-06-gen-1', headline: '今日から Vercel に SaaS をデプロイ', description: 'Next.js 14 テンプレート。ワンクリックデプロイ。AI、Stripe、認証付き。€19 から。', cta: 'デプロイを始める' },
            { id: 'g-ja-06-gen-2', headline: 'SaaS テンプレート — デプロイ準備完了', description: 'プロフェッショナル Next.js 14 テンプレート。数分で Vercel にデプロイ。フルスタック対応。', cta: '始める' },
            { id: 'g-ja-06-gen-3', headline: 'Next.js 14 SaaS — 数分でデプロイ', description: '認証、決済、AI、管理画面を含むテンプレート。すぐに Vercel にデプロイ。', cta: 'テンプレートを探索' },
          ],
        },
      ],
    },
    // === キャンペーン 7: EC テンプレート ===
    {
      id: 'g-ja-07',
      name: 'EC テンプレート — NeuraStore',
      objective: 'NeuraStore テンプレートの販売を促進する',
      budget: '月€300',
      adGroups: [
        {
          id: 'g-ja-07-brand',
          name: 'ブランド',
          keywords: ['neurastore', 'ai empire ecommerce', 'neurastore テンプレート', 'neurastore next.js'],
          ads: [
            { id: 'g-ja-07-brand-1', headline: 'NeuraStore — AI 搭載 EC テンプレート', description: 'Stripe、カート、管理ダッシュボード付きの Next.js 14 EC テンプレート。AI による商品レコメンド。', cta: 'NeuraStore を見る' },
            { id: 'g-ja-07-brand-2', headline: 'NeuraStore — オンラインストアをローンチ', description: 'プロフェッショナル EC テンプレート。Stripe 決済、在庫管理、レスポンシブデザイン。', cta: 'デモを見る' },
            { id: 'g-ja-07-brand-3', headline: 'AI Empire の NeuraStore — €29', description: '完全な EC テンプレート。Next.js 14、Stripe、Tailwind。数分でデプロイ。', cta: 'NeuraStore を購入' },
          ],
        },
        {
          id: 'g-ja-07-competitor',
          name: '競合比較',
          keywords: ['ecommerce テンプレート next.js', 'オンラインストア テンプレート', 'shopify 代替 テンプレート', 'react ecommerce テンプレート', 'nextjs ストア テンプレート'],
          ads: [
            { id: 'g-ja-07-comp-1', headline: 'EC テンプレート — 自分のストアを持とう', description: 'Shopify とは異なり、NeuraStore はあなたのものです。セルフホスト、カスタマイズ可能、AI 搭載。€29。', cta: 'NeuraStore を取得' },
            { id: 'g-ja-07-comp-2', headline: 'Next.js EC — 完全なコントロール', description: 'NeuraStore：コードもデータもストアもすべて yours。Stripe 統合、管理ダッシュボード。', cta: 'テンプレートを見る' },
            { id: 'g-ja-07-comp-3', headline: 'オンラインストアを構築', description: 'NeuraStore テンプレート：Next.js 14、Stripe、レスポンシブデザイン、管理パネル。€29。', cta: '開発を始める' },
          ],
        },
        {
          id: 'g-ja-07-generic',
          name: '汎用',
          keywords: ['ecommerce ウェブサイト テンプレート', 'オンラインショップ テンプレート', 'nextjs ecommerce', 'オンラインストアを構築', 'saas ecommerce テンプレート', 'デジタルストア テンプレート'],
          ads: [
            { id: 'g-ja-07-gen-1', headline: 'EC ウェブサイト テンプレート — Next.js 14', description: 'プロフェッショナルオンラインストア テンプレート。Stripe、カート、管理画面。レスポンシブ、ダークモード。€29。', cta: 'テンプレートを購入' },
            { id: 'g-ja-07-gen-2', headline: 'Next.js でオンラインストアを構築', description: 'NeuraStore：完全な EC ソリューション。決済、在庫管理、AI レコメンド。', cta: '始める' },
            { id: 'g-ja-07-gen-3', headline: 'オンラインストア テンプレート — ローンチ準備完了', description: 'Next.js 14 EC テンプレート。Stripe 請求、レスポンシブデザイン、SEO 最適化。€29。', cta: '今すぐデプロイ' },
          ],
        },
      ],
    },
    // === キャンペーン 8: ブログテンプレート ===
    {
      id: 'g-ja-08',
      name: 'ブログテンプレート — NeuraBlog',
      objective: 'NeuraBlog テンプレートの販売を促進する',
      budget: '月€250',
      adGroups: [
        {
          id: 'g-ja-08-brand',
          name: 'ブランド',
          keywords: ['neurablog', 'ai empire ブログ', 'neurablog テンプレート', 'neurablog next.js'],
          ads: [
            { id: 'g-ja-08-brand-1', headline: 'NeuraBlog — SEO 最適化ブログテンプレート', description: 'MDX、ダークモード、RSS フィード付きの Next.js 14 ブログテンプレート。ニュースレター統合内蔵。', cta: 'NeuraBlog を見る' },
            { id: 'g-ja-08-brand-2', headline: 'NeuraBlog — 数分でプロフェッショナルブログ', description: 'プレミアムブログテンプレート。MDX サポート、SEO 最適化、コメントシステム。€19。', cta: 'デモを見る' },
            { id: 'g-ja-08-brand-3', headline: 'AI Empire の NeuraBlog — €19', description: '完全なブログテンプレート。Next.js 14、MDX、ダークモード、RSS。Vercel にデプロイ。', cta: 'NeuraBlog を購入' },
          ],
        },
        {
          id: 'g-ja-08-competitor',
          name: '競合比較',
          keywords: ['ブログテンプレート next.js', 'wordpress 代替', 'ghost 代替', 'mdx ブログテンプレート', 'react ブログテンプレート'],
          ads: [
            { id: 'g-ja-08-comp-1', headline: 'ブログテンプレート — WordPress より高速', description: 'NeuraBlog：静的サイトの速度、動的機能。MDX、SEO、ニュースレター。€19。', cta: 'NeuraBlog を試す' },
            { id: 'g-ja-08-comp-2', headline: 'MDX ブログテンプレート — Next.js 14', description: 'Ghost とは異なり、NeuraBlog は完全なコントロールを提供。セルフホスト、高速、カスタマイズ可能。', cta: 'テンプレートを見る' },
            { id: 'g-ja-08-comp-3', headline: 'あなたのブログ、あなたのコード — NeuraBlog', description: 'コンテンツプラットフォームを的所有。NeuraBlog：Next.js 14、MDX、ダークモード、RSS。€19。', cta: 'NeuraBlog を取得' },
          ],
        },
        {
          id: 'g-ja-08-generic',
          name: '汎用',
          keywords: ['ブログテンプレート', '個人ブログ テンプレート', 'nextjs ブログ', 'テックブログ テンプレート', 'ブログを始める', 'ブログ ウェブサイト テンプレート'],
          ads: [
            { id: 'g-ja-08-gen-1', headline: 'ブログテンプレート — 今日からブログを開始', description: 'プロフェッショナルブログテンプレート。SEO 最適化、ダークモード、ニュースレター。数分でデプロイ。€19。', cta: 'ブログを始める' },
            { id: 'g-ja-08-gen-2', headline: 'Next.js 14 ブログ — 高速で美しい', description: 'NeuraBlog：モダンブログテンプレート。MDX、ダークモード、RSS、コメントシステム。€19。', cta: 'テンプレートを見る' },
            { id: 'g-ja-08-gen-3', headline: 'プロフェッショナルブログを始める — €19', description: 'NeuraBlog テンプレート。SEO 最適化、レスポンシブ、ダークモード。Vercel にデプロイ。', cta: '始める' },
          ],
        },
      ],
    },
    // === キャンペーン 9: ポートフォリオテンプレート ===
    {
      id: 'g-ja-09',
      name: 'ポートフォリオテンプレート — NeuraPortfolio',
      objective: 'NeuraPortfolio テンプレートの販売を促進する',
      budget: '月€200',
      adGroups: [
        {
          id: 'g-ja-09-brand',
          name: 'ブランド',
          keywords: ['neuraportfolio', 'ai empire ポートフォリオ', 'neuraportfolio テンプレート', '開発者 ポートフォリオ テンプレート'],
          ads: [
            { id: 'g-ja-09-brand-1', headline: 'NeuraPortfolio — 開発者向けポートフォリオテンプレート', description: 'アニメーション、ダークモード、お問い合わせフォーム付きのプロフェッショナルポートフォリオ。Next.js 14。€29。', cta: 'NeuraPortfolio を見る' },
            { id: 'g-ja-09-brand-2', headline: 'NeuraPortfolio — オンラインで差をつける', description: '素晴らしいポートフォリオテンプレート。Framer Motion アニメーション、レスポンシブ、ダークモード。€29。', cta: 'デモを見る' },
            { id: 'g-ja-09-brand-3', headline: 'AI Empire の NeuraPortfolio — €29', description: '完全なポートフォリオテンプレート。Next.js 14、アニメーション、ダークモード、お問い合わせフォーム。', cta: 'NeuraPortfolio を購入' },
          ],
        },
        {
          id: 'g-ja-09-competitor',
          name: '競合比較',
          keywords: ['開発者 ポートフォリオ テンプレート', 'ポートフォリオ ウェブサイト テンプレート', '最高の ポートフォリオ テンプレート', 'クリエイティブ ポートフォリオ テンプレート', 'フリーランス ポートフォリオ'],
          ads: [
            { id: 'g-ja-09-comp-1', headline: 'ポートフォリオテンプレート — 印象を残す', description: 'NeuraPortfolio：美しいアニメーション、レスポンシブデザイン、ダークモード。汎用テーマより優れています。', cta: 'テンプレートを見る' },
            { id: 'g-ja-09-comp-2', headline: 'あなたのポートフォリオは差をつけるべき', description: 'NeuraPortfolio：Framer Motion アニメーション、モダンデザイン、完全なカスタマイズ。€29。', cta: 'NeuraPortfolio を見る' },
            { id: 'g-ja-09-comp-3', headline: '開発者ポートフォリオ — Next.js 14', description: 'NeuraPortfolio でポートフォリオを構築。高速、美しい、数分でデプロイ可能。', cta: '始める' },
          ],
        },
        {
          id: 'g-ja-09-generic',
          name: '汎用',
          keywords: ['ポートフォリオ ウェブサイト', 'ポートフォリオを構築', 'オンライン ポートフォリオ', '個人サイト テンプレート', 'フリーランス ポートフォリオ テンプレート', 'ショーケース ポートフォリオ'],
          ads: [
            { id: 'g-ja-09-gen-1', headline: 'オンライン ポートフォリオを構築 — €29', description: 'NeuraPortfolio：アニメーション付きのプロフェッショナルテンプレート。数分でデプロイ。', cta: '開発を始める' },
            { id: 'g-ja-09-gen-2', headline: '個人サイト テンプレート — Next.js 14', description: '美しいポートフォリオテンプレート。ダークモード、アニメーション、レスポンシブ。€29 から。', cta: 'テンプレートを見る' },
            { id: 'g-ja-09-gen-3', headline: 'ポートフォリオテンプレート — 今日デプロイ', description: 'モダンデザインのプロフェッショナルポートフォリオ。Framer Motion、ダークモード。€29。', cta: 'ポートフォリオを取得' },
          ],
        },
      ],
    },
    // === キャンペーン 10: AI SaaS ビルダー ===
    {
      id: 'g-ja-10',
      name: 'AI SaaS ビルダー',
      objective: 'AI SaaS 構築の意図を獲得する',
      budget: '月€350',
      adGroups: [
        {
          id: 'g-ja-10-brand',
          name: 'ブランド',
          keywords: ['ai empire saas ビルダー', 'ai empire で saas を構築', 'ai empire ローンチ', 'ai empire プラットフォーム'],
          ads: [
            { id: 'g-ja-10-brand-1', headline: 'AI Empire — AI SaaS を構築', description: 'テンプレート + AI API + Stripe + 認証。AI 搭載 SaaS を構築・ローンチするすべて。', cta: '開発を始める' },
            { id: 'g-ja-10-brand-2', headline: 'AI Empire — あなたの AI SaaS プラットフォーム', description: 'アイデアからローンチまで。テンプレート、AI API、決済、認証。24時間以内にデプロイ。', cta: '今すぐローンチ' },
            { id: 'g-ja-10-brand-3', headline: 'AI Empire — SaaS をより速くローンチ', description: 'AI 統合済みのプロフェッショナルテンプレート。Stripe、認証、管理ダッシュボード。€19 から。', cta: '始める' },
          ],
        },
        {
          id: 'g-ja-10-competitor',
          name: '競合比較',
          keywords: ['ai saas を構築', 'saas ビルダー', 'ai saas テンプレート', 'saas ai プラットフォーム', 'ai で saas を構築', 'ai プロダクト ビルダー'],
          ads: [
            { id: 'g-ja-10-comp-1', headline: 'AI SaaS を構築 — ゼロからではなく', description: 'AI Empire：AI API 統合済みのプロフェッショナルテンプレート。開発期間を大幅に短縮。', cta: 'テンプレートを見る' },
            { id: 'g-ja-10-comp-2', headline: 'AI SaaS ビルダー — 数日でローンチ', description: 'テンプレート、AI API、Stripe、認証。AI Empire：ローンチに必要なすべて。', cta: '機能を比較' },
            { id: 'g-ja-10-comp-3', headline: 'あなたの AI SaaS — 今週ローンチ', description: 'ゼロから構築する必要は？AI Empire テンプレート：24時間でデプロイ。AI 統合済み。', cta: '無料で始める' },
          ],
        },
        {
          id: 'g-ja-10-generic',
          name: '汎用',
          keywords: ['saas テンプレート', 'saas を構築', 'saas アプリ', 'saas プラットフォーム', 'ai プロダクト テンプレート', 'saas アイデア', 'saas をローンチ'],
          ads: [
            { id: 'g-ja-10-gen-1', headline: 'SaaS を構築 — テンプレート、AI、決済', description: 'AI API、Stripe、認証付きの Next.js 14 テンプレート。€19 から。今日デプロイ。', cta: '始める' },
            { id: 'g-ja-10-gen-2', headline: 'SaaS ビルダー — すべて揃っている', description: 'テンプレート、AI 統合、決済、管理ダッシュボード。完全な SaaS ツールキット。€19 から。', cta: 'テンプレートを探索' },
            { id: 'g-ja-10-gen-3', headline: 'SaaS アイデアをローンチ — Next.js 14', description: 'モダンスタックのプロフェッショナルテンプレート。AI、Stripe、認証。数分でデプロイ。', cta: '開発を始める' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // 認知（2）
    {
      id: 'fb-ja-01',
      name: 'AI Empire ブランド認知',
      type: 'awareness',
      objective: '開発者とスタートアップ創業者の間でブランド認知度を高める',
      audience: '開発者、CTO、スタートアップ創業者、22〜45歳、AI、SaaS、Next.js、ウェブ開発に興味がある方',
      placements: ['Facebook フィード', 'Instagram フィード', 'Audience Network'],
      adCopy: 'SaaS を構築中ですか？AI Empire は Next.js 14 テンプレート、組み込み AI API（Groq + Gemini）、Stripe 請求、認証を提供します — €19 から。より速くローンチした 5,000 人以上の開発者に参加しましょう。',
      cta: '詳しく見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-ja-02',
      name: 'AI API の価値提案',
      type: 'awareness',
      objective: '開発者に統合 AI API を教える',
      audience: 'ソフトウェア開発者、ML エンジニア、AI 愛好家、22〜40歳',
      placements: ['Facebook フィード', 'Instagram ストーリーズ', 'リールズ'],
      adCopy: 'Groq と Gemini 用の1つの API。AI Empire は複数の AI モデルへの統合エンドポイントを提供 — 無料で始め、使った分だけ支払い。複数の AI SDK の管理から解放されます。',
      cta: '無料で試す',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // 検討（3）
    {
      id: 'fb-ja-03',
      name: 'NeuraStore 製品紹介',
      type: 'consideration',
      objective: 'NeuraStore テンプレートページへのトラフィックを促進',
      audience: 'EC 開発者、オンラインストア構築者、代替を探している Shopify ユーザー',
      placements: ['Facebook フィード', 'Instagram フィード', 'マーケットプレイス'],
      adCopy: 'NeuraStore：Next.js 14 で構築された完全な EC テンプレート。Stripe 決済、カート管理、管理ダッシュボード、AI 商品レコメンド。€29 — ストアもコードもすべて yours。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-ja-04',
      name: 'テンプレートバンドルオファー',
      type: 'consideration',
      objective: '全テンプレートバンドルへの関心を促進',
      audience: 'SaaS 創業者、インディーハッカー、フルスタック開発者',
      placements: ['Facebook フィード', 'Instagram フィード', 'Facebook マーケットプレイス'],
      adCopy: 'AI Empire の全6テンプレートを €299 で。NeuraStore、NeuraBlog、NeuraPortfolio 他3つ。優先サポート、無料更新、すべて込み。個別購入より €400 以上お得。',
      cta: 'バンドルを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-ja-05',
      name: 'AI 統合チュートリアル',
      type: 'consideration',
      objective: '教育コンテンツで開発者を関与させる',
      audience: 'ウェブ開発者、React 開発者、Node.js 開発者',
      placements: ['Facebook フィード', 'Instagram リールズ', 'ストーリーズ'],
      adCopy: '5分で Next.js アプリに AI を追加。AI Empire の SDK で統合はシンプル — 1つの API キー、1つのエンドポイント。100 クレジットの無料 tier。ドキュメントとサンプル付き。',
      cta: 'ドキュメントを読む',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // 転換（3）
    {
      id: 'fb-ja-06',
      name: '無料 API 登録',
      type: 'conversion',
      objective: '無料 tier の登録を促進',
      audience: 'ウェブサイト訪問者、ドキュメント読者、ブログ読者、類似オーディエンス',
      placements: ['Facebook フィード', 'Instagram フィード', 'Audience Network'],
      adCopy: '無料の AI API があなたを待っています。AI Empire に登録して Groq と Gemini の100クレジットを取得。クレジットカード不要。今日から AI で開発を始めましょう。',
      cta: '無料で登録',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-ja-07',
      name: 'テンプレート購入転換',
      type: 'conversion',
      objective: 'テンプレートページ訪問者を購入者に転換',
      audience: 'テンプレートページ訪問者、カート放棄者、高インテントユーザー',
      placements: ['Facebook フィード', 'Instagram フィード', 'Messenger'],
      adCopy: 'まだ迷っていますか？NeuraBlog（€19）と NeuraStore（€29）はデプロイ準備完了。Stripe、認証、AI 統合付き。100% 返金保証。',
      cta: '今すぐ購入',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-ja-08',
      name: '期間限定バンドル割引',
      type: 'conversion',
      objective: '緊急性でバンドル購入を促進',
      audience: 'メール購読者、カート放棄者、高エンゲージメントユーザー',
      placements: ['Facebook フィード', 'Instagram フィード', 'Instagram ストーリーズ'],
      adCopy: '期間限定：AI Empire の全テンプレートバンドルを €299 で（€400 以上お得）。全6テンプレート、優先サポート、無料更新込み。オファーはまもなく終了。',
      cta: 'バンドルを取得',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // リターゲティング（2）
    {
      id: 'fb-ja-09',
      name: '再訪問者 — テンプレート',
      type: 'retargeting',
      objective: 'テンプレートを閲覧したが購入しなかった訪問者を再エンゲージ',
      audience: 'テンプレートページ訪問者（7〜30日）、購入未完了',
      placements: ['Facebook フィード', 'Instagram フィード', 'Audience Network'],
      adCopy: 'AI Empire のテンプレートを見ていた您へ。NeuraBlog は €19 から、NeuraStore は €29 から。フルスタック、デプロイ対応、AI 統合済み。戻って SaaS をローンチしましょう。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-ja-10',
      name: '再訪問者 — API',
      type: 'retargeting',
      objective: 'API ドキュメントを閲覧したが登録しなかった訪問者を再エンゲージ',
      audience: 'ドキュメントページ訪問者（7〜30日）、アカウント未作成',
      placements: ['Facebook フィード', 'Instagram ストーリーズ', 'リールズ'],
      adCopy: 'API ドキュメントを探索していましたね。開発を始める準備はできましたか？AI Empire は Groq と Gemini の無料クレジットを提供。30秒で登録、クレジットカード不要。',
      cta: '無料で始める',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // スポンサードコンテンツ（4）
    {
      id: 'li-ja-01',
      name: 'SaaS ローンチ告知',
      type: 'sponsored_content',
      objective: 'テクノロジー意思決定者から登録を獲得',
      audience: 'CTO、テックリード、エンジニアリングマネージャー（スタートアップおよび中小企業）',
      headline: 'AI Empire で SaaS を10倍速くローンチ',
      body: 'AI Empire は AI API（Groq + Gemini）組み込み、Stripe 請求、認証を備えた Next.js 14 テンプレートを提供。アイデアからデプロイ済み SaaS まで24時間で — 数ヶ月ではなく。\n\n含まれるもの：\n- 6つの本番環境対応テンプレート（€19〜€299）\n- 無料 tier 付き統合 AI API\n- Stripe + 認証設定済み\n- 管理ダッシュボード\n\n5,000人以上の開発者が AI Empire で開発中。',
      cta: '開発を始める',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-ja-02',
      name: 'エンタープライズ向け AI API',
      type: 'sponsored_content',
      objective: 'AI API ソリューションを評価中のエンジニアリングリーチャーにアプローチ',
      audience: 'エンジニアリングマネージャー、VP Engineering、アーキテクト（ミドルマーケットおよびエンタープライズ企業）',
      headline: '統合 AI API — あなたのチームの Groq + Gemini',
      body: '複数の AI ベンダーとの管理をやめましょう。AI Empire は Groq と Gemini 用の1つの API を提供 — 請求、レート制限、監視が統合。\n\nエンジニアリングチームが AI Empire を選ぶ理由：\n- 複数の AI モデルへの1つのエンドポイント\n- JavaScript と Python の SDK\n- プロトタイプ用の無料 tier\n- 従量課金のスケーラビリティ\n\nAI 統合の複雑さを軽減します。',
      cta: 'API を探索',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-ja-03',
      name: 'インディーハッカーの成功',
      type: 'sponsored_content',
      objective: 'インディーハッカーと個人起業家を獲得',
      audience: 'インディーハッカー、個人起業家、ootstrap スタートアップ創業者',
      headline: '今週末に SaaS をローンチ',
      body: '素早く動く個人起業家のために構築。\n\nAI Empire が提供するもの：\n- プロフェッショナル Next.js 14 テンプレート\n- すぐに使える AI API\n- 5分で Stripe 請求設定\n- ローンチにコーディング不要\n\n€19 からテンプレート。ワンクリックで Vercel にデプロイ。\n\n考えすぎは禁止。ローンチを始めましょう。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-ja-04',
      name: 'コスト比較',
      type: 'sponsored_content',
      objective: 'AI プロバイダーを比較するコスト意識の高いチームにアピール',
      audience: 'CTO、財務リーダー、調達担当（スタートアップおよび中小企業）',
      headline: 'AI API — 競合より 70% 安い',
      body: 'AI Empire は Groq と Gemini を1つの API に統合。使った分だけ支払い。\n\n比較：\n- OpenAI：€0.03/1K トークン（GPT-4）\n- AI Empire：約€0.009/1K トークン（Groq Llama）\n\n無料 tier 含む。ベンダーロックインなし。数分で切り替え可能。\n\n5,000人以上の開発者がすでに節約中。',
      cta: '料金を見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // メッセージ広告（3）
    {
      id: 'li-ja-05',
      name: 'ダイレクトアウトリーチ — CTO',
      type: 'message_ads',
      objective: 'ターゲット企業の CTO へのパーソナライズされたアプローチ',
      audience: 'テック、SaaS、EC 分野の従業員10〜200人の企業の CTO',
      headline: 'AI スタックについて質問です',
      body: '{{first_name}} 様\n\n{{company}} が AI を活用されていることを見かけました。 quick question: 複数の AI ベンダー API を管理されていますか？\n\nAI Empire は Groq と Gemini 用の統合 API を提供 — 1つのエンドポイント、1つの請求書、1つのダッシュボード。無料 tier 含む。\n\n10分お時間いただけますでしょうか？詳しくご説明させていただきます。',
      cta: 'チャットを設定',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-ja-06',
      name: 'ダイレクトアウトリーチ — 開発者',
      type: 'message_ads',
      objective: 'パーソナライズされたオファーで個人開発者を関与させる',
      audience: 'テック企業のフルスタック開発者、React/Next.js 開発者',
      headline: 'Next.js で開発されていますか？',
      body: '{{first_name}} 様\n\nNext.js で開発されていることを見かけました。私たちは Next.js エコシステム専用に AI Empire を構築しました — AI API、Stripe、認証が組み込まれたテンプレート。\n\n個人プロジェクトに取り組んでいるか、チームのローンチをサポートされている場合、無料 tier がお役に立てるかもしれません。\n\n興味があれば、割引コードをお送りできます。',
      cta: '割引コードを取得',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-ja-07',
      name: 'パートナーシップアウトリーチ',
      type: 'message_ads',
      objective: 'エージェンシーやコンサルティング会社とのパートナーシップ機会を模索',
      audience: 'エージェンシー所有者、コンサルティング会社創業者、デジタルトランスフォーメーションリーダー',
      headline: '{{company}} へのパートナーシップオファー',
      body: '{{first_name}} 様\n\nAI Empire はチームが AI 搭載プロダクトをより速くローンチするのを支援。クライアントにテンプレートや API を推奨するエージェンシーやコンサルティング会社向けのパートナープログラムを構築中です。\n\n特典：\n- リファラルの収益分配\n- クライアントへの優先サポート\n- 共同マーケティングの機会\n\n探る価値はありますか？',
      cta: 'パートナーシップについて詳しく見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // ダイナミック（3）
    {
      id: 'li-ja-08',
      name: 'ダイナミック — 職種ターゲティング',
      type: 'dynamic',
      objective: '職種別にパーソナライズされた広告で開発者をターゲット',
      audience: '職種：CTO、VP Engineering、Tech Lead、Senior Developer のユーザー',
      headline: '{{job_title}} のための AI Empire — よ速くローンチ',
      body: 'AI Empire は {{company_name}} にプロダuction へのより速い道を提供。AI API、Stripe、認証付きの Next.js 14 テンプレート。プロトタイプ用の無料 tier、従量課金でスケール。',
      cta: 'AI Empire を探索',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-ja-09',
      name: 'ダイナミック — 企業規模',
      type: 'dynamic',
      objective: '企業規模に応じてメッセージをカスタマイズ',
      audience: '従業員1〜50人（スタートアップ）および51〜500人（成長企業）',
      headline: '{{company_name}} — AI SaaS テンプレート',
      body: '成長中のチームへ：AI Empire は AI 統合済みの本番環境対応 Next.js 14 テンプレートを提供。数ヶ月ではなく数日でデプロイ。€19 から。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-ja-10',
      name: 'ダイナミック — 業界ターゲティング',
      type: 'dynamic',
      objective: 'カスタマイズされたメッセージで特定の業界をターゲット',
      audience: 'EC、SaaS、デジタルエージェンシー',
      headline: '{{industry}} 向け AI ソリューション',
      body: 'AI Empire テンプレートは {{industry}} 向けに構築。Next.js 14、Stripe、AI API、管理ダッシュボード。€19 から €299 バンドル。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-ja-01',
      tweet: 'AI Empire はあなたが作らなくていいように構築しました。\n\nNext.js 14 テンプレート + Groq と Gemini API + Stripe + 認証 — すべて1つのプラットフォームで。\n\n無料で始められます。数分でデプロイ。',
      cta: '無料で試す',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: '開発者、スタートアップ創業者',
    },
    {
      id: 'tw-ja-02',
      tweet: 'SaaS を作るのは6ヶ月もかかるべきじゃない。\n\nAI Empire テンプレート：プロフェッショナル Next.js 14、AI API 統合、Stripe 設定済み。\n\nアイデアからデプロイまで24時間。',
      cta: 'テンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'インディーハッカー、個人起業家',
    },
    {
      id: 'tw-ja-03',
      tweet: '1つの API。複数の AI モデル。無料 tier。\n\nAI Empire：Groq は速度、Gemini は能力。統合エンドポイント。\n\n5つの異なる AI SDK の管理から解放されます。',
      cta: 'API キーを取得',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'AI 開発者、テックリード',
    },
    {
      id: 'tw-ja-04',
      tweet: 'NeuraStore：Next.js 14 向けの完全な EC テンプレート。\n\nStripe 決済 ✓ カート ✓ 管理ダッシュボード ✓ AI レコメンド ✓\n\n€29。数分で Vercel にデプロイ。',
      cta: 'NeuraStore を見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'EC 開発者',
    },
    {
      id: 'tw-ja-05',
      tweet: 'OpenAI と AI Empire の料金を比較：\n\n同等の品質、コスト70%減。\n\n1つの API で Groq と Gemini。無料 tier 含む。ベンダーロックインなし。',
      cta: '料金を比較',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'コスト意識の高い開発者',
    },
    {
      id: 'tw-ja-06',
      tweet: 'AI Empire テンプレートで4時間で SaaS をデプロイしました。\n\nNext.js 14 + Stripe + 認証 + AI API。すべて設定済み。あとはコードを追加するだけ。',
      cta: 'より速くローンチ',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: '開発者、スタートアップ創業者',
    },
    {
      id: 'tw-ja-07',
      tweet: 'AI Empire バンドル：6テンプレート、€299。\n\nNeuraStore、NeuraBlog、NeuraPortfolio + 他3つ。優先サポート。無料更新。\n\n個別購入より €400 以上お得。',
      cta: 'バンドルを取得',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'SaaS 創業者、開発者',
    },
    {
      id: 'tw-ja-08',
      tweet: 'WordPress に飽きましたか？\n\nNeuraBlog：Next.js 14 ブログテンプレート。MDX、ダークモード、RSS、SEO 最適化。€19。\n\n高速。モダン。あなたのもの。',
      cta: 'NeuraBlog を見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'ブロガー、コンテンツクリエイター',
    },
    {
      id: 'tw-ja-09',
      tweet: 'AI Empire 無料 tier：Groq + Gemini で100クレジット。\n\nクレジットカード不要。コミットメントなし。開発するだけ。\n\n5分でセットアップ。JS と Python の SDK。',
      cta: '無料で始める',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: '学生、ホビー開発者',
    },
    {
      id: 'tw-ja-10',
      tweet: 'あなたのポートフォリオは基本的な HTML テンプレート以上の価値があります。\n\nNeuraPortfolio：Next.js 14、Framer Motion アニメーション、ダークモード、レスポンシブ。€29。\n\n印象を残しましょう。',
      cta: 'ポートフォリオテンプレートを見る',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: '開発者、デザイナー、フリーランス',
    },
  ],
  instagram: [
    {
      id: 'ig-ja-01',
      name: 'プラットフォーム概要リール',
      type: 'reel',
      script: 'シーン1：ダッシュボードの画面録画 — "AI Empire をご紹介" テキストオーバーレイ。シーン2：コードエディタで API コール — "1つの API、複数モデル"。シーン3：Stripe チェックアウト — "5分で決済"。シーン4：ライブデプロイ — "24時間でデプロイ完了"。シーン5：ロゴ + URL — "今日から無料で始めよう"。',
      visualDirection: 'スムーズなトランジションの高速画面録画。ダークモード UI。ブランドの紫色グラデーション。アップビートなエレクトロニック BGM。',
      textOverlay: 'AI Empire — SaaS をより速く構築',
      cta: 'プロフィールリンク — 無料で試す',
      duration: '15〜30秒',
    },
    {
      id: 'ig-ja-02',
      name: 'NeuraStore ショーケースストーリー',
      type: 'story',
      script: 'NeuraStore テンプレートをスワイプで紹介。商品グリッド、カートフロー、Stripe チェックアウト、モバイルレスポンシブビューを表示。価格タグ（€29）と CTA で締め。',
      visualDirection: 'クリーンな白/暗い背景。iPhone と MacBook の商品モックアップ。スムーズなスワイプアニメーション。ブランドの紫色アクセント。',
      textOverlay: 'NeuraStore — €29 — EC テンプレート',
      cta: 'スワイプして表示',
      duration: '15秒',
    },
    {
      id: 'ig-ja-03',
      name: 'AI API デモリール',
      type: 'reel',
      script: 'シーン1：開発者がコードを入力 — "アプリに AI を追加"。シーン2：ターミナルで API レスポンス — "1回の呼び出しで Groq + Gemini"。シーン3：AI 機能付きアプリの実行 — "5分で統合完了"。シーン4：料金画面 — "無料で始められます"。',
      visualDirection: '肩越しのコーディングショットと画面録画のミックス。ダークテーマ。ターミナルの緑色 on ブラック。音楽に同期した速いカット。',
      textOverlay: 'AI API — 無料 tier 利用可能',
      cta: 'API キーを取得 — プロフィールリンク',
      duration: '20〜30秒',
    },
    {
      id: 'ig-ja-04',
      name: 'テンプレートバンドルストーリー',
      type: 'story',
      script: '3フレームのストーリー。フレーム1：全6テンプレートをグリッド表示 — "6テンプレート。€299。" フレーム2：個別テンプレートのハイライト — "NeuraStore、NeuraBlog、NeuraPortfolio..." フレーム3：お得情報 — "€400 以上お得" と CTA ボタン。',
      visualDirection: '商品グリッドレイアウト。各テンプレートをデバイスモックアップで表示。紫色グラデーション背景。大胆なタイポグラフィ。',
      textOverlay: 'フルバンドル — €299 — €400 以上お得',
      cta: 'バンドルを取得',
      duration: '1フレーム15秒',
    },
    {
      id: 'ig-ja-05',
      name: '開発者テスティモニアルリール',
      type: 'reel',
      script: 'シーン1：開発者のセルフィー/動画 — "AI Empire で2日で SaaS をローンチしました"。シーン2：デプロイ済みアプリの画面録画。シーン3：統合を示すコードスニペット。シーン4：CTA オーバーレイ。',
      visualDirection: '本物の UGC スタイルの映像。自然光。手持ちカメラ風感。アクセシビリティのための字幕付き。',
      textOverlay: '"2日でローンチ" — @developer',
      cta: '開発を始める — プロフィールリンク',
      duration: '30秒',
    },
    {
      id: 'ig-ja-06',
      name: 'NeuraBlog 機能ストーリー',
      type: 'story',
      script: 'NeuraBlog の walkthrough：MDX エディタ、ダークモード切り替え、レスポンシブモバイルビュー、RSS フィードプレビュー、コメントセクション。価格（€19）と CTA で締め。',
      visualDirection: '主要機能にズーム効果のある画面録画。ライト/ダークモードを並べて表示。クリーンでミニマルな美学。',
      textOverlay: 'NeuraBlog — €19 — SEO ブログテンプレート',
      cta: 'スワイプして表示 — テンプレート',
      duration: '15秒',
    },
    {
      id: 'ig-ja-07',
      name: 'SaaS スピードチャレンジリール',
      type: 'reel',
      script: 'ゼロから SaaS を構築するタイムラプス。0:00 から 4:00:00 までのタイマーオーバーレイ。テンプレート選択、API セットアップ、Stripe 設定、デプロイを表示。ライブ URL で締め。',
      visualDirection: '分割画面：左にタイマー、右に画面録画。早送り効果。エネルギッシュな BGM。1h、2h、3h にマイルストーンマーカー。',
      textOverlay: '4時間で SaaS を構築',
      cta: 'AI Empire を試す — プロフィールリンク',
      duration: '30〜60秒',
    },
    {
      id: 'ig-ja-08',
      name: '無料 tier アナウンスストーリー',
      type: 'story',
      script: '大胆なタイポグラフィで次々と表示："無料" → "AI API" → "100 クレジット" → "Groq + Gemini" → "クレジットカード不要" → CTA。各テキスト要素がバウンドまたはスライドアニメーションで表示。',
      visualDirection: '固体の紫/暗い背景。大きく太い白文字。ミニマルデザイン。各フレームが力強いアニメーションでトランジション。',
      textOverlay: '無料 AI API — 100 クレジット — カード不要',
      cta: '無料で登録',
      duration: '合計10秒',
    },
    {
      id: 'ig-ja-09',
      name: 'NeuraPortfolio ショーケースリール',
      type: 'reel',
      script: 'NeuraPortfolio のアニメーションをショーケース：ヒーローセクションのパララックス、プロジェクトカードのホバーエフェクト、スムーズなページトランジション、ダークモード。すべて MacBook モックアップで表示。',
      visualDirection: 'エレガント、スローモーションのデバイスモックアップ。繊細なカメラワーク。柔らかい照明。ミニマルな BGM。アニメーションの品質に注目。',
      textOverlay: 'NeuraPortfolio — €29 — 開発者ポートフォリオ',
      cta: 'プロフィールリンク — デモを見る',
      duration: '20〜30秒',
    },
    {
      id: 'ig-ja-10',
      name: '比較カローセルストーリー',
      type: 'story',
      script: 'フレーム1："ゼロから構築：3〜6ヶ月" カレンダーアイコン付き。フレーム2："AI Empire を使う：1〜2日" ロケットアイコン付き。フレーム3："同じ結果。95% の時間短縮。" フレーム4：料金付き CTA。',
      visualDirection: 'サイドバイサイド比較レイアウト。ビフォーアフター風。「遅い」オプションは赤、AI Empire は緑。インパクトのある大胆なタイポグラフィ。',
      textOverlay: '3ヶ月 vs 2日 — 速さを選ぶ',
      cta: '今すぐ始める — プロフィールリンク',
      duration: '1フレーム15秒',
    },
  ],
};
