import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'ko',
  googleSearch: [
    {
      id: 'g-ko-01',
      name: 'AI API 플랫폼',
      objective: 'AI API 무료 티어 가입 유도',
      budget: '€500/월',
      adGroups: [
        {
          id: 'g-ko-01-brand',
          name: '브랜드',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'ai empire 플랫폼'],
          ads: [
            { id: 'g-ko-01-brand-1', headline: 'AI Empire — 통합 AI API 플랫폼', description: 'Groq와 Gemini를 하나의 API로 이용하세요. 무료 티어 제공, 신용카드 불필요. 5분 만에 통합 가능합니다.', cta: '무료 체험' },
            { id: 'g-ko-01-brand-2', headline: 'AI Empire — 나만의 AI API 게이트웨이', description: '하나의 API, 다양한 AI 모델. Groq + Gemini. 가입 시 무료 크레딧 제공. JavaScript 및 Python SDK 포함.', cta: 'API 키 발급' },
            { id: 'g-ko-01-brand-3', headline: 'AI Empire — 지금 바로 AI를 빌드하세요', description: '프로덕션 준비 완료 AI API. Groq는 속도, Gemini는 성능. 무료 티어, 종량제 과금 방식.', cta: '시작하기' },
          ],
        },
        {
          id: 'g-ko-01-competitor',
          name: '경쟁사',
          keywords: ['openai 대안', 'groq api 대안', '저렴한 ai api', 'gemini api 래퍼', 'ai api 비교'],
          ads: [
            { id: 'g-ko-01-comp-1', headline: '합리적인 AI API — OpenAI 대비 비용 절감', description: '동일한 품질의 AI를 더 저렴하게 이용하세요. Groq + Gemini 통합. 무료 티어 100 크레딧 제공. 몇 분 안에 전환 가능.', cta: '가격 비교' },
            { id: 'g-ko-01-comp-2', headline: 'OpenAI 대안 — AI Empire', description: '비용 효율적인 AI API를 찾고 계신가요? AI Empire는 Groq와 Gemini를 하나의 엔드포인트에서 제공합니다. 무료로 시작하세요.', cta: '요금제 보기' },
            { id: 'g-ko-01-comp-3', headline: 'AI API — OpenAI 대비 70% 저렴', description: 'Groq와 Gemini로 GPT급 결과를 받아보세요. 통합 API. 무료 티어. 벤더 종속 없음.', cta: '무료 시작' },
          ],
        },
        {
          id: 'g-ko-01-generic',
          name: '일반',
          keywords: ['ai api', '인공지능 api', 'groq api', 'gemini api', '개발자를 위한 ai', '무료 ai api'],
          ads: [
            { id: 'g-ko-01-gen-1', headline: '개발자를 위한 AI API — 무료 티어', description: '하나의 API로 Groq + Gemini 이용. 가입 시 무료 크레딧. 문서, 예제, SDK 모두 포함.', cta: '문서 보기' },
            { id: 'g-ko-01-gen-2', headline: '앱에 AI 통합 — 5분 설정', description: 'Groq와 Gemini를 위한 하나의 API. 무료 티어 제공. Stripe 과금. 전체 문서화.', cta: '시작하기' },
            { id: 'g-ko-01-gen-3', headline: 'AI API — Groq & Gemini 결합', description: '여러 AI 모델을 위한 통합 엔드포인트. 무료 시작, 사용량 기반 과금. 프로덕션 준비 완료.', cta: 'API 탐색' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-02',
      name: 'Next.js SaaS 템플릿',
      objective: '템플릿 판매 촉진',
      budget: '€400/월',
      adGroups: [
        {
          id: 'g-ko-02-brand',
          name: '브랜드',
          keywords: ['ai empire 템플릿', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-ko-02-brand-1', headline: 'AI Empire — Next.js 14 SaaS 템플릿', description: 'AI 통합이 포함된 프로덕션 템플릿. NeuraStore, NeuraBlog, NeuraPortfolio. €19부터.', cta: '템플릿 보기' },
            { id: 'g-ko-02-brand-2', headline: 'NeuraStore & NeuraBlog by AI Empire', description: 'Stripe, 인증, AI가 내장된 프로 Next.js 14 템플릿. 몇 분 만에 배포 가능.', cta: '템플릿 확인' },
            { id: 'g-ko-02-brand-3', headline: 'AI Empire 템플릿 — SaaS를 런칭하세요', description: '프리미엄 템플릿 6종. Next.js 14, Tailwind, Stripe, AI API 포함. €19부터 €299 번들.', cta: '템플릿 둘러보기' },
          ],
        },
        {
          id: 'g-ko-02-competitor',
          name: '경쟁사',
          keywords: ['saas 보일러플레이트', 'next.js 템플릿', 'react saas 템플릿', 'saas 스타터 키트', 'nextjs 이커머스 템플릿'],
          ads: [
            { id: 'g-ko-02-comp-1', headline: 'Next.js SaaS 템플릿 — AI 내장', description: '일반 보일러플레이트와 달리 AI Empire 템플릿에는 AI API, Stripe, 인증이 포함됩니다. 바로 배포 가능.', cta: '템플릿 비교' },
            { id: 'g-ko-02-comp-2', headline: 'SaaS 보일러플레이트보다 우수', description: 'AI Empire 템플릿: 전문적인 디자인, AI 통합, Stripe 과금. 단순 스타터 코드가 아닙니다.', cta: '차이점 확인' },
            { id: 'g-ko-02-comp-3', headline: 'Next.js 14 템플릿 — 풀스택 준비 완료', description: 'UI, API, 인증, 결제, AI가 모두 포함된 템플릿. 지금 바로 배포하세요.', cta: '템플릿 보기' },
          ],
        },
        {
          id: 'g-ko-02-generic',
          name: '일반',
          keywords: ['saas 템플릿', 'nextjs 14 템플릿', 'react 템플릿', 'saas 랜딩페이지', 'saas용 템플릿', '빠른 saas 구축'],
          ads: [
            { id: 'g-ko-02-gen-1', headline: 'SaaS 템플릿 — 몇 달이 아닌 며칠 만에 런칭', description: '인증, Stripe, AI, 관리자 대시보드가 포함된 Next.js 14 템플릿. €19부터.', cta: '시작하기' },
            { id: 'g-ko-02-gen-2', headline: 'Next.js 14로 SaaS를 구축하세요', description: '프로덕션 준비 완료 템플릿. Stripe 과금, 인증, AI API, 관리자 패널 포함.', cta: '템플릿 탐색' },
            { id: 'g-ko-02-gen-3', headline: 'Next.js 14 이커머스 & 블로그 템플릿', description: '모던한 디자인의 프로 템플릿. 반응형, 다크모드, SEO 최적화. €19부터.', cta: '템플릿 쇼핑' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-03',
      name: 'AI 통합',
      objective: 'AI 통합이 필요한 개발자 유치',
      budget: '€350/월',
      adGroups: [
        {
          id: 'g-ko-03-brand',
          name: '브랜드',
          keywords: ['ai empire 통합', 'ai empire 문서', 'ai empire sdk', 'ai empire api 문서'],
          ads: [
            { id: 'g-ko-03-brand-1', headline: 'AI Empire — 어떤 앱에든 AI 추가', description: '간단한 API로 앱에 AI 기능을 추가하세요. Groq + Gemini. JS와 Python용 SDK 제공.', cta: '문서 보기' },
            { id: 'g-ko-03-brand-2', headline: 'AI Empire SDK — 5분 만에 AI 통합', description: '설치, 설정, 배포. SDK가 AI 통합을 간편하게 만들어 드립니다. 무료 티어 제공.', cta: 'SDK 확인' },
            { id: 'g-ko-03-brand-3', headline: 'AI Empire API 문서 — 지금 빌드하세요', description: '상세한 문서, 코드 예제, 튜토리얼. 오늘 바로 Next.js 앱에 AI를 추가하세요.', cta: '문서 보기' },
          ],
        },
        {
          id: 'g-ko-03-competitor',
          name: '경쟁사',
          keywords: ['ai 통합 서비스', '앱에 ai 삽입', 'ai sdk', 'groq sdk', 'gemini sdk', 'ai api 래퍼'],
          ads: [
            { id: 'g-ko-03-comp-1', headline: '커스텀 구축보다 쉬운 AI 통합', description: '여러 AI SDK를 관리하는 것은 그만하세요. AI Empire: 하나의 API, 여러 모델. 무료 티어.', cta: '간편하게 시작' },
            { id: 'g-ko-03-comp-2', headline: 'AI 통합 — 복잡한 설정 없음', description: '하나의 API 키, 하나의 엔드포인트. Groq와 Gemini 즉시 사용 가능. 테스트용 무료 크레딧. 문서 포함.', cta: '무료 체험' },
            { id: 'g-ko-03-comp-3', headline: 'AI API 래퍼를 대체하세요', description: 'AI Empire는 프로덕션 준비 완료 통합 API를 제공합니다. 과금, 속도 제한, 모니터링 포함.', cta: '자세히 보기' },
          ],
        },
        {
          id: 'g-ko-03-generic',
          name: '일반',
          keywords: ['앱에 ai 추가', 'ai 통합', '웹앱용 ai api', 'groq 통합', 'gemini 통합', 'ai api rest'],
          ads: [
            { id: 'g-ko-03-gen-1', headline: '웹앱에 AI 추가 — 간편한 REST API', description: 'Groq와 Gemini를 위한 REST API. 무료 티어. JSON 응답. 모든 언어에서 사용 가능.', cta: '무료 시작' },
            { id: 'g-ko-03-gen-2', headline: 'AI API 통합 — 개발자 친화적', description: 'JavaScript와 Python용 SDK가 포함된 잘 문서화된 API. 무료 티어. 사용량 기반 과금.', cta: '문서 보기' },
            { id: 'g-ko-03-gen-3', headline: 'Groq + Gemini API — 하나의 엔드포인트', description: '여러 AI 모델을 위한 단일 API. 무료 크레딧. Stripe 과금. 프로덕션 준비 완료.', cta: '시작하기' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-04',
      name: 'SaaS 스타터 키트',
      objective: 'SaaS 창업자 및 인디해커 전환',
      budget: '€400/월',
      adGroups: [
        {
          id: 'g-ko-04-brand',
          name: '브랜드',
          keywords: ['ai empire 스타터', 'ai empire saas 키트', 'ai empire 번들', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-ko-04-brand-1', headline: 'AI Empire — 완전한 SaaS 스타터 키트', description: 'Next.js 14, Stripe, 인증, AI API, 관리자 대시보드. SaaS 런칭에 필요한 모든 것. €19부터.', cta: '스타터 키트 받기' },
            { id: 'g-ko-04-brand-2', headline: 'AI Empire로 SaaS를 런칭하세요', description: '프로 템플릿 6종. Stripe 과금, 인증, AI API. 24시간 만에 배포.', cta: '템플릿 보기' },
            { id: 'g-ko-04-brand-3', headline: 'AI Empire 번들 — 전체 템플릿', description: '템플릿 6종 + 우선 지원 + 무료 업데이트. 완전한 SaaS 스타터 키트 €299.', cta: '번들 받기' },
          ],
        },
        {
          id: 'g-ko-04-competitor',
          name: '경쟁사',
          keywords: ['saas 스타터 키트', 'saas 보일러플레이트 nextjs', '인디해커 툴킷', '풀스택 saas 템플릿', '빠른 saas 런칭'],
          ads: [
            { id: 'g-ko-04-comp-1', headline: 'SaaS 스타터 키트 — 보일러플레이트 이상', description: 'AI Empire는 AI API, 관리자 대시보드, 실제 템플릿을 포함합니다. 단순 스타터 코드가 아닙니다.', cta: '기능 비교' },
            { id: 'g-ko-04-comp-2', headline: '24시간 만에 SaaS를 런칭하세요', description: '왜 몇 달 동안 처음부터 구축하나요? AI Empire 템플릿: 오늘 배포, 내일 반복.', cta: '템플릿 보기' },
            { id: 'g-ko-04-comp-3', headline: '인디해커 SaaS 툴킷', description: '필요한 모든 것: 템플릿, AI API, Stripe, 인증. €19부터. API는 무료 티어 제공.', cta: '빌드 시작' },
          ],
        },
        {
          id: 'g-ko-04-generic',
          name: '일반',
          keywords: ['saas 템플릿', 'saas 만들기', 'saas 앱 템플릿', 'next.js saas', 'stripe saas 템플릿', 'saas mvp'],
          ads: [
            { id: 'g-ko-04-gen-1', headline: '며칠 만에 SaaS MVP를 구축하세요', description: 'Stripe, 인증, AI가 포함된 Next.js 14 템플릿. €19부터. Vercel에 배포.', cta: '시작하기' },
            { id: 'g-ko-04-gen-2', headline: 'SaaS 템플릿 — Stripe + 인증 포함', description: '프로덕션 준비 완료 Next.js 14 템플릿. 결제, 인증, AI API 내장.', cta: '템플릿 탐색' },
            { id: 'g-ko-04-gen-3', headline: '풀스택 SaaS 템플릿 — Next.js 14', description: '모던 스택: Next.js 14, Tailwind, Stripe, AI. €19부터.', cta: '템플릿 보기' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-05',
      name: 'OpenAI 대안',
      objective: 'OpenAI 비교 트래픽 확보',
      budget: '€300/월',
      adGroups: [
        {
          id: 'g-ko-05-brand',
          name: '브랜드',
          keywords: ['ai empire vs openai', 'ai empire 대안', 'ai empire 가격', 'openai보다 저렴한'],
          ads: [
            { id: 'g-ko-05-brand-1', headline: 'AI Empire vs OpenAI — 동일한 품질, 더 저렴한 비용', description: 'AI Empire를 통한 Groq와 Gemini. 무료 티어가 포함된 통합 API. OpenAI 대비 최대 70% 절약.', cta: '가격 비교' },
            { id: 'g-ko-05-brand-2', headline: 'OpenAI에서 AI Empire로 전환하는 이유', description: '더 저렴한 비용, 다양한 모델, 통합 API, 무료 티어. 몇 분 만에 전환, 코드 변경 불필요.', cta: '가격 확인' },
            { id: 'g-ko-05-brand-3', headline: 'AI Empire — 비용 효율적인 AI API', description: 'Groq + Gemini. OpenAI 대비 70% 저렴한 동일 품질. 가입 시 무료 크레딧.', cta: '무료 시작' },
          ],
        },
        {
          id: 'g-ko-05-competitor',
          name: '경쟁사',
          keywords: ['openai 대안 api', 'openai api보다 저렴한', 'openai 가격 대안', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-ko-05-comp-1', headline: '저렴한 OpenAI 대안 — 무료 체험', description: 'AI Empire: 통합 Groq + Gemini API. 무료 티어, 종량제. OpenAI 대비 70% 저렴.', cta: '무료 체험' },
            { id: 'g-ko-05-comp-2', headline: 'Groq & Gemini API — 더 나은 가치', description: '왜 더 많이 지불하나요? Groq는 속도, Gemini는 성능. 하나의 API, 더 저렴한 비용. 무료 티어.', cta: '요금제 보기' },
            { id: 'g-ko-05-comp-3', headline: 'OpenAI에서 전환 — 70% 절약', description: 'AI Empire는 하나의 API로 Groq + Gemini를 제공합니다. 동일한 품질, 극히 저렴한 비용.', cta: '지금 비교' },
          ],
        },
        {
          id: 'g-ko-05-generic',
          name: '일반',
          keywords: ['ai api 가격', 'ai api 비용', 'groq 가격', 'gemini api 가격', 'ai api 비교', '가장 저렴한 ai api'],
          ads: [
            { id: 'g-ko-05-gen-1', headline: 'AI API — 무료부터 종량제까지', description: '무료로 시작, 합리적으로 성장. Groq + Gemini. 월정액 없음. 사용한 만큼만 지불.', cta: '가격 확인' },
            { id: 'g-ko-05-gen-2', headline: '합리적인 AI API — Groq + Gemini', description: '100 크레딧의 무료 티어. 이후 종량제. 최소 금액 없음, 벤더 종속 없음.', cta: '시작하기' },
            { id: 'g-ko-05-gen-3', headline: 'AI API 가격 — 투명하고 합리적', description: '숨겨진 비용 없음. 하나의 API로 Groq + Gemini. 무료 티어. Stripe 과금.', cta: '가격 보기' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-06',
      name: 'Vercel 템플릿 대안',
      objective: '템플릿 비교 트래픽 확보',
      budget: '€250/월',
      adGroups: [
        {
          id: 'g-ko-06-brand',
          name: '브랜드',
          keywords: ['ai empire vercel', 'ai empire 배포', 'ai empire next.js', 'ai empire 호스팅'],
          ads: [
            { id: 'g-ko-06-brand-1', headline: 'AI Empire 템플릿 — Vercel에 배포', description: 'Vercel에 최적화된 Next.js 14 템플릿. AI API, Stripe, 인증 포함. 몇 분 만에 배포.', cta: '지금 배포' },
            { id: 'g-ko-06-brand-2', headline: 'Vercel 준비 완료 SaaS 템플릿', description: 'AI Empire 템플릿: Vercel용으로 제작. 원클릭 배포. AI 통합, 과금, 인증.', cta: '템플릿 보기' },
            { id: 'g-ko-06-brand-3', headline: 'Vercel용 Next.js 14 템플릿', description: '프로 템플릿. 몇 분 만에 Vercel에 배포. AI API와 Stripe 과금 내장.', cta: '템플릿 받기' },
          ],
        },
        {
          id: 'g-ko-06-competitor',
          name: '경쟁사',
          keywords: ['vercel 템플릿 대안', 'next.js 템플릿', 'vercel 템플릿보다 우수한', 'saas 템플릿 vercel', 'template saas deploy'],
          ads: [
            { id: 'g-ko-06-comp-1', headline: '기본 템플릿을 넘어서 — AI Empire', description: '기본 Vercel 템플릿과 달리 AI Empire는 AI API, Stripe, 관리자 대시보드를 포함합니다.', cta: '기능 보기' },
            { id: 'g-ko-06-comp-2', headline: 'AI와 Stripe가 포함된 Next.js 템플릿', description: 'AI Empire: 단순 템플릿이 아닌 완전한 SaaS 스타터. AI API, 과금, 인증 포함.', cta: '비교하기' },
            { id: 'g-ko-06-comp-3', headline: '프로덕션 SaaS 템플릿 — Next.js 14', description: '데모 템플릿을 넘어서세요. AI Empire: 실제 인증, 실제 결제, 실제 AI 통합.', cta: '템플릿 보기' },
          ],
        },
        {
          id: 'g-ko-06-generic',
          name: '일반',
          keywords: ['next.js 배포 템플릿', 'saas 템플릿 배포', 'vercel saas', 'nextjs 14 배포', 'saas 배포 템플릿', 'vercel 배포 템플릿'],
          ads: [
            { id: 'g-ko-06-gen-1', headline: '오늘 SaaS를 Vercel에 배포하세요', description: 'Next.js 14 템플릿. 원클릭 배포. AI, Stripe, 인증 포함. €19부터.', cta: '배포 시작' },
            { id: 'g-ko-06-gen-2', headline: 'SaaS 템플릿 — 배포 준비 완료', description: '프로 Next.js 14 템플릿. 몇 분 만에 Vercel에 배포. 풀스택 포함.', cta: '시작하기' },
            { id: 'g-ko-06-gen-3', headline: 'Next.js 14 SaaS — 몇 분 만에 배포', description: '모든 것이 포함된 템플릿: 인증, 결제, AI, 관리자. 즉시 Vercel에 배포.', cta: '템플릿 탐색' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-07',
      name: '전자상거래 템플릿 — NeuraStore',
      objective: 'NeuraStore 템플릿 판매 촉진',
      budget: '€300/월',
      adGroups: [
        {
          id: 'g-ko-07-brand',
          name: '브랜드',
          keywords: ['neurastore', 'ai empire 이커머스', 'neurastore 템플릿', 'neurastore next.js'],
          ads: [
            { id: 'g-ko-07-brand-1', headline: 'NeuraStore — AI 기반 전자상거래 템플릿', description: 'Stripe, 장바구니, 관리자 대시보드가 포함된 Next.js 14 이커머스 템플릿. AI 상품 추천 기능.', cta: 'NeuraStore 보기' },
            { id: 'g-ko-07-brand-2', headline: 'NeuraStore — 온라인 스토어를 런칭하세요', description: '프로 이커머스 템플릿. Stripe 결제, 재고 관리, 반응형 디자인.', cta: '데모 보기' },
            { id: 'g-ko-07-brand-3', headline: 'NeuraStore by AI Empire — €29', description: '완전한 이커머스 템플릿. Next.js 14, Stripe, Tailwind. 몇 분 만에 배포.', cta: 'NeuraStore 구매' },
          ],
        },
        {
          id: 'g-ko-07-competitor',
          name: '경쟁사',
          keywords: ['next.js 이커머스 템플릿', '온라인 스토어 템플릿', 'shopify 대안 템플릿', 'react 이커머스 템플릿', 'nextjs 스토어 템플릿'],
          ads: [
            { id: 'g-ko-07-comp-1', headline: '전자상거래 템플릿 — 내 스토어를 소유하세요', description: 'Shopify와 달리 NeuraStore는 당신의 것입니다. 셀프호스팅, 커스터마이징 가능, AI 기반. €29.', cta: 'NeuraStore 받기' },
            { id: 'g-ko-07-comp-2', headline: 'Next.js 이커머스 — 완전한 제어', description: 'NeuraStore: 코드와 데이터, 스토어를 소유하세요. Stripe 통합, 관리자 대시보드.', cta: '템플릿 보기' },
            { id: 'g-ko-07-comp-3', headline: '나만의 온라인 스토어를 구축하세요', description: 'NeuraStore 템플릿: Next.js 14, Stripe, 반응형 디자인, 관리자 패널. €29.', cta: '빌드 시작' },
          ],
        },
        {
          id: 'g-ko-07-generic',
          name: '일반',
          keywords: ['전자상거래 웹사이트 템플릿', '온라인 쇼핑몰 템플릿', 'nextjs 이커머스', '온라인 스토어 구축', 'saas 이커머스 템플릿', '디지털 스토어 템플릿'],
          ads: [
            { id: 'g-ko-07-gen-1', headline: '전자상거래 웹사이트 템플릿 — Next.js 14', description: '프로 온라인 스토어 템플릿. Stripe, 장바구니, 관리자. 반응형, 다크모드. €29.', cta: '템플릿 쇼핑' },
            { id: 'g-ko-07-gen-2', headline: 'Next.js로 온라인 스토어를 구축하세요', description: 'NeuraStore: 완전한 이커머스 솔루션. 결제, 재고, AI 추천.', cta: '시작하기' },
            { id: 'g-ko-07-gen-3', headline: '온라인 스토어 템플릿 — 런칭 준비 완료', description: 'Next.js 14 이커머스 템플릿. Stripe 과금, 반응형 디자인, SEO 최적화. €29.', cta: '지금 배포' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-08',
      name: '블로그 템플릿 — NeuraBlog',
      objective: 'NeuraBlog 템플릿 판매 촉진',
      budget: '€250/월',
      adGroups: [
        {
          id: 'g-ko-08-brand',
          name: '브랜드',
          keywords: ['neurablog', 'ai empire 블로그', 'neurablog 템플릿', 'neurablog next.js'],
          ads: [
            { id: 'g-ko-08-brand-1', headline: 'NeuraBlog — SEO 최적화 블로그 템플릿', description: 'MDX, 다크모드, RSS 피드가 포함된 Next.js 14 블로그 템플릿. 뉴스레터 통합 내장.', cta: 'NeuraBlog 보기' },
            { id: 'g-ko-08-brand-2', headline: 'NeuraBlog — 몇 분 만에 프로 블로그', description: '프리미엄 블로그 템플릿. MDX 지원, SEO 최적화, 댓글 시스템. €19.', cta: '데모 보기' },
            { id: 'g-ko-08-brand-3', headline: 'NeuraBlog by AI Empire — €19', description: '완전한 블로그 템플릿. Next.js 14, MDX, 다크모드, RSS. Vercel에 배포.', cta: 'NeuraBlog 구매' },
          ],
        },
        {
          id: 'g-ko-08-competitor',
          name: '경쟁사',
          keywords: ['next.js 블로그 템플릿', 'wordpress 대안', 'ghost 대안', 'mdx 블로그 템플릿', 'react 블로그 템플릿'],
          ads: [
            { id: 'g-ko-08-comp-1', headline: '블로그 템플릿 — WordPress보다 빠른', description: 'NeuraBlog: 정적 사이트 속도, 동적 기능. MDX, SEO, 뉴스레터. €19.', cta: 'NeuraBlog 체험' },
            { id: 'g-ko-08-comp-2', headline: 'MDX 블로그 템플릿 — Next.js 14', description: 'Ghost와 달리 NeuraBlog는 완전한 제어권을 제공합니다. 셀프호스팅, 빠르고 커스터마이징 가능.', cta: '템플릿 보기' },
            { id: 'g-ko-08-comp-3', headline: '나만의 블로그, 나만의 코드 — NeuraBlog', description: '콘텐츠 플랫폼을 소유하세요. NeuraBlog: Next.js 14, MDX, 다크모드, RSS. €19.', cta: 'NeuraBlog 받기' },
          ],
        },
        {
          id: 'g-ko-08-generic',
          name: '일반',
          keywords: ['블로그 템플릿', '개인 블로그 템플릿', 'nextjs 블로그', '테크 블로그 템플릿', '블로그 시작하기', '블로그 웹사이트 템플릿'],
          ads: [
            { id: 'g-ko-08-gen-1', headline: '블로그 템플릿 — 오늘 블로그를 시작하세요', description: '프로 블로그 템플릿. SEO 최적화, 다크모드, 뉴스레터. 몇 분 만에 배포. €19.', cta: '블로그 시작' },
            { id: 'g-ko-08-gen-2', headline: 'Next.js 14 블로그 — 빠르고 아름다운', description: 'NeuraBlog: 모던 블로그 템플릿. MDX, 다크모드, RSS, 댓글 시스템. €19.', cta: '템플릿 보기' },
            { id: 'g-ko-08-gen-3', headline: '프로 블로그를 시작하세요 — €19', description: 'NeuraBlog 템플릿. SEO 최적화, 반응형, 다크모드. Vercel에 배포.', cta: '시작하기' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-09',
      name: '포트폴리오 템플릿 — NeuraPortfolio',
      objective: 'NeuraPortfolio 템플릿 판매 촉진',
      budget: '€200/월',
      adGroups: [
        {
          id: 'g-ko-09-brand',
          name: '브랜드',
          keywords: ['neuraportfolio', 'ai empire 포트폴리오', 'neuraportfolio 템플릿', '개발자 포트폴리오 템플릿'],
          ads: [
            { id: 'g-ko-09-brand-1', headline: 'NeuraPortfolio — 개발자 포트폴리오 템플릿', description: '애니메이션, 다크모드, 문의 폼이 포함된 프로 포트폴리오. Next.js 14. €29.', cta: 'NeuraPortfolio 보기' },
            { id: 'g-ko-09-brand-2', headline: 'NeuraPortfolio — 온라인에서 돋보이세요', description: '아름다운 포트폴리오 템플릿. Framer Motion 애니메이션, 반응형, 다크모드. €29.', cta: '데모 보기' },
            { id: 'g-ko-09-brand-3', headline: 'NeuraPortfolio by AI Empire — €29', description: '완전한 포트폴리오 템플릿. Next.js 14, 애니메이션, 다크모드, 문의 폼.', cta: 'NeuraPortfolio 구매' },
          ],
        },
        {
          id: 'g-ko-09-competitor',
          name: '경쟁사',
          keywords: ['개발자 포트폴리오 템플릿', '포트폴리오 웹사이트 템플릿', '최고의 포트폴리오 템플릿', '크리에이티브 포트폴리오 템플릿', '프리랜서 포트폴리오'],
          ads: [
            { id: 'g-ko-09-comp-1', headline: '포트폴리오 템플릿 — 강한 인상을 남기세요', description: 'NeuraPortfolio: 아름다운 애니메이션, 반응형 디자인, 다크모드. 일반 테마보다 우수.', cta: '템플릿 보기' },
            { id: 'g-ko-09-comp-2', headline: '포트폴리오는 돋보여야 합니다', description: 'NeuraPortfolio: Framer Motion 애니메이션, 모던 디자인, 완전한 커스터마이징. €29.', cta: 'NeuraPortfolio 보기' },
            { id: 'g-ko-09-comp-3', headline: '개발자 포트폴리오 — Next.js 14', description: 'NeuraPortfolio로 포트폴리오를 구축하세요. 빠르고 아름답고 몇 분 만에 배포 가능.', cta: '시작하기' },
          ],
        },
        {
          id: 'g-ko-09-generic',
          name: '일반',
          keywords: ['포트폴리오 웹사이트', '포트폴리오 구축', '온라인 포트폴리오', '개인 웹사이트 템플릿', '프리랜서 포트폴리오 템플릿', '쇼케이스 포트폴리오'],
          ads: [
            { id: 'g-ko-09-gen-1', headline: '온라인 포트폴리오를 구축하세요 — €29', description: 'NeuraPortfolio: 애니메이션이 포함된 프로 템플릿. 몇 분 만에 배포.', cta: '빌드 시작' },
            { id: 'g-ko-09-gen-2', headline: '개인 웹사이트 템플릿 — Next.js 14', description: '아름다운 포트폴리오 템플릿. 다크모드, 애니메이션, 반응형. €29부터.', cta: '템플릿 보기' },
            { id: 'g-ko-09-gen-3', headline: '포트폴리오 템플릿 — 오늘 배포', description: '모던한 디자인의 프로 포트폴리오. Framer Motion, 다크모드. €29.', cta: '포트폴리오 받기' },
          ],
        },
      ],
    },
    {
      id: 'g-ko-10',
      name: 'AI SaaS 빌더',
      objective: 'AI SaaS 빌더 의도 확보',
      budget: '€350/월',
      adGroups: [
        {
          id: 'g-ko-10-brand',
          name: '브랜드',
          keywords: ['ai empire saas 빌더', 'ai empire saas 구축', 'ai empire 런칭', 'ai empire 플랫폼'],
          ads: [
            { id: 'g-ko-10-brand-1', headline: 'AI Empire — AI SaaS를 구축하세요', description: '템플릿 + AI API + Stripe + 인증. AI 기반 SaaS를 구축하고 런칭하는 모든 것.', cta: '빌드 시작' },
            { id: 'g-ko-10-brand-2', headline: 'AI Empire — 나만의 AI SaaS 플랫폼', description: '아이디어에서 런칭까지. 템플릿, AI API, 결제, 인증. 24시간 만에 배포.', cta: '지금 런칭' },
            { id: 'g-ko-10-brand-3', headline: 'AI Empire — SaaS를 더 빠르게 출시하세요', description: 'AI 통합이 포함된 프로 템플릿. Stripe, 인증, 관리자 대시보드. €19부터.', cta: '시작하기' },
          ],
        },
        {
          id: 'g-ko-10-competitor',
          name: '경쟁사',
          keywords: ['ai saas 구축', 'saas 빌더', 'ai saas 템플릿', 'saas ai 플랫폼', 'ai로 saas 구축', 'ai 제품 빌더'],
          ads: [
            { id: 'g-ko-10-comp-1', headline: 'AI SaaS를 구축하세요 — 처음부터 아닙니다', description: 'AI Empire: AI API가 내장된 프로 템플릿. 몇 달의 개발 시간을 절약하세요.', cta: '템플릿 보기' },
            { id: 'g-ko-10-comp-2', headline: 'AI SaaS 빌더 — 며칠 만에 출시', description: '템플릿, AI API, Stripe, 인증. AI Empire: 런칭에 필요한 모든 것.', cta: '기능 비교' },
            { id: 'g-ko-10-comp-3', headline: 'AI SaaS를 이번 주에 런칭하세요', description: '왜 처음부터 구축하나요? AI Empire 템플릿: 24시간 만에 배포. AI 통합 포함.', cta: '무료 시작' },
          ],
        },
        {
          id: 'g-ko-10-generic',
          name: '일반',
          keywords: ['saas 템플릿', 'saas 구축', 'saas 앱', 'saas 플랫폼', 'ai 제품 템플릿', 'saas 아이디어', 'saas 런칭'],
          ads: [
            { id: 'g-ko-10-gen-1', headline: 'SaaS를 구축하세요 — 템플릿, AI, 결제', description: 'AI API, Stripe, 인증이 포함된 Next.js 14 템플릿. €19부터. 오늘 배포.', cta: '시작하기' },
            { id: 'g-ko-10-gen-2', headline: 'SaaS 빌더 — 모든 것이 포함', description: '템플릿, AI 통합, 결제, 관리자 대시보드. 완전한 SaaS 툴킷. €19부터.', cta: '템플릿 탐색' },
            { id: 'g-ko-10-gen-3', headline: 'SaaS 아이디어를 출시하세요 — Next.js 14', description: '모던 스택의 프로 템플릿. AI, Stripe, 인증. 몇 분 만에 배포.', cta: '빌드 시작' },
          ],
        },
      ],
    },
  ],
  facebook: [
    {
      id: 'fb-ko-01',
      name: 'AI Empire 브랜드 인지도',
      type: 'awareness',
      objective: '개발자와 스타트업 창업자 사이에서 브랜드 인지도 증대',
      audience: '개발자, CTO, 스타트업 창업자, 22~45세, AI, SaaS, Next.js, 웹 개발에 관심',
      placements: ['Facebook 피드', 'Instagram 피드', 'Audience Network'],
      adCopy: 'SaaS를 구축하고 계신가요? AI Empire는 Next.js 14 템플릿, 내장 AI API(Groq + Gemini), Stripe 과금, 인증을 제공합니다 — €19부터 시작. 5,000명 이상의 개발자가 더 빠르게 런칭했습니다.',
      cta: '자세히 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-ko-02',
      name: 'AI API 가치 제안',
      type: 'awareness',
      objective: '개발자에게 통합 AI API 교육',
      audience: '소프트웨어 개발자, ML 엔지니어, AI 마니아, 22~40세',
      placements: ['Facebook 피드', 'Instagram 스토리', '릴스'],
      adCopy: 'Groq와 Gemini를 위한 하나의 API. AI Empire는 여러 AI 모델을 위한 통합 엔드포인트를 제공합니다 — 무료로 시작하고 성장하면서 지불하세요. 여러 AI SDK 관리에 지쳤다면 지금 확인하세요.',
      cta: '무료 체험',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    {
      id: 'fb-ko-03',
      name: 'NeuraStore 제품 쇼케이스',
      type: 'consideration',
      objective: 'NeuraStore 템플릿 페이지로 트래픽 유도',
      audience: '이커머스 개발자, 온라인 스토어 구축자, 대안을 찾는 Shopify 사용자',
      placements: ['Facebook 피드', 'Instagram 피드', 'Marketplace'],
      adCopy: 'NeuraStore: Next.js 14로 제작된 완전한 이커머스 템플릿. Stripe 결제, 장바구니 관리, 관리자 대시보드, AI 상품 추천. €29 — 스토어와 코드를 소유하세요.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-ko-04',
      name: '템플릿 번들 혜택',
      type: 'consideration',
      objective: '전체 템플릿 번들에 대한 관심 유도',
      audience: 'SaaS 창업자, 인디해커, 풀스택 개발자',
      placements: ['Facebook 피드', 'Instagram 피드', 'Facebook Marketplace'],
      adCopy: 'AI Empire 템플릿 6종을 €299에 이용하세요. NeuraStore, NeuraBlog, NeuraPortfolio + 3종 추가. 우선 지원, 무료 업데이트, 모든 것 포함. 개별 구매 대비 €400 이상 절약.',
      cta: '번들 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-ko-05',
      name: 'AI 통합 튜토리얼',
      type: 'consideration',
      objective: '교육 콘텐츠로 개발자 참여 유도',
      audience: '웹 개발자, React 개발자, Node.js 개발자',
      placements: ['Facebook 피드', 'Instagram 릴스', '스토리'],
      adCopy: '5분 만에 Next.js 앱에 AI를 추가하세요. AI Empire의 SDK가 통합을 간편하게 만들어 드립니다 — 하나의 API 키, 하나의 엔드포인트. 100 크레딧의 무료 티어. 문서와 예제 포함.',
      cta: '문서 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    {
      id: 'fb-ko-06',
      name: '무료 API 가입',
      type: 'conversion',
      objective: '무료 티어 가입 유도',
      audience: '웹사이트 방문자, 문서 독자, 블로그 독자, 유사 오디언스',
      placements: ['Facebook 피드', 'Instagram 피드', 'Audience Network'],
      adCopy: '무료 AI API가 여러분을 기다리고 있습니다. AI Empire에 가입하고 Groq와 Gemini를 위한 100 크레딧을 받으세요. 신용카드 불필요. 지금 바로 AI로 빌드를 시작하세요.',
      cta: '무료 가입',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-ko-07',
      name: '템플릿 구매 전환',
      type: 'conversion',
      objective: '템플릿 페이지 방문자를 구매자로 전환',
      audience: '템플릿 페이지 방문자, 장바구니 포기자, 고의도 사용자',
      placements: ['Facebook 피드', 'Instagram 피드', 'Messenger'],
      adCopy: '아직 고려 중이신가요? NeuraBlog(€19)와 NeuraStore(€29)는 배포 준비 완료입니다. Stripe, 인증, AI 통합 포함. 100% 환불 보장.',
      cta: '지금 구매',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-ko-08',
      name: '한정 번들 할인',
      type: 'conversion',
      objective: '번들 구매를 위한 긴급성 생성',
      audience: '이메일 구독자, 장바구니 포기자, 높은 참여 사용자',
      placements: ['Facebook 피드', 'Instagram 피드', 'Instagram 스토리'],
      adCopy: '한정 혜택: 전체 AI Empire 템플릿 번들을 €299에 이용하세요(€400 이상 절약). 템플릿 6종, 우선 지원, 무료 업데이트 포함. 혜택이 곧 종료됩니다.',
      cta: '번들 받기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    {
      id: 'fb-ko-09',
      name: '재방문자 — 템플릿',
      type: 'retargeting',
      objective: '템플릿을 확인했으나 구매하지 않은 방문자 재참여',
      audience: '템플릿 페이지 방문자(7~30일), 구매 미완료',
      placements: ['Facebook 피드', 'Instagram 피드', 'Audience Network'],
      adCopy: 'AI Empire 템플릿을 확인하셨군요. NeuraBlog는 €19부터, NeuraStore는 €29부터입니다. 풀스택, 배포 준비 완료, AI 통합. 돌아와서 SaaS를 런칭하세요.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-ko-10',
      name: '재방문자 — API',
      type: 'retargeting',
      objective: 'API 문서를 확인했으나 가입하지 않은 방문자 재참여',
      audience: '문서 페이지 방문자(7~30일), 계정 미생성',
      placements: ['Facebook 피드', 'Instagram 스토리', '릴스'],
      adCopy: 'API 문서를 확인하셨군요. 빌드할 준비가 되셨나요? AI Empire는 Groq와 Gemini를 위한 무료 크레딧을 제공합니다. 30초 만에 가입, 신용카드 불필요.',
      cta: '무료 시작',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    {
      id: 'li-ko-01',
      name: 'SaaS 런칭 발표',
      type: 'sponsored_content',
      objective: '기술 의사결정자로부터 가입 유도',
      audience: '스타트업 및 중소기업의 CTO, 테크 리드, 엔지니어링 매니저',
      headline: 'AI Empire로 SaaS를 10배 빠르게 런칭하세요',
      body: 'AI Empire는 내장 AI API(Groq + Gemini), Stripe 과금, 인증이 포함된 Next.js 14 템플릿을 제공합니다. 몇 달이 아닌 24시간 만에 아이디어를 배포된 SaaS로 전환하세요.\n\n포함 사항:\n- 프로덕션 템플릿 6종(€19~€299)\n- 무료 티어가 포함된 통합 AI API\n- Stripe + 인증 설정 완료\n- 관리자 대시보드\n\n5,000명 이상의 개발자가 AI Empire와 함께 빌드하고 있습니다.',
      cta: '빌드 시작',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-ko-02',
      name: '엔터프라이즈용 AI API',
      type: 'sponsored_content',
      objective: 'AI API 솔루션을 평가하는 엔지니어링 리더 도달',
      audience: '중견기업 및 대기업의 엔지니어링 매니저, VP 엔지니어링, 아키텍트',
      headline: '통합 AI API — 팀을 위한 Groq + Gemini',
      body: '여러 AI 벤더 관리를 그만하세요. AI Empire는 하나의 API로 Groq와 Gemini를 제공합니다 — 내장 과금, 속도 제한, 모니터링 포함.\n\n엔지니어링 팀이 AI Empire를 선택하는 이유:\n- 여러 AI 모델을 위한 단일 엔드포인트\n- JavaScript 및 Python SDK\n- 프로토타이핑용 무료 티어\n- 종량제 스케일링\n\nAI 통합 복잡성을 줄이세요.',
      cta: 'API 탐색',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-ko-03',
      name: '인디해커 성공 사례',
      type: 'sponsored_content',
      objective: '인디해커 및 솔로 창업자 유치',
      audience: '인디해커, 솔로 창업자, 부트스트랩 스타트업 창업자',
      headline: '이번 주말에 SaaS를 출시하세요',
      body: '빠르게 움직이고 싶은 솔로 창업자를 위해 제작되었습니다.\n\nAI Empire가 제공하는 것:\n- 프로 Next.js 14 템플릿\n- 즉시 사용 가능한 AI API\n- 5분 만에 Stripe 과금\n- 런칭에 코드 작성 불필요\n\n€19부터 템플릿. 원클릭으로 Vercel에 배포.\n\n더 이상 망설이지 마세요. 출시를 시작하세요.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-ko-04',
      name: '비용 비교',
      type: 'sponsored_content',
      objective: 'AI 제공업체를 비교하는 비용 의식 팀 어필',
      audience: '스타트업 및 중소기업의 CTO, 재무 리드, 조달 담당자',
      headline: 'AI API — 경쟁사 대비 70% 저렴',
      body: 'AI Empire는 하나의 API로 Groq와 Gemini를 결합합니다. 사용한 만큼만 지불하세요.\n\n비교:\n- OpenAI: 1K 토큰당 €0.03(GPT-4)\n- AI Empire: 1K 토큰당 ~€0.009(Groq Llama)\n\n무료 티어 포함. 벤더 종속 없음. 몇 분 만에 전환.\n\n5,000명 이상의 개발자가 이미 절약하고 있습니다.',
      cta: '가격 확인',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    {
      id: 'li-ko-05',
      name: 'CTO 대상 다이렉트 아웃리치',
      type: 'message_ads',
      objective: '대상 기업의 CTO에게 맞춤형 아웃리치',
      audience: '테크, SaaS, 이커머스 분야 10~200명 규모 기업의 CTO',
      headline: 'AI 스택에 대한 간단한 질문',
      body: '{{first_name}}님 안녕하세요,\n\n{{company}}에서 AI를 사용하고 계신 것을 확인했습니다. 간단한 질문입니다: 여러 AI 벤더 API를 관리하고 계신가요?\n\nAI Empire는 Groq와 Gemini를 위한 통합 API를 제공합니다 — 단일 엔드포인트, 단일 청구서, 단일 대시보드. 무료 티어 포함.\n\n10분간 대화가 가능할까요? 자세히 설명드리겠습니다.',
      cta: '채팅 예약',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-ko-06',
      name: '개발자 대상 다이렉트 아웃리치',
      type: 'message_ads',
      objective: '개별 개발자에게 맞춤 혜택으로 참여 유도',
      audience: '테크 기업의 풀스택 개발자, React/Next.js 개발자',
      headline: 'Next.js로 빌드하고 계신가요?',
      body: '{{first_name}}님 안녕하세요,\n\nNext.js를 사용하고 계신 것을 확인했습니다. AI Empire는 Next.js 생태계를 위해 특별히 제작되었습니다 — AI API, Stripe, 인증이 준비된 템플릿.\n\n사이드 프로젝트를 진행 중이거나 팀의 출시를 돕고 계시다면 무료 티할이 유용할 수 있습니다.\n\n관심 있으시면 할인 코드를 공유해 드리겠습니다.',
      cta: '할인 코드 받기',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-ko-07',
      name: '파트너십 아웃리치',
      type: 'message_ads',
      objective: '에이전시 및 컨설팅과의 파트너십 기회 모색',
      audience: '에이전시 대표, 컨설팅 창업자, 디지털 전환 리더',
      headline: '{{company}}를 위한 파트너십 기회',
      body: '{{first_name}}님 안녕하세요,\n\nAI Empire는 팀이 AI 기반 제품을 더 빠르게 출시하도록 돕습니다. 고객에게 템플릿과 API를 추천하는 에이전시 및 컨설팅을 위한 파트너 프로그램을 구축하고 있습니다.\n\n혜택:\n- 추천 수익 분배\n- 고객 대상 우선 지원\n- 공동 마케팅 기회\n\n탐색해 볼 가치가 있을까요?',
      cta: '파트너십 알아보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    {
      id: 'li-ko-08',
      name: '다이나믹 — 직책 타겟팅',
      type: 'dynamic',
      objective: '직책별 맞춤 광고로 개발자 타겟팅',
      audience: 'CTO, VP 엔지니어링, 테크 리드, 시니어 개발자 직책 사용자',
      headline: '{{job_title}}을 위한 AI Empire — 더 빠르게 출시',
      body: 'AI Empire는 {{company_name}}에 프로덕션까지 더 빠른 경로를 제공합니다. AI API, Stripe, 인증이 포함된 Next.js 14 템플릿. 프로토타이핑용 무료 티어, 성장 시 종량제.',
      cta: 'AI Empire 탐색',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-ko-09',
      name: '다이나믹 — 기업 규모',
      type: 'dynamic',
      objective: '기업 규모별 메시징 맞춤화',
      audience: '1~50명(스타트업) 및 51~500명(성장기) 규모 기업',
      headline: '{{company_name}} — AI SaaS 템플릿',
      body: '성장하는 팀을 위해: AI Empire는 AI 통합이 포함된 프로덕션 Next.js 14 템플릿을 제공합니다. 몇 달이 아닌 며칠 만에 배포. €19부터.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-ko-10',
      name: '다이나믹 — 업종 타겟팅',
      type: 'dynamic',
      objective: '맞춤 메시징으로 특정 업종 타겟팅',
      audience: '이커머스, SaaS, 디지털 에이전시',
      headline: 'AI 기반 {{industry}} 솔루션',
      body: 'AI Empire 템플릿은 {{industry}}를 위해 제작되었습니다. Next.js 14, Stripe, AI API, 관리자 대시보드. €19부터 €299 번들까지.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-ko-01',
      tweet: 'AI Empire는 여러분이 직접 만들 필요 없도록 제작되었습니다.\n\nNext.js 14 템플릿 + Groq & Gemini API + Stripe + 인증 — 하나의 플랫폼에서.\n\n무료로 시작. 몇 분 만에 배포.',
      cta: '무료 체험',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: '개발자, 스타트업 창업자',
    },
    {
      id: 'tw-ko-02',
      tweet: '솔직히 말해서: SaaS를 구축하는 데 6개월이 걸려서는 안 됩니다.\n\nAI Empire 템플릿: 프로 Next.js 14, 내장 AI API, 설정된 Stripe.\n\n아이디어에서 배포까지 24시간.',
      cta: '템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: '인디해커, 솔로 창업자',
    },
    {
      id: 'tw-ko-03',
      tweet: '하나의 API. 여러 AI 모델. 무료 티어.\n\nAI Empire: 속도를 위한 Groq, 성능을 위한 Gemini. 통합 엔드포인트.\n\n5개의 서로 다른 AI SDK 관리를 그만하세요.',
      cta: 'API 키 받기',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'AI 개발자, 테크 리드',
    },
    {
      id: 'tw-ko-04',
      tweet: 'NeuraStore: Next.js 14용 완전한 이커머스 템플릿.\n\nStripe 결제 ✓ 장바구니 ✓ 관리자 대시보드 ✓ AI 추천 ✓\n\n€29. 몇 분 만에 Vercel에 배포.',
      cta: 'NeuraStore 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: '이커머스 개발자',
    },
    {
      id: 'tw-ko-05',
      tweet: 'OpenAI vs AI Empire 가격을 비교했습니다:\n\n동일한 품질의 결과, 70% 저렴한 비용.\n\n하나의 API로 Groq + Gemini. 무료 티어 포함. 벤더 종속 없음.',
      cta: '가격 비교',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: '비용 의식 개발자',
    },
    {
      id: 'tw-ko-06',
      tweet: 'AI Empire 템플릿으로 4시간 만에 SaaS를 배포했습니다.\n\nNext.js 14 + Stripe + 인증 + AI API. 모두 설정 완료. 코드만 추가하세요.',
      cta: '더 빠르게 출시',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: '개발자, 스타트업 창업자',
    },
    {
      id: 'tw-ko-07',
      tweet: 'AI Empire 번들: 템플릿 6종, €299.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + 3종 추가. 우선 지원. 무료 업개이트.\n\n개별 구매 대비 €400 이상 절약.',
      cta: '번들 받기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'SaaS 창업자, 개발자',
    },
    {
      id: 'tw-ko-08',
      tweet: 'WordPress에 지치셨나요?\n\nNeuraBlog: Next.js 14 블로그 템플릿. MDX, 다크모드, RSS, SEO 최적화. €19.\n\n빠르고. 모던하고. 여러분의 것.',
      cta: 'NeuraBlog 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: '블로거, 콘텐츠 크리에이터',
    },
    {
      id: 'tw-ko-09',
      tweet: 'AI Empire 무료 티어: Groq + Gemini용 100 크레딧.\n\n신용카드 불필요. 약정 없음. 빌드만 하세요.\n\n5분 설정. JS와 Python용 SDK.',
      cta: '무료 시작',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: '학생, 취미 개발자',
    },
    {
      id: 'tw-ko-10',
      tweet: '포트폴리오는 기본 HTML 템플릿보다 더 나은 것을 받을 자격이 있습니다.\n\nNeuraPortfolio: Next.js 14, Framer Motion 애니메이션, 다크모드, 반응형. €29.\n\n강한 인상을 남기세요.',
      cta: '포트폴리오 템플릿 보기',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: '개발자, 디자이너, 프리랜서',
    },
  ],
  instagram: [
    {
      id: 'ig-ko-01',
      name: '플랫폼 개요 릴스',
      type: 'reel',
      script: '씬 1: 대시보드 화면 녹화 — "AI Empire를 만나보세요" 텍스트 오버레이. 씬 2: 코드 에디터에서 API 호출 — "하나의 API, 여러 모델". 씬 3: Stripe 결제 — "5분 만에 결제 설정". 씬 4: 실시간 배포 — "24시간 만에 배포 완료". 씬 5: 로고 + URL — "오늘 무료로 시작하세요".',
      visualDirection: '부드러운 전환이 포함된 빠른 화면 녹화. 다크모드 UI. 퍼플 그라디언트 브랜드 컬러. 경쾌한 일렉트로닉 배경 음악.',
      textOverlay: 'AI Empire — SaaS를 더 빠르게 구축하세요',
      cta: '바이오 링크 — 무료 시작',
      duration: '15~30초',
    },
    {
      id: 'ig-ko-02',
      name: 'NeuraStore 쇼케이스 스토리',
      type: 'story',
      script: 'NeuraStore 템플릿 스와이프 쇼케이스. 상품 그리드, 장바구니 흐름, Stripe 결제, 모바일 반응형 뷰 표시. 가격 태그(€29)와 CTA로 마무리.',
      visualDirection: '깔끔한 화이트/다크 배경. iPhone과 MacBook의 제품 모킹. 부드러운 스와이프 애니메이션. 브랜드 퍼플 악센트.',
      textOverlay: 'NeuraStore — €29 — 이커머스 템플릿',
      cta: '스와이프하여 보기',
      duration: '15초',
    },
    {
      id: 'ig-ko-03',
      name: 'AI API 데모 릴스',
      type: 'reel',
      script: '씬 1: 개발자가 코드를 입력 — "앱에 AI 추가하기". 씬 2: 터미널에서 API 응답 — "Groq + Gemini 단일 호출". 씬 3: AI 기능이 적용된 앱 실행 — "5분 통합". 씬 4: 가격 화면 — "무료로 시작".',
      visualDirection: '어깨 너머 코딩 샷과 화면 녹화 혼합. 다크 테마. 검정 배경에 녹색 터미널. 음악에 맞춘 빠른 컷.',
      textOverlay: 'AI API — 무료 티어 제공',
      cta: 'API 키 받기 — 바이오 링크',
      duration: '20~30초',
    },
    {
      id: 'ig-ko-04',
      name: '템플릿 번들 스토리',
      type: 'story',
      script: '3프레임 스토리. 프레임 1: 6개 템플릿 그리드 표시 — "6개 템플릿. €299." 프레임 2: 개별 템플릿 하이라이트 — "NeuraStore, NeuraBlog, NeuraPortfolio..." 프레임 3: 절약 강조 — "€400+ 절약" CTA 버튼 포함.',
      visualDirection: '제품 그리드 레이아웃. 각 템플릿을 기기 모킹으로 표시. 퍼플 그라디언트 배경. 굵은 타이포그래피.',
      textOverlay: '전체 번들 — €299 — €400+ 절약',
      cta: '번들 받기',
      duration: '프레임당 15초',
    },
    {
      id: 'ig-ko-05',
      name: '개발자 추천 릴스',
      type: 'reel',
      script: '씬 1: 개발자 셀프카메라/영상 — "AI Empire로 2일 만에 SaaS를 런칭했습니다". 씬 2: 배포된 앱 화면 녹화. 씬 3: 통합 코드 스니펫. 씬 4: CTA 오버레이.',
      visualDirection: '진정성 있는 UGC 스타일 영상. 자연광. 핸드헬드 카메라 느낌. 접근성을 위한 자막.',
      textOverlay: '"2일 만에 런칭" — @developer',
      cta: '빌드 시작 — 바이오 링크',
      duration: '30초',
    },
    {
      id: 'ig-ko-06',
      name: 'NeuraBlog 기능 스토리',
      type: 'story',
      script: 'NeuraBlog 워크스루: MDX 에디터, 다크모드 토글, 반응형 모바일 뷰, RSS 피드 미리보기, 댓글 섹션. 가격(€19)과 CTA로 마무리.',
      visualDirection: '주요 기능에 대한 줌 효과가 포함된 화면 녹화. 라이트/다크 모드를 보여주는 분할 화면. 깔끔하고 미니멀한 미학.',
      textOverlay: 'NeuraBlog — €19 — SEO 블로그 템플릿',
      cta: '스와이프 — 템플릿 보기',
      duration: '15초',
    },
    {
      id: 'ig-ko-07',
      name: 'SaaS 속도 챌린지 릴스',
      type: 'reel',
      script: '처음부터 SaaS를 구축하는 타임랩스. 0:00부터 4:00:00까지 카운트되는 타이머 오버레이. 템플릿 선택, API 설정, Stripe 설정, 배포 과정 표시. 실시간 URL로 마무리.',
      visualDirection: '분할 화면: 왼쪽 타이머, 오른쪽 화면 녹화. 고속 효과. 활기찬 배경 음악. 1시간, 2시간, 3시간 마일스톤 마커.',
      textOverlay: '4시간 만에 SaaS를 구축했습니다',
      cta: 'AI Empire 체험 — 바이오 링크',
      duration: '30~60초',
    },
    {
      id: 'ig-ko-08',
      name: '무료 티어 발표 스토리',
      type: 'story',
      script: '굵은 타이포그래피 리빌: "무료" → "AI API" → "100 크레딧" → "Groq + Gemini" → "신용카드 불필요" → CTA. 각 텍스트 요소가 바운스 또는 슬라이드 효과로 등장.',
      visualDirection: '단색 퍼플/다크 배경. 큰 굵은 흰색 텍스트. 미니멀 디자인. 각 프레임이 강렬한 애니메이션으로 전환.',
      textOverlay: '무료 AI API — 100 크레딧 — 카드 불필요',
      cta: '무료 가입',
      duration: '전체 10초',
    },
    {
      id: 'ig-ko-09',
      name: 'NeuraPortfolio 쇼케이스 릴스',
      type: 'reel',
      script: 'NeuraPortfolio 애니메이션 쇼케이스: 히어로 섹션 패럴랙스, 프로젝트 카드 호버 효과, 부드러운 페이지 전환, 다크모드. 모두 MacBook 모킹에서 표시.',
      visualDirection: '우아하고 슬로우 모션 기기 모킹. 미세한 카메라 움직임. 부드러운 조명. 미니멀 배경 음악. 애니메이션 품질에 초점.',
      textOverlay: 'NeuraPortfolio — €29 — 개발자 포트폴리오',
      cta: '바이오 링크 — 데모 보기',
      duration: '20~30초',
    },
    {
      id: 'ig-ko-10',
      name: '비교 캐러셀 스토리',
      type: 'story',
      script: '프레임 1: "처음부터 구축: 3~6개월" 달력 아이콘. 프레임 2: "AI Empire 사용: 1~2일" 로켓 아이콘. 프레임 3: "동일한 결과. 95% 단축." 프레임 4: 가격이 포함된 CTA.',
      visualDirection: '나란히 비교 레이아웃. 비포/에프터 스타일. "느린" 옵션에 빨간색, AI Empire에 녹색. 강렬한 임팩트 타이포그래피.',
      textOverlay: '3개월 vs 2일 — 빠른 것을 선택하세요',
      cta: '지금 시작 — 바이오 링크',
      duration: '프레임당 15초',
    },
  ],
};
