import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'pt',
  googleSearch: [
    // === Campanha 1: Plataforma de API de IA ===
    {
      id: 'g-pt-01',
      name: 'Plataforma de API de IA',
      objective: 'Impulsionar inscrições no tier gratuito da API de IA',
      budget: '€500/mês',
      adGroups: [
        {
          id: 'g-pt-01-brand',
          name: 'Brand',
          keywords: ['ai empire', 'ai-empire', 'api ai empire', 'plataforma ai empire'],
          ads: [
            { id: 'g-pt-01-brand-1', headline: 'AI Empire — Plataforma Unificada de API de IA', description: 'Acesse Groq e Gemini por meio de uma única API. Tier gratuito disponível, sem cartão de crédito. Integração em 5 minutos.', cta: 'Testar Grátis' },
            { id: 'g-pt-01-brand-2', headline: 'AI Empire — Sua Gateway de IA', description: 'Uma API, múltiplos modelos de IA. Groq + Gemini. Créditos gratuitos na inscrição. SDKs para JavaScript e Python incluídos.', cta: 'Obter Chave de API' },
            { id: 'g-pt-01-brand-3', headline: 'AI Empire — Desenvolva com IA Hoje', description: 'APIs de IA prontas para produção. Groq para velocidade, Gemini para capacidade. Tier gratuito, preços pay-as-you-go.', cta: 'Começar a Construir' },
          ],
        },
        {
          id: 'g-pt-01-competitor',
          name: 'Competidor',
          keywords: ['alternativa openai', 'alternativa groq api', 'api de ia mais barata', 'wrapper api gemini', 'comparativo api ia'],
          ads: [
            { id: 'g-pt-01-comp-1', headline: 'API de IA Acessível — Economize vs OpenAI', description: 'Mesma qualidade de IA por menor custo. Groq + Gemini unificados. Tier gratuito com 100 créditos. Mude em minutos.', cta: 'Comparar Preços' },
            { id: 'g-pt-01-comp-2', headline: 'Alternativa ao OpenAI — AI Empire', description: 'Procurando uma API de IA econômica? AI Empire combina Groq e Gemini em um único endpoint. Grátis para começar.', cta: 'Ver Planos' },
            { id: 'g-pt-01-comp-3', headline: 'API de IA — 70% Menos que OpenAI', description: 'Resultados de qualidade GPT com Groq e Gemini. API unificada. Tier gratuito. Sem lock-in com fornecedor.', cta: 'Começar Grátis' },
          ],
        },
        {
          id: 'g-pt-01-generic',
          name: 'Genérico',
          keywords: ['api de ia', 'api inteligência artificial', 'api groq', 'api gemini', 'ia para desenvolvedores', 'api ia gratuita'],
          ads: [
            { id: 'g-pt-01-gen-1', headline: 'API de IA para Desenvolvedores — Tier Gratuito', description: 'Groq + Gemini por meio de uma única API. Créditos gratuitos na inscrição. Documentação, exemplos e SDKs incluídos.', cta: 'Ler Documentação' },
            { id: 'g-pt-01-gen-2', headline: 'Integre IA ao Seu App — Setup em 5 Min', description: 'Uma API para Groq e Gemini. Tier gratuito disponível. Faturamento Stripe. Documentação completa.', cta: 'Começar' },
            { id: 'g-pt-01-gen-3', headline: 'APIs de IA — Groq e Gemini Combinados', description: 'Endpoint unificado para múltiplos modelos de IA. Grátis para começar, pague pelo que usar. Pronto para produção.', cta: 'Explorar API' },
          ],
        },
      ],
    },
    // === Campanha 2: Templates SaaS Next.js ===
    {
      id: 'g-pt-02',
      name: 'Templates SaaS Next.js',
      objective: 'Impulsionar vendas de templates',
      budget: '€400/mês',
      adGroups: [
        {
          id: 'g-pt-02-brand',
          name: 'Brand',
          keywords: ['template ai empire', 'saas ai empire', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-pt-02-brand-1', headline: 'AI Empire — Templates SaaS para Next.js 14', description: 'Templates prontos para produção com integração de IA. NeuraStore, NeuraBlog, NeuraPortfolio. A partir de €19.', cta: 'Ver Templates' },
            { id: 'g-pt-02-brand-2', headline: 'NeuraStore e NeuraBlog da AI Empire', description: 'Templates profissionais para Next.js 14 com Stripe, autenticação e IA integrados. Deploy em minutos.', cta: 'Ver Templates' },
            { id: 'g-pt-02-brand-3', headline: 'Templates AI Empire — Lançue Seu SaaS', description: '6 templates premium. Next.js 14, Tailwind, Stripe, APIs de IA incluídas. De €19 a €299 no bundle.', cta: 'Navegar Templates' },
          ],
        },
        {
          id: 'g-pt-02-competitor',
          name: 'Competidor',
          keywords: ['boilerplate saas', 'template next.js', 'template saas react', 'kit inicial saas', 'template ecommerce nextjs'],
          ads: [
            { id: 'g-pt-02-comp-1', headline: 'Template SaaS Next.js — IA Integrada', description: 'Diferente de boilerplates genéricos, os templates AI Empire incluem APIs de IA, Stripe e autenticação. Prontos para deploy.', cta: 'Comparar Templates' },
            { id: 'g-pt-02-comp-2', headline: 'Mais que um Boilerplate SaaS', description: 'Templates AI Empire: design profissional, integração de IA, faturamento Stripe. Não é apenas código inicial.', cta: 'Ver a Diferença' },
            { id: 'g-pt-02-comp-3', headline: 'Template Next.js 14 — Full Stack Pronto', description: 'Templates com tudo incluso: UI, API, autenticação, pagamentos, IA. Deploy hoje.', cta: 'Ver Templates' },
          ],
        },
        {
          id: 'g-pt-02-generic',
          name: 'Genérico',
          keywords: ['template saas', 'template nextjs 14', 'template react', 'landing page saas', 'template para saas', 'construir saas rápido'],
          ads: [
            { id: 'g-pt-02-gen-1', headline: 'Templates SaaS — Lance em Dias, Não Meses', description: 'Templates Next.js 14 com autenticação, Stripe, IA e painel administrativo. A partir de €19.', cta: 'Começar' },
            { id: 'g-pt-02-gen-2', headline: 'Construa um SaaS com Next.js 14', description: 'Templates prontos para produção. Faturamento Stripe, autenticação, APIs de IA, painel admin incluídos.', cta: 'Explorar Templates' },
            { id: 'g-pt-02-gen-3', headline: 'Templates E-Commerce e Blog Next.js 14', description: 'Templates profissionais com design moderno. Responsivo, dark mode, otimizados para SEO. A partir de €19.', cta: 'Comprar Templates' },
          ],
        },
      ],
    },
    // === Campanha 3: Integração de IA ===
    {
      id: 'g-pt-03',
      name: 'Integração de IA',
      objective: 'Atrair desenvolvedores que precisam de integração de IA',
      budget: '€350/mês',
      adGroups: [
        {
          id: 'g-pt-03-brand',
          name: 'Brand',
          keywords: ['integração ai empire', 'documentação ai empire', 'sdk ai empire', 'documentação api ai empire'],
          ads: [
            { id: 'g-pt-03-brand-1', headline: 'AI Empire — Adicione IA a Qualquer App', description: 'API simples para adicionar capacidades de IA ao seu app. Groq + Gemini. SDKs para JS e Python.', cta: 'Ler Documentação' },
            { id: 'g-pt-03-brand-2', headline: 'SDK AI Empire — IA em 5 Minutos', description: 'Instale, configure, faça deploy. Nosso SDK torna a integração de IA simples. Tier gratuito disponível.', cta: 'Ver SDK' },
            { id: 'g-pt-03-brand-3', headline: 'Documentação API AI Empire — Comece', description: 'Documentação completa, exemplos de código e tutoriais. Adicione IA ao seu app Next.js hoje.', cta: 'Ler Documentação' },
          ],
        },
        {
          id: 'g-pt-03-competitor',
          name: 'Competidor',
          keywords: ['serviço integração ia', 'incorporar ia no app', 'sdk ia', 'sdk groq', 'sdk gemini', 'wrapper api ia'],
          ads: [
            { id: 'g-pt-03-comp-1', headline: 'Integração de IA Mais Fácil que Construir Custom', description: 'Pare de manter múltiplos SDKs de IA. AI Empire: uma API, múltiplos modelos. Tier gratuito.', cta: 'Simplificar Agora' },
            { id: 'g-pt-03-comp-2', headline: 'Integração de IA — Sem Configuração Complexa', description: 'Uma chave de API, um endpoint. Groq e Gemini prontos. Créditos gratuitos para testes. Documentação incluída.', cta: 'Testar Grátis' },
            { id: 'g-pt-03-comp-3', headline: 'Substitua Seu Wrapper de API de IA', description: 'AI Empire fornece uma API unificada pronta para produção. Faturamento, rate limiting e monitoramento incluídos.', cta: 'Saiba Como' },
          ],
        },
        {
          id: 'g-pt-03-generic',
          name: 'Genérico',
          keywords: ['adicionar ia ao app', 'integrar ia', 'api ia para web app', 'integração groq', 'integração gemini', 'api ia rest'],
          ads: [
            { id: 'g-pt-03-gen-1', headline: 'Adicione IA à Sua Web App — API REST Simples', description: 'API REST para Groq e Gemini. Tier gratuito. Respostas JSON. Funciona com qualquer linguagem.', cta: 'Começar Grátis' },
            { id: 'g-pt-03-gen-2', headline: 'Integração API de IA — Amigável para Desenvolvedores', description: 'API bem documentada com SDKs para JavaScript e Python. Tier gratuito. Pague pelo que usar.', cta: 'Ver Documentação' },
            { id: 'g-pt-03-gen-3', headline: 'API Groq + Gemini — Um Endpoint', description: 'API única para múltiplos modelos de IA. Créditos gratuitos. Faturamento Stripe. Pronto para produção.', cta: 'Começar' },
          ],
        },
      ],
    },
    // === Campanha 4: Kit Inicial SaaS ===
    {
      id: 'g-pt-04',
      name: 'Kit Inicial SaaS',
      objective: 'Converter fundadores de SaaS e hackers indie',
      budget: '€400/mês',
      adGroups: [
        {
          id: 'g-pt-04-brand',
          name: 'Brand',
          keywords: ['kit inicial ai empire', 'kit saas ai empire', 'bundle ai empire', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-pt-04-brand-1', headline: 'AI Empire — Kit Completo de Início SaaS', description: 'Next.js 14, Stripe, Autenticação, APIs de IA, painel administrativo. Tudo para lançar seu SaaS. A partir de €19.', cta: 'Obter Kit' },
            { id: 'g-pt-04-brand-2', headline: 'Lance Seu SaaS com AI Empire', description: '6 templates profissionais. Faturamento Stripe, autenticação, APIs de IA. Deploy em 24 horas.', cta: 'Ver Templates' },
            { id: 'g-pt-04-brand-3', headline: 'Bundle AI Empire — Todos os Templates', description: '6 templates + suporte prioritário + atualizações gratuitas. Kit completo para SaaS por €299.', cta: 'Obter Bundle' },
          ],
        },
        {
          id: 'g-pt-04-competitor',
          name: 'Competidor',
          keywords: ['kit inicial saas', 'boilerplate saas nextjs', 'toolkit hacker indie', 'template saas full stack', 'lançar saas rápido'],
          ads: [
            { id: 'g-pt-04-comp-1', headline: 'Kit Inicial SaaS — Mais que Boilerplate', description: 'AI Empire inclui APIs de IA, painel administrativo e templates reais. Não é apenas código inicial.', cta: 'Comparar Funcionalidades' },
            { id: 'g-pt-04-comp-2', headline: 'Lance Seu SaaS em 24 Horas', description: 'Por que gastar meses construindo do zero? Templates AI Empire: deploy hoje, itere amanhã.', cta: 'Ver Templates' },
            { id: 'g-pt-04-comp-3', headline: 'Toolkit SaaS para Hacker Indie', description: 'Tudo que você precisa: templates, APIs de IA, Stripe, autenticação. A partir de €19. Tier gratuito para API.', cta: 'Começar a Construir' },
          ],
        },
        {
          id: 'g-pt-04-generic',
          name: 'Genérico',
          keywords: ['template saas', 'como construir saas', 'template app saas', 'next.js saas', 'template saas stripe', 'saas mvp'],
          ads: [
            { id: 'g-pt-04-gen-1', headline: 'Construa um MVP SaaS em Dias', description: 'Templates Next.js 14 com Stripe, autenticação e IA. A partir de €19. Deploy na Vercel.', cta: 'Começar' },
            { id: 'g-pt-04-gen-2', headline: 'Template SaaS — Stripe e Autenticação Incluídos', description: 'Templates Next.js 14 prontos para produção. Pagamentos, autenticação, APIs de IA integrados.', cta: 'Explorar Templates' },
            { id: 'g-pt-04-gen-3', headline: 'Template SaaS Full Stack — Next.js 14', description: 'Stack moderno: Next.js 14, Tailwind, Stripe, IA. Templates a partir de €19.', cta: 'Ver Templates' },
          ],
        },
      ],
    },
    // === Campanha 5: Alternativa ao OpenAI ===
    {
      id: 'g-pt-05',
      name: 'Alternativa ao OpenAI',
      objective: 'Capturar tráfego de comparação com OpenAI',
      budget: '€300/mês',
      adGroups: [
        {
          id: 'g-pt-05-brand',
          name: 'Brand',
          keywords: ['ai empire vs openai', 'alternativa ai empire', 'preços ai empire', 'mais barato que openai'],
          ads: [
            { id: 'g-pt-05-brand-1', headline: 'AI Empire vs OpenAI — Mesma Qualidade, Menor Custo', description: 'Groq e Gemini por meio da AI Empire. API unificada com tier gratuito. Economize até 70% vs OpenAI.', cta: 'Comparar Preços' },
            { id: 'g-pt-05-brand-2', headline: 'Por que Mudar para AI Empire do OpenAI', description: 'Menor custo, múltiplos modelos, API unificada, tier gratuito. Mude em minutos, sem alterar o código.', cta: 'Ver Preços' },
            { id: 'g-pt-05-brand-3', headline: 'AI Empire — API de IA Acessível', description: 'Groq + Gemini. 70% mais barata que OpenAI para qualidade semelhante. Créditos gratuitos na inscrição.', cta: 'Começar Grátis' },
          ],
        },
        {
          id: 'g-pt-05-competitor',
          name: 'Competidor',
          keywords: ['alternativa api openai', 'api mais barata que openai', 'alternativa preços openai', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-pt-05-comp-1', headline: 'Alternativa Econômica ao OpenAI — Teste Grátis', description: 'AI Empire: API unificada Groq + Gemini. Tier gratuito, pay-as-you-go. 70% menos que OpenAI.', cta: 'Testar Grátis' },
            { id: 'g-pt-05-comp-2', headline: 'API Groq e Gemini — Melhor Custo-Benefício', description: 'Por que pagar mais? Groq para velocidade, Gemini para capacidade. Uma API, menor custo. Tier gratuito.', cta: 'Ver Planos' },
            { id: 'g-pt-05-comp-3', headline: 'Mude do OpenAI — Economize 70%', description: 'AI Empire fornece Groq e Gemini por meio de uma API. Mesma qualidade, fração do custo.', cta: 'Comparar Agora' },
          ],
        },
        {
          id: 'g-pt-05-generic',
          name: 'Genérico',
          keywords: ['preços api ia', 'custo api ia', 'preços groq', 'preços api gemini', 'comparativo api ia', 'api ia mais barata'],
          ads: [
            { id: 'g-pt-05-gen-1', headline: 'API de IA — De Grátis a Pay-As-You-Go', description: 'Comece grátis, escale acessivelmente. Groq + Gemini. Sem taxas mensais. Pague apenas pelo que usar.', cta: 'Ver Preços' },
            { id: 'g-pt-05-gen-2', headline: 'API de IA Acessível — Groq + Gemini', description: 'Tier gratuito com 100 créditos. Depois pay-as-you-go. Sem mínimo, sem lock-in.', cta: 'Começar' },
            { id: 'g-pt-05-gen-3', headline: 'Preços API de IA — Transparentes e Justos', description: 'Sem taxas ocultas. Groq e Gemini por meio de uma API. Tier gratuito. Faturamento Stripe.', cta: 'Ver Preços' },
          ],
        },
      ],
    },
    // === Campanha 6: Alternativa aos Templates Vercel ===
    {
      id: 'g-pt-06',
      name: 'Alternativa aos Templates Vercel',
      objective: 'Capturar tráfego de comparação de templates',
      budget: '€250/mês',
      adGroups: [
        {
          id: 'g-pt-06-brand',
          name: 'Brand',
          keywords: ['ai empire vercel', 'deploy ai empire', 'ai empire next.js', 'hosting ai empire'],
          ads: [
            { id: 'g-pt-06-brand-1', headline: 'Templates AI Empire — Deploy na Vercel', description: 'Templates Next.js 14 otimizados para Vercel. APIs de IA, Stripe, autenticação incluídos. Deploy em minutos.', cta: 'Fazer Deploy Agora' },
            { id: 'g-pt-06-brand-2', headline: 'Templates SaaS Prontos para Vercel', description: 'Templates AI Empire: construídos para Vercel. Deploy com um clique. Integração de IA, faturamento, autenticação.', cta: 'Ver Templates' },
            { id: 'g-pt-06-brand-3', headline: 'Templates Next.js 14 para Vercel', description: 'Templates profissionais. Deploy na Vercel em minutos. APIs de IA e faturamento Stripe integrados.', cta: 'Obter Templates' },
          ],
        },
        {
          id: 'g-pt-06-competitor',
          name: 'Competidor',
          keywords: ['alternativa template vercel', 'template next.js', 'melhor que template vercel', 'template saas vercel', 'template saas deploy'],
          ads: [
            { id: 'g-pt-06-comp-1', headline: 'Templates Além do Básico — AI Empire', description: 'Diferente de templates básicos da Vercel, AI Empire inclui APIs de IA, Stripe, painel administrativo.', cta: 'Ver Funcionalidades' },
            { id: 'g-pt-06-comp-2', headline: 'Template Next.js com IA e Stripe', description: 'AI Empire: não é apenas um template, é um kit inicial SaaS completo. APIs de IA, faturamento, autenticação incluídos.', cta: 'Comparar' },
            { id: 'g-pt-06-comp-3', headline: 'Templates SaaS para Produção — Next.js 14', description: 'Além de templates demo. AI Empire: autenticação real, pagamentos reais, integração de IA real.', cta: 'Ver Templates' },
          ],
        },
        {
          id: 'g-pt-06-generic',
          name: 'Genérico',
          keywords: ['template deploy next.js', 'template deploy saas', 'vercel saas', 'deploy nextjs 14', 'template deploy saas', 'template deploy vercel'],
          ads: [
            { id: 'g-pt-06-gen-1', headline: 'Faça Deploy do Seu SaaS na Vercel Hoje', description: 'Templates Next.js 14. Deploy com um clique. IA, Stripe, autenticação incluídos. A partir de €19.', cta: 'Começar Deploy' },
            { id: 'g-pt-06-gen-2', headline: 'Template SaaS — Pronto para Deploy', description: 'Templates profissionais Next.js 14. Deploy na Vercel em minutos. Full stack incluído.', cta: 'Começar' },
            { id: 'g-pt-06-gen-3', headline: 'Next.js 14 SaaS — Deploy em Minutos', description: 'Templates com tudo: autenticação, pagamentos, IA, admin. Deploy na Vercel instantaneamente.', cta: 'Explorar Templates' },
          ],
        },
      ],
    },
    // === Campanha 7: Template E-Commerce ===
    {
      id: 'g-pt-07',
      name: 'Template E-Commerce — NeuraStore',
      objective: 'Impulsionar vendas do template NeuraStore',
      budget: '€300/mês',
      adGroups: [
        {
          id: 'g-pt-07-brand',
          name: 'Brand',
          keywords: ['neurastore', 'ecommerce ai empire', 'template neurastore', 'neurastore next.js'],
          ads: [
            { id: 'g-pt-07-brand-1', headline: 'NeuraStore — Template E-Commerce com IA', description: 'Template e-commerce Next.js 14 com Stripe, carrinho, painel administrativo. Recomendações de produto por IA.', cta: 'Ver NeuraStore' },
            { id: 'g-pt-07-brand-2', headline: 'NeuraStore — Lance Sua Loja Online', description: 'Template e-commerce profissional. Pagamentos Stripe, gerenciamento de inventário, design responsivo.', cta: 'Ver Demo' },
            { id: 'g-pt-07-brand-3', headline: 'NeuraStore da AI Empire — €29', description: 'Template e-commerce completo. Next.js 14, Stripe, Tailwind. Deploy em minutos.', cta: 'Comprar NeuraStore' },
          ],
        },
        {
          id: 'g-pt-07-competitor',
          name: 'Competidor',
          keywords: ['template ecommerce next.js', 'template loja online', 'alternativa shopify template', 'template react ecommerce', 'template store nextjs'],
          ads: [
            { id: 'g-pt-07-comp-1', headline: 'Template E-Commerce — Tenha Sua Loja', description: 'Diferente da Shopify, NeuraStore é sua. Self-hosted, personalizável, com IA. €29.', cta: 'Obter NeuraStore' },
            { id: 'g-pt-07-comp-2', headline: 'E-Commerce Next.js — Controle Total', description: 'NeuraStore: tenha seu código, seus dados, sua loja. Integração Stripe, painel administrativo.', cta: 'Ver Template' },
            { id: 'g-pt-07-comp-3', headline: 'Construa Sua Loja Online', description: 'Template NeuraStore: Next.js 14, Stripe, design responsivo, painel admin. €29.', cta: 'Começar a Construir' },
          ],
        },
        {
          id: 'g-pt-07-generic',
          name: 'Genérico',
          keywords: ['template site ecommerce', 'template loja online', 'nextjs ecommerce', 'construir loja online', 'template saas ecommerce', 'template loja digital'],
          ads: [
            { id: 'g-pt-07-gen-1', headline: 'Template Site E-Commerce — Next.js 14', description: 'Template loja online profissional. Stripe, carrinho, admin. Responsivo, dark mode. €29.', cta: 'Comprar Template' },
            { id: 'g-pt-07-gen-2', headline: 'Construa uma Loja Online com Next.js', description: 'NeuraStore: solução e-commerce completa. Pagamentos, inventário, recomendações de IA.', cta: 'Começar' },
            { id: 'g-pt-07-gen-3', headline: 'Template Loja Online — Pronto para Lançar', description: 'Template e-commerce Next.js 14. Faturamento Stripe, design responsivo, otimizado para SEO. €29.', cta: 'Fazer Deploy Agora' },
          ],
        },
      ],
    },
    // === Campanha 8: Template Blog ===
    {
      id: 'g-pt-08',
      name: 'Template Blog — NeuraBlog',
      objective: 'Impulsionar vendas do template NeuraBlog',
      budget: '€250/mês',
      adGroups: [
        {
          id: 'g-pt-08-brand',
          name: 'Brand',
          keywords: ['neurablog', 'blog ai empire', 'template neurablog', 'neurablog next.js'],
          ads: [
            { id: 'g-pt-08-brand-1', headline: 'NeuraBlog — Template Blog Otimizado para SEO', description: 'Template blog Next.js 14 com MDX, dark mode, feed RSS. Integração de newsletter integrada.', cta: 'Ver NeuraBlog' },
            { id: 'g-pt-08-brand-2', headline: 'NeuraBlog — Blog Profissional em Minutos', description: 'Template blog premium. Suporte MDX, otimização SEO, sistema de comentários. €19.', cta: 'Ver Demo' },
            { id: 'g-pt-08-brand-3', headline: 'NeuraBlog da AI Empire — €19', description: 'Template blog completo. Next.js 14, MDX, dark mode, RSS. Deploy na Vercel.', cta: 'Comprar NeuraBlog' },
          ],
        },
        {
          id: 'g-pt-08-competitor',
          name: 'Competidor',
          keywords: ['template blog next.js', 'alternativa wordpress', 'alternativa ghost', 'template blog mdx', 'template blog react'],
          ads: [
            { id: 'g-pt-08-comp-1', headline: 'Template Blog — Mais Rápido que WordPress', description: 'NeuraBlog: velocidade de site estático, funcionalidades dinâmicas. MDX, SEO, newsletter. €19.', cta: 'Testar NeuraBlog' },
            { id: 'g-pt-08-comp-2', headline: 'Template Blog MDX — Next.js 14', description: 'Diferente do Ghost, NeuraBlog dá controle total. Self-hosted, rápido, personalizável.', cta: 'Ver Template' },
            { id: 'g-pt-08-comp-3', headline: 'Seu Blog, Seu Código — NeuraBlog', description: 'Tenha sua plataforma de conteúdo. NeuraBlog: Next.js 14, MDX, dark mode, RSS. €19.', cta: 'Obter NeuraBlog' },
          ],
        },
        {
          id: 'g-pt-08-generic',
          name: 'Genérico',
          keywords: ['template blog', 'template blog pessoal', 'nextjs blog', 'template blog tech', 'iniciar um blog', 'template site blog'],
          ads: [
            { id: 'g-pt-08-gen-1', headline: 'Template Blog — Lance Seu Blog Hoje', description: 'Template blog profissional. Otimizado para SEO, dark mode, newsletter. Deploy em minutos. €19.', cta: 'Começar a Blogar' },
            { id: 'g-pt-08-gen-2', headline: 'Blog Next.js 14 — Rápido e Bonito', description: 'NeuraBlog: template blog moderno. MDX, dark mode, RSS, sistema de comentários. €19.', cta: 'Ver Template' },
            { id: 'g-pt-08-gen-3', headline: 'Inicie um Blog Profissional — €19', description: 'Template NeuraBlog. Otimizado para SEO, responsivo, dark mode. Deploy na Vercel.', cta: 'Começar' },
          ],
        },
      ],
    },
    // === Campanha 9: Template Portfolio ===
    {
      id: 'g-pt-09',
      name: 'Template Portfolio — NeuraPortfolio',
      objective: 'Impulsionar vendas do template NeuraPortfolio',
      budget: '€200/mês',
      adGroups: [
        {
          id: 'g-pt-09-brand',
          name: 'Brand',
          keywords: ['neuraportfolio', 'portfolio ai empire', 'template neuraportfolio', 'template portfolio desenvolvedor'],
          ads: [
            { id: 'g-pt-09-brand-1', headline: 'NeuraPortfolio — Template Portfolio de Desenvolvedor', description: 'Portfolio profissional com animações, dark mode, formulário de contato. Next.js 14. €29.', cta: 'Ver NeuraPortfolio' },
            { id: 'g-pt-09-brand-2', headline: 'NeuraPortfolio — Destaque-se Online', description: 'Template portfolio impressionante. Animações Framer Motion, responsivo, dark mode. €29.', cta: 'Ver Demo' },
            { id: 'g-pt-09-brand-3', headline: 'NeuraPortfolio da AI Empire — €29', description: 'Template portfolio completo. Next.js 14, animações, dark mode, formulário de contato.', cta: 'Comprar NeuraPortfolio' },
          ],
        },
        {
          id: 'g-pt-09-competitor',
          name: 'Competidor',
          keywords: ['template portfolio desenvolvedor', 'template site portfolio', 'melhor template portfolio', 'template portfolio criativo', 'portfolio freelancer'],
          ads: [
            { id: 'g-pt-09-comp-1', headline: 'Template Portfolio — Cause Boa Impressão', description: 'NeuraPortfolio: animações lindas, design responsivo, dark mode. Melhor que temas genéricos.', cta: 'Ver Template' },
            { id: 'g-pt-09-comp-2', headline: 'Seu Portfolio Deve se Destacar', description: 'NeuraPortfolio: animações Framer Motion, design moderno, personalização completa. €29.', cta: 'Ver NeuraPortfolio' },
            { id: 'g-pt-09-comp-3', headline: 'Portfolio Desenvolvedor — Next.js 14', description: 'Construa seu portfolio com NeuraPortfolio. Rápido, lindo, implantável em minutos.', cta: 'Começar' },
          ],
        },
        {
          id: 'g-pt-09-generic',
          name: 'Genérico',
          keywords: ['site portfolio', 'construir portfolio', 'portfolio online', 'template site pessoal', 'template portfolio freelancer', 'portfolio showcase'],
          ads: [
            { id: 'g-pt-09-gen-1', headline: 'Construa Seu Portfolio Online — €29', description: 'NeuraPortfolio: template profissional com animações. Deploy em minutos.', cta: 'Começar a Construir' },
            { id: 'g-pt-09-gen-2', headline: 'Template Site Pessoal — Next.js 14', description: 'Template portfolio lindo. Dark mode, animações, responsivo. A partir de €29.', cta: 'Ver Templates' },
            { id: 'g-pt-09-gen-3', headline: 'Template Portfolio — Deploy Hoje', description: 'Portfolio profissional com design moderno. Framer Motion, dark mode. €29.', cta: 'Obter Portfolio' },
          ],
        },
      ],
    },
    // === Campanha 10: Construtor SaaS com IA ===
    {
      id: 'g-pt-10',
      name: 'Construtor SaaS com IA',
      objective: 'Capturar intenção de construção de SaaS com IA',
      budget: '€350/mês',
      adGroups: [
        {
          id: 'g-pt-10-brand',
          name: 'Brand',
          keywords: ['construtor saas ai empire', 'construir saas com ai empire', 'lançar ai empire', 'plataforma ai empire'],
          ads: [
            { id: 'g-pt-10-brand-1', headline: 'AI Empire — Construa Seu SaaS com IA', description: 'Templates + APIs de IA + Stripe + Autenticação. Tudo para construir e lançar um SaaS potencializado por IA.', cta: 'Começar a Construir' },
            { id: 'g-pt-10-brand-2', headline: 'AI Empire — Sua Plataforma SaaS com IA', description: 'Da ideia ao lançamento. Templates, APIs de IA, pagamentos, autenticação. Deploy em 24 horas.', cta: 'Lançar Agora' },
            { id: 'g-pt-10-brand-3', headline: 'AI Empire — Lance Seu SaaS Mais Rápido', description: 'Templates profissionais com integração de IA. Stripe, autenticação, painel administrativo. A partir de €19.', cta: 'Começar' },
          ],
        },
        {
          id: 'g-pt-10-competitor',
          name: 'Competidor',
          keywords: ['construir saas ia', 'construtor saas', 'template saas ia', 'plataforma saas ia', 'construir saas com ia', 'construtor produto ia'],
          ads: [
            { id: 'g-pt-10-comp-1', headline: 'Construa um SaaS com IA — Não do Zero', description: 'AI Empire: templates profissionais com APIs de IA integradas. Economize meses de desenvolvimento.', cta: 'Ver Templates' },
            { id: 'g-pt-10-comp-2', headline: 'Construtor SaaS com IA — Lance em Dias', description: 'Templates, APIs de IA, Stripe, autenticação. AI Empire: tudo que você precisa para lançar.', cta: 'Comparar Funcionalidades' },
            { id: 'g-pt-10-comp-3', headline: 'Seu SaaS com IA — Lance Esta Semana', description: 'Por que construir do zero? Templates AI Empire: deploy em 24 horas. Integração de IA incluída.', cta: 'Começar Grátis' },
          ],
        },
        {
          id: 'g-pt-10-generic',
          name: 'Genérico',
          keywords: ['template saas', 'construir saas', 'app saas', 'plataforma saas', 'template produto ia', 'ideias saas', 'lançar saas'],
          ads: [
            { id: 'g-pt-10-gen-1', headline: 'Construa um SaaS — Templates, IA, Pagamentos', description: 'Templates Next.js 14 com APIs de IA, Stripe, autenticação. A partir de €19. Deploy hoje.', cta: 'Começar' },
            { id: 'g-pt-10-gen-2', headline: 'Construtor SaaS — Tudo Incluído', description: 'Templates, integração de IA, pagamentos, painel administrativo. Kit SaaS completo. A partir de €19.', cta: 'Explorar Templates' },
            { id: 'g-pt-10-gen-3', headline: 'Lance Sua Ideia SaaS — Next.js 14', description: 'Templates profissionais com stack moderno. IA, Stripe, autenticação. Deploy em minutos.', cta: 'Começar a Construir' },
          ],
        },
      ],
    },
  ],
  facebook: [
    // Consciência de Marca (2)
    {
      id: 'fb-pt-01',
      name: 'Consciência de Marca AI Empire',
      type: 'awareness',
      objective: 'Aumentar a consciência de marca entre desenvolvedores e fundadores de startups',
      audience: 'Desenvolvedores, CTOs, fundadores de startups, 22-45 anos, interessados em IA, SaaS, Next.js, desenvolvimento web',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Audience Network'],
      adCopy: 'Está construindo um SaaS? AI Empire oferece templates Next.js 14, APIs de IA integradas (Groq + Gemini), faturamento Stripe e autenticação — tudo a partir de €19. Junte-se a mais de 5.000 desenvolvedores que lançaram mais rápido.',
      cta: 'Saiba Mais',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-pt-02',
      name: 'Proposta de Valor da API de IA',
      type: 'awareness',
      objective: 'Educar desenvolvedores sobre a API de IA unificada',
      audience: 'Desenvolvedores de software, engenheiros de ML, entusiastas de IA, 22-40 anos',
      placements: ['Feed do Facebook', 'Stories do Instagram', 'Reels'],
      adCopy: 'Uma API para Groq e Gemini. AI Empire fornece um endpoint unificado para múltiplos modelos de IA — grátis para começar, pague pelo que usar. Pare de gerenciar múltiplos SDKs de IA.',
      cta: 'Testar Grátis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    // Consideração (3)
    {
      id: 'fb-pt-03',
      name: 'Apresentação do Produto NeuraStore',
      type: 'consideration',
      objective: 'Impulsionar tráfego para a página do template NeuraStore',
      audience: 'Desenvolvedores de e-commerce, construtores de lojas online, usuários Shopify em busca de alternativas',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Marketplace'],
      adCopy: 'NeuraStore: template e-commerce completo construído com Next.js 14. Pagamentos Stripe, gerenciamento de carrinho, painel administrativo e recomendações de produto por IA. €29 — tenha sua loja, tenha seu código.',
      cta: 'Ver Template',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-pt-04',
      name: 'Oferta de Bundle de Templates',
      type: 'consideration',
      objective: 'Gerar interesse no bundle completo de templates',
      audience: 'Fundadores de SaaS, hackers indie, desenvolvedores full stack',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Marketplace do Facebook'],
      adCopy: 'Obtenha todos os 6 templates da AI Empire por €299. NeuraStore, NeuraBlog, NeuraPortfolio e mais 3. Suporte prioritário, atualizações gratuitas, tudo incluso. Economize mais de €400 comprando individualmente.',
      cta: 'Ver Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-pt-05',
      name: 'Tutorial de Integração de IA',
      type: 'consideration',
      objective: 'Engajar desenvolvedores com conteúdo educacional',
      audience: 'Desenvolvedores web, desenvolvedores React, desenvolvedores Node.js',
      placements: ['Feed do Facebook', 'Reels do Instagram', 'Stories'],
      adCopy: 'Adicione IA ao seu app Next.js em 5 minutos. O SDK da AI Empire torna a integração simples — uma chave de API, um endpoint. Tier gratuito com 100 créditos. Documentação e exemplos incluídos.',
      cta: 'Ler Documentação',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    // Conversão (3)
    {
      id: 'fb-pt-06',
      name: 'Inscrição na API Gratuita',
      type: 'conversion',
      objective: 'Impulsionar inscrições no tier gratuito',
      audience: 'Visitantes do site, leitores de documentação, leitores de blog, públicos similares',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Audience Network'],
      adCopy: 'Sua API de IA gratuita está esperando. Inscreva-se na AI Empire e obtenha 100 créditos para Groq e Gemini. Sem cartão de crédito. Comece a construir com IA hoje.',
      cta: 'Inscrever-se Grátis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-pt-07',
      name: 'Conversão de Compra de Template',
      type: 'conversion',
      objective: 'Converter visitantes de páginas de templates em compradores',
      audience: 'Visitantes de páginas de templates, abandonadores de carrinho, usuários de alta intenção',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Messenger'],
      adCopy: 'Ainda pensando? NeuraBlog (€19) e NeuraStore (€29) estão prontos para deploy. Stripe, autenticação, integração de IA incluídos. Garantia de reembolso de 100%.',
      cta: 'Comprar Agora',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-pt-08',
      name: 'Desconto de Bundle por Tempo Limitado',
      type: 'conversion',
      objective: 'Impulsionar compras de bundle com urgência',
      audience: 'Assinantes de e-mail, abandonadores de carrinho, usuários de alto engajamento',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Stories do Instagram'],
      adCopy: 'Oferta limitada: obtenha o bundle completo de templates da AI Empire por €299 (economize mais de €400). Inclui todos os 6 templates, suporte prioritário e atualizações gratuitas. A oferta termina em breve.',
      cta: 'Obter Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    // Retargeting (2)
    {
      id: 'fb-pt-09',
      name: 'Visitante de Volta — Templates',
      type: 'retargeting',
      objective: 'Reengajar visitantes que visualizaram templates sem comprar',
      audience: 'Visitantes de páginas de templates (7-30 dias), não completaram a compra',
      placements: ['Feed do Facebook', 'Feed do Instagram', 'Audience Network'],
      adCopy: 'Você estava olhando os templates da AI Empire. NeuraBlog começa a €19, NeuraStore a €29. Full stack, prontos para deploy, com IA integrada. Volte e lance seu SaaS.',
      cta: 'Ver Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-pt-10',
      name: 'Visitante de Volta — API',
      type: 'retargeting',
      objective: 'Reengajar visitantes que exploraram a documentação da API sem se inscrever',
      audience: 'Visitantes de páginas de documentação (7-30 dias), não criaram conta',
      placements: ['Feed do Facebook', 'Stories do Instagram', 'Reels'],
      adCopy: 'Você explorou nossa documentação de API. Pronto para construir? AI Empire oferece créditos gratuitos para Groq e Gemini. Inscreva-se em 30 segundos, sem cartão de crédito.',
      cta: 'Começar Grátis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    // Conteúdo Patrocinado (4)
    {
      id: 'li-pt-01',
      name: 'Anúncio de Lançamento SaaS',
      type: 'sponsored_content',
      objective: 'Gerar inscrições de decisores de tecnologia',
      audience: 'CTOs, tech leads, gerentes de engenharia em startups e PMEs',
      headline: 'Lance Seu SaaS 10x Mais Rápido com AI Empire',
      body: 'AI Empire fornece templates Next.js 14 com APIs de IA integradas (Groq + Gemini), faturamento Stripe e autenticação. Passe de ideia a SaaS implantado em 24 horas, não meses.\n\nO que está incluído:\n- 6 templates prontos para produção (€19-€299)\n- API de IA unificada com tier gratuito\n- Stripe + Autenticação configurados\n- Painel administrativo\n\nJunte-se a mais de 5.000 desenvolvedores construindo com AI Empire.',
      cta: 'Começar a Construir',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-pt-02',
      name: 'API de IA para Enterprise',
      type: 'sponsored_content',
      objective: 'Alcançar líderes de engenharia avaliando soluções de API de IA',
      audience: 'Gerentes de engenharia, VP Engineering, arquitetos em empresas mid-market e enterprise',
      headline: 'API de IA Unificada — Groq + Gemini para Sua Equipe',
      body: 'Pare de gerenciar múltiplos relacionamentos com fornecedores de IA. AI Empire fornece uma API para Groq e Gemini — com faturamento, rate limiting e monitoramento integrados.\n\nPor que equipes de engenharia escolhem AI Empire:\n- Um endpoint para múltiplos modelos de IA\n- SDKs para JavaScript e Python\n- Tier gratuito para prototipagem\n- Escalabilidade pay-as-you-go\n\nReduza a complexidade da sua integração de IA.',
      cta: 'Explorar API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-pt-03',
      name: 'Sucesso do Hacker Indie',
      type: 'sponsored_content',
      objective: 'Atrair hackers indie e fundadores solo',
      audience: 'Hackers indie, fundadores solo, fundadores de startups bootstrapped',
      headline: 'Lance Seu SaaS Este Fim de Semana',
      body: 'Construído para fundadores solo que querem se movimentar rápido.\n\nAI Empire oferece:\n- Templates Next.js 14 profissionais\n- APIs de IA prontas para uso\n- Faturamento Stripe em 5 minutos\n- Sem necessidade de código para o lançamento\n\nTemplates a partir de €19. Deploy na Vercel com um clique.\n\nPare de pensar demais. Comece a lançar.',
      cta: 'Ver Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-pt-04',
      name: 'Comparação de Custos',
      type: 'sponsored_content',
      objective: 'Atrair equipes que关注 custos comparando fornecedores de IA',
      audience: 'CTOs, líderes financeiros, compradores em startups e PMEs',
      headline: 'APIs de IA — 70% Menos que Concorrentes',
      body: 'AI Empire combina Groq e Gemini em uma API. Pague apenas pelo que usar.\n\nComparação:\n- OpenAI: €0.03/1K tokens (GPT-4)\n- AI Empire: ~€0.009/1K tokens (Groq Llama)\n\nTier gratuito incluso. Sem lock-in com fornecedor. Mude em minutos.\n\nMais de 5.000 desenvolvedores já estão economizando.',
      cta: 'Ver Preços',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    // Mensagens Patrocinadas (3)
    {
      id: 'li-pt-05',
      name: 'Contato Direto — CTOs',
      type: 'message_ads',
      objective: 'Contato personalizado com CTOs em empresas alvo',
      audience: 'CTOs em empresas com 10-200 funcionários em tech, SaaS e e-commerce',
      headline: 'Uma pergunta sobre seu stack de IA',
      body: 'Olá {{first_name}},\n\nNotei que a {{company}} está trabalhando com IA. Uma pergunta rápida: você está gerenciando APIs de IA de múltiplos fornecedores?\n\nAI Empire fornece uma API unificada para Groq e Gemini — um endpoint, uma fatura, um dashboard. Tier gratuito incluído.\n\nFaz sentido conversarmos por 10 minutos? Estou à disposição para mostrar como funciona.',
      cta: 'Agendar uma Conversa',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-pt-06',
      name: 'Contato Direto — Desenvolvedores',
      type: 'message_ads',
      objective: 'Engajar desenvolvedores individuais com ofertas personalizadas',
      audience: 'Desenvolvedores full stack, desenvolvedores React/Next.js em empresas tech',
      headline: 'Está desenvolvendo com Next.js?',
      body: 'Olá {{first_name}},\n\nVi que você trabalha com Next.js. Construímos a AI Empire especificamente para o ecossistema Next.js — templates com APIs de IA, Stripe e autenticação prontos para uso.\n\nSe você está trabalhando em um projeto pessoal ou ajudando sua equipe a lançar mais rápido, nosso tier gratuito pode ser útil.\n\nPosso compartilhar um código de desconto se você estiver interessado.',
      cta: 'Obter Código de Desconto',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-pt-07',
      name: 'Contato de Parceria',
      type: 'message_ads',
      objective: 'Explorar oportunidades de parceria com agências e consultorias',
      audience: 'Proprietários de agências, fundadores de consultorias, líderes de transformação digital',
      headline: 'Oportunidade de parceria para {{company}}',
      body: 'Olá {{first_name}},\n\nA AI Empire ajuda equipes a lançar produtos potencializados por IA mais rápido. Estamos construindo um programa de parceiros para agências e consultorias que recomendam nossos templates e APIs para clientes.\n\nBenefícios:\n- Revenue share em referrals\n- Suporte prioritário para seus clientes\n- Oportunidades de co-marketing\n\nVale a pena explorar?',
      cta: 'Saiba Sobre Parcerias',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    // Dinâmico (3)
    {
      id: 'li-pt-08',
      name: 'Dinâmico — Targeting por Título de Trabalho',
      type: 'dynamic',
      objective: 'Alcançar desenvolvedores por título de trabalho com anúncios personalizados',
      audience: 'Usuários com títulos: CTO, VP Engineering, Tech Lead, Senior Developer',
      headline: 'AI Empire para {{job_title}}s — Lance Mais Rápido',
      body: 'AI Empire oferece à {{company_name}} um caminho mais rápido para produção. Templates Next.js 14 com APIs de IA, Stripe e autenticação. Tier gratuito para prototipar, escalabilidade pay-as-you-go.',
      cta: 'Explorar AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-pt-09',
      name: 'Dinâmico — Tamanho da Empresa',
      type: 'dynamic',
      objective: 'Personalizar a mensagem pelo tamanho da empresa',
      audience: 'Empresas com 1-50 funcionários (startup) e 51-500 funcionários (growth)',
      headline: '{{company_name}} — Templates SaaS com IA',
      body: 'Para equipes em crescimento: AI Empire fornece templates Next.js 14 prontos para produção com integração de IA. Deploy em dias, não meses. A partir de €19.',
      cta: 'Ver Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-pt-10',
      name: 'Dinâmico — Targeting por Setor',
      type: 'dynamic',
      objective: 'Alcançar setores específicos com mensagens personalizadas',
      audience: 'E-commerce, SaaS e agências digitais',
      headline: 'Soluções de IA para {{industry}}',
      body: 'Os templates AI Empire são construídos para {{industry}}. Next.js 14, Stripe, APIs de IA e painéis administrativos. De €19 a €299 no bundle.',
      cta: 'Ver Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-pt-01',
      tweet: 'Construímos a AI Empire para que você não precisasse.\n\nTemplates Next.js 14 + APIs Groq e Gemini + Stripe + Autenticação — tudo em uma plataforma.\n\nGrátis para começar. Deploy em minutos.',
      cta: 'Testar Grátis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: 'Desenvolvedores, fundadores de startups',
    },
    {
      id: 'tw-pt-02',
      tweet: 'Opinião polêmica: construir um SaaS não deveria levar 6 meses.\n\nTemplates AI Empire: Next.js 14 profissionais, APIs de IA integradas, Stripe configurado.\n\nDa ideia ao deploy em 24 horas.',
      cta: 'Ver Templates',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: 'Hackers indie, fundadores solo',
    },
    {
      id: 'tw-pt-03',
      tweet: 'Uma API. Múltiplos modelos de IA. Tier gratuito.\n\nAI Empire: Groq para velocidade, Gemini para capacidade. Endpoint unificado.\n\nPare de gerenciar 5 SDKs de IA diferentes.',
      cta: 'Obter Chave de API',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'Desenvolvedores de IA, tech leads',
    },
    {
      id: 'tw-pt-04',
      tweet: 'NeuraStore: template e-commerce completo para Next.js 14.\n\nPagamentos Stripe ✓ Carrinho ✓ Painel admin ✓ Recomendações de IA ✓\n\n€29. Deploy na Vercel em minutos.',
      cta: 'Ver NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: 'Desenvolvedores de e-commerce',
    },
    {
      id: 'tw-pt-05',
      tweet: 'Comparamos preços do OpenAI vs AI Empire:\n\nMesma qualidade de resultados, 70% menor custo.\n\nGroq + Gemini por meio de uma API. Tier gratuito incluso. Sem lock-in.',
      cta: 'Comparar Preços',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: 'Desenvolvedores que关注 custos',
    },
    {
      id: 'tw-pt-06',
      tweet: 'Acabei de fazer deploy de um SaaS em 4 horas usando templates AI Empire.\n\nNext.js 14 + Stripe + Autenticação + APIs de IA. Tudo configurado. Basta adicionar seu código.',
      cta: 'Lançar Mais Rápido',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: 'Desenvolvedores, fundadores de startups',
    },
    {
      id: 'tw-pt-07',
      tweet: 'O bundle AI Empire: 6 templates, €299.\n\nNeuraStore, NeuraBlog, NeuraPortfolio + mais 3. Suporte prioritário. Atualizações gratuitas.\n\nEconomize mais de €400 comprando individualmente.',
      cta: 'Obter Bundle',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'Fundadores de SaaS, desenvolvedores',
    },
    {
      id: 'tw-pt-08',
      tweet: 'Cansado do WordPress?\n\nNeuraBlog: template blog Next.js 14. MDX, dark mode, RSS, otimizado para SEO. €19.\n\nRápido. Moderno. Seu.',
      cta: 'Ver NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: 'Blogueiros, criadores de conteúdo',
    },
    {
      id: 'tw-pt-09',
      tweet: 'Tier gratuito da AI Empire: 100 créditos para Groq + Gemini.\n\nSem cartão de crédito. Sem compromisso. Construa.\n\nSetup em 5 minutos. SDKs para JS e Python.',
      cta: 'Começar Grátis',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: 'Estudantes, desenvolvedores hobbistas',
    },
    {
      id: 'tw-pt-10',
      tweet: 'Seu portfolio merece algo melhor que um template HTML básico.\n\nNeuraPortfolio: Next.js 14, animações Framer Motion, dark mode, responsivo. €29.\n\nCause uma boa impressão.',
      cta: 'Ver Template Portfolio',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: 'Desenvolvedores, designers, freelancers',
    },
  ],
  instagram: [
    {
      id: 'ig-pt-01',
      name: 'Visão Geral da Plataforma Reel',
      type: 'reel',
      script: 'Cena 1: Gravação de tela do dashboard — texto "Conheça a AI Empire". Cena 2: Editor de código com chamada de API — "Uma API, Múltiplos Modelos". Cena 3: Checkout Stripe — "Pagamentos em 5 Minutos". Cena 4: Deploy ao vivo — "Implantado em 24 Horas". Cena 5: Logo + URL — "Comece Grátis Hoje".',
      visualDirection: 'Gravações de tela rápidas com transições suaves. UI dark mode. Cores roxas gradiente da marca. Música eletrônica animada.',
      textOverlay: 'AI Empire — Construa Seu SaaS Mais Rápido',
      cta: 'Link na Bio — Comece Grátis',
      duration: '15-30 segundos',
    },
    {
      id: 'ig-pt-02',
      name: 'Apresentação NeuraStore Story',
      type: 'story',
      script: 'Navegação pelo template NeuraStore. Mostrar grade de produtos, fluxo do carrinho, checkout Stripe, visual responsivo mobile. Terminar com tag de preço (€29) e CTA.',
      visualDirection: 'Fundos brancos/escuros limpos. Mockups de produtos em iPhone e MacBook. Animações de navegação suaves. Acentos roxos da marca.',
      textOverlay: 'NeuraStore — €29 — Template E-Commerce',
      cta: 'Deslize para Visualizar',
      duration: '15 segundos',
    },
    {
      id: 'ig-pt-03',
      name: 'Demo API de IA Reel',
      type: 'reel',
      script: 'Cena 1: Desenvolvedor digitando código — "Adicionando IA ao seu app". Cena 2: Terminal mostrando resposta da API — "Groq + Gemini em uma chamada". Cena 3: App rodando com funcionalidades de IA — "Integração em 5 minutos". Cena 4: Tela de preços — "Grátis para começar".',
      visualDirection: 'Filmagens por cima do ombro misturadas com gravações de tela. Tema escuro. Verde de terminal em preto. Cortes rápidos sincronizados com a música.',
      textOverlay: 'API de IA — Tier Gratuito Disponível',
      cta: 'Obtenha Sua Chave de API — Link na Bio',
      duration: '20-30 segundos',
    },
    {
      id: 'ig-pt-04',
      name: 'Bundle de Templates Story',
      type: 'story',
      script: 'Story em três quadros. Quadro 1: Todos os 6 templates em grade — "6 Templates. €299." Quadro 2: Destaques individuais dos templates — "NeuraStore, NeuraBlog, NeuraPortfolio..." Quadro 3: Destaque de economia — "Economize Mais de €400" com botão CTA.',
      visualDirection: 'Layout de grade de produtos. Cada template mostrado como mockup de dispositivo. Fundo gradiente roxo. Tipografia ousada.',
      textOverlay: 'Bundle Completo — €299 — Economize Mais de €400',
      cta: 'Obter o Bundle',
      duration: '15 segundos por quadro',
    },
    {
      id: 'ig-pt-05',
      name: 'Depoimento de Desenvolvedor Reel',
      type: 'reel',
      script: 'Cena 1: Selfie/vídeo do desenvolvedor — "Lancei meu SaaS em 2 dias com a AI Empire". Cena 2: Gravação de tela do app implantado. Cena 3: Trechos de código mostrando integração. Cena 4: Overlay de CTA.',
      visualDirection: 'Filmagem autêntica estilo UGC. Iluminação natural. Sensação de câmera handheld. Legendas para acessibilidade.',
      textOverlay: '"Lançado em 2 Dias" — @desenvolvedor',
      cta: 'Comece a Construir — Link na Bio',
      duration: '30 segundos',
    },
    {
      id: 'ig-pt-06',
      name: 'Funcionalidade NeuraBlog Story',
      type: 'story',
      script: 'Demonstração do NeuraBlog: editor MDX, alternância dark mode, visual mobile responsivo, pré-visualização do feed RSS, seção de comentários. Terminar com preço (€19) e CTA.',
      visualDirection: 'Gravação de tela com efeitos de zoom nas funcionalidades principais. Tela dividida mostrando claro/escuro. Estética limpa e minimalista.',
      textOverlay: 'NeuraBlog — €19 — Template Blog SEO',
      cta: 'Deslize — Ver Template',
      duration: '15 segundos',
    },
    {
      id: 'ig-pt-07',
      name: 'Desafio de Velocidade SaaS Reel',
      type: 'reel',
      script: 'Time-lapse da construção de um SaaS do zero. Overlay do timer de 0:00 a 4:00:00. Mostrar seleção de template, setup da API, configuração do Stripe, deploy. Terminar com URL ao vivo.',
      visualDirection: 'Tela dividida: timer à esquerda, gravação de tela à direita. Efeito de avanço rápido. Música de fundo energética. Marcadores de marcos em 1h, 2h, 3h.',
      textOverlay: 'SaaS Construído em 4 Horas',
      cta: 'Testar a AI Empire — Link na Bio',
      duration: '30-60 segundos',
    },
    {
      id: 'ig-pt-08',
      name: 'Anúncio de Tier Gratuito Story',
      type: 'story',
      script: 'Revelação de tipografia ousada: "GRÁTIS" → "API DE IA" → "100 CRÉDITOS" → "GROQ + GEMINI" → "SEM CARTÃO DE CRÉDITO" → CTA. Cada elemento de texto aparece com animação de quique ou deslize.',
      visualDirection: 'Fundos roxos/escuros sólidos. Texto branco grande e ousado. Design minimalista. Cada quadro transita com animação marcante.',
      textOverlay: 'API DE IA GRÁTIS — 100 Créditos — Sem Cartão',
      cta: 'Inscrever-se Grátis',
      duration: '10 segundos no total',
    },
    {
      id: 'ig-pt-09',
      name: 'Apresentação NeuraPortfolio Reel',
      type: 'reel',
      script: 'Demonstração das animações do NeuraPortfolio: parallax da seção hero, efeitos hover nos cards de projeto, transições suaves de página, dark mode. Tudo em um mockup MacBook.',
      visualDirection: 'Elegante, mockup de dispositivo em câmera lenta. Movimentos sutis de câmera. Iluminação suave. Música de fundo minimalista. Foco na qualidade das animações.',
      textOverlay: 'NeuraPortfolio — €29 — Portfolio de Desenvolvedor',
      cta: 'Link na Bio — Ver Demo',
      duration: '20-30 segundos',
    },
    {
      id: 'ig-pt-10',
      name: 'Carrossel de Comparação Story',
      type: 'story',
      script: 'Quadro 1: "Construir do zero: 3-6 meses" com ícone de calendário. Quadro 2: "Usando AI Empire: 1-2 dias" com ícone de foguete. Quadro 3: "Mesmo resultado. 95% menos tempo." Quadro 4: CTA com preços.',
      visualDirection: 'Layout de comparação lado a lado. Antes/depois. Vermelho para a opção "lenta", verde para AI Empire. Tipografia de impacto ousada.',
      textOverlay: '3 Meses vs 2 Dias — Escolha Rapidez',
      cta: 'Comece Agora — Link na Bio',
      duration: '15 segundos por quadro',
    },
  ],
};
