import type { AdCampaignBundle } from './types';

export const adCampaignBundle: AdCampaignBundle = {
  language: 'zh',
  googleSearch: [
    {
      id: 'g-zh-01',
      name: 'AI API 平台',
      objective: '推动 AI API 免费套餐注册',
      budget: '€500/月',
      adGroups: [
        {
          id: 'g-zh-01-brand',
          name: '品牌',
          keywords: ['ai empire', 'ai-empire', 'ai empire api', 'ai empire 平台'],
          ads: [
            { id: 'g-zh-01-brand-1', headline: 'AI Empire — 统一 AI API 平台', description: '通过一个 API 访问 Groq 和 Gemini。提供免费套餐，无需信用卡。5 分钟即可完成集成。', cta: '免费试用' },
            { id: 'g-zh-01-brand-2', headline: 'AI Empire — 您的 AI API 网关', description: '一个 API，多种 AI 模型。Groq + Gemini。注册即送免费额度。包含 JavaScript 和 Python SDK。', cta: '获取 API 密钥' },
            { id: 'g-zh-01-brand-3', headline: 'AI Empire — 立即构建 AI 应用', description: '生产就绪的 AI API。Groq 提供速度，Gemini 提供能力。免费套餐，按量付费。', cta: '开始使用' },
          ],
        },
        {
          id: 'g-zh-01-competitor',
          name: '竞争对手',
          keywords: ['openai 替代品', 'groq api 替代品', '更便宜的 ai api', 'gemini api 包装器', 'ai api 对比'],
          ads: [
            { id: 'g-zh-01-comp-1', headline: '经济实惠的 AI API — 比 OpenAI 更省钱', description: '同等质量的 AI，更低的成本。Groq + Gemini 统一。免费套餐含 100 额度。几分钟内切换。', cta: '比较价格' },
            { id: 'g-zh-01-comp-2', headline: 'OpenAI 替代方案 — AI Empire', description: '在寻找性价比更高的 AI API 吗？AI Empire 将 Groq 和 Gemini 结合在一个端点中。免费开始。', cta: '查看方案' },
            { id: 'g-zh-01-comp-3', headline: 'AI API — 比 OpenAI 便宜 70%', description: '使用 Groq 和 Gemini 获得 GPT 级别的结果。统一 API。免费套餐。无供应商锁定。', cta: '免费开始' },
          ],
        },
        {
          id: 'g-zh-01-generic',
          name: '通用',
          keywords: ['ai api', '人工智能 api', 'groq api', 'gemini api', '开发者 ai', '免费 ai api'],
          ads: [
            { id: 'g-zh-01-gen-1', headline: '开发者专用 AI API — 免费套餐', description: '通过一个 API 使用 Groq + Gemini。注册即送免费额度。文档、示例和 SDK 全部包含。', cta: '查看文档' },
            { id: 'g-zh-01-gen-2', headline: '为您的应用集成 AI — 5 分钟设置', description: 'Groq 和 Gemini 的统一 API。提供免费套餐。Stripe 计费。完整文档。', cta: '开始使用' },
            { id: 'g-zh-01-gen-3', headline: 'AI API — Groq 与 Gemini 结合', description: '多种 AI 模型的统一端点。免费开始，按使用量付费。生产就绪。', cta: '探索 API' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-02',
      name: 'Next.js SaaS 模板',
      objective: '推动模板销售',
      budget: '€400/月',
      adGroups: [
        {
          id: 'g-zh-02-brand',
          name: '品牌',
          keywords: ['ai empire 模板', 'ai empire saas', 'ai empire next.js', 'neurablog', 'neurastore'],
          ads: [
            { id: 'g-zh-02-brand-1', headline: 'AI Empire — Next.js 14 SaaS 模板', description: '集成 AI 的生产就绪模板。NeuraStore、NeuraBlog、NeuraPortfolio。€19 起。', cta: '查看模板' },
            { id: 'g-zh-02-brand-2', headline: 'NeuraStore 与 NeuraBlog by AI Empire', description: '内置 Stripe、认证和 AI 的专业 Next.js 14 模板。几分钟内即可部署。', cta: '查看模板' },
            { id: 'g-zh-02-brand-3', headline: 'AI Empire 模板 — 发布您的 SaaS', description: '6 款高级模板。Next.js 14、Tailwind、Stripe、AI API。€19 到 €299 套餐。', cta: '浏览模板' },
          ],
        },
        {
          id: 'g-zh-02-competitor',
          name: '竞争对手',
          keywords: ['saas 样板', 'next.js 模板', 'react saas 模板', 'saas 入门套件', 'nextjs 电商模板'],
          ads: [
            { id: 'g-zh-02-comp-1', headline: 'Next.js SaaS 模板 — 内置 AI', description: '与普通样板不同，AI Empire 模板包含 AI API、Stripe 和认证。可直接部署。', cta: '比较模板' },
            { id: 'g-zh-02-comp-2', headline: '超越 SaaS 样板', description: 'AI Empire 模板：专业设计、AI 集成、Stripe 计费。不仅仅是入门代码。', cta: '查看差异' },
            { id: 'g-zh-02-comp-3', headline: 'Next.js 14 模板 — 全栈就绪', description: '包含一切的模板：UI、API、认证、支付、AI。立即部署。', cta: '查看模板' },
          ],
        },
        {
          id: 'g-zh-02-generic',
          name: '通用',
          keywords: ['saas 模板', 'nextjs 14 模板', 'react 模板', 'saas 落地页', 'saas 用模板', '快速构建 saas'],
          ads: [
            { id: 'g-zh-02-gen-1', headline: 'SaaS 模板 — 数天发布，而非数月', description: '包含认证、Stripe、AI 和管理后台的 Next.js 14 模板。€19 起。', cta: '开始使用' },
            { id: 'g-zh-02-gen-2', headline: '使用 Next.js 14 构建 SaaS', description: '生产就绪模板。Stripe 计费、认证、AI API、管理面板。', cta: '探索模板' },
            { id: 'g-zh-02-gen-3', headline: 'Next.js 14 电商与博客模板', description: '现代设计的专业模板。响应式、暗黑模式、SEO 优化。€19 起。', cta: '选购模板' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-03',
      name: 'AI 集成',
      objective: '吸引需要 AI 集成的开发者',
      budget: '€350/月',
      adGroups: [
        {
          id: 'g-zh-03-brand',
          name: '品牌',
          keywords: ['ai empire 集成', 'ai empire 文档', 'ai empire sdk', 'ai empire api 文档'],
          ads: [
            { id: 'g-zh-03-brand-1', headline: 'AI Empire — 为任何应用添加 AI', description: '通过简单 API 为您的应用添加 AI 功能。Groq + Gemini。JS 和 Python SDK。', cta: '查看文档' },
            { id: 'g-zh-03-brand-2', headline: 'AI Empire SDK — 5 分钟集成 AI', description: '安装、配置、部署。我们的 SDK 让 AI 集成变得简单。提供免费套餐。', cta: '查看 SDK' },
            { id: 'g-zh-03-brand-3', headline: 'AI Empire API 文档 — 开始构建', description: '全面的文档、代码示例和教程。今天就为您的 Next.js 应用添加 AI。', cta: '查看文档' },
          ],
        },
        {
          id: 'g-zh-03-competitor',
          name: '竞争对手',
          keywords: ['ai 集成服务', '在应用中嵌入 ai', 'ai sdk', 'groq sdk', 'gemini sdk', 'ai api 包装器'],
          ads: [
            { id: 'g-zh-03-comp-1', headline: '比自定义构建更简单的 AI 集成', description: '停止维护多个 AI SDK。AI Empire：一个 API，多个模型。免费套餐。', cta: '立即简化' },
            { id: 'g-zh-03-comp-2', headline: 'AI 集成 — 无需复杂设置', description: '一个 API 密钥，一个端点。Groq 和 Gemini 即时可用。提供测试免费额度。文档包含。', cta: '免费试用' },
            { id: 'g-zh-03-comp-3', headline: '替代您的 AI API 包装器', description: 'AI Empire 提供生产就绪的统一 API。包含计费、速率限制和监控。', cta: '了解详情' },
          ],
        },
        {
          id: 'g-zh-03-generic',
          name: '通用',
          keywords: ['为应用添加 ai', '集成 ai', 'web 应用 ai api', 'groq 集成', 'gemini 集成', 'ai api rest'],
          ads: [
            { id: 'g-zh-03-gen-1', headline: '为您的 Web 应用添加 AI — 简单 REST API', description: 'Groq 和 Gemini 的 REST API。免费套餐。JSON 响应。适用于任何语言。', cta: '免费开始' },
            { id: 'g-zh-03-gen-2', headline: 'AI API 集成 — 开发者友好', description: '文档完善的 API，附带 JavaScript 和 Python SDK。免费套餐。按使用量付费。', cta: '查看文档' },
            { id: 'g-zh-03-gen-3', headline: 'Groq + Gemini API — 一个端点', description: '多种 AI 模型的单一 API。免费额度。Stripe 计费。生产就绪。', cta: '开始使用' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-04',
      name: 'SaaS 入门套件',
      objective: '转化 SaaS 创始人和独立开发者',
      budget: '€400/月',
      adGroups: [
        {
          id: 'g-zh-04-brand',
          name: '品牌',
          keywords: ['ai empire 入门', 'ai empire saas 套件', 'ai empire 套餐', 'neurastore', 'neurablog', 'neuraportfolio'],
          ads: [
            { id: 'g-zh-04-brand-1', headline: 'AI Empire — 完整 SaaS 入门套件', description: 'Next.js 14、Stripe、认证、AI API、管理后台。发布 SaaS 所需的一切。€19 起。', cta: '获取入门套件' },
            { id: 'g-zh-04-brand-2', headline: '使用 AI Empire 发布您的 SaaS', description: '6 款专业模板。Stripe 计费、认证、AI API。24 小时内部署。', cta: '查看模板' },
            { id: 'g-zh-04-brand-3', headline: 'AI Empire 套餐 — 全部模板', description: '6 款模板 + 优先支持 + 免费更新。完整 SaaS 入门套件 €299。', cta: '获取套餐' },
          ],
        },
        {
          id: 'g-zh-04-competitor',
          name: '竞争对手',
          keywords: ['saas 入门套件', 'saas 样板 nextjs', '独立开发者工具包', 'saas 全栈模板', '快速发布 saas'],
          ads: [
            { id: 'g-zh-04-comp-1', headline: 'SaaS 入门套件 — 超越样板', description: 'AI Empire 包含 AI API、管理后台和实际模板。不仅仅是入门代码。', cta: '比较功能' },
            { id: 'g-zh-04-comp-2', headline: '24 小时内发布您的 SaaS', description: '为什么要花几个月从头构建？AI Empire 模板：今天部署，明天迭代。', cta: '查看模板' },
            { id: 'g-zh-04-comp-3', headline: '独立开发者 SaaS 工具包', description: '您需要的一切：模板、AI API、Stripe、认证。€19 起。API 免费套餐。', cta: '开始构建' },
          ],
        },
        {
          id: 'g-zh-04-generic',
          name: '通用',
          keywords: ['saas 模板', '如何构建 saas', 'saas 应用模板', 'next.js saas', 'stripe saas 模板', 'saas mvp'],
          ads: [
            { id: 'g-zh-04-gen-1', headline: '数天构建 SaaS MVP', description: '包含 Stripe、认证和 AI 的 Next.js 14 模板。€19 起。部署到 Vercel。', cta: '开始使用' },
            { id: 'g-zh-04-gen-2', headline: 'SaaS 模板 — Stripe + 认证包含', description: '生产就绪的 Next.js 14 模板。支付、认证、AI API 内置。', cta: '探索模板' },
            { id: 'g-zh-04-gen-3', headline: '全栈 SaaS 模板 — Next.js 14', description: '现代技术栈：Next.js 14、Tailwind、Stripe、AI。€19 起。', cta: '查看模板' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-05',
      name: 'OpenAI 替代方案',
      objective: '捕获 OpenAI 比较流量',
      budget: '€300/月',
      adGroups: [
        {
          id: 'g-zh-05-brand',
          name: '品牌',
          keywords: ['ai empire vs openai', 'ai empire 替代品', 'ai empire 定价', '比 openai 更便宜'],
          ads: [
            { id: 'g-zh-05-brand-1', headline: 'AI Empire vs OpenAI — 同等质量，更低成本', description: '通过 AI Empire 使用 Groq 和 Gemini。统一 API 含免费套餐。比 OpenAI 节省最高 70%。', cta: '比较价格' },
            { id: 'g-zh-05-brand-2', headline: '为什么从 OpenAI 切换到 AI Empire', description: '更低成本、多模型、统一 API、免费套餐。几分钟内切换，无需更改代码。', cta: '查看价格' },
            { id: 'g-zh-05-brand-3', headline: 'AI Empire — 高性价比 AI API', description: 'Groq + Gemini。同等质量比 OpenAI 便宜 70%。注册即送免费额度。', cta: '免费开始' },
          ],
        },
        {
          id: 'g-zh-05-competitor',
          name: '竞争对手',
          keywords: ['openai 替代 api', '比 openai api 更便宜', 'openai 定价替代', 'groq vs openai', 'gemini vs gpt'],
          ads: [
            { id: 'g-zh-05-comp-1', headline: '更便宜的 OpenAI 替代方案 — 免费试用', description: 'AI Empire：统一 Groq + Gemini API。免费套餐，按量付费。比 OpenAI 便宜 70%。', cta: '免费试用' },
            { id: 'g-zh-05-comp-2', headline: 'Groq 和 Gemini API — 更高价值', description: '为什么要多付？Groq 提供速度，Gemini 提供能力。一个 API，更低成本。免费套餐。', cta: '查看方案' },
            { id: 'g-zh-05-comp-3', headline: '从 OpenAI 切换 — 节省 70%', description: 'AI Empire 通过一个 API 提供 Groq + Gemini。同等质量，极低成本。', cta: '立即比较' },
          ],
        },
        {
          id: 'g-zh-05-generic',
          name: '通用',
          keywords: ['ai api 定价', 'ai api 成本', 'groq 定价', 'gemini api 定价', 'ai api 对比', '最便宜的 ai api'],
          ads: [
            { id: 'g-zh-05-gen-1', headline: 'AI API — 从免费到按量付费', description: '免费开始，经济地扩展。Groq + Gemini。无月费。仅为使用量付费。', cta: '查看价格' },
            { id: 'g-zh-05-gen-2', headline: '经济实惠的 AI API — Groq + Gemini', description: '100 额度的免费套餐。之后按量付费。无最低消费，无锁定。', cta: '开始使用' },
            { id: 'g-zh-05-gen-3', headline: 'AI API 定价 — 透明公平', description: '无隐藏费用。通过一个 API 使用 Groq + Gemini。免费套餐。Stripe 计费。', cta: '查看价格' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-06',
      name: 'Vercel 模板替代方案',
      objective: '捕获模板比较流量',
      budget: '€250/月',
      adGroups: [
        {
          id: 'g-zh-06-brand',
          name: '品牌',
          keywords: ['ai empire vercel', 'ai empire 部署', 'ai empire next.js', 'ai empire 托管'],
          ads: [
            { id: 'g-zh-06-brand-1', headline: 'AI Empire 模板 — 部署到 Vercel', description: '为 Vercel 优化的 Next.js 14 模板。AI API、Stripe、认证。几分钟内部署。', cta: '立即部署' },
            { id: 'g-zh-06-brand-2', headline: 'Vercel 就绪的 SaaS 模板', description: 'AI Empire 模板：专为 Vercel 构建。一键部署。AI 集成、计费、认证。', cta: '查看模板' },
            { id: 'g-zh-06-brand-3', headline: 'Vercel 专用 Next.js 14 模板', description: '专业模板。几分钟内部署到 Vercel。AI API 和 Stripe 计费内置。', cta: '获取模板' },
          ],
        },
        {
          id: 'g-zh-06-competitor',
          name: '竞争对手',
          keywords: ['vercel 模板替代品', 'next.js 模板', '优于 vercel 模板', 'saas 模板 vercel', '模板 saas 部署'],
          ads: [
            { id: 'g-zh-06-comp-1', headline: '超越基础模板 — AI Empire', description: '与基础 Vercel 模板不同，AI Empire 包含 AI API、Stripe、管理后台。', cta: '查看功能' },
            { id: 'g-zh-06-comp-2', headline: '集成 AI 和 Stripe 的 Next.js 模板', description: 'AI Empire：不仅是模板，而是完整的 SaaS 入门套件。AI API、计费、认证。', cta: '比较' },
            { id: 'g-zh-06-comp-3', headline: '生产级 SaaS 模板 — Next.js 14', description: '超越演示模板。AI Empire：真实的认证、真实的支付、真实的 AI 集成。', cta: '查看模板' },
          ],
        },
        {
          id: 'g-zh-06-generic',
          name: '通用',
          keywords: ['next.js 部署模板', 'saas 模板 部署', 'vercel saas', 'nextjs 14 部署', 'saas 部署 模板', '模板 vercel 部署'],
          ads: [
            { id: 'g-zh-06-gen-1', headline: '今天就将您的 SaaS 部署到 Vercel', description: 'Next.js 14 模板。一键部署。AI、Stripe、认证。€19 起。', cta: '开始部署' },
            { id: 'g-zh-06-gen-2', headline: 'SaaS 模板 — 部署就绪', description: '专业 Next.js 14 模板。几分钟内部署到 Vercel。全栈包含。', cta: '开始使用' },
            { id: 'g-zh-06-gen-3', headline: 'Next.js 14 SaaS — 几分钟内部署', description: '包含一切的模板：认证、支付、AI、管理后台。即刻部署到 Vercel。', cta: '探索模板' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-07',
      name: '电商模板 — NeuraStore',
      objective: '推动 NeuraStore 模板销售',
      budget: '€300/月',
      adGroups: [
        {
          id: 'g-zh-07-brand',
          name: '品牌',
          keywords: ['neurastore', 'ai empire 电商', 'neurastore 模板', 'neurastore next.js'],
          ads: [
            { id: 'g-zh-07-brand-1', headline: 'NeuraStore — AI 驱动的电商模板', description: '内置 Stripe、购物车、管理后台的 Next.js 14 电商模板。AI 商品推荐。', cta: '查看 NeuraStore' },
            { id: 'g-zh-07-brand-2', headline: 'NeuraStore — 发布您的在线商店', description: '专业电商模板。Stripe 支付、库存管理、响应式设计。', cta: '查看演示' },
            { id: 'g-zh-07-brand-3', headline: 'NeuraStore by AI Empire — €29', description: '完整的电商模板。Next.js 14、Stripe、Tailwind。几分钟内部署。', cta: '购买 NeuraStore' },
          ],
        },
        {
          id: 'g-zh-07-competitor',
          name: '竞争对手',
          keywords: ['next.js 电商模板', '在线商店模板', 'shopify 替代模板', 'react 电商模板', 'nextjs 商店模板'],
          ads: [
            { id: 'g-zh-07-comp-1', headline: '电商模板 — 拥有您的商店', description: '与 Shopify 不同，NeuraStore 属于您。自托管、可定制、AI 驱动。€29。', cta: '获取 NeuraStore' },
            { id: 'g-zh-07-comp-2', headline: 'Next.js 电商 — 完全控制', description: 'NeuraStore：拥有您的代码、数据、商店。Stripe 集成、管理后台。', cta: '查看模板' },
            { id: 'g-zh-07-comp-3', headline: '构建您自己的在线商店', description: 'NeuraStore 模板：Next.js 14、Stripe、响应式设计、管理面板。€29。', cta: '开始构建' },
          ],
        },
        {
          id: 'g-zh-07-generic',
          name: '通用',
          keywords: ['电商网站模板', '在线商店模板', 'nextjs 电商', '构建在线商店', 'saas 电商模板', '数字商店模板'],
          ads: [
            { id: 'g-zh-07-gen-1', headline: '电商网站模板 — Next.js 14', description: '专业的在线商店模板。Stripe、购物车、管理后台。响应式、暗黑模式。€29。', cta: '选购模板' },
            { id: 'g-zh-07-gen-2', headline: '使用 Next.js 构建在线商店', description: 'NeuraStore：完整的电商解决方案。支付、库存、AI 推荐。', cta: '开始使用' },
            { id: 'g-zh-07-gen-3', headline: '在线商店模板 — 发布就绪', description: 'Next.js 14 电商模板。Stripe 计费、响应式设计、SEO 优化。€29。', cta: '立即部署' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-08',
      name: '博客模板 — NeuraBlog',
      objective: '推动 NeuraBlog 模板销售',
      budget: '€250/月',
      adGroups: [
        {
          id: 'g-zh-08-brand',
          name: '品牌',
          keywords: ['neurablog', 'ai empire 博客', 'neurablog 模板', 'neurablog next.js'],
          ads: [
            { id: 'g-zh-08-brand-1', headline: 'NeuraBlog — SEO 优化的博客模板', description: '内置 MDX、暗黑模式、RSS 订阅的 Next.js 14 博客模板。邮件订阅集成。', cta: '查看 NeuraBlog' },
            { id: 'g-zh-08-brand-2', headline: 'NeuraBlog — 几分钟创建专业博客', description: '高级博客模板。MDX 支持、SEO 优化、评论系统。€19。', cta: '查看演示' },
            { id: 'g-zh-08-brand-3', headline: 'NeuraBlog by AI Empire — €19', description: '完整的博客模板。Next.js 14、MDX、暗黑模式、RSS。部署到 Vercel。', cta: '购买 NeuraBlog' },
          ],
        },
        {
          id: 'g-zh-08-competitor',
          name: '竞争对手',
          keywords: ['next.js 博客模板', 'wordpress 替代品', 'ghost 替代品', 'mdx 博客模板', 'react 博客模板'],
          ads: [
            { id: 'g-zh-08-comp-1', headline: '博客模板 — 比 WordPress 更快', description: 'NeuraBlog：静态网站速度，动态功能。MDX、SEO、邮件订阅。€19。', cta: '试用 NeuraBlog' },
            { id: 'g-zh-08-comp-2', headline: 'MDX 博客模板 — Next.js 14', description: '与 Ghost 不同，NeuraBlog 给您完全的控制权。自托管、快速、可定制。', cta: '查看模板' },
            { id: 'g-zh-08-comp-3', headline: '您的博客，您的代码 — NeuraBlog', description: '拥有您的内容平台。NeuraBlog：Next.js 14、MDX、暗黑模式、RSS。€19。', cta: '获取 NeuraBlog' },
          ],
        },
        {
          id: 'g-zh-08-generic',
          name: '通用',
          keywords: ['博客模板', '个人博客模板', 'nextjs 博客', '技术博客模板', '开始写博客', '博客网站模板'],
          ads: [
            { id: 'g-zh-08-gen-1', headline: '博客模板 — 今天就开始写博客', description: '专业博客模板。SEO 优化、暗黑模式、邮件订阅。几分钟内部署。€19。', cta: '开始写博客' },
            { id: 'g-zh-08-gen-2', headline: 'Next.js 14 博客 — 快速且美观', description: 'NeuraBlog：现代博客模板。MDX、暗黑模式、RSS、评论系统。€19。', cta: '查看模板' },
            { id: 'g-zh-08-gen-3', headline: '创建专业博客 — €19', description: 'NeuraBlog 模板。SEO 优化、响应式、暗黑模式。部署到 Vercel。', cta: '开始使用' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-09',
      name: '作品集模板 — NeuraPortfolio',
      objective: '推动 NeuraPortfolio 模板销售',
      budget: '€200/月',
      adGroups: [
        {
          id: 'g-zh-09-brand',
          name: '品牌',
          keywords: ['neuraportfolio', 'ai empire 作品集', 'neuraportfolio 模板', '开发者作品集模板'],
          ads: [
            { id: 'g-zh-09-brand-1', headline: 'NeuraPortfolio — 开发者作品集模板', description: '包含动画、暗黑模式、联系表单的专业作品集。Next.js 14。€29。', cta: '查看 NeuraPortfolio' },
            { id: 'g-zh-09-brand-2', headline: 'NeuraPortfolio — 在线脱颖而出', description: '精美的作品集模板。Framer Motion 动画、响应式、暗黑模式。€29。', cta: '查看演示' },
            { id: 'g-zh-09-brand-3', headline: 'NeuraPortfolio by AI Empire — €29', description: '完整的作品集模板。Next.js 14、动画、暗黑模式、联系表单。', cta: '购买 NeuraPortfolio' },
          ],
        },
        {
          id: 'g-zh-09-competitor',
          name: '竞争对手',
          keywords: ['开发者作品集模板', '作品集网站模板', '最佳作品集模板', '创意作品集模板', '自由职业者作品集'],
          ads: [
            { id: 'g-zh-09-comp-1', headline: '作品集模板 — 留下深刻印象', description: 'NeuraPortfolio：精美动画、响应式设计、暗黑模式。优于通用主题。', cta: '查看模板' },
            { id: 'g-zh-09-comp-2', headline: '您的作品集应该脱颖而出', description: 'NeuraPortfolio：Framer Motion 动画、现代设计、完全定制。€29。', cta: '查看 NeuraPortfolio' },
            { id: 'g-zh-09-comp-3', headline: '开发者作品集 — Next.js 14', description: '使用 NeuraPortfolio 构建您的作品集。快速、美观、几分钟内部署。', cta: '开始使用' },
          ],
        },
        {
          id: 'g-zh-09-generic',
          name: '通用',
          keywords: ['作品集网站', '构建作品集', '在线作品集', '个人网站模板', '自由职业者作品集模板', '展示作品集'],
          ads: [
            { id: 'g-zh-09-gen-1', headline: '构建您的在线作品集 — €29', description: 'NeuraPortfolio：包含动画的专业模板。几分钟内部署。', cta: '开始构建' },
            { id: 'g-zh-09-gen-2', headline: '个人网站模板 — Next.js 14', description: '精美的作品集模板。暗黑模式、动画、响应式。€29 起。', cta: '查看模板' },
            { id: 'g-zh-09-gen-3', headline: '作品集模板 — 今天部署', description: '现代设计的专业作品集。Framer Motion、暗黑模式。€29。', cta: '获取作品集' },
          ],
        },
      ],
    },
    {
      id: 'g-zh-10',
      name: 'AI SaaS 构建器',
      objective: '捕获 AI SaaS 构建意图',
      budget: '€350/月',
      adGroups: [
        {
          id: 'g-zh-10-brand',
          name: '品牌',
          keywords: ['ai empire saas 构建器', 'ai empire 构建 saas', 'ai empire 发布', 'ai empire 平台'],
          ads: [
            { id: 'g-zh-10-brand-1', headline: 'AI Empire — 构建您的 AI SaaS', description: '模板 + AI API + Stripe + 认证。构建和发布 AI 驱动 SaaS 所需的一切。', cta: '开始构建' },
            { id: 'g-zh-10-brand-2', headline: 'AI Empire — 您的 AI SaaS 平台', description: '从想法到发布。模板、AI API、支付、认证。24 小时内部署。', cta: '立即发布' },
            { id: 'g-zh-10-brand-3', headline: 'AI Empire — 更快推出您的 SaaS', description: '集成 AI 的专业模板。Stripe、认证、管理后台。€19 起。', cta: '开始使用' },
          ],
        },
        {
          id: 'g-zh-10-competitor',
          name: '竞争对手',
          keywords: ['构建 ai saas', 'saas 构建器', 'ai saas 模板', 'saas ai 平台', '用 ai 构建 saas', 'ai 产品构建器'],
          ads: [
            { id: 'g-zh-10-comp-1', headline: '构建 AI SaaS — 无需从头开始', description: 'AI Empire：内置 AI API 的专业模板。节省数月开发时间。', cta: '查看模板' },
            { id: 'g-zh-10-comp-2', headline: 'AI SaaS 构建器 — 数天内发布', description: '模板、AI API、Stripe、认证。AI Empire：发布所需的一切。', cta: '比较功能' },
            { id: 'g-zh-10-comp-3', headline: '本周发布您的 AI SaaS', description: '为什么要从头构建？AI Empire 模板：24 小时内部署。AI 集成包含。', cta: '免费开始' },
          ],
        },
        {
          id: 'g-zh-10-generic',
          name: '通用',
          keywords: ['saas 模板', '构建 saas', 'saas 应用', 'saas 平台', 'ai 产品模板', 'saas 创意', '发布 saas'],
          ads: [
            { id: 'g-zh-10-gen-1', headline: '构建 SaaS — 模板、AI、支付', description: '包含 AI API、Stripe、认证的 Next.js 14 模板。€19 起。今天部署。', cta: '开始使用' },
            { id: 'g-zh-10-gen-2', headline: 'SaaS 构建器 — 一切包含', description: '模板、AI 集成、支付、管理后台。完整的 SaaS 工具包。€19 起。', cta: '探索模板' },
            { id: 'g-zh-10-gen-3', headline: '发布您的 SaaS 创意 — Next.js 14', description: '现代技术栈的专业模板。AI、Stripe、认证。几分钟内部署。', cta: '开始构建' },
          ],
        },
      ],
    },
  ],
  facebook: [
    {
      id: 'fb-zh-01',
      name: 'AI Empire 品牌认知',
      type: 'awareness',
      objective: '在开发者和初创创始人中提升品牌认知度',
      audience: '开发者、CTO、初创创始人，22-45 岁，对 AI、SaaS、Next.js、Web 开发感兴趣',
      placements: ['Facebook 动态', 'Instagram 动态', 'Audience Network'],
      adCopy: '正在构建 SaaS 吗？AI Empire 为您提供 Next.js 14 模板、内置 AI API（Groq + Gemini）、Stripe 计费和认证 — €19 起。已有 5,000+ 开发者更快地发布了产品。',
      cta: '了解更多',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=brand',
    },
    {
      id: 'fb-zh-02',
      name: 'AI API 价值主张',
      type: 'awareness',
      objective: '向开发者介绍统一 AI API',
      audience: '软件开发者、ML 工程师、AI 爱好者，22-40 岁',
      placements: ['Facebook 动态', 'Instagram 快拍', 'Reels'],
      adCopy: '一个 API 同时支持 Groq 和 Gemini。AI Empire 为多种 AI 模型提供统一端点 — 免费开始，按使用量付费。停止管理多个 AI SDK。',
      cta: '免费试用',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=api',
    },
    {
      id: 'fb-zh-03',
      name: 'NeuraStore 产品展示',
      type: 'consideration',
      objective: '将流量引导至 NeuraStore 模板页面',
      audience: '电商开发者、在线商店构建者、寻找替代方案的 Shopify 用户',
      placements: ['Facebook 动态', 'Instagram 动态', 'Marketplace'],
      adCopy: 'NeuraStore：使用 Next.js 14 构建的完整电商模板。Stripe 支付、购物车管理、管理后台、AI 商品推荐。€29 — 拥有您的商店，拥有您的代码。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=consideration&utm_campaign=neurastore',
    },
    {
      id: 'fb-zh-04',
      name: '模板套餐优惠',
      type: 'consideration',
      objective: '引起对完整模板套餐的兴趣',
      audience: 'SaaS 创始人、独立开发者、全栈开发者',
      placements: ['Facebook 动态', 'Instagram 动态', 'Facebook Marketplace'],
      adCopy: '€299 获取全部 6 款 AI Empire 模板。NeuraStore、NeuraBlog、NeuraPortfolio 加 3 款更多。优先支持、免费更新、全部包含。比单独购买节省 €400+。',
      cta: '查看套餐',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=consideration&utm_campaign=bundle',
    },
    {
      id: 'fb-zh-05',
      name: 'AI 集成教程',
      type: 'consideration',
      objective: '以教育内容吸引开发者参与',
      audience: 'Web 开发者、React 开发者、Node.js 开发者',
      placements: ['Facebook 动态', 'Instagram Reels', '快拍'],
      adCopy: '5 分钟为您的 Next.js 应用添加 AI。AI Empire 的 SDK 让集成变得简单 — 一个 API 密钥，一个端点。100 额度的免费套餐。文档和示例包含。',
      cta: '查看文档',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=consideration&utm_campaign=docs',
    },
    {
      id: 'fb-zh-06',
      name: '免费 API 注册',
      type: 'conversion',
      objective: '推动免费套餐注册',
      audience: '网站访客、文档读者、博客读者、相似受众',
      placements: ['Facebook 动态', 'Instagram 动态', 'Audience Network'],
      adCopy: '您的免费 AI API 正在等待。注册 AI Empire，获取 Groq 和 Gemini 的 100 额度。无需信用卡。今天就开始用 AI 构建。',
      cta: '免费注册',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=freesignup',
    },
    {
      id: 'fb-zh-07',
      name: '模板购买转化',
      type: 'conversion',
      objective: '将模板页面访客转化为购买者',
      audience: '模板页面访客、购物车放弃者、高意向用户',
      placements: ['Facebook 动态', 'Instagram 动态', 'Messenger'],
      adCopy: '还在考虑吗？NeuraBlog（€19）和 NeuraStore（€29）已准备部署。Stripe、认证、AI 集成包含。100% 退款保证。',
      cta: '立即购买',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=purchase',
    },
    {
      id: 'fb-zh-08',
      name: '限时套餐折扣',
      type: 'conversion',
      objective: '以紧迫感推动套餐购买',
      audience: '邮件订阅者、购物车放弃者、高互动用户',
      placements: ['Facebook 动态', 'Instagram 动态', 'Instagram 快拍'],
      adCopy: '限时优惠：€299 获取完整 AI Empire 模板套餐（节省 €400+）。包含全部 6 款模板、优先支持和免费更新。优惠即将结束。',
      cta: '获取套餐',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=conversion&utm_campaign=bundle_offer',
    },
    {
      id: 'fb-zh-09',
      name: '回访者 — 模板',
      type: 'retargeting',
      objective: '重新吸引查看了模板但未购买的访客',
      audience: '模板页面访客（7-30 天），未完成购买',
      placements: ['Facebook 动态', 'Instagram 动态', 'Audience Network'],
      adCopy: '您之前在浏览 AI Empire 模板。NeuraBlog €19 起，NeuraStore €29 起。全栈、部署就绪、AI 集成。回来发布您的 SaaS。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=template_return',
    },
    {
      id: 'fb-zh-10',
      name: '回访者 — API',
      type: 'retargeting',
      objective: '重新吸引查看了 API 文档但未注册的访客',
      audience: '文档页面访客（7-30 天），未创建账户',
      placements: ['Facebook 动态', 'Instagram 快拍', 'Reels'],
      adCopy: '您浏览了我们的 API 文档。准备好构建了吗？AI Empire 为您提供 Groq 和 Gemini 的免费额度。30 秒内注册，无需信用卡。',
      cta: '免费开始',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=api_return',
    },
  ],
  linkedin: [
    {
      id: 'li-zh-01',
      name: 'SaaS 发布公告',
      type: 'sponsored_content',
      objective: '从技术决策者获取注册',
      audience: '初创和中小企业的 CTO、技术负责人、工程经理',
      headline: '使用 AI Empire 将 SaaS 发布速度提升 10 倍',
      body: 'AI Empire 提供内置 AI API（Groq + Gemini）、Stripe 计费和认证的 Next.js 14 模板。不是几个月，而是 24 小时内将想法变为已部署的 SaaS。\n\n包含内容：\n- 6 款生产就绪模板（€19-€299）\n- 免费套餐的统一 AI API\n- Stripe + 认证已配置\n- 管理后台\n\n5,000+ 开发者正在使用 AI Empire 构建。',
      cta: '开始构建',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=launch',
    },
    {
      id: 'li-zh-02',
      name: '企业级 AI API',
      type: 'sponsored_content',
      objective: '触达评估 AI API 解决方案的工程领导者',
      audience: '中型和大型企业的工程经理、VP 工程、架构师',
      headline: '统一 AI API — 为您的团队提供 Groq + Gemini',
      body: '停止管理多个 AI 供应商关系。AI Empire 通过一个 API 提供 Groq 和 Gemini — 内置计费、速率限制和监控。\n\n工程团队选择 AI Empire 的原因：\n- 多种 AI 模型的单个端点\n- JavaScript 和 Python SDK\n- 原型设计免费套餐\n- 按使用量扩展\n\n降低 AI 集成的复杂性。',
      cta: '探索 API',
      ctaUrl: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=enterprise',
    },
    {
      id: 'li-zh-03',
      name: '独立开发者成功',
      type: 'sponsored_content',
      objective: '吸引独立开发者和独立创始人',
      audience: '独立开发者、独立创始人、自力更生的初创创始人',
      headline: '本周末就发布您的 SaaS',
      body: '为想要快速行动的独立创始人打造。\n\nAI Empire 为您提供：\n- 专业 Next.js 14 模板\n- 即用型 AI API\n- 5 分钟完成 Stripe 计费\n- 发布无需编码\n\n€19 起的模板。一键部署到 Vercel。\n\n停止过度思考。开始发布。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=indie',
    },
    {
      id: 'li-zh-04',
      name: '成本对比',
      type: 'sponsored_content',
      objective: '吸引关注成本的团队比较 AI 供应商',
      audience: '初创和中小企业的 CTO、财务负责人、采购部门',
      headline: 'AI API — 比竞争对手便宜 70%',
      body: 'AI Empire 通过一个 API 结合 Groq 和 Gemini。仅为使用量付费。\n\n对比：\n- OpenAI：每 1K token €0.03（GPT-4）\n- AI Empire：每 1K token 约 €0.009（Groq Llama）\n\n免费套餐包含。无供应商锁定。几分钟内切换。\n\n5,000+ 开发者已在节省。',
      cta: '查看价格',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=sponsored&utm_campaign=pricing',
    },
    {
      id: 'li-zh-05',
      name: 'CTO 直接外联',
      type: 'message_ads',
      objective: '对目标企业的 CTO 进行个性化外联',
      audience: '科技、SaaS 和电商领域 10-200 人规模企业的 CTO',
      headline: '关于您 AI 技术栈的简单问题',
      body: '您好 {{first_name}}，\n\n注意到 {{company}} 正在使用 AI。问一个简单的问题：您是否在管理多个 AI 供应商 API？\n\nAI Empire 通过一个统一 API 提供 Groq 和 Gemini — 一个端点、一份账单、一个仪表板。免费套餐包含。\n\n方便花 10 分钟聊聊吗？我很乐意为您详细介绍。',
      cta: '安排聊天',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=cto_outreach',
    },
    {
      id: 'li-zh-06',
      name: '开发者直接外联',
      type: 'message_ads',
      objective: '以个性化优惠吸引个人开发者',
      audience: '科技企业的全栈开发者、React/Next.js 开发者',
      headline: '使用 Next.js 构建吗？',
      body: '您好 {{first_name}}，\n\n看到您在使用 Next.js。我们专门为您这样的 Next.js 生态系统构建了 AI Empire — 内置 AI API、Stripe 和认证的模板。\n\n如果您在做个人项目或帮助团队更快发布，我们的免费套餐可能会有用。\n\n如果您感兴趣，我很乐意分享一个优惠码。',
      cta: '获取优惠码',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=dev_outreach',
    },
    {
      id: 'li-zh-07',
      name: '合作伙伴外联',
      type: 'message_ads',
      objective: '与代理机构和咨询公司探索合作机会',
      audience: '代理机构负责人、咨询公司创始人、数字化转型领导者',
      headline: '{{company}} 的合作机会',
      body: '您好 {{first_name}}，\n\nAI Empire 帮助团队更快发布 AI 驱动的产品。我们正在建立面向向客户推荐我们模板和 API 的代理机构和咨询公司的合作伙伴计划。\n\n优势：\n- 推荐收入分成\n- 客户优先支持\n- 联合营销机会\n\n值得探索吗？',
      cta: '了解合作',
      ctaUrl: 'https://ai-empire-steel.vercel.app/partners?utm_source=linkedin&utm_medium=message&utm_campaign=partnership',
    },
    {
      id: 'li-zh-08',
      name: '动态 — 职位定位',
      type: 'dynamic',
      objective: '按职位向开发者投放个性化广告',
      audience: '职位为 CTO、VP 工程、技术负责人、高级开发者的用户',
      headline: '面向 {{job_title}} 的 AI Empire — 更快发布',
      body: 'AI Empire 为 {{company_name}} 提供更快的生产路径。集成 AI API、Stripe 和认证的 Next.js 14 模板。原型设计免费套餐，按使用量扩展。',
      cta: '探索 AI Empire',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=title',
    },
    {
      id: 'li-zh-09',
      name: '动态 — 公司规模',
      type: 'dynamic',
      objective: '按公司规模定制消息',
      audience: '1-50 人（初创）和 51-500 人（成长期）规模的企业',
      headline: '{{company_name}} — AI SaaS 模板',
      body: '面向成长型团队：AI Empire 提供集成 AI 的生产就绪 Next.js 14 模板。数天内部署，而非数月。€19 起。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=company_size',
    },
    {
      id: 'li-zh-10',
      name: '动态 — 行业定位',
      type: 'dynamic',
      objective: '针对特定行业定制消息',
      audience: '电商、SaaS 和数字代理机构',
      headline: 'AI 驱动的 {{industry}} 解决方案',
      body: 'AI Empire 模板专为 {{industry}} 打造。Next.js 14、Stripe、AI API 和管理后台。€19 到 €299 套餐。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=dynamic&utm_campaign=industry',
    },
  ],
  twitter: [
    {
      id: 'tw-zh-01',
      tweet: '我们构建 AI Empire 是为了让您不必从零开始。\n\nNext.js 14 模板 + Groq 与 Gemini API + Stripe + 认证 — 一个平台搞定。\n\n免费开始。几分钟内部署。',
      cta: '免费试用',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=launch',
      targetAudience: '开发者、初创创始人',
    },
    {
      id: 'tw-zh-02',
      tweet: '说实话：构建 SaaS 不应该花 6 个月。\n\nAI Empire 模板：专业的 Next.js 14、内置 AI API、配置好的 Stripe。\n\n从想法到部署只需 24 小时。',
      cta: '查看模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=saas',
      targetAudience: '独立开发者、独立创始人',
    },
    {
      id: 'tw-zh-03',
      tweet: '一个 API。多个 AI 模型。免费套餐。\n\nAI Empire：速度型 Groq，能力型 Gemini。统一端点。\n\n停止管理 5 个不同的 AI SDK。',
      cta: '获取 API 密钥',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=api',
      targetAudience: 'AI 开发者、技术负责人',
    },
    {
      id: 'tw-zh-04',
      tweet: 'NeuraStore：Next.js 14 的完整电商模板。\n\nStripe 支付 ✓ 购物车 ✓ 管理后台 ✓ AI 推荐 ✓\n\n€29。几分钟内部署到 Vercel。',
      cta: '查看 NeuraStore',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=twitter&utm_medium=promoted&utm_campaign=neurastore',
      targetAudience: '电商开发者',
    },
    {
      id: 'tw-zh-05',
      tweet: '对比了 OpenAI 与 AI Empire 的定价：\n\n同等质量的结果，成本低 70%。\n\n通过一个 API 使用 Groq + Gemini。免费套餐包含。无供应商锁定。',
      cta: '比较价格',
      ctaUrl: 'https://ai-empire-steel.vercel.app/pricing?utm_source=twitter&utm_medium=promoted&utm_campaign=pricing',
      targetAudience: '关注成本的开发者',
    },
    {
      id: 'tw-zh-06',
      tweet: '使用 AI Empire 模板在 4 小时内部署了 SaaS。\n\nNext.js 14 + Stripe + 认证 + AI API。全部配置完毕。只需添加您的代码。',
      cta: '更快发布',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=speed',
      targetAudience: '开发者、初创创始人',
    },
    {
      id: 'tw-zh-07',
      tweet: 'AI Empire 套餐：6 款模板，€299。\n\nNeuraStore、NeuraBlog、NeuraPortfolio 加 3 款更多。优先支持。免费更新。\n\n比单独购买节省 €400+。',
      cta: '获取套餐',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates?utm_source=twitter&utm_medium=promoted&utm_campaign=bundle',
      targetAudience: 'SaaS 创始人、开发者',
    },
    {
      id: 'tw-zh-08',
      tweet: '受够了 WordPress？\n\nNeuraBlog：Next.js 14 博客模板。MDX、暗黑模式、RSS、SEO 优化。€19。\n\n快速。现代。属于您。',
      cta: '查看 NeuraBlog',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=twitter&utm_medium=promoted&utm_campaign=neurablog',
      targetAudience: '博主、内容创作者',
    },
    {
      id: 'tw-zh-09',
      tweet: 'AI Empire 免费套餐：Groq + Gemini 的 100 额度。\n\n无需信用卡。无承诺。直接构建。\n\n5 分钟设置。JS 和 Python SDK。',
      cta: '免费开始',
      ctaUrl: 'https://ai-empire-steel.vercel.app?utm_source=twitter&utm_medium=promoted&utm_campaign=freetier',
      targetAudience: '学生、爱好者开发者',
    },
    {
      id: 'tw-zh-10',
      tweet: '您的作品集值得比基础 HTML 模板更好的。\n\nNeuraPortfolio：Next.js 14、Framer Motion 动画、暗黑模式、响应式。€29。\n\n留下深刻印象。',
      cta: '查看作品集模板',
      ctaUrl: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=twitter&utm_medium=promoted&utm_campaign=portfolio',
      targetAudience: '开发者、设计师、自由职业者',
    },
  ],
  instagram: [
    {
      id: 'ig-zh-01',
      name: '平台概览 Reels',
      type: 'reel',
      script: '场景 1：仪表板屏幕录制 — "认识 AI Empire" 文字覆盖。场景 2：代码编辑器中的 API 调用 — "一个 API，多个模型"。场景 3：Stripe 结账 — "5 分钟完成支付设置"。场景 4：实时部署 — "24 小时内已部署"。场景 5：Logo + URL — "今天免费开始"。',
      visualDirection: '快速屏幕录制，流畅过渡。暗黑模式 UI。紫色渐变品牌色。轻快的电子背景音乐。',
      textOverlay: 'AI Empire — 更快构建您的 SaaS',
      cta: '简介链接 — 免费开始',
      duration: '15-30 秒',
    },
    {
      id: 'ig-zh-02',
      name: 'NeuraStore 展示快拍',
      type: 'story',
      script: 'NeuraStore 模板滑动展示。展示商品网格、购物车流程、Stripe 结账、移动响应式视图。以价格标签（€29）和 CTA 结尾。',
      visualDirection: '干净的白色/暗色背景。iPhone 和 MacBook 上的产品展示。流畅的滑动动画。品牌紫色点缀。',
      textOverlay: 'NeuraStore — €29 — 电商模板',
      cta: '向上滑动查看',
      duration: '15 秒',
    },
    {
      id: 'ig-zh-03',
      name: 'AI API 演示 Reels',
      type: 'reel',
      script: '场景 1：开发者输入代码 — "为您的应用添加 AI"。场景 2：终端显示 API 响应 — "一次调用同时获得 Groq + Gemini"。场景 3：运行 AI 功能的应用 — "5 分钟集成"。场景 4：定价页面 — "免费开始"。',
      visualDirection: '肩上拍摄的编码镜头与屏幕录制混合。暗色主题。黑色背景上的绿色终端。与音乐同步的快速剪辑。',
      textOverlay: 'AI API — 提供免费套餐',
      cta: '获取 API 密钥 — 简介链接',
      duration: '20-30 秒',
    },
    {
      id: 'ig-zh-04',
      name: '模板套餐快拍',
      type: 'story',
      script: '三帧快拍。帧 1：6 款模板网格展示 — "6 款模板。€299。"帧 2：各模板亮点 — "NeuraStore、NeuraBlog、NeuraPortfolio..."帧 3：省钱提示 — "节省 €400+"附 CTA 按钮。',
      visualDirection: '产品网格布局。每款模板以设备展示呈现。紫色渐变背景。粗体排版。',
      textOverlay: '完整套餐 — €299 — 节省 €400+',
      cta: '获取套餐',
      duration: '每帧 15 秒',
    },
    {
      id: 'ig-zh-05',
      name: '开发者推荐 Reels',
      type: 'reel',
      script: '场景 1：开发者自拍/视频 — "使用 AI Empire 在 2 天内发布了我的 SaaS"。场景 2：已部署应用的屏幕录制。场景 3：集成代码片段。场景 4：CTA 覆盖。',
      visualDirection: '真实的 UGC 风格素材。自然光。手持相机感。字幕确保无障碍访问。',
      textOverlay: '"2 天内发布" — @developer',
      cta: '开始构建 — 简介链接',
      duration: '30 秒',
    },
    {
      id: 'ig-zh-06',
      name: 'NeuraBlog 功能快拍',
      type: 'story',
      script: 'NeuraBlog 演示：MDX 编辑器、暗黑模式切换、响应式移动视图、RSS 订阅预览、评论区。以定价（€19）和 CTA 结尾。',
      visualDirection: '带缩放效果的屏幕录制，突出关键功能。分屏展示亮色/暗色模式。简洁、极简美学。',
      textOverlay: 'NeuraBlog — €19 — SEO 博客模板',
      cta: '向上滑动 — 查看模板',
      duration: '15 秒',
    },
    {
      id: 'ig-zh-07',
      name: 'SaaS 速度挑战 Reels',
      type: 'reel',
      script: '从零构建 SaaS 的延时摄影。从 0:00 到 4:00:00 的计时器覆盖。展示模板选择、API 设置、Stripe 配置、部署过程。以实际 URL 结尾。',
      visualDirection: '分屏：左侧计时器，右侧屏幕录制。快进效果。活力背景音乐。1 小时、2 小时、3 小时里程碑标记。',
      textOverlay: '4 小时构建了 SaaS',
      cta: '试用 AI Empire — 简介链接',
      duration: '30-60 秒',
    },
    {
      id: 'ig-zh-08',
      name: '免费套餐公告快拍',
      type: 'story',
      script: '粗体排版展示："免费" → "AI API" → "100 额度" → "Groq + Gemini" → "无需信用卡" → CTA。每个文字元素以弹跳或滑动效果入场。',
      visualDirection: '纯紫色/暗色背景。大号粗体白色文字。极简设计。每个画面以有力的动画过渡。',
      textOverlay: '免费 AI API — 100 额度 — 无需卡',
      cta: '免费注册',
      duration: '总计 10 秒',
    },
    {
      id: 'ig-zh-09',
      name: 'NeuraPortfolio 展示 Reels',
      type: 'reel',
      script: 'NeuraPortfolio 动画展示：英雄区域视差、项目卡片悬停效果、流畅页面过渡、暗黑模式。全部在 MacBook 展示中呈现。',
      visualDirection: '优雅的慢动作设备展示。微妙的相机移动。柔和灯光。极简背景音乐。聚焦动画质量。',
      textOverlay: 'NeuraPortfolio — €29 — 开发者作品集',
      cta: '简介链接 — 查看演示',
      duration: '20-30 秒',
    },
    {
      id: 'ig-zh-10',
      name: '对比轮播快拍',
      type: 'story',
      script: '帧 1："从零构建：3-6 个月"配日历图标。帧 2："使用 AI Empire：1-2 天"配火箭图标。帧 3："相同结果。节省 95% 时间。"帧 4：附定价的 CTA。',
      visualDirection: '并排对比布局。前后对比风格。"慢速"选项用红色，AI Empire 用绿色。有力的冲击排版。',
      textOverlay: '3 个月 vs 2 天 — 选择快速方案',
      cta: '立即开始 — 简介链接',
      duration: '每帧 15 秒',
    },
  ],
};
