import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-ar-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'SaaS لتحليل البيانات',
    teamSize: '4 مهندسين',
    challenge: 'كان على DataPulse إطلاق لوحة التحليلات المدعومة بالذكاء الاصطناعي خلال 6 أسابيع. كان الفريق يقضي 80% من وقت التطوير في المصادقة وتكامل فواتير Stripe ولوحة الإدارة من الصفر.',
    solution: 'اتبعوا قالب NeuraDashboard من AI Empire مع تكامل Groq AI المبني مسبقاً وفواتير Stripe والتحكم في الوصول القائم على الأدوار.',
    implementation: [
      { step: 1, title: 'الاستنساخ والتكوين', description: 'استنسخوا قالب NeuraDashboard و蚧ّوا متغيرات البيئة بمفتاح Groq API وبيانات Stripe.', duration: '2 ساعات' },
      { step: 2, title: 'تخصيص العلامة التجارية', description: 'حدّثوا نظام الألوان والشعار والخط ليتوافق مع هوية DataPulse.', duration: '1 يوم' },
      { step: 3, title: 'إضافة ميزات AI', description: 'دمجوا ميزة الاستعلام باللغة الطبيعية المدعومة بـ Groq في لوحة التحليلات عبر نقطة النهاية /api/chat.', duration: '2 يوم' },
      { step: 4, title: 'تكوين الفواتير', description: 'أقاموا ثلاث مستويات اشتراك باستخدام تكامل Stripe من القالب.', duration: '1 يوم' },
      { step: 5, title: 'النشر والإطلاق', description: 'نشروه على Vercel وصلّوا نطاق مخصص وأطلقوا النسخة التجريبية لأول 50 عميل.', duration: '1 يوم' },
    ],
    results: [
      { metric: 'وقت الإطلاق', before: '6 أسابيع (مقدر)', after: '8 أيام', improvement: 'أسرع بنسبة 85%' },
      { metric: 'تكلفة التطوير', before: '€12,000 (مقدر)', after: '€2,800', improvement: 'توفير 77%' },
      { metric: 'وقت استجابة API', before: 'غير متوفر', after: '180ms متوسط', improvement: 'جاهز للإنتاج' },
      { metric: 'الإيرادات الشهرية', before: '€0', after: '€4,200 MRR', improvement: '+€4,200/شهر' },
    ],
    testimonial: {
      quote: 'أطلقنا SaaS التحليلات بالـ AI في 8 أيام بدلاً من 6 أسابيع. تكامل Groq كان جاهزاً — أضفنا فقط تعليمات مخصصة للنطاق.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — لوحة الإدارة',
    timeToValue: '8 أيام',
  },
  agency: {
    id: 'cs-ar-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'وكالة رقمية',
    teamSize: '12 شخصاً',
    challenge: 'كان Bright Studio يبني حلول SaaS مخصصة للعملاء لكن كل مشروع تطلب 3-4 أسابيع لإعداد القوالب الجاهزة. المصادقة والفوائد وتكامل AI أعيد بناؤها من الصفر في كل مرة.',
    solution: 'قيّموا قوالب AI Empire كنقطة انطلاق لجميع المشاريع. NeuraSaaS للSaaS العام، NeuraStore للتجارة الإلكترونية، NeuraBlog للمحتوى.',
    implementation: [
      { step: 1, title: 'مكتبة القوالب', description: 'أنشأوا مكتبة داخلية مبنية على قوالب AI Empire مع تخصيصات الوكالة.', duration: '3 أيام' },
      { step: 2, title: 'عملية التأهيل', description: 'حددوا تدفقاً موحداً: اختيار القالب وتخصيص العلامة التجارية وتحديد النطاق.', duration: 'أسبوع' },
      { step: 3, title: 'تدريب الفريق', description: 'درّبوا جميع المطورين على أنماط قاعدة كود AI Empire.', duration: 'أسبوع' },
      { step: 4, title: 'أول مشروع عميل', description: 'سلّموا أول مشروع (لوحة تحكم SaaS) في 5 أيام باستخدام NeuraDashboard.', duration: '5 أيام' },
      { step: 5, title: 'التوسع', description: 'طبّقوا النهج القائم على القوالب على 6 مشاريع تالية مع أوقات تسليم متسقة.', duration: '3 أشهر' },
    ],
    results: [
      { metric: 'وقت التسليم', before: '6-8 أسابيع', after: '2-3 أسابيع', improvement: 'أسرع بنسبة 60%' },
      { metric: 'رضا العميل', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: 'الإيرادات الشهرية', before: '€25,000', after: '€42,000', improvement: '+68%' },
      { metric: 'المشاريع لكل ربع سنة', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'قلّص AI Empire وقت إعدادنا من 4 أسابيع إلى 3 أيام. نسلّم الآن مشاريع SaaS في 2-3 أسابيع بدلاً من 6-8.',
      author: 'Sophie Laurent',
      role: 'مديرة الوكالة, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: 'أسبوعان',
  },
  freelancer: {
    id: 'cs-ar-freelancer-01',
    company: 'Alex Rivera (مستقل)',
    companyType: 'freelancer',
    industry: 'تطوير الويب',
    teamSize: 'شخص واحد',
    challenge: 'كان Alex يبني MVP لـ SaaS للشركات الناشئة كمستقل. كل مشروع تطلب إعداد المصادقة والمدفوعات وميزات AI من الصفر، مستهلكاً 40% من الوقت.',
    solution: 'استخدم قوالب AI Empire كأساس لجميع MVP والمشاريع الشخصية. NeuraSaaS للعملاء وNeuraPortfolio للعلامة التجارية الشخصية.',
    implementation: [
      { step: 1, title: 'تقييم القالب', description: 'اختبر NeuraSaaS بالطبقة المجانية واستنسخه واستكشف قاعدة الكود.', duration: '2 ساعات' },
      { step: 2, title: 'إعداد مشروع العميل', description: 'استخدم NeuraSaaS كأساس لـ MVP أداة الكتابة بالـ AI لعميل.', duration: '3 أيام' },
      { step: 3, title: 'النشر', description: 'نشره على Vercel وأعد النطاق وسلّمه للعميل بالتوثيق.', duration: '1 يوم' },
      { step: 4, title: 'ملف شخصي', description: 'بنى ملف شخصي باستخدام قالب NeuraPortfolio.', duration: '1 يوم' },
      { step: 5, title: 'توسيع العمل الحر', description: 'تولى 3 عملاء إضافيين في الشهر التالي بالنهج القائم على القوالب.', duration: 'شهر' },
    ],
    results: [
      { metric: 'وقت تسليم MVP', before: '3-4 أسابيع', after: '5-7 أيام', improvement: 'أسرع بنسبة 75%' },
      { metric: 'الدخل الشهري', before: '€3,500', after: '€7,200', improvement: '+106%' },
      { metric: 'المشاريع لكل شهر', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'رضا العميل', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'كمطور مستقل، AI Empire يغيّر قواعد اللعبة. انتقلت من تسليم 2 MVP شهرياً إلى 4-5. تكامل Stripe وحده يوفر لي أسبوعاً لكل مشروع.',
      author: 'Alex Rivera',
      role: 'مطور Full-Stack مستقل',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5 أيام',
  },
  enterprise: {
    id: 'cs-ar-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'برمجيات المؤسسات',
    teamSize: '45 مهندساً',
    challenge: 'كان Meridian يبني أداة داخلية بالـ AI لفريق المبيعات. المشروع مقدر بـ 4 أشهر مع 6 مهندسين، مع حاجة للمصادقة وRBAC ومحادثة AI ولوحة تحليلات وStripe لتوزيع التكاليف الداخلية.',
    solution: 'اتبعوا NeuraSaaS كأساس. مصادقة مبنية مسبقاً مع RBAC وGroq AI للمحادثة وStripe لتتبع التكاليف.',
    implementation: [
      { step: 1, title: 'مراجعة الهيكل', description: 'راجعوا قاعدة الكود لمتطلبات المؤسسات: RBAC وتدقيق الوصول وتقييد المعدل.', duration: '3 أيام' },
      { step: 2, title: 'RBAC مخصص', description: 'وسّعوا نظام المصادقة بأدوار مخصصة: Admin وManager ومبيعات وقراءة فقط.', duration: 'أسبوع' },
      { step: 3, title: 'تكامل AI', description: 'دمجوا Groq AI لتحليل محادثات المبيعات وتقييم العملاء المحتملين وكتابة البريد الإلكتروني.', duration: '2 أسبوع' },
      { step: 4, title: 'فواتير داخلية', description: 'كوّنوا Stripe لتوزيع التكاليف الداخلية بين الأقسام مع تتبع الاستخدام.', duration: '3 أيام' },
      { step: 5, title: 'تجربة ونشر', description: 'تجربة مع 10 من فريق المبيعات لمدة أسبوعين، ثم النشر الكامل بعد جمع الملاحظات.', duration: '3 أسابيع' },
    ],
    results: [
      { metric: 'الوقت للإنتاج', before: '4 أشهر (مقدر)', after: '6 أسابيع', improvement: 'أسرع بنسبة 70%' },
      { metric: 'تكاليف الهندسة', before: '€80,000 (مقدر)', after: '€22,000', improvement: 'توفير 72%' },
      { metric: 'إنتاجية المبيعات', before: 'مرجع', after: '+35%', improvement: '+35%' },
      { metric: 'اعتماد ميزات AI', before: '0%', after: '89%', improvement: '89% اعتماد' },
    ],
    testimonial: {
      quote: 'وفر لنا AI Empire 3 أشهر من التطوير و€58,000 من تكاليف الهندسة. المصادقة وتكامل AI المبنيان مسبقاً مكّنوا الفريق من التركيز على منطق المنتج بدلاً من البنية التحتية.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — مجموعة SaaS الكاملة',
    timeToValue: '6 أسابيع',
  },
}
