import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-de-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'Daten-Analyse SaaS',
    teamSize: '4 Ingenieure',
    challenge: 'DataPulse musste sein KI-gestütztes Analytics-Dashboard innerhalb von 6 Wochen launchen. Das Team verbrachte 80% der Entwicklungszeit mit Authentifizierung, Stripe-Abrechnungsintegration und dem Aufbau des Admin-Panels von Grund auf.',
    solution: 'Übernahme des NeuraDashboard-Templates von AI Empire mit vorgebauter Groq-KI-Integration, Stripe-Abrechnung und rollenbasiertem Zugriff.',
    implementation: [
      { step: 1, title: 'Klonen und konfigurieren', description: 'NeuraDashboard Template geklont, Umgebungsvariablen mit Groq-API-Schlüssel und Stripe-Anmeldeinformationen konfiguriert.', duration: '2 Stunden' },
      { step: 2, title: 'Branding anpassen', description: 'Farbschema, Logo und Typografie an DataPulse-Markenidentität angepasst.', duration: '1 Tag' },
      { step: 3, title: 'KI-Funktionen hinzufügen', description: 'Groq-gestützte Natural-Language-Abfrage in das Analytics-Dashboard integriert.', duration: '2 Tage' },
      { step: 4, title: 'Abrechnung konfigurieren', description: 'Drei Abonnementstufen mit der Stripe-Integration des Templates eingerichtet.', duration: '1 Tag' },
      { step: 5, title: 'Bereitstellen und starten', description: 'Auf Vercel bereitgestellt, benutzerdefinierte Domain verbunden und Beta für die ersten 50 Kunden gestartet.', duration: '1 Tag' },
    ],
    results: [
      { metric: 'Markteinführungszeit', before: '6 Wochen (geschätzt)', after: '8 Tage', improvement: '85% schneller' },
      { metric: 'Entwicklungskosten', before: '€12.000 (geschätzt)', after: '€2.800', improvement: '77% Einsparung' },
      { metric: 'API-Antwortzeit', before: 'N/A', after: '180ms Durchschnitt', improvement: 'Produktionsreif' },
      { metric: 'Monatlicher Umsatz', before: '€0', after: '€4.200 MRR', improvement: '+€4.200/Monat' },
    ],
    testimonial: {
      quote: 'Wir haben unser KI-Analytics-SaaS in 8 Tagen statt 6 Wochen gestartet. Die Groq-Integration war bereits verkabelt — wir haben nur unsere domänenspezifischen Prompts hinzugefügt.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — Admin-Panel',
    timeToValue: '8 Tage',
  },
  agency: {
    id: 'cs-de-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'Digitale Agentur',
    teamSize: '12 Personen',
    challenge: 'Bright Studio baute individuelle SaaS-Lösungen, aber jedes Projekt erforderte 3-4 Wochen Boilerplate-Setup. Auth, Abrechnung und KI-Integration wurden jedes Mal neu gebaut.',
    solution: 'Standardisierung auf AI Empire Templates als Ausgangspunkt. NeuraSaaS für allgemeine SaaS, NeuraStore für E-Commerce, NeuraBlog für Inhalte.',
    implementation: [
      { step: 1, title: 'Template-Bibliothek', description: 'Interne Template-Bibliothek basierend auf AI Empire mit agenturspezifischen Anpassungen erstellt.', duration: '3 Tage' },
      { step: 2, title: 'Kunden-Onboarding', description: 'Standardisierter Kunden-Onboarding-Prozess definiert: Template-Auswahl, Branding, Funktionsumfang.', duration: '1 Woche' },
      { step: 3, title: 'Team-Schulung', description: 'Alle Entwickler an AI-Empire-Codebase-Muster geschult.', duration: '1 Woche' },
      { step: 4, title: 'Erstes Kundenprojekt', description: 'Erstes Kundenprojekt (SaaS-Dashboard) in 5 Tagen mit NeuraDashboard als Basis geliefert.', duration: '5 Tage' },
      { step: 5, title: 'Skalierung', description: 'Template-Ansatz auf 6 weitere Kundenprojekte mit konsistenten Lieferzeiten angewendet.', duration: '3 Monate' },
    ],
    results: [
      { metric: 'Projektlieferzeit', before: '6-8 Wochen', after: '2-3 Wochen', improvement: '60% schneller' },
      { metric: 'Kundenzufriedenheit', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: 'Monatsumsatz', before: '€25.000', after: '€42.000', improvement: '+68%' },
      { metric: 'Projekte pro Quartal', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empire hat unsere Projekt-Setup-Zeit von 4 Wochen auf 3 Tage reduziert. Wir liefern jetzt SaaS-Projekte in 2-3 Wochen statt 6-8.',
      author: 'Sophie Laurent',
      role: 'Agenturleiterin, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2 Wochen',
  },
  freelancer: {
    id: 'cs-de-freelancer-01',
    company: 'Alex Rivera (Freiberuflich)',
    companyType: 'freelancer',
    industry: 'Webentwicklung',
    teamSize: '1 Person',
    challenge: 'Alex baute als Solo-Entwickler SaaS-MVPs für Startups. Jedes Projekt erforderte Auth, Zahlungen und KI-Features von Grund auf — 40% des Projektzeitraums.',
    solution: 'AI Empire Templates als Basis für alle MVPs und persönlichen Projekte. NeuraSaaS für Kunden, NeuraPortfolio für persönliches Branding.',
    implementation: [
      { step: 1, title: 'Template-Bewertung', description: 'NeuraSaaS mit Free-Tier getestet, geklont, Codebase erkundet.', duration: '2 Stunden' },
      { step: 2, title: 'Kundenprojekt-Setup', description: 'NeuraSaaS als Basis für Kunden-MVP eines KI-Schreibwerkzeugs verwendet.', duration: '3 Tage' },
      { step: 3, title: 'Bereitstellung', description: 'Auf Vercel bereitgestellt, Domain eingerichtet und an Kunden übergeben.', duration: '1 Tag' },
      { step: 4, title: 'Persönliches Portfolio', description: 'Persönliche Portfolio-Site mit NeuraPortfolio erstellt.', duration: '1 Tag' },
      { step: 5, title: 'Skalierung', description: '3 zusätzliche Kunden im Folgemonat mit Template-Ansatz übernommen.', duration: '1 Monat' },
    ],
    results: [
      { metric: 'MVP-Lieferzeit', before: '3-4 Wochen', after: '5-7 Tage', improvement: '75% schneller' },
      { metric: 'Monatseinkommen', before: '€3.500', after: '€7.200', improvement: '+106%' },
      { metric: 'Projekte pro Monat', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'Kundenzufriedenheit', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'Als Solo-Entwickler ist AI Empire ein Game-Changer. Ich liefere jetzt 4-5 MVPs pro Monat statt 2. Die Stripe-Integration allein spart mir eine Woche pro Projekt.',
      author: 'Alex Rivera',
      role: 'Freiberuflicher Full-Stack-Entwickler',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5 Tage',
  },
  enterprise: {
    id: 'cs-de-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'Unternehmenssoftware',
    teamSize: '45 Ingenieure',
    challenge: 'Meridian baute ein internes KI-Tool für das Vertriebsteam. Das Projekt wurde auf 4 Monate mit 6 Ingenieuren geschätzt, mit Auth, RBAC, KI-Chat, Analytics und Stripe-Abrechnung für interne Kosten.',
    solution: 'NeuraSaaS als Basis übernommen. Vorgebautes Auth mit RBAC, Groq KI für Chat und Stripe für Kosten-Tracking.',
    implementation: [
      { step: 1, title: 'Architektur-Review', description: 'AI-Empire-Codebase auf Unternehmensanforderungen geprüft: RBAC, Audit-Logging, Rate Limiting.', duration: '3 Tage' },
      { step: 2, title: 'Benutzerdefiniertes RBAC', description: 'Auth-System mit benutzerdefinierten Rollen erweitert: Admin, Manager, Vertrieb, Nur-Lesen.', duration: '1 Woche' },
      { step: 3, title: 'KI-Integration', description: 'Groq KI für Verkaufsgesprächsanalyse, Lead-Scoring und E-Mail-Erstellung integriert.', duration: '2 Wochen' },
      { step: 4, title: 'Interne Abrechnung', description: 'Stripe für interne Kostenzuweisung zwischen Abteilungen konfiguriert.', duration: '3 Tage' },
      { step: 5, title: 'Pilot und Rollout', description: 'Pilot mit 10 Vertriebsmitarbeitern für 2 Wochen, Feedback gesammelt, dann vollständiger Rollout.', duration: '3 Wochen' },
    ],
    results: [
      { metric: 'Zeit bis Produktion', before: '4 Monate (geschätzt)', after: '6 Wochen', improvement: '70% schneller' },
      { metric: 'Ingenieurskosten', before: '€80.000 (geschätzt)', after: '€22.000', improvement: '72% Einsparung' },
      { metric: 'Vertriebsproduktivität', before: 'Basis', after: '+35%', improvement: '+35%' },
      { metric: 'KI-Funktions-Adoption', before: '0%', after: '89%', improvement: '89% Adoption' },
    ],
    testimonial: {
      quote: 'AI Empire hat uns 3 Monate Entwicklung und €58.000 Ingenieurskosten gespart. Die vorgebaute Auth und KI-Integration ermöglichten es dem Team, sich auf Produktlogik statt Infrastruktur zu konzentrieren.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — SaaS Komplett-Kit',
    timeToValue: '6 Wochen',
  },
}
