import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-es-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'SaaS de Analítica de Datos',
    teamSize: '4 ingenieros',
    challenge: 'DataPulse necesitaba lanzar su panel de analítica con IA en 6 semanas. Su equipo dedicaba el 80% del tiempo a autenticación, integración de facturación Stripe y construcción del panel de administración desde cero. La integración de la API de IA se estimaba en 3 semanas.',
    solution: 'Adoptaron el template NeuraDashboard de AI Empire con integración Groq AI pre-construida, facturación Stripe y control de acceso basado en roles.',
    implementation: [
      { step: 1, title: 'Clonar y configurar', description: 'Clonaron el template NeuraDashboard, configuraron variables de entorno con clave API Groq y credenciales Stripe.', duration: '2 horas' },
      { step: 2, title: 'Personalizar marca', description: 'Actualizaron esquema de colores, logo y tipografía para coincidentar con la marca DataPulse.', duration: '1 día' },
      { step: 3, title: 'Añadir funciones IA', description: 'Integraron consulta en lenguaje natural con Groq en el panel de analítica usando /api/chat pre-construido.', duration: '2 días' },
      { step: 4, title: 'Configurar facturación', description: 'Configuraron tres niveles de suscripción (Starter, Pro, Enterprise) con la integración Stripe del template.', duration: '1 día' },
      { step: 5, title: 'Desplegar y lanzar', description: 'Desplegaron en Vercel, conectaron dominio personalizado y lanzaron beta a los primeros 50 clientes.', duration: '1 día' },
    ],
    results: [
      { metric: 'Tiempo de lanzamiento', before: '6 semanas (estimado)', after: '8 días', improvement: '85% más rápido' },
      { metric: 'Coste de desarrollo', before: '€12,000 (estimado)', after: '€2,800', improvement: '77% de ahorro' },
      { metric: 'Tiempo de respuesta API', before: 'N/A', after: '180ms promedio', improvement: 'Listo para producción' },
      { metric: 'Ingresos mensuales', before: '€0', after: '€4,200 MRR', improvement: '+€4,200/mes' },
    ],
    testimonial: {
      quote: 'Lanzamos nuestro SaaS analítico con IA en 8 días en lugar de 6 semanas. La integración Groq ya estaba conectada — solo añadimos prompts específicos del dominio.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — Panel Admin',
    timeToValue: '8 días',
  },
  agency: {
    id: 'cs-es-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'Agencia Digital',
    teamSize: '12 personas',
    challenge: 'Bright Studio construía soluciones SaaS personalizadas pero cada proyecto requería 3-4 semanas de configuración de boilerplate. Auth, facturación e integración IA se reconstruían desde cero cada vez, reduciendo márgenes y retrasando entregas.',
    solution: 'Estandarizaron templates AI Empire como punto de partida para todos los proyectos. NeuraSaaS para SaaS general, NeuraStore para e-commerce, NeuraBlog para contenido.',
    implementation: [
      { step: 1, title: 'Biblioteca de templates', description: 'Crearon biblioteca interna de templates basada en AI Empire con personalizaciones de agencia.', duration: '3 días' },
      { step: 2, title: 'Proceso de onboarding', description: 'Definieron flujo estándar: selección de template, personalización de marca, alcance de funcionalidades.', duration: '1 semana' },
      { step: 3, title: 'Formación del equipo', description: 'Formaron a todos los desarrolladores en los patrones del codebase de AI Empire.', duration: '1 semana' },
      { step: 4, title: 'Primer proyecto cliente', description: 'Entregaron el primer proyecto (panel SaaS) en 5 días usando NeuraDashboard como base.', duration: '5 días' },
      { step: 5, title: 'Escalar proyectos', description: 'Aplicaron el enfoque a 6 proyectos de clientes con tiempos de entrega consistentes.', duration: '3 meses' },
    ],
    results: [
      { metric: 'Tiempo de entrega', before: '6-8 semanas', after: '2-3 semanas', improvement: '60% más rápido' },
      { metric: 'Satisfacción del cliente', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: 'Ingresos mensuales', before: '€25,000', after: '€42,000', improvement: '+68%' },
      { metric: 'Proyectos por trimestre', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empire redujo nuestro tiempo de configuración de 4 semanas a 3 días. Ahora entregamos proyectos SaaS en 2-3 semanas en lugar de 6-8.',
      author: 'Sophie Laurent',
      role: 'Directora de Agencia, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2 semanas',
  },
  freelancer: {
    id: 'cs-es-freelancer-01',
    company: 'Alex Rivera (Independiente)',
    companyType: 'freelancer',
    industry: 'Desarrollo Web',
    teamSize: '1 persona',
    challenge: 'Alex construía MVPs SaaS para startups como freelance. Cada proyecto requería configurar auth, pagos e IA desde cero, consumiendo 40% del tiempo y limitando clientes.',
    solution: 'Usó templates AI Empire como base para todos los MVPs y proyectos personales. NeuraSaaS para clientes SaaS, NeuraPortfolio para marca personal.',
    implementation: [
      { step: 1, title: 'Evaluación del template', description: 'Probó NeuraSaaS con tier gratuito, clonó, exploró el codebase y verificó funcionalidad Stripe y auth.', duration: '2 horas' },
      { step: 2, title: 'Configurar proyecto cliente', description: 'Usó NeuraSaaS como base para el MVP de herramienta de escritura IA de un cliente.', duration: '3 días' },
      { step: 3, title: 'Despliegue y entrega', description: 'Desplegó en Vercel, configuró dominio y entregó al cliente con documentación.', duration: '1 día' },
      { step: 4, title: 'Portfolio personal', description: 'Construyó sitio portfolio personal con NeuraPortfolio.', duration: '1 día' },
      { step: 5, title: 'Escalar freelance', description: 'Asumió 3 clientes adicionales el mes siguiente con enfoque basado en templates.', duration: '1 mes' },
    ],
    results: [
      { metric: 'Tiempo de entrega MVP', before: '3-4 semanas', after: '5-7 días', improvement: '75% más rápido' },
      { metric: 'Ingresos mensuales', before: '€3,500', after: '€7,200', improvement: '+106%' },
      { metric: 'Proyectos por mes', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'Satisfacción del cliente', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'Como desarrollador solo, AI Empire cambia las reglas. Pasé de 2 MVPs al mes a 4-5. La integración Stripe sola me ahorra una semana por proyecto.',
      author: 'Alex Rivera',
      role: 'Desarrollador Full-Stack Freelance',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5 días',
  },
  enterprise: {
    id: 'cs-es-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'Software Empresarial',
    teamSize: '45 ingenieros',
    challenge: 'Meridian construía una herramienta interna con IA para su equipo de ventas. El proyecto se estimaba en 4 meses con 6 ingenieros, necesitando auth, RBAC, chat IA, panel analítico y facturation Stripe para costes internos.',
    solution: 'Adoptaron NeuraSaaS como base. Usaron el auth pre-construido con RBAC, Groq AI para chat y Stripe para tracking de costes internos.',
    implementation: [
      { step: 1, title: 'Revisión de arquitectura', description: 'Revisaron el codebase para requisitos empresariales: RBAC, auditoría, rate limiting, aislamiento de datos.', duration: '3 días' },
      { step: 2, title: 'RBAC personalizado', description: 'Extendieron auth con roles: Admin, Manager, Comercial, Solo lectura. Aislamiento de datos por departamento.', duration: '1 semana' },
      { step: 3, title: 'Integración IA', description: 'Integraron Groq AI para análisis de conversaciones de ventas, scoring de leads y redacción de emails.', duration: '2 semanas' },
      { step: 4, title: 'Facturación interna', description: 'Configuraron Stripe para asignación de costes internos entre departamentos con reporting mensual.', duration: '3 días' },
      { step: 5, title: 'Piloto y despliegue', description: 'Piloto con 10 comerciales durante 2 semanas, recogida de feedback, ajustes y despliegue completo.', duration: '3 semanas' },
    ],
    results: [
      { metric: 'Tiempo a producción', before: '4 meses (estimado)', after: '6 semanas', improvement: '70% más rápido' },
      { metric: 'Coste de ingeniería', before: '€80,000 (estimado)', after: '€22,000', improvement: '72% de ahorro' },
      { metric: 'Productividad ventas', before: 'Referencia', after: '+35%', improvement: '+35%' },
      { metric: 'Adopción funciones IA', before: '0%', after: '89%', improvement: '89% adopción' },
    ],
    testimonial: {
      quote: 'AI Empire nos ahorró 3 meses de desarrollo y €58,000 en costes de ingeniería. El auth e integración IA pre-construidos permitieron al equipo enfocarse en lógica de producto.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — Kit Completo SaaS',
    timeToValue: '6 semanas',
  },
}
