import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-it-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'SaaS Analisi Dati',
    teamSize: '4 ingegneri',
    challenge: 'DataPulse doveva lanciare la sua dashboard analitica con AI entro 6 settimane. Il team dedicava l\'80% del tempo all\'autenticazione, integrazione fatturazione Stripe e costruzione del pannello admin da zero.',
    solution: 'Adottato il template NeuraDashboard di AI Empire con integrazione Groq AI pre-costruita, fatturazione Stripe e controllo accessi basato sui ruoli.',
    implementation: [
      { step: 1, title: 'Clonare e configurare', description: 'Clonato template NeuraDashboard, configurate variabili d\'ambiente con chiave API Groq e credenziali Stripe.', duration: '2 ore' },
      { step: 2, title: 'Personalizzare il brand', description: 'Aggiornato schema colori, logo e tipografia per corrispondere all\'identità DataPulse.', duration: '1 giorno' },
      { step: 3, title: 'Aggiungere funzionalità AI', description: 'Integrata funzionalità di query in linguaggio naturale con Groq nella dashboard analitica.', duration: '2 giorni' },
      { step: 4, title: 'Configurare fatturazione', description: 'Impostati tre livelli di abbonamento con l\'integrazione Stripe del template.', duration: '1 giorno' },
      { step: 5, title: 'Distribuire e lanciare', description: 'Distribuito su Vercel, connesso dominio personalizzato e lanciata beta ai primi 50 clienti.', duration: '1 giorno' },
    ],
    results: [
      { metric: 'Tempo di lancio', before: '6 settimane (stimato)', after: '8 giorni', improvement: '85% più veloce' },
      { metric: 'Costo sviluppo', before: '€12.000 (stimato)', after: '€2.800', improvement: '77% di risparmio' },
      { metric: 'Tempo di risposta API', before: 'N/A', after: '180ms medio', improvement: 'Pronto per produzione' },
      { metric: 'Entrate mensili', before: '€0', after: '€4.200 MRR', improvement: '+€4.200/mese' },
    ],
    testimonial: {
      quote: 'Abbiamo lanciato il nostro SaaS analitico con AI in 8 giorni invece di 6 settimane. L\'integrazione Groq era già collegata — abbiamo solo aggiunto i nostri prompt specifici.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — Pannello Admin',
    timeToValue: '8 giorni',
  },
  agency: {
    id: 'cs-it-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'Agenzia Digitale',
    teamSize: '12 persone',
    challenge: 'Bright Studio costruiva soluzioni SaaS personalizzate ma ogni progetto richiedeva 3-4 settimane di setup boilerplate. Auth, fatturazione e integrazione AI venivano ricostruite ogni volta.',
    solution: 'Standardizzati template AI Empire come punto di partenza. NeuraSaaS per SaaS generali, NeuraStore per e-commerce, NeuraBlog per contenuti.',
    implementation: [
      { step: 1, title: 'Libreria template', description: 'Creata libreria interna di template basata su AI Empire con personalizzazioni agenzia.', duration: '3 giorni' },
      { step: 2, title: 'Processo onboarding', description: 'Definito flusso standard: selezione template, personalizzazione brand, definizione scope.', duration: '1 settimana' },
      { step: 3, title: 'Formazione team', description: 'Formati tutti gli sviluppatori sui pattern del codebase AI Empire.', duration: '1 settimana' },
      { step: 4, title: 'Primo progetto cliente', description: 'Consegnato il primo progetto (dashboard SaaS) in 5 giorni con NeuraDashboard.', duration: '5 giorni' },
      { step: 5, title: 'Scalare i progetti', description: 'Applicato approccio a 6 progetti successivi con tempi di consegna costanti.', duration: '3 mesi' },
    ],
    results: [
      { metric: 'Tempo di consegna', before: '6-8 settimane', after: '2-3 settimane', improvement: '60% più veloce' },
      { metric: 'Soddisfazione cliente', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: 'Entrate mensili', before: '€25.000', after: '€42.000', improvement: '+68%' },
      { metric: 'Progetti per trimestre', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empire ha ridotto il nostro tempo di setup da 4 settimane a 3 giorni. Ora consegniamo progetti SaaS in 2-3 settimane invece di 6-8.',
      author: 'Sophie Laurent',
      role: 'Direttrice Agenzia, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2 settimane',
  },
  freelancer: {
    id: 'cs-it-freelancer-01',
    company: 'Alex Rivera (Indipendente)',
    companyType: 'freelancer',
    industry: 'Sviluppo Web',
    teamSize: '1 persona',
    challenge: 'Alex costruiva MVP SaaS per startup come freelance. Ogni progetto richiedeva di configurare auth, pagamenti e funzionalità AI da zero, consumando il 40% del tempo.',
    solution: 'Usati template AI Empire come base per tutti gli MVP e progetti personali. NeuraSaaS per clienti, NeuraPortfolio per personal branding.',
    implementation: [
      { step: 1, title: 'Valutazione template', description: 'Testato NeuraSaaS con tier gratuito, clonato, esplorato codebase.', duration: '2 ore' },
      { step: 2, title: 'Setup progetto cliente', description: 'Usato NeuraSaaS come base per MVP strumento di scrittura AI di un cliente.', duration: '3 giorni' },
      { step: 3, title: 'Distribuzione', description: 'Distribuito su Vercel, configurato dominio e consegnato al cliente.', duration: '1 giorno' },
      { step: 4, title: 'Portfolio personale', description: 'Costruito sito portfolio personale con NeuraPortfolio.', duration: '1 giorno' },
      { step: 5, title: 'Scalare freelance', description: 'Assunti 3 clienti aggiuntivi il mese seguente.', duration: '1 mese' },
    ],
    results: [
      { metric: 'Tempo consegna MVP', before: '3-4 settimane', after: '5-7 giorni', improvement: '75% più veloce' },
      { metric: 'Entrate mensili', before: '€3.500', after: '€7.200', improvement: '+106%' },
      { metric: 'Progetti per mese', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'Soddisfazione cliente', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'Come sviluppatore solo, AI Empire è un game-changer. Sono passato da 2 MVP al mese a 4-5. L\'integrazione Stripe da sola mi fa risparmiare una settimana per progetto.',
      author: 'Alex Rivera',
      role: 'Sviluppatore Full-Stack Freelance',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5 giorni',
  },
  enterprise: {
    id: 'cs-it-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'Software Enterprise',
    teamSize: '45 ingegneri',
    challenge: 'Meridian costruiva un tool interno con AI per il team vendite. Il progetto era stimato in 4 mesi con 6 ingegneri, con auth, RBAC, chat AI, dashboard analitica e Stripe per costi interni.',
    solution: 'Adottato NeuraSaaS come base. Auth pre-costruito con RBAC, Groq AI per chat e Stripe per il tracking dei costi.',
    implementation: [
      { step: 1, title: 'Review architettura', description: 'Revisionato codebase per requisiti enterprise: RBAC, audit logging, rate limiting.', duration: '3 giorni' },
      { step: 2, title: 'RBAC personalizzato', description: 'Esteso sistema auth con ruoli personalizzati: Admin, Manager, Vendite, Sola lettura.', duration: '1 settimana' },
      { step: 3, title: 'Integrazione AI', description: 'Integrato Groq AI per analisi conversazioni vendite, scoring lead e redazione email.', duration: '2 settimane' },
      { step: 4, title: 'Fatturazione interna', description: 'Configurato Stripe per allocazione costi interni tra dipartimenti.', duration: '3 giorni' },
      { step: 5, title: 'Pilota e rollout', description: 'Pilota con 10 venditori per 2 settimane, raccolta feedback, poi rollout completo.', duration: '3 settimane' },
    ],
    results: [
      { metric: 'Tempo a produzione', before: '4 mesi (stimato)', after: '6 settimane', improvement: '70% più veloce' },
      { metric: 'Costi ingegneria', before: '€80.000 (stimato)', after: '€22.000', improvement: '72% risparmio' },
      { metric: 'Produttività vendite', before: 'Base', after: '+35%', improvement: '+35%' },
      { metric: 'Adozione funzionalità AI', before: '0%', after: '89%', improvement: '89% adozione' },
    ],
    testimonial: {
      quote: 'AI Empire ci ha fatto risparmiare 3 mesi di sviluppo e €58.000 di costi ingegneria. Auth e integrazione AI pre-costruiti hanno permesso al team di concentrarsi sulla logica di prodotto.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — Kit Completo SaaS',
    timeToValue: '6 settimane',
  },
}
