import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-ja-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'データ分析SaaS',
    teamSize: '4名のエンジニア',
    challenge: 'DataPulseは6週間以内にAI搭載の分析ダッシュボードをローンチする必要がありました。チームは開発時間の80%を認証、Stripe決済統合、管理パネルのゼロからの構築に費やしていました。',
    solution: 'AI EmpireのNeuraDashboardテンプレートを採用。事前構築されたGroq AI統合、Stripe決済、ロールベースのアクセス制御を活用。',
    implementation: [
      { step: 1, title: 'クローンと設定', description: 'NeuraDashboardテンプレートをクローン、Groq APIキーとStripe認証情報で環境変数を設定。', duration: '2時間' },
      { step: 2, title: 'ブランディング', description: 'DataPulseのブランドアイデンティティに合わせてカラースキーム、ロゴ、タイポグラフィを更新。', duration: '1日' },
      { step: 3, title: 'AI機能の追加', description: 'Groq搭載の自然言語クエリ機能を /api/chat エンドポイントで分析ダッシュボードに統合。', duration: '2日' },
      { step: 4, title: '決済設定', description: 'テンプレートのStripe統合で3つのサブスクリプション階層（Starter、Pro、Enterprise）を設定。', duration: '1日' },
      { step: 5, title: 'デプロイとローンチ', description: 'Vercelにデプロイ、カスタムドメイン接続、最初の50人の顧客にベータ版をローンチ。', duration: '1日' },
    ],
    results: [
      { metric: 'ローンチまでの時間', before: '6週間（推定）', after: '8日', improvement: '85%高速化' },
      { metric: '開発コスト', before: '€12,000（推定）', after: '€2,800', improvement: '77%節約' },
      { metric: 'API応答時間', before: 'N/A', after: '平均180ms', improvement: '本番環境対応' },
      { metric: '月間収益', before: '€0', after: '€4,200 MRR', improvement: '+€4,200/月' },
    ],
    testimonial: {
      quote: 'AI分析SaaSを6週間ではなく8日でローンチしました。Groq統合は既に接続済み — ドメイン固有のプロンプトを追加するだけでした。',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — 管理パネル',
    timeToValue: '8日',
  },
  agency: {
    id: 'cs-ja-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'デジタルエージェンシー',
    teamSize: '12名',
    challenge: 'Bright Studioはクライアント向けにカスタムSaaSソリューションを構築していましたが、各プロジェクトに3-4週間のボイラープレートセットアップが必要でした。',
    solution: 'AI Empireテンプレートを全クライアントプロジェクトの出発点として標準化。汎用SaaSにNeuraSaaS、EコマースにNeuraStore、コンテンツにNeuraBlogを使用。',
    implementation: [
      { step: 1, title: 'テンプレートライブラリ', description: 'AI Empireテンプレートをベースに、エージェンシー固有のカスタマイズを加えた内部テンプレートライブラリを作成。', duration: '3日' },
      { step: 2, title: 'クライアントオンボーディング', description: '標準化されたフローを定義：テンプレート選択、ブランディングカスタマイズ、機能範囲の決定。', duration: '1週間' },
      { step: 3, title: 'チーム研修', description: '全開発者をAI Empireのコードベースパターンについて研修。', duration: '1週間' },
      { step: 4, title: '最初のクライアントプロジェクト', description: 'NeuraDashboardをベースに最初のプロジェクト（SaaSダッシュボード）を5日で納品。', duration: '5日' },
      { step: 5, title: 'スケール', description: 'テンプレートアプローチを6つの後続クライアントプロジェクトに適用。', duration: '3ヶ月' },
    ],
    results: [
      { metric: '納品時間', before: '6-8週間', after: '2-3週間', improvement: '60%高速化' },
      { metric: 'クライアント満足度', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: '月間収益', before: '€25,000', after: '€42,000', improvement: '+68%' },
      { metric: '四半期ごとのプロジェクト', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empireはプロジェクトセットアップ時間を4週間から3日に短縮しました。現在SaaSプロジェクトを2-3週間で納品しています。',
      author: 'Sophie Laurent',
      role: 'エージェンシー director, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2週間',
  },
  freelancer: {
    id: 'cs-ja-freelancer-01',
    company: 'Alex Rivera（個人事業主）',
    companyType: 'freelancer',
    industry: 'ウェブ開発',
    teamSize: '1名',
    challenge: 'Alexはフリーランスとしてスタートアップ向けにSaaS MVPを構築していました。各プロジェクトで認証、決済、AI機能をゼロから構築する必要があり、プロジェクト時間の40%を消費していました。',
    solution: '全クライアントMVPと個人プロジェクトの基盤としてAI Empireテンプレートを使用。クライアント向けにNeuraSaaS、パーソナルブランディングにNeuraPortfolio。',
    implementation: [
      { step: 1, title: 'テンプレート評価', description: 'Free tierでNeuraSaaSをテスト、クローン、コードベースを探索。', duration: '2時間' },
      { step: 2, title: 'クライアントプロジェクト設定', description: 'クライアントのAIライティングツールMVPの基盤としてNeuraSaaSを使用。', duration: '3日' },
      { step: 3, title: 'デプロイと納品', description: 'Vercelにデプロイ、ドメイン設定、クライアントにドキュメント付きで納品。', duration: '1日' },
      { step: 4, title: 'パーソナルポートフォリオ', description: 'NeuraPortfolioテンプレートでパーソナルポートフォリオサイトを構築。', duration: '1日' },
      { step: 5, title: 'フリーランスのスケール', description: '翌月にテンプレートアプローチで追加3クライアントを獲得。', duration: '1ヶ月' },
    ],
    results: [
      { metric: 'MVP納品時間', before: '3-4週間', after: '5-7日', improvement: '75%高速化' },
      { metric: '月間収入', before: '€3,500', after: '€7,200', improvement: '+106%' },
      { metric: '月間プロジェクト数', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'クライアント満足度', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'ソロ開発者として、AI Empireはゲームチェンジャーです。月2個のMVPから4-5個に増えました。Stripe統合だけでプロジェクト1つあたり1週間節約できます。',
      author: 'Alex Rivera',
      role: 'フリーランスフルスタック開発者',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5日',
  },
  enterprise: {
    id: 'cs-ja-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'エンタープライズソフトウェア',
    teamSize: '45名のエンジニア',
    challenge: 'Meridianは営業チーム向けの社内AIツールを構築していました。6名のエンジニアで4ヶ月のプロジェクト。認証、RBAC、AIチャット、分析ダッシュボード、社内コスト分配用のStripe決済が必要でした。',
    solution: 'NeuraSaaSを基盤として採用。事前構築されたRBAC付き認証、チャット用Groq AI、コスト追跡用Stripeを活用。',
    implementation: [
      { step: 1, title: 'アーキテクチャレビュー', description: 'AI Empireコードベースをエンタープライズ要件でレビュー：RBAC、監査ログ、レート制限、データ分離。', duration: '3日' },
      { step: 2, title: 'カスタムRBAC設定', description: 'テンプレートの認証システムにカスタムロールを追加：Admin、Manager、営業、読み取り専用。', duration: '1週間' },
      { step: 3, title: 'AI機能統合', description: 'Groq AIを営業会話分析、リードスコアリング、メール作成に統合。API経由で社内CRMに接続。', duration: '2週間' },
      { step: 4, title: '社内決済設定', description: '部門間の社内コスト分配用にStripeを設定。使用量追跡と月次レポートを実装。', duration: '3日' },
      { step: 5, title: 'パイロットと展開', description: '10名の営業担当者で2週間パイロット。フィードバック収集、調整後、全チームに展開。', duration: '3週間' },
    ],
    results: [
      { metric: '本番環境までの時間', before: '4ヶ月（推定）', after: '6週間', improvement: '70%高速化' },
      { metric: 'エンジニアリングコスト', before: '€80,000（推定）', after: '€22,000', improvement: '72%節約' },
      { metric: '営業生産性', before: 'ベースライン', after: '+35%', improvement: '+35%' },
      { metric: 'AI機能導入率', before: '0%', after: '89%', improvement: '89%導入' },
    ],
    testimonial: {
      quote: 'AI Empireは開発を3ヶ月、エンジニアリングコストを€58,000節約しました。事前構築された認証とAI統合により、チームはインフラではなく製品ロジックに集中できました。',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — SaaSコンプリートキット',
    timeToValue: '6週間',
  },
}
