import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-ko-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: '데이터 분석 SaaS',
    teamSize: '4명의 엔지니어',
    challenge: 'DataPulse는 6주 이내에 AI 기반 분석 대시보드를 출시해야 했습니다. 팀은 개발 시간의 80%를 인증, Stripe 결제 통합, 관리자 패널 구축에 소비하고 있었습니다.',
    solution: 'AI Empire의 NeuraDashboard 템플릿을 채택. 사전 구축된 Groq AI 통합, Stripe 결제, 역할 기반 접근 제어를 활용.',
    implementation: [
      { step: 1, title: '클론 및 설정', description: 'NeuraDashboard 템플릿을 클론하고, Groq API 키와 Stripe 자격 증명으로 환경 변수를 구성.', duration: '2시간' },
      { step: 2, title: '브랜딩 사용자 정의', description: 'DataPulse 브랜드 아이덴티티에 맞춰 색상 체계, 로고, 타이포그래피를 업데이트.', duration: '1일' },
      { step: 3, title: 'AI 기능 추가', description: 'Groq 기반 자연어 쿼리 기능을 /api/chat 엔드포인트를 통해 분석 대시보드에 통합.', duration: '2일' },
      { step: 4, title: '결제 설정', description: '템플릿의 Stripe 통합으로 3개 구독 등급(Starter, Pro, Enterprise)을 설정.', duration: '1일' },
      { step: 5, title: '배포 및 출시', description: 'Vercel에 배포, 사용자 정의 도메인 연결, 처음 50명의 고객에게 베타 출시.', duration: '1일' },
    ],
    results: [
      { metric: '출시 시간', before: '6주 (추정)', after: '8일', improvement: '85% 더 빠름' },
      { metric: '개발 비용', before: '€12,000 (추정)', after: '€2,800', improvement: '77% 절약' },
      { metric: 'API 응답 시간', before: 'N/A', after: '평균 180ms', improvement: '프로덕션 준비 완료' },
      { metric: '월간 수익', before: '€0', after: '€4,200 MRR', improvement: '+€4,200/월' },
    ],
    testimonial: {
      quote: 'AI 분석 SaaS를 6주가 아닌 8일 만에 출시했습니다. Groq 통합이 이미 연결되어 있었고 — 도메인별 프롬프트만 추가하면 되었습니다.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — 관리자 패널',
    timeToValue: '8일',
  },
  agency: {
    id: 'cs-ko-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: '디지털 에이전시',
    teamSize: '12명',
    challenge: 'Bright Studio는 클라이언트를 위한 맞춤형 SaaS 솔루션을 구축했지만, 각 프로젝트에 3-4주의 보일러플레이트 설정이 필요했습니다.',
    solution: 'AI Empire 템플릿을 모든 클라이언트 프로젝트의 출발점으로 표준화. 범용 SaaS에 NeuraSaaS, 이커머스에 NeuraStore, 콘텐츠에 NeuraBlog 사용.',
    implementation: [
      { step: 1, title: '템플릿 라이브러리', description: 'AI Empire 템플릿을 기반으로 에이전시 맞춤 커스터마이징이 포함된 내부 템플릿 라이브러리 생성.', duration: '3일' },
      { step: 2, title: '클라이언트 온보딩', description: '표준화된 흐름 정의: 템플릿 선택, 브랜딩 커스터마이징, 기능 범위 결정.', duration: '1주' },
      { step: 3, title: '팀 교육', description: '모든 개발자에게 AI Empire 코드베이스 패턴 교육.', duration: '1주' },
      { step: 4, title: '첫 번째 클라이언트 프로젝트', description: 'NeuraDashboard를 기반으로 첫 번째 프로젝트(SaaS 대시보드)를 5일 만에 납품.', duration: '5일' },
      { step: 5, title: '스케일링', description: '템플릿 기반 접근 방식을 6개 후속 클라이언트 프로젝트에 적용.', duration: '3개월' },
    ],
    results: [
      { metric: '납품 시간', before: '6-8주', after: '2-3주', improvement: '60% 더 빠름' },
      { metric: '클라이언트 만족도', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: '월간 수익', before: '€25,000', after: '€42,000', improvement: '+68%' },
      { metric: '분기별 프로젝트', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empire는 프로젝트 설정 시간을 4주에서 3일로 줄였습니다. 이제 SaaS 프로젝트를 6-8주가 아닌 2-3주 만에 납품합니다.',
      author: 'Sophie Laurent',
      role: '에이전시 디렉터, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2주',
  },
  freelancer: {
    id: 'cs-ko-freelancer-01',
    company: 'Alex Rivera (프리랜서)',
    companyType: 'freelancer',
    industry: '웹 개발',
    teamSize: '1명',
    challenge: 'Alex는 프리랜서로 스타트업을 위한 SaaS MVP를 구축했습니다. 각 프로젝트에서 인증, 결제, AI 기능을 처음부터 구축해야 했고, 프로젝트 시간의 40%를 소비했습니다.',
    solution: '모든 MVP와 개인 프로젝트의 기반으로 AI Empire 템플릿 사용. 클라이언트에게 NeuraSaaS, 개인 브랜딩에 NeuraPortfolio.',
    implementation: [
      { step: 1, title: '템플릿 평가', description: 'Free tier로 NeuraSaaS를 테스트하고 클론하고 코드베이스 탐색.', duration: '2시간' },
      { step: 2, title: '클라이언트 프로젝트 설정', description: '클라이언트의 AI 글쓰기 도구 MVP의 기반으로 NeuraSaaS 사용.', duration: '3일' },
      { step: 3, title: '배포 및 납품', description: 'Vercel에 배포, 도메인 설정, 문서와 함께 클라이언트에게 납품.', duration: '1일' },
      { step: 4, title: '개인 포트폴리오', description: 'NeuraPortfolio 템플릿으로 개인 포트폴리오 사이트 구축.', duration: '1일' },
      { step: 5, title: '프리랜서 스케일링', description: '다음 달에 템플릿 기반 접근으로 추가 3명의 클라이언트 확보.', duration: '1개월' },
    ],
    results: [
      { metric: 'MVP 납품 시간', before: '3-4주', after: '5-7일', improvement: '75% 더 빠름' },
      { metric: '월간 수입', before: '€3,500', after: '€7,200', improvement: '+106%' },
      { metric: '월간 프로젝트 수', before: '2', after: '4-5', improvement: '+125%' },
      { metric: '클라이언트 만족도', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: '솔로 개발자로서 AI Empire는 게임 체인저입니다. 월 2개의 MVP에서 4-5개로 늘었습니다. Stripe 통합만으로 프로젝트당 1주를 절약합니다.',
      author: 'Alex Rivera',
      role: '프리랜서 풀스택 개발자',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5일',
  },
  enterprise: {
    id: 'cs-ko-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: '엔터프라이즈 소프트웨어',
    teamSize: '45명의 엔지니어',
    challenge: 'Meridian은 영업 팀을 위한 내부 AI 도구를 구축하고 있었습니다. 6명의 엔지니어로 4개월 프로젝트. 인증, RBAC, AI 채팅, 분석 대시보드, 내부 비용 할당용 Stripe 결제가 필요했습니다.',
    solution: 'NeuraSaaS를 기반으로 채택. RBAC가 포함된 사전 구축 인증, 채팅용 Groq AI, 비용 추적용 Stripe 활용.',
    implementation: [
      { step: 1, title: '아키텍처 리뷰', description: 'AI Empire 코드베이스를 엔터프라이즈 요구사항으로 검토: RBAC, 감사 로깅, 속도 제한, 데이터 격리.', duration: '3일' },
      { step: 2, title: '사용자 정의 RBAC', description: '템플릿 인증 시스템에 사용자 정의 역할 확장: Admin, Manager, 영업, 읽기 전용.', duration: '1주' },
      { step: 3, title: 'AI 기능 통합', description: 'Groq AI를 영업 대화 분석, 리드 스코어링, 이메일 작성에 통합. API를 통해 내부 CRM 연결.', duration: '2주' },
      { step: 4, title: '내부 결제 설정', description: '부서 간 내부 비용 할당을 위해 Stripe 구성. 사용량 추적 및 월간 보고서 구현.', duration: '3일' },
      { step: 5, title: '파일럿 및 롤아웃', description: '10명의 영업 담당자와 2주간 파일럿. 피드백 수집, 조정 후 전체 팀에 롤아웃.', duration: '3주' },
    ],
    results: [
      { metric: '프로덕션까지 시간', before: '4개월 (추정)', after: '6주', improvement: '70% 더 빠름' },
      { metric: '엔지니어링 비용', before: '€80,000 (추정)', after: '€22,000', improvement: '72% 절약' },
      { metric: '영업 생산성', before: '기준선', after: '+35%', improvement: '+35%' },
      { metric: 'AI 기능 도입률', before: '0%', after: '89%', improvement: '89% 도입' },
    ],
    testimonial: {
      quote: 'AI Empire는 개발을 3개월, 엔지니어링 비용을 €58,000 절약했습니다. 사전 구축된 인증과 AI 통합으로 팀은 인프라가 아닌 제품 로직에 집중할 수 있었습니다.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — SaaS 컴플릿 키트',
    timeToValue: '6주',
  },
}
