import type { CaseStudiesByLanguage } from './index'

export const caseStudies: CaseStudiesByLanguage = {
  saas: {
    id: 'cs-pt-saas-01',
    company: 'DataPulse Analytics',
    companyType: 'saas',
    industry: 'SaaS de Análise de Dados',
    teamSize: '4 engenheiros',
    challenge: 'DataPulse precisava lançar seu dashboard de análise com IA em 6 semanas. Sua equipe dedicava 80% do tempo a autenticação, integração de faturamento Stripe e construção do painel admin do zero.',
    solution: 'Adotaram o template NeuraDashboard da AI Empire com integração Groq AI pré-construída, faturamento Stripe e controle de acesso baseado em funções.',
    implementation: [
      { step: 1, title: 'Clonar e configurar', description: 'Clonaram template NeuraDashboard, configuraram variáveis de ambiente com chave API Groq e credenciais Stripe.', duration: '2 horas' },
      { step: 2, title: 'Personalizar marca', description: 'Atualizaram esquema de cores, logo e tipografia para corresponder à marca DataPulse.', duration: '1 dia' },
      { step: 3, title: 'Adicionar funcionalidades IA', description: 'Integraram consulta em linguagem natural com Groq no dashboard de análise usando /api/chat pré-construído.', duration: '2 dias' },
      { step: 4, title: 'Configurar faturamento', description: 'Configuraram três níveis de assinatura com a integração Stripe do template.', duration: '1 dia' },
      { step: 5, title: 'Implantar e lançar', description: 'Implantaram no Vercel, conectaram domínio personalizado e lançaram beta para os primeiros 50 clientes.', duration: '1 dia' },
    ],
    results: [
      { metric: 'Tempo de lançamento', before: '6 semanas (estimado)', after: '8 dias', improvement: '85% mais rápido' },
      { metric: 'Custo de desenvolvimento', before: '€12.000 (estimado)', after: '€2.800', improvement: '77% de economia' },
      { metric: 'Tempo de resposta API', before: 'N/A', after: '180ms médio', improvement: 'Pronto para produção' },
      { metric: 'Receita mensal', before: '€0', after: '€4.200 MRR', improvement: '+€4.200/mês' },
    ],
    testimonial: {
      quote: 'Lançamos nosso SaaS analítico com IA em 8 dias em vez de 6 semanas. A integração Groq já estava conectada — só adicionamos prompts específicos do domínio.',
      author: 'Marcus Chen',
      role: 'CTO, DataPulse Analytics',
    },
    templateUsed: 'NeuraDashboard — Painel Admin',
    timeToValue: '8 dias',
  },
  agency: {
    id: 'cs-pt-agency-01',
    company: 'Bright Studio',
    companyType: 'agency',
    industry: 'Agência Digital',
    teamSize: '12 pessoas',
    challenge: 'Bright Studio construía soluções SaaS personalizadas mas cada projeto requeria 3-4 semanas de configuração boilerplate. Auth, faturamento e integração IA eram reconstruídos toda vez.',
    solution: 'Padronizaram templates AI Empire como ponto de partida. NeuraSaaS para SaaS geral, NeuraStore para e-commerce, NeuraBlog para conteúdo.',
    implementation: [
      { step: 1, title: 'Biblioteca de templates', description: 'Criaram biblioteca interna baseada em AI Empire com personalizações da agência.', duration: '3 dias' },
      { step: 2, title: 'Processo de onboarding', description: 'Definiram fluxo padrão: seleção de template, personalização de marca, escopo de funcionalidades.', duration: '1 semana' },
      { step: 3, title: 'Treinamento da equipe', description: 'Treinaram todos os desenvolvedores nos padrões do codebase AI Empire.', duration: '1 semana' },
      { step: 4, title: 'Primeiro projeto cliente', description: 'Entregaram o primeiro projeto (dashboard SaaS) em 5 dias com NeuraDashboard.', duration: '5 dias' },
      { step: 5, title: 'Escalar projetos', description: 'Aplicaram abordagem a 6 projetos subsequentes com tempos de entrega consistentes.', duration: '3 meses' },
    ],
    results: [
      { metric: 'Tempo de entrega', before: '6-8 semanas', after: '2-3 semanas', improvement: '60% mais rápido' },
      { metric: 'Satisfação do cliente', before: '8.2/10', after: '9.5/10', improvement: '+16%' },
      { metric: 'Receita mensal', before: '€25.000', after: '€42.000', improvement: '+68%' },
      { metric: 'Projetos por trimestre', before: '3', after: '6', improvement: '+100%' },
    ],
    testimonial: {
      quote: 'AI Empire reduziu nosso tempo de configuração de 4 semanas para 3 dias. Agora entregamos projetos SaaS em 2-3 semanas em vez de 6-8.',
      author: 'Sophie Laurent',
      role: 'Diretora de Agência, Bright Studio',
    },
    templateUsed: 'NeuraSaaS, NeuraStore, NeuraBlog',
    timeToValue: '2 semanas',
  },
  freelancer: {
    id: 'cs-pt-freelancer-01',
    company: 'Alex Rivera (Independente)',
    companyType: 'freelancer',
    industry: 'Desenvolvimento Web',
    teamSize: '1 pessoa',
    challenge: 'Alex construía MVPs SaaS para startups como freelancer. Cada projeto requeria configurar auth, pagamentos e funcionalidades IA do zero, consumindo 40% do tempo.',
    solution: 'Usou templates AI Empire como base para todos os MVPs e projetos pessoais. NeuraSaaS para clientes, NeuraPortfolio para marca pessoal.',
    implementation: [
      { step: 1, title: 'Avaliação do template', description: 'Testou NeuraSaaS com tier gratuito, clonou, explorou o codebase.', duration: '2 horas' },
      { step: 2, title: 'Setup projeto cliente', description: 'Usou NeuraSaaS como base para MVP de ferramenta de escrita IA de um cliente.', duration: '3 dias' },
      { step: 3, title: 'Implantação', description: 'Implantou no Vercel, configurou domínio e entregou ao cliente.', duration: '1 dia' },
      { step: 4, title: 'Portfolio pessoal', description: 'Construiu site portfolio pessoal com NeuraPortfolio.', duration: '1 dia' },
      { step: 5, title: 'Escalar freelance', description: 'Assumiu 3 clientes adicionais no mês seguinte.', duration: '1 mês' },
    ],
    results: [
      { metric: 'Tempo entrega MVP', before: '3-4 semanas', after: '5-7 dias', improvement: '75% mais rápido' },
      { metric: 'Receita mensal', before: '€3.500', after: '€7.200', improvement: '+106%' },
      { metric: 'Projetos por mês', before: '2', after: '4-5', improvement: '+125%' },
      { metric: 'Satisfação do cliente', before: '8/10', after: '9.5/10', improvement: '+19%' },
    ],
    testimonial: {
      quote: 'Como desenvolvedor solo, AI Empire muda o jogo. Passei de 2 MVPs por mês para 4-5. A integração Stripe sozinha me economiza uma semana por projeto.',
      author: 'Alex Rivera',
      role: 'Desenvolvedor Full-Stack Freelance',
    },
    templateUsed: 'NeuraSaaS, NeuraPortfolio',
    timeToValue: '5 dias',
  },
  enterprise: {
    id: 'cs-pt-enterprise-01',
    company: 'Meridian Technologies',
    companyType: 'enterprise',
    industry: 'Software Empresarial',
    teamSize: '45 engenheiros',
    challenge: 'Meridian construía uma ferramenta interna com IA para o time de vendas. O projeto era estimado em 4 meses com 6 engenheiros, necessitando auth, RBAC, chat IA, dashboard analítico e Stripe para custos internos.',
    solution: 'Adotaram NeuraSaaS como base. Auth pré-construído com RBAC, Groq AI para chat e Stripe para rastreamento de custos.',
    implementation: [
      { step: 1, title: 'Revisão de arquitetura', description: 'Revisaram codebase para requisitos empresariais: RBAC, auditoria, rate limiting.', duration: '3 dias' },
      { step: 2, title: 'RBAC personalizado', description: 'Estenderam auth com funções: Admin, Manager, Vendas, Somente leitura.', duration: '1 semana' },
      { step: 3, title: 'Integração IA', description: 'Integraram Groq AI para análise de conversas de vendas, scoring de leads e redação de emails.', duration: '2 semanas' },
      { step: 4, title: 'Faturamento interno', description: 'Configuraram Stripe para alocação de custos internos entre departamentos.', duration: '3 dias' },
      { step: 5, title: 'Piloto e rollout', description: 'Piloto com 10 vendedores por 2 semanas, coleta de feedback, depois rollout completo.', duration: '3 semanas' },
    ],
    results: [
      { metric: 'Tempo para produção', before: '4 meses (estimado)', after: '6 semanas', improvement: '70% mais rápido' },
      { metric: 'Custos de engenharia', before: '€80.000 (estimado)', after: '€22.000', improvement: '72% de economia' },
      { metric: 'Produtividade vendas', before: 'Base', after: '+35%', improvement: '+35%' },
      { metric: 'Adoção funcionalidades IA', before: '0%', after: '89%', improvement: '89% adoção' },
    ],
    testimonial: {
      quote: 'AI Empire nos economizou 3 meses de desenvolvimento e €58.000 em custos de engenharia. Auth e integração IA pré-construídos permitiram que a equipe focasse na lógica do produto.',
      author: 'James Whitfield',
      role: 'VP Engineering, Meridian Technologies',
    },
    templateUsed: 'NeuraSaaS — Kit Completo SaaS',
    timeToValue: '6 semanas',
  },
}
