// ============================================
// AI-EMPIRE — Paid Ads Copy (Arabic)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === بحث (4) ===
  {
    id: 'g-ar-01',
    platform: 'google',
    type: 'search',
    headline: 'واجهة برمجة تطبيقات الذكاء الاصطناعي — خطة مجانية',
    description: 'واجهة موحدة لـ Groq و Gemini. مجاناً للبدء. فوترة عبر Stripe.',
    cta: 'جرب مجاناً',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'المطورون الباحثون عن مزودي واجهات برمجة التطبيقات للذكاء الاصطناعي',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-ar-02',
    platform: 'google',
    type: 'search',
    headline: 'قوالب Next.js SaaS — أطلق أسرع',
    description: 'قوالب Next.js 14 جاهزة للإنتاج مع دمج الذكاء الاصطناعي. NeuraStore و NeuraBlog.',
    cta: 'عرض القوالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'المطورون الباحثون عن قوالب Next.js',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-ar-03',
    platform: 'google',
    type: 'search',
    headline: 'ادمج الذكاء الاصطناعي في تطبيقك في دقائق',
    description: 'اتصل بـ Groq و Gemini من خلال واجهة برمجة واحدة. إعداد في 5 دقائق. توثيق مضمن.',
    cta: 'اقرأ التوثيق',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'قادة التقنية، المطورون المتكاملون',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-ar-04',
    platform: 'google',
    type: 'search',
    headline: 'مجموعة بدء SaaS مع Stripe والذكاء الاصطناعي',
    description: 'قالب Next.js مع فوترة Stripe والتوثيق وواجهة برمجة الذكاء الاصطناعي. جاهز للنشر.',
    cta: 'ابدأ الآن',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'مؤسسون SaaS، مطورو مستقلون',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === عرض (3) ===
  {
    id: 'g-ar-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — قالب تجارة إلكترونية لـ Next.js',
    description: 'قالب متجر بالذكاء الاصطناعي مع تكامل Stripe. مبني بـ Next.js 14 و Tailwind.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'زائرو الموقع، اهتمام بالتجارة الإلكترونية',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-ar-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — قالب مدونة محسّن لـ SEO',
    description: 'قالب مدونة Next.js مع MDX والوضع المظلم وخلاصة RSS. جاهز للإنتاج.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'منشئو المحتوى، مدونون',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-ar-07',
    platform: 'google',
    type: 'display',
    headline: 'أنشئ تطبيقات ذكاء اصطناعي بـ Groq و Gemini',
    description: 'واجهة برمجة واحدة، نماذج ذكاء اصطناعي متعددة. خطة مجانية. مكتبات JavaScript و Python.',
    cta: 'استكشف الواجهة',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'مطورون ذكاء اصطناعي، مهندسو تعلم آلي',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === أقصى أداء (3) ===
  {
    id: 'g-ar-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'قوالب SaaS بالذكاء الاصطناعي — مجاناً للبدء',
    description: 'قوالب Next.js 14 مع واجهة برمجة ذكاء اصطناعي و Stripe والتوثيق. انشر اليوم.',
    cta: 'جرب مجاناً',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'مؤسسون SaaS، مطورون',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-ar-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — قالب محفظة للمطورين',
    description: 'اعرض أعمالك بمحفظة Next.js نظيفة. 50+ مكون، تصميم متجاوب، وضع مظلم.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'مطورون، مستقلون',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-ar-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'تسعير واجهة برمجة الذكاء الاصطناعي — مجاناً للبدء',
    description: 'واجهة برمجة تطبيقات حسب الاستخدام. نماذج Groq و Gemini. بدون تكاليف مسبقة. شاهد التسعير.',
    cta: 'شاهد التسعير',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'مطورون مهتمون بالتكلفة',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === الوعي (4) ===
  {
    id: 'fb-ar-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'أنشئ تطبيقات ذكاء اصطناعي بدون تعقيد',
    description: 'AI-Empire يوفر لك واجهة برمجة موحدة لـ Groq و Gemini. مجاناً، بدون بطاقة ائتمان.',
    cta: 'اعرف المزيد',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'مطورون، 25-45 سنة، اهتمامات: ذكاء اصطناعي، React، Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-ar-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'قوالب Next.js SaaS مع ذكاء اصطناعي',
    description: 'NeuraStore و NeuraBlog و NeuraPortfolio — جاهزة مع Stripe والذكاء الاصطناعي.',
    cta: 'استكشف القوالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'مطورو React/Next.js، 22-40 سنة',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-ar-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'واجهة برمجة ذكاء اصطناعي لمشروعك التالي',
    description: 'اتصل بـ Groq و Gemini من خلال واجهة برمجة واحدة. مكتبات JS و Python. توثيق مضمن.',
    cta: 'اقرأ التوثيق',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'مطورون، متبنون مبكرون، 20-38 سنة',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-ar-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'ما يمكنك بناؤه مع AI-Empire',
    description: 'روبوتات المحادثة، مولدو المحتوى، مساعدو الكود — عبر واجهة برمجة Groq و Gemini.',
    cta: 'شاهد الأمثلة',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'هاوون التقنية، 18-35 سنة',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === التحويل (3) ===
  {
    id: 'fb-ar-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'ابدأ SaaS الذكاء الاصطناعي اليوم',
    description: 'قوالب Next.js مع Stripe والتوثيق وواجهة برمجة الذكاء الاصطناعي. خطة مجانية. نشر في دقائق.',
    cta: 'ابدأ الآن',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'زائرو الموقع، آخر 7 أيام',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-ar-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — متجرك بالذكاء الاصطناعي',
    description: 'قالب تجارة إلكترونية مع توصيات ذكية ودفع Stripe. قابل للتخصيص.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'اهتمام بالتجارة الإلكترونية، زائرو الموقع',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-ar-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'قارن أسعار واجهة البرمجة',
    description: 'خطة مجانية، ثم الدفع حسب الاستخدام. نماذج Groq و Gemini. قارن الأسعار.',
    cta: 'شاهد التسعير',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'مطورون مهتمون بالسعر',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === إعادة الاستهداف (3) ===
  {
    id: 'fb-ar-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'لا تزال تفكر في AI-Empire؟',
    description: 'خطة مجانية متاحة. بدون بطاقة ائتمان. جرب واجهة البرمجة والقوالب اليوم.',
    cta: 'جرب مجاناً',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'زائرون شاهدوا التسعير بدون تحويل',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-ar-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — أنشئ مدونتك بالذكاء الاصطناعي',
    description: 'قالب مدونة محسّن لـ SEO مع MDX والوضع المظلم. جاهز للإنتاج.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'زائرون صفحة القوالب',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-ar-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'مستعد لنشر تطبيق الذكاء الاصطناعي؟',
    description: 'قوالبنا تتضمن التوثيق والدفع ودمج الذكاء الاصطناعي. ابدأ بأساس متين.',
    cta: 'ابدأ الآن',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'زائرو التوثيق، غير المحولين',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === محتوى ممول (4) ===
  {
    id: 'li-ar-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'واجهة برمجة ذكاء اصطناعي لفرق SaaS — Groq و Gemini',
    description: 'واجهة موحدة لـ Groq و Gemini. خطة مجانية، تكامل Stripe، متوافقة مع GDPR. مبنية للفرق.',
    cta: 'اعرف المزيد',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'قادة تقنية، قادة التطوير، 10-200 موظف',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-ar-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'أطلق SaaS الذكاء الاصطناعي أسرع',
    description: 'قوالب Next.js 14 مع التوثيق والدفع والذكاء الاصطناعي. جاهزة للإنتاج. شاهد القوالب.',
    cta: 'شاهد القوالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'مدرجو المنتجات، قادة الهندسة',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-ar-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'كيف تضيف الذكاء الاصطناعي إلى منتجك',
    description: 'دليل خطوة بخطوة لدمج Groq و Gemini. خطة واجهة برمجة مجانية متاحة.',
    cta: 'اقرأ الدليل',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'قادة تقنية، نواب الهندسة، 50-500 موظف',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-ar-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: ابنِ SaaS مع ذكاء اصطناعي مدمج',
    description: 'قوالب Next.js + واجهة برمجة ذكاء اصطناعي + Stripe. كل ما تحتاجه لإطلاق SaaS.',
    cta: 'ابدأ الآن',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'مؤسسون، قادة تقنية، شركات تقنية ناشئة',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === إعلانات الرسائل (3) ===
  {
    id: 'li-ar-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'خطة واجهة برمجة ذكاء اصطناعي مجانية — جرب اليوم',
    description: 'Groq و Gemini من خلال واجهة برمجة واحدة. مجاناً للبدء. دمج في 5 دقائق. توثيق ومكتبات مضمنة.',
    cta: 'جرب مجاناً',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'قادة تقنية، مطورون، 25-45 سنة',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-ar-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'قوالب Next.js لمشروع الذكاء الاصطناعي',
    description: 'NeuraStore و NeuraBlog و NeuraPortfolio — جاهزة للإنتاج. توثيق ودفع وذكاء اصطناعي مضمنة.',
    cta: 'استكشف القوالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'فرق التطوير، شركات ناشئة',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-ar-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'بسط مكدس الذكاء الاصطناعي',
    description: 'واجهة برمجة واحدة لـ Groq و Gemini. لا مزيد من إدارة مفاتيح مزودين متعددين. خطة مجانية.',
    cta: 'اعرف المزيد',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'مدرجو الهندسة، قادة تقنية',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === إعلانات ديناميكية (3) ===
  {
    id: 'li-ar-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'واجهة برمجة ذكاء اصطناعي — مجاناً للبدء، ادفع مع النمو',
    description: 'نماذج Groq و Gemini. بدون تكاليف مسبقة. شاهد التسعير.',
    cta: 'شاهد التسعير',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'المتخذون التقنيون، واعون بالتكلفة',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-ar-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — قالب محفظة للمطورين',
    description: 'محفظة Next.js نظيفة ومتجاوبة. 50+ مكون. وضع مظلم. انشر اليوم.',
    cta: 'عرض القالب',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'مطورون، مستقلون',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-ar-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'واجهة برمجة ذكاء اصطناعي متوافقة مع GDPR لأوروبا',
    description: 'AI-Empire مبنية مع خصوصية البيانات. خطة مجانية. فوترة Stripe. توثيق مضمن.',
    cta: 'اعرف المزيد',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'شركات تقنية أوروبية، أدوار الامتثال',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
