// ============================================
// AI-EMPIRE — Paid Ads Copy (German)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Suche (4) ===
  {
    id: 'g-de-01',
    platform: 'google',
    type: 'search',
    headline: 'AI API mit Groq & Gemini — Kostenloser Tier',
    description: 'Einheitliche API für Groq- und Gemini-Modelle. Kostenlos starten. Stripe-Abrechnung.',
    cta: 'Kostenlos Testen',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Entwickler, die AI-API-Anbieter suchen',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-de-02',
    platform: 'google',
    type: 'search',
    headline: 'Next.js SaaS Templates — Schneller Launch',
    description: 'Produktionsfertige Next.js 14 Templates mit KI-Integration. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'Templates Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Entwickler, die Next.js Templates suchen',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-de-03',
    platform: 'google',
    type: 'search',
    headline: 'KI in Ihre App Integrieren — In Minuten',
    description: 'Verbinden Sie sich mit Groq und Gemini über eine API. 5-Minuten-Setup. Docs inklusive.',
    cta: 'Docs Lesen',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech Leads, Full-Stack-Entwickler',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-de-04',
    platform: 'google',
    type: 'search',
    headline: 'Stripe-Integriertes AI SaaS Starter Kit',
    description: 'Next.js SaaS-Template mit Stripe-Abrechnung, Auth und AI-API. Bereit zum Deploy.',
    cta: 'Jetzt Starten',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'SaaS-Gründer, Indie Hackers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-de-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — E-Commerce Template für Next.js',
    description: 'KI-gestütztes Shop-Template mit Stripe-Integration. Gebaut mit Next.js 14 und Tailwind.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Website-Besucher, E-Commerce-Interesse',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-de-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — SEO-Optimiertes Blog-Template',
    description: 'Next.js Blog-Template mit MDX, Dark Mode und RSS-Feed. Produktionsbereit.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Content-Ersteller, Blogger',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-de-07',
    platform: 'google',
    type: 'display',
    headline: 'KI-Apps Bauen mit Groq & Gemini',
    description: 'Eine API, mehrere KI-Modelle. Kostenloser Tier. JavaScript und Python SDKs.',
    cta: 'API Erkunden',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'KI-Entwickler, ML-Ingenieure',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-de-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'KI-gestützte SaaS Templates — Kostenlos',
    description: 'Next.js 14 Templates mit AI-API, Stripe und Auth. Heute deployen.',
    cta: 'Kostenlos Testen',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'SaaS-Gründer, Entwickler',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-de-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Entwickler-Portfolio-Template',
    description: 'Präsentieren Sie Ihre Arbeit mit einem sauberen Next.js Portfolio. 50+ Komponenten, Dark Mode.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Entwickler, Freelancer',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-de-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI API Preise — Kostenlos Starten',
    description: 'Pay-as-you-go AI API. Groq- und Gemini-Modelle. Keine Vorkosten. Preise ansehen.',
    cta: 'Preise Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Kostenbewusste Entwickler',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-de-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'KI-Apps Bauen ohne Komplexität',
    description: 'AI-Empire gibt Ihnen eine einheitliche API für Groq und Gemini. Kostenlos, keine Kreditkarte nötig.',
    cta: 'Mehr Erfahren',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Entwickler, 25-45, Interessen: AI, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-de-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Next.js Templates für KI-SaaS',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — produktionsfertig mit Stripe und KI.',
    cta: 'Templates Erkunden',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'React/Next.js-Entwickler, 22-40',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-de-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI API für Ihr Nächstes Projekt',
    description: 'Verbinden Sie sich mit Groq und Gemini über eine API. JS- und Python-SDKs. Docs inklusive.',
    cta: 'Docs Lesen',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Entwickler, Early Adopters, 20-38',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-de-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Was Sie mit AI-Empire Bauen Können',
    description: 'Chatbots, Content-Generatoren, Code-Assistenten — mit Groq und Gemini via eine API.',
    cta: 'Beispiele Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Tech-Enthusiasten, 18-35',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-de-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Starten Sie Ihr KI-SaaS Heute',
    description: 'Next.js Templates mit Stripe, Auth und AI-API. Kostenloser Tier. In Minuten deployen.',
    cta: 'Jetzt Starten',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Website-Besucher, letzte 7 Tage',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-de-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Ihr KI-Shop',
    description: 'E-Commerce-Template mit KI-Produktempfehlungen und Stripe-Checkout. Anpassbar.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'E-Commerce-Interesse, Website-Besucher',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-de-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Vergleichen Sie Unsere API-Preise',
    description: 'Kostenloser Tier, dann Pay-as-you-go. Groq- und Gemini-Modelle. Preise vergleichen.',
    cta: 'Preise Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Preissensible Entwickler',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-de-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Noch Über AI-Empire Nachdenken?',
    description: 'Kostenloser Tier verfügbar. Keine Kreditkarte. Testen Sie unsere API und Templates heute.',
    cta: 'Kostenlos Testen',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Besucher, die Preise angesehen haben',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-de-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Erstellen Sie Ihren KI-Blog',
    description: 'SEO-optimiertes Blog-Template mit MDX und Dark Mode. Produktionsbereit.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Template-Seiten-Besucher',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-de-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Bereit zur Deployment Ihrer KI-App?',
    description: 'Unsere Templates enthalten Auth, Zahlungen und KI-Integration. Starten Sie mit einer soliden Basis.',
    cta: 'Jetzt Starten',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Docs-Besucher, Nicht-Konvertierer',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-de-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI API für SaaS-Teams — Groq & Gemini',
    description: 'Einheitliche API für Groq und Gemini. Kostenloser Tier, Stripe-Integration, DSGVO-konform. Für Teams.',
    cta: 'Mehr Erfahren',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTOs, Lead Devs, 10-200 Mitarbeiter',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-de-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Ihr KI-SaaS Schneller Bereitstellen',
    description: 'Next.js 14 Templates mit Auth, Zahlungen und KI. Produktionsfertig. Templates ansehen.',
    cta: 'Templates Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Managers, Engineering Leads',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-de-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'KI Zu Ihrem Produkt Hinzufügen',
    description: 'Schritt-für-Schritt-Anleitung zur Integration von Groq und Gemini. Kostenloser API-Tier.',
    cta: 'Anleitung Lesen',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTOs, VP Engineering, 50-500 Mitarbeiter',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-de-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: SaaS Mit Integrierter KI Bauen',
    description: 'Next.js Templates + AI-API + Stripe. Alles was Sie für einen SaaS-Launch brauchen.',
    cta: 'Jetzt Starten',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Gründer, CTOs, Tech-Startups',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-de-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'AI API Kostenloser Tier — Heute Testen',
    description: 'Groq und Gemini via eine API. Kostenlos starten. 5-Minuten-Integration. Docs und SDKs inklusive.',
    cta: 'Kostenlos Testen',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech Leads, Entwickler, 25-45',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-de-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Next.js Templates für Ihr KI-Projekt',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — produktionsfertig. Auth, Zahlungen, KI inklusive.',
    cta: 'Templates Erkunden',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Entwicklungsteams, Startups',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-de-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Ihren KI-Stack Vereinfachen',
    description: 'Eine API für Groq und Gemini. Kein Management mehrerer Anbieter-Schlüssel. Kostenloser Tier.',
    cta: 'Mehr Erfahren',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering Manager, CTOs',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-de-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'AI API — Kostenlos Starten, Nach Wachstum Zahlen',
    description: 'Groq- und Gemini-Modelle. Keine Vorkosten. Preise ansehen.',
    cta: 'Preise Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Technische Entscheider, Budget-bewusst',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-de-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Entwickler-Portfolio-Template',
    description: 'Sauberes, responsive Next.js Portfolio. 50+ Komponenten. Dark Mode. Heute deployen.',
    cta: 'Template Ansehen',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Entwickler, Freelancer',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-de-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'DSGVO-konforme AI API für Europa',
    description: 'AI-Empire mit Fokus auf Datenschutz. Kostenloser Tier. Stripe-Abrechnung. Docs inklusive.',
    cta: 'Mehr Erfahren',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'Europäische Tech-Unternehmen, Compliance-Rollen',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
