// ============================================
// AI-EMPIRE — Paid Ads Copy (English)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Search (4) ===
  {
    id: 'g-en-01',
    platform: 'google',
    type: 'search',
    headline: 'AI API with Groq & Gemini — Free Tier Available',
    description: 'Unified API for Groq and Gemini models. Free to start, no credit card required. Stripe billing.',
    cta: 'Try Free',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Developers searching for AI API providers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-en-02',
    platform: 'google',
    type: 'search',
    headline: 'Next.js SaaS Templates — Launch Faster',
    description: 'Production-ready Next.js 14 templates with AI integration. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'See Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Developers searching for Next.js templates',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-en-03',
    platform: 'google',
    type: 'search',
    headline: 'Integrate AI into Your App in Minutes',
    description: 'Connect to Groq and Gemini through one API. 5-minute setup. Docs and examples included.',
    cta: 'Read Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech leads, full-stack developers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-en-04',
    platform: 'google',
    type: 'search',
    headline: 'Stripe-Integrated AI SaaS Starter Kit',
    description: 'Next.js SaaS template with Stripe billing, auth, and AI API. Ready to deploy.',
    cta: 'Get Started',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'SaaS founders, indie hackers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-en-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — E-Commerce Template for Next.js',
    description: 'AI-powered storefront template with Stripe integration. Built with Next.js 14 and Tailwind.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Site visitors, e-commerce interest',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-en-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — SEO-Optimized Blog Template',
    description: 'Next.js blog template with MDX, dark mode, and RSS feed. Ready for production.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Content creators, bloggers',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-en-07',
    platform: 'google',
    type: 'display',
    headline: 'Build AI Apps with Groq & Gemini',
    description: 'One API, multiple AI models. Free tier available. JavaScript and Python SDKs.',
    cta: 'Explore API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'AI developers, ML engineers',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-en-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI-Powered SaaS Templates — Start Free',
    description: 'Next.js 14 templates with built-in AI API, Stripe, and authentication. Deploy today.',
    cta: 'Try Free',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'SaaS founders, developers',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-en-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Developer Portfolio Template',
    description: 'Showcase your work with a clean Next.js portfolio. 50+ components, responsive, dark mode.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Developers, freelancers',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-en-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI API Pricing — Free to Start',
    description: 'Pay-as-you-go AI API. Groq and Gemini models. No upfront costs. See our pricing.',
    cta: 'See Pricing',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Cost-conscious developers',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-en-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Build AI Apps Without the Complexity',
    description: 'AI-Empire gives you a unified API for Groq and Gemini. Free to start, no credit card needed.',
    cta: 'Learn More',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Developers, 25-45, tech interests: AI, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-en-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Next.js Templates Built for AI SaaS',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — production-ready templates with Stripe and AI.',
    cta: 'Explore Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'React/Next.js developers, 22-40',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-en-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI API for Your Next Project',
    description: 'Connect to Groq and Gemini through one API. JavaScript and Python SDK. Docs included.',
    cta: 'Read Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Developers, early adopters, 20-38',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-en-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'What You Can Build with AI-Empire',
    description: 'Chatbots, content generators, code assistants — powered by Groq and Gemini via one API.',
    cta: 'See Examples',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Tech enthusiasts, 18-35',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-en-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Start Your AI SaaS Today',
    description: 'Next.js templates with Stripe, auth, and AI API. Free tier available. Deploy in minutes.',
    cta: 'Get Started',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Site visitors, last 7 days',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-en-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Your AI Storefront',
    description: 'E-commerce template with AI product recommendations and Stripe checkout. Ready to customize.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'E-commerce interest, site visitors',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-en-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Compare Our AI API Pricing',
    description: 'Free tier, then pay-as-you-go. Groq and Gemini models. See how we compare.',
    cta: 'See Pricing',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Price-conscious developers, site visitors',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-en-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Still Thinking About AI-Empire?',
    description: 'Free tier available. No credit card required. Try our API and templates today.',
    cta: 'Try Free',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Visitors who viewed pricing but didn\'t convert',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-en-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Build Your AI Blog',
    description: 'SEO-optimized blog template with MDX and dark mode. Ready for production.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Template page visitors',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-en-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Ready to Deploy Your AI App?',
    description: 'Our templates include auth, payments, and AI integration. Start from a solid foundation.',
    cta: 'Get Started',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Docs page visitors, non-converters',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-en-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI API for SaaS Teams — Groq & Gemini',
    description: 'Unified API for Groq and Gemini. Free tier, Stripe integration, GDPR-compliant. Built for teams.',
    cta: 'Learn More',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTOs, Lead Devs, 10-200 employees',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-en-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Ship Your AI SaaS Faster',
    description: 'Next.js 14 templates with auth, payments, and AI. Production-ready. See our templates.',
    cta: 'See Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Managers, Engineering Leads',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-en-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'How to Add AI to Your Product',
    description: 'Step-by-step guide to integrating Groq and Gemini into your app. Free API tier available.',
    cta: 'Read Guide',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTOs, VP Engineering, 50-500 employees',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-en-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: Build SaaS with AI Built-In',
    description: 'Next.js templates + AI API + Stripe. Everything you need to launch a SaaS product.',
    cta: 'Get Started',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Founders, CTOs, tech startups',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-en-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'AI API Free Tier — Try It Today',
    description: 'Groq and Gemini via one API. Free to start. 5-minute integration. Docs and SDKs included.',
    cta: 'Try Free',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech leads, developers, 25-45',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-en-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Next.js Templates for Your AI Project',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — production-ready. Auth, payments, AI included.',
    cta: 'Explore Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Development teams, startups',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-en-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Simplify Your AI Stack',
    description: 'One API for Groq and Gemini. No more managing multiple provider keys. Free tier available.',
    cta: 'Learn More',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering managers, CTOs',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-en-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'AI API — Free to Start, Pay as You Grow',
    description: 'Groq and Gemini models. No upfront costs. See our pricing for details.',
    cta: 'See Pricing',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Budget-conscious tech decision makers',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-en-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Developer Portfolio Template',
    description: 'Clean, responsive Next.js portfolio. 50+ components. Dark mode. Deploy today.',
    cta: 'View Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Developers, freelancers',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-en-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'GDPR-Compliant AI API for Europe',
    description: 'AI-Empire is built with data privacy in mind. Free tier. Stripe billing. Docs included.',
    cta: 'Learn More',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'European tech companies, data compliance roles',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
