// ============================================
// AI-EMPIRE — Paid Ads Copy (Spanish)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Búsqueda (4) ===
  {
    id: 'g-es-01',
    platform: 'google',
    type: 'search',
    headline: 'API de IA con Groq y Gemini — Tier Gratuito',
    description: 'API unificada para modelos Groq y Gemini. Gratis para empezar. Facturación con Stripe.',
    cta: 'Probar Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Desarrolladores buscando proveedores de API de IA',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-es-02',
    platform: 'google',
    type: 'search',
    headline: 'Templates Next.js SaaS — Lanza Más Rápido',
    description: 'Templates Next.js 14 listos para producción con IA integrada. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'Ver Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Desarrolladores buscando templates Next.js',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-es-03',
    platform: 'google',
    type: 'search',
    headline: 'Integra IA en Tu App en Minutos',
    description: 'Conecta con Groq y Gemini a través de una API. Configuración en 5 minutos. Documentación incluida.',
    cta: 'Leer Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech leads, desarrolladores full-stack',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-es-04',
    platform: 'google',
    type: 'search',
    headline: 'Kit Starter SaaS con Stripe e IA',
    description: 'Template Next.js con facturación Stripe, auth y API de IA. Listo para desplegar.',
    cta: 'Empezar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'Fundadores de SaaS, indie hackers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-es-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Template E-Commerce para Next.js',
    description: 'Template de tienda con IA y integración Stripe. Construido con Next.js 14 y Tailwind.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Visitantes del sitio, interés en e-commerce',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-es-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — Template Blog SEO Optimizado',
    description: 'Template de blog Next.js con MDX, modo oscuro y feed RSS. Listo para producción.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Creadores de contenido, blogueros',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-es-07',
    platform: 'google',
    type: 'display',
    headline: 'Crea Apps de IA con Groq y Gemini',
    description: 'Una API, múltiples modelos de IA. Tier gratuito disponible. SDKs para JavaScript y Python.',
    cta: 'Explorar API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'Desarrolladores de IA, ingenieros ML',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-es-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'Templates SaaS Potenciados por IA — Gratis',
    description: 'Templates Next.js 14 con API de IA, Stripe y autenticación. Despliega hoy.',
    cta: 'Probar Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'Fundadores de SaaS, desarrolladores',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-es-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Template Portafolio Dev',
    description: 'Muestra tu trabajo con un portafolio Next.js limpio. 50+ componentes, responsive, modo oscuro.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Desarrolladores, freelancers',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-es-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'Precios de API de IA — Gratis para Empezar',
    description: 'API de IA bajo demanda. Modelos Groq y Gemini. Sin costos iniciales. Ver我们的定价.',
    cta: 'Ver Precios',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Desarrolladores conscientes del costo',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-es-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Crea Apps de IA Sin Complejidad',
    description: 'AI-Empire te da una API unificada para Groq y Gemini. Gratis para empezar, sin tarjeta de crédito.',
    cta: 'Saber Más',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Desarrolladores, 25-45, intereses: IA, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-es-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Templates Next.js para SaaS con IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — templates listos con Stripe e IA integrada.',
    cta: 'Explorar Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'Desarrolladores React/Next.js, 22-40',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-es-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'API de IA para Tu Próximo Proyecto',
    description: 'Conecta con Groq y Gemini a través de una API. SDKs para JavaScript y Python. Docs incluidos.',
    cta: 'Leer Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Desarrolladores, early adopters, 20-38',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-es-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Lo Que Puedes Construir con AI-Empire',
    description: 'Chatbots, generadores de contenido, asistentes de código — con Groq y Gemini vía una API.',
    cta: 'Ver Ejemplos',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Entusiastas de tecnología, 18-35',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-es-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Empieza Tu SaaS de IA Hoy',
    description: 'Templates Next.js con Stripe, auth y API de IA. Tier gratuito. Despliega en minutos.',
    cta: 'Empezar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Visitantes del sitio, últimos 7 días',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-es-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Tu Tienda con IA',
    description: 'Template e-commerce con recomendaciones de IA y checkout Stripe. Listo para personalizar.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'Interés en e-commerce, visitantes del sitio',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-es-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Compara Nuestros Precios de API',
    description: 'Tier gratuito, luego pago por uso. Modelos Groq y Gemini. Compara我们的定价.',
    cta: 'Ver Precios',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Desarrolladores sensibles al precio',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-es-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: '¿Todavía Piensas en AI-Empire?',
    description: 'Tier gratuito disponible. Sin tarjeta de crédito. Prueba nuestra API y templates hoy.',
    cta: 'Probar Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Visitantes que vieron precios pero no convirtieron',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-es-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Crea Tu Blog con IA',
    description: 'Template de blog SEO optimizado con MDX y modo oscuro. Listo para producción.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Visitantes de la página de templates',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-es-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: '¿Listo para Desplegar Tu App de IA?',
    description: 'Nuestros templates incluyen auth, pagos e integración IA. Empieza con una base sólida.',
    cta: 'Empezar',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Visitantes de docs, no conversores',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-es-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'API de IA para Equipos SaaS — Groq y Gemini',
    description: 'API unificada para Groq y Gemini. Tier gratuito, integración Stripe, cumplimiento GDPR. Hecha para equipos.',
    cta: 'Saber Más',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTOs, Lead Devs, 10-200 empleados',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-es-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Lanza Tu SaaS de IA Más Rápido',
    description: 'Templates Next.js 14 con auth, pagos y IA. Listos para producción. Ver templates.',
    cta: 'Ver Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Managers, Engineering Leads',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-es-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Cómo Agregar IA a Tu Producto',
    description: 'Guía paso a paso para integrar Groq y Gemini en tu app. Tier gratuito de API disponible.',
    cta: 'Leer Guía',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTOs, VP Engineering, 50-500 empleados',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-es-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: Construye SaaS con IA Integrada',
    description: 'Templates Next.js + API de IA + Stripe. Todo lo que necesitas para lanzar un SaaS.',
    cta: 'Empezar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Fundadores, CTOs, startups tech',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-es-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'Tier Gratuito de API de IA — Prueba Hoy',
    description: 'Groq y Gemini vía una API. Gratis para empezar. Integración en 5 minutos. Docs y SDKs incluidos.',
    cta: 'Probar Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech leads, desarrolladores, 25-45',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-es-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Templates Next.js para Tu Proyecto de IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — listos para producción. Auth, pagos, IA incluidos.',
    cta: 'Explorar Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Equipos de desarrollo, startups',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-es-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Simplifica Tu Stack de IA',
    description: 'Una API para Groq y Gemini. Sin gestionar múltiples claves de proveedor. Tier gratuito.',
    cta: 'Saber Más',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering managers, CTOs',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-es-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API de IA — Gratis para Empezar, Paga al Crecer',
    description: 'Modelos Groq y Gemini. Sin costos iniciales. Ver nuestra precios.',
    cta: 'Ver Precios',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Tomadores de decisión tech, presupuesto ajustado',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-es-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Template Portafolio Dev',
    description: 'Portafolio Next.js limpio y responsive. 50+ componentes. Modo oscuro. Despliega hoy.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Desarrolladores, freelancers',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-es-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API de IA Cumplimiento GDPR para Europa',
    description: 'AI-Empire construida con privacidad de datos. Tier gratuito. Facturación Stripe. Docs incluidos.',
    cta: 'Saber Más',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'Empresas tech europeas, roles de cumplimiento',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
