// ============================================
// AI-EMPIRE — Paid Ads Copy (French)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Recherche (4) ===
  {
    id: 'g-fr-01',
    platform: 'google',
    type: 'search',
    headline: 'API IA avec Groq et Gemini — Tier Gratuit',
    description: 'API unifiée pour les modèles Groq et Gemini. Gratuit pour démarrer. Facturation Stripe.',
    cta: 'Essayer Gratuitement',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Développeurs cherchant des fournisseurs d\'API IA',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-fr-02',
    platform: 'google',
    type: 'search',
    headline: 'Templates SaaS Next.js — Lancez Plus Vite',
    description: 'Templates Next.js 14 prêts pour la production avec IA intégrée. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'Voir les Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Développeurs cherchant des templates Next.js',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-fr-03',
    platform: 'google',
    type: 'search',
    headline: 'Intégrez l\'IA dans Votre App en Minutes',
    description: 'Connectez-vous à Groq et Gemini via une API. Configuration en 5 minutes. Documentation incluse.',
    cta: 'Lire la Doc',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech leads, développeurs full-stack',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-fr-04',
    platform: 'google',
    type: 'search',
    headline: 'Kit Starter SaaS avec Stripe et IA',
    description: 'Template Next.js avec facturation Stripe, auth et API IA. Prêt au déploiement.',
    cta: 'Commencer',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'Fondateurs de SaaS, indie hackers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-fr-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Template E-Commerce pour Next.js',
    description: 'Template de boutique IA avec intégration Stripe. Construit avec Next.js 14 et Tailwind.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Visiteurs du site, intérêt e-commerce',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-fr-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — Template Blog SEO Optimisé',
    description: 'Template blog Next.js avec MDX, mode sombre et flux RSS. Prêt pour la production.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Créateurs de contenu, blogueurs',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-fr-07',
    platform: 'google',
    type: 'display',
    headline: 'Créez des Apps IA avec Groq et Gemini',
    description: 'Une API, plusieurs modèles IA. Tier gratuit. SDKs JavaScript et Python.',
    cta: 'Explorer l\'API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'Développeurs IA, ingénieurs ML',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-fr-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'Templates SaaS avec IA — Gratuits pour Démarrer',
    description: 'Templates Next.js 14 avec API IA, Stripe et authentification. Déployez aujourd\'hui.',
    cta: 'Essayer Gratuitement',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'Fondateurs de SaaS, développeurs',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-fr-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Template Portfolio Développeur',
    description: 'Présentez votre travail avec un portfolio Next.js épuré. 50+ composants, mode sombre.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Développeurs, freelances',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-fr-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'Tarifs API IA — Gratuit pour Démarrer',
    description: 'API IA à l\'usage. Modèles Groq et Gemini. Pas de frais initiaux. Voir nos tarifs.',
    cta: 'Voir les Tarifs',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Développeurs soucieux des coûts',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-fr-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Créez des Apps IA Sans Complexité',
    description: 'AI-Empire vous donne une API unifiée pour Groq et Gemini. Gratuit, sans CB requise.',
    cta: 'En Savoir Plus',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Développeurs, 25-45 ans, intérêts: IA, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-fr-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Templates Next.js pour SaaS IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — prêts avec Stripe et IA intégrée.',
    cta: 'Explorer les Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'Développeurs React/Next.js, 22-40 ans',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-fr-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'API IA pour Votre Projet',
    description: 'Connectez-vous à Groq et Gemini via une API. SDKs JS et Python. Documentation incluse.',
    cta: 'Lire la Doc',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Développeurs, early adopters, 20-38 ans',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-fr-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Ce Que Vous Pouvez Construire avec AI-Empire',
    description: 'Chatbots, générateurs de contenu, assistants de code — avec Groq et Gemini via une API.',
    cta: 'Voir les Exemples',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Enthousiastes tech, 18-35 ans',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-fr-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Lancez Votre SaaS IA Aujourd\'hui',
    description: 'Templates Next.js avec Stripe, auth et API IA. Tier gratuit. Déploiement en minutes.',
    cta: 'Commencer',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Visiteurs du site, 7 derniers jours',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-fr-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Votre Boutique IA',
    description: 'Template e-commerce avec recommandations IA et checkout Stripe. Personnalisable.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'Intérêt e-commerce, visiteurs du site',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-fr-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Comparez Nos Tarifs API',
    description: 'Tier gratuit, puis paiement à l\'usage. Modèles Groq et Gemini. Comparez nos tarifs.',
    cta: 'Voir les Tarifs',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Développeurs sensibles au prix',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-fr-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Toujours en Réflexion sur AI-Empire ?',
    description: 'Tier gratuit disponible. Sans CB. Testez notre API et nos templates aujourd\'hui.',
    cta: 'Essayer Gratuitement',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Visiteurs ayant consulté les tarifs sans convertir',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-fr-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Créez Votre Blog IA',
    description: 'Template blog SEO optimisé avec MDX et mode sombre. Prêt pour la production.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Visiteurs de la page templates',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-fr-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Prêt à Déployer Votre App IA ?',
    description: 'Nos templates incluent auth, paiements et intégration IA. Commencez sur de bonnes bases.',
    cta: 'Commencer',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Visiteurs docs, non-convertis',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-fr-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'API IA pour Équipes SaaS — Groq et Gemini',
    description: 'API unifiée pour Groq et Gemini. Tier gratuit, intégration Stripe, conforme RGPD. Conçue pour les équipes.',
    cta: 'En Savoir Plus',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTOs, Lead Devs, 10-200 employés',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-fr-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Lancez Votre SaaS IA Plus Vite',
    description: 'Templates Next.js 14 avec auth, paiements et IA. Prêts pour la production. Voir les templates.',
    cta: 'Voir les Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Managers, Engineering Leads',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-fr-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Comment Ajouter l\'IA à Votre Produit',
    description: 'Guide étape par étape pour intégrer Groq et Gemini. Tier gratuit d\'API disponible.',
    cta: 'Lire le Guide',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTOs, VP Engineering, 50-500 employés',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-fr-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire : Construisez un SaaS avec IA Intégrée',
    description: 'Templates Next.js + API IA + Stripe. Tout ce qu\'il faut pour lancer un SaaS.',
    cta: 'Commencer',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Fondateurs, CTOs, startups tech',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-fr-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'Tier Gratuit API IA — Testez Aujourd\'hui',
    description: 'Groq et Gemini via une API. Gratuit pour démarrer. Intégration en 5 minutes. Docs et SDKs inclus.',
    cta: 'Essayer Gratuitement',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech leads, développeurs, 25-45 ans',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-fr-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Templates Next.js pour Votre Projet IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — prêts pour la production. Auth, paiements, IA inclus.',
    cta: 'Explorer les Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Équipes de développement, startups',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-fr-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Simplifiez Votre Stack IA',
    description: 'Une API pour Groq et Gemini. Plus de gestion multi-clés fournisseur. Tier gratuit disponible.',
    cta: 'En Savoir Plus',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering managers, CTOs',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-fr-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API IA — Gratuit pour Démarrer, Payez en Croissant',
    description: 'Modèles Groq et Gemini. Pas de frais initiaux. Voir nos tarifs.',
    cta: 'Voir les Tarifs',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Décideurs tech, budget serré',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-fr-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Template Portfolio Développeur',
    description: 'Portfolio Next.js épuré et responsive. 50+ composants. Mode sombre. Déployez aujourd\'hui.',
    cta: 'Voir le Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Développeurs, freelances',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-fr-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API IA Conforme RGPD pour l\'Europe',
    description: 'AI-Empire construite avec la protection des données. Tier gratuit. Facturation Stripe. Doc incluse.',
    cta: 'En Savoir Plus',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'Entreprises tech européennes, rôles conformité',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
