// ============================================
// AI-EMPIRE — Paid Ads Copy (Italian)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Ricerca (4) ===
  {
    id: 'g-it-01',
    platform: 'google',
    type: 'search',
    headline: 'API AI con Groq e Gemini — Tier Gratuito',
    description: 'API unificata per modelli Groq e Gemini. Gratis per iniziare. Fatturazione Stripe.',
    cta: 'Prova Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Sviluppatori che cercano provider di API AI',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-it-02',
    platform: 'google',
    type: 'search',
    headline: 'Template SaaS Next.js — Lancia Più Velocemente',
    description: 'Template Next.js 14 pronti per la produzione con IA integrata. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Sviluppatori che cercano template Next.js',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-it-03',
    platform: 'google',
    type: 'search',
    headline: 'Integra l\'IA nella Tua App in Minuti',
    description: 'Connettiti a Groq e Gemini attraverso un\'API. Setup in 5 minuti. Documentazione inclusa.',
    cta: 'Leggi la Doc',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech lead, sviluppatori full-stack',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-it-04',
    platform: 'google',
    type: 'search',
    headline: 'Kit Starter SaaS con Stripe e IA',
    description: 'Template Next.js con fatturazione Stripe, auth e API IA. Pronto per il deploy.',
    cta: 'Inizia Ora',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'Fondatori di SaaS, indie hacker',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-it-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Template E-Commerce per Next.js',
    description: 'Template negozio IA con integrazione Stripe. Costruito con Next.js 14 e Tailwind.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Visitatori del sito, interesse e-commerce',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-it-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — Template Blog SEO Ottimizzato',
    description: 'Template blog Next.js con MDX, dark mode e feed RSS. Pronto per la produzione.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Creator di contenuti, blogger',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-it-07',
    platform: 'google',
    type: 'display',
    headline: 'Costruisci App IA con Groq e Gemini',
    description: 'Un\'API, più modelli IA. Tier gratuito. SDK JavaScript e Python.',
    cta: 'Esplora l\'API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'Sviluppatori IA, ingegneri ML',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-it-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'Template SaaS con IA — Gratis per Iniziare',
    description: 'Template Next.js 14 con API IA, Stripe e autenticazione. Deploy oggi.',
    cta: 'Prova Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'Fondatori di SaaS, sviluppatori',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-it-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Template Portfolio Sviluppatore',
    description: 'Presenta il tuo lavoro con un portfolio Next.js pulito. 50+ componenti, dark mode.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Sviluppatori, freelancer',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-it-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'Prezzi API IA — Gratis per Iniziare',
    description: 'API IA pay-as-you-go. Modelli Groq e Gemini. Nessun costo iniziale. Vedi i prezzi.',
    cta: 'Vedi i Prezzi',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Sviluppatori attenti ai costi',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-it-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Costruisci App IA Senza Complessità',
    description: 'AI-Empire ti dà un\'API unificata per Groq e Gemini. Gratis, senza carta di credito.',
    cta: 'Scopri di Più',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Sviluppatori, 25-45, interessi: IA, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-it-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Template Next.js per SaaS con IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — pronti con Stripe e IA integrata.',
    cta: 'Esplora i Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'Sviluppatori React/Next.js, 22-40',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-it-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'API IA per il Tuo Prossimo Progetto',
    description: 'Connettiti a Groq e Gemini attraverso un\'API. SDK JS e Python. Doc inclusa.',
    cta: 'Leggi la Doc',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Sviluppatori, early adopters, 20-38',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-it-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Cosa Puoi Costruire con AI-Empire',
    description: 'Chatbot, generatori di contenuti, assistenti codice — con Groq e Gemini via un\'API.',
    cta: 'Vedi gli Esempi',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Appassionati di tech, 18-35',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-it-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Inizia il Tuo SaaS IA Oggi',
    description: 'Template Next.js con Stripe, auth e API IA. Tier gratuito. Deploy in minuti.',
    cta: 'Inizia Ora',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Visitatori del sito, ultimi 7 giorni',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-it-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Il Tuo Negozio IA',
    description: 'Template e-commerce con raccomandazioni IA e checkout Stripe. Personalizzabile.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'Interesse e-commerce, visitatori del sito',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-it-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Confronta i Nostri Prezzi API',
    description: 'Tier gratuito, poi pay-as-you-go. Modelli Groq e Gemini. Confronta i prezzi.',
    cta: 'Vedi i Prezzi',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Sviluppatori attenti al prezzo',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-it-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Ancora Indeciso su AI-Empire?',
    description: 'Tier gratuito disponibile. Senza carta di credito. Prova la nostra API e i template oggi.',
    cta: 'Prova Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Visitatori che hanno visto i prezzi senza convertire',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-it-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Crea il Tuo Blog IA',
    description: 'Template blog SEO ottimizzato con MDX e dark mode. Pronto per la produzione.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Visitatori della pagina template',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-it-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Pronto per il Deploy della Tua App IA?',
    description: 'I nostri template includono auth, pagamenti e integrazione IA. Inizia su solide basi.',
    cta: 'Inizia Ora',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Visitatori doc, non convertiti',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-it-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'API IA per Team SaaS — Groq e Gemini',
    description: 'API unificata per Groq e Gemini. Tier gratuito, integrazione Stripe, conforme GDPR. Per i team.',
    cta: 'Scopri di Più',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTO, Lead Dev, 10-200 dipendenti',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-it-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Lancia il Tuo SaaS IA Più Velocemente',
    description: 'Template Next.js 14 con auth, pagamenti e IA. Pronti per la produzione. Vedi i template.',
    cta: 'Vedi i Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Manager, Engineering Lead',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-it-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Come Aggiungere l\'IA al Tuo Prodotto',
    description: 'Guida passo-passo per integrare Groq e Gemini. Tier gratuito API disponibile.',
    cta: 'Leggi la Guida',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTO, VP Engineering, 50-500 dipendenti',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-it-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: Costruisci SaaS con IA Integrata',
    description: 'Template Next.js + API IA + Stripe. Tutto ciò che serve per lanciare un SaaS.',
    cta: 'Inizia Ora',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Fondatori, CTO, startup tech',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-it-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'Tier Gratuito API IA — Prova Oggi',
    description: 'Groq e Gemini via un\'API. Gratis per iniziare. Integrazione in 5 minuti. Doc e SDK inclusi.',
    cta: 'Prova Gratis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech lead, sviluppatori, 25-45',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-it-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Template Next.js per il Tuo Progetto IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — pronti per la produzione. Auth, pagamenti, IA inclusi.',
    cta: 'Esplora i Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Team di sviluppo, startup',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-it-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Semplifica il Tuo Stack IA',
    description: 'Un\'API per Groq e Gemini. Niente più gestione multi-key. Tier gratuito disponibile.',
    cta: 'Scopri di Più',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering manager, CTO',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-it-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API IA — Gratis per Iniziare, Paga Crescendo',
    description: 'Modelli Groq e Gemini. Nessun costo iniziale. Vedi i prezzi.',
    cta: 'Vedi i Prezzi',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Decision maker tech, attenti al budget',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-it-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Template Portfolio Sviluppatore',
    description: 'Portfolio Next.js pulito e responsive. 50+ componenti. Dark mode. Deploy oggi.',
    cta: 'Vedi Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Sviluppatori, freelancer',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-it-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API IA Conforme GDPR per l\'Europa',
    description: 'AI-Empire costruita con la privacy dei dati. Tier gratuito. Fatturazione Stripe. Doc inclusa.',
    cta: 'Scopri di Più',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: 'Aziende tech europee, ruoli compliance',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
