// ============================================
// AI-EMPIRE — Paid Ads Copy (Japanese)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === 検索 (4) ===
  {
    id: 'g-ja-01',
    platform: 'google',
    type: 'search',
    headline: 'Groq・Gemini対応AI API — 無料プランあり',
    description: 'GroqとGeminiを統一APIで利用。無料で始められる。Stripe決済対応。',
    cta: '無料で試す',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'AI APIプロバイダーを探す開発者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-ja-02',
    platform: 'google',
    type: 'search',
    headline: 'Next.js SaaSテンプレート — 素早くローンチ',
    description: 'Next.js 14のプロダクション対応テンプレート。AI統合済み。NeuraStore、NeuraBlog、NeuraPortfolio。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Next.jsテンプレートを探す開発者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-ja-03',
    platform: 'google',
    type: 'search',
    headline: 'アプリにAIを5分で統合',
    description: 'GroqとGeminiに1つのAPIで接続。5分でセットアップ。ドキュメント付き。',
    cta: 'ドキュメントを読む',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'テックリード、フルスタック開発者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-ja-04',
    platform: 'google',
    type: 'search',
    headline: 'Stripe統合済み SaaSスターターキット',
    description: 'Next.jsテンプレートにStripe請求、認証、AI APIを統合。デプロイ可能。',
    cta: '始める',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'SaaS創業者、インディーハッカー',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === ディスプレイ (3) ===
  {
    id: 'g-ja-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Next.js向けEコマステンプレート',
    description: 'AI搭載ストアテンプレート。Stripe統合。Next.js 14とTailwindで構築。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'サイト訪問者、Eコマス関心',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-ja-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — SEO最適化ブログテンプレート',
    description: 'Next.jsブログテンプレート。MDX、ダークモード、RSSフィード対応。プロダクション対応。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'コンテンツクリエイター、ブロガー',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-ja-07',
    platform: 'google',
    type: 'display',
    headline: 'Groq・GeminiでAIアプリを構築',
    description: '1つのAPIで複数のAIモデルにアクセス。無料プランあり。JavaScript/Python SDK対応。',
    cta: 'APIを探索',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'AI開発者、MLエンジニア',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === パフォーマンスマックス (3) ===
  {
    id: 'g-ja-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI搭載SaaSテンプレート — 無料で始められる',
    description: 'Next.js 14テンプレートにAI API、Stripe、認証を統合。今日からデプロイ。',
    cta: '無料で試す',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'SaaS創業者、開発者',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-ja-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — 開発者ポートフォリオテンプレート',
    description: 'Next.jsでワークを紹介。50以上のコンポーネント、レスポンシブ、ダークモード。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: '開発者、フリーランス',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-ja-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI API料金 — 無料で始められる',
    description: '従量課金制AI API。GroqとGeminiモデル。初期費用なし。料金を見る。',
    cta: '料金を見る',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'コストを重視する開発者',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === 認知 (4) ===
  {
    id: 'fb-ja-01',
    platform: 'facebook',
    type: 'awareness',
    headline: '複雑さなしでAIアプリを構築',
    description: 'AI-EmpireはGroqとGeminiの統一APIを提供。無料、クレジットカード不要。',
    cta: '詳しく見る',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: '開発者、25-45歳、関心：AI、React、Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-ja-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI統合Next.js SaaSテンプレート',
    description: 'NeuraStore、NeuraBlog、NeuraPortfolio — StripeとAI統合済み。',
    cta: 'テンプレートを探索',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'React/Next.js開発者、22-40歳',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-ja-03',
    platform: 'facebook',
    type: 'awareness',
    headline: '次のプロジェクト向けのAI API',
    description: 'GroqとGeminiに1つのAPIで接続。JS/Python SDK。ドキュメント付き。',
    cta: 'ドキュメントを読む',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: '開発者、アーリーアダプター、20-38歳',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-ja-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI-Empireでできること',
    description: 'チャットボット、コンテンツ生成、コードアシスタント — GroqとGeminiで1つのAPIから。',
    cta: '例を見る',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'テック愛好者、18-35歳',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === コンバージョン (3) ===
  {
    id: 'fb-ja-05',
    platform: 'facebook',
    type: 'conversion',
    headline: '今日からAI SaaSを始めよう',
    description: 'Next.jsテンプレートにStripe、認証、AI APIを統合。無料プラン。数分でデプロイ。',
    cta: '始める',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'サイト訪問者、過去7日間',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-ja-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — AIストアフロント',
    description: 'AI商品レコメンデーション付きEコマステンプレート。Stripe決済。カスタマイズ可能。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'Eコマス関心、サイト訪問者',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-ja-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'API料金を比較する',
    description: '無料プランあり、その後従量課金。GroqとGeminiモデル。料金を比較。',
    cta: '料金を見る',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'コストを重視する開発者',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === リターゲティング (3) ===
  {
    id: 'fb-ja-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'AI-Empireについてまだ考えていますか？',
    description: '無料プラン利用可能。クレジットカード不要。今日APIとテンプレートを試そう。',
    cta: '無料で試す',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: '料金ページを訪問したがコンバートしなかった訪問者',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-ja-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — AIブログを作ろう',
    description: 'SEO最適化ブログテンプレート。MDXとダークモード対応。プロダクション対応。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'テンプレートページ訪問者',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-ja-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'AIアプリのデプロイ準備はできましたか？',
    description: 'テンプレートには認証、決済、AI統合が含まれています。堅実な基盤から始めましょう。',
    cta: '始める',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'ドキュメント訪問者、未コンバート',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === スポンサードコンテンツ (4) ===
  {
    id: 'li-ja-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'SaaSチーム向けのAI API — Groq & Gemini',
    description: 'GroqとGeminiの統一API。無料プラン、Stripe統合、GDPR準拠。チーム向けに構築。',
    cta: '詳しく見る',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTO、リードデブ、10-200従業員',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-ja-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI SaaSをより速くローンチ',
    description: 'Next.js 14テンプレートに認証、決済、AIを統合。プロダクション対応。テンプレートを見る。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'プロダクトマネージャー、エンジニアリングリード',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-ja-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'プロダクトにAIを追加する方法',
    description: 'GroqとGeminiを統合するステップバイステップガイド。無料APIプランあり。',
    cta: 'ガイドを読む',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTO、VPエンジニアリング、50-500従業員',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-ja-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: 統合AIでSaaSを構築',
    description: 'Next.jsテンプレート + AI API + Stripe。SaaSローンチに必要なすべて。',
    cta: '始める',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: '創業者、CTO、テックスタートアップ',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === メッセージ広告 (3) ===
  {
    id: 'li-ja-05',
    platform: 'linkedin',
    type: 'message',
    headline: '無料AI APIプラン — 今日試す',
    description: '1つのAPIでGroqとGemini。無料で始められる。5分で統合。ドキュメントとSDK付き。',
    cta: '無料で試す',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'テックリード、開発者、25-45歳',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-ja-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'AIプロジェクト向けNext.jsテンプレート',
    description: 'NeuraStore、NeuraBlog、NeuraPortfolio — プロダクション対応。認証、決済、AI込み。',
    cta: 'テンプレートを探索',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: '開発チーム、スタートアップ',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-ja-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'AIスタックをシンプルに',
    description: 'GroqとGeminiの1つのAPI。複数プロバイダーキーの管理が不要に。無料プランあり。',
    cta: '詳しく見る',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'エンジニアリングマネージャー、CTO',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === ダイナミック広告 (3) ===
  {
    id: 'li-ja-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'AI API — 無料で始め、成長に合わせて支払い',
    description: 'GroqとGeminiモデル。初期費用なし。料金を見る。',
    cta: '料金を見る',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'テック意思決定者、コスト意識',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-ja-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — 開発者ポートフォリオテンプレート',
    description: 'シンプルでレスポンシブなNext.jsポートフォリオ。50以上のコンポーネント。ダークモード。今日デプロイ。',
    cta: 'テンプレートを見る',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: '開発者、フリーランス',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-ja-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: '欧州向けGDPR準拠のAI API',
    description: 'AI-Empireはデータプライバシーを重視して構築。無料プラン。Stripe請求。ドキュメント付き。',
    cta: '詳しく見る',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: '欧州テック企業、コンプライアンス担当者',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
