// ============================================
// AI-EMPIRE — Paid Ads Copy (Korean)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === 검색 (4) ===
  {
    id: 'g-ko-01',
    platform: 'google',
    type: 'search',
    headline: 'Groq & Gemini AI API — 무료 플랜 제공',
    description: 'Groq와 Gemini를 통합 API로 제공. 무료로 시작 가능. Stripe 결제.',
    cta: '무료로 시작',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'AI API 제공자를 찾는 개발자',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-ko-02',
    platform: 'google',
    type: 'search',
    headline: 'Next.js SaaS 템플릿 — 더 빠른 출시',
    description: 'Next.js 14 프로덕션 준비 템플릿. AI 통합. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Next.js 템플릿을 찾는 개발자',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-ko-03',
    platform: 'google',
    type: 'search',
    headline: '앱에 AI를 5분 만에 통합',
    description: 'Groq와 Gemini에 하나의 API로 연결. 5분 셋업. 문서 포함.',
    cta: '문서 읽기',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: '테크 리드, 풀스택 개발자',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-ko-04',
    platform: 'google',
    type: 'search',
    headline: 'Stripe 통합 SaaS 스타터 키트',
    description: 'Next.js 템플릿에 Stripe 결제, 인증, AI API 통합. 배포 준비.',
    cta: '시작하기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'SaaS 창업자, 인디 해커',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === 디스플레이 (3) ===
  {
    id: 'g-ko-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Next.js 이커머스 템플릿',
    description: 'AI 기반 스토어 템플릿. Stripe 통합. Next.js 14와 Tailwind로 제작.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: '사이트 방문자, 이커머스 관심',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-ko-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — SEO 최적화 블로그 템플릿',
    description: 'Next.js 블로그 템플릿. MDX, 다크 모드, RSS 피드. 프로덕션 준비.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: '콘텐츠 크리에이터, 블로거',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-ko-07',
    platform: 'google',
    type: 'display',
    headline: 'Groq & Gemini로 AI 앱 만들기',
    description: '하나의 API, 여러 AI 모델. 무료 플랜. JavaScript/Python SDK.',
    cta: 'API 탐색',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'AI 개발자, ML 엔지니어',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === 퍼포먼스 맥스 (3) ===
  {
    id: 'g-ko-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI 기반 SaaS 템플릿 — 무료로 시작',
    description: 'Next.js 14 템플릿에 AI API, Stripe, 인증 통합. 오늘 배포.',
    cta: '무료로 시작',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'SaaS 창업자, 개발자',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-ko-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — 개발자 포트폴리오 템플릿',
    description: 'Next.js로 작업을 소개. 50개 이상 컴포넌트, 반응형, 다크 모드.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: '개발자, 프리랜서',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-ko-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI API 가격 — 무료로 시작',
    description: '종량제 AI API. Groq와 Gemini 모델. 초기 비용 없음. 가격 보기.',
    cta: '가격 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: '비용을 고려하는 개발자',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === 인지도 (4) ===
  {
    id: 'fb-ko-01',
    platform: 'facebook',
    type: 'awareness',
    headline: '복잡함 없이 AI 앱 만들기',
    description: 'AI-Empire는 Groq와 Gemini의 통합 API를 제공. 무료, 신용카드 불필요.',
    cta: '자세히 보기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: '개발자, 25-45세, 관심사: AI, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-ko-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI 통합 Next.js SaaS 템플릿',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — Stripe와 AI 통합.',
    cta: '템플릿 탐색',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'React/Next.js 개발자, 22-40세',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-ko-03',
    platform: 'facebook',
    type: 'awareness',
    headline: '다음 프로젝트를 위한 AI API',
    description: 'Groq와 Gemini에 하나의 API로 연결. JS/Python SDK. 문서 포함.',
    cta: '문서 읽기',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: '개발자, 얼리 어답터, 20-38세',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-ko-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI-Empire로 만들 수 있는 것들',
    description: '챗봇, 콘텐츠 생성기, 코드 어시스턴트 — Groq와 Gemini API로.',
    cta: '예시 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: '테크 매니아, 18-35세',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === 전환 (3) ===
  {
    id: 'fb-ko-05',
    platform: 'facebook',
    type: 'conversion',
    headline: '오늘 AI SaaS를 시작하세요',
    description: 'Next.js 템플릿에 Stripe, 인증, AI API 통합. 무료 플랜. 수 분 내 배포.',
    cta: '시작하기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: '사이트 방문자, 최근 7일',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-ko-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — AI 스토어프론트',
    description: 'AI 상품 추천 이커머스 템플릿. Stripe 결제. 커스터마이즈 가능.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: '이커머스 관심, 사이트 방문자',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-ko-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'API 가격 비교',
    description: '무료 플랜에서 종량제까지. Groq와 Gemini 모델. 가격 비교.',
    cta: '가격 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: '비용을 고려하는 개발자',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === 리타겟팅 (3) ===
  {
    id: 'fb-ko-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: '아직 AI-Empire를 고려하고 계신가요?',
    description: '무료 플랜 가능. 신용카드 불필요. 오늘 API와 템플릿을 시도하세요.',
    cta: '무료로 시작',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: '가격 페이지를 방문했지만 전환하지 않은 방문자',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-ko-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — AI 블로그 만들기',
    description: 'SEO 최적화 블로그 템플릿. MDX와 다크 모드. 프로덕션 준비.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: '템플릿 페이지 방문자',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-ko-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'AI 앱 배포 준비가 되셨나요?',
    description: '템플릿에 인증, 결제, AI 통합이 포함. 견고한 기반에서 시작하세요.',
    cta: '시작하기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: '문서 방문자, 미전환자',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === 스폰서 콘텐츠 (4) ===
  {
    id: 'li-ko-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'SaaS 팀을 위한 AI API — Groq & Gemini',
    description: 'Groq와 Gemini 통합 API. 무료 플랜, Stripe 통합, GDPR 준수. 팀을 위해 구축.',
    cta: '자세히 보기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTO, 리드 개발자, 10-200명',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-ko-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI SaaS를 더 빠르게 출시',
    description: 'Next.js 14 템플릿에 인증, 결제, AI 통합. 프로덕션 준비. 템플릿 보기.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: '프로덕트 매니저, 엔지니어링 리드',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-ko-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: '제품에 AI 추가하는 방법',
    description: 'Groq와 Gemini 통합 단계별 가이드. 무료 API 플랜 가능.',
    cta: '가이드 읽기',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTO, VP 엔지니어링, 50-500명',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-ko-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: 통합 AI로 SaaS 구축',
    description: 'Next.js 템플릿 + AI API + Stripe. SaaS 출시에 필요한 모든 것.',
    cta: '시작하기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: '창업자, CTO, 테크 스타트업',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === 메시지 광고 (3) ===
  {
    id: 'li-ko-05',
    platform: 'linkedin',
    type: 'message',
    headline: '무료 AI API 플랜 — 오늘 시도',
    description: '하나의 API로 Groq와 Gemini. 무료 시작. 5분 통합. 문서와 SDK 포함.',
    cta: '무료로 시작',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: '테크 리드, 개발자, 25-45세',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-ko-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'AI 프로젝트용 Next.js 템플릿',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — 프로덕션 준비. 인증, 결제, AI 포함.',
    cta: '템플릿 탐색',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: '개발 팀, 스타트업',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-ko-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'AI 스택을 간소화',
    description: 'Groq와 Gemini를 위한 하나의 API. 다중 프로바이더 키 관리 불필요. 무료 플랜.',
    cta: '자세히 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: '엔지니어링 매니저, CTO',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === 다이나믹 광고 (3) ===
  {
    id: 'li-ko-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'AI API — 무료로 시작, 성장에 맞춰 지불',
    description: 'Groq와 Gemini 모델. 초기 비용 없음. 가격 보기.',
    cta: '가격 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: '테크 의사결정자, 비용 인식',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-ko-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — 개발자 포트폴리오 템플릿',
    description: '깔끔하고 반응형 Next.js 포트폴리오. 50개 이상 컴포넌트. 다크 모드. 오늘 배포.',
    cta: '템플릿 보기',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: '개발자, 프리랜서',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-ko-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: '유럽 GDPR 준수 AI API',
    description: 'AI-Empire는 데이터 프라이버시를 고려하여 구축. 무료 플랜. Stripe 결제. 문서 포함.',
    cta: '자세히 보기',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: '유럽 테크 기업, 컴플라이언스 역할',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
