// ============================================
// AI-EMPIRE — Paid Ads Copy (Brazilian Portuguese)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === Busca (4) ===
  {
    id: 'g-pt-01',
    platform: 'google',
    type: 'search',
    headline: 'API de IA com Groq e Gemini — Tier Gratuito',
    description: 'API unificada para modelos Groq e Gemini. Grátis para começar. Faturamento via Stripe.',
    cta: 'Testar Grátis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: 'Desenvolvedores buscando provedores de API de IA',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-pt-02',
    platform: 'google',
    type: 'search',
    headline: 'Templates SaaS Next.js — Lance Mais Rápido',
    description: 'Templates Next.js 14 prontos para produção com IA integrada. NeuraStore, NeuraBlog, NeuraPortfolio.',
    cta: 'Ver Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: 'Desenvolvedores buscando templates Next.js',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-pt-03',
    platform: 'google',
    type: 'search',
    headline: 'Integre IA no Seu App em Minutos',
    description: 'Conecte-se ao Groq e Gemini via uma API. Setup em 5 minutos. Documentação incluída.',
    cta: 'Ler Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: 'Tech leads, desenvolvedores full-stack',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-pt-04',
    platform: 'google',
    type: 'search',
    headline: 'Kit Starter SaaS com Stripe e IA',
    description: 'Template Next.js com faturamento Stripe, auth e API de IA. Pronto para deploy.',
    cta: 'Começar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'Fundadores de SaaS, indie hackers',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === Display (3) ===
  {
    id: 'g-pt-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Template E-Commerce para Next.js',
    description: 'Template de loja com IA e integração Stripe. Construído com Next.js 14 e Tailwind.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: 'Visitantes do site, interesse em e-commerce',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-pt-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — Template Blog Otimizado para SEO',
    description: 'Template de blog Next.js com MDX, modo escuro e feed RSS. Pronto para produção.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: 'Criadores de conteúdo, blogueiros',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-pt-07',
    platform: 'google',
    type: 'display',
    headline: 'Crie Apps de IA com Groq e Gemini',
    description: 'Uma API, vários modelos de IA. Tier gratuito. SDKs para JavaScript e Python.',
    cta: 'Explorar API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'Desenvolvedores de IA, engenheiros ML',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === Performance Max (3) ===
  {
    id: 'g-pt-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'Templates SaaS com IA — Grátis para Começar',
    description: 'Templates Next.js 14 com API de IA, Stripe e autenticação. Deploy hoje.',
    cta: 'Testar Grátis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'Fundadores de SaaS, desenvolvedores',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-pt-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — Template Portfólio Dev',
    description: 'Apresente seu trabalho com um portfólio Next.js limpo. 50+ componentes, modo escuro.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: 'Desenvolvedores, freelancers',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-pt-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'Preços API de IA — Grátis para Começar',
    description: 'API de IA pay-as-you-go. Modelos Groq e Gemini. Sem custos iniciais. Ver preços.',
    cta: 'Ver Preços',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: 'Desenvolvedores conscientes de custos',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === Awareness (4) ===
  {
    id: 'fb-pt-01',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Crie Apps de IA Sem Complexidade',
    description: 'AI-Empire te dá uma API unificada para Groq e Gemini. Grátis, sem cartão de crédito.',
    cta: 'Saiba Mais',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: 'Desenvolvedores, 25-45, interesses: IA, React, Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-pt-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'Templates Next.js para SaaS com IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — prontos com Stripe e IA integrada.',
    cta: 'Explorar Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'Desenvolvedores React/Next.js, 22-40',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-pt-03',
    platform: 'facebook',
    type: 'awareness',
    headline: 'API de IA para Seu Próximo Projeto',
    description: 'Conecte-se ao Groq e Gemini via uma API. SDKs para JS e Python. Docs incluídos.',
    cta: 'Ler Docs',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: 'Desenvolvedores, early adopters, 20-38',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-pt-04',
    platform: 'facebook',
    type: 'awareness',
    headline: 'O Que Você Pode Construir com AI-Empire',
    description: 'Chatbots, geradores de conteúdo, assistentes de código — com Groq e Gemini via uma API.',
    cta: 'Ver Exemplos',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: 'Entusiastas de tech, 18-35',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === Conversion (3) ===
  {
    id: 'fb-pt-05',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Comece Seu SaaS de IA Hoje',
    description: 'Templates Next.js com Stripe, auth e API de IA. Tier gratuito. Deploy em minutos.',
    cta: 'Começar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: 'Visitantes do site, últimos 7 dias',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-pt-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — Sua Loja com IA',
    description: 'Template e-commerce com recomendações de IA e checkout Stripe. Personalizável.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: 'Interesse em e-commerce, visitantes do site',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-pt-07',
    platform: 'facebook',
    type: 'conversion',
    headline: 'Compare Nossos Preços de API',
    description: 'Tier gratuito, depois pay-as-you-go. Modelos Groq e Gemini. Compare preços.',
    cta: 'Ver Preços',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: 'Desenvolvedores sensíveis a preço',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === Retargeting (3) ===
  {
    id: 'fb-pt-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Ainda Pensando no AI-Empire?',
    description: 'Tier gratuito disponível. Sem cartão de crédito. Teste nossa API e templates hoje.',
    cta: 'Testar Grátis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: 'Visitantes que viram preços sem converter',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-pt-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — Crie Seu Blog com IA',
    description: 'Template blog otimizado para SEO com MDX e modo escuro. Pronto para produção.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: 'Visitantes da página de templates',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-pt-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'Pronto para Fazer Deploy da Sua App IA?',
    description: 'Nossos templates incluem auth, pagamentos e integração IA. Comece com uma base sólida.',
    cta: 'Começar',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: 'Visitantes de docs, não conversores',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === Sponsored Content (4) ===
  {
    id: 'li-pt-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'API de IA para Equipes SaaS — Groq e Gemini',
    description: 'API unificada para Groq e Gemini. Tier gratuito, integração Stripe, conforme LGPD. Feita para equipes.',
    cta: 'Saiba Mais',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTOs, Lead Devs, 10-200 funcionários',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-pt-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Lance Seu SaaS de IA Mais Rápido',
    description: 'Templates Next.js 14 com auth, pagamentos e IA. Prontos para produção. Ver templates.',
    cta: 'Ver Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: 'Product Managers, Engineering Leads',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-pt-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'Como Adicionar IA ao Seu Produto',
    description: 'Guia passo a passo para integrar Groq e Gemini. Tier gratuito de API disponível.',
    cta: 'Ler Guia',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTOs, VP Engineering, 50-500 funcionários',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-pt-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire: Construa SaaS com IA Integrada',
    description: 'Templates Next.js + API de IA + Stripe. Tudo que você precisa para lançar um SaaS.',
    cta: 'Começar',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: 'Fundadores, CTOs, startups tech',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === Message Ads (3) ===
  {
    id: 'li-pt-05',
    platform: 'linkedin',
    type: 'message',
    headline: 'Tier Gratuito API de IA — Teste Hoje',
    description: 'Groq e Gemini via uma API. Grátis para começar. Integração em 5 minutos. Docs e SDKs incluídos.',
    cta: 'Testar Grátis',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: 'Tech leads, desenvolvedores, 25-45',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-pt-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'Templates Next.js para Seu Projeto de IA',
    description: 'NeuraStore, NeuraBlog, NeuraPortfolio — prontos para produção. Auth, pagamentos, IA incluídos.',
    cta: 'Explorar Templates',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: 'Equipes de desenvolvimento, startups',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-pt-07',
    platform: 'linkedin',
    type: 'message',
    headline: 'Simplifique Seu Stack de IA',
    description: 'Uma API para Groq e Gemini. Sem gerenciar múltiplas chaves de provedor. Tier gratuito disponível.',
    cta: 'Saiba Mais',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: 'Engineering managers, CTOs',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === Dynamic Ads (3) ===
  {
    id: 'li-pt-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API de IA — Grátis para Começar, Pague ao Crescer',
    description: 'Modelos Groq e Gemini. Sem custos iniciais. Ver preços.',
    cta: 'Ver Preços',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: 'Decisores tech, orçamento consciente',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-pt-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — Template Portfólio Dev',
    description: 'Portfólio Next.js limpo e responsivo. 50+ componentes. Modo escuro. Deploy hoje.',
    cta: 'Ver Template',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: 'Desenvolvedores, freelancers',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-pt-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'API de IA Conforme LGPD para o Brasil',
    description: 'AI-Empire construída com privacidade de dados. Tier gratuito. Faturamento Stripe. Docs incluídos.',
    cta: 'Saiba Mais',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=lgpd',
    targetAudience: 'Empresas tech brasileiras, cargos de compliance',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=lgpd',
  },
];
