// ============================================
// AI-EMPIRE — Paid Ads Copy (Simplified Chinese)
// ============================================

import type { AdCopy } from '../paid-ads';

export const googleAds: AdCopy[] = [
  // === 搜索广告 (4) ===
  {
    id: 'g-zh-01',
    platform: 'google',
    type: 'search',
    headline: 'Groq & Gemini AI API — 免费计划',
    description: 'Groq和Gemini统一API。免费开始使用。Stripe计费。',
    cta: '免费试用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=api',
    targetAudience: '寻找AI API提供商的开发者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=api',
  },
  {
    id: 'g-zh-02',
    platform: 'google',
    type: 'search',
    headline: 'Next.js SaaS 模板 — 更快上线',
    description: 'Next.js 14 生产就绪模板。内置AI集成。NeuraStore、NeuraBlog、NeuraPortfolio。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=google&utm_medium=search&utm_campaign=templates',
    targetAudience: '寻找Next.js模板的开发者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=templates',
  },
  {
    id: 'g-zh-03',
    platform: 'google',
    type: 'search',
    headline: '5分钟内将AI集成到应用中',
    description: '通过一个API连接Groq和Gemini。5分钟设置。包含文档。',
    cta: '阅读文档',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=search&utm_campaign=integration',
    targetAudience: '技术负责人、全栈开发者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=integration',
  },
  {
    id: 'g-zh-04',
    platform: 'google',
    type: 'search',
    headline: '集成Stripe的AI SaaS启动套件',
    description: 'Next.js模板集成Stripe计费、认证和AI API。可部署。',
    cta: '开始使用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=search&utm_campaign=starter',
    targetAudience: 'SaaS创始人、独立开发者',
    trackingParams: '?utm_source=google&utm_medium=search&utm_campaign=starter',
  },
  // === 展示广告 (3) ===
  {
    id: 'g-zh-05',
    platform: 'google',
    type: 'display',
    headline: 'NeuraStore — Next.js电商模板',
    description: 'AI驱动的商店模板。Stripe集成。基于Next.js 14和Tailwind构建。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=google&utm_medium=display&utm_campaign=neurastore',
    targetAudience: '网站访客、电商兴趣',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurastore',
  },
  {
    id: 'g-zh-06',
    platform: 'google',
    type: 'display',
    headline: 'NeuraBlog — SEO优化博客模板',
    description: 'Next.js博客模板。支持MDX、暗色模式、RSS。生产就绪。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=google&utm_medium=display&utm_campaign=neurablog',
    targetAudience: '内容创作者、博主',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=neurablog',
  },
  {
    id: 'g-zh-07',
    platform: 'google',
    type: 'display',
    headline: '使用Groq和Gemini构建AI应用',
    description: '一个API，多个AI模型。免费计划。JavaScript/Python SDK。',
    cta: '探索API',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=google&utm_medium=display&utm_campaign=api',
    targetAudience: 'AI开发者、ML工程师',
    trackingParams: '?utm_source=google&utm_medium=display&utm_campaign=api',
  },
  // === 效果最大化 (3) ===
  {
    id: 'g-zh-08',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI SaaS模板 — 免费开始',
    description: 'Next.js 14模板集成AI API、Stripe和认证。今天即可部署。',
    cta: '免费试用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
    targetAudience: 'SaaS创始人、开发者',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pmax',
  },
  {
    id: 'g-zh-09',
    platform: 'google',
    type: 'performance_max',
    headline: 'NeuraPortfolio — 开发者作品集模板',
    description: '用简洁的Next.js作品集展示你的工作。50+组件、响应式、暗色模式。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
    targetAudience: '开发者、自由职业者',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=portfolio',
  },
  {
    id: 'g-zh-10',
    platform: 'google',
    type: 'performance_max',
    headline: 'AI API定价 — 免费开始',
    description: '按量付费AI API。Groq和Gemini模型。无前期费用。查看价格。',
    cta: '查看价格',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
    targetAudience: '注重成本的开发者',
    trackingParams: '?utm_source=google&utm_medium=performance_max&utm_campaign=pricing',
  },
];

export const facebookAds: AdCopy[] = [
  // === 品牌认知 (4) ===
  {
    id: 'fb-zh-01',
    platform: 'facebook',
    type: 'awareness',
    headline: '无复杂性构建AI应用',
    description: 'AI-Empire提供Groq和Gemini的统一API。免费，无需信用卡。',
    cta: '了解更多',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
    targetAudience: '开发者、25-45岁、兴趣：AI、React、Next.js',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=intro',
  },
  {
    id: 'fb-zh-02',
    platform: 'facebook',
    type: 'awareness',
    headline: 'AI集成的Next.js SaaS模板',
    description: 'NeuraStore、NeuraBlog、NeuraPortfolio — 内置Stripe和AI。',
    cta: '探索模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
    targetAudience: 'React/Next.js开发者、22-40岁',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=templates',
  },
  {
    id: 'fb-zh-03',
    platform: 'facebook',
    type: 'awareness',
    headline: '为你的下一个项目提供AI API',
    description: '通过一个API连接Groq和Gemini。JS/Python SDK。包含文档。',
    cta: '阅读文档',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
    targetAudience: '开发者、早期采用者、20-38岁',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=docs',
  },
  {
    id: 'fb-zh-04',
    platform: 'facebook',
    type: 'awareness',
    headline: '用AI-Empire可以构建什么',
    description: '聊天机器人、内容生成器、代码助手 — 通过Groq和Gemini API。',
    cta: '查看示例',
    landingPage: 'https://ai-empire-steel.vercel.app/docs/examples?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
    targetAudience: '技术爱好者、18-35岁',
    trackingParams: '?utm_source=facebook&utm_medium=awareness&utm_campaign=examples',
  },
  // === 转化 (3) ===
  {
    id: 'fb-zh-05',
    platform: 'facebook',
    type: 'conversion',
    headline: '今天开始你的AI SaaS',
    description: 'Next.js模板集成Stripe、认证和AI API。免费计划。数分钟部署。',
    cta: '开始使用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
    targetAudience: '网站访客、过去7天',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=start',
  },
  {
    id: 'fb-zh-06',
    platform: 'facebook',
    type: 'conversion',
    headline: 'NeuraStore — 你的AI商店',
    description: 'AI商品推荐电商模板。Stripe结算。可定制。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurastore?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
    targetAudience: '电商兴趣、网站访客',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=neurastore',
  },
  {
    id: 'fb-zh-07',
    platform: 'facebook',
    type: 'conversion',
    headline: '比较我们的API价格',
    description: '免费计划，然后按量付费。Groq和Gemini模型。比较价格。',
    cta: '查看价格',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
    targetAudience: '注重成本的开发者',
    trackingParams: '?utm_source=facebook&utm_medium=conversion&utm_campaign=pricing',
  },
  // === 再营销 (3) ===
  {
    id: 'fb-zh-08',
    platform: 'facebook',
    type: 'retargeting',
    headline: '还在考虑AI-Empire？',
    description: '免费计划可用。无需信用卡。今天就试试我们的API和模板。',
    cta: '免费试用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
    targetAudience: '查看价格但未转化的访客',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=return',
  },
  {
    id: 'fb-zh-09',
    platform: 'facebook',
    type: 'retargeting',
    headline: 'NeuraBlog — 创建你的AI博客',
    description: 'SEO优化博客模板。支持MDX和暗色模式。生产就绪。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neurablog?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
    targetAudience: '模板页面访客',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=neurablog',
  },
  {
    id: 'fb-zh-10',
    platform: 'facebook',
    type: 'retargeting',
    headline: '准备好部署你的AI应用了吗？',
    description: '我们的模板包含认证、支付和AI集成。从坚实基础开始。',
    cta: '开始使用',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
    targetAudience: '文档页面访客、未转化',
    trackingParams: '?utm_source=facebook&utm_medium=retargeting&utm_campaign=deploy',
  },
];

export const linkedinAds: AdCopy[] = [
  // === 赞助内容 (4) ===
  {
    id: 'li-zh-01',
    platform: 'linkedin',
    type: 'sponsored',
    headline: '面向SaaS团队的AI API — Groq & Gemini',
    description: 'Groq和Gemini统一API。免费计划、Stripe集成、GDPR合规。为团队构建。',
    cta: '了解更多',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
    targetAudience: 'CTO、技术负责人、10-200人',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=teams',
  },
  {
    id: 'li-zh-02',
    platform: 'linkedin',
    type: 'sponsored',
    headline: '更快推出你的AI SaaS',
    description: 'Next.js 14模板集成认证、支付和AI。生产就绪。查看模板。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
    targetAudience: '产品经理、技术负责人',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=ship',
  },
  {
    id: 'li-zh-03',
    platform: 'linkedin',
    type: 'sponsored',
    headline: '如何为产品添加AI',
    description: '集成Groq和Gemini的分步指南。免费API计划可用。',
    cta: '阅读指南',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
    targetAudience: 'CTO、工程VP、50-500人',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=guide',
  },
  {
    id: 'li-zh-04',
    platform: 'linkedin',
    type: 'sponsored',
    headline: 'AI-Empire：用内置AI构建SaaS',
    description: 'Next.js模板 + AI API + Stripe。发布SaaS所需的一切。',
    cta: '开始使用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
    targetAudience: '创始人、CTO、技术创业公司',
    trackingParams: '?utm_source=linkedin&utm_medium=sponsored&utm_campaign=saas',
  },
  // === 消息广告 (3) ===
  {
    id: 'li-zh-05',
    platform: 'linkedin',
    type: 'message',
    headline: '免费AI API计划 — 今天试试',
    description: '通过一个API访问Groq和Gemini。免费开始。5分钟集成。包含文档和SDK。',
    cta: '免费试用',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
    targetAudience: '技术负责人、开发者、25-45岁',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=freetier',
  },
  {
    id: 'li-zh-06',
    platform: 'linkedin',
    type: 'message',
    headline: 'AI项目Next.js模板',
    description: 'NeuraStore、NeuraBlog、NeuraPortfolio — 生产就绪。包含认证、支付、AI。',
    cta: '探索模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
    targetAudience: '开发团队、创业公司',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=templates',
  },
  {
    id: 'li-zh-07',
    platform: 'linkedin',
    type: 'message',
    headline: '简化你的AI技术栈',
    description: 'Groq和Gemini的一个API。不再需要管理多个提供商密钥。免费计划可用。',
    cta: '了解更多',
    landingPage: 'https://ai-empire-steel.vercel.app/docs?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
    targetAudience: '工程经理、CTO',
    trackingParams: '?utm_source=linkedin&utm_medium=message&utm_campaign=stack',
  },
  // === 动态广告 (3) ===
  {
    id: 'li-zh-08',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'AI API — 免费开始，按增长付费',
    description: 'Groq和Gemini模型。无前期费用。查看价格。',
    cta: '查看价格',
    landingPage: 'https://ai-empire-steel.vercel.app/pricing?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
    targetAudience: '技术决策者、关注成本',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=pricing',
  },
  {
    id: 'li-zh-09',
    platform: 'linkedin',
    type: 'dynamic',
    headline: 'NeuraPortfolio — 开发者作品集模板',
    description: '简洁响应式Next.js作品集。50+组件。暗色模式。今天部署。',
    cta: '查看模板',
    landingPage: 'https://ai-empire-steel.vercel.app/templates/neuraportfolio?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
    targetAudience: '开发者、自由职业者',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=portfolio',
  },
  {
    id: 'li-zh-10',
    platform: 'linkedin',
    type: 'dynamic',
    headline: '面向欧洲的GDPR合规AI API',
    description: 'AI-Empire注重数据隐私构建。免费计划。Stripe计费。包含文档。',
    cta: '了解更多',
    landingPage: 'https://ai-empire-steel.vercel.app?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
    targetAudience: '欧洲科技公司、合规角色',
    trackingParams: '?utm_source=linkedin&utm_medium=dynamic&utm_campaign=gdpr',
  },
];
