import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-ar-01',
    title: 'AI Empire — أطلق SaaS الخاص بك في 48 ساعة',
    type: 'product-demo',
    duration: '60 ثانية',
    platform: 'يوتيوب، الموقع',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'لقطة واسعة: مطور على مكتبه، شاشة اللابتوب تظهر الطرفية',
        onScreenText: 'لا تزال تبني SaaS الخاص بك من الصفر؟',
        narration: 'بناء SaaS من الصفر يستغرق شهوراً. ماذا لو استطعت إطلاقه في 48 ساعة؟',
        transition: 'تكبير سريع على الشاشة',
      },
      {
        duration: '0:05-0:15',
        shot: 'تسجيل الشاشة: معرض قوالب AI Empire',
        onScreenText: 'AI Empire — قوالب SaaS Next.js 14',
        narration: 'تعرّف على AI Empire. قوالب Next.js 14 جاهزة للإنتاج مع APIs للذكاء الاصطناعي وفواتير Stripe والمصادقة — كلها مبنية مسبقاً.',
        transition: 'انزلاق لليسار',
      },
      {
        duration: '0:15-0:25',
        shot: 'تسجيل الشاشة: استنساخ القالب، تثبيت التبعيات',
        onScreenText: '1. استنساخ ← 2. تكوين ← 3. نشر',
        narration: 'اختر قالباً. استنسخه. أضف مفتاح Groq API الخاص بك. انشر على Vercel. تم.',
        transition: 'قص',
      },
      {
        duration: '0:25-0:35',
        shot: 'شاشة مقسومة: كود على اليسار، تطبيق محادثة AI على اليمين',
        onScreenText: 'Groq AI + Gemini API مدمجان',
        narration: 'كل قالب يشمل محادثة AI بالتدفق ونتائج منظمة وتحليل مستندات — مدعومان بـ Groq و Gemini.',
        transition: 'تصغير',
      },
      {
        duration: '0:35-0:45',
        shot: 'تسجيل الشاشة: لوحة تحكم Stripe، إعداد الاشتراكات',
        onScreenText: 'فواتير Stripe — اشتراكات، استخدام، بوابة',
        narration: 'فواتير Stripe معتمدة مسبقاً. الاشتراكات والأسعار حسب الاستخدام وبوابة العملاء — كلها متصلة.',
        transition: 'تلاشي',
      },
      {
        duration: '0:45-0:55',
        shot: 'montage سريع: 6 واجهات قوالب',
        onScreenText: '6 قوالب · 50+ مكون · جاهز للإنتاج',
        narration: 'NeuraSaaS و NeuraStore و NeuraBlog و NeuraPortfolio — اختر ما يناسب منتجك.',
        transition: 'قص إلى CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'شعار AI Empire + URL على خلفية داكنة',
        onScreenText: 'ai-empire-steel.vercel.app — تجربة مجانية',
        narration: 'ابدأ مجاناً. بدون بطاقة ائتمان. ai-empire-steel.vercel.app',
        transition: 'تلاشي للخروج',
      },
    ],
    cta: 'جرّب مجاناً على ai-empire-steel.vercel.app',
    music: 'إلكتروني حماسي، باس خفيف',
    targetAudience: 'المطورون، رواد الأعمال المستقلون، مؤسسو SaaS',
  },

  socialAd: {
    id: 'va-ar-01',
    title: 'AI Empire — توقف عن برمجة القوالب الجاهزة',
    type: 'social-ad',
    duration: '30 ثانية',
    platform: 'Instagram Reels، TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'لقطة قريبة: مطور محبط، عدة تبويبات مفتوحة',
        onScreenText: 'المصادقة... الفواتير... لوحات التحكم...',
        narration: '',
        transition: 'قص حاد',
      },
      {
        duration: '0:03-0:08',
        shot: 'تسجيل الشاشة: معرض قوالب AI Empire',
        onScreenText: 'تجاوز القوالب الجاهزة',
        narration: '',
        transition: 'سحب للأعلى',
      },
      {
        duration: '0:08-0:15',
        shot: 'تسجيل الشاشة: استنساخ، npm install، تشغيل الخادم',
        onScreenText: 'استنساخ ← تثبيت ← تشغيل',
        narration: '',
        transition: 'تكبير سريع',
      },
      {
        duration: '0:15-0:22',
        shot: 'مقسوم: كود على اليسار، واجهة جميلة مع محادثة AI على اليمين',
        onScreenText: 'AI + Stripe + Auth — مبني مسبقاً',
        narration: '',
        transition: 'انزلاق لليسار',
      },
      {
        duration: '0:22-0:27',
        shot: 'تطبيق منشور على الهاتف، يعمل بشكل مثالي',
        onScreenText: 'أطلق في 48 ساعة، وليس 48 يوماً',
        narration: '',
        transition: 'قص',
      },
      {
        duration: '0:27-0:30',
        shot: 'شعار AI Empire على خلفية متدرجة',
        onScreenText: 'تجربة مجانية · بدون بطاقة',
        narration: '',
        transition: 'تلاشي للخروج',
      },
    ],
    cta: 'رابط في البايو',
    music: 'م track ترندي سريع الإيقاع',
    targetAudience: 'المطورون 18-35 سنة، وسائل التواصل الاجتماعي',
  },

  tutorial: {
    id: 'vt-ar-01',
    title: 'إنشاء لوحة تحكم SaaS بالذكاء الاصطناعي في 10 دقائق',
    type: 'tutorial',
    duration: '2:00',
    platform: 'يوتيوب',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'المقدم أمام الكاميرا، لوحة تحكم AI Empire مرئية في الخلفية',
        onScreenText: 'لوحة تحكم SaaS بالـ AI — 10 دقائق',
        narration: 'في هذا الفيديو، سأريك كيفية إنشاء لوحة تحكم SaaS كاملة بالذكاء الاصطناعي باستخدام قوالب AI Empire. يلا نبدأ.',
        transition: 'قص إلى الشاشة',
      },
      {
        duration: '0:15-0:40',
        shot: 'تسجيل الشاشة: GitHub، استنساخ مستودع NeuraDashboard',
        onScreenText: 'الخطوة 1: استنساخ القالب',
        narration: 'أولاً، اذهب إلى GitHub الخاص بنا واستنسخ قالب NeuraDashboard. شغّل npm install للحصول على جميع التبعيات. القالب يستخدم Next.js 14 و TypeScript و Tailwind.',
        transition: 'قص',
      },
      {
        duration: '0:40-1:10',
        shot: 'تسجيل الشاشة: إعداد .env.local، مفاتيح API، قاعدة البيانات',
        onScreenText: 'الخطوة 2: تكوين البيئة',
        narration: 'أضف متغيرات البيئة. مفتاح Groq API يذهب هنا — احصل عليه مجاناً من console.groq.com. قم بتكوين رابط قاعدة البيانات مع Prisma. اربط Stripe للفواتير. يستغرق حوالي 3 دقائق.',
        transition: 'قص',
      },
      {
        duration: '1:10-1:40',
        shot: 'تسجيل الشاشة: تشغيل خادم التطوير، تصفح لوحة التحكم',
        onScreenText: 'الخطوة 3: التخصيص والبناء',
        narration: 'شغّل npm run dev وستحصل على لوحة تحكم كاملة مع رسوم بيانية مباشرة وإدارة المستخدمين وتحليلات AI. خصص الألوان وأضف علامتك التجارية. الكود نظيف وموثق جيداً.',
        transition: 'قص',
      },
      {
        duration: '1:40-1:55',
        shot: 'تسجيل الشاشة: نشر Vercel، التطبيق يعمل على الهاتف',
        onScreenText: 'الخطوة 4: النشر في الإنتاج',
        narration: 'عندما تكون جاهزاً، ادفع إلى GitHub وانشر على Vercel. نقرة واحدة. لوحة تحكم SaaS بالـ AI جاهزة. فواتير Stripe والمصادقة وAPIs الذكاء الاصطناعي — كلها تعمل.',
        transition: 'قص إلى المقدم',
      },
      {
        duration: '1:55-2:00',
        shot: 'المقدم أمام الكاميرا، يبتسم',
        onScreenText: 'ai-empire-steel.vercel.app — تجربة مجانية',
        narration: 'هذا كل شيء. الروابط في الوصف. جرّب مجاناً — بدون بطاقة ائتمان.',
        transition: 'تلاشي للخروج',
      },
    ],
    cta: 'الروابط في الوصف — جرّب مجاناً',
    music: 'Lo-fi هادئ، في الخلفية',
    targetAudience: 'المطورون يتعلمون تطوير SaaS',
  },

  founderStory: {
    id: 'vf-ar-01',
    title: 'لماذا بنيت AI Empire — قصة Build-in-Public',
    type: 'founder-story',
    duration: '5:00',
    platform: 'يوتيوب، LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'المؤسس على مكتبه، أجواء غير رسمية، قهوة في يده',
        onScreenText: 'بناء AI Empire — الأسبوع 1',
        narration: 'قبل ستة أشهر كنت أقضي وقتاً أطول في إعداد Webhooks Stripe وتدفقات المصادقة מאשר في بناء منتجي الحقيقي. كان لدي فكرة لأداة ذكاء اصطناعي لكنني كنت عالقاً في جحيم القوالب الجاهزة. قررت وقتها أن أبني ما كنت أتمنى أن يكون موجوداً.',
        transition: 'قص',
      },
      {
        duration: '0:20-0:50',
        shot: 'مونتاج: برمجة متأخرة، أكواب قهوة، شاشات طرفية',
        onScreenText: 'المشكلة: 80% قوالب جاهزة، 20% منتج',
        narration: 'كل مشروع SaaS يبدأ بنفس الطريقة. إعداد المصادقة. ربط Stripe. بناء لوحة تحكم. إضافة API ذكاء اصطناعي. تكوين قاعدة البيانات. عندما تبدأ ببناء ميزتك الأساسية، تكون قد أضعت 3 أسابيع وطاقة كبيرة.',
        transition: 'تلاشي متقاطع',
      },
      {
        duration: '0:50-1:30',
        shot: 'تسجيل الشاشة: إنشاء قالب NeuraSaaS الأول',
        onScreenText: 'الأسبوع 2: القالب الأول — NeuraSaaS',
        narration: 'هكذا بدأت ببناء القوالب. ليست قوالباً جاهزة، بل نقاط انطلاق جاهزة للإنتاج. NeuraSaaS كان الأول. Next.js 14 و Tailwind و Prisma و Stripe و Groq AI — كلها مترابطة. استخدمته لبناء SaaS الخاص بي في عطلة نهاية أسبوع.',
        transition: 'قص',
      },
      {
        duration: '1:30-2:10',
        shot: 'تسجيل الشاشة: معرض القوالب يتوسع',
        onScreenText: 'الأسبوع 4: 6 قوالب جاهزة',
        narration: 'بحلول الأسبوع الرابع كان لدي 6 قوالب. NeuraSaaS للSaaS العام. NeuraStore للتجارة الإلكترونية. NeuraBlog للمحتوى. NeuraPortfolio لعرض العمل. كل واحد يتبع نفس الأنماط: TypeScript نظيف ومعالجة أخطاء وربط Stripe وAPIs ذكاء اصطناعي.',
        transition: 'قص',
      },
      {
        duration: '2:10-2:50',
        shot: 'تسجيل الشاشة: اختبارات Groq AI، استدلال سريع',
        onScreenText: 'طبقة AI: Groq + Gemini',
        narration: 'تكامل AI هو الفخر الأكبر. Groq يوفر استدلالاً بـ 500 رمز في الثانية — سريع بما يكفي للمحادثة المباشرة. Gemini يتعامل مع التحليل المركّب. كلاهما متاح عبر API موحدة.',
        transition: 'قص',
      },
      {
        duration: '2:50-3:30',
        shot: 'المؤسس أمام الكاميرا، شغوف',
        onScreenText: 'يوم الإطلاق: 500 تسجيل',
        narration: 'أطلقت AI Empire يوم الاثنين. نشرت على Twitter و LinkedIn و Reddit. بحلول الجمعة كان لدي 500 تسجيل وأول عملاء مدفوعين. الطبقة المجانية كانت الطُّعم — 100 رصيد API، بدون بطاقة.',
        transition: 'تلاشي متقاطع',
      },
      {
        duration: '3:30-4:10',
        shot: 'مونتاج: شهادات المستخدمين، لقطات شاشة، مدفوعات Stripe',
        onScreenText: 'الشهر 3: €3,000 MRR',
        narration: 'بعد ثلاثة أشهر وصلت إلى €3,000 MRR. ليس مالاً يغير الحياة، لكنه كافٍ لإثبات المفهوم. الملاحظات كانت لا تصدق. المطورون يوفرون أسابيع من الإعداد.',
        transition: 'قص',
      },
      {
        duration: '4:10-4:40',
        shot: 'تسجيل الشاشة: خارطة الطريق، الميزات القادمة',
        onScreenText: 'ما ينتظرنا: AI Empire v2.0',
        narration: 'ها ما يأتي. المزيد من القوالب. منشئ تدفقات AI بالسحب والإفلات. توثيق أفضل. وسوق مجتمعي حيث يمكن للمطورين مشاركة وبيع قوالبهم الخاصة.',
        transition: 'قص',
      },
      {
        duration: '4:40-5:00',
        shot: 'المؤسس أمام الكاميرا، ابتسامة صادقة',
        onScreenText: 'ai-empire-steel.vercel.app — تجربة مجانية',
        narration: 'إذا كنت تبني SaaS ومليت من القوالب الجاهزة، جرّب AI Empire. طبقة مجانية، بدون بطاقة ائتمان، الروابط في الوصف. شكراً للمشاهدة. نراك في المرة القادمة.',
        transition: 'تلاشي إلى الشعار',
      },
    ],
    cta: 'جرّب مجاناً — رابط في الوصف',
    music: 'ambiante ملهم، يتصاعد تدريجياً',
    targetAudience: 'المطورون، المؤسسون، مجتمع Build-in-Public',
  },
}
