import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-de-01',
    title: 'AI Empire — Starten Sie Ihr SaaS in 48 Stunden',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Website',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Weitwinkel: Entwickler am Schreibtisch, Laptop-Bildschirm zeigt Terminal',
        onScreenText: 'Bauen Sie Ihr SaaS noch von Grund auf?',
        narration: 'Ein SaaS von Grund auf zu bauen dauert Monate. Was wenn Sie es in 48 Stunden starten könnten?',
        transition: 'Schneller Zoom auf den Bildschirm',
      },
      {
        duration: '0:05-0:15',
        shot: 'Bildschirmaufnahme: AI Empire Template-Galerie',
        onScreenText: 'AI Empire — Next.js 14 SaaS Templates',
        narration: 'Entdecken Sie AI Empire. Produktionsfertige Next.js 14 Templates mit KI-APIs, Stripe-Abrechnung und Authentifizierung — alles vorgebaut.',
        transition: 'Gleiten links',
      },
      {
        duration: '0:15-0:25',
        shot: 'Bildschirmaufnahme: Template klonen, Abhängigkeiten installieren',
        onScreenText: '1. Klonen → 2. Konfigurieren → 3. Bereitstellen',
        narration: 'Wählen Sie ein Template. Klonen Sie es. Fügen Sie Ihren Groq-API-Schlüssel hinzu. Deployen Sie auf Vercel. Fertig.',
        transition: 'Schnitt',
      },
      {
        duration: '0:25-0:35',
        shot: 'Geteilte Ansicht: Code links, KI-App rechts mit Chat',
        onScreenText: 'Groq AI + Gemini API integriert',
        narration: 'Jedes Template enthält Streaming-KI-Chat, strukturierte Completion und Dokumentenanalyse — angetrieben von Groq und Gemini.',
        transition: 'Zoom-out',
      },
      {
        duration: '0:35-0:45',
        shot: 'Bildschirmaufnahme: Stripe-Dashboard, Abonnements-Setup',
        onScreenText: 'Stripe-Abrechnung — Abonnements, Nutzung, Portal',
        narration: 'Die Stripe-Abrechnung ist vorkonfiguriert. Abonnements, nutzungsbasierte Preise, Kundenportal — alles verbunden.',
        transition: 'Überblendung',
      },
      {
        duration: '0:45-0:55',
        shot: 'Schneller Montage: 6 Template-Oberflächen',
        onScreenText: '6 Templates · 50+ Komponenten · Produktionsfertig',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — wählen Sie das passende für Ihr Produkt.',
        transition: 'Schnitt zu CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'AI Empire Logo + URL auf dunklem Hintergrund',
        onScreenText: 'ai-empire-steel.vercel.app — Kostenloser Zugang',
        narration: 'Starten Sie kostenlos. Keine Kreditkarte erforderlich. ai-empire-steel.vercel.app',
        transition: 'Ausblenden',
      },
    ],
    cta: 'Kostenlos testen auf ai-empire-steel.vercel.app',
    music: 'Upbeat Elektronik, subtiler Bass',
    targetAudience: 'Entwickler, Indie-Hacker, SaaS-Gründer',
  },

  socialAd: {
    id: 'va-de-01',
    title: 'AI Empire — Hören Sie auf, Boilerplate zu programmieren',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'Nahaufnahme: frustrierter Entwickler, mehrere Tabs geöffnet',
        onScreenText: 'Auth... Abrechnung... Dashboards...',
        narration: '',
        transition: 'Harter Schnitt',
      },
      {
        duration: '0:03-0:08',
        shot: 'Bildschirmaufnahme: AI Empire Template-Galerie',
        onScreenText: 'Überspringen Sie das Boilerplate',
        narration: '',
        transition: 'Swipe nach oben',
      },
      {
        duration: '0:08-0:15',
        shot: 'Bildschirmaufnahme: klonen, npm install, Server startet',
        onScreenText: 'Klonen → Installieren → Ausführen',
        narration: '',
        transition: 'Schneller Zoom',
      },
      {
        duration: '0:15-0:22',
        shot: 'Geteilt: Code links, schöne UI rechts mit KI-Chat',
        onScreenText: 'KI + Stripe + Auth — Vorgebaut',
        narration: '',
        transition: 'Gleiten links',
      },
      {
        duration: '0:22-0:27',
        shot: 'App auf Telefon bereitgestellt, funktioniert perfekt',
        onScreenText: 'In 48h starten, nicht in 48 Tagen',
        narration: '',
        transition: 'Schnitt',
      },
      {
        duration: '0:27-0:30',
        shot: 'AI Empire Logo auf Gradient-Hintergrund',
        onScreenText: 'Kostenloser Zugang · Keine Kreditkarte',
        narration: '',
        transition: 'Ausblenden',
      },
    ],
    cta: 'Link in Bio',
    music: 'Trending Upbeat-Track, schnelles Tempo',
    targetAudience: 'Entwickler 18-35 Jahre, soziale Medien',
  },

  tutorial: {
    id: 'vt-de-01',
    title: 'Erstellen Sie ein KI-SaaS-Dashboard in 10 Minuten',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Moderator zur Kamera, AI Empire Dashboard im Hintergrund',
        onScreenText: 'KI-SaaS-Dashboard — 10 Min',
        narration: 'In diesem Video zeige ich Ihnen, wie Sie ein vollständiges KI-gesteuertes SaaS-Dashboard mit AI Empire Templates erstellen. Los geht\'s.',
        transition: 'Schnitt zur Ansicht',
      },
      {
        duration: '0:15-0:40',
        shot: 'Bildschirmaufnahme: GitHub, NeuraDashboard Repo klonen',
        onScreenText: 'Schritt 1: Template klonen',
        narration: 'Gehen Sie zuerst zu unserem GitHub und klonen Sie das NeuraDashboard Template. Führen Sie npm install aus, um alle Abhängigkeiten zu erhalten. Das Template verwendet Next.js 14, TypeScript und Tailwind.',
        transition: 'Schnitt',
      },
      {
        duration: '0:40-1:10',
        shot: 'Bildschirmaufnahme: .env.local Setup, API-Schlüssel, Datenbank',
        onScreenText: 'Schritt 2: Umgebung konfigurieren',
        narration: 'Fügen Sie Ihre Umgebungsvariablen hinzu. Ihr Groq-API-Schlüssel kommt hier hin — erhalten Sie einen kostenlos bei console.groq.com. Richten Sie Ihre Datenbank-URL mit Prisma ein. Verbinden Sie Stripe für die Abrechnung. Dauert etwa 3 Minuten.',
        transition: 'Schnitt',
      },
      {
        duration: '1:10-1:40',
        shot: 'Bildschirmaufnahme: Dev-Server, Dashboard durchsuchen',
        onScreenText: 'Schritt 3: Anpassen und Bauen',
        narration: 'Führen Sie npm run dev aus und Sie haben ein vollständiges Dashboard mit Echtzeit-Diagrammen, Benutzerverwaltung und KI-Analysen. Passen Sie die Farben an, fügen Sie Ihr Branding hinzu, modifizieren Sie die API-Routen.',
        transition: 'Schnitt',
      },
      {
        duration: '1:40-1:55',
        shot: 'Bildschirmaufnahme: Vercel-Deployment, App live auf Telefon',
        onScreenText: 'Schritt 4: In Produktion bereitstellen',
        narration: 'Wenn Sie bereit sind, pushen Sie zu GitHub und deployen Sie auf Vercel. Ein Klick. Ihr KI-SaaS-Dashboard ist live. Stripe-Abrechnung, Authentifizierung und KI-APIs — alles funktioniert.',
        transition: 'Schnitt zum Moderator',
      },
      {
        duration: '1:55-2:00',
        shot: 'Moderator zur Kamera, lächelnd',
        onScreenText: 'ai-empire-steel.vercel.app — Kostenloser Zugang',
        narration: 'Das war\'s. Links in der Beschreibung. Kostenlos testen — keine Kreditkarte erforderlich.',
        transition: 'Ausblenden',
      },
    ],
    cta: 'Links in der Beschreibung — Kostenlos testen',
    music: 'Chill Lo-Fi, im Hintergrund',
    targetAudience: 'Entwickler, die SaaS-Entwicklung lernen',
  },

  founderStory: {
    id: 'vf-de-01',
    title: 'Warum ich AI Empire gebaut habe — Build-in-Public Geschichte',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Gründer am Schreibtisch, lockerer Rahmen, Kaffee in der Hand',
        onScreenText: 'AI Empire bauen — Woche 1',
        narration: 'Vor sechs Monaten verbrachte ich mehr Zeit damit, Stripe Webhooks und Authentifizierungsabläufe einzurichten, als mein eigentliches Produkt zu bauen. Ich hatte diese KI-Idee, aber ich steckte in der Boilerplate-Hölle fest. Da entschied ich mich, das zu bauen, was ich mir gewünscht hätte.',
        transition: 'Schnitt',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montage: Nachts programmieren, Kaffeebecher, Terminal-Bildschirme',
        onScreenText: 'Das Problem: 80% Boilerplate, 20% Produkt',
        narration: 'Jedes SaaS-Projekt beginnt gleich. Auth einrichten. Stripe verbinden. Dashboard bauen. KI-API hinzufügen. Datenbank konfigurieren. Wenn Sie mit Ihrer eigentlichen Funktion anfangen, haben Sie 3 Wochen und viel Energie verbrannt.',
        transition: 'Überblendung',
      },
      {
        duration: '0:50-1:30',
        shot: 'Bildschirmaufnahme: Erstellung des ersten NeuraSaaS Templates',
        onScreenText: 'Woche 2: Erstes Template — NeuraSaaS',
        narration: 'Also fing ich an, Templates zu bauen. Nicht Boilerplate, sondern produktionsfertige Ausgangspunkte. NeuraSaaS war das erste. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — alles verbunden. Ich benutzte es, um mein eigenes SaaS an einem Wochenende zu bauen.',
        transition: 'Schnitt',
      },
      {
        duration: '1:30-2:10',
        shot: 'Bildschirmaufnahme: Template-Galerie wächst',
        onScreenText: 'Woche 4: 6 Templates fertig',
        narration: 'Bis Woche vier hatte ich 6 Templates. NeuraSaaS für allgemeines SaaS. NeuraStore für E-Commerce. NeuraBlog für Inhalte. NeuraPortfolio zur Arbeitspräsentation. Jedes folgt denselben Mustern: sauberer TypeScript, Fehlerbehandlung, Stripe-Integration und KI-APIs.',
        transition: 'Schnitt',
      },
      {
        duration: '2:10-2:50',
        shot: 'Bildschirmaufnahme: Groq AI Benchmarks, schnelle Inferenz',
        onScreenText: 'Die KI-Schicht: Groq + Gemini',
        narration: 'Die KI-Integration ist der Teil, auf den ich am meisten stolz bin. Groq bietet Inferenz mit 500 Tokens pro Sekunde — schnell genug für Echtzeit-Chat. Gemini behandelt komplexe Analyse. Beide über eine einheitliche API verfügbar.',
        transition: 'Schnitt',
      },
      {
        duration: '2:50-3:30',
        shot: 'Gründer zur Kamera, leidenschaftlich',
        onScreenText: 'Launch-Tag: 500 Anmeldungen',
        narration: 'Ich startete AI Empire an einem Montag. Posted auf Twitter, LinkedIn und Reddit. Bis Freitag hatte ich 500 Anmeldungen und meine ersten zahlenden Kunden. Das kostenlose Tier war der Köder — 100 API-Guthaben, keine Kreditkarte.',
        transition: 'Überblendung',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montage: Kunden-Testimonials, Dashboard-Screenshots, Stripe-Zahlungen',
        onScreenText: 'Monat 3: €3.000 MRR',
        narration: 'Drei Monate später erreichte ich €3.000 MRR. Kein lebensveränderndes Geld, aber genug, um das Konzept zu beweisen. Das Feedback war unglaublich. Entwickler sparen Wochen beim Setup.',
        transition: 'Schnitt',
      },
      {
        duration: '4:10-4:40',
        shot: 'Bildschirmaufnahme: Roadmap, kommende Funktionen',
        onScreenText: 'Was kommt: AI Empire v2.0',
        narration: 'Hier ist was kommt. Mehr Templates. Ein Drag-and-Drop KI-Workflow-Builder. Bessere Dokumentation. Und ein Community-Marketplace, wo Entwickler ihre eigenen Templates teilen und verkaufen können.',
        transition: 'Schnitt',
      },
      {
        duration: '4:40-5:00',
        shot: 'Gründer zur Kamera, ehrliches Lächeln',
        onScreenText: 'ai-empire-steel.vercel.app — Kostenloser Zugang',
        narration: 'Wenn Sie ein SaaS bauen und das Boilerplate satt haben, probieren Sie AI Empire. Kostenloser Zugang, keine Kreditkarte, Links in der Beschreibung. Danke fürs Zuschauen. Bis zum nächsten Mal.',
        transition: 'Überblenden zum Logo',
      },
    ],
    cta: 'Kostenlos testen — Link in der Beschreibung',
    music: 'Inspirierender Ambient, baut sich langsam auf',
    targetAudience: 'Entwickler, Gründer, Build-in-Public-Community',
  },
}
