import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-en-01',
    title: 'AI Empire — Launch Your SaaS in 48 Hours',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Website',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Wide shot: Developer at desk, laptop screen shows terminal',
        onScreenText: 'Still building your SaaS from scratch?',
        narration: 'Building a SaaS from scratch takes months. What if you could launch in 48 hours?',
        transition: 'Fast zoom into screen',
      },
      {
        duration: '0:05-0:15',
        shot: 'Screen recording: Browsing AI Empire templates gallery',
        onScreenText: 'AI Empire — Next.js 14 SaaS Templates',
        narration: 'Meet AI Empire. Production-ready Next.js 14 templates with AI APIs, Stripe billing, and authentication — all pre-built.',
        transition: 'Slide left',
      },
      {
        duration: '0:15-0:25',
        shot: 'Screen recording: Clone template, install dependencies',
        onScreenText: '1. Clone → 2. Configure → 3. Deploy',
        narration: 'Pick a template. Clone it. Add your Groq API key. Deploy to Vercel. Done.',
        transition: 'Cut',
      },
      {
        duration: '0:25-0:35',
        shot: 'Split screen: Left shows code, right shows live app with AI chat',
        onScreenText: 'Built-in Groq AI + Gemini API',
        narration: 'Every template includes streaming AI chat, structured completions, and document analysis — powered by Groq and Gemini.',
        transition: 'Zoom out',
      },
      {
        duration: '0:35-0:45',
        shot: 'Screen recording: Stripe dashboard, subscription setup',
        onScreenText: 'Stripe Billing — Subscriptions, Usage, Portal',
        narration: 'Stripe billing is pre-configured. Subscriptions, usage-based pricing, customer portal — all wired up.',
        transition: 'Fade',
      },
      {
        duration: '0:45-0:55',
        shot: 'Montage: 6 different template UIs flashing',
        onScreenText: '6 Templates · 50+ Components · Production Ready',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — pick the one that fits your product.',
        transition: 'Cut to CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'AI Empire logo + URL on dark background',
        onScreenText: 'ai-empire-steel.vercel.app — Free Tier Available',
        narration: 'Start free. No credit card required. ai-empire-steel.vercel.app',
        transition: 'Fade out',
      },
    ],
    cta: 'Try free at ai-empire-steel.vercel.app',
    music: 'Upbeat electronic, subtle bass',
    targetAudience: 'Developers, indie hackers, SaaS founders',
  },

  socialAd: {
    id: 'va-en-01',
    title: 'AI Empire — Stop Building Boilerplate',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'Close-up: Frustrated developer rubbing eyes, multiple tabs open',
        onScreenText: 'Auth... billing... dashboards...',
        narration: '',
        transition: 'Hard cut',
      },
      {
        duration: '0:03-0:08',
        shot: 'Screen recording: AI Empire template gallery, fast scroll',
        onScreenText: 'Skip the boilerplate',
        narration: '',
        transition: 'Swipe up',
      },
      {
        duration: '0:08-0:15',
        shot: 'Screen recording: Clone, npm install, dev server starts',
        onScreenText: 'Clone → Install → Run',
        narration: '',
        transition: 'Fast zoom',
      },
      {
        duration: '0:15-0:22',
        shot: 'Split: Code on left, beautiful UI on right with AI chat working',
        onScreenText: 'AI + Stripe + Auth — Pre-built',
        narration: '',
        transition: 'Slide left',
      },
      {
        duration: '0:22-0:27',
        shot: 'App deployed on phone, working perfectly',
        onScreenText: 'Launch in 48h, not 48 days',
        narration: '',
        transition: 'Cut',
      },
      {
        duration: '0:27-0:30',
        shot: 'AI Empire logo on gradient background',
        onScreenText: 'Free Tier · No Credit Card',
        narration: '',
        transition: 'Fade out',
      },
    ],
    cta: 'Link in bio',
    music: 'Trending upbeat track, fast-paced',
    targetAudience: 'Developers 18-35, social media',
  },

  tutorial: {
    id: 'vt-en-01',
    title: 'Build an AI SaaS Dashboard in 10 Minutes',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Presenter face-to-camera, AI Empire dashboard visible behind',
        onScreenText: 'Build an AI SaaS Dashboard — 10 Min',
        narration: 'In this video, I\'ll show you how to build a complete AI-powered SaaS dashboard using AI Empire templates. Let\'s go.',
        transition: 'Cut to screen',
      },
      {
        duration: '0:15-0:40',
        shot: 'Screen recording: GitHub, clone NeuraDashboard repo',
        onScreenText: 'Step 1: Clone the Template',
        narration: 'First, head to our GitHub and clone the NeuraDashboard template. Run npm install to get all dependencies. The template uses Next.js 14, TypeScript, and Tailwind — everything you need.',
        transition: 'Cut',
      },
      {
        duration: '0:40-1:10',
        shot: 'Screen recording: .env.local setup, API keys, database connection',
        onScreenText: 'Step 2: Configure Environment',
        narration: 'Add your environment variables. Your Groq API key goes here — get one free at console.groq.com. Set up your database URL with Prisma. Connect Stripe for billing. Takes about 3 minutes.',
        transition: 'Cut',
      },
      {
        duration: '1:10-1:40',
        shot: 'Screen recording: Running dev server, browsing dashboard UI',
        onScreenText: 'Step 3: Customize & Build',
        narration: 'Run npm run dev and you\'ve got a full dashboard with real-time charts, user management, and AI-powered analytics. Customize the colors, add your branding, modify the API routes — the code is clean and well-documented.',
        transition: 'Cut',
      },
      {
        duration: '1:40-1:55',
        shot: 'Screen recording: Vercel deployment, app live on phone',
        onScreenText: 'Step 4: Deploy to Production',
        narration: 'When you\'re ready, push to GitHub and deploy to Vercel. One click. Your AI SaaS dashboard is live. Stripe billing, authentication, and AI APIs — all working out of the box.',
        transition: 'Cut to presenter',
      },
      {
        duration: '1:55-2:00',
        shot: 'Presenter face-to-camera, smiling',
        onScreenText: 'ai-empire-steel.vercel.app — Start Free',
        narration: 'That\'s it. Links in the description. Try it free — no credit card required.',
        transition: 'Fade out',
      },
    ],
    cta: 'Links in description — Start free',
    music: 'Chill lo-fi beats, background',
    targetAudience: 'Developers learning SaaS development',
  },

  founderStory: {
    id: 'vf-en-01',
    title: 'Why I Built AI Empire — A Build-in-Public Story',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Founder at desk, casual setting, coffee in hand',
        onScreenText: 'Building AI Empire — Week 1',
        narration: 'Six months ago, I was spending more time setting up Stripe webhooks and authentication flows than building my actual product. I had this idea for an AI tool, but I was stuck in boilerplate hell. That\'s when I decided to build what I wished existed.',
        transition: 'Cut',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montage: Late night coding, coffee cups, terminal screens',
        onScreenText: 'The Problem: 80% Boilerplate, 20% Product',
        narration: 'Every SaaS project starts the same way. Set up auth. Wire up Stripe. Build a dashboard. Add an AI API. Configure the database. By the time you start building your actual feature, you\'ve burned 3 weeks and a lot of energy. I talked to dozens of developers. They all said the same thing: the tech stack is the easy part — it\'s the integration that kills you.',
        transition: 'Cross-dissolve',
      },
      {
        duration: '0:50-1:30',
        shot: 'Screen recording: Building the first NeuraSaaS template',
        onScreenText: 'Week 2: First Template — NeuraSaaS',
        narration: 'So I started building templates. Not boilerplate, but production-ready starting points. NeuraSaaS was the first one. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — all wired together. I used it to build my own SaaS in a weekend. That\'s when I knew this could help others too.',
        transition: 'Cut',
      },
      {
        duration: '1:30-2:10',
        shot: 'Screen recording: Templates gallery expanding, 6 templates visible',
        onScreenText: 'Week 4: 6 Templates Ready',
        narration: 'By week four, I had 6 templates. NeuraSaaS for general SaaS. NeuraStore for e-commerce. NeuraBlog for content. NeuraPortfolio for showcasing work. Each one follows the same patterns: clean TypeScript, proper error handling, Stripe integration, and AI APIs ready to go.',
        transition: 'Cut',
      },
      {
        duration: '2:10-2:50',
        shot: 'Screen recording: Groq AI API benchmarks, fast inference',
        onScreenText: 'The AI Layer: Groq + Gemini',
        narration: 'The AI integration was the part I\'m most proud of. Groq gives you inference at 500 tokens per second — that\'s fast enough for real-time chat. Gemini handles complex analysis. Both are available through one unified API. No managing multiple provider keys. It just works.',
        transition: 'Cut',
      },
      {
        duration: '2:50-3:30',
        shot: 'Founder talking to camera, passionate',
        onScreenText: 'Launch Day: 500 Sign-ups',
        narration: 'I launched AI Empire on a Monday. Posted on Twitter, LinkedIn, and Reddit. By Friday, I had 500 sign-ups and my first paying customers. The free tier was the hook — 100 API credits, no credit card. Developers love trying before they buy.',
        transition: 'Cross-dissolve',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montage: User testimonials, dashboard screenshots, Stripe payments',
        onScreenText: 'Month 3: €3,000 MRR',
        narration: 'Three months in, I hit €3,000 MRR. Not life-changing money, but enough to prove the concept. The feedback has been incredible. Developers are saving weeks of setup time. One customer launched their SaaS in 2 days using NeuraSaaS. That\'s exactly what I built this for.',
        transition: 'Cut',
      },
      {
        duration: '4:10-4:40',
        shot: 'Screen recording: Roadmap, upcoming features',
        onScreenText: 'What\'s Next: AI Empire v2.0',
        narration: 'Here\'s what\'s coming. More templates. A drag-and-drop AI workflow builder. Better documentation. And a community marketplace where developers can share and sell their own templates. AI Empire isn\'t just templates — it\'s a platform for building AI-powered SaaS products.',
        transition: 'Cut',
      },
      {
        duration: '4:40-5:00',
        shot: 'Founder face-to-camera, genuine smile',
        onScreenText: 'ai-empire-steel.vercel.app — Free Tier Available',
        narration: 'If you\'re building a SaaS and tired of boilerplate, try AI Empire. Free tier, no credit card, links in the description. Thanks for watching. I\'ll see you in the next one.',
        transition: 'Fade to logo',
      },
    ],
    cta: 'Try free — link in description',
    music: 'Inspiring ambient, builds gradually',
    targetAudience: 'Developers, founders, build-in-public community',
  },
}
