import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-es-01',
    title: 'AI Empire — Lanza tu SaaS en 48 horas',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Sitio web',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Plano general: desarrollador en su escritorio, pantalla con terminal',
        onScreenText: '¿Aún construyendo tu SaaS desde cero?',
        narration: 'Construir un SaaS desde cero toma meses. ¿Y si pudieras lanzarlo en 48 horas?',
        transition: 'Zoom rápido a la pantalla',
      },
      {
        duration: '0:05-0:15',
        shot: 'Grabación de pantalla: galería de plantillas AI Empire',
        onScreenText: 'AI Empire — Plantillas SaaS Next.js 14',
        narration: 'Conoce AI Empire. Plantillas Next.js 14 listas para producción con APIs de IA, facturación Stripe y autenticación — todo pre-construido.',
        transition: 'Deslizamiento izquierda',
      },
      {
        duration: '0:15-0:25',
        shot: 'Grabación de pantalla: clonar plantilla, instalar dependencias',
        onScreenText: '1. Clonar → 2. Configurar → 3. Desplegar',
        narration: 'Elige una plantilla. Clónala. Agrega tu clave API de Groq. Despliega en Vercel. Listo.',
        transition: 'Corte',
      },
      {
        duration: '0:25-0:35',
        shot: 'Pantalla dividida: código a la izquierda, app con chat IA a la derecha',
        onScreenText: 'Groq AI + Gemini API integrados',
        narration: 'Cada plantilla incluye chat IA en streaming, completions estructuradas y análisis de documentos — potenciados por Groq y Gemini.',
        transition: 'Zoom-out',
      },
      {
        duration: '0:35-0:45',
        shot: 'Grabación de pantalla: dashboard de Stripe, configuración de suscripciones',
        onScreenText: 'Facturación Stripe — Suscripciones, Uso, Portal',
        narration: 'La facturación Stripe está pre-configurada. Suscripciones, precios por uso, portal de clientes — todo conectado.',
        transition: 'Fundido',
      },
      {
        duration: '0:45-0:55',
        shot: 'Montaje rápido: 6 interfaces de plantillas',
        onScreenText: '6 Plantillas · 50+ Componentes · Listo para producción',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — elige la que se adapte a tu producto.',
        transition: 'Corte a CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'Logo AI Empire + URL en fondo oscuro',
        onScreenText: 'ai-empire-steel.vercel.app — Prueba gratuita',
        narration: 'Empieza gratis. Sin tarjeta de crédito. ai-empire-steel.vercel.app',
        transition: 'Fundido de salida',
      },
    ],
    cta: 'Prueba gratis en ai-empire-steel.vercel.app',
    music: 'Electrónica animada, bajo sutil',
    targetAudience: 'Desarrolladores, hackers independientes, fundadores de SaaS',
  },

  socialAd: {
    id: 'va-es-01',
    title: 'AI Empire — Deja de programar boilerplate',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'Primer plano: desarrollador frustrado, múltiples pestañas abiertas',
        onScreenText: 'Auth... facturación... dashboards...',
        narration: '',
        transition: 'Corte duro',
      },
      {
        duration: '0:03-0:08',
        shot: 'Grabación de pantalla: galería de plantillas AI Empire',
        onScreenText: 'Salta el boilerplate',
        narration: '',
        transition: 'Swipe hacia arriba',
      },
      {
        duration: '0:08-0:15',
        shot: 'Grabación de pantalla: clonar, npm install, servidor iniciado',
        onScreenText: 'Clonar → Instalar → Ejecutar',
        narration: '',
        transition: 'Zoom rápido',
      },
      {
        duration: '0:15-0:22',
        shot: 'Dividido: código a la izquierda, bonita UI a la derecha con chat IA',
        onScreenText: 'IA + Stripe + Auth — Pre-construidos',
        narration: '',
        transition: 'Deslizamiento izquierda',
      },
      {
        duration: '0:22-0:27',
        shot: 'App desplegada en teléfono, funcionando perfectamente',
        onScreenText: 'Lanza en 48h, no en 48 días',
        narration: '',
        transition: 'Corte',
      },
      {
        duration: '0:27-0:30',
        shot: 'Logo AI Empire en fondo degradado',
        onScreenText: 'Prueba gratuita · Sin tarjeta',
        narration: '',
        transition: 'Fundido de salida',
      },
    ],
    cta: 'Enlace en bio',
    music: 'Track tendencia animado, ritmo rápido',
    targetAudience: 'Desarrolladores 18-35 años, redes sociales',
  },

  tutorial: {
    id: 'vt-es-01',
    title: 'Crea un Dashboard SaaS con IA en 10 minutos',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Presentador cara a cámara, dashboard AI Empire visible detrás',
        onScreenText: 'Dashboard SaaS con IA — 10 Min',
        narration: 'En este video, te mostraré cómo crear un dashboard SaaS completo con IA usando las plantillas de AI Empire. ¡Vamos!',
        transition: 'Corte a pantalla',
      },
      {
        duration: '0:15-0:40',
        shot: 'Grabación de pantalla: GitHub, clonar repo NeuraDashboard',
        onScreenText: 'Paso 1: Clonar la Plantilla',
        narration: 'Primero, ve a nuestro GitHub y clona la plantilla NeuraDashboard. Ejecuta npm install para obtener todas las dependencias. La plantilla usa Next.js 14, TypeScript y Tailwind — todo lo que necesitas.',
        transition: 'Corte',
      },
      {
        duration: '0:40-1:10',
        shot: 'Grabación de pantalla: configuración .env.local, claves API, base de datos',
        onScreenText: 'Paso 2: Configurar Entorno',
        narration: 'Agrega tus variables de entorno. Tu clave API de Groq va aquí — obtén una gratis en console.groq.com. Configura tu URL de base de datos con Prisma. Conecta Stripe para facturación. Toma unos 3 minutos.',
        transition: 'Corte',
      },
      {
        duration: '1:10-1:40',
        shot: 'Grabación de pantalla: ejecutando dev server, navegando dashboard',
        onScreenText: 'Paso 3: Personalizar y Construir',
        narration: 'Ejecuta npm run dev y tienes un dashboard completo con gráficos en tiempo real, gestión de usuarios y análisis con IA. Personaliza los colores, agrega tu marca, modifica las rutas API — el código es limpio y está bien documentado.',
        transition: 'Corte',
      },
      {
        duration: '1:40-1:55',
        shot: 'Grabación de pantalla: despliegue Vercel, app live en teléfono',
        onScreenText: 'Paso 4: Desplegar en Producción',
        narration: 'Cuando estés listo, haz push a GitHub y despliega en Vercel. Un clic. Tu dashboard SaaS con IA está en línea. Facturación Stripe, autenticación y APIs de IA — todo funciona.',
        transition: 'Corte a presentador',
      },
      {
        duration: '1:55-2:00',
        shot: 'Presentador cara a cámara, sonriendo',
        onScreenText: 'ai-empire-steel.vercel.app — Prueba gratuita',
        narration: 'Eso es todo. Enlaces en la descripción. Pruébalo gratis — sin tarjeta de crédito.',
        transition: 'Fundido de salida',
      },
    ],
    cta: 'Enlaces en la descripción — Prueba gratis',
    music: 'Lo-fi chill, de fondo',
    targetAudience: 'Desarrolladores aprendiendo desarrollo SaaS',
  },

  founderStory: {
    id: 'vf-es-01',
    title: 'Por qué construí AI Empire — Historia Build-in-Public',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Fundador en su escritorio, ambiente casual, café en mano',
        onScreenText: 'Construyendo AI Empire — Semana 1',
        narration: 'Hace seis meses, pasaba más tiempo configurando webhooks de Stripe y flujos de autenticación que construyendo mi propio producto. Tenía una idea para una herramienta de IA, pero estaba atrapado en el infierno del boilerplate. Ahí fue cuando decidí construir lo que deseaba que existiera.',
        transition: 'Corte',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montaje: programando de noche, tazas de café, pantallas de terminal',
        onScreenText: 'El Problema: 80% Boilerplate, 20% Producto',
        narration: 'Cada proyecto SaaS comienza igual. Configurar auth. Conectar Stripe. Construir un dashboard. Agregar una API de IA. Configurar la base de datos. Cuando empiezas a construir tu funcionalidad principal, has quemado 3 semanas y mucha energía.',
        transition: 'Disolución cruzada',
      },
      {
        duration: '0:50-1:30',
        shot: 'Grabación de pantalla: creando la primera plantilla NeuraSaaS',
        onScreenText: 'Semana 2: Primera Plantilla — NeuraSaaS',
        narration: 'Así que empecé a construir plantillas. No boilerplate, sino puntos de partida listos para producción. NeuraSaaS fue la primera. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — todo conectado. La usé para construir mi propio SaaS en un fin de semana.',
        transition: 'Corte',
      },
      {
        duration: '1:30-2:10',
        shot: 'Grabación de pantalla: galería de plantillas creciendo',
        onScreenText: 'Semana 4: 6 Plantillas Listas',
        narration: 'Para la semana cuatro, tenía 6 plantillas. NeuraSaaS para SaaS general. NeuraStore para e-commerce. NeuraBlog para contenido. NeuraPortfolio para mostrar trabajo. Cada una sigue los mismos patrones: TypeScript limpio, manejo de errores, integración Stripe y APIs de IA.',
        transition: 'Corte',
      },
      {
        duration: '2:10-2:50',
        shot: 'Grabación de pantalla: benchmarks de Groq AI, inferencia rápida',
        onScreenText: 'La Capa de IA: Groq + Gemini',
        narration: 'La integración de IA es la parte de la que estoy más orgulloso. Groq te ofrece inferencia a 500 tokens por segundo — lo suficientemente rápido para chat en tiempo real. Gemini maneja análisis complejos. Ambos disponibles a través de una API unificada.',
        transition: 'Corte',
      },
      {
        duration: '2:50-3:30',
        shot: 'Fundador cara a cámara, apasionado',
        onScreenText: 'Día de lanzamiento: 500 registros',
        narration: 'Lancé AI Empire un lunes. Publiqué en Twitter, LinkedIn y Reddit. Para el viernes, tenía 500 registros y mis primeros clientes pagando. El tier gratuito fue el gancho — 100 créditos API, sin tarjeta.',
        transition: 'Disolución cruzada',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montaje: testimonios, capturas de pantalla, pagos de Stripe',
        onScreenText: 'Mes 3: €3,000 MRR',
        narration: 'Tres meses después, alcancé €3,000 de MRR. No es dinero que cambia la vida, pero suficiente para probar el concepto. Los comentarios han sido increíbles. Los desarrolladores ahorran semanas de configuración.',
        transition: 'Corte',
      },
      {
        duration: '4:10-4:40',
        shot: 'Grabación de pantalla: roadmap, próximas funcionalidades',
        onScreenText: 'Lo Que Viene: AI Empire v2.0',
        narration: 'Esto es lo que viene. Más plantillas. Un constructor de workflows IA drag-and-drop. Mejor documentación. Y un marketplace comunitario donde los desarrolladores pueden compartir y vender sus propias plantillas.',
        transition: 'Corte',
      },
      {
        duration: '4:40-5:00',
        shot: 'Fundador cara a cámara, sonrisa genuina',
        onScreenText: 'ai-empire-steel.vercel.app — Prueba gratuita',
        narration: 'Si estás construyendo un SaaS y estás harto del boilerplate, prueba AI Empire. Tier gratuito, sin tarjeta de crédito, enlaces en la descripción. Gracias por ver. Nos vemos en el próximo.',
        transition: 'Fundido a logo',
      },
    ],
    cta: 'Prueba gratis — enlace en la descripción',
    music: 'Ambient inspirador, sube gradualmente',
    targetAudience: 'Desarrolladores, fundadores, comunidad build-in-public',
  },
}
