import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-fr-01',
    title: 'AI Empire — Lancez votre SaaS en 48 heures',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Site web',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Plan large : développeur à son bureau, écran avec terminal',
        onScreenText: 'Vous codez encore votre SaaS de zéro ?',
        narration: 'Construire un SaaS de zéro prend des mois. Et si vous pouviez le lancer en 48 heures ?',
        transition: 'Zoom rapide vers l\'écran',
      },
      {
        duration: '0:05-0:15',
        shot: 'Enregistrement d\'écran : galerie de templates AI Empire',
        onScreenText: 'AI Empire — Templates SaaS Next.js 14',
        narration: 'Découvrez AI Empire. Des templates Next.js 14 prêts pour la production avec APIs IA, facturation Stripe et authentification — tout pré-construit.',
        transition: 'Glissement gauche',
      },
      {
        duration: '0:15-0:25',
        shot: 'Enregistrement d\'écran : cloner le template, installer les dépendances',
        onScreenText: '1. Cloner → 2. Configurer → 3. Déployer',
        narration: 'Choisissez un template. Clonez-le. Ajoutez votre clé API Groq. Déployez sur Vercel. C\'est fait.',
        transition: 'Cut',
      },
      {
        duration: '0:25-0:35',
        shot: 'Écran divisé : code à gauche, application IA à droite',
        onScreenText: 'Groq AI + Gemini API intégrés',
        narration: 'Chaque template inclut du chat IA en streaming, des compléments structurés et de l\'analyse de documents — propulsés par Groq et Gemini.',
        transition: 'Zoom arrière',
      },
      {
        duration: '0:35-0:45',
        shot: 'Enregistrement d\'écran : tableau de bord Stripe, configuration abonnements',
        onScreenText: 'Facturation Stripe — Abonnements, Usage, Portail',
        narration: 'La facturation Stripe est pré-configurée. Abonnements, tarification à l\'usage, portail client — tout est connecté.',
        transition: 'Fondu',
      },
      {
        duration: '0:45-0:55',
        shot: 'Montage rapide : 6 interfaces de templates',
        onScreenText: '6 Templates · 50+ Composants · Prêts pour la production',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — choisissez celui qui correspond à votre produit.',
        transition: 'Cut vers CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'Logo AI Empire + URL sur fond sombre',
        onScreenText: 'ai-empire-steel.vercel.app — Essai gratuit',
        narration: 'Commencez gratuitement. Sans carte bancaire. ai-empire-steel.vercel.app',
        transition: 'Fondu de sortie',
      },
    ],
    cta: 'Essayez gratuitement sur ai-empire-steel.vercel.app',
    music: 'Électro entraînante, basse subtile',
    targetAudience: 'Développeurs, indépendants, fondateurs de SaaS',
  },

  socialAd: {
    id: 'va-fr-01',
    title: 'AI Empire — Arrêtez de coder du boilerplate',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: ' Gros plan : développeur frustré, multiples onglets ouverts',
        onScreenText: 'Auth... facturation... dashboards...',
        narration: '',
        transition: 'Cut brutal',
      },
      {
        duration: '0:03-0:08',
        shot: 'Enregistrement d\'écran : galerie de templates AI Empire',
        onScreenText: 'Passez le boilerplate',
        narration: '',
        transition: 'Swipe vers le haut',
      },
      {
        duration: '0:08-0:15',
        shot: 'Enregistrement d\'écran : cloner, npm install, serveur démarré',
        onScreenText: 'Cloner → Installer → Lancer',
        narration: '',
        transition: 'Zoom rapide',
      },
      {
        duration: '0:15-0:22',
        shot: 'Divisé : code à gauche, belle UI à droite avec chat IA',
        onScreenText: 'IA + Stripe + Auth — Pré-construits',
        narration: '',
        transition: 'Glissement gauche',
      },
      {
        duration: '0:22-0:27',
        shot: 'Application déployée sur téléphone, fonctionnelle',
        onScreenText: 'Lancez en 48h, pas 48 jours',
        narration: '',
        transition: 'Cut',
      },
      {
        duration: '0:27-0:30',
        shot: 'Logo AI Empire sur fond dégradé',
        onScreenText: 'Essai gratuit · Sans CB',
        narration: '',
        transition: 'Fondu de sortie',
      },
    ],
    cta: 'Lien en bio',
    music: 'Track tendance entraînante, rythme rapide',
    targetAudience: 'Développeurs 18-35 ans, réseaux sociaux',
  },

  tutorial: {
    id: 'vt-fr-01',
    title: 'Créez un Dashboard SaaS IA en 10 minutes',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Présentateur face caméra, dashboard AI Empire visible',
        onScreenText: 'Dashboard SaaS IA — 10 Min',
        narration: 'Dans cette vidéo, je vais vous montrer comment créer un dashboard SaaS complet propulsé par l\'IA avec les templates AI Empire. C\'est parti.',
        transition: 'Cut vers écran',
      },
      {
        duration: '0:15-0:40',
        shot: 'Enregistrement d\'écran : GitHub, cloner le repo NeuraDashboard',
        onScreenText: 'Étape 1 : Cloner le Template',
        narration: 'D\'abord, rendez-vous sur notre GitHub et clonez le template NeuraDashboard. Lancez npm install pour obtenir toutes les dépendances. Le template utilise Next.js 14, TypeScript et Tailwind — tout ce dont vous avez besoin.',
        transition: 'Cut',
      },
      {
        duration: '0:40-1:10',
        shot: 'Enregistrement d\'écran : configuration .env.local, clés API, base de données',
        onScreenText: 'Étape 2 : Configurer l\'environnement',
        narration: 'Ajoutez vos variables d\'environnement. Votre clé API Groq va ici — obtenez-la gratuitement sur console.groq.com. Configurez votre URL de base de données avec Prisma. Connectez Stripe pour la facturation. Environ 3 minutes.',
        transition: 'Cut',
      },
      {
        duration: '1:10-1:40',
        shot: 'Enregistrement d\'écran : serveur de dev, navigation dans le dashboard',
        onScreenText: 'Étape 3 : Personnaliser et Construire',
        narration: 'Lancez npm run dev et vous avez un dashboard complet avec graphiques temps réel, gestion des utilisateurs et analyses IA. Personnalisez les couleurs, ajoutez votre marque, modifiez les routes API — le code est propre et bien documenté.',
        transition: 'Cut',
      },
      {
        duration: '1:40-1:55',
        shot: 'Enregistrement d\'écran : déploiement Vercel, application live sur téléphone',
        onScreenText: 'Étape 4 : Déployer en production',
        narration: 'Quand vous êtes prêt, poussez sur GitHub et déployez sur Vercel. Un clic. Votre dashboard SaaS IA est en ligne. Facturation Stripe, authentification et APIs IA — tout fonctionne directement.',
        transition: 'Cut vers présentateur',
      },
      {
        duration: '1:55-2:00',
        shot: 'Présentateur face caméra, souriant',
        onScreenText: 'ai-empire-steel.vercel.app — Essai gratuit',
        narration: 'C\'est tout. Liens dans la description. Essayez gratuitement — sans carte bancaire.',
        transition: 'Fondu de sortie',
      },
    ],
    cta: 'Liens dans la description — Essayez gratuitement',
    music: 'Lo-fi chill, en arrière-plan',
    targetAudience: 'Développeurs apprenant le développement SaaS',
  },

  founderStory: {
    id: 'vf-fr-01',
    title: 'Pourquoi j\'ai créé AI Empire — Histoire Build-in-Public',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Fondateur à son bureau, cadre décontracté, café en main',
        onScreenText: 'Construire AI Empire — Semaine 1',
        narration: 'Il y a six mois, je passais plus de temps à configurer des webhooks Stripe et des flux d\'authentification qu\'à construire mon propre produit. J\'avais une idée d\'outil IA, mais j\'étais coincé dans l\'enfer du boilerplate. C\'est là que j\'ai décidé de construire ce qui me manquait.',
        transition: 'Cut',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montage : coding tard le soir, tasses de café, écrans de terminal',
        onScreenText: 'Le Problème : 80% Boilerplate, 20% Produit',
        narration: 'Chaque projet SaaS commence de la même manière. Configurer l\'auth. Connecter Stripe. Construire un dashboard. Ajouter une API IA. Configurer la base de données. Au moment où vous commencez à construire votre fonctionnalité principale, vous avez brûlé 3 semaines et beaucoup d\'énergie.',
        transition: 'Fondu croisé',
      },
      {
        duration: '0:50-1:30',
        shot: 'Enregistrement d\'écran : création du premier template NeuraSaaS',
        onScreenText: 'Semaine 2 : Premier Template — NeuraSaaS',
        narration: 'Alors j\'ai commencé à construire des templates. Pas du boilerplate, mais des points de départ prêts pour la production. NeuraSaaS était le premier. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — tout connecté. Je l\'ai utilisé pour construire mon propre SaaS en un week-end.',
        transition: 'Cut',
      },
      {
        duration: '1:30-2:10',
        shot: 'Enregistrement d\'écran : galerie de templates qui s\'agrandit',
        onScreenText: 'Semaine 4 : 6 Templates Prêts',
        narration: 'En quatre semaines, j\'avais 6 templates. NeuraSaaS pour le SaaS général. NeuraStore pour l\'e-commerce. NeuraBlog pour le contenu. NeuraPortfolio pour présenter votre travail. Chacun suit les mêmes patterns : TypeScript propre, gestion d\'erreurs, intégration Stripe et APIs IA.',
        transition: 'Cut',
      },
      {
        duration: '2:10-2:50',
        shot: 'Enregistrement d\'écran : benchmarks Groq AI, inférence rapide',
        onScreenText: 'La Couche IA : Groq + Gemini',
        narration: 'L\'intégration IA est la partie dont je suis le plus fier. Groq vous offre une inférence à 500 tokens par seconde — assez rapide pour du chat en temps réel. Gemini gère l\'analyse complexe. Les deux sont disponibles via une API unifiée. Pas de gestion de clés multiples. Ça fonctionne.',
        transition: 'Cut',
      },
      {
        duration: '2:50-3:30',
        shot: 'Fondateur face caméra, passionné',
        onScreenText: 'Jour de lancement : 500 inscriptions',
        narration: 'J\'ai lancé AI Empire un lundi. Publié sur Twitter, LinkedIn et Reddit. Le vendredi, j\'avais 500 inscriptions et mes premiers clients payants. L\'essai gratuit était l\'appât — 100 crédits API, sans carte bancaire. Les développeurs adorent essayer avant d\'acheter.',
        transition: 'Fondu croisé',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montage : témoignages utilisateurs, captures d\'écran, paiements Stripe',
        onScreenText: 'Mois 3 : 3 000€ MRR',
        narration: 'Trois mois plus tard, j\'ai atteint 3 000€ de MRR. Pas de l\'argent qui change la vie, mais assez pour prouver le concept. Les retours ont été incroyables. Les développeurs économisent des semaines de configuration. Un client a lancé son SaaS en 2 jours avec NeuraSaaS.',
        transition: 'Cut',
      },
      {
        duration: '4:10-4:40',
        shot: 'Enregistrement d\'écran : feuille de route, futures fonctionnalités',
        onScreenText: 'La Suite : AI Empire v2.0',
        narration: 'Voici ce qui arrive. Plus de templates. Un constructeur de workflows IA drag-and-drop. Une meilleure documentation. Et une place de marché communautaire où les développeurs peuvent partager et vendre leurs propres templates.',
        transition: 'Cut',
      },
      {
        duration: '4:40-5:00',
        shot: 'Fondateur face caméra, sourire sincère',
        onScreenText: 'ai-empire-steel.vercel.app — Essai gratuit',
        narration: 'Si vous construisez un SaaS et que vous en avez assez du boilerplate, essayez AI Empire. Essai gratuit, sans carte bancaire, liens dans la description. Merci d\'avoir regardé. On se retrouve dans la prochaine vidéo.',
        transition: 'Fondu vers logo',
      },
    ],
    cta: 'Essayez gratuitement — lien dans la description',
    music: 'Ambient inspirant, monte progressivement',
    targetAudience: 'Développeurs, fondateurs, communauté build-in-public',
  },
}
