import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-it-01',
    title: 'AI Empire — Lancia il tuo SaaS in 48 ore',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Sito web',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Inquadratura larga: sviluppatore alla scrivania, schermo laptop con terminale',
        onScreenText: 'Stai ancora costruendo il tuo SaaS da zero?',
        narration: 'Costruire un SaaS da zero richiede mesi. E se potessi lanciarlo in 48 ore?',
        transition: 'Zoom rapido sullo schermo',
      },
      {
        duration: '0:05-0:15',
        shot: 'Screen recording: galleria template AI Empire',
        onScreenText: 'AI Empire — Template SaaS Next.js 14',
        narration: 'Scopri AI Empire. Template Next.js 14 pronti per la produzione con API AI, fatturazione Stripe e autenticazione — tutto pre-costruito.',
        transition: 'Scorrimento sinistra',
      },
      {
        duration: '0:15-0:25',
        shot: 'Screen recording: clonare template, installare dipendenze',
        onScreenText: '1. Clona → 2. Configura → 3. Distribuisci',
        narration: 'Scegli un template. Clonalo. Aggiungi la tua chiave API Groq. Distribuisci su Vercel. Fatto.',
        transition: 'Taglio',
      },
      {
        duration: '0:25-0:35',
        shot: 'Schermo diviso: codice a sinistra, app con chat AI a destra',
        onScreenText: 'Groq AI + Gemini API integrati',
        narration: 'Ogni template include chat AI in streaming, completions strutturate e analisi documenti — alimentati da Groq e Gemini.',
        transition: 'Zoom-out',
      },
      {
        duration: '0:35-0:45',
        shot: 'Screen recording: dashboard Stripe, configurazione abbonamenti',
        onScreenText: 'Fatturazione Stripe — Abbonamenti, Utilizzo, Portale',
        narration: 'La fatturazione Stripe è pre-configurata. Abbonamenti, prezzi all\'utilizzo, portale clienti — tutto connesso.',
        transition: 'Dissolvenza',
      },
      {
        duration: '0:45-0:55',
        shot: 'Montaggio rapido: 6 interfacce template',
        onScreenText: '6 Template · 50+ Componenti · Pronti per la produzione',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — scegli quello adatto al tuo prodotto.',
        transition: 'Taglio al CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'Logo AI Empire + URL su sfondo scuro',
        onScreenText: 'ai-empire-steel.vercel.app — Prova gratuita',
        narration: 'Inizia gratis. Nessuna carta di credito richiesta. ai-empire-steel.vercel.app',
        transition: 'Dissolvenza finale',
      },
    ],
    cta: 'Prova gratis su ai-empire-steel.vercel.app',
    music: 'Elettronica ritmata, basso sottile',
    targetAudience: 'Sviluppatori, hacker indipendenti, fondatori SaaS',
  },

  socialAd: {
    id: 'va-it-01',
    title: 'AI Empire — Smetti di programmare boilerplate',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'Primo piano: sviluppatore frustrato, più schede aperte',
        onScreenText: 'Auth... fatturazione... dashboard...',
        narration: '',
        transition: 'Taglio netto',
      },
      {
        duration: '0:03-0:08',
        shot: 'Screen recording: galleria template AI Empire',
        onScreenText: 'Supera il boilerplate',
        narration: '',
        transition: 'Swipe verso l\'alto',
      },
      {
        duration: '0:08-0:15',
        shot: 'Screen recording: clonare, npm install, server avviato',
        onScreenText: 'Clona → Installa → Esegui',
        narration: '',
        transition: 'Zoom rapido',
      },
      {
        duration: '0:15-0:22',
        shot: 'Diviso: codice a sinistra, bella UI a destra con chat AI',
        onScreenText: 'AI + Stripe + Auth — Pre-costruiti',
        narration: '',
        transition: 'Scorrimento sinistra',
      },
      {
        duration: '0:22-0:27',
        shot: 'App distribuita su telefono, funziona perfettamente',
        onScreenText: 'Lancia in 48h, non in 48 giorni',
        narration: '',
        transition: 'Taglio',
      },
      {
        duration: '0:27-0:30',
        shot: 'Logo AI Empire su sfondo sfumato',
        onScreenText: 'Prova gratuita · Nessuna carta',
        narration: '',
        transition: 'Dissolvenza finale',
      },
    ],
    cta: 'Link in bio',
    music: 'Track trending ritmato, ritmo veloce',
    targetAudience: 'Sviluppatori 18-35 anni, social media',
  },

  tutorial: {
    id: 'vt-it-01',
    title: 'Crea un Dashboard SaaS con AI in 10 minuti',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Presentatore in camera, dashboard AI Empire visibile dietro',
        onScreenText: 'Dashboard SaaS AI — 10 Min',
        narration: 'In questo video ti mostrerò come creare un dashboard SaaS completo con AI usando i template di AI Empire. Andiamo.',
        transition: 'Taglio allo schermo',
      },
      {
        duration: '0:15-0:40',
        shot: 'Screen recording: GitHub, clonare repo NeuraDashboard',
        onScreenText: 'Passo 1: Clona il Template',
        narration: 'Prima, vai al nostro GitHub e clona il template NeuraDashboard. Esegui npm install per ottenere tutte le dipendenze. Il template usa Next.js 14, TypeScript e Tailwind — tutto quello che ti serve.',
        transition: 'Taglio',
      },
      {
        duration: '0:40-1:10',
        shot: 'Screen recording: setup .env.local, chiavi API, database',
        onScreenText: 'Passo 2: Configura l\'Ambiente',
        narration: 'Aggiungi le tue variabili d\'ambiente. La chiave API Groq va qui — ottienila gratis su console.groq.com. Configura l\'URL del database con Prisma. Connetti Stripe per la fatturazione. Ci vogliono circa 3 minuti.',
        transition: 'Taglio',
      },
      {
        duration: '1:10-1:40',
        shot: 'Screen recording: eseguire dev server, navigare il dashboard',
        onScreenText: 'Passo 3: Personalizza e Costruisci',
        narration: 'Esegui npm run dev e hai un dashboard completo con grafici in tempo reale, gestione utenti e analisi AI. Personalizza i colori, aggiungi il tuo branding, modifica le route API — il codice è pulito e ben documentato.',
        transition: 'Taglio',
      },
      {
        duration: '1:40-1:55',
        shot: 'Screen recording: deployment Vercel, app live su telefono',
        onScreenText: 'Passo 4: Distribuisci in Produzione',
        narration: 'Quando sei pronto, fai push su GitHub e distribuisci su Vercel. Un clic. Il tuo dashboard SaaS AI è online. Fatturazione Stripe, autenticazione e API AI — tutto funziona.',
        transition: 'Taglio al presentatore',
      },
      {
        duration: '1:55-2:00',
        shot: 'Presentatore in camera, sorridente',
        onScreenText: 'ai-empire-steel.vercel.app — Prova gratuita',
        narration: 'Ecco fatto. Link nella descrizione. Provalo gratis — senza carta di credito.',
        transition: 'Dissolvenza finale',
      },
    ],
    cta: 'Link nella descrizione — Prova gratis',
    music: 'Lo-fi chill, di sottofondo',
    targetAudience: 'Sviluppatori che imparano lo sviluppo SaaS',
  },

  founderStory: {
    id: 'vf-it-01',
    title: 'Perché ho costruito AI Empire — Storia Build-in-Public',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Fondatore alla scrivania, ambiente informale, caffè in mano',
        onScreenText: 'Costruire AI Empire — Settimana 1',
        narration: 'Sei mesi fa passavo più tempo a configurare webhook Stripe e flussi di autenticazione che a costruire il mio prodotto. Avevo un\'idea per uno strumento AI, ma ero bloccato nell\'inferno del boilerplate. È lì che ho deciso di costruire quello che desideravo esistesse.',
        transition: 'Taglio',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montaggio: coding notturno, tazze di caffè, schermi terminal',
        onScreenText: 'Il Problema: 80% Boilerplate, 20% Prodotto',
        narration: 'Ogni progetto SaaS inizia allo stesso modo. Configurare auth. Collegare Stripe. Costruire un dashboard. Aggiungere un\'API AI. Configurare il database. Quando inizi a costruire la tua funzionalità principale, hai bruciato 3 settimane e molta energia.',
        transition: 'Dissolvenza incrociata',
      },
      {
        duration: '0:50-1:30',
        shot: 'Screen recording: creazione del primo template NeuraSaaS',
        onScreenText: 'Settimana 2: Primo Template — NeuraSaaS',
        narration: 'Così ho iniziato a costruire template. Non boilerplate, ma punti di partenza pronti per la produzione. NeuraSaaS è stato il primo. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — tutto connesso. L\'ho usato per costruire il mio SaaS in un weekend.',
        transition: 'Taglio',
      },
      {
        duration: '1:30-2:10',
        shot: 'Screen recording: galleria template in espansione',
        onScreenText: 'Settimana 4: 6 Template Pronti',
        narration: 'Per la settimana quattro avevo 6 template. NeuraSaaS per SaaS generale. NeuraStore per e-commerce. NeuraBlog per contenuti. NeuraPortfolio per mostrare il lavoro. Ognuno segue gli stessi pattern: TypeScript pulito, gestione errori, integrazione Stripe e API AI.',
        transition: 'Taglio',
      },
      {
        duration: '2:10-2:50',
        shot: 'Screen recording: benchmark Groq AI, inferenza veloce',
        onScreenText: 'Lo Strato AI: Groq + Gemini',
        narration: 'L\'integrazione AI è la parte di cui sono più orgoglioso. Groq offre inferenza a 500 token al secondo — abbastanza veloce per chat in tempo reale. Gemini gestisce analisi complesse. Entrambi disponibili tramite un\'API unificata.',
        transition: 'Taglio',
      },
      {
        duration: '2:50-3:30',
        shot: 'Fondatore in camera, appassionato',
        onScreenText: 'Giorno del lancio: 500 iscrizioni',
        narration: 'Ho lanciato AI Empire un lunedì. Pubblicato su Twitter, LinkedIn e Reddit. Entro venerdì avevo 500 iscrizioni e i miei primi clienti paganti. Il tier gratuito è stato l\'amo — 100 crediti API, nessuna carta.',
        transition: 'Dissolvenza incrociata',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montaggio: testimonianze, screenshot, pagamenti Stripe',
        onScreenText: 'Mese 3: €3.000 MRR',
        narration: 'Tre mesi dopo ho raggiunto €3.000 MRR. Non soldi che cambiano la vita, ma abbastanza per dimostrare il concetto. Il feedback è stato incredibile. Gli sviluppatori risparmiano settimane di setup.',
        transition: 'Taglio',
      },
      {
        duration: '4:10-4:40',
        shot: 'Screen recording: roadmap, funzionalità in arrivo',
        onScreenText: 'Il Futuro: AI Empire v2.0',
        narration: 'Ecco cosa arriva. Più template. Un costruttore di workflow AI drag-and-drop. Migliore documentazione. E un marketplace comunitario dove gli sviluppatori possono condivendere e vendere i propri template.',
        transition: 'Taglio',
      },
      {
        duration: '4:40-5:00',
        shot: 'Fondatore in camera, sorriso genuino',
        onScreenText: 'ai-empire-steel.vercel.app — Prova gratuita',
        narration: 'Se stai costruendo un SaaS e sei stanco del boilerplate, prova AI Empire. Tier gratuito, nessuna carta di credito, link nella descrizione. Grazie per aver guardato. Ci vediamo al prossimo.',
        transition: 'Dissolvenza al logo',
      },
    ],
    cta: 'Prova gratis — link nella descrizione',
    music: 'Ambient ispiratore, cresce gradualmente',
    targetAudience: 'Sviluppatori, fondatori, community build-in-public',
  },
}
