import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-ja-01',
    title: 'AI Empire — 48時間でSaaSをローンチ',
    type: 'product-demo',
    duration: '60秒',
    platform: 'YouTube、ウェブサイト',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'ワイドショット：デスクの開発者、ラップトップにターミナル画面',
        onScreenText: 'まだゼロからSaaSを構築していますか？',
        narration: 'ゼロからSaaSを構築するには数ヶ月かかります。48時間でローンチできたらどうですか？',
        transition: '画面への高速ズーム',
      },
      {
        duration: '0:05-0:15',
        shot: '画面録画：AI Empireテンプレートギャラリー',
        onScreenText: 'AI Empire — Next.js 14 SaaSテンプレート',
        narration: 'AI Empireをご紹介。AI API、Stripe決済、認証が組み込まれたNext.js 14の本番環境対応テンプレート。',
        transition: '左にスライド',
      },
      {
        duration: '0:15-0:25',
        shot: '画面録画：テンプレートのクローン、依存関係のインストール',
        onScreenText: '1. クローン → 2. 設定 → 3. デプロイ',
        narration: 'テンプレートを選んでクローン。Groq APIキーを追加。Vercelにデプロイ。完了。',
        transition: 'カット',
      },
      {
        duration: '0:25-0:35',
        shot: '分割画面：左にコード、右にAIチャット付きアプリ',
        onScreenText: 'Groq AI + Gemini API 統合済み',
        narration: '全テンプレートにストリーミングAIチャット、構造化された補完、ドキュメント分析が含まれています。',
        transition: 'ズームアウト',
      },
      {
        duration: '0:35-0:45',
        shot: '画面録画：Stripeダッシュボード、サブスクリプション設定',
        onScreenText: 'Stripe決済 — サブスクリプション、従量課金、ポータル',
        narration: 'Stripe決済は事前設定済み。サブスクリプション、従量課金、顧客ポータル — すべて接続済み。',
        transition: 'フェード',
      },
      {
        duration: '0:45-0:55',
        shot: '高速モンタージュ：6つのテンプレートUI',
        onScreenText: '6テンプレート · 50+コンポーネント · 本番環境対応',
        narration: 'NeuraSaaS、NeuraStore、NeuraBlog、NeuraPortfolio — あなたの製品に合ったものを選んでください。',
        transition: 'CTAへのカット',
      },
      {
        duration: '0:55-1:00',
        shot: 'AI Empireロゴ + URL（暗い背景）',
        onScreenText: 'ai-empire-steel.vercel.app — 無料トライアル',
        narration: '無料で始められます。クレジットカード不要。ai-empire-steel.vercel.app',
        transition: 'フェードアウト',
      },
    ],
    cta: 'ai-empire-steel.vercel.appで無料トライアル',
    music: 'アップテンポの電子音楽、控えめなベース',
    targetAudience: '開発者、インディーハッカー、SaaS創業者',
  },

  socialAd: {
    id: 'va-ja-01',
    title: 'AI Empire — ボイラープレートのコーディングをやめよう',
    type: 'social-ad',
    duration: '30秒',
    platform: 'Instagram Reels、TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'クローズアップ：イライラした開発者、複数タブが開いている',
        onScreenText: 'Auth...決済...ダッシュボード...',
        narration: '',
        transition: 'ハードカット',
      },
      {
        duration: '0:03-0:08',
        shot: '画面録画：AI Empireテンプレートギャラリー',
        onScreenText: 'ボイラープレートをスキップ',
        narration: '',
        transition: '上にスワイプ',
      },
      {
        duration: '0:08-0:15',
        shot: '画面録画：クローン、npm install、サーバー起動',
        onScreenText: 'クローン → インストール → 実行',
        narration: '',
        transition: '高速ズーム',
      },
      {
        duration: '0:15-0:22',
        shot: '分割：左にコード、右にAIチャット付き美しいUI',
        onScreenText: 'AI + Stripe + Auth — 事前構築済み',
        narration: '',
        transition: '左にスライド',
      },
      {
        duration: '0:22-0:27',
        shot: '電話にデプロイされたアプリ、完璧に動作中',
        onScreenText: '48日ではなく48時間でローンチ',
        narration: '',
        transition: 'カット',
      },
      {
        duration: '0:27-0:30',
        shot: 'AI Empireロゴ（グラデーション背景）',
        onScreenText: '無料トライアル · カード不要',
        narration: '',
        transition: 'フェードアウト',
      },
    ],
    cta: 'プロフィールリンク',
    music: 'トレンドアップテンポトラック、速いリズム',
    targetAudience: '開発者 18-35歳、ソーシャルメディア',
  },

  tutorial: {
    id: 'vt-ja-01',
    title: '10分でAI SaaSダッシュボードを作成',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'プレゼンター正面、背後にAI Empireダッシュボード',
        onScreenText: 'AI SaaSダッシュボード — 10分',
        narration: 'この動画では、AI Empireテンプレートを使ってAI搭載のSaaSダッシュボードをCompleteに作る方法をご紹介します。始めましょう。',
        transition: '画面へのカット',
      },
      {
        duration: '0:15-0:40',
        shot: '画面録画：GitHub、NeuraDashboardリポをクローン',
        onScreenText: 'ステップ1：テンプレートをクローン',
        narration: 'まずGitHubでNeuraDashboardテンプレートをクローン。npm installで全依存関係を取得。テンプレートはNext.js 14、TypeScript、Tailwindを使用しています。',
        transition: 'カット',
      },
      {
        duration: '0:40-1:10',
        shot: '画面録画：.env.local設定、APIキー、データベース',
        onScreenText: 'ステップ2：環境を設定',
        narration: '環境変数を追加。Groq APIキーはここに — console.groq.comで無料取得。PrismaでデータベースURLを設定。Stripeを接続。約3分で完了。',
        transition: 'カット',
      },
      {
        duration: '1:10-1:40',
        shot: '画面録画：dev server起動、ダッシュボードを閲覧',
        onScreenText: 'ステップ3：カスタマイズして構築',
        narration: 'npm run devでリアルタイムチャート、ユーザー管理、AI分析を備えた完全なダッシュボードが完成。カラーやブランドをカスタマイズ。コードはクリーンでドキュメント充実。',
        transition: 'カット',
      },
      {
        duration: '1:40-1:55',
        shot: '画面録画：Vercelデプロイ、電話でアプリがライブ',
        onScreenText: 'ステップ4：本番環境にデプロイ',
        narration: '準備ができたらGitHubにプッシュ、Vercelにデプロイ。ワンクリックでAI SaaSダッシュボードが公開。Stripe決済、認証、AI API — すべて動作。',
        transition: 'プレゼンターへのカット',
      },
      {
        duration: '1:55-2:00',
        shot: 'プレゼンター正面、笑顔',
        onScreenText: 'ai-empire-steel.vercel.app — 無料トライアル',
        narration: '以上です。説明欄にリンクがあります。無料でお試しください。クレジットカード不要。',
        transition: 'フェードアウト',
      },
    ],
    cta: '説明欄のリンク — 無料トライアル',
    music: 'チルなローファイ、背景',
    targetAudience: 'SaaS開発を学んでいる開発者',
  },

  founderStory: {
    id: 'vf-ja-01',
    title: 'なぜAI Empireを構築したか — ビルドインパブリックストーリー',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube、LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: '創業者、デスクで、カジュアルな雰囲気、コーヒー片手に',
        onScreenText: 'AI Empireを構築 — 週1',
        narration: '6ヶ月前、私はStripe Webhookや認証フローの設定に自分の製品を作る時間よりも多くの時間を費やしていました。AIツールのアイアアはありましたが、ボイラープレート地獄に閉じ込められていました。そこで、私が欲しかったものを構築することに決めました。',
        transition: 'カット',
      },
      {
        duration: '0:20-0:50',
        shot: 'モンタージュ：深夜のコーディング、コーヒー、ターミナル画面',
        onScreenText: '問題：80%ボイラープレート、20%製品',
        narration: 'すべてのSaaSプロジェクトは同じように始まります。Authを設定。Stripeを接続。ダッシュボードを構築。AI APIを追加。データベースを設定。実際の機能を書き始める頃には、3週間とエネルギーの大半を費やしています。',
        transition: 'クロスディゾルブ',
      },
      {
        duration: '0:50-1:30',
        shot: '画面録画：最初のNeuraSaaSテンプレートを作成',
        onScreenText: '週2：最初のテンプレート — NeuraSaaS',
        narration: 'そこでテンプレートの構築を始めました。ボイラープレートではなく、本番環境対応の出発点を。NeuraSaaSが最初でした。Next.js 14、Tailwind、Prisma、Stripe、Groq AI — すべて接続。週末に自分で使うSaaSを構築しました。',
        transition: 'カット',
      },
      {
        duration: '1:30-2:10',
        shot: '画面録画：テンプレートギャラリーが拡大',
        onScreenText: '週4：6テンプレート完成',
        narration: '4週目には6つのテンプレートがありました。汎用SaaS用NeuraSaaS、Eコマース用NeuraStore、コンテンツ用NeuraBlog、ポートフォリオ用NeuraPortfolio。すべて同じパターン：クリーンなTypeScript、エラーハンドリング、Stripe統合、AI API。',
        transition: 'カット',
      },
      {
        duration: '2:10-2:50',
        shot: '画面録画：Groq AIベンチマーク、高速推論',
        onScreenText: 'AIレイヤー：Groq + Gemini',
        narration: 'AI統合が一番の自慢です。Groqは毎秒500トークンの推論を提供 — リアルタイムチャットに十分な速さ。Geminiは複雑な分析を処理。両方とも統一APIで利用可能。',
        transition: 'カット',
      },
      {
        duration: '2:50-3:30',
        shot: '創業者、情熱的に',
        onScreenText: 'ローンチ日：500登録',
        narration: '月曜にAI Empireをローンチ。Twitter、LinkedIn、Redditに投稿。金曜までに500登録と初の有料顧客。無料ティアがフックに — 100 APIクレジット、カード不要。',
        transition: 'クロスディゾルブ',
      },
      {
        duration: '3:30-4:10',
        shot: 'モンタージュ：ユーザーテストモニアル、ダッシュボードスクリーンショット',
        onScreenText: '月3：€3,000 MRR',
        narration: '3ヶ月で€3,000 MRRに到達。人生を変える額ではありませんが、コンセプトを証明するには十分。フィードバックは信じられないほど良い。開発者は数週間のセットアップを節約。',
        transition: 'カット',
      },
      {
        duration: '4:10-4:40',
        shot: '画面録画：ロードマップ、今後の機能',
        onScreenText: '次：AI Empire v2.0',
        narration: '次は何が来るか。テンプレート追加。ドラッグアンドドロップAIワークフロービルダー。より良いドキュメント。開発者がテンプレートを共有・販売できるコミュニティマーケットプレイス。',
        transition: 'カット',
      },
      {
        duration: '4:40-5:00',
        shot: '創業者、素顔の笑顔',
        onScreenText: 'ai-empire-steel.vercel.app — 無料トライアル',
        narration: 'SaaSを構築していてボイラープレートにうんざりなら、AI Empireをお試しください。無料ティア、カード不要、説明欄にリンク。ご視聴ありがとうございました。また次回お会いしましょう。',
        transition: 'ロゴへのフェード',
      },
    ],
    cta: '無料トライアル — 説明欄のリンク',
    music: 'インスピレーション系アンビエント、徐々に盛り上がる',
    targetAudience: '開発者、創業者、ビルドインパブリックコミュニティ',
  },
}
