import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-ko-01',
    title: 'AI Empire — 48시간 만에 SaaS 출시',
    type: 'product-demo',
    duration: '60초',
    platform: 'YouTube, 웹사이트',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: '와이드 샷: 데스크의 개발자, 노트북에 터미널 화면',
        onScreenText: '아직 SaaS를 처음부터 만드시나요?',
        narration: '처음부터 SaaS를 만들면 몇 달이 걸립니다. 48시간 만에 출시할 수 있다면?',
        transition: '화면으로 빠른 줌',
      },
      {
        duration: '0:05-0:15',
        shot: '화면 녹화: AI Empire 템플릿 갤러리',
        onScreenText: 'AI Empire — Next.js 14 SaaS 템플릿',
        narration: 'AI Empire를 소개합니다. AI API, Stripe 결제, 인증이 포함된 Next.js 14 프로덕션 템플릿.',
        transition: '왼쪽으로 슬라이드',
      },
      {
        duration: '0:15-0:25',
        shot: '화면 녹화: 템플릿 클론, 의존성 설치',
        onScreenText: '1. 클론 → 2. 설정 → 3. 배포',
        narration: '템플릿을 선택하세요. 클론하세요. Groq API 키를 추가하세요. Vercel에 배포하세요. 끝.',
        transition: '컷',
      },
      {
        duration: '0:25-0:35',
        shot: '분할 화면: 왼쪽 코드, 오른쪽 AI 채팅 앱',
        onScreenText: 'Groq AI + Gemini API 통합됨',
        narration: '모든 템플릿에 스트리밍 AI 채팅, 구조화된 완성, 문서 분석이 포함되어 있습니다.',
        transition: '줌 아웃',
      },
      {
        duration: '0:35-0:45',
        shot: '화면 녹화: Stripe 대시보드, 구독 설정',
        onScreenText: 'Stripe 결제 — 구독, 사용량, 포털',
        narration: 'Stripe 결제가 사전 설정되어 있습니다. 구독, 사용량 기반 가격, 고객 포털 — 모두 연결됨.',
        transition: '페이드',
      },
      {
        duration: '0:45-0:55',
        shot: '빠른 몬타주: 6개 템플릿 UI',
        onScreenText: '6 템플릿 · 50+ 컴포넌트 · 프로덕션 준비',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — 귀하의 제품에 맞는 것을 선택하세요.',
        transition: 'CTA로 컷',
      },
      {
        duration: '0:55-1:00',
        shot: 'AI Empire 로고 + URL (어두운 배경)',
        onScreenText: 'ai-empire-steel.vercel.app — 무료 체험',
        narration: '무료로 시작하세요. 신용카드 불필요. ai-empire-steel.vercel.app',
        transition: '페이드 아웃',
      },
    ],
    cta: 'ai-empire-steel.vercel.app에서 무료 체험',
    music: '업비트 일렉트로닉, 은은한 베이스',
    targetAudience: '개발자, 인디 해커, SaaS 창업자',
  },

  socialAd: {
    id: 'va-ko-01',
    title: 'AI Empire — 보일러플레이트 코딩을 멈추세요',
    type: 'social-ad',
    duration: '30초',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: '클로즈업: 짜증난 개발자, 여러 탭 열려 있음',
        onScreenText: 'Auth... 결제... 대시보드...',
        narration: '',
        transition: '하드 컷',
      },
      {
        duration: '0:03-0:08',
        shot: '화면 녹화: AI Empire 템플릿 갤러리',
        onScreenText: '보일러플레이트를 건너뛰세요',
        narration: '',
        transition: '위로 스와이프',
      },
      {
        duration: '0:08-0:15',
        shot: '화면 녹화: 클론, npm install, 서버 시작',
        onScreenText: '클론 → 설치 → 실행',
        narration: '',
        transition: '빠른 줌',
      },
      {
        duration: '0:15-0:22',
        shot: '분할: 왼쪽 코드, 오른쪽 AI 채팅이 포함된 아름다운 UI',
        onScreenText: 'AI + Stripe + Auth — 사전 구축됨',
        narration: '',
        transition: '왼쪽으로 슬라이드',
      },
      {
        duration: '0:22-0:27',
        shot: '핸드폰에 배포된 앱, 완벽하게 작동',
        onScreenText: '48일이 아닌 48시간 만에 출시',
        narration: '',
        transition: '컷',
      },
      {
        duration: '0:27-0:30',
        shot: 'AI Empire 로고 (그라데이션 배경)',
        onScreenText: '무료 체험 · 카드 불필요',
        narration: '',
        transition: '페이드 아웃',
      },
    ],
    cta: '프로필 링크',
    music: '트렌딩 업비트 트랙, 빠른 리듬',
    targetAudience: '개발자 18-35세, 소셜 미디어',
  },

  tutorial: {
    id: 'vt-ko-01',
    title: '10분 만에 AI SaaS 대시보드 만들기',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: '사회자 정면, 뒤에 AI Empire 대시보드',
        onScreenText: 'AI SaaS 대시보드 — 10분',
        narration: '이 영상에서는 AI Empire 템플릿을 사용하여 완전한 AI 기반 SaaS 대시보드를 만드는 방법을 보여드리겠습니다. 시작합시다.',
        transition: '화면으로 컷',
      },
      {
        duration: '0:15-0:40',
        shot: '화면 녹화: GitHub, NeuraDashboard 리포 클론',
        onScreenText: '1단계: 템플릿 클론',
        narration: '먼저 GitHub에서 NeuraDashboard 템플릿을 클론하세요. npm install로 모든 의존성을 설치하세요. 템플릿은 Next.js 14, TypeScript, Tailwind를 사용합니다.',
        transition: '컷',
      },
      {
        duration: '0:40-1:10',
        shot: '화면 녹화: .env.local 설정, API 키, 데이터베이스',
        onScreenText: '2단계: 환경 설정',
        narration: '환경 변수를 추가하세요. Groq API 키는 여기에 — console.groq.com에서 무료로 받으세요. Prisma로 데이터베이스 URL을 설정하세요. Stripe를 연결하세요. 약 3분 정도 걸립니다.',
        transition: '컷',
      },
      {
        duration: '1:10-1:40',
        shot: '화면 녹화: dev server 실행, 대시보드 탐색',
        onScreenText: '3단계: 사용자 정의 및 구축',
        narration: 'npm run dev를 실행하면 실시간 차트, 사용자 관리, AI 분석이 포함된 완전한 대시보드가 있습니다. 색상과 브랜딩을 사용자 정의하세요. 코드는 깔끔하고 문서화가 잘 되어 있습니다.',
        transition: '컷',
      },
      {
        duration: '1:40-1:55',
        shot: '화면 녹화: Vercel 배포, 핸드폰에서 앱 라이브',
        onScreenText: '4단계: 프로덕션 배포',
        narration: '준비가 되면 GitHub에 푸시하고 Vercel에 배포하세요. 원클릭으로 AI SaaS 대시보드가 라이브됩니다. Stripe 결제, 인증, AI API — 모두 작동합니다.',
        transition: '사회자에게 컷',
      },
      {
        duration: '1:55-2:00',
        shot: '사회자 정면, 미소',
        onScreenText: 'ai-empire-steel.vercel.app — 무료 체험',
        narration: '끝났습니다. 설명란에 링크가 있습니다. 무료로 체험하세요. 신용카드 불필요.',
        transition: '페이드 아웃',
      },
    ],
    cta: '설명란의 링크 — 무료 체험',
    music: '치르한 로파이, 배경',
    targetAudience: 'SaaS 개발을 배우는 개발자',
  },

  founderStory: {
    id: 'vf-ko-01',
    title: 'AI Empire를 만든 이유 — 빌드인퍼블릭 스토리',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: '창업자, 데스크, 캐주얼한 분위기, 커피를 들고',
        onScreenText: 'AI Empire 구축 — 1주차',
        narration: '6개월 전, 저는 Stripe 웹훅과 인증 흐름 설정에 실제 제품을 만드는 것보다 더 많은 시간을 할애하고 있었습니다. AI 도구 아이디어는 있었지만 보일러플레이트 지옥에 갇혀 있었습니다. 그래서 제가 원했던 것을 만들기로 결심했습니다.',
        transition: '컷',
      },
      {
        duration: '0:20-0:50',
        shot: '몬타주: 심야 코딩, 커피잔, 터미널 화면',
        onScreenText: '문제: 80% 보일러플레이트, 20% 제품',
        narration: '모든 SaaS 프로젝트는 같은 방식으로 시작합니다. Auth 설정. Stripe 연결. 대시보드 구축. AI API 추가. 데이터베이스 설정. 실제 기능을 만들기 시작할 즈음에는 3주와 많은 에너지를 소진했습니다.',
        transition: '크로스 디졸브',
      },
      {
        duration: '0:50-1:30',
        shot: '화면 녹화: 첫 번째 NeuraSaaS 템플릿 제작',
        onScreenText: '2주차: 첫 번째 템플릿 — NeuraSaaS',
        narration: '그래서 템플릿 구축을 시작했습니다. 보일러플레이트가 아닌 프로덕션 준비가 된 출발점. NeuraSaaS가 첫 번째였습니다. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — 모두 연결. 주말에 제 SaaS를 만들었습니다.',
        transition: '컷',
      },
      {
        duration: '1:30-2:10',
        shot: '화면 녹화: 템플릿 갤러리 확장',
        onScreenText: '4주차: 6개 템플릿 완성',
        narration: '4주째에 템플릿 6개가 있었습니다. 범용 SaaS용 NeuraSaaS, 이커머스용 NeuraStore, 콘텐츠용 NeuraBlog, 포트폴리오용 NeuraPortfolio. 모두 동일한 패턴: 깔끔한 TypeScript, 에러 처리, Stripe 통합, AI API.',
        transition: '컷',
      },
      {
        duration: '2:10-2:50',
        shot: '화면 녹화: Groq AI 벤치마크, 빠른 추론',
        onScreenText: 'AI 레이어: Groq + Gemini',
        narration: 'AI 통합이 가장 자랑스러운 부분입니다. Groq는 초당 500토큰의 추론을 제공 — 실시간 채팅에 충분한 속도. Gemini는 복잡한 분석을 처리. 둘 다 통합 API로 사용 가능.',
        transition: '컷',
      },
      {
        duration: '2:50-3:30',
        shot: '창업자, 열정적으로',
        onScreenText: '출시일: 500명 등록',
        narration: '월요일에 AI Empire를 출시. Twitter, LinkedIn, Reddit에 게시. 금요일까지 500명 등록과 첫 유료 고객. 무료 티어가 미끼 — 100 API 크레딧, 카드 불필요.',
        transition: '크로스 디졸브',
      },
      {
        duration: '3:30-4:10',
        shot: '몬타주: 사용자 후기, 대시보드 스크린샷, Stripe 결제',
        onScreenText: '3개월: €3,000 MRR',
        narration: '3개월 만에 €3,000 MRR에 도달. 인생을 바꾸는 돈은 아니지만 개념을 증명하기에는 충분. 피드백은 놀라웠습니다. 개발자들이 수 주의 설정을 절약하고 있습니다.',
        transition: '컷',
      },
      {
        duration: '4:10-4:40',
        shot: '화면 녹화: 로드맵, 향후 기능',
        onScreenText: '다음: AI Empire v2.0',
        narration: '다가오는 것들. 더 많은 템플릿. 드래그 앤 드롭 AI 워크플로우 빌더. 더 나은 문서. 개발자가 템플릿을 공유하고 판매할 수 있는 커뮤니티 마켓플레이스.',
        transition: '컷',
      },
      {
        duration: '4:40-5:00',
        shot: '창업자, 진심 어린 미소',
        onScreenText: 'ai-empire-steel.vercel.app — 무료 체험',
        narration: 'SaaS를 만들고 보일러플레이트에 지쳤다면 AI Empire를 체험하세요. 무료 티어, 카드 불필요, 설명란에 링크. 시청해 주셔서 감사합니다. 다음에 만나요.',
        transition: '로고로 페이드',
      },
    ],
    cta: '무료 체험 — 설명란의 링크',
    music: '영감을 주는 앰비언트, 점차 고조',
    targetAudience: '개발자, 창업자, 빌드인퍼블릭 커뮤니티',
  },
}
