import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-pt-01',
    title: 'AI Empire — Lance seu SaaS em 48 horas',
    type: 'product-demo',
    duration: '60s',
    platform: 'YouTube, Site',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: 'Plano amplo: desenvolvedor na mesa, tela do laptop mostrando terminal',
        onScreenText: 'Ainda construindo seu SaaS do zero?',
        narration: 'Construir um SaaS do zero leva meses. E se você pudesse lançar em 48 horas?',
        transition: 'Zoom rápido na tela',
      },
      {
        duration: '0:05-0:15',
        shot: 'Gravação de tela: galeria de templates AI Empire',
        onScreenText: 'AI Empire — Templates SaaS Next.js 14',
        narration: 'Conheça AI Empire. Templates Next.js 14 prontos para produção com APIs de IA, faturamento Stripe e autenticação — tudo pré-construído.',
        transition: 'Deslizar para esquerda',
      },
      {
        duration: '0:15-0:25',
        shot: 'Gravação de tela: clonar template, instalar dependências',
        onScreenText: '1. Clonar → 2. Configurar → 3. Implantar',
        narration: 'Escolha um template. Clone. Adicione sua chave API Groq. Implante no Vercel. Pronto.',
        transition: 'Corte',
      },
      {
        duration: '0:25-0:35',
        shot: 'Tela dividida: código à esquerda, app com chat IA à direita',
        onScreenText: 'Groq AI + Gemini API integrados',
        narration: 'Cada template inclui chat IA com streaming, completions estruturadas e análise de documentos — potencializados por Groq e Gemini.',
        transition: 'Zoom-out',
      },
      {
        duration: '0:35-0:45',
        shot: 'Gravação de tela: dashboard Stripe, configuração de assinaturas',
        onScreenText: 'Faturamento Stripe — Assinaturas, Uso, Portal',
        narration: 'O faturamento Stripe está pré-configurado. Assinaturas, preços por uso, portal do cliente — tudo conectado.',
        transition: 'Fade',
      },
      {
        duration: '0:45-0:55',
        shot: 'Montagem rápida: 6 interfaces de templates',
        onScreenText: '6 Templates · 50+ Componentes · Prontos para produção',
        narration: 'NeuraSaaS, NeuraStore, NeuraBlog, NeuraPortfolio — escolha o que se adapta ao seu produto.',
        transition: 'Corte para CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'Logo AI Empire + URL em fundo escuro',
        onScreenText: 'ai-empire-steel.vercel.app — Teste gratuito',
        narration: 'Comece grátis. Sem cartão de crédito. ai-empire-steel.vercel.app',
        transition: 'Fade de saída',
      },
    ],
    cta: 'Teste grátis em ai-empire-steel.vercel.app',
    music: 'Eletrônica animada, baixo sutil',
    targetAudience: 'Desenvolvedores, hackers independentes, fundadores de SaaS',
  },

  socialAd: {
    id: 'va-pt-01',
    title: 'AI Empire — Pare de programar boilerplate',
    type: 'social-ad',
    duration: '30s',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: 'Close-up: desenvolvedor frustrado, múltiplas abas abertas',
        onScreenText: 'Auth... faturamento... dashboards...',
        narration: '',
        transition: 'Corte duro',
      },
      {
        duration: '0:03-0:08',
        shot: 'Gravação de tela: galeria de templates AI Empire',
        onScreenText: 'Pule o boilerplate',
        narration: '',
        transition: 'Swipe para cima',
      },
      {
        duration: '0:08-0:15',
        shot: 'Gravação de tela: clonar, npm install, servidor iniciado',
        onScreenText: 'Clonar → Instalar → Executar',
        narration: '',
        transition: 'Zoom rápido',
      },
      {
        duration: '0:15-0:22',
        shot: 'Dividido: código à esquerda, bela UI à direita com chat IA',
        onScreenText: 'IA + Stripe + Auth — Pré-construídos',
        narration: '',
        transition: 'Deslizar para esquerda',
      },
      {
        duration: '0:22-0:27',
        shot: 'App implantada no telefone, funcionando perfeitamente',
        onScreenText: 'Lance em 48h, não em 48 dias',
        narration: '',
        transition: 'Corte',
      },
      {
        duration: '0:27-0:30',
        shot: 'Logo AI Empire em fundo gradiente',
        onScreenText: 'Teste gratuito · Sem cartão',
        narration: '',
        transition: 'Fade de saída',
      },
    ],
    cta: 'Link na bio',
    music: 'Track trending animado, ritmo rápido',
    targetAudience: 'Desenvolvedores 18-35 anos, redes sociais',
  },

  tutorial: {
    id: 'vt-pt-01',
    title: 'Crie um Dashboard SaaS com IA em 10 minutos',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: 'Apresentador na câmera, dashboard AI Empire visível atrás',
        onScreenText: 'Dashboard SaaS IA — 10 Min',
        narration: 'Neste vídeo, vou mostrar como criar um dashboard SaaS completo com IA usando os templates da AI Empire. Vamos lá.',
        transition: 'Corte para tela',
      },
      {
        duration: '0:15-0:40',
        shot: 'Gravação de tela: GitHub, clonar repo NeuraDashboard',
        onScreenText: 'Passo 1: Clonar o Template',
        narration: 'Primeiro, vá ao nosso GitHub e clone o template NeuraDashboard. Execute npm install para obter todas as dependências. O template usa Next.js 14, TypeScript e Tailwind — tudo que você precisa.',
        transition: 'Corte',
      },
      {
        duration: '0:40-1:10',
        shot: 'Gravação de tela: configuração .env.local, chaves API, banco de dados',
        onScreenText: 'Passo 2: Configurar o Ambiente',
        narration: 'Adicione suas variáveis de ambiente. Sua chave API Groq vai aqui — obtenha uma grátis em console.groq.com. Configure a URL do banco de dados com Prisma. Conecte Stripe para faturamento. Leva cerca de 3 minutos.',
        transition: 'Corte',
      },
      {
        duration: '1:10-1:40',
        shot: 'Gravação de tela: executando dev server, navegando dashboard',
        onScreenText: 'Passo 3: Personalizar e Construir',
        narration: 'Execute npm run dev e você tem um dashboard completo com gráficos em tempo real, gerenciamento de usuários e análises com IA. Personalize as cores, adicione sua marca, modifique as rotas API — o código é limpo e bem documentado.',
        transition: 'Corte',
      },
      {
        duration: '1:40-1:55',
        shot: 'Gravação de tela: deploy Vercel, app ao vivo no telefone',
        onScreenText: 'Passo 4: Implantar em Produção',
        narration: 'Quando estiver pronto, faça push para GitHub e implante no Vercel. Um clique. Seu dashboard SaaS com IA está no ar. Faturamento Stripe, autenticação e APIs de IA — tudo funcionando.',
        transition: 'Corte para apresentador',
      },
      {
        duration: '1:55-2:00',
        shot: 'Apresentador na câmera, sorrindo',
        onScreenText: 'ai-empire-steel.vercel.app — Teste gratuito',
        narration: 'É isso. Links na descrição. Teste grátis — sem cartão de crédito.',
        transition: 'Fade de saída',
      },
    ],
    cta: 'Links na descrição — Teste grátis',
    music: 'Lo-fi chill, ao fundo',
    targetAudience: 'Desenvolvedores aprendendo desenvolvimento SaaS',
  },

  founderStory: {
    id: 'vf-pt-01',
    title: 'Por que criei AI Empire — História Build-in-Public',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: 'Fundador na mesa, ambiente casual, café na mão',
        onScreenText: 'Construindo AI Empire — Semana 1',
        narration: 'Seis meses atrás eu passava mais tempo configurando webhooks Stripe e fluxos de autenticação do que construindo meu próprio produto. Eu tinha uma ideia para uma ferramenta de IA, mas estava preso no inferno do boilerplate. Foi aí que decidi construir o que eu desejava que existisse.',
        transition: 'Corte',
      },
      {
        duration: '0:20-0:50',
        shot: 'Montagem: programando à noite, xícaras de café, telas de terminal',
        onScreenText: 'O Problema: 80% Boilerplate, 20% Produto',
        narration: 'Todo projeto SaaS começa da mesma forma. Configurar auth. Conectar Stripe. Construir um dashboard. Adicionar uma API IA. Configurar o banco de dados. Quando você começa a construir sua funcionalidade principal, já gastou 3 semanas e muita energia.',
        transition: 'Dissolução cruzada',
      },
      {
        duration: '0:50-1:30',
        shot: 'Gravação de tela: criando o primeiro template NeuraSaaS',
        onScreenText: 'Semana 2: Primeiro Template — NeuraSaaS',
        narration: 'Então comecei a construir templates. Não boilerplate, mas pontos de partida prontos para produção. NeuraSaaS foi o primeiro. Next.js 14, Tailwind, Prisma, Stripe, Groq AI — tudo conectado. Usei para construir meu próprio SaaS em um fim de semana.',
        transition: 'Corte',
      },
      {
        duration: '1:30-2:10',
        shot: 'Gravação de tela: galeria de templates expandindo',
        onScreenText: 'Semana 4: 6 Templates Prontos',
        narration: 'Na semana quatro eu tinha 6 templates. NeuraSaaS para SaaS geral. NeuraStore para e-commerce. NeuraBlog para conteúdo. NeuraPortfolio para mostrar trabalho. Cada um segue os mesmos padrões: TypeScript limpo, tratamento de erros, integração Stripe e APIs IA.',
        transition: 'Corte',
      },
      {
        duration: '2:10-2:50',
        shot: 'Gravação de tela: benchmarks Groq AI, inferência rápida',
        onScreenText: 'A Camada de IA: Groq + Gemini',
        narration: 'A integração de IA é a parte de que mais tenho orgulho. Groq oferece inferência a 500 tokens por segundo — rápido o suficiente para chat em tempo real. Gemini lida com análises complexas. Ambos disponíveis através de uma API unificada.',
        transition: 'Corte',
      },
      {
        duration: '2:50-3:30',
        shot: 'Fundador na câmera, apaixonado',
        onScreenText: 'Dia do lançamento: 500 cadastros',
        narration: 'Lancei AI Empire numa segunda. Postei no Twitter, LinkedIn e Reddit. Na sexta eu tinha 500 cadastros e meus primeiros clientes pagantes. O tier gratuito foi a isca — 100 créditos API, sem cartão.',
        transition: 'Dissolução cruzada',
      },
      {
        duration: '3:30-4:10',
        shot: 'Montagem: depoimentos, screenshots, pagamentos Stripe',
        onScreenText: 'Mês 3: €3.000 MRR',
        narration: 'Três meses depois atingi €3.000 de MRR. Não é dinheiro que muda a vida, mas o suficiente para provar o conceito. O feedback foi incrível. Desenvolvedores economizam semanas de setup.',
        transition: 'Corte',
      },
      {
        duration: '4:10-4:40',
        shot: 'Gravação de tela: roadmap, próximas funcionalidades',
        onScreenText: 'O Que Vem: AI Empire v2.0',
        narration: 'Aqui está o que vem. Mais templates. Um construtor de workflows IA drag-and-drop. Melhor documentação. E um marketplace comunitário onde desenvolvedores podem compartilhar e vender seus próprios templates.',
        transition: 'Corte',
      },
      {
        duration: '4:40-5:00',
        shot: 'Fundador na câmera, sorriso genuíno',
        onScreenText: 'ai-empire-steel.vercel.app — Teste gratuito',
        narration: 'Se você está construindo um SaaS e está cansado do boilerplate, experimente AI Empire. Tier gratuito, sem cartão de crédito, links na descrição. Obrigado por assistir. Nos vemos no próximo.',
        transition: 'Fade para logo',
      },
    ],
    cta: 'Teste grátis — link na descrição',
    music: 'Ambient inspirador, sobe gradualmente',
    targetAudience: 'Desenvolvedores, fundadores, comunidade build-in-public',
  },
}
