import type { VideoScriptsByLanguage } from './index'

export const videoScripts: VideoScriptsByLanguage = {
  productDemo: {
    id: 'vd-zh-01',
    title: 'AI Empire — 48小时内上线你的SaaS',
    type: 'product-demo',
    duration: '60秒',
    platform: 'YouTube、网站',
    scenes: [
      {
        duration: '0:00-0:05',
        shot: '广角镜头：开发者在办公桌前，笔记本屏幕显示终端',
        onScreenText: '还在从零构建你的SaaS？',
        narration: '从零构建SaaS需要数月时间。如果48小时内就能上线呢？',
        transition: '快速缩放到屏幕',
      },
      {
        duration: '0:05-0:15',
        shot: '屏幕录制：AI Empire模板库',
        onScreenText: 'AI Empire — Next.js 14 SaaS模板',
        narration: '认识AI Empire。内置AI API、Stripe支付和认证的Next.js 14生产级模板。',
        transition: '向左滑动',
      },
      {
        duration: '0:15-0:25',
        shot: '屏幕录制：克隆模板、安装依赖',
        onScreenText: '1. 克隆 → 2. 配置 → 3. 部署',
        narration: '选择一个模板。克隆它。添加你的Groq API密钥。部署到Vercel。完成。',
        transition: '剪切',
      },
      {
        duration: '0:25-0:35',
        shot: '分屏：左侧代码，右侧AI聊天应用',
        onScreenText: '内置 Groq AI + Gemini API',
        narration: '每个模板都包含流式AI聊天、结构化补全和文档分析——由Groq和Gemini驱动。',
        transition: '缩小',
      },
      {
        duration: '0:35-0:45',
        shot: '屏幕录制：Stripe仪表板、订阅设置',
        onScreenText: 'Stripe支付 — 订阅、用量、门户',
        narration: 'Stripe支付已预配置。订阅、按用量计费、客户门户——全部连接就绪。',
        transition: '淡入淡出',
      },
      {
        duration: '0:45-0:55',
        shot: '快速蒙太奇：6个模板UI界面',
        onScreenText: '6个模板 · 50+组件 · 生产就绪',
        narration: 'NeuraSaaS、NeuraStore、NeuraBlog、NeuraPortfolio——选择适合你产品的那个。',
        transition: '切换到CTA',
      },
      {
        duration: '0:55-1:00',
        shot: 'AI Empire标志+URL（深色背景）',
        onScreenText: 'ai-empire-steel.vercel.app — 免费试用',
        narration: '免费开始。无需信用卡。ai-empire-steel.vercel.app',
        transition: '淡出',
      },
    ],
    cta: '在 ai-empire-steel.vercel.app 免费试用',
    music: '轻快电子乐，低沉贝斯',
    targetAudience: '开发者、独立黑客、SaaS创始人',
  },

  socialAd: {
    id: 'va-zh-01',
    title: 'AI Empire — 别再写样板代码了',
    type: 'social-ad',
    duration: '30秒',
    platform: 'Instagram Reels, TikTok',
    scenes: [
      {
        duration: '0:00-0:03',
        shot: '特写：沮丧的开发者，多个标签页打开',
        onScreenText: 'Auth...支付...仪表板...',
        narration: '',
        transition: '硬切',
      },
      {
        duration: '0:03-0:08',
        shot: '屏幕录制：AI Empire模板库',
        onScreenText: '跳过样板代码',
        narration: '',
        transition: '向上滑动',
      },
      {
        duration: '0:08-0:15',
        shot: '屏幕录制：克隆、npm install、服务器启动',
        onScreenText: '克隆 → 安装 → 运行',
        narration: '',
        transition: '快速缩放',
      },
      {
        duration: '0:15-0:22',
        shot: '分屏：左侧代码，右侧精美UI带AI聊天',
        onScreenText: 'AI + Stripe + Auth — 预置',
        narration: '',
        transition: '向左滑动',
      },
      {
        duration: '0:22-0:27',
        shot: '应用部署在手机上，完美运行',
        onScreenText: '48小时上线，不是48天',
        narration: '',
        transition: '剪切',
      },
      {
        duration: '0:27-0:30',
        shot: 'AI Empire标志（渐变背景）',
        onScreenText: '免费试用 · 无需信用卡',
        narration: '',
        transition: '淡出',
      },
    ],
    cta: '个人主页链接',
    music: '热门快节奏曲目',
    targetAudience: '18-35岁开发者，社交媒体',
  },

  tutorial: {
    id: 'vt-zh-01',
    title: '10分钟构建AI SaaS仪表板',
    type: 'tutorial',
    duration: '2:00',
    platform: 'YouTube',
    scenes: [
      {
        duration: '0:00-0:15',
        shot: '主持人面对镜头，背景是AI Empire仪表板',
        onScreenText: 'AI SaaS仪表板 — 10分钟',
        narration: '在这个视频中，我将展示如何使用AI Empire模板构建一个完整的AI驱动SaaS仪表板。开始吧。',
        transition: '切换到屏幕',
      },
      {
        duration: '0:15-0:40',
        shot: '屏幕录制：GitHub，克隆NeuraDashboard仓库',
        onScreenText: '步骤1：克隆模板',
        narration: '首先，前往我们的GitHub克隆NeuraDashboard模板。运行npm install获取所有依赖。模板使用Next.js 14、TypeScript和Tailwind。',
        transition: '剪切',
      },
      {
        duration: '0:40-1:10',
        shot: '屏幕录制：.env.local设置、API密钥、数据库',
        onScreenText: '步骤2：配置环境',
        narration: '添加环境变量。Groq API密钥放这里——在console.groq.com免费获取。用Prisma配置数据库URL。连接Stripe进行支付。大约3分钟完成。',
        transition: '剪切',
      },
      {
        duration: '1:10-1:40',
        shot: '屏幕录制：运行dev server，浏览仪表板',
        onScreenText: '步骤3：自定义和构建',
        narration: '运行npm run dev，你就有了一个完整的仪表板，包含实时图表、用户管理和AI分析。自定义颜色，添加品牌，修改API路由——代码干净且文档完善。',
        transition: '剪切',
      },
      {
        duration: '1:40-1:55',
        shot: '屏幕录制：Vercel部署，手机上应用运行',
        onScreenText: '步骤4：部署到生产环境',
        narration: '准备就绪后，推送到GitHub并在Vercel上部署。一键完成。你的AI SaaS仪表板上线了。Stripe支付、认证和AI API——全部正常运行。',
        transition: '切换到主持人',
      },
      {
        duration: '1:55-2:00',
        shot: '主持人面对镜头，微笑',
        onScreenText: 'ai-empire-steel.vercel.app — 免费试用',
        narration: '就是这样。链接在描述中。免费试用——无需信用卡。',
        transition: '淡出',
      },
    ],
    cta: '描述中的链接 — 免费试用',
    music: 'Lo-fi chill，背景',
    targetAudience: '学习SaaS开发的开发者',
  },

  founderStory: {
    id: 'vf-zh-01',
    title: '为什么我构建了AI Empire — Build-in-Public故事',
    type: 'founder-story',
    duration: '5:00',
    platform: 'YouTube, LinkedIn',
    scenes: [
      {
        duration: '0:00-0:20',
        shot: '创始人在办公桌前，休闲环境，手里拿着咖啡',
        onScreenText: '构建AI Empire — 第1周',
        narration: '六个月前，我花在设置Stripe webhook和认证流程上的时间比构建自己的产品还多。我有一个AI工具的想法，但被困在样板代码地狱里。于是我决定构建我所希望存在的东西。',
        transition: '剪切',
      },
      {
        duration: '0:20-0:50',
        shot: '蒙太奇：深夜编码、咖啡杯、终端屏幕',
        onScreenText: '问题：80%样板代码，20%产品',
        narration: '每个SaaS项目都以同样的方式开始。设置认证。连接Stripe。构建仪表板。添加AI API。配置数据库。当你开始构建核心功能时，已经花了3周和大量精力。',
        transition: '交叉溶解',
      },
      {
        duration: '0:50-1:30',
        shot: '屏幕录制：创建第一个NeuraSaaS模板',
        onScreenText: '第2周：第一个模板 — NeuraSaaS',
        narration: '于是我开始构建模板。不是样板代码，而是生产就绪的起点。NeuraSaaS是第一个。Next.js 14、Tailwind、Prisma、Stripe、Groq AI——全部连接。我用它在一个周末构建了自己的SaaS。',
        transition: '剪切',
      },
      {
        duration: '1:30-2:10',
        shot: '屏幕录制：模板库扩展',
        onScreenText: '第4周：6个模板就绪',
        narration: '到第四周，我有了6个模板。NeuraSaaS用于通用SaaS。NeuraStore用于电商。NeuraBlog用于内容。NeuraPortfolio用于展示作品。每个都遵循相同的模式：干净的TypeScript、错误处理、Stripe集成和AI API。',
        transition: '剪切',
      },
      {
        duration: '2:10-2:50',
        shot: '屏幕录制：Groq AI基准测试、快速推理',
        onScreenText: 'AI层：Groq + Gemini',
        narration: 'AI集成是我最自豪的部分。Groq提供每秒500个token的推理——足以支持实时聊天。Gemini处理复杂分析。两者都通过统一API提供。',
        transition: '剪切',
      },
      {
        duration: '2:50-3:30',
        shot: '创始人面对镜头，充满激情',
        onScreenText: '发布日：500注册',
        narration: '我在周一发布了AI Empire。在Twitter、LinkedIn和Reddit上发帖。到周五，我有了500个注册和首批付费客户。免费层级是诱饵——100个API积分，无需信用卡。',
        transition: '交叉溶解',
      },
      {
        duration: '3:30-4:10',
        shot: '蒙太奇：用户证言、仪表板截图、Stripe支付',
        onScreenText: '第3个月：€3,000 MRR',
        narration: '三个月后，我达到了€3,000 MRR。不是改变生活的钱，但足以证明概念。反馈令人难以置信。开发者们节省了数周的设置时间。',
        transition: '剪切',
      },
      {
        duration: '4:10-4:40',
        shot: '屏幕录制：路线图、即将到来的功能',
        onScreenText: '接下来：AI Empire v2.0',
        narration: '即将推出：更多模板、拖拽式AI工作流构建器、更好的文档，以及开发者可以分享和销售自己模板的社区市场。',
        transition: '剪切',
      },
      {
        duration: '4:40-5:00',
        shot: '创始人面对镜头，真诚微笑',
        onScreenText: 'ai-empire-steel.vercel.app — 免费试用',
        narration: '如果你在构建SaaS并且厌倦了样板代码，试试AI Empire。免费层级，无需信用卡，链接在描述中。感谢观看。下次见。',
        transition: '淡出到标志',
      },
    ],
    cta: '免费试用 — 描述中的链接',
    music: '激励型氛围音乐，逐渐增强',
    targetAudience: '开发者、创始人、Build-in-Public社区',
  },
}
